force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Expansion</fullName>
            </value>
            <value>
                <fullName>Cross-sell (New product)</fullName>
            </value>
            <value>
                <fullName>Contract Path Change</fullName>
            </value>
            <value>
                <fullName>Price Increase</fullName>
            </value>
            <value>
                <fullName>Hunting License</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

manifest/objects/Q_Item__c.object
<CustomObject>
    <fields>
        <fullName>Dst__c</fullName>
        <label>Destination</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ItemKey__c</fullName>
        <externalId>true</externalId>
        <label>Item Key</label>
        <length>36</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Q Items</relationshipLabel>
        <relationshipName>Q_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parser_Name__c</fullName>
        <label>Parser Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payload__c</fullName>
        <label>Payload</label>
        <length>65536</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <length>65536</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Processed with error</fullName>
                </value>
                <value>
                    <fullName>Processed without error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Teladoc_Account_Id__c</fullName>
        <label>Teladoc Account Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Teladoc_Opp_Id__c</fullName>
        <label>Teladoc Opp Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Outgoing</fullName>
                </value>
                <value>
                    <fullName>Incoming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isSync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isSync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>src__c</fullName>
        <label>Source</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>Q Item</label>
    <nameField>
        <label>Q Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Q Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/classes/MsgBusErrorReporting_Test.cls
@isTest
private class MsgBusErrorReporting_Test {
  @TestSetup
  public static void setup() {
    Account umrAcct = TestDataFactory.createUMR();
    Account accObj = TestDataFactory.createAccountUMR();
    Opportunity oppObj2 = TestDataFactory.createOpportunity(accObj.Id);
    oppObj2.Message_Bus_Error__c = true;
    insert oppObj2;

    String result = '{  "Parsing_Errors" : {    "OPPORTUNITY_LEVEL_BAD_DATA" : "Opportunity OwnerId : User Id is invalid in LVN."  },  "DML_Errors" : { }}';
    Q_Item__c qitem = new Q_Item__c(
      Opportunity__c = oppObj2.Id,
      Teladoc_Opp_Id__c = oppObj2.Id,
      Teladoc_Account_Id__c = '22222',
      Payload__c = '{}',
      ItemKey__c = 'DE3C1C1E-5197-18DB-9539-270433A22EB4',
      Status__c = 'Processed with error',
      Src__c = 'TDH',
      Dst__c = 'LVN',
      Parser_Name__c = 'parserName',
      Type__c = 'Outgoing',
      isSync__c = true,
      Result__c = result
    );
    insert qitem;
  }

  static testMethod void getQItem() {
    Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
    system.assertEquals(
      1,
      MsgBusErrorReporting_Controller.getQItem(
          opp.Id,
          system.today(),
          system.today().addDays(3),
          null
        )
        .size()
    );
  }
}