force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityLineItem__c/OpportunityLineItem__c.object-meta.xml
<CustomObject>
    <label>Opportunity Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OpportunityLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityLineItem__c/fields/Enrollment_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Percentage__c</fullName>
    <label>Enrollment Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>OpportunityId</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Opportunity Products</relationshipLabel>
    <relationshipName>LGVO_OpportunityProducts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/OpportunityProductName__c.field-meta.xml
<CustomField>
    <fullName>OpportunityProductName__c</fullName>
    <label>Opportunity Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Pricing_Structure__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Structure__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Updating Pricing Structure will overwrite the Sales Price, Estimated At-Risk PPPM, Estimated Partner Admin Fees, and Up Front Per Member fields.</inlineHelpText>
    <label>Pricing Structure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Pricing Structure is not available.</errorMessage>
        <filterItems>
            <field>Pricing_Structure__c.Program__c</field>
            <operation>equals</operation>
            <valueField>$Source.Program_ID__c</valueField>
        </filterItems>
        <filterItems>
            <field>Pricing_Structure__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book_ID__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Pricing_Structure__c</referenceTo>
    <relationshipLabel>Opportunity Program</relationshipLabel>
    <relationshipName>LVGO_Opportunity_Program</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product2Id</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunity LineItems</relationshipLabel>
    <relationshipName>OpportunityLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Program_Family__c.field-meta.xml
<CustomField>
    <fullName>Program_Family__c</fullName>
    <formula>TEXT(Product2__r.Family)</formula>
    <label>Program Family</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricing_Structure__c/Pricing_Structure__c.object-meta.xml
<CustomObject>
    <label>LV Pricing Structure</label>
    <nameField>
        <label>Pricing Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Pricing Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/classes/LVGO__OppLineEnrollmentPercentUpdateBatch.cls
global class OppLineEnrollmentPercentUpdateBatch implements Database.Batchable<sObject>, Database.Stateful {
    global String finalstr;
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('SELECT Id, Enrollment_Percentage__c, Opportunity__c,Program_Family__c, Pricing_Structure__c, Product2__c, OpportunityProductName__c FROM ' +
                                        'OpportunityLineItem__c');
    }
    
    global void execute(Database.BatchableContext bc, List<OpportunityLineItem__c> scope){
        List<OpportunityLineItem__c> oppLines = OppLineEnrollmentPercentService.updateEnrollmentPercentage(scope);
        if (oppLines.size() > 0) {
            Database.SaveResult[] srList = Database.update(oppLines, false);
            finalstr = 'Id'+','+'Status Code'+','+'Message'+'\n';           
            for(Integer i=0; i < srList.size(); i++) {
                String recordString = '';
                if (srList.get(i).isSuccess()) {
                    recordString = oppLines.get(i).Id+','+ 'success'+ ',' + 'success' +'\n';
                }
                else {
                    // Operation failed, so get all errors                
                    for(Database.Error err : srList.get(i).getErrors()) {
                        recordString = oppLines.get(i).Id+','+ err.getStatusCode()+ ',' + err.getMessage()+'\n';   
                    }
                }
                finalstr = finalstr + recordString;
            }            
        }
    }
    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setSubject('Batch process has been completed');
        mail.setPlainTextBody('Batch Process has completed. Please see the attached file for any errors');
        String[] toAddresses = new list<string> {'saikalyani.jangala@teladochealth.com','virinchi.bairisetty@teladochealth.com'};
        mail.setToAddresses(toAddresses);
        Messaging.EmailFileAttachment csvAttc = new Messaging.EmailFileAttachment();
        Blob csvBlob = Blob.valueOf(finalstr);
        csvAttc.setFileName('Exceptions.csv');
        csvAttc.setBody(csvBlob);
        
        mail.setFileAttachments(new Messaging.EmailFileAttachment[]{csvAttc});
        Messaging.sendEmail(new Messaging.Email[] { mail });
    }
}