objects/APTS_integration_Allowed__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Switch for callouts happening</description>
    <fields>
        <fullName>APTS_Allow_Callout__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow Callout</label>
        <type>Checkbox</type>
    </fields>
    <label>Integration_Allowed</label>
</CustomObject>

manifest/objects/Apttus__AgreementLineItem__c.object
<CustomObject>
    <description>Represents a product or service line item associated with an agreement</description>
    <fields>
        <fullName>APTS_Fee_Type__c</fullName>
        <label>Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PEPM</fullName>
                </value>
                <value>
                    <fullName>PMPM</fullName>
                </value>
                <value>
                    <fullName>PPPM</fullName>
                </value>
                <value>
                    <fullName>Flat Rate</fullName>
                </value>
                <value>
                    <fullName>Case Rate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Membership_Fee__c</fullName>
        <label>Membership Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_ProductName__c</fullName>
        <inlineHelpText>Opportunity Product name</inlineHelpText>
        <label>Product</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>APTS_Product_Family__c</fullName>
        <formula>TEXT( Apttus__ProductId__r.Family )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Family</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus__AgreementId__c</fullName>
        <description>ID of the associated agreement</description>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Agreement Line Items</relationshipLabel>
        <relationshipName>AgreementLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Agreement Line Item</label>
    <nameField>
        <displayFormat>AL-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The link to the account record to identify the external party to this agreement</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N50000001Xl0UEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__Contract_End_Date__c</fullName>
        <description>The end date for this agreement</description>
        <label>Agreement End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus__Contract_Start_Date__c</fullName>
        <description>The effective date of the agreement</description>
        <label>Agreement Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus__Related_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>R00N50000001Xl0FEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__Status_Category__c</fullName>
        <description>The higher level state of the agreement – In Authoring, In Effect, Expired, etc.  These are Apttus reserved values and cannot be changed.</description>
        <label>Status Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>In Authoring</fullName>
                </value>
                <value>
                    <fullName>In Signatures</fullName>
                </value>
                <value>
                    <fullName>In Filing</fullName>
                </value>
                <value>
                    <fullName>In Effect</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Import</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Request</fullName>
                </value>
                <value>
                    <fullName>Request Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted Request</fullName>
                </value>
                <value>
                    <fullName>Contract Ops Review</fullName>
                </value>
                <value>
                    <fullName>Approved Request</fullName>
                </value>
                <value>
                    <fullName>Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Author Contract</fullName>
                </value>
                <value>
                    <fullName>Language Approval</fullName>
                </value>
                <value>
                    <fullName>Language Approved</fullName>
                </value>
                <value>
                    <fullName>Internal Signatures</fullName>
                </value>
                <value>
                    <fullName>Other Party Signatures</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Being Renewed</fullName>
                </value>
                <value>
                    <fullName>In Renewal</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Being Terminated</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>In Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Reconciled</fullName>
                </value>
                <value>
                    <fullName>Internal Review</fullName>
                </value>
                <value>
                    <fullName>Other Party Review</fullName>
                </value>
                <value>
                    <fullName>Signature Declined</fullName>
                </value>
                <value>
                    <fullName>Ready for Signatures</fullName>
                </value>
                <value>
                    <fullName>Fully Signed</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Performance_Guarantees__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Performance Guarantees</relationshipLabel>
        <relationshipName>Performance_Guarantees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expert Medical Service</fullName>
                </value>
                <value>
                    <fullName>Virtual Care Services</fullName>
                </value>
                <value>
                    <fullName>Chronic Care Management</fullName>
                </value>
                <value>
                    <fullName>Livongo Services</fullName>
                    <isActive>false</isActive>
                    <label>Livongo Services</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Performance Guarantees</label>
    <nameField>
        <displayFormat>PG - {0000}</displayFormat>
        <label>Performance Guarantee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Performance Guarantees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Product_Family__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Product Families</relationshipLabel>
        <relationshipName>Product_Families</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Family</label>
    <nameField>
        <displayFormat>PF-{0000}</displayFormat>
        <label>Product Family</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/classes/PerformanceGuaranteeControllerTest.cls
@isTest
private class PerformanceGuaranteeControllerTest {
    
    @testSetup   
     static void setup() {

         //create an account record
         Account accObj = TestDataFactoryForPG_Test.createAccount('TestAccount');        

         Id pricebookId = Test.getStandardPricebookId();
        //create an opportunity record
        Opportunity oppObj2 = TestDataFactoryForPG_Test.createOpportunity(accObj.Id);
        oppObj2.Name = 'TestAmendmentOpp2';
        oppObj2.Pricebook2Id = pricebookId;
        oppObj2.LeadSource = 'Sales';
        insert oppObj2;
        
        Opportunity oppObj = TestDataFactoryForPG_Test.createOpportunity(accObj.Id);
        oppObj.Name = 'TestAmendmentOpp';
        oppObj.Pricebook2Id = pricebookId;
        oppObj.LeadSource = 'Sales';
        insert oppObj;


        // create Aggrment record
       
      
         
        APTS_integration_Allowed__c obj = new APTS_integration_Allowed__c(Name = 'Integration_Allowed', APTS_Allow_Callout__c = true);
        insert obj;
         
        Opportunity opp = [SELECT Id,accountId FROM Opportunity WHERE Name = 'TestAmendmentOpp'];
         
        /*Account acc = [SELECT Id FROM Account WHERE Name = 'TestAccount'];*/
         
        //Apttus__APTS_Agreement__c agreement = TestDataFactoryForPG_Test.createApttusAPTSAgreement(acc.Id, opp.Id);
        //insert agreement;


        Apttus__APTS_Agreement__c agreementRecord = new Apttus__APTS_Agreement__c();
        agreementRecord.Apttus__Account__c = opp.accountId;
        agreementRecord.Name = 'Test Agreement';
        agreementRecord.OwnerId = userinfo.getUserId();
        agreementRecord.Apttus__Contract_Start_Date__c = system.today();
        agreementRecord.Apttus__Contract_End_Date__c = System.Today() + 5;
        agreementRecord.Apttus__Related_Opportunity__c = opp.Id;
        agreementRecord.Apttus__Status_Category__c = 'Request';
        agreementRecord.Apttus__Status__c = 'Request';
        insert agreementRecord;


        // create Aggrment Line Item record
        List<Apttus__AgreementLineItem__c> lineItems = new List<Apttus__AgreementLineItem__c>();
        for(Integer i =1; i<6; i++){
            Apttus__AgreementLineItem__c  lineItemRecord = new Apttus__AgreementLineItem__c();          
            lineItemRecord.APTS_ProductName__c = 'APTS_Product_Family__c';
            lineItemRecord.APTS_Membership_Fee__c = 10.00 * i;
            lineItemRecord.APTS_Fee_Type__c = 'PEPM';
            lineItemRecord.Apttus__AgreementId__c = agreementRecord.ID;

            lineItems.add(lineItemRecord);
        }

        Insert lineItems;

        // create PG Records;
        List<Performance_Guarantees__c> pgItems = new List<Performance_Guarantees__c>();
        for(Integer i =1; i<4; i++){
            Performance_Guarantees__c pgRecord = new Performance_Guarantees__c();
            pgRecord.Product_Family__c ='Expert Medical Service';
            pgRecord.Guarantee_Type__c ='Call Center';
            pgRecord.PG_Status__c = 'Active';
            pgRecord.Credit_or_Refund__c ='Credit';
            pgRecord.Calculation_Method__c ='Average';
            pgRecord.Evaluation_Frequency__c ='Semi-Annually';
            pgRecord.PG_Level__c = 'Book of Business';
            pgRecord.Guarantee_Description__c ='none';
            pgRecord.Agreement__c = agreementRecord.ID;     
            pgRecord.Fees_at_Risk_Type__c ='PPPM';
            pgRecord.PG_Start_Date__c = Date.newInstance(2022, 10, 20);
            pgRecord.Fees_At_Risk_Payment_Term__c =4567;
            pgRecord.Fees_At_Risk_Payment_Timeframe__c =654;
            pgRecord.Fees_At_Risk_Unit__c ='Dollar';
            pgRecord.PG_Initial_Measurement_Term_Recurring__c='Yes';
            pgRecord.PG_Initial_Measurement_Term__c=4;
            pgRecord.Source_Document__c = '2334';
            pgItems.add(pgRecord);
        }
        Insert pgItems;
    }
   
    @isTest
    static void testgetLineitems()
    {
        Test.startTest();
        Apttus__APTS_Agreement__c agrmt = [SELECT ID,Name FROM Apttus__APTS_Agreement__c WHERE OwnerId = :userinfo.getUserId() limit 1];         
        List<Apttus__AgreementLineItem__c> agrLineitems = PerformanceGuaranteeController.getLineItems(agrmt.ID);
        Test.stopTest();   
        System.assertEquals(5, agrLineitems.size(), 'Should return list of Agreement Line Item for selected Agreement');
    }

    @isTest
    static void testgetPGAssociationrecords()
    {
         Test.startTest();
        Apttus__APTS_Agreement__c agrmt = [SELECT ID FROM Apttus__APTS_Agreement__c WHERE OwnerId = :userinfo.getUserId() limit 1]; 
        List<Apttus__AgreementLineItem__c> agrLineitems = PerformanceGuaranteeController.getLineItems(agrmt.ID);
        List<Performance_Guarantees__c> pgList = PerformanceGuaranteeController.getPGRecords(agrmt.ID);

        List<PerformanceGuaranteeController.PGWrapper> pGWrapperList = new  List<PerformanceGuaranteeController.PGWrapper> ();
        PerformanceGuaranteeController.PGWrapper record = new PerformanceGuaranteeController.PGWrapper();
        record.Id = pgList[0].Id;
        record.LineItemId =  agrLineitems[0].Id;
        pGWrapperList.add(record);
        

        PerformanceGuaranteeController.PGWrapper record2 = new PerformanceGuaranteeController.PGWrapper();
        record2.Id = pgList[1].Id;
        record2.LineItemId = agrLineitems[1].Id;
        pGWrapperList.add(record2);    
        
        PerformanceGuaranteeController.updateRecords(pGWrapperList);        
        
        List<PG_Association__c> records =PerformanceGuaranteeController.getPGAssociationRecords(agrmt.Id);

        System.assertEquals(2, records.size(), 'Should return list of PG Association object for selected Agreement');        
        Test.stopTest();  
    }

    @isTest
    static void testgetPGrecords()
    {
        Test.startTest();
        Apttus__APTS_Agreement__c agrmt = [SELECT ID FROM Apttus__APTS_Agreement__c WHERE OwnerId = :userinfo.getUserId() limit 1];        
        List<Performance_Guarantees__c> pgList = PerformanceGuaranteeController.getPGRecords(agrmt.ID);
        Test.stopTest();    
        System.assertEquals(3, pgList.size(), 'Should return list of Performance Guarantees Item for selected Agreement');        
        
    }

    @isTest
    static void testgetupdaterecords()
    {
        
        Test.startTest();
        Apttus__APTS_Agreement__c agrmt = [SELECT ID FROM Apttus__APTS_Agreement__c WHERE OwnerId = :userinfo.getUserId() limit 1]; 
        List<Apttus__AgreementLineItem__c> agrLineitems = PerformanceGuaranteeController.getLineItems(agrmt.ID);
        List<Performance_Guarantees__c> pgList = PerformanceGuaranteeController.getPGRecords(agrmt.ID);

        List<PerformanceGuaranteeController.PGWrapper> pGWrapperList = new  List<PerformanceGuaranteeController.PGWrapper> ();
        PerformanceGuaranteeController.PGWrapper record = new PerformanceGuaranteeController.PGWrapper();
        record.Id = pgList[0].Id;
        record.LineItemId =  agrLineitems[0].Id;
        pGWrapperList.add(record);
        

        PerformanceGuaranteeController.PGWrapper record2 = new PerformanceGuaranteeController.PGWrapper();
        record2.Id = pgList[1].Id;
        record2.LineItemId = agrLineitems[1].Id;
        pGWrapperList.add(record2);     
       

        PerformanceGuaranteeController.updateRecords(pGWrapperList);

        List<PG_Association__c> records = [SELECT ID, Agreement_Line_Item__c,Performance_Guarantee__c FROM PG_Association__c 
                                            WHERE Agreement_Line_Item__c IN (Select Id FROM Apttus__AgreementLineItem__c 
                                            WHERE Apttus__AgreementId__c= :agrmt.Id)];   
        
        
             
        System.assertEquals(2, records.size(), 'Should create record of PG Association object for selected Agreement line item and Performance Guarantee record.');        
        Test.stopTest();   
    }

    @isTest
    static void testupdateandDeleterecords()
    {
        
        Test.startTest();
        Apttus__APTS_Agreement__c agrmt = [SELECT ID FROM Apttus__APTS_Agreement__c WHERE OwnerId = :userinfo.getUserId() limit 1]; 
        List<Apttus__AgreementLineItem__c> agrLineitems = PerformanceGuaranteeController.getLineItems(agrmt.ID);
        List<Performance_Guarantees__c> pgList = PerformanceGuaranteeController.getPGRecords(agrmt.ID);

        
        
        List<PerformanceGuaranteeController.PGWrapper> pGWrapperList = new  List<PerformanceGuaranteeController.PGWrapper> ();
        PerformanceGuaranteeController.PGWrapper record = new PerformanceGuaranteeController.PGWrapper();
        record.Id = pgList[0].Id;
        record.LineItemId =  agrLineitems[0].Id;
        pGWrapperList.add(record);
        

        PerformanceGuaranteeController.PGWrapper record2 = new PerformanceGuaranteeController.PGWrapper();
        record2.Id = pgList[1].Id;
        record2.LineItemId = agrLineitems[1].Id;
        pGWrapperList.add(record2);       

        PerformanceGuaranteeController.updateRecords(pGWrapperList);       
        
        
        List<PerformanceGuaranteeController.PGWrapper> pGWrapperList2 = new  List<PerformanceGuaranteeController.PGWrapper> ();
        record = new PerformanceGuaranteeController.PGWrapper();
        record.Id =  pgList[2].Id;
        record.LineItemId = agrLineitems[2].Id;
        pGWrapperList2.add(record);
       

        List<String>existingPGIds = new List<String>();
        for (PG_Association__c pgRecord: [SELECT ID, Agreement_Line_Item__c,Performance_Guarantee__c FROM PG_Association__c 
                        WHERE Agreement_Line_Item__c IN (Select Id FROM Apttus__AgreementLineItem__c 
                        WHERE Apttus__AgreementId__c= :agrmt.Id)]){
                            
           existingPGIds.add(pgRecord.Id);

        }       

        List<PG_Association__c> records = PerformanceGuaranteeController.insertAndDeleteRecords(pGWrapperList2,existingPGIds,agrmt.ID);        
        
       
        System.assertEquals(1, records.size(), 'Should return updated list of PG Association object for newly created record of PG_Association object only.');        
        Test.stopTest();   
    }
    
}