force-app/main/default/objects/Estimated_Enrollment_Mapping__mdt/Estimated_Enrollment_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Estimated Enrollment Mapping</label>
    <pluralLabel>Estimated Enrollment Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Estimated_Enrollment_Mapping__mdt/fields/Estimated_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Enrollment__c</fullName>
    <label>Estimated Enrollment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Estimated_Enrollment_Mapping__mdt/fields/Opp_Owner_Role__c.field-meta.xml
<CustomField>
    <fullName>Opp_Owner_Role__c</fullName>
    <label>Opp Owner Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Estimated_Enrollment_Mapping__mdt/fields/Program_Family__c.field-meta.xml
<CustomField>
    <fullName>Program_Family__c</fullName>
    <label>Program Family</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Opp_Owner_Role__c.field-meta.xml
<CustomField>
    <fullName>Opp_Owner_Role__c</fullName>
    <formula>Owner__r.UserRole.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opp Owner Role</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TD</fullName>
            </value>
            <value>
                <fullName>LV</fullName>
            </value>
            <value>
                <fullName>ITH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/OpportunityLineItem__c.object-meta.xml
<CustomObject>
    <label>Opportunity Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OpportunityLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityLineItem__c/fields/Currently_Enrolled_Members__c.field-meta.xml
<CustomField>
    <fullName>Currently_Enrolled_Members__c</fullName>
    <description>JENGA:1589: WP Transition. This field will have the existing enrolled program participants</description>
    <inlineHelpText>Please refer to the ipos daily snapshot email.</inlineHelpText>
    <label>Currently Enrolled Members</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Enrollment_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Percentage__c</fullName>
    <label>Enrollment Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Estimated_At_Risk_PPPM__c.field-meta.xml
<CustomField>
    <fullName>Estimated_At_Risk_PPPM__c</fullName>
    <label>Estimated At-Risk PPPM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Estimated_Partner_Admin_Fees__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Partner_Admin_Fees__c</fullName>
    <label>Estimated Partner Admin Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Gross_Program_ARR_Copy__c.field-meta.xml
<CustomField>
    <fullName>Gross_Program_ARR_Copy__c</fullName>
    <label>Gross Program ARR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Incremental_Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Incremental_Sales_Price__c</fullName>
    <description>JENGA-1589: WP transitions, this field will capture the the delta between the new sales price and standalone sales price</description>
    <inlineHelpText>The delta between the new WP Sales Price and Standalone Sales Price</inlineHelpText>
    <label>Incremental Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>OpportunityId</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Opportunity Products</relationshipLabel>
    <relationshipName>LGVO_OpportunityProducts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Opportunity_Owner_Role__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Owner_Role__c</fullName>
    <label>Opportunity Owner Role</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/PMPM__c.field-meta.xml
<CustomField>
    <fullName>PMPM__c</fullName>
    <description>JENGA-1357</description>
    <inlineHelpText>Only used for BH 2.0 product</inlineHelpText>
    <label>PMPM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Pricing_Structure__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Structure__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Updating Pricing Structure will overwrite the Sales Price, Estimated At-Risk PPPM, Estimated Partner Admin Fees, and Up Front Per Member fields.</inlineHelpText>
    <label>Pricing Structure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Pricing Structure is not available.</errorMessage>
        <filterItems>
            <field>Pricing_Structure__c.Program__c</field>
            <operation>equals</operation>
            <valueField>$Source.Program_ID__c</valueField>
        </filterItems>
        <filterItems>
            <field>Pricing_Structure__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book_ID__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Pricing_Structure__c</referenceTo>
    <relationshipLabel>Opportunity Program</relationshipLabel>
    <relationshipName>LVGO_Opportunity_Program</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product2Id</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunity LineItems</relationshipLabel>
    <relationshipName>OpportunityLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Product_Participants__c.field-meta.xml
<CustomField>
    <fullName>Product_Participants__c</fullName>
    <inlineHelpText>For new opportunities, enter estimated recruitables or rPwX. For renewals, enter enrolled members.</inlineHelpText>
    <label>Program Participants (rPwX or Enrolled)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Program_ARR_Copy__c.field-meta.xml
<CustomField>
    <fullName>Program_ARR_Copy__c</fullName>
    <description>Workflow field update will populate this field with the value from Program ARR; this field will then be rolled up into value on Opportunity</description>
    <label>Net Program ARR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Program_Family__c.field-meta.xml
<CustomField>
    <fullName>Program_Family__c</fullName>
    <formula>TEXT(Product2__r.Family)</formula>
    <label>Program Family</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Program Term</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <inlineHelpText>For all Whole Person opportunities, input the Whole Person PPPM for the solution. Do not input the incremental sales price. To capture a Whole Person upgrade populate the section below titled &apos;Whole Person Upgrade</inlineHelpText>
    <label>Sales Price</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Up_Front_Per_Member__c.field-meta.xml
<CustomField>
    <fullName>Up_Front_Per_Member__c</fullName>
    <label>Up Front Per Member</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Year_2_Price__c.field-meta.xml
<CustomField>
    <fullName>Year_2_Price__c</fullName>
    <description>This is the year 2+ maintenance price. This currently only applies to Weight Management/Diabetes Prevention</description>
    <inlineHelpText>This is the year 2+ maintenance price. This currently only applies to Weight Management/Diabetes Prevention. You need to enter this in order for the DPP ROI model to properly populate</inlineHelpText>
    <label>Year 2+ Price</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Pricing_Structure__c/Pricing_Structure__c.object-meta.xml
<CustomObject>
    <label>LV Pricing Structure</label>
    <nameField>
        <label>Pricing Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Pricing Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pricing_Structure__c/fields/Estimated_At_Risk_PPPM__c.field-meta.xml
<CustomField>
    <fullName>Estimated_At_Risk_PPPM__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Estimated At-Risk PPPM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Pricing_Structure__c/fields/Estimated_Partner_Admin_Fees__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Partner_Admin_Fees__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Estimated Partner Admin Fees</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Pricing_Structure__c/fields/PMPM__c.field-meta.xml
<CustomField>
    <fullName>PMPM__c</fullName>
    <description>JENGA-1357</description>
    <inlineHelpText>Only used for BH 2.0 product</inlineHelpText>
    <label>PMPM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Pricing_Structure__c/fields/Up_Front_Per_Member__c.field-meta.xml
<CustomField>
    <fullName>Up_Front_Per_Member__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Up Front Per Member</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

manifest/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Enrollment_Percentage__c</fullName>
        <description>This field is used to set the default Enrollment Percentage for Livongo Products. It gets used in PriceRule to calculate the Quantity.</description>
        <label>Direct Enrollment Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OppLineRevCalcHelper.cls
public class OppLineRevCalcHelper {
    public static final String DIABETES_W_CKD_AWARE_VARIANT = System.Label.Diabetes_w_CKD_Aware_Variant;
    public static final String HYPERTENSION_W_CKD_AWARE_VARIANT = System.Label.Hypertension_w_CKD_Aware_Variant;
    public static final String MYSTRENGTH = System.Label.myStrength;
    public static final String MYSTRENGTH_COMPLETE = System.Label.myStrength_Complete;
    
    public static void calculateArrFieldValues(List < OpportunityLineItem__c> lstOP) {
        if (lstOP != null && !lstOP.isEmpty()) {
            Set <String> setPS = new Set <String> ();
            Set <String> setP = new Set <String> ();
            Set <Id> setOppId = new Set <Id> ();
            
            for (OpportunityLineItem__c obj: lstOP) {
                if (obj.Pricing_Structure__c != null) {
                    setPS.add(obj.Pricing_Structure__c);
                }
                if (obj.Product2__c != null) {
                    setP.add(obj.Product2__c);
                }
                setOppId.add(obj.Opportunity__c);
            }
            Map <Id,Opportunity__c> oppMap = new Map<Id,Opportunity__c>([SELECT Id, Name, Source__c, Opp_Owner_Role__c FROM Opportunity__c WHERE 
                                                                   Id IN : setOppId]);
            Map <Id, Pricing_Structure__c> mapPS = new Map <Id, Pricing_Structure__c> ([Select Id, Name From Pricing_Structure__c Where Id IN: setPS]);
            Map <Id, Product2> mapP = new Map <Id, Product2> ([Select Id, Name From Product2 Where Id IN: setP]);
            
            //Getting Estimated Enrollment Percentage from custom metadata
            List <Estimated_Enrollment_Mapping__mdt> estimatedEnrollementMDTList = [SELECT Id, MasterLabel, DeveloperName, Opp_Owner_Role__c, Estimated_Enrollment__c, Program_Family__c FROM Estimated_Enrollment_Mapping__mdt];
            Map <String, Estimated_Enrollment_Mapping__mdt> estimatedEnrollementMDTMap = new Map < String, Estimated_Enrollment_Mapping__mdt > ();
            if (!estimatedEnrollementMDTList.isEmpty()) {
                for (Estimated_Enrollment_Mapping__mdt objMDA: estimatedEnrollementMDTList) {
                    estimatedEnrollementMDTMap.put(objMDA.Opp_Owner_Role__c + '' + objMDA.Program_Family__c, objMDA);
                }
            }
            
            for (OpportunityLineItem__c obj: lstOP) {
                //obj.Name = oppMap.get(obj.Opportunity__c).Name + ' ' + mapP.get(obj.Product2__c).Name;
                String oppName = mapP.get(obj.Product2__c).Name + ' ' + oppMap.get(obj.Opportunity__c).Name;
                obj.Name = oppName.length() > 80 ? oppName.substring(0,80):oppName;
                if(oppMap.get(obj.Opportunity__c).Source__c != 'TD') {
                    
                    Decimal Product_Participants = obj.Product_Participants__c != null ? obj.Product_Participants__c : 0.00;
                    Decimal Estimated_At_Risk_PPPM = obj.Estimated_At_Risk_PPPM__c != null ? obj.Estimated_At_Risk_PPPM__c : 0.00;
                    Decimal Estimated_Partner_Admin_Fees = obj.Estimated_Partner_Admin_Fees__c != null ? obj.Estimated_Partner_Admin_Fees__c : 0.00;
                    Decimal Up_Front_Per_Member = obj.Up_Front_Per_Member__c != null ? obj.Up_Front_Per_Member__c : 0.00;
                    Decimal Program_Term = obj.Quantity__c;
                    Decimal Currently_Enrolled_Members = obj.Currently_Enrolled_Members__c != null ? obj.Currently_Enrolled_Members__c : 0.00;
                    Decimal Incremental_Sales_Price = obj.Incremental_Sales_Price__c != null ? obj.Incremental_Sales_Price__c : 0.00;
                    Decimal Year_2_Price = obj.Year_2_Price__c != null ? obj.Year_2_Price__c : 0.00;
                    Decimal PMPM = obj.PMPM__c != null ? obj.PMPM__c : 0.00;
                    Decimal UnitPrice = obj.UnitPrice__c != null ? obj.UnitPrice__c : 0.00;
                    
                    //Identifying if the Owner Role is Commercial or Other
                    String Opp_Owner_Role = obj.Opportunity__c != null && oppMap.get(obj.Opportunity__c).Opp_Owner_Role__c != null && oppMap.get(obj.Opportunity__c).Opp_Owner_Role__c.contains('Commercial') ? 'Commercial' : 'Other';
                    //Creating unique key using  Opp_Owner_Role__c and Program_Family__c
                    String EstimatedEnrollmentKey = (Opp_Owner_Role != null && Opp_Owner_Role.contains('Commercial') ? 'Commercial' : 'Other')+obj.Program_Family__c;
                    //Assigning Estimated Enrollment Percentages from custom metadata    
                    Decimal EstimatedEnrollmentPercent = estimatedEnrollementMDTMap.containsKey(EstimatedEnrollmentKey) && estimatedEnrollementMDTMap.get(EstimatedEnrollmentKey).Estimated_Enrollment__c != null ? estimatedEnrollementMDTMap.get(EstimatedEnrollmentKey).Estimated_Enrollment__c : 1;
                    //Assigning Estimated Enrollment Percentages for Diabetes and Hypertension w/ CKD Aware Variants
                    if (mapP.containsKey(obj.Product2__c) && mapP.get(obj.Product2__c).Name.equals(DIABETES_W_CKD_AWARE_VARIANT) || mapP.get(obj.Product2__c).Name.equals(HYPERTENSION_W_CKD_AWARE_VARIANT)) {
                        EstimatedEnrollmentPercent = 0.20;
                    }
                    //obj.Opportunity_Owner_Role__c = mapOpp.get(obj.OpportunityId).Owner.UserRole.Name;
                    Boolean myStrengthCalculation = false;
                    
                    /*START***MYSTRENGTH AND MYSTRENGTH COMPLETE CALCULATION***/
                    
                    if (obj.Pricing_Structure__c != null && obj.Product2__c != null &&
                        (mapPS.get(obj.Pricing_Structure__c).Name.containsIgnoreCase('PPPM') || mapPS.get(obj.Pricing_Structure__c).Name.containsIgnoreCase('PEPM') 
                         || mapPS.get(obj.Pricing_Structure__c).Name.containsIgnoreCase('PMPM')) && mapP.containsKey(obj.Product2__c) && 
                        (mapP.get(obj.Product2__c).Name.equals(MYSTRENGTH) || mapP.get(obj.Product2__c).Name.equals(MYSTRENGTH_COMPLETE))) {
                            myStrengthCalculation = true;
                        }
                    if (myStrengthCalculation) {
                        Decimal myStrengthEstimatedEnrollmentRate = obj.Pricing_Structure__c != null && (mapPS.get(obj.Pricing_Structure__c).Name.containsIgnoreCase('DTE') ||
                                                                                                         mapPS.get(obj.Pricing_Structure__c).Name.containsIgnoreCase('Health Plan ASO Opt IN') || 
                                                                                                         mapPS.get(obj.Pricing_Structure__c).Name.containsIgnoreCase('Broker') ||
                                                                                                         mapPS.get(obj.Pricing_Structure__c).Name.containsIgnoreCase('TPA/Reseller')) ? 0.05 :
                        obj.Pricing_Structure__c != null && (mapPS.get(obj.Pricing_Structure__c).Name.containsIgnoreCase('Health Plan FI') ||
                                                             mapPS.get(obj.Pricing_Structure__c).Name.containsIgnoreCase('Health Plan ASO Opt Out')) ? 0.025 : 1;
                        
                        
                        /***MYSTRENGTH OR MYSTRENGTH COMPLETE FOR PPPM BASED CALCULATION***/
                        if(obj.Pricing_Structure__c != null && mapPS.get(obj.Pricing_Structure__c).Name.containsIgnoreCase('PPPM')) {
                            if(mapP.get(obj.Product2__c).Name.equals(MYSTRENGTH) || mapP.get(obj.Product2__c).Name.equals(MYSTRENGTH_COMPLETE)) {
                                obj.Gross_Program_ARR_Copy__c = UnitPrice  * myStrengthEstimatedEnrollmentRate * Product_Participants * 6;
                                obj.Program_ARR_Copy__c = Product_Participants * myStrengthEstimatedEnrollmentRate * ((UnitPrice - (Estimated_At_Risk_PPPM + Estimated_Partner_Admin_Fees)) * 6 + Up_Front_Per_Member);                               
                            }
                            EstimatedEnrollmentPercent =  myStrengthEstimatedEnrollmentRate;
                        }
                        /***MYSTRENGTH OR MYSTRENGTH COMPLETE FOR PEPM OR PMPM BASED CALCULATION***/
                        else if(obj.Pricing_Structure__c != null && mapPS.get(obj.Pricing_Structure__c).Name.containsIgnoreCase('PEPM') || mapPS.get(obj.Pricing_Structure__c).Name.containsIgnoreCase('PMPM')) {
                            if(mapP.get(obj.Product2__c).Name.equals(MYSTRENGTH) || mapP.get(obj.Product2__c).Name.equals(MYSTRENGTH_COMPLETE)) {
                                obj.Gross_Program_ARR_Copy__c = UnitPrice * Product_Participants * 12;
                                obj.Program_ARR_Copy__c = Product_Participants * ((UnitPrice - (Estimated_At_Risk_PPPM + Estimated_Partner_Admin_Fees)) * 12 + Up_Front_Per_Member);
                            }
                           EstimatedEnrollmentPercent =  1;
                        }
                    }
                    /*END***MYSTRENGTH AND MYSTRENGTH COMPLETE CALCULATION***/
                    
                    /*START***ALL OTHER PROGRAMS CALCULATION***/
                    
                    else if (obj.Program_Family__c != null && !myStrengthCalculation) {
                        
                        /*START***GROSS PROGRAM ARR***/
                        
                        /***PEPM BASED CALCULATION***/
                        if (obj.Pricing_Structure__c != null && mapPS.get(obj.Pricing_Structure__c).Name.containsIgnoreCase('PEPM')) {
                            obj.Gross_Program_ARR_Copy__c = Product_Participants * UnitPrice * 12 + Currently_Enrolled_Members * Incremental_Sales_Price * 12;
                        }
                        /***MILESTONE BASED CALCULATION***/
                        else if ((obj.Program_Family__c == LABEL.Weight_Management || obj.Program_Family__c == LABEL.Prediabetes) && UnitPrice == 1) {
                            obj.Gross_Program_ARR_Copy__c = 608 * EstimatedEnrollmentPercent * Product_Participants;
                        }
                        /***STANDARD PPPM BASED CALCULATION***/
                        else if (obj.Program_Family__c != Label.Behavioral_Health){
                            obj.Gross_Program_ARR_Copy__c = EstimatedEnrollmentPercent * Product_Participants * UnitPrice * 12 
                                + Currently_Enrolled_Members * Incremental_Sales_Price * 12;
                        }
                        /***BH and DEFALUT CALCULATION***/
                        else {
                            obj.Gross_Program_ARR_Copy__c = Product_Participants * UnitPrice * 12 + Product_Participants * 0.02 * PMPM * 6;
                        }
                        /*END***GROSS PROGRAM ARR***/
                        
                        /*START***NET PROGRAM ARR***/
                        
                        /***PEPM BASED CALCULATION***/
                        if (obj.Pricing_Structure__c != null && mapPS.get(obj.Pricing_Structure__c).Name.containsIgnoreCase('PEPM')) {
                            obj.Program_ARR_Copy__c = Product_Participants * ((UnitPrice - (Estimated_At_Risk_PPPM + Estimated_Partner_Admin_Fees)) * 12 + Up_Front_Per_Member) 
                                + Currently_Enrolled_Members * Incremental_Sales_Price * 12;
                        }
                        /***MILESTONE BASED CALCULATION***/
                        else if ((obj.Program_Family__c == LABEL.Weight_Management || obj.Program_Family__c == LABEL.Prediabetes) && UnitPrice == 1) {
                            obj.Program_ARR_Copy__c = 608 * EstimatedEnrollmentPercent * Product_Participants;
                        }
                        /***STANDARD PPPM BASED CALCULATION***/
                        else if (obj.Program_Family__c != Label.Behavioral_Health){
                            obj.Program_ARR_Copy__c = EstimatedEnrollmentPercent * Product_Participants * ((UnitPrice - (Estimated_At_Risk_PPPM + Estimated_Partner_Admin_Fees)) * 12 + Up_Front_Per_Member) 
                                + Currently_Enrolled_Members * Incremental_Sales_Price * 12;
                        }
                        /***BH and DEFALUT CALCULATION***/
                        else {
                            obj.Program_ARR_Copy__c = Product_Participants * ((UnitPrice - (Estimated_At_Risk_PPPM + Estimated_Partner_Admin_Fees)) * 12 + Up_Front_Per_Member) 
                                + Product_Participants * 0.02 * PMPM * 6;
                        }
                        
                        /*END***NET PROGRAM ARR***/
                    }
                    if (obj.Pricing_Structure__c != null && mapPS.get(obj.Pricing_Structure__c).Name.containsIgnoreCase('PEPM') && obj.Program_Family__c != null && !myStrengthCalculation) {
                        EstimatedEnrollmentPercent = 1;  
                    }
                    obj.Enrollment_Percentage__c = EstimatedEnrollmentPercent * 100;       
                    /*END***ALL OTHER PROGRAMS CALCULATION****************/
                }
            }
        }
    } 
}