force-app/main/default/objects/Estimated_Enrollment_Mapping__mdt/Estimated_Enrollment_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Estimated Enrollment Mapping</label>
    <pluralLabel>Estimated Enrollment Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Estimated_Enrollment_Mapping__mdt/fields/Estimated_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Enrollment__c</fullName>
    <label>Estimated Enrollment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Estimated_Enrollment_Mapping__mdt/fields/Opp_Owner_Role__c.field-meta.xml
<CustomField>
    <fullName>Opp_Owner_Role__c</fullName>
    <label>Opp Owner Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Estimated_Enrollment_Mapping__mdt/fields/Program_Family__c.field-meta.xml
<CustomField>
    <fullName>Program_Family__c</fullName>
    <label>Program Family</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Opp_Owner_Role__c.field-meta.xml
<CustomField>
    <fullName>Opp_Owner_Role__c</fullName>
    <formula>Owner__r.UserRole.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opp Owner Role</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TD</fullName>
            </value>
            <value>
                <fullName>LV</fullName>
            </value>
            <value>
                <fullName>ITH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/OpportunityLineItem__c.object-meta.xml
<CustomObject>
    <label>Opportunity Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OpportunityLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityLineItem__c/fields/Enrollment_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Percentage__c</fullName>
    <label>Enrollment Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>OpportunityId</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Opportunity Products</relationshipLabel>
    <relationshipName>LGVO_OpportunityProducts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Pricing_Structure__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Structure__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Updating Pricing Structure will overwrite the Sales Price, Estimated At-Risk PPPM, Estimated Partner Admin Fees, and Up Front Per Member fields.</inlineHelpText>
    <label>Pricing Structure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Pricing Structure is not available.</errorMessage>
        <filterItems>
            <field>Pricing_Structure__c.Program__c</field>
            <operation>equals</operation>
            <valueField>$Source.Program_ID__c</valueField>
        </filterItems>
        <filterItems>
            <field>Pricing_Structure__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book_ID__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Pricing_Structure__c</referenceTo>
    <relationshipLabel>Opportunity Program</relationshipLabel>
    <relationshipName>LVGO_Opportunity_Program</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product2Id</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunity LineItems</relationshipLabel>
    <relationshipName>OpportunityLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Program_Family__c.field-meta.xml
<CustomField>
    <fullName>Program_Family__c</fullName>
    <formula>TEXT(Product2__r.Family)</formula>
    <label>Program Family</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricing_Structure__c/Pricing_Structure__c.object-meta.xml
<CustomObject>
    <label>LV Pricing Structure</label>
    <nameField>
        <label>Pricing Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Pricing Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Enrollment_Percentage__c</fullName>
        <description>This field is used to set the default Enrollment Percentage for Livongo Products. It gets used in PriceRule to calculate the Quantity.</description>
        <label>Direct Enrollment Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/classes/LVGO__OppLineEnrollmentPercentService.cls
public class OppLineEnrollmentPercentService {
    
    public static final String DIABETES_W_CKD_AWARE_VARIANT = System.Label.Diabetes_w_CKD_Aware_Variant;
    public static final String HYPERTENSION_W_CKD_AWARE_VARIANT = System.Label.Hypertension_w_CKD_Aware_Variant;
    public static final String MYSTRENGTH = System.Label.myStrength;
    public static final String MYSTRENGTH_COMPLETE = System.Label.myStrength_Complete;
    
    public static List<OpportunityLineItem__c> updateEnrollmentPercentage(List<OpportunityLineItem__c> oppLineList) {
        System.debug('HERe::'+ oppLineList);
        Set<String> pricingStructureIds = new Set<String>();
        Set<String> productIds = new Set<String>();
        Set<String> OppIds = new Set<String>();
        List<OpportunityLineItem__c> oppLineItemsTobeUpdated = new List<OpportunityLineItem__c>();
        
        for(OpportunityLineItem__c oppLine : OppLineList) {
            if(oppLine.Pricing_Structure__c != null) {
                pricingStructureIds.add(oppLine.Pricing_Structure__c);
            }
            if(oppLine.Product2__c != null) {
                productIds.add(oppLine.Product2__c);
            }
            oppIds.add(OppLine.Opportunity__c);
        }
        
        Map <Id,Opportunity__c> oppMap = new Map<Id,Opportunity__c>([SELECT Id, Source__c, Opp_Owner_Role__c FROM Opportunity__c WHERE Id IN : OppIds]);
        Map <Id, Pricing_Structure__c> pricingStructureMap = new Map <Id, Pricing_Structure__c> ([Select Id, Name From Pricing_Structure__c Where Id IN: pricingStructureIds]);
        Map <Id, Product2> productMap = new Map <Id, Product2> ([Select Id, Name From Product2 Where Id IN: productIds]);
        
        List <Estimated_Enrollment_Mapping__mdt> estimatedEnrollementMDTList = [SELECT Id, MasterLabel, DeveloperName, Opp_Owner_Role__c, Estimated_Enrollment__c, Program_Family__c FROM Estimated_Enrollment_Mapping__mdt];
        Map <String, Estimated_Enrollment_Mapping__mdt> estimatedEnrollementMDTMap = new Map < String, Estimated_Enrollment_Mapping__mdt > ();
        if (!estimatedEnrollementMDTList.isEmpty()) {
            for (Estimated_Enrollment_Mapping__mdt enr : estimatedEnrollementMDTList) {
                estimatedEnrollementMDTMap.put(enr.Opp_Owner_Role__c + '' + enr.Program_Family__c, enr);
            }
        }
        for (OpportunityLineItem__c oli: oppLineList) {
            if(oppMap.get(oli.Opportunity__c).Source__c != 'TD') {
                
                String Opp_Owner_Role = oli.Opportunity__c != null && oppMap.get(oli.Opportunity__c).Opp_Owner_Role__c != null && oppMap.get(oli.Opportunity__c).Opp_Owner_Role__c.contains('Commercial') ? 'Commercial' : 'Other';
                
                String EstimatedEnrollmentKey = (Opp_Owner_Role != null && Opp_Owner_Role.contains('Commercial') ? 'Commercial' : 'Other')+oli.Program_Family__c;
               
                Decimal EstimatedEnrollmentPercent = estimatedEnrollementMDTMap.containsKey(EstimatedEnrollmentKey) && estimatedEnrollementMDTMap.get(EstimatedEnrollmentKey).Estimated_Enrollment__c != null ? estimatedEnrollementMDTMap.get(EstimatedEnrollmentKey).Estimated_Enrollment__c : 1;
            
                if (productMap.containsKey(oli.Product2__c) && productMap.get(oli.Product2__c).Name.equals(DIABETES_W_CKD_AWARE_VARIANT) || productMap.get(oli.Product2__c).Name.equals(HYPERTENSION_W_CKD_AWARE_VARIANT)) {
                    EstimatedEnrollmentPercent = 0.20;
                }
                
                Boolean myStrengthCalculation = false;
                
                if (oli.Pricing_Structure__c != null && oli.Product2__c != null &&
                    (pricingStructureMap.get(oli.Pricing_Structure__c).Name.containsIgnoreCase('PPPM') || pricingStructureMap.get(oli.Pricing_Structure__c).Name.containsIgnoreCase('PEPM') 
                     || pricingStructureMap.get(oli.Pricing_Structure__c).Name.containsIgnoreCase('PMPM')) && productMap.containsKey(oli.Product2__c) && 
                    (productMap.get(oli.Product2__c).Name.equals(MYSTRENGTH) || productMap.get(oli.Product2__c).Name.equals(MYSTRENGTH_COMPLETE))) {
                        myStrengthCalculation = true;
                    }
                if (myStrengthCalculation) {
                    EstimatedEnrollmentPercent = oli.Pricing_Structure__c != null && (pricingStructureMap.get(oli.Pricing_Structure__c).Name.containsIgnoreCase('DTE') ||
                                                                                      pricingStructureMap.get(oli.Pricing_Structure__c).Name.containsIgnoreCase('Health Plan ASO Opt IN') || 
                                                                                      pricingStructureMap.get(oli.Pricing_Structure__c).Name.containsIgnoreCase('Broker') ||
                                                                                      pricingStructureMap.get(oli.Pricing_Structure__c).Name.containsIgnoreCase('TPA/Reseller')) ? 0.05 :
                    oli.Pricing_Structure__c != null && (pricingStructureMap.get(oli.Pricing_Structure__c).Name.containsIgnoreCase('Health Plan FI') ||
                                                         pricingStructureMap.get(oli.Pricing_Structure__c).Name.containsIgnoreCase('Health Plan ASO Opt Out')) ? 0.025 : 0;
                }
                else if (oli.Pricing_Structure__c != null && pricingStructureMap.get(oli.Pricing_Structure__c).Name.containsIgnoreCase('PEPM') && oli.Program_Family__c != null && !myStrengthCalculation) {
                    EstimatedEnrollmentPercent = 1;  
                }
                oli.Enrollment_Percentage__c = EstimatedEnrollmentPercent * 100;
                oppLineItemsTobeUpdated.add(oli);
            }
        }
        return oppLineItemsTobeUpdated;
    }
}