force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>LV Contract</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Edits Controlled - Financially Material -  Flows to Redshift</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>LVGO_Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Account_Client_Overview__c.field-meta.xml
<CustomField>
    <fullName>Account_Client_Overview__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account (Client Overview)</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Client Overviews</relationshipLabel>
    <relationshipName>ClientOverviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Client_Able_to_Send_HR_Comms__c.field-meta.xml
<CustomField>
    <fullName>Client_Able_to_Send_HR_Comms__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enrollment Marketing - Client Overview</description>
    <label>Client Able to Send HR Comms?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Disclaimer__c.field-meta.xml
<CustomField>
    <fullName>Disclaimer__c</fullName>
    <description>This is the disclaimer used for Enrollment Marketing purposes across multiple programs.</description>
    <label>Disclaimer</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Eligibility_Sentence__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Sentence__c</fullName>
    <description>This is the Eligibility Sentence used for Enrollment Marketing across multiple programs.</description>
    <label>Eligibility Sentence</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Employee_Title__c.field-meta.xml
<CustomField>
    <fullName>Employee_Title__c</fullName>
    <label>Employee Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/General_Eligibility_Sentence__c.field-meta.xml
<CustomField>
    <fullName>General_Eligibility_Sentence__c</fullName>
    <description>General Eligibility Sentence information to be used on assets promoting Whole Person solutions or multiple standalone programs</description>
    <inlineHelpText>General Eligibility Sentence information to be used on assets promoting Whole Person solutions or multiple standalone programs</inlineHelpText>
    <label>General Eligibility Sentence</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Marketing_Name__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Name__c</fullName>
    <description>Integrated with Redshift</description>
    <inlineHelpText>Integrated with Redshift</inlineHelpText>
    <label>Marketing Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/OE_Month_End__c.field-meta.xml
<CustomField>
    <fullName>OE_Month_End__c</fullName>
    <label>OE Month End</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Months</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/OE_Month_Start__c.field-meta.xml
<CustomField>
    <fullName>OE_Month_Start__c</fullName>
    <label>OE Month Start</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Months</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/OE_Period_Length__c.field-meta.xml
<CustomField>
    <fullName>OE_Period_Length__c</fullName>
    <label>OE Period Length</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 Week</fullName>
            </value>
            <value>
                <fullName>2 Weeks</fullName>
            </value>
            <value>
                <fullName>3 Weeks</fullName>
            </value>
            <value>
                <fullName>4 Weeks</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <description>Integrated with NetSuite and Redshift</description>
    <inlineHelpText>Integrated with NetSuite and Redshift</inlineHelpText>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Diabetes</fullName>
            </value>
            <value>
                <fullName>Hypertension</fullName>
            </value>
            <value>
                <fullName>Prediabetes</fullName>
            </value>
            <value>
                <fullName>Weight Management</fullName>
            </value>
            <value>
                <fullName>Behavioral Health</fullName>
            </value>
            <value>
                <fullName>Chronic Kidney Disease</fullName>
            </value>
            <value>
                <fullName>Heart Failure</fullName>
            </value>
            <value>
                <fullName>A1C Test Kits</fullName>
            </value>
            <value>
                <fullName>A1C Test Kits - Results</fullName>
            </value>
            <value>
                <fullName>Diabetes Deviceflex</fullName>
            </value>
            <value>
                <fullName>Home Kidney Testing Program</fullName>
            </value>
            <value>
                <fullName>Home Kidney Testing Program - Results</fullName>
            </value>
            <value>
                <fullName>Advanced Weight Management (Select Populations)</fullName>
            </value>
            <value>
                <fullName>Comprehensive Weight Care (Select Populations)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Edits Controlled - Financially Material -  Flows to Redshift</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Activate</fullName>
            </value>
            <value>
                <fullName>Re-Activate</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>In Approval Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/recordTypes/Client_Overview.recordType-meta.xml
<RecordType>
    <fullName>Client_Overview</fullName>
    <active>true</active>
    <description>Represents the overarching Program Agreement between Livongo and Client + the Client&apos;s specific operational processes</description>
    <label>Client Overview</label>
</RecordType>

force-app/main/default/objects/Contract__c/recordTypes/Program_Overview.recordType-meta.xml
<RecordType>
    <fullName>Program_Overview</fullName>
    <active>true</active>
    <description>Represents the program-specific, Program Schedule under a Program Agreement + the Client&apos;s specific operational processes regarding the program</description>
    <label>Program Overview</label>
</RecordType>

force-app/main/default/objects/Enrollment_Communications_Survey__c/Enrollment_Communications_Survey__c.object-meta.xml
<CustomObject>
    <label>LV Enrollment Communications Survey</label>
    <nameField>
        <displayFormat>Survey-{0000}</displayFormat>
        <label>Enrollment Communications Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LV Enrollment Communications Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Communications_Survey__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Enrollment Communications Surveys</relationshipLabel>
    <relationshipName>Enrollment_Communications_Surveys</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment_Communications_Survey__c/fields/Client_able_to_send_HR_comms__c.field-meta.xml
<CustomField>
    <fullName>Client_able_to_send_HR_comms__c</fullName>
    <label>Client able to send HR comms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment_Communications_Survey__c/fields/Diabetes_Eligibility_Sentence__c.field-meta.xml
<CustomField>
    <fullName>Diabetes_Eligibility_Sentence__c</fullName>
    <label>Diabetes Eligibility Sentence</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Enrollment_Communications_Survey__c/fields/Disclaimer__c.field-meta.xml
<CustomField>
    <fullName>Disclaimer__c</fullName>
    <label>Disclaimer</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Enrollment_Communications_Survey__c/fields/Employee_Title__c.field-meta.xml
<CustomField>
    <fullName>Employee_Title__c</fullName>
    <label>Employee Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment_Communications_Survey__c/fields/General_Eligibility_Sentence__c.field-meta.xml
<CustomField>
    <fullName>General_Eligibility_Sentence__c</fullName>
    <label>General Eligibility Sentence</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Enrollment_Communications_Survey__c/fields/Livongo_Programs__c.field-meta.xml
<CustomField>
    <fullName>Livongo_Programs__c</fullName>
    <label>Livongo Programs</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Diabetes</fullName>
            </value>
            <value>
                <fullName>Hypertension</fullName>
            </value>
            <value>
                <fullName>Prediabetes</fullName>
            </value>
            <value>
                <fullName>Weight Management</fullName>
            </value>
            <value>
                <fullName>Behavioral Health</fullName>
                <label>myStrength</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment_Communications_Survey__c/fields/Marketing_Name__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Name__c</fullName>
    <label>Marketing Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment_Communications_Survey__c/fields/OE_Month_End__c.field-meta.xml
<CustomField>
    <fullName>OE_Month_End__c</fullName>
    <label>OE Month End</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>January</fullName>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment_Communications_Survey__c/fields/OE_Month_Start__c.field-meta.xml
<CustomField>
    <fullName>OE_Month_Start__c</fullName>
    <label>OE Month Start</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>January</fullName>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment_Communications_Survey__c/fields/OE_Period_Length__c.field-meta.xml
<CustomField>
    <fullName>OE_Period_Length__c</fullName>
    <label>OE Period Length</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 week</fullName>
            </value>
            <value>
                <fullName>2 weeks</fullName>
            </value>
            <value>
                <fullName>3 weeks</fullName>
            </value>
            <value>
                <fullName>4 weeks</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EnrollmentCommunicationsTriggerHandler.cls
public class EnrollmentCommunicationsTriggerHandler {
    
    public static final String DIABETES = System.Label.Diabetes;
    public static final String HYPERTENSION = System.Label.Hypertension;
    public static final String PREDIABETES = System.Label.Prediabetes;
    public static final String WEIGHTMGMT = System.Label.Weight_Management;
    public static final String BEHAVIORAL_HEALTH = System.Label.Behavioral_Health;
    public static final Id CO_RECORDTYPEID = Schema.SObjectType.Contract__c.getRecordTypeInfosByDeveloperName().get('Client_Overview').getRecordTypeId();
    public static final Id PO_RECORDTYPEID = Schema.SObjectType.Contract__c.getRecordTypeInfosByDeveloperName().get('Program_Overview').getRecordTypeId();
    
    Public Static void updateContractrecords(List<Enrollment_Communications_Survey__c> enrolSurveyList){
        //Retrieving the Account Ids//
        Set<Id> accountIds = new Set<Id>();
        for(Enrollment_Communications_Survey__c survey:enrolSurveyList){
            accountIds.add(survey.account__c);
        }
        
        List<Id> contactRecordTypes = new List<Id>{CO_RECORDTYPEID,PO_RECORDTYPEID};

        //Fetching the respective Contracts//
        List<contract__c> contractList = [SELECT Id,Account__c, RecordTypeId, Status__c, Program_Name__c, Eligibility_Sentence__c,
                                       Account_Client_Overview__c,  Marketing_Name__c, General_Eligibility_Sentence__c,
                                       Employee_Title__c, Client_Able_to_Send_HR_Comms__c, OE_Month_Start__c,
                                       OE_Month_End__c, OE_Period_Length__c, Disclaimer__c from contract__c
                                       WHERE Account__c In :accountIds and RecordTypeId IN :contactRecordTypes and 
                                       (Status__c =: 'Active' or Status__c =: 'Draft')];
        
        List<contract__c> contractListToUpdate = New List<contract__c>();
        for(Enrollment_Communications_Survey__c enrollComms : enrolSurveyList){            
            for(Contract__c co : contractList){
                if(co.Account__c == enrollComms.Account__c){   //Checking for Client Overview records//                    
                    if(co.recordTypeId  == co_RecordTypeId){
                        co.Marketing_Name__c =enrollComms.Marketing_Name__c ;
                        co.Employee_Title__c =enrollComms.Employee_Title__c ;
                        co.OE_Month_Start__c = enrollComms.OE_Month_Start__c ;
                        co.OE_Month_End__c = enrollComms.OE_Month_End__c;
                        co.OE_Period_Length__c = enrollComms.OE_Period_Length__c ;
                        if(enrollComms.Client_able_to_send_HR_comms__c == 'Yes'){
                            co.Client_Able_to_Send_HR_Comms__c = true;
                            if(string.isNotBlank(enrollComms.General_Eligibility_Sentence__c)){
                                co.General_Eligibility_Sentence__c = enrollComms.General_Eligibility_Sentence__c; 
                                co.Disclaimer__c = enrollComms.Disclaimer__c;
                            }
                            contractListToUpdate.add(co);
                        }
                    }
                    else if(co.recordTypeId  == po_RecordTypeId) {  //Checking for Program Overview records//
                        if((co.Account__c  == enrollComms.Account__c)&&(enrollComms.Livongo_programs__c.contains(co.Program_Name__c))){ 
                            co.Disclaimer__c = enrollComms.Disclaimer__c;
                            if(co.Program_Name__c == DIABETES){
                                co.Eligibility_Sentence__c = enrollComms.Diabetes_Eligibility_Sentence__c;                                
                            }
                            else if(co.Program_Name__c == HYPERTENSION){
                                co.Eligibility_Sentence__c = enrollComms.Hypertension_Eligibility_Sentence__c;
                            }
                            else if(co.Program_Name__c == PREDIABETES){
                                co.Eligibility_Sentence__c = enrollComms.Prediabetes_Eligibility_Sentence__c; co.Disclaimer__c = enrollComms.Disclaimer__c;
                            }
                            Else if(co.Program_Name__c == WEIGHTMGMT){
                                co.Eligibility_Sentence__c = enrollComms.Weight_Management_Eligibility_Sentence__c;co.Disclaimer__c = enrollComms.Disclaimer__c;
                            }
                            else if(co.Program_Name__c == BEHAVIORAL_HEALTH){
                                co.Eligibility_Sentence__c = enrollComms.Behavioral_Health_Eligibility_Sentence__c;co.Disclaimer__c = enrollComms.Disclaimer__c;
                            }                               
                        }
                        contractListToUpdate.add(co);
                    }
                }
                try{
                    if(!contractListToUpdate .isEmpty()){
                        update contractListToUpdate;
                    }  
                }catch(DmlException e){
                    system.debug('The Following Exception occured - '+e.getMessage());  
                }
                
            }
        }
    }
}