force-app/main/default/objects/Contact__c/Contact__c.object-meta.xml
<CustomObject>
    <label>LV Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact__c</referenceTo>
    <relationshipName>Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

manifest/objects/Experience_Center_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attended Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Experience Center Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Experience Center Contacts</relationshipLabel>
        <relationshipName>Experience_Center_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Experience_Center_Briefing_Request__c</fullName>
        <label>Experience Center Briefing Request</label>
        <referenceTo>Briefing__c</referenceTo>
        <relationshipLabel>Experience Center Contacts</relationshipLabel>
        <relationshipName>Experience_Center_Contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Experience Center Contact</label>
    <nameField>
        <displayFormat>ECC-{0000}</displayFormat>
        <label>Experience Center Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Experience Center Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/classes/ClientExperienceContactController.cls
public with sharing class ClientExperienceContactController {
  @AuraEnabled
  public static void createExperienceContact(
    Id contactId,
    Id parentId,
    Boolean isAttend
  ) {
    Experience_Center_Contact__c ecc = new Experience_Center_Contact__c();
    ecc.Attendee__c = isAttend;
    ecc.Experience_Center_Briefing_Request__c = parentId;
    ecc.Contact__c = contactId;
    insert ecc;
  }
}