force-app/main/default/objects/Contact__c/Contact__c.object-meta.xml
<CustomObject>
    <label>LV Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact__c</referenceTo>
    <relationshipName>Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

manifest/objects/Mbr_Group__c.object
<CustomObject>
    <fields>
        <fullName>Client_Account__c</fullName>
        <description>Account that the Group is created</description>
        <inlineHelpText>Account that the Group is created</inlineHelpText>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Member Groups</relationshipLabel>
        <relationshipName>Member_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Enter a descriptive Member Group Name.</description>
        <inlineHelpText>Enter a descriptive Member Group Name.</inlineHelpText>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Use this as a backend field to identify the source of member group record</description>
        <inlineHelpText>Use this as a backend field to identify the source of member group record</inlineHelpText>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Data_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Group Status</description>
        <inlineHelpText>Group Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>PENDING</fullName>
                    <default>true</default>
                    <label>PENDING</label>
                </value>
                <value>
                    <fullName>TERMED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Member Group</label>
    <nameField>
        <displayFormat>MG-{00000000}</displayFormat>
        <label>Member Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Mbr_Group_Role__c.object
<CustomObject>
    <fields>
        <fullName>Mbr_Group__c</fullName>
        <description>SF Record name of the Group</description>
        <inlineHelpText>SF Record name of the Group</inlineHelpText>
        <label>Member Group</label>
        <referenceTo>Mbr_Group__c</referenceTo>
        <relationshipLabel>Member Group Roles</relationshipLabel>
        <relationshipName>Member_Group_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role_Type__c</fullName>
        <description>Type of association with Group</description>
        <inlineHelpText>Type of association with Group</inlineHelpText>
        <label>Role Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Fee_Group_Role_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account that is servicing the type of role</description>
        <inlineHelpText>Account that is servicing the type of role</inlineHelpText>
        <label>Source Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Member Group Roles</relationshipLabel>
        <relationshipName>Member_Group_Roles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact that serves the Member Group Role. This contact should be associated to the Source Account</description>
        <inlineHelpText>Contact that serves the Member Group Role. This contact should be associated to the Source Account</inlineHelpText>
        <label>Source Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Source_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Member Group Roles</relationshipLabel>
        <relationshipName>Member_Group_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member Group Role</label>
    <nameField>
        <displayFormat>MGR-{00000000}</displayFormat>
        <label>Member Group Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Group Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Mkt_Site_User__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>MSU Contact to have marketing hub access for this member group</description>
        <inlineHelpText>MSU Contact to have marketing hub access for this member group</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Mkt Site Users</relationshipLabel>
        <relationshipName>Mkt_Site_Users</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mbr_Group__c</fullName>
        <description>SF record name of member group</description>
        <inlineHelpText>SF record name of member group</inlineHelpText>
        <label>Member Group</label>
        <referenceTo>Mbr_Group__c</referenceTo>
        <relationshipLabel>Mkt Site Users</relationshipLabel>
        <relationshipName>Mkt_Site_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Mkt Site User</label>
    <nameField>
        <displayFormat>MSU-{00000000}</displayFormat>
        <label>Mkt Site User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mkt Site Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/globalValueSets/Data_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>HUB</fullName>
        <default>true</default>
        <label>HUB</label>
    </customValue>
    <customValue>
        <fullName>TD</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>LVGO</fullName>
    </customValue>
    <customValue>
        <fullName>GCRM</fullName>
    </customValue>
    <masterLabel>Data Source</masterLabel>
</GlobalValueSet>

manifest/globalValueSets/Fee_Group_Role_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Benefit Sponsor</fullName>
    </customValue>
    <customValue>
        <fullName>Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Contractee</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Payer</fullName>
    </customValue>
    <customValue>
        <fullName>MSU Access</fullName>
    </customValue>
    <masterLabel>Fee Group Role Type</masterLabel>
</GlobalValueSet>

manifest/classes/MSULookup_Tst.cls
@IsTest
public with sharing class MSULookup_Tst {
  public static testMethod void testMSULookup() {
    Account umrAcct = TestDataFactory.createUMR();
    Account aRef = new Account(Export_Id__c = 'TestAcct1234');
    Account a2Ref = new Account(Export_Id__c = 'TestAcct9876');
    Account a = new Account(
      Name = 'BioHorizons Implant Systems, Inc',
      Export_Id__c = 'TestAcct1234',
      Source__c = 'HUB'
    );
    Account a2 = new Account(
      Name = 'Sobobo Implant Systems, Inc',
      Export_Id__c = 'TestAcct9876',
      Source__c = 'HUB'
    );
    Contact tmpCon = new Contact(
      FirstName = 'Mrs',
      LastName = 'User',
      Marketing_Site_Username__c = 'eufbe',
      Email = 'Test.User@teladoc.com',
      Marketing_Site_User__c = true,
      Account = a2Ref,
      Contact_Status__c = 'Active'
    );
    Contact tmpCon2 = new Contact(
      FirstName = 'Mr',
      LastName = 'User2',
      Email = 'Test.User2@teladoc.com',
      Marketing_Site_User__c = true,
      Account = aRef,
      Contact_Status__c = 'Inactive - Deceased'
    );
    Contact tmpCon3 = new Contact(
      FirstName = 'Mr',
      LastName = 'Delme',
      Email = 'Test.User2@teladoc.com',
      Marketing_Site_User__c = true,
      Account = aRef,
      Contact_Status__c = 'Active'
    );
    Contact tmpCon4 = new Contact(
      FirstName = 'Mrs',
      LastName = 'Notanmsu',
      Marketing_Site_Username__c = 'eufbfeefe',
      Email = 'Test.User@teladoc.com',
      Marketing_Site_User__c = false,
      Account = a2Ref,
      Contact_Status__c = 'Active'
    );
    Mbr_Group__c tmpGroup = new Mbr_Group__c(
      Name__c = 'Test Group',
      Client_Account__r = aRef,
      Status__c = 'ACTIVE'
    );
    Mbr_Group__c tmpGroup2 = new Mbr_Group__c(
      Name__c = 'Te2st Group',
      Client_Account__r = a2Ref,
      Status__c = 'ACTIVE'
    );
    Database.insert(
      new List<SObject>{
        a,
        a2,
        tmpCon,
        tmpCon2,
        tmpGroup,
        tmpGroup2,
        tmpCon3,
        tmpCon4
      }
    );

    Mbr_Group_Role__c mgr = new Mbr_Group_Role__c();
    mgr.Mbr_Group__c = tmpGroup.Id;
    mgr.Role_Type__c = 'Payer';
    mgr.Source_Contact__c = tmpCon.Id;
    mgr.Source_Account__c = a2.Id;
    insert mgr;

    delete tmpCon3;
    List<Mkt_Site_User__c> dupeBatch = new List<Mkt_Site_User__c>();
    Mkt_Site_User__c msug = new Mkt_Site_User__c();
    msug.Contact__c = tmpCon2.Id;
    msug.Mbr_Group__c = tmpGroup2.Id;

    try {
      insert msug;
    } catch (Exception e) {
      System.debug(e.getMessage());
    }
    // try to flag dupe error for existing and batch

    msug = new Mkt_Site_User__c();
    msug.Contact__c = tmpCon2.Id;
    msug.Mbr_Group__c = tmpGroup2.Id;
    dupeBatch.add(msug);

    msug = new Mkt_Site_User__c();
    msug.Contact__c = tmpCon.Id;
    msug.Mbr_Group__c = tmpGroup2.Id;
    dupeBatch.add(msug);

    msug = new Mkt_Site_User__c();
    msug.Contact__c = tmpCon.Id;
    msug.Mbr_Group__c = tmpGroup2.Id;
    dupeBatch.add(msug);

    try {
      insert dupeBatch;
    } catch (Exception e) {
      System.debug(e.getMessage());
    }

    Test.startTest();

    PageReference pageRef = Page.MSULookup;
    Test.setCurrentPage(pageRef);

    pageRef.getParameters().put('gid', tmpGroup.Id);
    MSULookupController mc = new MSULookupController();
    mc.searchContactName = 'mrs';
    mc.filterContacts();
    mc.searchContactName = 'mr';
    mc.filterContacts();
    mc.searchContactName = '';
    mc.filterContacts();

    PageReference pageRef2 = Page.MSULookup;
    pageRef2.getParameters().put('cid', tmpCon.Id);
    Test.setCurrentPage(pageRef2);

    System.debug('CON ID-->' + tmpCon.Id);

    mc = new MSULookupController();
    mc.searchGroupName = '';
    mc.filterGroups();
    mc.searchGroupName = 'fail';
    mc.filterGroups();
    mc.searchGroupName = 'Test';
    mc.filterGroups();

    PageReference pageRef3 = Page.MSULookup;
    pageRef3.getParameters().put('cid', tmpCon2.Id);
    Test.setCurrentPage(pageRef3);

    // Test Deleted ID
    PageReference pageRef4 = Page.MSULookup;
    pageRef4.getParameters().put('cid', tmpCon3.Id);
    Test.setCurrentPage(pageRef4);
    MSULookupController mc2 = new MSULookupController();
    System.debug('sel contact:' + mc2.selContactId + ' -> ' + mc2.selContact);

    PageReference pageRef5 = Page.MSULookup;
    Test.setCurrentPage(pageRef5);
    pageRef5.getParameters().put('gid', null);
    pageRef5.getParameters().put('cid', null);
    MSULookupController mc4 = new MSULookupController();
    System.assert(mc4.selContact == null);

    PageReference pageRef6 = Page.MSULookup;
    pageRef6.getParameters().put('cid', tmpCon4.Id);
    Test.setCurrentPage(pageRef6);
    MSULookupController mc3 = new MSULookupController();
    System.debug('sel contact:' + mc3.selContactId + ' -> ' + mc3.selContact);
    Test.stopTest();
  }
}