force-app/main/default/objects/Contact__c/Contact__c.object-meta.xml
<CustomObject>
    <label>LV Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact__c</referenceTo>
    <relationshipName>Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

manifest/objects/Mbr_Group__c.object
<CustomObject>
    <fields>
        <fullName>Client_Account__c</fullName>
        <description>Account that the Group is created</description>
        <inlineHelpText>Account that the Group is created</inlineHelpText>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Member Groups</relationshipLabel>
        <relationshipName>Member_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <description>System Generated Global UniqueId</description>
        <externalId>true</externalId>
        <inlineHelpText>System Generated Global UniqueId</inlineHelpText>
        <label>GUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Enter a descriptive Member Group Name.</description>
        <inlineHelpText>Enter a descriptive Member Group Name.</inlineHelpText>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Group Status</description>
        <inlineHelpText>Group Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>PENDING</fullName>
                    <default>true</default>
                    <label>PENDING</label>
                </value>
                <value>
                    <fullName>TERMED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <description>This date will allow for staged terminations in the future.  A nightly batch job will check if this date has passed and set status to termed along with all blank term dates on associated PSF records.</description>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <label>Member Group</label>
    <nameField>
        <displayFormat>MG-{00000000}</displayFormat>
        <label>Member Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Mbr_Group_Role__c.object
<CustomObject>
    <fields>
        <fullName>Mbr_Group__c</fullName>
        <description>SF Record name of the Group</description>
        <inlineHelpText>SF Record name of the Group</inlineHelpText>
        <label>Member Group</label>
        <referenceTo>Mbr_Group__c</referenceTo>
        <relationshipLabel>Member Group Roles</relationshipLabel>
        <relationshipName>Member_Group_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role_Type__c</fullName>
        <description>Type of association with Group</description>
        <inlineHelpText>Type of association with Group</inlineHelpText>
        <label>Role Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Fee_Group_Role_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account that is servicing the type of role</description>
        <inlineHelpText>Account that is servicing the type of role</inlineHelpText>
        <label>Source Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Member Group Roles</relationshipLabel>
        <relationshipName>Member_Group_Roles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Member Group Role</label>
    <nameField>
        <displayFormat>MGR-{00000000}</displayFormat>
        <label>Member Group Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Group Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Mkt_Site_User__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>MSU Contact to have marketing hub access for this member group</description>
        <inlineHelpText>MSU Contact to have marketing hub access for this member group</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Mkt Site Users</relationshipLabel>
        <relationshipName>Mkt_Site_Users</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mbr_Group__c</fullName>
        <description>SF record name of member group</description>
        <inlineHelpText>SF record name of member group</inlineHelpText>
        <label>Member Group</label>
        <referenceTo>Mbr_Group__c</referenceTo>
        <relationshipLabel>Mkt Site Users</relationshipLabel>
        <relationshipName>Mkt_Site_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Mkt Site User</label>
    <nameField>
        <displayFormat>MSU-{00000000}</displayFormat>
        <label>Mkt Site User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mkt Site Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/globalValueSets/Fee_Group_Role_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Benefit Sponsor</fullName>
    </customValue>
    <customValue>
        <fullName>Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Contractee</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Payer</fullName>
    </customValue>
    <customValue>
        <fullName>MSU Access</fullName>
    </customValue>
    <masterLabel>Fee Group Role Type</masterLabel>
</GlobalValueSet>

manifest/classes/Contact_Grp_Rollup_BchTest.cls
@isTest
private class Contact_Grp_Rollup_BchTest {
  @TestSetup
  static void setup() {
    Account umrAcct = TestDataFactory.createUMR();
    Account acct = TestDataFactory.createParentAccount();
    Account acct2 = new Account();
    acct2.Name = 'New Benefits, LTD';
    acct2.GUID__c = '5326F18B-33D6-4F53-A532-ECC7C29Ed74C';
    acct2.revenue_effective_date__c = Date.today();
    acct2.BillingStreet = 'test road test state';
    insert acct2;
    Contact con = TestDataFactory.createContact(acct.Id);
    con.marketing_site_user__c = true;
    con.email = 'test@test.com';
    update con;
    Mbr_Group__c mg = new Mbr_Group__c();
    mg.Name__c = 'Test Group';
    mg.Client_Account__c = acct2.Id;
    mg.Termination_Date__c = system.today() + 3;
    mg.Status__c = 'Active';
    insert mg;
    Mbr_Group__c mg2 = new Mbr_Group__c();
    mg2.Name__c = 'Test Group1';
    mg2.Client_Account__c = acct2.Id;
    mg2.Termination_Date__c = system.today() + 3;
    mg2.Status__c = 'Active';
    insert mg2;
    List<Mbr_Group__c> mbrGrp = TestDataFactory.createMbrGroup(acct.Id);
    Mbr_Group_Role__c mbrGrpRole = new Mbr_Group_Role__c(
      Mbr_Group__c = mg.Id,
      Source_Account__c = acct.Id,
      Role_Type__c = 'Payer'
    );
    insert mbrGrpRole;
    Mkt_Site_User__c mktSiteUser = new Mkt_Site_User__c();
    mktSiteUser.Contact__c = con.Id;
    mktSiteUser.Mbr_Group__c = mg2.Id;
    insert mktSiteUser;
  }

  static testMethod void defaultTest() {
    test.startTest();
    Contact_Grp_Rollup_Bch testing = new Contact_Grp_Rollup_Bch(null);
    DataBase.executeBatch(testing);
    test.stopTest();
    system.assertEquals(
      12,
      [SELECT Group_Count__c FROM Contact].Group_Count__c
    );
  }

  static testMethod void sameCountDefaultTest() {
    Contact con = [SELECT Id FROM Contact];
    con.Group_Count__c = 12;
    update con;
    test.startTest();
    Contact_Grp_Rollup_Bch testing = new Contact_Grp_Rollup_Bch(null);
    DataBase.executeBatch(testing);
    test.stopTest();
    system.assertEquals(
      12,
      [SELECT Group_Count__c FROM Contact].Group_Count__c
    );
  }

  static testMethod void customTest() {
    List<Mbr_Group__c> mglist = [SELECT id FROM Mbr_Group__c];
    test.startTest();
    Contact_Grp_Rollup_Bch testing = new Contact_Grp_Rollup_Bch(
      'SELECT Id, Group_Count__c, AccountId FROM Contact WHERE marketing_site_user__c = TRUE'
    );
    DataBase.executeBatch(testing);
    test.stopTest();
    system.assertEquals(
      12,
      [SELECT Group_Count__c FROM Contact].Group_Count__c
    );
  }
}