force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>LV Lead</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Last_Status__c.field-meta.xml
<CustomField>
    <fullName>Last_Status__c</fullName>
    <label>Last Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Last_Status_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Status_Date__c</fullName>
    <label>Last Status Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AQL</fullName>
                <default>true</default>
                <label>AQL</label>
            </value>
            <value>
                <fullName>MQL</fullName>
            </value>
            <value>
                <fullName>SAL</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

manifest/classes/LVGO__LeadTriggerHandler.cls
public class LeadTriggerHandler {
	public static void leadStatusChange(List<Lead__c> leads, Map<Id,Lead__c> oldMap) {
        for (Lead__c l : leads){
            if(oldMap == null){
                l.Last_Status__c = l.Status__c;
                l.Last_Status_Date__c = Datetime.now();
            }else if(l.Status__c != oldMap.get(l.id).Status__c){
                l.Last_Status__c = oldMap.get(l.id).Status__c;
                l.Last_Status_Date__c = Datetime.now();
            } 
        }
    }
}