force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>LV Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/Acct_Rev_Synergy_Flag__c.field-meta.xml
<CustomField>
    <fullName>Acct_Rev_Synergy_Flag__c</fullName>
    <label>Acct Rev Synergy Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Legacy TD Client</fullName>
            </value>
            <value>
                <fullName>Legacy LV Client</fullName>
            </value>
            <value>
                <fullName>Legacy Combined TD/LV Client</fullName>
            </value>
            <value>
                <fullName>Net New Client (All Solutions)</fullName>
                <default>true</default>
                <label>Net New Client (All Solutions)</label>
            </value>
            <value>
                <fullName>Legacy HHS Client</fullName>
            </value>
            <value>
                <fullName>Legacy Combined HHS/LV Client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>LVGO_Opportunities</relationshipName>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type> 
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity_Covered_Lives__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Covered_Lives__c</fullName>
    <label>Opportunity Covered Lives</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/OpportunityLineItem__c.object-meta.xml
<CustomObject>
    <label>Opportunity Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OpportunityLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityLineItem__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>OpportunityId</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Opportunity Products</relationshipLabel>
    <relationshipName>LGVO_OpportunityProducts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/OpportunityProductName__c.field-meta.xml
<CustomField>
    <fullName>OpportunityProductName__c</fullName>
    <label>Opportunity Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Price_Book_ID__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book ID</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Opportunity Program</relationshipLabel>
    <relationshipName>LVGO_Opportunity_Program</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Pricing_Structure__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Structure__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Updating Pricing Structure will overwrite the Sales Price, Estimated At-Risk PPPM, Estimated Partner Admin Fees, and Up Front Per Member fields.</inlineHelpText>
    <label>Pricing Structure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Pricing Structure is not available.</errorMessage>
        <filterItems>
            <field>Pricing_Structure__c.Program__c</field>
            <operation>equals</operation>
            <valueField>$Source.Program_ID__c</valueField>
        </filterItems>
        <filterItems>
            <field>Pricing_Structure__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book_ID__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Pricing_Structure__c</referenceTo>
    <relationshipLabel>Opportunity Program</relationshipLabel>
    <relationshipName>LVGO_Opportunity_Program</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product2Id</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunity LineItems</relationshipLabel>
    <relationshipName>OpportunityLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Product_Participants__c.field-meta.xml
<CustomField>
    <fullName>Product_Participants__c</fullName>
    <inlineHelpText>For new opportunities, enter estimated recruitables or rPwX. For renewals, enter enrolled members.</inlineHelpText>
    <label>Program Participants (rPwX or Enrolled)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Program_Family__c.field-meta.xml
<CustomField>
    <fullName>Program_Family__c</fullName>
    <formula>TEXT(Product2__r.Family)</formula>
    <label>Program Family</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Program_ID__c.field-meta.xml
<CustomField>
    <fullName>Program_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program ID</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunity Program</relationshipLabel>
    <relationshipName>LVGO_Opportunity_Program</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Program_Rev_Synergy_Flag__c.field-meta.xml
<CustomField>
    <fullName>Program_Rev_Synergy_Flag__c</fullName>
    <label>Program Rev Synergy Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Synergy</fullName>
            </value>
            <value>
                <fullName>Combined TD/LV Solution (MH)</fullName>
            </value>
            <value>
                <fullName>Cross-sell TD Products into LV</fullName>
            </value>
            <value>
                <fullName>Cross-sell LV Products into TD</fullName>
            </value>
            <value>
                <fullName>Cross-sell LV to HHS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Program Term</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pricing_Structure__c/Pricing_Structure__c.object-meta.xml
<CustomObject>
    <label>LV Pricing Structure</label>
    <nameField>
        <label>Pricing Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Pricing Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Product2.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/Whole_Person_Solution__c.field-meta.xml
<CustomField>
    <fullName>Whole_Person_Solution__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check only if the program is a WP Solution.</inlineHelpText>
    <label>Whole Person Solution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program_Participant__mdt/Program_Participant__mdt.object-meta.xml
<CustomObject>
    <description>Jenga#1448 - Opp wizard enhancement. Created a mapping between program and participants percentage based on opp covered lives.</description>
    <label>Program Participant</label>
    <pluralLabel>Program Participants</pluralLabel>
</CustomObject>

force-app/main/default/objects/Program_Participant__mdt/fields/ParticipantPercentage__c.field-meta.xml
<CustomField>
    <fullName>ParticipantPercentage__c</fullName>
    <label>ParticipantPercentage</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Participant__mdt/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <label>Program Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Livongo for Diabetes</fullName>
            </value>
            <value>
                <fullName>Livongo for Hypertension</fullName>
            </value>
            <value>
                <fullName>Livongo for Weight Management</fullName>
            </value>
            <value>
                <fullName>Livongo Diabetes Prevention Program</fullName>
            </value>
            <value>
                <fullName>Livongo for Behavioral Health by myStrength 1.0</fullName>
            </value>
            <value>
                <fullName>Livongo for Behavioral Health by myStrength 2.0</fullName>
            </value>
            <value>
                <fullName>DM Solution</fullName>
            </value>
            <value>
                <fullName>DP Solution</fullName>
            </value>
            <value>
                <fullName>CV Solution</fullName>
            </value>
            <value>
                <fullName>CV + DM</fullName>
            </value>
            <value>
                <fullName>CV + DP</fullName>
            </value>
            <value>
                <fullName>CV + DM + DP</fullName>
            </value>
            <value>
                <fullName>Teladoc Telehealth Services</fullName>
            </value>
            <value>
                <fullName>Teladoc Expert Medical Services</fullName>
            </value>
            <value>
                <fullName>CKD Solution</fullName>
            </value>
            <value>
                <fullName>myStrength</fullName>
            </value>
            <value>
                <fullName>myStrength Complete</fullName>
            </value>
            <value>
                <fullName>Diabetes w/ CKD Aware Variant</fullName>
            </value>
            <value>
                <fullName>Hypertension w/ CKD Aware Variant</fullName>
            </value>
            <value>
                <fullName>HF Solution</fullName>
            </value>
            <value>
                <fullName>A1C Test Kits - Results</fullName>
            </value>
            <value>
                <fullName>A1C Test Kits</fullName>
            </value>
            <value>
                <fullName>Diabetes DeviceFlex</fullName>
            </value>
            <value>
                <fullName>Diabetes Management</fullName>
            </value>
            <value>
                <fullName>Hypertension Management</fullName>
            </value>
            <value>
                <fullName>Diabetes Management Plus</fullName>
            </value>
            <value>
                <fullName>Hypertension Management Plus</fullName>
            </value>
            <value>
                <fullName>Prediabetes Management Plus</fullName>
            </value>
            <value>
                <fullName>Prediabetes Management</fullName>
            </value>
            <value>
                <fullName>Weight Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

manifest/classes/LVGO__OpportunityLineItemService.cls
public without sharing class OpportunityLineItemService {
    public static final String DM_SOLUTION = System.Label.DM_Solution;
    public static final String CV_SOLUTION = System.Label.CV_Solution;
    public static final String DP_SOLUTION = System.Label.DP_Solution;
    public static Map<String, Decimal> programToParticipantPercentMap = new Map<String, Decimal>();
    
    static {
        Map<String, Decimal> ppMap = new Map<String, Decimal>();
        Program_Participant__mdt[] ppMDT = [SELECT Program_Name__c, ParticipantPercentage__c FROM Program_Participant__mdt];
        for (Program_Participant__mdt pp: ppMDT) {
            ppMap.put(pp.Program_Name__c, pp.ParticipantPercentage__c);
        }
        programToParticipantPercentMap = ppMap;        
    }
    
    @InvocableMethod(label='Calculate Program Participant')
    public static List<List<OpportunityLineItem__c>> calculateProgramParticipants(List<List<OpportunityLineItem__c>> oliList) {
        
        //Get the OpportunityLineItem Information
        List<OpportunityLineItem__c> OppLineItemlist=new List<OpportunityLineItem__c>();
        List<List<OpportunityLineItem__c>> finalOppLineItemList = new List<List<OpportunityLineItem__c>>();
        Map<Id,String> oppLinePsMap = new Map<Id,String>();
        Map<Id,String> opplineNameMap = new Map<Id,String>();
        Map<Id,Integer> OppCoveredLivesMap = new Map<Id,Integer>();
        Set<Id> pricingStructureIds = new Set<Id>();
        Set<Id> oliIds = new Set<Id>();
        
        OppLineItemlist=oliList[0];         
        
        for (OpportunityLineItem__c l : OppLineItemlist) {
            oliIds.add(l.Id);
            pricingStructureIds.add(l.Pricing_Structure__c);
        }
        
        Map<Id,Pricing_Structure__c> pricingStructureMap = new Map <Id, Pricing_Structure__c> ([SELECT Id, Name From Pricing_Structure__c WHERE Id IN: pricingStructureIds]);
         
        for (OpportunityLineItem__c oli : OppLineItemlist) {
            if(oli.Pricing_Structure__c != NULL) {
              oppLinePsMap.put(oli.Id, pricingStructureMap.get(oli.Pricing_Structure__c).Name);  
            } 
        }
        
        List<OpportunityLineItem__c> lineItemList = [SELECT Id, Program_ID__c, OpportunityProductName__c,Pricing_Structure__c, Opportunity__r.Opportunity_Covered_Lives__c, Product_Participants__c,
                                                  Price_Book_ID__r.Name, Quantity__c, Product2__r.Whole_Person_Solution__c, Opportunity__c FROM OpportunityLineItem__c WHERE Id IN :oliIds];
        //Add Unique Programs to Set
        
        Set<String> programNameSet = new Set<String>();
        for (OpportunityLineItem__c lineItem: lineItemList) {
            programNameSet.add(lineItem.OpportunityProductName__c); 
            opplineNameMap.put(lineItem.Id,lineItem.OpportunityProductName__c);
            OppCoveredLivesMap.put(lineItem.Id,Integer.valueOf(lineItem.Opportunity__r.Opportunity_Covered_Lives__c));
        }
       
        for (OpportunityLineItem__c oli: OppLineItemlist) {
            if (OppCoveredLivesMap.get(oli.Id) != null) {                
                if (opplineNameMap.get(oli.Id) == CV_SOLUTION) {
                    if (programNameSet.contains(DM_SOLUTION) && programNameSet.contains(DP_SOLUTION)) {
                        oli.Product_Participants__c = programToParticipantPercentMap.get('CV + DM + DP') * OppCoveredLivesMap.get(oli.Id);                        
                    }
                    else if (programNameSet.contains(DM_SOLUTION)) {
                        oli.Product_Participants__c = programToParticipantPercentMap.get('CV + DM') * OppCoveredLivesMap.get(oli.Id); 
                    }
                    else if (programNameSet.contains(DP_SOLUTION)) {
                        oli.Product_Participants__c = programToParticipantPercentMap.get('CV + DP') * OppCoveredLivesMap.get(oli.Id); 
                    }
                    else {
                        oli.Product_Participants__c = programToParticipantPercentMap.get(opplineNameMap.get(oli.Id)) * OppCoveredLivesMap.get(oli.Id);
                    }
                }
                else if (programToParticipantPercentMap.get(opplineNameMap.get(oli.Id)) != null) {
                    oli.Product_Participants__c = programToParticipantPercentMap.get(opplineNameMap.get(oli.Id)) * OppCoveredLivesMap.get(oli.Id);
                }
                if(oppLinePsMap.get(oli.Id) != NULL) {
                    if(oppLinePsMap.get(oli.Id).containsIgnoreCase('PEPM')) {
                        oli.Product_Participants__c = OppCoveredLivesMap.get(oli.Id);
                    }  
                }
                if(oli.Product_Participants__c != null){
                   oli.Product_Participants__c = oli.Product_Participants__c.round();                   
                }
            }            
        }
        finalOppLineItemList.add(OppLineItemlist);
        return finalOppLineItemList;
    }    
      
    
    public static void updateRevSynergyOnPrograms(List<OpportunityLineItem__c> oppLineList, Boolean isUpdate) { 
        List<Id> oppIds = new List<Id>();
        Map<Id,String> oppAccRevFlag = new Map<Id,String>();
        List<OpportunityLineItem__c> oppLineItemsToBeUpdated = new List<OpportunityLineItem__c>();
        String myStrId = [SELECT Id FROM Product2 WHERE ProductCode = 'MYSTR3' LIMIT 1].Id;	
        String myStrCompleteId = [SELECT Id FROM Product2 WHERE ProductCode  = 'MYSTRPLUS' LIMIT 1].Id;
        for(OpportunityLineItem__c opli : oppLineList) {
            oppIds.add(opli.Opportunity__c);          
        }
        List<Opportunity__c> oppList = [SELECT Id, Account__r.Acct_Rev_Synergy_Flag__c FROM Opportunity__c WHERE ID IN : OppIds];
        for(Opportunity__c opp : oppList) {
            oppAccRevFlag.put(opp.Id, opp.Account__r.Acct_Rev_Synergy_Flag__c);
        }
       
        for(OpportunityLineItem__c opli : oppLineList) {
            Boolean isLvPrgm = false;
            Boolean isTdPrgm = false;
            
            if (opli.Product2__c == myStrId || opli.Product2__c == myStrCompleteId ) { 
                opli.Program_Rev_Synergy_Flag__c = 'Combined TD/LV Solution (MH)';
            }
            else if (opli.Program_Family__c == 'Teladoc'){ 
                isTdPrgm = true;
            }
            else {
                isLvPrgm = true;
            }
            switch on oppAccRevFlag.get(opli.Opportunity__c) {
                when 'Legacy Combined TD/LV Client' {
                    if (isLvPrgm || isTdPrgm) { 
                        opli.Program_Rev_Synergy_Flag__c = 'No Synergy';
                    }
                }
                when 'Legacy LV Client' {
                    if (isLvPrgm) { 
                        opli.Program_Rev_Synergy_Flag__c = 'No Synergy';
                    }
                    else if (isTdPrgm) { 
                        opli.Program_Rev_Synergy_Flag__c = 'Cross-sell TD Products into LV';
                    }  
                }
                when 'Legacy TD Client' {
                    if (isLvPrgm) { 
                        opli.Program_Rev_Synergy_Flag__c = 'Cross-sell LV Products into TD';
                    }
                    else if(isTdPrgm) { 
                        opli.Program_Rev_Synergy_Flag__c = 'No Synergy';
                    }
                }
                when 'Net New Client (All Solutions)' { 
                    if (isLvPrgm || isTdPrgm) { 
                        opli.Program_Rev_Synergy_Flag__c = 'No Synergy';
                    }
                }
                when 'Legacy HHS Client' {
                    if (isLvPrgm) {
                        opli.Program_Rev_Synergy_Flag__c = 'Cross-sell LV to HHS';
                    }
                    else if(isTdPrgm) {
                        opli.Program_Rev_Synergy_Flag__c = 'No Synergy';
                    }
                }
                when 'Legacy Combined HHS/LV Client' {
                    if (isLvPrgm || isTdPrgm) {
                        opli.Program_Rev_Synergy_Flag__c = 'No Synergy';
                    }
                }
            }
            oppLineItemsToBeUpdated.add(opli);
        }
        if(isUpdate && oppLineItemsToBeUpdated.size() > 0) {
            update oppLineItemsToBeUpdated;
        }
    }
}