force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>LV Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TD</fullName>
            </value>
            <value>
                <fullName>LV</fullName>
            </value>
            <value>
                <fullName>ITH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Estimated_Enrollment_Mapping__mdt/Estimated_Enrollment_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Estimated Enrollment Mapping</label>
    <pluralLabel>Estimated Enrollment Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Estimated_Enrollment_Mapping__mdt/fields/Estimated_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Enrollment__c</fullName>
    <label>Estimated Enrollment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Estimated_Enrollment_Mapping__mdt/fields/Opp_Owner_Role__c.field-meta.xml
<CustomField>
    <fullName>Opp_Owner_Role__c</fullName>
    <label>Opp Owner Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Estimated_Enrollment_Mapping__mdt/fields/Program_Family__c.field-meta.xml
<CustomField>
    <fullName>Program_Family__c</fullName>
    <label>Program Family</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LVGO_Automation_Switch__c/LVGO_Automation_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>LVGO Automation Switch</label>
</CustomObject>

force-app/main/default/objects/LVGO_Automation_Switch__c/fields/Flows__c.field-meta.xml
<CustomField>
    <fullName>Flows__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Switch to Control execution of  Flows</description>
    <inlineHelpText>Turning this flag on runs all the LVGO Flows</inlineHelpText>
    <label>Enable Flows</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVGO_Automation_Switch__c/fields/ProcessBuilders__c.field-meta.xml
<CustomField>
    <fullName>ProcessBuilders__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Switch to Control execution of  Process Builders</description>
    <inlineHelpText>Turning this flag on runs all the LVGO Process Builders</inlineHelpText>
    <label>Enable Process Builders</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVGO_Automation_Switch__c/fields/Triggers__c.field-meta.xml
<CustomField>
    <fullName>Triggers__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Switch to Control execution of  Triggers</description>
    <inlineHelpText>Turning this flag on runs all the LVGO Triggers</inlineHelpText>
    <label>Enable Triggers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVGO_Automation_Switch__c/fields/Validations__c.field-meta.xml
<CustomField>
    <fullName>Validations__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Switch to control execution of  Validations</description>
    <inlineHelpText>Turning this flag on runs all the LVGO validations</inlineHelpText>
    <label>Enable Validations</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVGO_Automation_Switch__c/fields/Workflows__c.field-meta.xml
<CustomField>
    <fullName>Workflows__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Switch to Control execution of  Worklfow Rules</description>
    <inlineHelpText>Turning this flag on runs all the LVGO Worklfows</inlineHelpText>
    <label>Enable Workflow Rules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>LVGO_Opportunities</relationshipName>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type> 
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opp_Owner_Role__c.field-meta.xml
<CustomField>
    <fullName>Opp_Owner_Role__c</fullName>
    <formula>Owner__r.UserRole.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opp Owner Role</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity_Covered_Lives__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Covered_Lives__c</fullName>
    <label>Opportunity Covered Lives</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <label>Opportunity Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OpportunitiesOwned</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TD</fullName>
            </value>
            <value>
                <fullName>LV</fullName>
            </value>
            <value>
                <fullName>ITH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/OpportunityLineItem__c.object-meta.xml
<CustomObject>
    <label>Opportunity Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OpportunityLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityLineItem__c/fields/Enrollment_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Percentage__c</fullName>
    <label>Enrollment Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>OpportunityId</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Opportunity Products</relationshipLabel>
    <relationshipName>LGVO_OpportunityProducts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/OpportunityProductName__c.field-meta.xml
<CustomField>
    <fullName>OpportunityProductName__c</fullName>
    <label>Opportunity Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Price_Book_ID__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book ID</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Opportunity Program</relationshipLabel>
    <relationshipName>LVGO_Opportunity_Program</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Pricing_Structure__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Structure__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Updating Pricing Structure will overwrite the Sales Price, Estimated At-Risk PPPM, Estimated Partner Admin Fees, and Up Front Per Member fields.</inlineHelpText>
    <label>Pricing Structure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Pricing Structure is not available.</errorMessage>
        <filterItems>
            <field>Pricing_Structure__c.Program__c</field>
            <operation>equals</operation>
            <valueField>$Source.Program_ID__c</valueField>
        </filterItems>
        <filterItems>
            <field>Pricing_Structure__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book_ID__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Pricing_Structure__c</referenceTo>
    <relationshipLabel>Opportunity Program</relationshipLabel>
    <relationshipName>LVGO_Opportunity_Program</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product2Id</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunity LineItems</relationshipLabel>
    <relationshipName>OpportunityLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <formula>HYPERLINK( LVGO__Opportunity_Product_ID__c , LVGO__Product2__r.Name, &quot;_self&quot;)</formula>
    <label>Program</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Program_Family__c.field-meta.xml
<CustomField>
    <fullName>Program_Family__c</fullName>
    <formula>TEXT(Product2__r.Family)</formula>
    <label>Program Family</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricing_Structure__c/Pricing_Structure__c.object-meta.xml
<CustomObject>
    <label>LV Pricing Structure</label>
    <nameField>
        <label>Pricing Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Pricing Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pricing_Structure__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipName>Price_Book_Entry_Variations_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricing_Structure__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Price_Book_Entry_Variations</relationshipName>
    <type>Lookup</type>
</CustomField>

manifest/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Enrollment_Percentage__c</fullName>
        <description>This field is used to set the default Enrollment Percentage for Livongo Products. It gets used in PriceRule to calculate the Quantity.</description>
        <label>Direct Enrollment Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OppLineEnrollmenPercentBatchTest.cls
@IsTest
public class OppLineEnrollmenPercentBatchTest {
    
    @TestSetup
    static void testData(){
        
        
        User testUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        //System.runAs ( testUser ) {
            UserRole ur = new UserRole();
            ur.Name='Commercial_DTE_East_Client_Sales';
            ur.DeveloperName='Commercial_DTE_East_Client_Sales';
            insert ur;
        //}    
        System.runAs (testUser) {
        LVGO_Automation_Switch__c asw  =new LVGO_Automation_Switch__c();
        asw.Triggers__c  =true;
        asw.Flows__c  =true;
        asw.ProcessBuilders__c  =true;
        asw.Validations__c  =true; 
        asw.Workflows__c  =true;
        insert asw;
            Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
            User newUser = new User (Alias = 'standt', Email='testuser@test.com', 
                                     EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                     LocaleSidKey='en_US', ProfileId = p.Id, 
                                     TimeZoneSidKey='America/Los_Angeles', UserName='testuser@testlv.com', UserRoleId = getUserRole().Id);
            insert newUser;
            Account__c clientAccount = TestFactory.createClientAccount();
            clientAccount.Account_Name__c=clientAccount.Name;
            insert clientAccount;      
            
            Opportunity__c newBusinessOpp = TestFactory.createTypeBasedOpportunity('New Business');
            newBusinessOpp.Account__c = clientAccount.Id;
            newBusinessOpp.Name = 'Enrollment Opp';
            newBusinessOpp.Opportunity_Covered_Lives__c=10000;   
            newBusinessOpp.Opportunity_Name__c = newBusinessOpp.Name;  
            insert newBusinessOpp;
            
            
            
            Pricebook2 livongoPricebook = TestFactory.createPricebook();
            insert livongoPricebook;
            
            
            List<Product2> programsList = new List<Product2>();
            programsList.add(TestFactory.createProgramWithFamily('Livongo for Diabetes', 'Diabetes'));
            programsList.add(TestFactory.createProgramWithFamily('Livongo for Hypertension', 'Hypertension'));
            programsList.add(TestFactory.createProgramWithFamily('Livongo Diabetes Prevention Program', 'Prediabetes'));
            programsList.add(TestFactory.createProgramWithFamily('Livongo for Weight Management', 'Weight Management'));
            programsList.add(TestFactory.createProgramWithFamily('Livongo for Behavioral Health by myStrength 2.0', 'Behavioral Health'));
            programsList.add(TestFactory.createProgramWithFamily('Teladoc', 'Teladoc'));
            programsList.add(TestFactory.createProgramWithFamily('myStrength', 'Behavioral Health'));
            programsList.add(TestFactory.createProgramWithFamily('myStrength Complete', 'Behavioral Health'));
            insert programsList;
            
            Id standardPBId = Test.getStandardPricebookId();
            
            List<PricebookEntry> entriesList = new List<PricebookEntry>();
            List<PricebookEntry> livongoPBEntriesList = new List<PricebookEntry>();
            List<Pricing_Structure__c> pricingStructureList = new List<Pricing_Structure__c>();
            
            for(Product2 program: programsList) {
                entriesList.add(TestFactory.createPricebookEntry(standardPBId, program.Id));
                livongoPBEntriesList.add(TestFactory.createPricebookEntry(livongoPricebook.Id, program.Id));
                pricingStructureList.add(TestFactory.createPricingStructure(livongoPricebook.Id, program.Id));
            }        
            insert entriesList;
            insert livongoPBEntriesList;
            insert pricingStructureList;
            
            livongoPBEntriesList = [Select Id, Pricebook2ID, Product2Id, Product2.Name, UnitPrice, IsActive from PricebookEntry where Id IN:livongoPBEntriesList];
            
            List<OpportunityLineItem__c> oliList = new List<OpportunityLineItem__c>();
            
            for(PricebookEntry pbe: livongoPBEntriesList) {
                //oliList.add(TestFactory.createOpportunityLineItem(newBusinessOpp.Id, pbe.Id));
                OpportunityLineItem__c oli = TestFactory.createOpportunityLineItem(newBusinessOpp.Id, pbe.Id);
                oli.Product2__c = pbe.Product2Id;
                oli.Price_Book_ID__c = pbe.Pricebook2ID;
                oli.OpportunityProductName__c = pbe.Product2.Name;
                oliList.add(oli);
            }   
            insert oliList;
        }
    }
    
    private static UserRole getUserRole() {
        return [SELECT Id FROM UserRole WHERE DeveloperName = 'Commercial_DTE_East_Client_Sales' LIMIT 1];
    }
    
    private static List<OpportunityLineItem__c> getOppline(Id oppId, String OppProductName) {
        return [SELECT Id, Enrollment_Percentage__c, Opportunity__c,Program_Family__c, Pricing_Structure__c, Product2__c, OpportunityProductName__c FROM 
                                                 OpportunityLineItem__c WHERE Opportunity__c =: oppId and OpportunityProductName__c =: oppProductName];
    }

    private static List<Pricing_Structure__c> getPricingStructures() {
        return [SELECT Id,Name From Pricing_Structure__c];
    }
    
    private static Product2 getProducts(String programName) {
        return [Select Id, Name From Product2 WHERE Name =: programName];
    }
    static {
        List <Estimated_Enrollment_Mapping__mdt> estimatedEnrollementMDTList = [SELECT Id, MasterLabel, DeveloperName, Opp_Owner_Role__c, Estimated_Enrollment__c, Program_Family__c FROM Estimated_Enrollment_Mapping__mdt];
        Map <String, Estimated_Enrollment_Mapping__mdt> estimatedEnrollementMDTMap = new Map < String, Estimated_Enrollment_Mapping__mdt > ();
        if (!estimatedEnrollementMDTList.isEmpty()) {
            for (Estimated_Enrollment_Mapping__mdt enr : estimatedEnrollementMDTList) {
                estimatedEnrollementMDTMap.put(enr.Opp_Owner_Role__c + '' + enr.Program_Family__c, enr);
            }
        }    
    }
    
    @istest
   static void calEnrollmentPercentageForHypertension() {
       
        User user = [SELECT Id, UserRoleId FROM User WHERE UserName='testuser@testlv.com' LIMIT 1];
        Opportunity__c opp = [SELECT Id, Source__c, Opp_Owner_Role__c FROM Opportunity__c WHERE Name = 'Enrollment Opp' LIMIT 1];
        opp.Owner__c = user.Id;
        update opp;
        List<OpportunityLineItem__c> oppLineList = getOppline(opp.Id, 'Livongo for Hypertension');
        //List<Pricing_structure__c> pricingStructureList = getPricingStructures();
        Product2 productHP = getProducts('Livongo for Hypertension');
        Test.startTest();
        OppLineEnrollmentPercentUpdateBatch OppLineBatch = new OppLineEnrollmentPercentUpdateBatch();
        Id batchId = Database.executeBatch(OppLineBatch);
        Test.stopTest();
        System.assertEquals(10.00, [SELECT Id, Enrollment_Percentage__c FROM OpportunityLineItem__c WHERE OpportunityProductName__c = 'Livongo for Hypertension' LIMIT 1].Enrollment_Percentage__c);
    } 
    
    @istest
    static void calEnrollmentPercentageForMystrength() {
    
        User user = [SELECT Id, UserRoleId FROM User WHERE UserName='testuser@testlv.com' LIMIT 1];
        Opportunity__c opp = [SELECT Id,Source__c, Opp_Owner_Role__c FROM Opportunity__c WHERE Name = 'Enrollment Opp' LIMIT 1];
        opp.Owner__c = user.Id;
        update opp;
        List<OpportunityLineItem__c> oppLineList = getOppline(opp.Id, 'myStrength Complete');
        PriceBook2 priceBook = [SELECT Id, Name FROM PriceBook2 WHERE Name = 'Livongo'];
        Product2 product = getProducts('myStrength Complete');
        Pricing_Structure__c ps = new Pricing_Structure__c(Name = 'Broker PPPM', Price_Book__c = priceBook.Id, Program__c = product.Id, IsActive__c = true, List_Price__c = 65);
        insert ps;
        oppLineList[0].Pricing_structure__c =ps.Id;
        oppLineList[0].Price_Book_ID__c = priceBook.Id; 
        update oppLineList;
        Test.startTest();
        OppLineEnrollmentPercentUpdateBatch OppLineBatch = new OppLineEnrollmentPercentUpdateBatch();
        Id batchId = Database.executeBatch(OppLineBatch);
        Test.stopTest();
        System.assertEquals(5.00, [SELECT Id, Enrollment_Percentage__c FROM OpportunityLineItem__c WHERE OpportunityProductName__c = 'myStrength Complete' LIMIT 1].Enrollment_Percentage__c);
    }
}