force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>LV Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/Account_Health_Score_Color__c.field-meta.xml
<CustomField>
    <fullName>Account_Health_Score_Color__c</fullName>
    <label>Account Health Score Color</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/Acct_Rev_Synergy_Flag__c.field-meta.xml
<CustomField>
    <fullName>Acct_Rev_Synergy_Flag__c</fullName>
    <label>Acct Rev Synergy Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Legacy TD Client</fullName>
            </value>
            <value>
                <fullName>Legacy LV Client</fullName>
            </value>
            <value>
                <fullName>Legacy Combined TD/LV Client</fullName>
            </value>
            <value>
                <fullName>Net New Client (All Solutions)</fullName>
                <default>true</default>
                <label>Net New Client (All Solutions)</label>
            </value>
            <value>
                <fullName>Legacy HHS Client</fullName>
            </value>
            <value>
                <fullName>Legacy Combined HHS/LV Client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account__c/fields/Activated_Percent_HTN__c.field-meta.xml
<CustomField>
    <fullName>Activated_Percent_HTN__c</fullName>
    <description>Member Activation percentage (for Hypertension)</description>
    <label>Activated Percent (HTN)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/Activation__c.field-meta.xml
<CustomField>
    <fullName>Activation__c</fullName>
    <description>Member Activation percent (for Diabetes)</description>
    <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
    <label>Activated Percent (Diabetes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/Billing_State_Backend__c.field-meta.xml
<CustomField>
    <fullName>Billing_State_Backend__c</fullName>
    <label>Billing State(Backend)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/BillingState__c.field-meta.xml
<CustomField>
    <fullName>BillingState__c</fullName>
    <label>BillingState</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/Client_Risk_Notes__c.field-meta.xml
<CustomField>
    <fullName>Client_Risk_Notes__c</fullName>
    <description>Place to track details regarding the Account Health Score (green, yellow, red) and possible risks to the account health</description>
    <label>Account Health Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/Email_Coverage_Percentage_DM__c.field-meta.xml
<CustomField>
    <fullName>Email_Coverage_Percentage_DM__c</fullName>
    <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
    <label>Email Coverage Percentage (DM)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/Email_Coverage_Percentage_HTN__c.field-meta.xml
<CustomField>
    <fullName>Email_Coverage_Percentage_HTN__c</fullName>
    <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
    <label>Email Coverage Percentage (HTN)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/Enrollment_Percentage_rPwDs__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Percentage_rPwDs__c</fullName>
    <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
    <label>Enrollment Percentage (rPwDs)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/Enrollment_Percentage_rPwHs__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Percentage_rPwHs__c</fullName>
    <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
    <label>Enrollment Percentage (rPwHs)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/Overall_Account_Score__c.field-meta.xml
<CustomField>
    <fullName>Overall_Account_Score__c</fullName>
    <label>Overall Account Score</label>
    <summarizedField>Health_Score__c.Score__c</summarizedField>
    <summaryFilterItems>
        <field>Health_Score__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Account Health Score</value>
    </summaryFilterItems>
    <summaryForeignKey>Health_Score__c.Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/Shipping_State_Backend__c.field-meta.xml
<CustomField>
    <fullName>Shipping_State_Backend__c</fullName>
    <label>Shipping State(Backend)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/Usage_Last_30_day_Diabetes__c.field-meta.xml
<CustomField>
    <fullName>Usage_Last_30_day_Diabetes__c</fullName>
    <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
    <label>Usage % Last 30 day (Diabetes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/Usage_Last_30_day_HTN__c.field-meta.xml
<CustomField>
    <fullName>Usage_Last_30_day_HTN__c</fullName>
    <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
    <label>Usage % Last 30 day (HTN)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account__c/recordTypes/Client_Account.recordType-meta.xml
<RecordType>
    <fullName>Client_Account</fullName>
    <active>true</active>
    <description>Sales account associated with direct-client relationships (e.g. employer groups)</description>
    <label>Client Account</label>
</RecordType>

force-app/main/default/objects/Account__c/recordTypes/Partner_Account.recordType-meta.xml
<RecordType>
    <fullName>Partner_Account</fullName>
    <active>true</active>
    <description>Non-sales account associated with partner relationships (e.g. Health Plans, PBMs, Benefit Consultants)</description>
    <label>Partner Account</label>
</RecordType>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>LVGO_Opportunities</relationshipName>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type> 
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/OpportunityLineItem__c.object-meta.xml
<CustomObject>
    <label>Opportunity Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OpportunityLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityLineItem__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>OpportunityId</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Opportunity Products</relationshipLabel>
    <relationshipName>LGVO_OpportunityProducts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product2Id</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunity LineItems</relationshipLabel>
    <relationshipName>OpportunityLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Program_Family__c.field-meta.xml
<CustomField>
    <fullName>Program_Family__c</fullName>
    <formula>TEXT(Product2__r.Family)</formula>
    <label>Program Family</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Program_Rev_Synergy_Flag__c.field-meta.xml
<CustomField>
    <fullName>Program_Rev_Synergy_Flag__c</fullName>
    <label>Program Rev Synergy Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Synergy</fullName>
            </value>
            <value>
                <fullName>Combined TD/LV Solution (MH)</fullName>
            </value>
            <value>
                <fullName>Cross-sell TD Products into LV</fullName>
            </value>
            <value>
                <fullName>Cross-sell LV Products into TD</fullName>
            </value>
            <value>
                <fullName>Cross-sell LV to HHS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

manifest/classes/LVGO__AccountTriggerHandler.cls
/**
* AccountTriggerHandler Class
* 
*/

public class AccountTriggerHandler {
    public static final Id CLIENT_ACCOUNT_RT = Schema.SObjectType.Account__c.getRecordTypeInfosByDeveloperName().get('Client_Account').getRecordTypeId();
    public static final Id PARTNER_ACCOUNT_RT = Schema.SObjectType.Account__c.getRecordTypeInfosByDeveloperName().get('Partner_Account').getRecordTypeId();
    
    public static void handleAccountUpdate(Map<Id,Account__c> oldAccounts, List<Account__c> newAccounts) {
        List<Account__c> updatedAccounts = new List<Account__c>();
        List<Account__c> hsUpdateAccounts = new List<Account__c>();
        List<Account__c> hsProgramScoreAccounts = new List<Account__c>();
        for(Account__c acc : newAccounts){
            if(acc.Client_Risk_Notes__c != null && acc.Client_Risk_Notes__c != oldAccounts.get(acc.Id).Client_Risk_Notes__c){
                updatedAccounts.add(acc);
            }
            if ((acc.RecordTypeId == CLIENT_ACCOUNT_RT || acc.RecordTypeId == PARTNER_ACCOUNT_RT)
                &&
                (acc.Enrollment_Percentage_rPwDs__c != oldAccounts.get(acc.Id).Enrollment_Percentage_rPwDs__c ||
                 acc.Enrollment_Percentage_rPwHs__c != oldAccounts.get(acc.Id).Enrollment_Percentage_rPwHs__c || 
                 acc.Activation__c  != oldAccounts.get(acc.Id).Activation__c || 
                 acc.Activated_Percent_HTN__c != oldAccounts.get(acc.Id).Activated_Percent_HTN__c ||
                 acc.Usage_Last_30_day_Diabetes__c != oldAccounts.get(acc.Id).Usage_Last_30_day_Diabetes__c ||
                 acc.Usage_Last_30_day_HTN__c != oldAccounts.get(acc.Id).Usage_Last_30_day_HTN__c ||
                 acc.Email_Coverage_Percentage_DM__c != oldAccounts.get(acc.Id).Email_Coverage_Percentage_DM__c || 
                 acc.Email_Coverage_Percentage_HTN__c != oldAccounts.get(acc.Id).Email_Coverage_Percentage_HTN__c)) {
                     hsUpdateAccounts.add(acc);
                 }
        }
        if (!updatedAccounts.isEmpty()) {
            AccountService.autoCreateNote(updatedAccounts);           
        }
        if (!hsUpdateAccounts.isEmpty()) {
            AccountService.updateHealthScores(hsUpdateAccounts, oldAccounts);
        }
    }
    public static void handleAccountAfterInsert(List<Account__c> newAccounts) {
        List<Account__c> accList = new List<Account__c>();
        for (Account__c acc: newAccounts) {
            if (acc.RecordTypeId == CLIENT_ACCOUNT_RT || acc.RecordTypeId == PARTNER_ACCOUNT_RT) {
                accList.add(acc);
            }
        }
        if (!accList.isEmpty()) {
            AccountService.createHealthScores(accList);
        }
    }
    
    public static void updateState( Map<Id, Account__c> oldAccounts, List<Account__c> newAccounts ) {
        Map<String, String> mapStateCode = new Map<String, String>();
        Schema.DescribeFieldResult fieldResult = User.statecode.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry f : ple){  
            mapStateCode.put(f.getValue(), f.getLabel());
        }
        for(Account__c objAcc: newAccounts) 
        { 
            if( String.isNotBlank(objAcc.Billing_State_Backend__c) &&
               ( oldAccounts.isEmpty() || ( !oldAccounts.isEmpty() && oldAccounts.get(objAcc.Id).Billing_State_Backend__c != objAcc.Billing_State_Backend__c))
               && mapStateCode.containsKey(objAcc.Billing_State_Backend__c) ) 
            {
                objAcc.Billing_State_Backend__c = mapStateCode.get(objAcc.Billing_State_Backend__c);
                objAcc.BillingState__c = objAcc.Billing_State_Backend__c;
            }
            if( String.isNotBlank(objAcc.Shipping_State_Backend__c) &&
               ( oldAccounts.isEmpty() || ( !oldAccounts.isEmpty() && oldAccounts.get(objAcc.Id).Shipping_State_Backend__c != objAcc.Shipping_State_Backend__c))
               && mapStateCode.containsKey(objAcc.Shipping_State_Backend__c) ) 
            {
                objAcc.Shipping_State_Backend__c = mapStateCode.get(objAcc.Shipping_State_Backend__c);
                //objAcc.ShippingState = objAcc.Shipping_State_Backend__c; 
            }
        }
    }
    
    public static void updateOppRevSynergyFlag(Map<Id,Account__c> accOldMap, List<Account__c> accList) {
        List<String> accIdList = new List<String>();
        Boolean isUpdate = true;
        for (Account__c acct: accList) {
            if(acct.Acct_Rev_Synergy_Flag__c != accOldMap.get(acct.Id).Acct_Rev_Synergy_Flag__c) {
                accIdList.add(acct.Id);
            }
        }
        List<Opportunity__c> oppUpdateList = [SELECT Id FROM Opportunity__c WHERE Account__c IN: accIdList];
        if(oppUpdateList.size() > 0) {
            update oppUpdateList;
        }
        
        List<OpportunityLineItem__c> oppLineItemUpdateList = [SELECT Id,Opportunity__c,Product2__r.Name,Product2__c,Program_Family__c,
                                                           Program_Rev_Synergy_Flag__c FROM OpportunityLineItem__c WHERE Opportunity__r.Account__c IN: accIdList];
        if(oppLineItemUpdateList.size() > 0) {
            OpportunityLineItemTriggerHandler.updateRevSynergyFlag(oppLineItemUpdateList, true);
            //update oppLineItemUpdateList; /* Updating these Opp Line Items from OpportunityLineItemService */
        }  
        
    }
    
    public static void updateAccountHealthColor(Map<Id,Account__c> accOldMap, List<Account__c> accList) {
        for(Account__c acc : accList) {
            if (acc.Overall_Account_Score__c != NULL && acc.Overall_Account_Score__c != accOldMap.get(acc.Id).Overall_Account_Score__c) { 
                if (acc.Overall_Account_Score__c >= 75) {
                    acc.Account_Health_Score_Color__c = 'Green';
                }
                else if (acc.Overall_Account_Score__c >= 60) {
                    acc.Account_Health_Score_Color__c = 'Yellow';
                }
                else {
                    acc.Account_Health_Score_Color__c = 'Red';  
                }
            }
        }
    }
}