force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>LV Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Health_Score__c/Health_Score__c.object-meta.xml
<CustomObject>
    <label>Health Score</label>
    <nameField>
        <displayFormat>HS-{00000000}</displayFormat>
        <label>Health Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Health Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Health_Score__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Health Scores</relationshipLabel>
    <relationshipName>Health_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LVGO_Automation_Switch__c/LVGO_Automation_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>LVGO Automation Switch</label>
</CustomObject>

force-app/main/default/objects/LVGO_Automation_Switch__c/fields/Triggers__c.field-meta.xml
<CustomField>
    <fullName>Triggers__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Switch to Control execution of  Triggers</description>
    <inlineHelpText>Turning this flag on runs all the LVGO Triggers</inlineHelpText>
    <label>Enable Triggers</label>
    <type>Checkbox</type>
</CustomField>

manifest/classes/LVGO__AccountHealthScoreControllerTest.cls
@isTest
public class AccountHealthScoreControllerTest {
    @TestSetup
    static void setupData() {
        LVGO_Automation_Switch__c asw  =new LVGO_Automation_Switch__c();
        asw.Triggers__c  =true;
        insert asw;
        
        Account__c clientAccount = TestFactory.createClientAccount();
        insert clientAccount;
    }
    
    private static Account__c getClientAccount() {
        return [SELECT Id FROM Account__c LIMIT 1];
    }
    
    private static List<Health_Score__c> getHealthScores(Id accId) {
        return [SELECT Id FROM Health_Score__c WHERE Account__c = :accId];
    }
    
    @isTest
    static void hsControllerTest() {
        Account__c acc = getClientAccount();
        Test.startTest();
        AccountHealthScoreController.getHealthScores(acc.Id);
        Test.stopTest();
        List<Health_Score__c> hsList = getHealthScores(acc.Id);
        system.assertEquals(32, hsList.size());
    }
}