force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>LV Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/recordTypes/Client_Account.recordType-meta.xml
<RecordType>
    <fullName>Client_Account</fullName>
    <active>true</active>
    <description>Sales account associated with direct-client relationships (e.g. employer groups)</description>
    <label>Client Account</label>
</RecordType>

force-app/main/default/objects/Account__c/recordTypes/Partner_Account.recordType-meta.xml
<RecordType>
    <fullName>Partner_Account</fullName>
    <active>true</active>
    <description>Non-sales account associated with partner relationships (e.g. Health Plans, PBMs, Benefit Consultants)</description>
    <label>Partner Account</label>
</RecordType>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>LV Contract</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Edits Controlled - Financially Material -  Flows to Redshift</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>LVGO_Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <description>This junction object links Client with Partner Accounts, Partner Accounts with Client Opportunities, Client Accounts with Competitor Accounts, and Competitor Accounts with Client Opportunities.</description>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Relationship Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationship__c/fields/Master_Account__c.field-meta.xml
<CustomField>
    <fullName>Master_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to either a Partner or Competitor Account for linking to a Client Account.</description>
    <inlineHelpText>Lookup to either a Partner or Competitor Account for linking to a Client Account.</inlineHelpText>
    <label>Master Vendor Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Master Vendor Accounts</relationshipLabel>
    <relationshipName>PartnerAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Master_Client_Account__c.field-meta.xml
<CustomField>
    <fullName>Master_Client_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Defines the master account for the Relates To record</description>
    <label>Master Client Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Master Client Accounts</relationshipLabel>
    <relationshipName>MasterAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/recordTypes/Contract_Partnership.recordType-meta.xml
<RecordType>
    <fullName>Contract_Partnership</fullName>
    <active>true</active>
    <description>Partner at the Contract level (Admin Party, Billing Partner, Care Coordinator, Contract Path, Contract Terms, or Data)</description>
    <label>Contract Partnership</label>
</RecordType>

force-app/main/default/classes/RelatedClientAccountsCtrlTest.cls
@isTest
public class RelatedClientAccountsCtrlTest {

    public static final Id PARTNER_ACCOUNT_RT_ID = Schema.SObjectType.Account__c.getRecordTypeInfosByDeveloperName().get('Partner_Account').getRecordTypeId();
    public static final Id CLIENT_ACCOUNT_RT_ID = Schema.SObjectType.Account__c.getRecordTypeInfosByDeveloperName().get('Client_Account').getRecordTypeId();
    public static final Id CONTRACT_PARTNERSHIP_RT_ID = Schema.SObjectType.Relationship__c.getRecordTypeInfosByDeveloperName().get('Contract_Partnership').getRecordTypeId();


    public static Account__c getPartnerAccount() {
        Id partnerAccountRTId = Schema.SObjectType.Account__c.getRecordTypeInfosByDeveloperName().get('Partner_Account').getRecordTypeId();
        return [SELECT Id, RecordTypeId, Name FROM Account__c WHERE RecordTypeId = :PARTNER_ACCOUNT_RT_ID LIMIT 1];
    }

    @TestSetup
    static void setupData() {
        Account__c partnerAccount = TestFactory.createPartnerAccount();
        insert partnerAccount;
        
        Contract__c co = TestFactory.createClientOverview();
        co.Account__c = partnerAccount.Id;
        insert co;
        
        List<Relationship__c> allRelationships = new List<Relationship__c>();
        Relationship__c rel1 = TestFactory.createRelationship('Contract Path');
        rel1.RecordtypeId=CONTRACT_PARTNERSHIP_RT_ID; 
        allRelationships.add(rel1);    
        insert allRelationships; 
    }

    @isTest
    static void getRelatedClientAccountsRelationshipsLinkedToPartnerAccountTest() {
        Account__c partnerAccount = getPartnerAccount();
        
        List<Relationship__c> relationships = [SELECT Id, Name, RecordTypeId, Master_Account__c, Master_Client_Account__c FROM Relationship__c WHERE RecordTypeId = :CONTRACT_PARTNERSHIP_RT_ID];
        for (Relationship__c rel : relationships) {
            rel.Master_Account__c = partnerAccount.Id;
        }
        
        update relationships;

        Test.startTest();

        List<Relationship__c> rels  = RelatedClientAccountsCtrl.getRelatedClientAccounts(partnerAccount.Id);

        Test.stopTest();
        
        //Should be multiple Relationships created
        System.assertNotEquals(0, rels.size());
        for (Relationship__c rel : rels) {
            //Each Relationship should be associated with the Partner Account
            System.assertEquals(partnerAccount.Id, rel.Master_Account__c);
            //Each Relationship should have the Contract Partnership Record Type
            System.assertEquals(CONTRACT_PARTNERSHIP_RT_ID, rel.RecordTypeId);
        }
    }

    @isTest
    static void getRelatedClientAccountsRelationshipsNotLinkedToPartnerAccountTest() {
        Account__c partnerAccount = getPartnerAccount();

        Test.startTest();
        
        List<Relationship__c> rels = RelatedClientAccountsCtrl.getRelatedClientAccounts(partnerAccount.Id);

        Test.stopTest();

        //No Relationships should be returned as they were never associated with a Partner Account
        System.assertEquals(0, rels.size());
    }
}