force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>LV Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountContactRelation__c/AccountContactRelation__c.object-meta.xml
<CustomObject>
    <label>Account Contact Relationship</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Contact Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountContactRelation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Account Contact Relations</relationshipLabel>
    <relationshipName>AccountContactRelations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact__c</referenceTo>
    <relationshipLabel>Account Contact Relations</relationshipLabel>
    <relationshipName>AccountContactRelations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact__c/Contact__c.object-meta.xml
<CustomObject>
    <label>LV Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact__c</referenceTo>
    <relationshipName>Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>FirstName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact__c/fields/MiddleName__c.field-meta.xml
<CustomField>
    <fullName>MiddleName__c</fullName>
    <label>MiddleName</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Prof.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactTriggerLVHelper.cls
public class ContactTriggerLVHelper {
   public static void createAccountContactRel(List<Contact__c> conlist,Map<id,Contact__c> newMap ,Map<id,Contact__c> oldMap){
        Set<id> accids = new set<id>();
        Set<id> conids = new set<id>();
        List<AccountContactRelation__c> accContRelLV = new List<AccountContactRelation__c>();
        for(Contact__c contObj: conlist){
            if(contObj.Account__c != null){
                if(trigger.isafter && (trigger.isinsert || (trigger.isupdate && contObj.Account__c != oldMap.get(contObj.Id).Account__c)))
            	accContRelLV.add(new AccountContactRelation__c(Account__c=contObj.Account__c, Contact__c=contObj.id,IsActive__c =true));
                if(trigger.isafter && trigger.isupdate && contObj.Account__c != newMap.get(contObj.Id).Account__c){
                    accids.add(contObj.Account__c);
                	conids.add(contObj.Id);
                }
            }
        }
        database.insert(accContRelLV,false);
        Map<String,AccountContactRelation__c> accContRelMap = new Map<String,AccountContactRelation__c>();
        for(AccountContactRelation__c contObj : [Select Id,IsActive__c,Account__c,Contact__c from AccountContactRelation__c where Contact__c in: conids and Account__c in :accids and IsActive__c =true]){
            accContRelMap.put(contObj.Account__c+'::'+contObj.Contact__c,contObj);
        }
        for(Contact__c contObj: conlist){
            if(contObj.Account__c != null && accContRelMap.containskey(contObj.Account__c+'::'+contObj.id)){
            	accContRelMap.get(contObj.Account__c+'::'+contObj.id).IsActive__c = false;
            }
        }
            system.debug('accContRelMap.values() '+accContRelMap.values());
        
        database.update(accContRelMap.values(),false);
    }

    public static void updateName(List<Contact__c> conlist,Map<id,Contact__c> newMap ,Map<id,Contact__c> oldMap){
        for(Contact__c contObj: conlist){
            String conName='';
            if(NULL != contObj.Salutation__c)
                conName = contObj.Salutation__c;
            if(NULL != contObj.Firstname__c)
                conName+= ' '+contObj.Firstname__c;
            if(NULL != contObj.Middlename__c)
                conName+= ' '+contObj.Middlename__c;
            if(NULL != contObj.Lastname__c)
                conName+= ' '+contObj.Lastname__c;
            contObj.Name = conName;
        }
    }
    
}