force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>LV Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Field that indicates whether an account is a prospect, a client (and where they&apos;re at in the onboarding process), or former client</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospecting</fullName>
                <default>true</default>
                <label>Prospecting</label>
            </value>
            <value>
                <fullName>Prospecting - Expressed Interest</fullName>
            </value>
            <value>
                <fullName>Prospecting – Not Currently Interested</fullName>
            </value>
            <value>
                <fullName>Engaging</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Former Client</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Active Partner</fullName>
            </value>
            <value>
                <fullName>Study</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payer/ASO</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>TPA</fullName>
            </value>
            <value>
                <fullName>Self Funded Employer</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Hospital/Health System</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Medicare Advantage</fullName>
            </value>
            <value>
                <fullName>PBM</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>Ops Partner</fullName>
            </value>
            <value>
                <fullName>Managed Care Organization</fullName>
            </value>
            <value>
                <fullName>Fully-Insured Employer</fullName>
                <label>Fully Insured Employer</label>
            </value>
            <value>
                <fullName>Labor/Pension Fund</fullName>
            </value>
            <value>
                <fullName>Federal Government</fullName>
            </value>
            <value>
                <fullName>Other Partner</fullName>
            </value>
            <value>
                <fullName>Behavioral Health Provider</fullName>
            </value>
            <value>
                <fullName>Chronic Care Management Organization</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Physician / Hospital</fullName>
            </value>
            <value>
                <fullName>Referral Agent</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account__c/recordTypes/Client_Account.recordType-meta.xml
<RecordType>
    <fullName>Client_Account</fullName>
    <active>true</active>
    <description>Sales account associated with direct-client relationships (e.g. employer groups)</description>
    <label>Client Account</label>
</RecordType>

force-app/main/default/objects/Health_Score__c/Health_Score__c.object-meta.xml
<CustomObject>
    <label>Health Score</label>
    <nameField>
        <displayFormat>HS-{00000000}</displayFormat>
        <label>Health Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Health Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Health_Score__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Health Scores</relationshipLabel>
    <relationshipName>Health_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LVGO_Automation_Switch__c/LVGO_Automation_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>LVGO Automation Switch</label>
</CustomObject>

force-app/main/default/objects/LVGO_Automation_Switch__c/fields/Triggers__c.field-meta.xml
<CustomField>
    <fullName>Triggers__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Switch to Control execution of  Triggers</description>
    <inlineHelpText>Turning this flag on runs all the LVGO Triggers</inlineHelpText>
    <label>Enable Triggers</label>
    <type>Checkbox</type>
</CustomField>

manifest/classes/LVGO__HealthScoresBatchTest.cls
@isTest
private class HealthScoresBatchTest {
    @testSetup 
    static void setup() {
        LVGO_Automation_Switch__c asw  =new LVGO_Automation_Switch__c();
        asw.Triggers__c  =true;
        insert asw;
        
        List<Account__c> accounts = new List<Account__c>();
        for (Integer i=0; i<10; i++) {
            Account__c testAccount = new Account__c();
            testAccount.RecordTypeId = Schema.SObjectType.Account__c.getRecordTypeInfosByDeveloperName().get('Client_Account').getRecordTypeId();
            testAccount.Name = 'Test Batch Account' + i;
            testAccount.Type__c = 'Self Funded Employer';
            testAccount.Account_Type__c = 'Client';
            accounts.add(testAccount);
        }
        insert accounts;
    }
    
    static testmethod void test() {  
        List<Account__c> accList = [SELECT Id FROM Account__c WHERE Name LIKE 'Test Batch Account%'];
        Test.startTest();
        HealthScoresBatch caub = new HealthScoresBatch();
        Id batchId = Database.executeBatch(caub);
        Test.stopTest();
        System.assertEquals(640, [SELECT count() FROM Health_Score__c WHERE Account__c IN: accList]);
    }
     
}