force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>LV Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payer/ASO</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>TPA</fullName>
            </value>
            <value>
                <fullName>Self Funded Employer</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Hospital/Health System</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Medicare Advantage</fullName>
            </value>
            <value>
                <fullName>PBM</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>Ops Partner</fullName>
            </value>
            <value>
                <fullName>Managed Care Organization</fullName>
            </value>
            <value>
                <fullName>Fully-Insured Employer</fullName>
                <label>Fully Insured Employer</label>
            </value>
            <value>
                <fullName>Labor/Pension Fund</fullName>
            </value>
            <value>
                <fullName>Federal Government</fullName>
            </value>
            <value>
                <fullName>Other Partner</fullName>
            </value>
            <value>
                <fullName>Behavioral Health Provider</fullName>
            </value>
            <value>
                <fullName>Chronic Care Management Organization</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Physician / Hospital</fullName>
            </value>
            <value>
                <fullName>Referral Agent</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account__c/recordTypes/Client_Account.recordType-meta.xml
<RecordType>
    <fullName>Client_Account</fullName>
    <active>true</active>
    <description>Sales account associated with direct-client relationships (e.g. employer groups)</description>
    <label>Client Account</label>
</RecordType>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>LV Contract</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Edits Controlled - Financially Material -  Flows to Redshift</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>LVGO_Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Client_Able_to_Send_HR_Comms__c.field-meta.xml
<CustomField>
    <fullName>Client_Able_to_Send_HR_Comms__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enrollment Marketing - Client Overview</description>
    <label>Client Able to Send HR Comms?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Disclaimer__c.field-meta.xml
<CustomField>
    <fullName>Disclaimer__c</fullName>
    <description>This is the disclaimer used for Enrollment Marketing purposes across multiple programs.</description>
    <label>Disclaimer</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Eligibility_Sentence__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Sentence__c</fullName>
    <description>This is the Eligibility Sentence used for Enrollment Marketing across multiple programs.</description>
    <label>Eligibility Sentence</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Employee_Title__c.field-meta.xml
<CustomField>
    <fullName>Employee_Title__c</fullName>
    <label>Employee Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/General_Eligibility_Sentence__c.field-meta.xml
<CustomField>
    <fullName>General_Eligibility_Sentence__c</fullName>
    <description>General Eligibility Sentence information to be used on assets promoting Whole Person solutions or multiple standalone programs</description>
    <inlineHelpText>General Eligibility Sentence information to be used on assets promoting Whole Person solutions or multiple standalone programs</inlineHelpText>
    <label>General Eligibility Sentence</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Marketing_Name__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Name__c</fullName>
    <description>Integrated with Redshift</description>
    <inlineHelpText>Integrated with Redshift</inlineHelpText>
    <label>Marketing Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/OE_Month_End__c.field-meta.xml
<CustomField>
    <fullName>OE_Month_End__c</fullName>
    <label>OE Month End</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Months</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/OE_Month_Start__c.field-meta.xml
<CustomField>
    <fullName>OE_Month_Start__c</fullName>
    <label>OE Month Start</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Months</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Edits Controlled - Financially Material -  Flows to Redshift</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Activate</fullName>
            </value>
            <value>
                <fullName>Re-Activate</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>In Approval Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type of Incentive to Exclude</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Visa GC</fullName>
            </value>
            <value>
                <fullName>Amazon GC</fullName>
            </value>
            <value>
                <fullName>Food Products</fullName>
            </value>
            <value>
                <fullName>Activity Trackers</fullName>
            </value>
            <value>
                <fullName>Hospitality Incentives</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/recordTypes/Client_Overview.recordType-meta.xml
<RecordType>
    <fullName>Client_Overview</fullName>
    <active>true</active>
    <description>Represents the overarching Program Agreement between Livongo and Client + the Client&apos;s specific operational processes</description>
    <label>Client Overview</label>
</RecordType>

force-app/main/default/objects/Contract__c/recordTypes/Program_Overview.recordType-meta.xml
<RecordType>
    <fullName>Program_Overview</fullName>
    <active>true</active>
    <description>Represents the program-specific, Program Schedule under a Program Agreement + the Client&apos;s specific operational processes regarding the program</description>
    <label>Program Overview</label>
</RecordType>

force-app/main/default/objects/Enrollment_Communications_Survey__c/Enrollment_Communications_Survey__c.object-meta.xml
<CustomObject>
    <label>LV Enrollment Communications Survey</label>
    <nameField>
        <displayFormat>Survey-{0000}</displayFormat>
        <label>Enrollment Communications Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LV Enrollment Communications Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Communications_Survey__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Enrollment Communications Surveys</relationshipLabel>
    <relationshipName>Enrollment_Communications_Surveys</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment_Communications_Survey__c/fields/Client_able_to_send_HR_comms__c.field-meta.xml
<CustomField>
    <fullName>Client_able_to_send_HR_comms__c</fullName>
    <label>Client able to send HR comms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment_Communications_Survey__c/fields/Diabetes_Eligibility_Sentence__c.field-meta.xml
<CustomField>
    <fullName>Diabetes_Eligibility_Sentence__c</fullName>
    <label>Diabetes Eligibility Sentence</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Enrollment_Communications_Survey__c/fields/Disclaimer__c.field-meta.xml
<CustomField>
    <fullName>Disclaimer__c</fullName>
    <label>Disclaimer</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Enrollment_Communications_Survey__c/fields/Employee_Title__c.field-meta.xml
<CustomField>
    <fullName>Employee_Title__c</fullName>
    <label>Employee Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment_Communications_Survey__c/fields/General_Eligibility_Sentence__c.field-meta.xml
<CustomField>
    <fullName>General_Eligibility_Sentence__c</fullName>
    <label>General Eligibility Sentence</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Enrollment_Communications_Survey__c/fields/Hypertension_Eligibility_Sentence__c.field-meta.xml
<CustomField>
    <fullName>Hypertension_Eligibility_Sentence__c</fullName>
    <label>Hypertension Eligibility Sentence</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Enrollment_Communications_Survey__c/fields/Marketing_Name__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Name__c</fullName>
    <label>Marketing Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment_Communications_Survey__c/fields/OE_Month_Start__c.field-meta.xml
<CustomField>
    <fullName>OE_Month_Start__c</fullName>
    <label>OE Month Start</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>January</fullName>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment_Communications_Survey__c/fields/Prediabetes_Eligibility_Sentence__c.field-meta.xml
<CustomField>
    <fullName>Prediabetes_Eligibility_Sentence__c</fullName>
    <label>Prediabetes Eligibility Sentence</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Enrollment_Communications_Survey__c/fields/Survey_Status__c.field-meta.xml
<CustomField>
    <fullName>Survey_Status__c</fullName>
    <label>Survey Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Resent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment_Communications_Survey__c/fields/Weight_Management_Eligibility_Sentence__c.field-meta.xml
<CustomField>
    <fullName>Weight_Management_Eligibility_Sentence__c</fullName>
    <label>Weight Management Eligibility Sentence</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EnrollmentCommunicationsHandlerTest.cls
@isTest
public class EnrollmentCommunicationsHandlerTest {
    public static final Id CO_RECORDTYPEID = Schema.SObjectType.Contract__c.getRecordTypeInfosByDeveloperName().get('Client_Overview').getRecordTypeId();
    public static final Id PO_RECORDTYPEID = Schema.SObjectType.Contract__c.getRecordTypeInfosByDeveloperName().get('Program_Overview').getRecordTypeId();
    public static final Id ACC_RECORDTYPEID = Schema.SObjectType.Account__c.getRecordTypeInfosByDeveloperName().get('Client_Account').getRecordTypeId();
    
    Public static testMethod void doTestContract_CO_PO(){
        List<String> livPrograms = new List<String>{'Diabetes', 'Hypertension', 'Prediabetes', 'Weight Management',
            'Behavioral Health'};
                List<Account__c> accList = new List<Account__c>();
        for(integer i=0; i<2; i++){
            Account__c acc = new Account__c();
            acc.RecordTypeId = ACC_RECORDTYPEID;
            acc.Name = 'Test Account'+i;
            acc.Type__c = 'TPA';
            accList.add(acc);
        }
        insert accList;
        List<Enrollment_Communications_Survey__c> envList = new List<Enrollment_Communications_Survey__c>();
        for(integer j=0; j<2; j++){
            Enrollment_Communications_Survey__c envSurvey = new Enrollment_Communications_Survey__c();
            envSurvey.Account__c = accList.get(j).Id;
            envSurvey.Survey_Status__c = 'Sent';
            envList.add(envSurvey);
        }
        insert envList;
        
        for(Enrollment_Communications_Survey__c env:envList){
            env.Survey_Status__c = 'Completed';
            env.Client_able_to_send_HR_Comms__c = 'Yes';
            env.Disclaimer__c = 'NA';
            env.Diabetes_Eligibility_Sentence__c = 'Diabetes Eligibility';
            env.Hypertension_Eligibility_Sentence__c = 'Hypertension Eligibility';
            env.Prediabetes_Eligibility_Sentence__c = 'Prediabetes Eligibility';
            env.Weight_Management_Eligibility_Sentence__c = 'Weight Management Eligibility';
            env.General_Eligibility_Sentence__c = 'General';
            env.Employee_Title__c = 'Employees';
            env.Marketing_Name__c = 'ABC Inc';
            env.OE_Month_Start__c = 'January';
            env.OE_Month_End__c = 'February';
            env.OE_Period_Length__c = '2 weeks';
            DescribeFieldResult describe = Enrollment_Communications_Survey__c.Livongo_programs__c.getDescribe();
            List<PicklistEntry> avl = describe.getPicklistValues();
            string fgh =avl[0].value+';'+avl[4].value+';'+avl[3].value+';'+avl[2].value+';'+avl[1].value;
            env.Livongo_programs__c= fgh;
        }  
        update envList;
        
        List<contract__c> coList = New List<contract__c>();
        Contract__c cont_CO = new Contract__c();
        cont_CO.RecordTypeId = CO_RECORDTYPEID;
        cont_CO.Account__c = accList.get(1).Id;
        cont_CO.Status__c = 'Draft';
        insert cont_CO;
        
        for(integer k=0; k<5; k++){
            Contract__c cont_PO = new Contract__c();
            cont_PO.Account__c = accList.get(1).Id;
            cont_PO.RecordTypeId = PO_RECORDTYPEID;
            cont_PO.Account_Client_Overview__c = cont_CO.Id;
            cont_PO.Program_Name__c = livPrograms.get(k);
            cont_PO.Eligibility_Sentence__c = '';
            cont_PO.Status__c = 'Draft';
            coList.add(cont_PO);
        }
        insert coList;
        
        
        test.startTest();
        EnrollmentCommunicationsTriggerHandler.updateContractrecords(envList);
        test.stopTest();
        
    }
}