force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>LV Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact__c/Contact__c.object-meta.xml
<CustomObject>
    <label>LV Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact__c</referenceTo>
    <relationshipName>Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LVGO_Automation_Switch__c/LVGO_Automation_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>LVGO Automation Switch</label>
</CustomObject>

force-app/main/default/objects/LVGO_Automation_Switch__c/fields/Triggers__c.field-meta.xml
<CustomField>
    <fullName>Triggers__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Switch to Control execution of  Triggers</description>
    <inlineHelpText>Turning this flag on runs all the LVGO Triggers</inlineHelpText>
    <label>Enable Triggers</label>
    <type>Checkbox</type>
</CustomField>

manifest/classes/LVGO__ContactTriggerLVHelper_Test.cls
@isTest
public class ContactTriggerLVHelper_Test {
@isTest
    public static void testContactTrigger(){
        LVGO_Automation_Switch__c switchFlg = LVGO_Automation_Switch__c.getInstance();
        switchFlg.Triggers__c = True;
        upsert switchFlg;
        Account__c acc1 = new Account__c(name = 'acc1');
        insert acc1;
        Account__c acc2 = new Account__c(name = 'acc2');
        insert acc2;
        Contact__c con = new contact__c(LastName__c='testcont',account__c = acc1.id);
        insert con;
        con.account__c = acc2.id;
        update con;
        
    }
}