force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>LV Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/CSM__c.field-meta.xml
<CustomField>
    <fullName>CSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CSM assigned to account</description>
    <label>Commercial CSM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LVGO_CSM_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>LV Contract</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Edits Controlled - Financially Material -  Flows to Redshift</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>LVGO_Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Client_Overview_Status__c.field-meta.xml
<CustomField>
    <fullName>Client_Overview_Status__c</fullName>
    <description>Copy for Client Overview&apos;s Status on Program Overview. Populated by workflow rule.</description>
    <inlineHelpText>Copy for Client Overview&apos;s Status on Program Overview. Populated by workflow rule.</inlineHelpText>
    <label>Client Overview Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Contract_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Effective_Date__c</fullName>
    <description>Date the Client Overview becomes effective.</description>
    <inlineHelpText>Integrated with NetSuite</inlineHelpText>
    <label>Contract Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Contract_Path__c.field-meta.xml
<CustomField>
    <fullName>Contract_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Edits Controlled - Financially Material</inlineHelpText>
    <label>Contract Path</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Contracts (Contract Path)</relationshipLabel>
    <relationshipName>LVGO_Contracts_ContractPath</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Contract_Termination_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Termination_Date__c</fullName>
    <description>The date a contract is terminated with a client (or has expired and not been renewed)</description>
    <inlineHelpText>Integrated with NetSuite</inlineHelpText>
    <label>Contract Termination Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/CSM__c.field-meta.xml
<CustomField>
    <fullName>CSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Integrated with Redshift</description>
    <inlineHelpText>Integrated with Redshift</inlineHelpText>
    <label>Client Success Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LVGO_Client_Overviews1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Edits Controlled - Financially Material -  Flows to Redshift</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Activate</fullName>
            </value>
            <value>
                <fullName>Re-Activate</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>In Approval Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

manifest/classes/LVGO__ContractStatusUpdateBatchTest.cls
@istest
public class ContractStatusUpdateBatchTest {
    
	static testMethod void unitTest1() {
        Account__c clientAccount = TestFactory.createClientAccount();
        insert clientAccount;
        Account__c partnerAccount = TestFactory.createPartnerAccount();
        insert partnerAccount;
        Contract__c clientOverview = TestFactory.createClientOverview();
        clientOverview.RecordTypeId = Schema.SObjectType.Contract__c.getRecordTypeInfosByName().get('Client Overview').getRecordTypeId();
        clientOverview.Account__c = clientAccount.Id;
        clientOverview.Contract_Path__c = partnerAccount.Id;
        clientOverview.CSM__c = System.UserInfo.getUserId();
        clientOverview.Status__c ='Draft';
        clientOverview.Contract_Effective_Date__c = Date.today();
        insert clientOverview;
        ContractStatusUpdateBatch sh1 = new ContractStatusUpdateBatch();
        String sch = '0 0 23 * * ?'; 
        Test.startTest();
        system.schedule('Test Territory Check', sch, sh1);
        DataBase.executeBatch(sh1); 
        Test.stopTest();         
    }
    static testMethod void unitTest2() {
        Account__c clientAccount = TestFactory.createClientAccount();
        insert clientAccount;
        Account__c partnerAccount = TestFactory.createPartnerAccount();
        insert partnerAccount;
        Contract__c clientOverview = TestFactory.createClientOverview();
        clientOverview.RecordTypeId = Schema.SObjectType.Contract__c.getRecordTypeInfosByName().get('Client Overview').getRecordTypeId();
        clientOverview.Account__c = clientAccount.Id;
        clientOverview.Contract_Path__c = partnerAccount.Id;
        clientOverview.CSM__c = System.UserInfo.getUserId();
        clientOverview.Status__c ='Draft'; 
        clientOverview.Client_Overview_Status__c = 'Active';
        clientOverview.Contract_Termination_Date__c = Date.today();
        insert clientOverview;
        ContractStatusUpdateBatch sh1 = new ContractStatusUpdateBatch();
        String sch = '0 0 23 * * ?'; 
        Test.startTest();
        system.schedule('Test Territory Check', sch, sh1);
        DataBase.executeBatch(sh1); 
        Test.stopTest();         
    }
}