force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>LV Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>LV Contract</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Edits Controlled - Financially Material -  Flows to Redshift</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>LVGO_Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Client_Overview__c.field-meta.xml
<CustomField>
    <fullName>Client_Overview__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The parent Client Overview record to which an individual, program-specific Program Overview relates.</description>
    <inlineHelpText>The parent Client Overview contract record to which an individual, program-specific Program Overview relates. Integrated with Redshift.</inlineHelpText>
    <label>Client Overview</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>You must select a &quot;Client Overview&quot;</errorMessage>
        <filterItems>
            <field>Contract__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Client Overview</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Program Overviews</relationshipLabel>
    <relationshipName>ProgramOverviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/New_Device_Type__c.field-meta.xml
<CustomField>
    <fullName>New_Device_Type__c</fullName>
    <label>New Device Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HT900</fullName>
            </value>
            <value>
                <fullName>HTAND</fullName>
                <isActive>false</isActive>
                <label>HTAND</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <description>Integrated with NetSuite and Redshift</description>
    <inlineHelpText>Integrated with NetSuite and Redshift</inlineHelpText>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Diabetes</fullName>
            </value>
            <value>
                <fullName>Hypertension</fullName>
            </value>
            <value>
                <fullName>Prediabetes</fullName>
            </value>
            <value>
                <fullName>Weight Management</fullName>
            </value>
            <value>
                <fullName>Behavioral Health</fullName>
            </value>
            <value>
                <fullName>Chronic Kidney Disease</fullName>
            </value>
            <value>
                <fullName>Heart Failure</fullName>
            </value>
            <value>
                <fullName>A1C Test Kits</fullName>
            </value>
            <value>
                <fullName>A1C Test Kits - Results</fullName>
            </value>
            <value>
                <fullName>Diabetes Deviceflex</fullName>
            </value>
            <value>
                <fullName>Home Kidney Testing Program</fullName>
            </value>
            <value>
                <fullName>Home Kidney Testing Program - Results</fullName>
            </value>
            <value>
                <fullName>Advanced Weight Management (Select Populations)</fullName>
            </value>
            <value>
                <fullName>Comprehensive Weight Care (Select Populations)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LVGO_Automation_Switch__c/LVGO_Automation_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>LVGO Automation Switch</label>
</CustomObject>

force-app/main/default/objects/LVGO_Automation_Switch__c/fields/Flows__c.field-meta.xml
<CustomField>
    <fullName>Flows__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Switch to Control execution of  Flows</description>
    <inlineHelpText>Turning this flag on runs all the LVGO Flows</inlineHelpText>
    <label>Enable Flows</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVGO_Automation_Switch__c/fields/ProcessBuilders__c.field-meta.xml
<CustomField>
    <fullName>ProcessBuilders__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Switch to Control execution of  Process Builders</description>
    <inlineHelpText>Turning this flag on runs all the LVGO Process Builders</inlineHelpText>
    <label>Enable Process Builders</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVGO_Automation_Switch__c/fields/Triggers__c.field-meta.xml
<CustomField>
    <fullName>Triggers__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Switch to Control execution of  Triggers</description>
    <inlineHelpText>Turning this flag on runs all the LVGO Triggers</inlineHelpText>
    <label>Enable Triggers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ContractHistortyTrackingTest.cls
/**
* This class contains the test methods for chatter posts made on the Contract Service Apex Class .
* Created : 07/08/2020
* @author Virinchi Bairisetty
*/
@isTest
public class ContractHistortyTrackingTest {
    public static final List<Schema.FieldSetMember> contractTrackedFields = SObjectType.Contract__c.FieldSets.HistoryTracking.getFields();
    @isTest
    static void contractHistoryTrackingInsertOperation() {
        LVGO_Automation_Switch__c asw  =new LVGO_Automation_Switch__c();
        asw.Triggers__c  = true;
        asw.ProcessBuilders__c = true;
        asw.Flows__c = true;
        insert asw;
        
        List<Contract__c> newContracts = new List<Contract__c>();
        
        Account__c clientAccount = TestFactory.createClientAccount();
        insert clientAccount;
        
        Contract__c clientOverview = TestFactory.createClientOverview();
        clientOverview.Account__c = clientAccount.Id;
        insert clientOverview;
        
        Contract__c newProgramOverview = TestFactory.createProgramOverview();
        newProgramOverview.Program_Name__c = 'Diabetes';
        newProgramOverview.New_Device_Type__c = 'HT900';
        newProgramOverview.Client_Overview__c = clientOverview.Id;
        newProgramOverview.Account__c = clientAccount.Id;
        newContracts.add(newProgramOverview);
        insert newContracts;
        
        //ContractService.chatterTechOps(null, newContracts, null, 'Insert');
        system.assertEquals(1, newContracts.size());
    }
    
    @isTest
    static void contractHistoryTrackingDeleteOperation() {
        LVGO_Automation_Switch__c asw  =new LVGO_Automation_Switch__c();
        asw.Triggers__c  = true;
        asw.ProcessBuilders__c = true;
        asw.Flows__c = true;
        insert asw;
        
        Map<Id, Contract__c> oldContracts = new Map<Id, Contract__c>();
        List<Contract__c> oldContractsList = new List<Contract__c>();
        
        Account__c clientAccount = TestFactory.createClientAccount();
        insert clientAccount;
        
        Contract__c clientOverview = TestFactory.createClientOverview();
        clientOverview.Account__c = clientAccount.Id;
        insert clientOverview;
        
        Contract__c oldProgramOverview = TestFactory.createProgramOverview();
        oldProgramOverview.Account__c = clientAccount.Id;
        oldProgramOverview.Program_Name__c = 'Diabetes';
        oldProgramOverview.New_Device_Type__c = 'HT900';
        oldProgramOverview.Client_Overview__c = clientOverview.Id;
        oldContractsList.add(oldProgramOverview);
        insert oldContractsList;
        
        for (Contract__c oldCon : oldContractsList) {
            oldContracts.put(oldCon.Id, oldCon);
        }
        
        //ContractService.chatterTechOps(oldContracts, null, null, 'Delete');
        system.assertEquals(1, oldContracts.size());
    }
}