force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>LV Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountContactRelation__c/AccountContactRelation__c.object-meta.xml
<CustomObject>
    <label>Account Contact Relationship</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Contact Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountContactRelation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Account Contact Relations</relationshipLabel>
    <relationshipName>AccountContactRelations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact__c</referenceTo>
    <relationshipLabel>Account Contact Relations</relationshipLabel>
    <relationshipName>AccountContactRelations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation__c/fields/Roles__c.field-meta.xml
<CustomField>
    <fullName>Roles__c</fullName>
    <label>Roles</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Actuary / Data Analytics</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Billing POC</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Budget Approver</fullName>
            </value>
            <value>
                <fullName>Business Decision Maker</fullName>
            </value>
            <value>
                <fullName>Business Influencer</fullName>
            </value>
            <value>
                <fullName>Care Management Lead / POC</fullName>
            </value>
            <value>
                <fullName>Client Implementation Lead / POC</fullName>
            </value>
            <value>
                <fullName>Client Success Lead / POC</fullName>
            </value>
            <value>
                <fullName>Clinical Lead / POC</fullName>
            </value>
            <value>
                <fullName>Consulting Pharmacist</fullName>
            </value>
            <value>
                <fullName>Enrollment Marketing POC</fullName>
            </value>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>Gatekeeper</fullName>
            </value>
            <value>
                <fullName>Lead Consultant</fullName>
            </value>
            <value>
                <fullName>Legal Lead / POC</fullName>
            </value>
            <value>
                <fullName>Marketing Recipient</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Procurement Lead / POC</fullName>
            </value>
            <value>
                <fullName>Sales Lead / POC</fullName>
            </value>
            <value>
                <fullName>Scorecard Recipient</fullName>
            </value>
            <value>
                <fullName>Supporting ASO Executive - Commercial Partner Executive</fullName>
            </value>
            <value>
                <fullName>Supporting Consultant</fullName>
            </value>
            <value>
                <fullName>Supporting Other Partner Executive</fullName>
            </value>
            <value>
                <fullName>Supporting PBM Executive</fullName>
            </value>
            <value>
                <fullName>Technical Decision Maker</fullName>
            </value>
            <value>
                <fullName>Technical Influencer</fullName>
            </value>
            <value>
                <fullName>Telemedicine</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CHS_Contact_Roles__mdt/CHS_Contact_Roles__mdt.object-meta.xml
<CustomObject>
    <label>CHS Contact Roles</label>
    <pluralLabel>CHS Contact Roles</pluralLabel>
</CustomObject>

force-app/main/default/objects/CHS_Contact_Roles__mdt/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Client_Handoff_Summary__c/Client_Handoff_Summary__c.object-meta.xml
<CustomObject>
    <label>Client Handoff Summary</label>
    <nameField>
        <displayFormat>CHS# {00000}</displayFormat>
        <label>Client Handoff Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Handoff Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Handoff_Summary__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Client Handoff Summary</relationshipLabel>
    <relationshipName>Client_Handoff_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Handoff_Summary__c/fields/Client_Overview__c.field-meta.xml
<CustomField>
    <fullName>Client_Overview__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Overview</label>
    <referenceTo>Contract__c</referenceTo> 
    <relationshipLabel>Client Handoff Summary</relationshipLabel>
    <relationshipName>Client_Handoff_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact__c/Contact__c.object-meta.xml
<CustomObject>
    <label>LV Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact__c</referenceTo>
    <relationshipName>Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>FirstName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact__c/fields/Include_in_Client_Strategy_Calls_Emails__c.field-meta.xml
<CustomField>
    <fullName>Include_in_Client_Strategy_Calls_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include in Client Strategy Calls/Emails?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>LV Contract</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Edits Controlled - Financially Material -  Flows to Redshift</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>LVGO_Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Client_Overview__c.field-meta.xml
<CustomField>
    <fullName>Client_Overview__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The parent Client Overview record to which an individual, program-specific Program Overview relates.</description>
    <inlineHelpText>The parent Client Overview contract record to which an individual, program-specific Program Overview relates. Integrated with Redshift.</inlineHelpText>
    <label>Client Overview</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>You must select a &quot;Client Overview&quot;</errorMessage>
        <filterItems>
            <field>Contract__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Client Overview</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Program Overviews</relationshipLabel>
    <relationshipName>ProgramOverviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <description>Integrated with NetSuite and Redshift</description>
    <inlineHelpText>Integrated with NetSuite and Redshift</inlineHelpText>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Diabetes</fullName>
            </value>
            <value>
                <fullName>Hypertension</fullName>
            </value>
            <value>
                <fullName>Prediabetes</fullName>
            </value>
            <value>
                <fullName>Weight Management</fullName>
            </value>
            <value>
                <fullName>Behavioral Health</fullName>
            </value>
            <value>
                <fullName>Chronic Kidney Disease</fullName>
            </value>
            <value>
                <fullName>Heart Failure</fullName>
            </value>
            <value>
                <fullName>A1C Test Kits</fullName>
            </value>
            <value>
                <fullName>A1C Test Kits - Results</fullName>
            </value>
            <value>
                <fullName>Diabetes Deviceflex</fullName>
            </value>
            <value>
                <fullName>Home Kidney Testing Program</fullName>
            </value>
            <value>
                <fullName>Home Kidney Testing Program - Results</fullName>
            </value>
            <value>
                <fullName>Advanced Weight Management (Select Populations)</fullName>
            </value>
            <value>
                <fullName>Comprehensive Weight Care (Select Populations)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

manifest/classes/LVGO__ClientHandoffSummaryController.cls
public with sharing class ClientHandoffSummaryController {
    public static List<CHS_Contact_Roles__mdt> accConRolesMDT {get; set;}
    static {
        CHS_Contact_Roles__mdt[] conRoles = [SELECT Role__c FROM CHS_Contact_Roles__mdt];
        accConRolesMDT = conRoles;
    }
    @AuraEnabled(cacheable=true)
    public static List<Contract__c> getPrograms(Id clientHandoffId){
        Client_Handoff_Summary__c clientHandoffSummary = getClientHandoffSummaryRecord(clientHandoffId);
        Id clientOverviewId = clientHandoffSummary.Client_Overview__c;
        List<Contract__c> contractList = [SELECT Id, Program_Name__c FROM Contract__c WHERE Client_Overview__c =: clientOverviewId];
        return contractList;
    }
    @AuraEnabled(cacheable=true)
    public static List<AccountContactRelation__c> getAccountContactRelationships(Id clientHandoffId) {
        String roleString = '';
        for(CHS_Contact_Roles__mdt crm: accConRolesMDT) {
            roleString += '\'' + crm.Role__c + '\',';
        }
        roleString = roleString.removeEnd(',');
        Client_Handoff_Summary__c clientHandoffSummary = getClientHandoffSummaryRecord(clientHandoffId);
        Id taskRayAccountId = clientHandoffSummary.Account__c;
        String queryString = 'SELECT Id, Account__c, Contact__c, Account__r.Name, Contact__r.Name, Contact__r.Email__c, Contact__r.Phone__c, Contact__c.Description__c,'+ 
                                'Roles__c, Contact__r.Title__c, Contact__r.Account__r.Name,'+
                                'Contact__r.FirstName__c, Contact__r.LastName__c FROM AccountContactRelation__c WHERE Account__c =: taskRayAccountId AND Roles__c includes (' + roleString +')'; //Contact.Include_in_Client_Strategy_Calls_Emails__c, 
        List<AccountContactRelation__c> accConRelList = Database.Query(queryString);
        return accConRelList;
    }
    private static Client_Handoff_Summary__c getClientHandoffSummaryRecord(Id chsId) {
        return [SELECT Id, Client_Overview__c, Account__c
                 FROM Client_Handoff_Summary__c WHERE Id =: chsId LIMIT 1]; //TaskRay_Project__c,
    }
}