manifest/objects/Account.object
<CustomObject>
    <fields>
        <fullName>L2O_Amendment_Opportunity_SubType__c</fullName>
        <description>To capture the Amendment Opportunity Sub Type 
[Transaction Type] via the Manage Install Base account
 button for amendment flow.</description>
        <label>Amendment Opportunity SubType</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

manifest/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contract.object
    <fields>
        <fullName>L2O_Amendment_Opportunity_SubType__c</fullName>
        <description>In order enable Amend functionality on contract, Please update the field to either Expansion or Change Order.</description>
        <inlineHelpText>In order enable Amend functionality on contract, Please update the field to either Expansion or Change Order.</inlineHelpText>
        <label>Amendment Opportunity SubType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Change Order</fullName>
                </value>
                <value>
                    <fullName>Recontracting</fullName>
                </value>
                <value>
                    <fullName>Contract Path Change</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                    <isActive>false</isActive>
                    <label>Expansion</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Contract.object
    <fields>
        <fullName>L2O_Channel_Segment__c</fullName>
        <label>Channel Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Employer</fullName>
                </value>
                <value>
                    <fullName>Health Plan</fullName>
                </value>
                <value>
                    <fullName>Client Management</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Hospital &amp; Health System (HHS)</fullName>
                </value>
                <value>
                    <fullName>Partner (Broker)</fullName>
                    <isActive>false</isActive>
                    <label>Partner (Broker)</label>
                </value>
                <value>
                    <fullName>Partner (Consultant)</fullName>
                    <isActive>false</isActive>
                    <label>Partner (Consultant)</label>
                </value>
                <value>
                    <fullName>Partner (Reseller)</fullName>
                    <isActive>false</isActive>
                    <label>Partner (Reseller)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Contract.object
    <fields>
        <fullName>L2O_Client_Line_of_Business__c</fullName>
        <description>Twin field from Contract to Renewal Opportunity</description>
        <label>Client Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Client_Line_of_Business</valueSetName>
        </valueSet>
    </fields>

objects/Contract.object
    <fields>
        <fullName>L2O_Contract_Path__c</fullName>
        <label>Contract Path</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contract_Path</valueSetName>
        </valueSet>
    </fields>

objects/Contract.object
    <fields>
        <fullName>L2O_Contract_Path_Sub_type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contract_Path_Sub_Types</valueSetName>
        </valueSet>
    </fields>

manifest/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2O_Channel_Segment__c</fullName>
        <description>Which of the 5 segments (Employer, Health Plan, Client Management, INTL, HHS) is this Opportunity a part of?</description>
        <label>Channel Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Employer</fullName>
                </value>
                <value>
                    <fullName>Health Plan</fullName>
                </value>
                <value>
                    <fullName>Client Management</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Hospital &amp; Health System (HHS)</fullName>
                </value>
                <value>
                    <fullName>Partner (Broker)</fullName>
                    <isActive>false</isActive>
                    <label>Partner (Broker)</label>
                </value>
                <value>
                    <fullName>Partner (Consultant)</fullName>
                    <isActive>false</isActive>
                    <label>Partner (Consultant)</label>
                </value>
                <value>
                    <fullName>Partner (Reseller)</fullName>
                    <isActive>false</isActive>
                    <label>Partner (Reseller)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2O_Contract_Path_Sub_type__c</fullName>
        <description>Does the Contract Path have: No pricing, Contracted Pricing or New Pricing</description>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contract_Path_Sub_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2O_Contract_Path__c</fullName>
        <description>How should this Opportunity be Contracted?</description>
        <label>Contract Path</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contract_Path</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2O_Initial_of_Lives__c</fullName>
        <description># of Employees or Members, in this piece of Business</description>
        <inlineHelpText>Number of lives, either employees OR members, to be closed (formerly \Initial # of Lives\&quot;). Should be only what will be acquired if this particular piece of business is closed - not the total number at the company. SALES REPS: Be conservative!&quot;</inlineHelpText>
        <label>Number of Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>L2O_Subtype__c</fullName>
        <label>Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Sale</fullName>
                </value>
                <value>
                    <fullName>Initial Sale - Partner</fullName>
                </value>
                <value>
                    <fullName>Hunting License</fullName>
                </value>
                <value>
                    <fullName>Pilot</fullName>
                </value>
                <value>
                    <fullName>Change Order</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Pilot to Paid Conversion</fullName>
                </value>
                <value>
                    <fullName>Attrition / Expiry</fullName>
                </value>
                <value>
                    <fullName>Pilot Extension</fullName>
                </value>
                <value>
                    <fullName>Contract Path Change</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                    <isActive>false</isActive>
                    <label>Expansion</label>
                </value>
                <value>
                    <fullName>Expansion / Add-On</fullName>
                    <isActive>false</isActive>
                    <label>Expansion / Add-On</label>
                </value>
                <value>
                    <fullName>Initial Sale - Direct</fullName>
                    <isActive>false</isActive>
                    <label>Initial Sale - Direct</label>
                </value>
                <value>
                    <fullName>New Population</fullName>
                    <isActive>false</isActive>
                    <label>New Population</label>
                </value>
                <value>
                    <fullName>Recontracting</fullName>
                    <isActive>false</isActive>
                    <label>Recontracting</label>
                </value>
                <value>
                    <fullName>Renewal + Expansion</fullName>
                    <isActive>false</isActive>
                    <label>Renewal + Expansion</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__AmendedContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the relationship to your Amended Contract.</description>
        <inlineHelpText>Lookup to your Amended Contract.</inlineHelpText>
        <label>Amended Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Amendment Opportunities</relationshipLabel>
        <relationshipName>AmendmentOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Contracted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Internal flag used to kick off automatic asset and subscription conversion.</description>
        <inlineHelpText>Salesforce CPQ uses this field to automatically convert assets and subscriptions.</inlineHelpText>
        <label>Contracted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__PrimaryQuote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Points to primary quote on this opportunity.</description>
        <inlineHelpText>Salesforce CPQ uses this to point to the primary quote on this opportunity.</inlineHelpText>
        <label>Primary Quote</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>PrimaryOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

manifest/objects/Order.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Contracted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the order is contracted.</description>
        <inlineHelpText>Indicates if the order is contracted.</inlineHelpText>
        <label>Contracted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/globalValueSets/Client_Line_of_Business.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Commercial ASO - Opt In</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial ASO - Opt Out</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial FI</fullName>
    </customValue>
    <customValue>
        <fullName>Dual Eligibles</fullName>
    </customValue>
    <customValue>
        <fullName>Exchange</fullName>
    </customValue>
    <customValue>
        <fullName>Managed Medicaid</fullName>
    </customValue>
    <customValue>
        <fullName>Medicare Advantage</fullName>
    </customValue>
    <customValue>
        <fullName>Other Government</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial ASO​</fullName>
        <isActive>false</isActive>
        <label>Commercial ASO​</label>
    </customValue>
    <masterLabel>Client Line of Business</masterLabel>
</GlobalValueSet>

manifest/globalValueSets/Contract_Path.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>US Health Plan</fullName>
    </customValue>
    <customValue>
        <fullName>Complex Case Mgmt</fullName>
    </customValue>
    <customValue>
        <fullName>TPA/Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital &amp; Health Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Intl Insurer</fullName>
    </customValue>
    <customValue>
        <fullName>Cross-Sell</fullName>
        <isActive>false</isActive>
        <label>Cross-Sell</label>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
        <isActive>false</isActive>
        <label>Broker</label>
    </customValue>
    <customValue>
        <fullName>Carrier</fullName>
        <isActive>false</isActive>
        <label>Carrier</label>
    </customValue>
    <customValue>
        <fullName>Canada Direct</fullName>
        <isActive>false</isActive>
        <label>Canada Direct</label>
    </customValue>
    <customValue>
        <fullName>Canada Insurance (New)</fullName>
        <isActive>false</isActive>
        <label>Canada Insurance (New)</label>
    </customValue>
    <customValue>
        <fullName>Canada Insurance (Exist)</fullName>
        <isActive>false</isActive>
        <label>Canada Insurance (Exist)</label>
    </customValue>
    <description>Values as per TDUAT</description>
    <masterLabel>Contract Path</masterLabel>
</GlobalValueSet>

globalValueSets/Contract_Path_Sub_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>Contracted Pricing</fullName>
    </customValue>
    <customValue>
        <fullName>New Pricing</fullName>
    </customValue>
    <masterLabel>Contract Path Sub Types</masterLabel>
</GlobalValueSet>

classes/L2O_OpportunityTriggerHelperService_Test.cls
/**
* Company : PwC.
* @description : Test Class for L2O_OpportunityTriggerHelperService
* ************************************************************************************************************************************
* History : 
* @date 14/06/2022
* @author Harshita Paliwal
*/
@isTest
public class L2O_OpportunityTriggerHelperService_Test {
    // String field variables
    public static String strAccepted = 'Accepted';
    public static Id pricebookId = Test.getStandardPricebookId();
    @testSetup
    /**
* @name  testSetup()
* @description Sets up Test Data for the Class
* @params  none
*/ 
     static void testSetup() {
         List<Account> accountList= L2O_DataFactoryTest.createAccount(true,2);
         List<Contact> conList =  L2O_DataFactoryTest.createContact(true,accountList); 
         List<Opportunity> oppList =  L2O_DataFactoryTest.createOpportunity(true,accountList); 
         L2O_DataFactoryTest.createContactRoles(true,oppList,conList[0].id);    
         List<SBQQ__Quote__c> quoteList =  L2O_DataFactoryTest.createQuote(true,oppList);    
         L2O_DataFactoryTest.createContract(oppList,QuoteList,accountList[0].id);  
        L2O_DataFactoryTest.createTeladocAccount();
        }
    
    /**
* @name testUpdateCancelRipOpptyToContracted()
* @description Tests whether cancelled rip opportunity stage is closed won or not
* @params  none
*/ 
     @isTest static void testUpdateCancelRipOpptyToContracted() { 
        Test.startTest();
        //create a contract record
        Contract contractRec = [SELECT Id,contractnumber FROM Contract WHERE ContractTerm = 12 LIMIT 1]; 
        //create quote list
        List<SBQQ__Quote__c> lstQuote = new List<SBQQ__Quote__c>();
        for(SBQQ__Quote__c quoteRec : [SELECT Id,SBQQ__Status__c,SBQQ__Primary__c
                                     FROM SBQQ__Quote__c 
                                      WHERE  SBQQ__Status__c != null] ){
               quoteRec.SBQQ__Status__c = strAccepted ;
               quoteRec.SBQQ__Primary__c = true;                           
                lstQuote.add(quoteRec);
            }
         update lstQuote;
       //create opportunity list
       List<Opportunity> lstOppty = [SELECT Id,Name,stageName,SBQQ__PrimaryQuote__c 
                                     FROM Opportunity 
                                     WHERE Name != null];
         for(integer count = 0;count<lstOppty.size();count++){
             lstOppty[count].SBQQ__PrimaryQuote__c = lstQuote[count].Id; 
             if(count == 0){
                 
                 lstOppty[count].Name = L2O_Constants.RIP_REPLACE_OPPTY_PREFIX_NAME+contractRec.contractnumber+'-'+DateTime.now();
                 lstOppty[count].stageName = L2O_Constants.OPPTY_STAGE_CLOSED_OWN;
              }
         }
        update lstOppty;
        //fetching opportunity and cancelled opportunity
        Opportunity rNrOpportunity=[SELECT Id,SBQQ__Contracted__c,StageName,Name,SBQQ__PrimaryQuote__c 
                                                    FROM Opportunity 
                                                    WHERE Name LIKE 'Rip And Replace- contract%' LIMIT 1];
         Opportunity cancelledOpportunity = [SELECT Id,SBQQ__Contracted__c,StageName 
                                                    FROM Opportunity 
                                                    WHERE Id =:rNrOpportunity.Id OR SBQQ__PrimaryQuote__r.L2O_Replacement_Quote__c =:rNrOpportunity.SBQQ__PrimaryQuote__c LIMIT 1];
         System.assertEquals(rNrOpportunity.StageName,cancelledOpportunity.StageName,'Cancelled opportunity is closed won!');
        Test.stopTest();     
     }
    
    /**
* @name testupdateAmendOpptyFrmContract()
* @description Tests whether amend opportunity subtype is getting populated from contract 
* @params  none
*/ 
    @isTest static void testupdateAmendOpptyFrmContract(){
         Test.startTest();
         //create contract
         Contract contractRec = [SELECT Id,contractnumber,L2O_Amendment_Opportunity_SubType__c,AccountId FROM Contract WHERE ContractTerm = 12 LIMIT 1];
         contractRec.L2O_Amendment_Opportunity_SubType__c = 'Change Order';
         //update contract 
         update contractRec;
         //create amendment opportunity and insert it
         Opportunity amendOpp=new Opportunity(Name='Amendment',
                                AccountId=contractRec.AccountId,
                                Type='Existing Business',
                                stageName='Discovery',
                                CloseDate=date.today().addMonths(2),
                                SBQQ__AmendedContract__c=contractRec.Id,
                                L2O_Initial_of_Lives__c=2300,
                                Pricebook2Id = pricebookId,
                                L2O_Contract_Path__c = 'Direct',
                                L2O_Contract_Path_Sub_type__c = 'None',
                                L2O_Channel_Segment__c ='Employer',
                                L2O_Subtype__c = 'Change Order',
                                L2O_Client_Line_of_Business__c = 'Commercial FI');
         insert amendOpp;
        //fetch and the same opportunity 
         Opportunity opptyRecAfterSubTypeSet = [SELECT Id,Type,Name,stageName,L2O_Subtype__c,SBQQ__AmendedContract__c
                                                  FROM Opportunity 
                                                  WHERE Id =:amendOpp.Id LIMIT 1];
         System.assertEquals(opptyRecAfterSubTypeSet.L2O_Subtype__c,contractRec.L2O_Amendment_Opportunity_SubType__c,'amend opportunity subtype verified');
         Test.stopTest();   
    }
     /**
* @name testupdateOpptyFromAccount()
* @description Tests whether opportunity subtype and business region is getting populated from account 
* @params  none
*/ 
    @isTest static void testupdateOpptyFromAccount(){ 
        Id accId;
        Test.startTest();
        // update Account
        List<Account> accountList=[SELECT Id, L2O_Business_Region__c,L2O_Amendment_Opportunity_SubType__c, Name FROM Account WHERE Name != null];
        accId = accountList[0].Id;
        accountList[0].L2O_Amendment_Opportunity_SubType__c = 'Change Order';
        update accountList;
        
        //create Opportunity
        Opportunity opp=new Opportunity(Name='Opportunity',
            Type='Existing Business',
            L2O_Subtype__c='Change Order',
            L2O_Initial_of_Lives__c=2300,
            Pricebook2Id = pricebookId,
            L2O_Contract_Path__c = 'Direct',
            L2O_Contract_Path_Sub_type__c = 'None',
            L2O_Channel_Segment__c ='Employer',
            stageName='Discovery',
            CloseDate=date.today().addMonths(2),
            L2O_Client_Line_of_Business__c = 'Commercial FI');
        Opp.L2O_IsAccountAmendAssets__c = TRUE;
        
        opp.AccountId=accId;
        opp.Name=System.Label.L2O_AmendOppDefaultName;
        insert opp;
        List<Account> accUpdtList = [SELECT Id, L2O_Business_Region__c,L2O_Amendment_Opportunity_SubType__c, Name FROM Account WHERE Id =:accId];
        List<Opportunity> oppUpdtList = [SELECT Id, L2O_Subtype__c,L2O_Business_Region__c, Name FROM Opportunity WHERE id=: opp.id];
        System.assertEquals(oppUpdtList[0].L2O_Business_Region__c,accUpdtList[0].L2O_Business_Region__c,'opportunity business region verified');
        System.assertEquals(oppUpdtList[0].L2O_Subtype__c,accUpdtList[0].L2O_Amendment_Opportunity_SubType__c,'opportunity subtype verified');
        Test.stopTest();   
    }
    /**
* @name testupdateOpportunity()
* @description Tests whether opportunity is getting contracted checked after stagename='closed won'
* @params  none
*/ 
    @isTest static void testupdateOpportunity(){
        Test.startTest();
        //create opportunity list
        List<Opportunity> lstOppty=[SELECT Id,Name,stageName,L2O_Business_Region__c,L2O_Subtype__c,SBQQ__Contracted__c,SBQQ__PrimaryQuote__c
                                     FROM Opportunity 
                                     WHERE (Name != null AND StageName!='Closed Won' AND SBQQ__Contracted__c = FALSE AND (NOT Name LIKE '%Rip And Replace- contract%'))];
        //create quote list
        List<SBQQ__Quote__c> lstQuote = new List<SBQQ__Quote__c>();
        // fetch quote asscociated to opportunity and accept it and add to quote list
        for(SBQQ__Quote__c quoteRec : [SELECT Id,SBQQ__Status__c,SBQQ__Primary__c,SBQQ__Opportunity2__c
                                     FROM SBQQ__Quote__c 
                                      WHERE  SBQQ__Status__c != null AND SBQQ__Opportunity2__c =:lstOppty[0].Id LIMIT 1] ){
               quoteRec.SBQQ__Status__c = strAccepted ;                      
              
               quoteRec.SBQQ__Primary__c = true;                           
               lstQuote.add(quoteRec);
            }
        //update quote list
        update lstQuote;
        //fetch opportunity record where SBQQ__PrimaryQuote__c =:lstQuote[0].Id and close won it
        Opportunity oppRec = [SELECT Id,Name,stageName,L2O_Business_Region__c,L2O_Subtype__c,SBQQ__Contracted__c,SBQQ__PrimaryQuote__c
                                     FROM Opportunity 
                                     WHERE SBQQ__PrimaryQuote__c =:lstQuote[0].Id];
       oppRec.stageName='Closed Won';
       //update opportunity record
       update oppRec;
       //fetch the opportunity 
       Opportunity oppRecTest = [SELECT Id,Name,stageName,L2O_Business_Region__c,L2O_Subtype__c,SBQQ__Contracted__c,SBQQ__PrimaryQuote__c
                                     FROM Opportunity 
                                     WHERE Id =:oppRec.Id];
       System.assertEquals(oppRecTest.SBQQ__Contracted__c,TRUE,'Contracted is true');
       Test.stopTest();   
        
    }
     /**
* @name testupdateRenewalOpptyFrmOriginalOppty()
* @description Tests whether renewal opportunity subtype is getting populated from original opportunity
* @params  none
*/ 
    @isTest static void testupdateRenewalOpptyFrmOriginalOppty(){
       Test.startTest();
       //fetch contract
       Contract contractRec = [SELECT Id,AccountId,contractNumber,SBQQ__Opportunity__r.L2O_Subtype__c,SBQQ__Opportunity__r.OwnerId,SBQQ__Opportunity__c  FROM Contract WHERE ContractTerm = 12 LIMIT 1];
       // fetch opportunity record and make subtype=pilot and update it
       Opportunity oppRec = [SELECT Id,L2O_Subtype__c FROM Opportunity WHERE Id =: contractRec.SBQQ__Opportunity__r.Id LIMIT 1];
       oppRec.L2O_Subtype__c =  L2O_Constants.RENEWAL_OPPTY_SUB_TYPE_PILOT;
       update oppRec;
        //create renewal opportunity and insert it
       Opportunity renewalOpp=new Opportunity(Name='Renewal',
       AccountId=contractRec.AccountId,Type='New Business',
       stageName='Discovery',CloseDate=date.today().addMonths(2),
       L2O_Subtype__c='Initial Sale',
       L2O_Initial_of_Lives__c=2300,
       Pricebook2Id = pricebookId,
       L2O_Contract_Path__c = 'Direct',
       L2O_Contract_Path_Sub_type__c = 'None',
       L2O_Channel_Segment__c ='Employer',                       
       SBQQ__Renewal__c=TRUE,
       SBQQ__RenewedContract__c=contractRec.Id); 
       insert renewalOpp;
       //fetch renewal opportunity 
       Opportunity renewalOppTest=[SELECT Id,L2O_Subtype__c FROM Opportunity WHERE Id =:renewalOpp.Id LIMIT 1];
       System.assertEquals(L2O_Constants.RENEWAL_OPPTY_SUB_TYPE_PILOT_EXT,renewalOppTest.L2O_Subtype__c,'renewal opportunity subtype is Pilot Extension'); 
       Test.stopTest();
    }
    
    /**
* @name testupdatePrimaryQuote()
* @description Tests whether quote's business region is getting populated from opportunity
* @params  none
*/ 
      @isTest static void testupdatePrimaryQuote(){ //done
        Test.startTest();
        //create opportunity list
        List<Account> acclist=[Select Id from Account];
        List<Opportunity> lstOppty=[SELECT Id,Name,stageName,L2O_Business_Region__c,L2O_Subtype__c,AccountId,L2O_Contracting_Account__c
                                     FROM Opportunity WHERE Name LIKE '%Test_Opportunity%'];
         //system.debug(lstOppty);
         List<SBQQ__Quote__c> setprimaryquotes=new List<SBQQ__Quote__c>();
         for(SBQQ__Quote__c qre:[SELECT Id,SBQQ__Opportunity2__c,L2O_Business_Region__c FROM SBQQ__Quote__c where SBQQ__Opportunity2__c=:lstOppty[0].Id limit 1])
         {
           SBQQ__Quote__c qrec=new SBQQ__Quote__c(Id=qre.Id,SBQQ__Primary__c=true);
            setprimaryquotes.add(qrec); 
         }
         update setprimaryquotes;  
        //create a set of opportunity Id's
        Set<Id> lstOpptyId= new Set<Id>();
          for(Opportunity  opp: lstOppty){
              lstOpptyId.add(opp.Id);
          }
        //change the business region
        lstOppty[0].L2O_Business_Region__c='USA';
        //Change account
        lstOppty[0].AccountId=acclist[1].Id;
        //Change contracting account
        lstOppty[0].L2O_Contracting_Account__c=acclist[1].Id;  
        update lstOppty[0]; 
                   
        //create list of primary quotes
        List<SBQQ__Quote__c> lstPrimaryQuotes = [SELECT Id, SBQQ__Opportunity2__c,L2O_Business_Region__c FROM SBQQ__Quote__c  
                                                     WHERE SBQQ__Primary__c = TRUE
                                                     AND SBQQ__Opportunity2__c IN :lstOpptyId];
         
         If(!lstPrimaryQuotes.isEmpty()){
                
                for(SBQQ__Quote__c quote: lstPrimaryQuotes){
                    System.assertEquals(quote.L2O_Business_Region__c ,lstOppty[0].L2O_Business_Region__c,'quote business region verified'); 
                }
               
            }
        Test.stopTest();
      }
    
     
    /**
* @name testSendEmailOnInternlOppClosedWon()
* @description Tests whether International Email sent on Opportunity closedwon
* @params  none
*/ 
   @isTest static void testSendEmailOnInternlOppClosedWon(){ 
        Id accId;
        List<Account> accountList= [SELECT Id, L2O_Business_Region__c, Name FROM Account WHERE Name != null LIMIT 1];
        accId = accountList[0].Id;
        accountList[0].L2O_Business_Region__c = 'Canada';
        update accountList;
        List<Account> updtAccList = [SELECT Id, L2O_Business_Region__c, Name FROM Account WHERE Id =:accId LIMIT 1];
        List<Contact> conList = [SELECT Id FROM Contact WHERE LastName != NULL LIMIT 1];
        List<Opportunity> oppList =  L2O_DataFactoryTest.createOpportunity(true,accountList);
        L2O_DataFactoryTest.createContactRoles(true,oppList,conList[0].id);    
        List<SBQQ__Quote__c> quoteList =  L2O_DataFactoryTest.createQuote(true,oppList);
       List<Product2> prodList = L2O_DataFactoryTest.createProduct();
       List<Asset> asstList = L2O_DataFactoryTest.createAsset(true,accId,prodList);
       List<SBQQ__Quoteline__c> quoteLineList =  L2O_DataFactoryTest.createQuoteLines(true,quoteList,prodList,asstList); 
        
        //Update quote list
        List<SBQQ__Quote__c> lstQuote = new List<SBQQ__Quote__c>();
        for(SBQQ__Quote__c quoteRec : quoteList){
                                           quoteRec.SBQQ__Status__c = strAccepted ;
                                           quoteRec.SBQQ__Primary__c = true;                           
                                           lstQuote.add(quoteRec);
                                       }
        if(!lstQuote.isEmpty()){
            update lstQuote;
        }
       List<SBQQ__Quoteline__c> quotLIList = new List<SBQQ__Quoteline__c>();
        FOR(SBQQ__Quoteline__c tempQli : quoteLineList) {
            tempQli.L2O_Service_Platform__c = 'INTL';
            tempQli.L2O_Business_Region_rev__c = 'Canada';
            quotLIList.add(tempQli);
        }
        if(!quotLIList.isEmpty()){
            update quotLIList;
        }
        
        //Update opportunity list
        Test.startTest();
        List<Opportunity> lstOppty = [SELECT Id,Name,stageName,SBQQ__PrimaryQuote__c,SBQQ__Ordered__c,L2O_Business_Region__c
                                      FROM Opportunity 
                                      WHERE Id=:oppList[0].Id];
        
        lstOppty[0].SBQQ__PrimaryQuote__c = lstQuote[0].Id; 
        lstOppty[0].stageName = L2O_Constants.OPPTY_STAGE_CLOSED_OWN;
        update lstOppty;
         System.assertEquals(updtAccList[0].L2O_Business_Region__c,'Canada','');
        Test.stopTest();
        
    }
    /**
* @name testSendEmailOnUSAOppClosedWon()
* @description Tests whether USA Email sent on Opportunity closedwon
* @params  none
*/ 
    @isTest static void testSendEmailOnUSAOppClosedWon(){ 
        Id accId;
        
        List<Account> accountList= [SELECT Id, L2O_Business_Region__c, Name FROM Account WHERE Name != null LIMIT 1];
        accId = accountList[0].Id;
        List<Product2> prodList = L2O_DataFactoryTest.createProduct();
        List<Asset> asstList = L2O_DataFactoryTest.createAsset(true,accId,prodList);
        // update account record
        accountList[0].L2O_Business_Region__c = 'USA';
        update accountList;
        
         List<Account> updtAccList = [SELECT Id, L2O_Business_Region__c, Name FROM Account WHERE Id =:accId LIMIT 1];
        List<Contact> conList = [SELECT Id FROM Contact WHERE LastName != NULL LIMIT 1];
        List<Opportunity> oppList =  L2O_DataFactoryTest.createOpportunity(true,accountList);
        
        L2O_DataFactoryTest.createContactRoles(true,oppList,conList[0].id);    
        List<SBQQ__Quote__c> quoteList =  L2O_DataFactoryTest.createQuote(true,oppList); 
        List<SBQQ__Quoteline__c> quoteLineList =  L2O_DataFactoryTest.createQuoteLines(true,quoteList,prodList,asstList);
        
        //Update quote list
        List<SBQQ__Quote__c> lstQuote = new List<SBQQ__Quote__c>();
        for(SBQQ__Quote__c quoteRec : quoteList){
                                           quoteRec.SBQQ__Status__c = strAccepted ;
                                           quoteRec.SBQQ__Primary__c = true;                           
                                           lstQuote.add(quoteRec);
                                       }
        if(!lstQuote.isEmpty() && !quoteLineList.isEmpty()){
            update lstQuote;
        }
        // update Quote Lines
        List<SBQQ__Quoteline__c> quotLIList = new List<SBQQ__Quoteline__c>();
        quoteLineList[0].L2O_Service_Platform__c = 'TDH';
        quoteLineList[0].L2O_Business_Region_rev__c = 'USA';
        quotLIList.add(quoteLineList[0]);
        if(!quotLIList.isEmpty()){
            update quotLIList;
        }
        // update Opportunity Line Item
        List<OpportunityLineItem> oppLIList = new List<OpportunityLineItem>();
        FOR(OpportunityLineItem tempoPli : [SELECT id, OpportunityId,L2O_Service_Platform__c
                                            FROM OpportunityLineItem 
                                            WHERE  OpportunityId =:oppList[0].Id]) {
                                                tempoPli.L2O_Service_Platform__c = 'HHS';
                                                oppLIList.add(tempoPli);
                                            }
        if(!oppLIList.isEmpty()){
            update oppLIList;
        }
        //Update opportunity list
        Test.startTest();
        List<Opportunity> lstOppty = [SELECT Id,Name,stageName,SBQQ__PrimaryQuote__c,SBQQ__Ordered__c,L2O_Business_Region__c
                                      FROM Opportunity 
                                      WHERE Id=:oppList[0].Id];
       lstOppty[0].stageName = L2O_Constants.OPPTY_STAGE_CLOSED_OWN;
       update lstOppty;
        System.assertEquals(updtAccList[0].L2O_Business_Region__c,lstOppty[0].L2O_Business_Region__c,'');
        Test.stopTest();
        
        
        
    }
    
    /**
    * @name testPreSalePlatformEvent()
    * @description Tests the PreSalePlatformEvent
    * @params  none
    */ 
    @isTest static void testPreSalePlatformEvent() {
        List<Account> accountList= [SELECT Id, L2O_Business_Region__c, Name FROM Account WHERE Name != null LIMIT 1];
        List<Opportunity> oppList =  L2O_DataFactoryTest.createOpportunity(true,accountList);
        for (Opportunity opp: oppList) {
            opp.Early_Implementation__c = true;
            opp.Pricing_and_Product_Lock__c = true;
        }
        Test.startTest();
        update oppList;
        System.assertEquals(oppList[0].Early_Implementation__c, true, 'Early Implementation Checkbox');
        System.assertEquals(oppList[0].Pricing_and_Product_Lock__c, true, 'Pricing and Product Lock Checkbox');
        Test.stopTest();
    }
    }