manifest/objects/Account.object
<CustomObject>
    <fields>
        <fullName>L2O_GUID__c</fullName>
        <description>System Generated Global Unique Id</description>
        <externalId>true</externalId>
        <inlineHelpText>System Generated Global UniqueId</inlineHelpText>
        <label>GUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

manifest/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>L2O_GUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/L2O_AgreementTriggerHelperService.cls
/**
* Company : PwC.
* @description : L2O_AgreementTriggerHelperService will be executed from the L2O_AgreementTriggerHandler and will update GUID Profile field on Agreement
* *****************************************************************************************************************************************
* History : 
* @date 03/06/2022
* @author Aviral Dhodi
*/

public without sharing class L2O_AgreementTriggerHelperService {
    
    /**
* @name  setGUID
* @description setGUID
* @param  newAgreements for trigger.new Agreement
**/
    public void setGUID(List<Apttus__APTS_Agreement__c> newAgreements) {
        
        Set<String> allGuids = new Set<String>();
        for (Apttus__APTS_Agreement__c tempAgreement : newAgreements) {
            
            // Create new GUID if account is new or has invalid GUID
            
            if (String.isBlank(tempAgreement.L2O_GUID__c) || !L2O_GlobalIdUtils.isGuid(tempAgreement.L2O_GUID__c)) {
                tempAgreement.L2O_GUID__c = L2O_GlobalIdUtils.generateGuid();
                allGuids.add(tempAgreement.L2O_GUID__c);
            }
            
            else {
                allGuids.add(tempAgreement.L2O_GUID__c);
            }
            
        }
    }
}