manifest/objects/Account.object
<CustomObject>
    <fields>
        <fullName>L2O_Amendment_Opportunity_SubType__c</fullName>
        <description>To capture the Amendment Opportunity Sub Type 
[Transaction Type] via the Manage Install Base account
 button for amendment flow.</description>
        <label>Amendment Opportunity SubType</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

manifest/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity from which this Contract was created.</description>
        <inlineHelpText>The Opportunity from which this Contract was created.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contract.object
    <fields>
        <fullName>L2O_Amendment_Opportunity_SubType__c</fullName>
        <description>In order enable Amend functionality on contract, Please update the field to either Expansion or Change Order.</description>
        <inlineHelpText>In order enable Amend functionality on contract, Please update the field to either Expansion or Change Order.</inlineHelpText>
        <label>Amendment Opportunity SubType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Change Order</fullName>
                </value>
                <value>
                    <fullName>Recontracting</fullName>
                </value>
                <value>
                    <fullName>Contract Path Change</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                    <isActive>false</isActive>
                    <label>Expansion</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/L2O_ManageInstallBase__mdt.object
<CustomObject>
    <description>To contain all the text from the flow Manage Install Base from Account object.</description>
    <fields>
        <fullName>L2O_AllContractsHeader__c</fullName>
        <label>L2O_AllContractsHeader</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>L2O_AmendAssetsOnly__c</fullName>
        <label>L2O_AmendAssetsOnly</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>L2O_AmendBothOption__c</fullName>
        <label>L2O_AmendBothOption</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>L2O_AmendOptionHeader__c</fullName>
        <label>L2O_AmendOptionHeader</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>L2O_AmendSubTypeHeader__c</fullName>
        <label>L2O_AmendSubTypeHeader</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>L2O_ChangeOrderOption__c</fullName>
        <label>L2O_ChangeOrderOption</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>L2O_ContractListNote2__c</fullName>
        <label>L2O_ContractListNote2</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>L2O_ContractListNote__c</fullName>
        <label>L2O_ContractListNote</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>L2O_ContractPathChangeOption__c</fullName>
        <label>L2O_ContractPathChangeOption</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>L2O_CpqAccountAmendURL__c</fullName>
        <label>L2O_CpqAccountAmendURL</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>L2O_CpqContractAmendURL__c</fullName>
        <label>L2O_CpqContractAmendURL</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>L2O_ExpansionOption__c</fullName>
        <label>L2O_ExpansionOption</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>L2O_RecontractingOption__c</fullName>
        <label>L2O_RecontractingOption</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>L2O_ManageInstallBase</label>
    <pluralLabel>L2O_ManageInstallBases</pluralLabel>
</CustomObject>

manifest/objects/Order.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__SubscribedQuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscribedAssetHelp</customHelpPage>
    <description>Links a particular asset to the subscription that covers it.</description>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the quote for the quoteLines.</description>
        <inlineHelpText>Identifies the quote for the quoteLines.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote</relationshipLabel>
        <relationshipName>Quote</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscribed Quote Line</label>
    <nameField>
        <displayFormat>SQL-{00000000}</displayFormat>
        <label>Subscribed Quote Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribed Quote Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/L2O_ManageInstallBaseController.cls
/**
* Company : PwC.
* @description : L2O_ManageInstallBaseController will be used to handle Manage Install Base flow from Account.
* *******************************************************************************************************************************************
* History : 
* @date 06/07/2022
* @author Lakshitha Salian
*/

public without sharing class L2O_ManageInstallBaseController{
    
    //Exception log variables
    public static String className = '';
    public static String methodName = '';
    @TestVisible private static Boolean isErrorFlag = false;
 
    /**
    * @name  getAllContracts   
    * @description This method returns all valid Contracts of specific Account
    * @param accountId for the Account Id
    * @return List of Contracts
    **/
    @AuraEnabled
    public static List<Contract> getAllContracts(String accountId){

                
        className = 'L2O_ManageInstallBaseController';
        methodName = 'getAllContracts';
        List<Contract> lstAllContracts = new List<Contract>();
        try {
             if(isErrorFlag == true && Test.isRunningTest()) {
             	throw new AuraHandledException(System.Label.L2O_AuraHandledError);
             }
        
            lstAllContracts = [SELECT Id,Name, AccountId, StartDate, EndDate, ContractTerm, Status, ActivatedDate, ContractNumber,SBQQ__Opportunity__r.Name, SBQQ__Quote__r.Name, SBQQ__Quote__c
                               FROM Contract WHERE AccountId =:accountId AND EndDate > TODAY AND Status = 'Activated' ORDER BY CREATEDDATE DESC];
            return lstAllContracts; 
        }catch (Exception ex) {
             SDF_LGR_LoggerManager.DBufLogger.error(ex,className,methodName);
        } finally{
        	SDF_LGR_LoggerManager.DBufLogger.flush();
        }
        // Return all valid Contracts of specific Account 
        return lstAllContracts;
    }
    
    /**
    * @name  getMetaDataSettings   
    * @description This method returns custom metadata texts for the Manage Install Base Flow
    * @return List of Metadata settings
    **/
    @AuraEnabled
    public static List<L2O_ManageInstallBase__mdt> getMetaDataSettings(){
        
        className = 'L2O_ManageInstallBaseController';
        methodName = 'getMetaDataSettings';
        List<L2O_ManageInstallBase__mdt> lstAllMetadata = new  List<L2O_ManageInstallBase__mdt>();
        
        try {
            if(isErrorFlag == true && Test.isRunningTest()) {
             	throw new AuraHandledException(System.Label.L2O_AuraHandledError);
             }
            lstAllMetadata = [SELECT MasterLabel, L2O_AmendAssetsOnly__c, L2O_AmendBothOption__c,L2O_ExpansionOption__c,L2O_ChangeOrderOption__c,L2O_RecontractingOption__c, L2O_AmendOptionHeader__c,L2O_AmendSubTypeHeader__c,L2O_AllContractsHeader__c,L2O_ContractListNote__c,L2O_CpqContractAmendURL__c,L2O_CpqAccountAmendURL__c,L2O_ContractListNote2__c,L2O_ContractPathChangeOption__c
                    			FROM L2O_ManageInstallBase__mdt WHERE DeveloperName ='L2O_ManageInstallBase_FlowText'];
            return lstAllMetadata;
        } catch (Exception ex) {
             SDF_LGR_LoggerManager.DBufLogger.error(ex,className,methodName);
        } finally{
        	SDF_LGR_LoggerManager.DBufLogger.flush();
        }
        // Return custom metadata texts for the Manage Install Base Flow
        return lstAllMetadata;
    }

    /**
    * @name  updateContract   
    * @description This method updates the sub type on Contract
    * @param contractId for the Contract Id
    * @param subtype for the Selected Subtype
    * @return This method returning response as String
    **/
    @AuraEnabled
    public static String updateContract(String contractId, String subtype){
        
        className = 'L2O_ManageInstallBaseController';
        methodName = 'updateContract';
        String response = '';  
        
        try {
            if(isErrorFlag == true && Test.isRunningTest()) {
             	throw new AuraHandledException(System.Label.L2O_AuraHandledError);
             }
            // update Contract record
            Contract con = [SELECT Id,L2O_Amendment_Opportunity_SubType__c FROM Contract WHERE Id = :contractId];
            con.L2O_Amendment_Opportunity_SubType__c = subtype;
            update con;
           	response ='Success';
         } catch (Exception ex) {
             response = 'Error';
             SDF_LGR_LoggerManager.DBufLogger.error(ex,className,methodName);
         } finally{
        	SDF_LGR_LoggerManager.DBufLogger.flush();
        }
  
      	return response;
    }

}