manifest/objects/Account.object
<CustomObject>
    <fields>
        <fullName>L2O_Business_Region__c</fullName>
        <description>Region this Account is selling out of</description>
        <label>Business Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>L2O_Business_Region</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

manifest/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2O_Business_Region__c</fullName>
        <description>To default to Accounts Business Region</description>
        <label>Business Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>L2O_Business_Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__PrimaryQuote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Points to primary quote on this opportunity.</description>
        <inlineHelpText>Salesforce CPQ uses this to point to the primary quote on this opportunity.</inlineHelpText>
        <label>Primary Quote</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>PrimaryOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</description>
        <inlineHelpText>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Start date for subscriptions in this quote.</description>
        <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__AdditionalDiscount__c</fullName>
        <description>Total additional discount extends on this line item. Additional discount is defined as discount extended on top of volume discount or negotiated prices.</description>
        <formula>(SBQQ__RegularPrice__c - SBQQ__CustomerPrice__c) *  SBQQ__EffectiveQuantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total additional discounts extended to this line item. Additional discount is defined as discount extended on top of volume discount or negotiated prices.</inlineHelpText>
        <label>Additional Disc.</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__EffectiveQuantity__c</fullName>
        <description>Effective quantity used in computing totals. Same as quantity unless the product is block priced, covered by &quot;Slab&quot; discount schedule, or an existing subscription.</description>
        <formula>IF(OR(ISPICKVAL(SBQQ__DiscountScheduleType__c, &apos;Slab&apos;),ISPICKVAL(SBQQ__PricingMethod__c, &apos;Block&apos;)),IF(OR(AND(!SBQQ__Existing__c, !SBQQ__CarryoverLine__c, SBQQ__Quantity__c == 0),AND(OR(SBQQ__Existing__c, SBQQ__CarryoverLine__c),OR(SBQQ__Quantity__c == SBQQ__PriorQuantity__c - SBQQ__UpgradedQuantity__c,AND(!SBQQ__AllowAssetRefund__c, ISPICKVAL(SBQQ__SubscriptionPricing__c, &apos;&apos;), SBQQ__Quantity__c &lt; SBQQ__PriorQuantity__c - SBQQ__UpgradedQuantity__c)))),0,1),IF(AND(!SBQQ__Existing__c, !SBQQ__CarryoverLine__c),SBQQ__Quantity__c,IF(SBQQ__Quantity__c &gt;= SBQQ__PriorQuantity__c - SBQQ__UpgradedQuantity__c,IF(ISPICKVAL(SBQQ__SubscriptionPricing__c, &apos;Percent Of Total&apos;),SBQQ__Quantity__c,SBQQ__Quantity__c - SBQQ__PriorQuantity__c + SBQQ__UpgradedQuantity__c),IF(AND(!SBQQ__AllowAssetRefund__c, ISPICKVAL(SBQQ__SubscriptionPricing__c, &apos;&apos;)),0,SBQQ__Quantity__c - SBQQ__PriorQuantity__c + SBQQ__UpgradedQuantity__c))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Effective quantity used in computing totals. Same as quantity unless the product is block priced, covered by &quot;Slab&quot; discount schedule, or an existing subscription.</inlineHelpText>
        <label>Effective Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__ListPrice__c</fullName>
        <description>List unit price for the product quoted by this line item. List Price originates from the price book.</description>
        <inlineHelpText>List unit price for the product quoted by this line item. List Price originates from the price book.</inlineHelpText>
        <label>List Unit Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__NetTotal__c</fullName>
        <description>Net total price for this quote line item.</description>
        <formula>IF(AND(SBQQ__Renewal__c, !SBQQ__Existing__c, ISBLANK(SBQQ__PriorQuantity__c)), 0, SBQQ__NetPrice__c * SBQQ__EffectiveQuantity__c)</formula>
        <inlineHelpText>Net total price for this quote line item.</inlineHelpText>
        <label>Net Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProductName__c</fullName>
        <description>Name for the product referenced by this line item.</description>
        <formula>SBQQ__Product__r.Name</formula>
        <inlineHelpText>Name for the product referenced by this line item.</inlineHelpText>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Date the service represented by this line item will begin (only applies if product is a subscription).</description>
        <inlineHelpText>The date the subscription for this product begins.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__UnitCost__c</fullName>
        <description>Cost for one unit of product quoted on this line item.</description>
        <inlineHelpText>Cost for one unit of product quoted on this line item.</inlineHelpText>
        <label>Unit Cost</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
    <fields>
        <fullName>L2O_Business_Region__c</fullName>
        <description>Pulled from the Address on the Quote</description>
        <formula>SBQQ__Quote__r.L2O_Business_Region__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Region</label>
        <type>Text</type>
    </fields>

objects/SBQQ__QuoteLine__c.object
    <fields>
        <fullName>L2O_Business_Region_rev__c</fullName>
        <label>Business Region_rev</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>L2O_Business_Region</valueSetName>
        </valueSet>
    </fields>

objects/SBQQ__QuoteLine__c.object
    <fields>
        <fullName>L2O_Case_Rate__c</fullName>
        <label>Case Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

objects/SBQQ__QuoteLine__c.object
    <fields>
        <fullName>L2O_Membership_Fee__c</fullName>
        <description>This is the recurring subscription fee</description>
        <formula>IF(NOT(ISBLANK(TEXT(SBQQ__SubscriptionPricing__c))),
IF(ISPICKVAL(L2O_Service_Platform__c,&apos;HHS&apos;), SBQQ__NetPrice__c / SBQQ__ProrateMultiplier__c, SBQQ__ListPrice__c - L2O_Per_Unit_Discount__c), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The per unit per month price of this Subscription. Formerly known as Membership Fee</inlineHelpText>
        <label>Subscription Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

objects/SBQQ__QuoteLine__c.object
    <fields>
        <fullName>L2O_Per_Unit_Discount__c</fullName>
        <description>Deal with USGH line items have the &quot;Per Unit Discount&quot; and not the OOB Add. Discount.
Per Unit Discount will only be Amount value and will basically be a dollar amount that can be deducted from List unit price</description>
        <label>Per Unit Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

objects/SBQQ__QuoteLine__c.object
    <fields>
        <fullName>L2O_Service_Platform__c</fullName>
        <description>Platform of service</description>
        <label>Service Platform</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HHS</fullName>
                </value>
                <value>
                    <fullName>LIV</fullName>
                </value>
                <value>
                    <fullName>TDH</fullName>
                </value>
                <value>
                    <fullName>INTL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

manifest/objects/SBQQ__SubscribedQuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscribedAssetHelp</customHelpPage>
    <description>Links a particular asset to the subscription that covers it.</description>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the quote for the quoteLines.</description>
        <inlineHelpText>Identifies the quote for the quoteLines.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote</relationshipLabel>
        <relationshipName>Quote</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscribed Quote Line</label>
    <nameField>
        <displayFormat>SQL-{00000000}</displayFormat>
        <label>Subscribed Quote Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribed Quote Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/globalValueSets/L2O_Business_Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>USA</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
    </customValue>
    <customValue>
        <fullName>APAC</fullName>
    </customValue>
    <customValue>
        <fullName>LATAM</fullName>
    </customValue>
    <customValue>
        <fullName>Europe</fullName>
        <isActive>false</isActive>
        <label>Europe</label>
    </customValue>
    <customValue>
        <fullName>Latin America</fullName>
        <isActive>false</isActive>
        <label>Latin America</label>
    </customValue>
    <customValue>
        <fullName>Asia-ME</fullName>
        <isActive>false</isActive>
        <label>Asia-ME</label>
    </customValue>
    <customValue>
        <fullName>AUS-NZ</fullName>
        <isActive>false</isActive>
        <label>AUS-NZ</label>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
        <isActive>false</isActive>
        <label>Japan</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <masterLabel>Business Region</masterLabel>
</GlobalValueSet>

manifest/classes/L2O_ClosedWon_VFCTemplateController.cls
/**
* Company : PwC.
* @description : L2O_ClosedWon_VFCTemplateController will be executed from the L2O_ClosedWon_VFCTemplate .
* *******************************************************************************************************************************************
* History : 
* @date 22/12/2022
* @author Neha Sheikh
*/
public without sharing class L2O_ClosedWon_VFCTemplateController {
    
    
    List<SBQQ__QuoteLine__c> quotLineItemLstINTL = new List<SBQQ__QuoteLine__c>();
    List<SBQQ__QuoteLine__c> quotLineItemLstUSGH = new List<SBQQ__QuoteLine__c>();
    List<SBQQ__QuoteLine__c> quotLineItemLstHHS = new List<SBQQ__QuoteLine__c>();

     /**
    * @name  oppId
    * @description opportunity Id value.
    * @params  none
    **/
    public String oppId{get;set;}
    
    /**
    * @name  getFields
    * @description fields in the L2O_ClosedWonEmailTemplateFieldSet field set.
    * @params  none
    * @return all the fields in the L2O_ClosedWonEmailTemplateFieldSet field set.
    **/
    List<Schema.FieldSetMember> getFields() {
        return SObjectType.Opportunity.FieldSets.L2O_ClosedWonEmailTemplateFieldSet.getFields();
    }
    /**
    * @name  oppRecord
    * @description opp value.
    * @params  none
    * @return opp record data.
    **/

    public Opportunity oppRecord{
        get {
        String query = 'SELECT ';
        for(Schema.FieldSetMember fieldSet : this.getFields()) {
            query += fieldSet.getFieldPath() + ', '; 
        }
       return Database.query(String.escapeSingleQuotes(query)+
                                  'Id, Account.Owner.Name,SBQQ__PrimaryQuote__r.SBQQ__PrimaryContact__r.Email FROM Opportunity WHERE Id =\'' + 
                                  String.escapeSingleQuotes(oppId) + '\''+' LIMIT 1');
        
        }
        set;
    }
    /**
    * @name  isInternational
    * @description check if the opp is international or not.
    * @params  none
    * @return true if opp is international else false.
    **/
    public Boolean isInternational{
        get{
            if(oppRecord.L2O_Business_Region__c != L2O_Constants.BUSSINESS_REGION_USA && oppRecord.L2O_Business_Region__c != null){
                return true;
            }else{
                 return false;
            }
        }
        set;
    }
    /**    
    * @name  quoteLineItems
    * @description related Quote's Quote line items value.
    * @params  none
    * @return list of quoteLine's.
    **/
 
    List<SBQQ__QuoteLine__c> quoteLineItems{
        
        get{   
          List<SBQQ__QuoteLine__c> quotLineItemList = [SELECT SBQQ__ProductName__c,SBQQ__EffectiveQuantity__c,SBQQ__UnitCost__c,
                                                         SBQQ__Quote__r.SBQQ__StartDate__c,L2O_Case_Rate__c,SBQQ__NetTotal__c,
                                                         L2O_Membership_Fee__c,L2O_Per_Unit_Discount__c,SBQQ__ListPrice__c,L2O_Service_Platform__c,
                                                         L2O_Business_Region_rev__c,SBQQ__AdditionalDiscount__c
                                                         FROM SBQQ__QuoteLine__c 
                                                         WHERE SBQQ__Quote__c=:oppRecord.SBQQ__PrimaryQuote__c];
             return quotLineItemList;
        }
        set;
        
    }
    /**    
    * @name  quoteLineItemsforINTL
    * @description related Quote's Quote line for international.
    * @params  none
    * @return list of quoteLine's.
    **/
    public List<SBQQ__QuoteLine__c> quoteLineItemsforINTL{
        get{
            for(SBQQ__QuoteLine__c qliTemp : quoteLineItems){
                if(qliTemp.L2O_Business_Region_rev__c != L2O_Constants.BUSSINESS_REGION_USA && !quotLineItemLstINTL.contains(qliTemp)){
                    quotLineItemLstINTL.add(qliTemp);
                }
            }
            return quotLineItemLstINTL;
        }
         set;
    }
    /**    
    * @name  quoteLineItemsforUSGH
    * @description related Quote's Quote line for USGH.
    * @params  none
    * @return list of quoteLine's.
    **/
    public List<SBQQ__QuoteLine__c> quoteLineItemsforUSGH{
        get{
            for(SBQQ__QuoteLine__c qliTemp : quoteLineItems){
                if((qliTemp.L2O_Service_Platform__c == L2O_Constants.BUSSINESS_TYPE_LIV || qliTemp.L2O_Service_Platform__c == L2O_Constants.BUSSINESS_TYPE_TDH) &&
                    qliTemp.L2O_Business_Region_rev__c == L2O_Constants.BUSSINESS_REGION_USA && !quotLineItemLstUSGH.contains(qliTemp)){
                    quotLineItemLstUSGH.add(qliTemp);
                }
            }
            return quotLineItemLstUSGH;
        }
         set;
    }
    /**    
    * @name  quoteLineItemsforHHS
    * @description related Quote's Quote line for HHS.
    * @params  none
    * @return list of quoteLine's.
    **/
    public List<SBQQ__QuoteLine__c> quoteLineItemsforHHS{
        get{
            for(SBQQ__QuoteLine__c qliTemp : quoteLineItems){
                if((qliTemp.L2O_Service_Platform__c != L2O_Constants.BUSSINESS_TYPE_LIV && qliTemp.L2O_Service_Platform__c != L2O_Constants.BUSSINESS_TYPE_TDH) && 
                    qliTemp.L2O_Business_Region_rev__c == L2O_Constants.BUSSINESS_REGION_USA && !quotLineItemLstHHS.contains(qliTemp)){
                    quotLineItemLstHHS.add(qliTemp);
                }
            }
            return quotLineItemLstHHS;
        }
         set;
    }
    /**    
    * @name  setTablevisibility
    * @description to set the table visibility based on products.
    * @param  productType type of the region.
    * @return true/false based on given condtions.
    **/
    public Boolean setTablevisibility(String productType){
        for(SBQQ__QuoteLine__c qliTemp : quoteLineItems){
            if(qliTemp.L2O_Business_Region_rev__c != L2O_Constants.BUSSINESS_REGION_USA && productType == 'INTL'){
                return true;
            }
            else if((qliTemp.L2O_Service_Platform__c == L2O_Constants.BUSSINESS_TYPE_LIV || qliTemp.L2O_Service_Platform__c == L2O_Constants.BUSSINESS_TYPE_TDH) &&
                    qliTemp.L2O_Business_Region_rev__c == L2O_Constants.BUSSINESS_REGION_USA && productType == 'USGH'){ 
                         return true;
                    }
            else if((qliTemp.L2O_Service_Platform__c != L2O_Constants.BUSSINESS_TYPE_LIV && qliTemp.L2O_Service_Platform__c != L2O_Constants.BUSSINESS_TYPE_TDH) && 
                    qliTemp.L2O_Business_Region_rev__c == L2O_Constants.BUSSINESS_REGION_USA && productType == 'HHS'){
                         return true;
                    }
            
        }
         return false;
    }
    /**    
    * @name  isINTL
    * @description to show the table with international products.
    * @params  none
    * @return true/false based on given condtions.
    **/
    public Boolean isINTL{
        get{
            if(setTablevisibility('INTL')){
                return true;
            }
            return false;
        }set;
    }
    /**    
    * @name  isUSGH
    * @description to show the table with USGH products.
    * @params  none
    * @return true/false based on given condtions.
    **/
        public Boolean isUSGH{
        get{
            if(setTablevisibility('USGH')){
                return true;
            }
            return false;
        }set;
    }
    /**    
    * @name  isHHS
    * @description to show the table with HHS products.
    * @params  none
    * @return true/false based on given condtions.
    **/
        public Boolean isHHS{
        get{
            if(setTablevisibility('HHS')){
                return true;
            }
            return false;
        }set;
    }    
}