manifest/objects/Account.object
<CustomObject>
    <fields>
        <fullName>L2O_Amendment_Opportunity_SubType__c</fullName>
        <description>To capture the Amendment Opportunity Sub Type 
[Transaction Type] via the Manage Install Base account
 button for amendment flow.</description>
        <label>Amendment Opportunity SubType</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

manifest/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contract.object
    <fields>
        <fullName>L2O_Amendment_Opportunity_SubType__c</fullName>
        <description>In order enable Amend functionality on contract, Please update the field to either Expansion or Change Order.</description>
        <inlineHelpText>In order enable Amend functionality on contract, Please update the field to either Expansion or Change Order.</inlineHelpText>
        <label>Amendment Opportunity SubType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Change Order</fullName>
                </value>
                <value>
                    <fullName>Recontracting</fullName>
                </value>
                <value>
                    <fullName>Contract Path Change</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                    <isActive>false</isActive>
                    <label>Expansion</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/L2O_ManageInstallBase__mdt.object
<CustomObject>
    <description>To contain all the text from the flow Manage Install Base from Account object.</description>
    <label>L2O_ManageInstallBase</label>
    <pluralLabel>L2O_ManageInstallBases</pluralLabel>
</CustomObject>

manifest/objects/Order.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SDF_LGR_Log__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <description>Logging level</description>
        <label>Level</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Log Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <description>Log reference</description>
        <externalId>true</externalId>
        <label>Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/classes/L2O_ManageInstallBaseController_Test.cls
/**
* Company : PwC.
* @description : Test Class for L2O_ManageInstallBaseController apex
* *******************************************************************************************************************************************
* History : 
* @date 06/07/2022
* @author Lakshitha Salian
*/
@isTest
public class L2O_ManageInstallBaseController_Test {
    
    /**
    * @name  testSetup 
    * @description To create setup records for test class.
    * @params  none
    **/
    
    @testSetup static void testSetup(){
         List<Account> accountList= L2O_DataFactoryTest.createAccount(true,2);
         List<Contact> conList =  L2O_DataFactoryTest.createContact(true,accountList); 
         List<Opportunity> oppList =  L2O_DataFactoryTest.createOpportunity(true,accountList); 
         L2O_DataFactoryTest.createContactRoles(true,oppList,conList[0].id);    
         List<SBQQ__Quote__c> quoteList =  L2O_DataFactoryTest.createQuote(true,oppList);    
         L2O_DataFactoryTest.createContract(oppList,quoteList,accountList[0].id);
         L2O_DataFactoryTest.createContract(oppList,quoteList,accountList[1].id);
         List<Contract> contractList = [SELECT Id, Status FROM Contract WHERE ContractTerm = 12 LIMIT 1 ];
         contractList[0].Status = 'Activated';
         update contractList;
    } 
    
    /**
    * @name  testGetAllContracts
    * @description To test Contract record fetch
    * @params  none
    **/
    @isTest static void testGetAllContracts(){
        List<Contract> testResult = new List<Contract>();
        Test.startTest();
        List<Account> accountList = [SELECT Id FROM Account WHERE Name LIKE '%Test_Customer%' LIMIT 1];
        testResult.addAll(L2O_ManageInstallBaseController.getAllContracts(accountList[0].id));
       
        //Check the Contract status is activated.
        for(Contract con: testResult){
            System.assertEquals('Activated',con.Status,'To check the Contract Status is Activated.');
        }
        
        //Check the Contracts returned if no Id passed.
        String nullId = '';
        List<Contract> testErrorResult = new List<Contract>();
        testErrorResult.addAll(L2O_ManageInstallBaseController.getAllContracts(nullId));
        System.assertEquals(0,testErrorResult.size(),'To check the size of returned Contracts List.');
        
        //To cover the catch block
        L2O_ManageInstallBaseController.isErrorFlag = true;
        L2O_ManageInstallBaseController.getAllContracts(nullId);
        List<SDF_LGR_Log__c> lstErrorLog = [SELECT Id,Class__c,Reference__c,Level__c,Message__c
                                            FROM SDF_LGR_Log__c
                                            WHERE Class__c = 'L2O_ManageInstallBaseController'];
        System.assertEquals(1,lstErrorLog.size(),'To cover the catch block.'); 
        System.assertEquals('getAllContracts',lstErrorLog[0].Reference__c,'To check the method of error.');
        Test.stopTest();  
    }
    
    /**
    * @name  testUpdateContract
    * @description To test Contract record update
    * @params  none
    **/
    @isTest static void testUpdateContract(){
        Test.startTest();
        Contract contract = [SELECT Id FROM Contract WHERE ContractTerm = 12 LIMIT 1];
        String subtype = 'Change Order';
        L2O_ManageInstallBaseController.updateContract(contract.Id,subtype);
        Contract updatedContract = [SELECT Id,L2O_Amendment_Opportunity_SubType__c FROM Contract WHERE ContractTerm = 12 LIMIT 1]; 
        System.assertEquals('Change Order',updatedContract.L2O_Amendment_Opportunity_SubType__c,'To check the Contract Sub Type is Change Order.');
        
		subtype = 'Test'; 
        String response = L2O_ManageInstallBaseController.updateContract(contract.Id,subtype);
        System.assertEquals('Error',response,'To check the method returned Error.');
        Test.stopTest();
       
    }
    
    /**
    * @name  testGetMetaDataSettings
    * @description To test L2O_ManageInstallBase__mdt record fetch
    * @params  none
    **/
    @isTest static void testGetMetaDataSettings(){
        List<L2O_ManageInstallBase__mdt> testResult = new List<L2O_ManageInstallBase__mdt>();
        Test.startTest();
        testResult.addAll(L2O_ManageInstallBaseController.getMetaDataSettings());
        
        for(L2O_ManageInstallBase__mdt mtd: testResult){
            System.assertEquals('L2O_Manage Install Base Flow Text',mtd.MasterLabel,'To check the Metadata master label.');
        }
        
        //To cover the catch block
        L2O_ManageInstallBaseController.isErrorFlag = true;
        L2O_ManageInstallBaseController.getMetaDataSettings();
        List<SDF_LGR_Log__c> lstErrorLog = [SELECT Id,Class__c,Reference__c,Level__c,Message__c
                                            FROM SDF_LGR_Log__c
                                            WHERE Class__c = 'L2O_ManageInstallBaseController'];
        System.assertEquals(1,lstErrorLog.size(),'To cover the catch block.'); 
        System.assertEquals('getMetaDataSettings',lstErrorLog[0].Reference__c,'To check the method of error.');
        Test.stopTest();
    }
}