manifest/objects/Account.object
<CustomObject>
    <fields>
        <fullName>L2O_Broadcast_Message__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field will be updated to &quot;True&quot; when an Account is sent down with its Order details</description>
        <label>Broadcast Message</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>L2O_GUID__c</fullName>
        <description>System Generated Global Unique Id</description>
        <externalId>true</externalId>
        <inlineHelpText>System Generated Global UniqueId</inlineHelpText>
        <label>GUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>L2O_Last_Integration_Date__c</fullName>
        <description>Last datetime the transaction was processed downstream</description>
        <label>Last Integration Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

manifest/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this asset.</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>L2O_GUID__c</fullName>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/L2O_Platform_Event_Published__c.object
<CustomObject>
    <fields>
        <fullName>L2O_Object_Id__c</fullName>
        <label>Object Id</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2O_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Errored</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Platform Event Published</label>
    <nameField>
        <label>Platform Event Published Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platform Events Published</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2O_Broadcast_Message__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked when Mulesoft process the payload</description>
        <label>Broadcast Message?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>L2O_GUID__c</fullName>
        <description>Global Unique Identifier that is used for integration</description>
        <externalId>true</externalId>
        <inlineHelpText>System Generated Global UniqueId</inlineHelpText>
        <label>GUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>L2O_Last_Integration_Date__c</fullName>
        <description>Last date of when data was migrated</description>
        <label>Last Integration Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SBQQ__Ordered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Internal flag that drives automatic order creation.</description>
        <inlineHelpText>Select this checkbox to automatically create an order from the primary quote.</inlineHelpText>
        <label>Ordered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__PrimaryQuote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Points to primary quote on this opportunity.</description>
        <inlineHelpText>Salesforce CPQ uses this to point to the primary quote on this opportunity.</inlineHelpText>
        <label>Primary Quote</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>PrimaryOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

manifest/objects/Order.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order.object
    <fields>
        <fullName>L2O_Broadcast_Message__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Broadcast Message?</label>
        <type>Checkbox</type>
    </fields>

objects/Order.object
    <fields>
        <fullName>L2O_GUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

objects/Order.object
    <fields>
        <fullName>L2O_Last_Integration_Date__c</fullName>
        <description>Last datetime the transaction was processed downstream</description>
        <label>Last Integration Date</label>
        <type>DateTime</type>
    </fields>

manifest/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>L2O_Broadcast_Message__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Broadcast Message</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>L2O_GUID__c</fullName>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote line where this order product is created from.</description>
        <inlineHelpText>The quote line where this order product is created from.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>OrderProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>The current state of the order product.</description>
        <inlineHelpText>Indicates the current state of the order product. It is defaulted to Draft when an order is created.</inlineHelpText>
        <label>Activation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SBQQ__OrderProductStatus</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

manifest/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Ordered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Internal flag to drive automatic order creation.</description>
        <inlineHelpText>Select this checkbox to automatically create an order from this quote, if it is a primary quote.</inlineHelpText>
        <label>Ordered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/classes/L2O_PlatFormEvent_Ctrl_Test.cls
/**
* Company : PwC.
* @description : Test Class for L2O_PlatFormEvent_Ctrl
* ************************************************************************************************************************************
* History : 
* @date 08/07/2022
* @author Neha Sheikh
*/

@isTest
public class L2O_PlatFormEvent_Ctrl_Test {
    
    @testSetup
    /**
* @name  testSetup()
* @description Sets up Test Data for the Class
* @params  none
*/ 
    
    static void testSetup() {
        // create test data
        List<Account> accountList= L2O_DataFactoryTest.createAccount(true,1);
        List<Contact> conList =  L2O_DataFactoryTest.createContact(true,accountList); 
        List<Opportunity> oppList =  L2O_DataFactoryTest.createOpportunity(true,accountList); 
        L2O_DataFactoryTest.createContactRoles(true,oppList,conList[0].id); 
        List<SBQQ__Quote__c> quoteList =  L2O_DataFactoryTest.createQuote(true,oppList);
        List<Product2> prodList = L2O_DataFactoryTest.createProduct();
        List<Asset> asstList = L2O_DataFactoryTest.createAsset(true,accountList[0].id,prodList);
        List<SBQQ__Quoteline__c> quoteLineList =  L2O_DataFactoryTest.createQuoteLines(true,quoteList,prodList,asstList);   
        
        //Update quote list
        List<SBQQ__Quote__c> lstQuote = new List<SBQQ__Quote__c>();
        for(SBQQ__Quote__c quoteRec : [SELECT Id,SBQQ__Status__c,SBQQ__Primary__c
                                       FROM SBQQ__Quote__c 
                                       WHERE  SBQQ__Status__c != null] ){
                                           quoteRec.SBQQ__Status__c ='Accepted' ;
                                           quoteRec.SBQQ__Primary__c = true;                           
                                           lstQuote.add(quoteRec);
                                       }
        if(!quoteLineList.isEmpty()){
             update lstQuote;
        }
       
        //Update opportunity list
        List<Opportunity> lstOppty = [SELECT Id,Name,stageName,SBQQ__PrimaryQuote__c,SBQQ__Ordered__c
                                      FROM Opportunity 
                                      WHERE Name != null];
        for(integer count = 0;count<lstOppty.size();count++){
            lstOppty[count].SBQQ__PrimaryQuote__c = lstQuote[count].Id; 
            if(count == 0){ 
                lstOppty[count].stageName = L2O_Constants.OPPTY_STAGE_CLOSED_OWN;
                lstOppty[count].SBQQ__Ordered__c = true;
            }
        }
        update lstOppty;
        
    }
    /**
* @name testUpdateRecords()
* @description Test when OrderITem record get 'Activated', Platform Event should publish and update the respective fields
* @params  none
*/ 
    @isTest static void testUpdateOrderRecords() { 
        List<Order> ordUpdt = new List<Order>();
        Test.startTest();
        // Query the related order 
        List<Order> lstOrder = [SELECT Id,Status,AccountId
                                FROM Order
                                WHERE AccountId != NULL
                                LIMIT 1];
        // Query the related account
        Account acc = [SELECT Id,L2O_Broadcast_Message__c
                       FROM Account 
                       WHERE Id =:lstOrder[0].AccountId LIMIT 1];
        
        // L2O_Broadcast_Message__c field on Account will be true post Platform Event fire
        System.assertEquals(True,acc.L2O_Broadcast_Message__c,'');
        for(Order ord : [SELECT Id,L2O_Broadcast_Message__c FROM Order WHERE Status = 'Activated']){
            ord.L2O_Broadcast_Message__c = true;
            ordUpdt.add(ord);
        }
        //update Order
        update ordUpdt; 
        Test.stopTest();
    }
    /**
* @name testUpdateRecords()
* @description Test when Account Name,Biiling/Shipping Address get change, Platform Event should publish and update the respective fields
* @params  none
*/ 
    @isTest static void testUpdateAccRecords() { 
        // Query the created Account record
        List<Account> lstAccount = [SELECT Id,Name,BillingPostalCode,BillingStreet,L2O_Last_Integration_Date__c, 
                                    L2O_Broadcast_Message__c,L2O_GUID__c
                                    FROM Account 
                                    WHERE Name != null];
        Test.startTest();
        //update Account list
        for(integer count = 0;count<lstAccount.size();count++){
            lstAccount[count].Name = 'test - update ';
            lstAccount[count].ShippingPostalCode = '1234';
            lstAccount[count].BillingPostalCode = '1234';
            lstAccount[count].L2O_Broadcast_Message__c = true;
        }
        update lstAccount;
        // L2O_Platform_Event_Published__c record will create post the Account Broadcast platform event fire.
        L2O_Platform_Event_Published__c insForAcc = [SELECT id,L2O_Object_Id__c,L2O_Status__c FROM L2O_Platform_Event_Published__c
                                                     WHERE L2O_Object_Id__c =: lstAccount[0].L2O_GUID__c LIMIT 1];
        System.assertEquals('Success',insForAcc.L2O_Status__c,'');
        Test.stopTest();
        
    }
}