manifest/objects/Account.object
<CustomObject>
    <fields>
        <fullName>L2O_GUID__c</fullName>
        <description>System Generated Global Unique Id</description>
        <externalId>true</externalId>
        <inlineHelpText>System Generated Global UniqueId</inlineHelpText>
        <label>GUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

manifest/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The link to the account record to identify the external party to this agreement</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N50000001Xl0UEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2O_GUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SDF_LGR_Log__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Log Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <description>Log reference</description>
        <externalId>true</externalId>
        <label>Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/classes/L2O_AgreementTriggerHandler_Test.cls
/**
* Company : PwC.
* @description : Test Class for L2O_AgreementTriggerHandler apex
* ************************************************************************************************************************************
* History : 
* @date 20/07/2023
* @author Neha Sheikh
*/

@istest
public class L2O_AgreementTriggerHandler_Test {
    /**
* @name  testcatchException()
* @description Tests L2O_AgreementTriggerHandler class catch block
* @params  none
*/
    @istest
    public static void testcatchException() {
        Test.startTest();
        L2O_AgreementTriggerHandler helper = new L2O_AgreementTriggerHandler();
        helper.beforeInsert();
        helper.beforeUpdate();
        Test.stopTest();
        SDF_LGR_Log__c errorLog = [SELECT Name, Id, Class__c, Message__c, Reference__c FROM SDF_LGR_Log__c WHERE Name != '' LIMIT 1];
        System.assertEquals('L2O_AgreementTriggerHandler',errorLog.Class__c,'Handler Test Successful');
        
    }
    /**
* @name  testsetGUID()
* @description Tests Auto updated L2O_GUID__c field onrecord creation
* @params  none
*/
    @istest
    public static void testsetGUID() {
        list<Account> accList= L2O_DataFactoryTest.createAccount(true,1);
        Apttus__APTS_Agreement__c tempAgreement = new Apttus__APTS_Agreement__c(Name = 'Test', Apttus__Account__c = accList[0].Id);
        Test.startTest();
        insert tempAgreement;
        Test.stopTest();
        Apttus__APTS_Agreement__c fetchAgreement = [SELECT Id,Name FROM Apttus__APTS_Agreement__c WHERE Name != '' LIMIT 1];
        System.assertEquals('Test',fetchAgreement.Name,'Creation Test Successful');
    }
    
}