manifest/objects/AcctGrpConParse_Exception__c.object
<CustomObject>
    <fields>
        <fullName>AGCPI__c</fullName>
        <description>Parent to this exception</description>
        <label>AcctGrpConParsing Item</label>
        <referenceTo>AcctGrpConParsing_Item__c</referenceTo>
        <relationshipLabel>AcctGrpConParse Exceptions</relationshipLabel>
        <relationshipName>AcctGrpConParse_Exceptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <description>What is the category of this exception (e.g. INFO, FORMAT ERROR, CONTENT ERROR, REQUIRED)</description>
        <label>Exception Type</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Desc__c</fullName>
        <description>Everything about the exception.</description>
        <label>Full Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SObject__c</fullName>
        <description>Which object was affected.</description>
        <label>SObject</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Short_Desc__c</fullName>
        <description>Abbreviated string hinting at the cause.</description>
        <label>Short Description</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AcctGrpConParse Exception</label>
    <nameField>
        <displayFormat>AGCPE-{00000000}</displayFormat>
        <label>AcctGrpConParse Exception</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AcctGrpConParse Exceptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/AcctGrpConParsing_Item__c.object
<CustomObject>
    <description>Staging queue to hold all data transmitted to create Accounts, groups, and contacts.</description>
    <fields>
        <fullName>Batch_Key__c</fullName>
        <description>Used to identify grouped submissions</description>
        <label>Batch Key</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Batch_Time__c</fullName>
        <description>When this batch was uploaded.</description>
        <label>Batch Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Item_Key__c</fullName>
        <label>Item Key</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>UMR, GENERIC, etc.</description>
        <label>Source</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AcctGrpConParsing Item</label>
    <nameField>
        <displayFormat>AGCPI-{00000000}</displayFormat>
        <label>AcctGrpConParsing Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AcctGrpConParsing Item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Update__c</fullName>
        <label>Opportunity Update</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

manifest/classes/OppCloseBatch.cls
global class OppCloseBatch implements Database.Batchable<sObject>, Database.Stateful {
  AcctGrpConParsing_Item__c agcpi = new AcctGrpConParsing_Item__c(
    Batch_Key__c = String.valueOf(DateTime.now().getTime()),
    Item_Key__c = String.valueOf(DateTime.now().getTime() / 1000),
    Processed__c = false,
    Batch_Time__c = DateTime.now(),
    Source__c = 'FIX_OPP'
  );
  global Database.QueryLocator start(Database.BatchableContext BC) {
    String target = string.valueOf(Date.today().addMonths(-2));
    String query =
      'SELECT Id, Sub_Channel__c FROM Opportunity WHERE (StageName != \'Closed Won\' AND StageName != \'Closed Lost\' AND StageName != \'Contracting\') AND CloseDate <=' +
      target;
    insert agcpi;
    return Database.getQueryLocator(query);
  }
  global void execute(Database.BatchableContext BC, List<Opportunity> scope) {
    for (Opportunity opp : scope) {
      opp.StageName = 'Closed Lost';

      opp.Reason_for_Loss__c = 'Other';
      if (opp.Sub_Channel__c == null) {
        opp.Sub_Channel__c = 'Undefined';
      }
      Opp.Opportunity_Update__c = 'Closed by Batch';
    }

    Database.SaveResult[] sr = Database.update(scope, false);
    List<AcctGrpConParse_Exception__c> agcpe_list = new List<AcctGrpConParse_Exception__c>();

    for (Integer i = 0; i < scope.size(); i++) {
      Database.SaveResult s = sr[i];
      Opportunity oldOpp = scope[i];
      if (!s.isSuccess()) {
        for (Database.Error rowError : s.getErrors()) {
          String fullDesc = ('OppId: ' +
          oldOpp.Id +
          ', ' +
          rowError.getMessage());
          if (fullDesc.length() > 255) {
            fullDesc = ('OppId: ' +
              oldOpp.Id +
              ', ' +
              rowError.getMessage())
              .substring(0, 255);
          }
          AcctGrpConParse_Exception__c agcpe = new AcctGrpConParse_Exception__c(
            AGCPI__c = agcpi.Id,
            Exception_Type__c = 'DML_ERROR',
            Short_Desc__c = String.valueOf(rowError.getStatusCode()),
            SObject__c = 'OPPORTUNITY',
            Full_Desc__c = fullDesc
          );
          agcpe_list.add(agcpe);
        }
      }
    }
    insert agcpe_list;
  }
  global void finish(Database.BatchableContext BC) {
    agcpi.processed__c = true;
    update agcpi;
  }
}