manifest/objects/Acct_Rel__c.object
<CustomObject>
    <description>Models the possible contracts between any two accounts regardless of hierarchy</description>
    <fields>
        <fullName>Benefit_Sponsor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account receiving services</description>
        <inlineHelpText>Lookup the Benefit Sponsor Account (Account receiving services) of the Relationship</inlineHelpText>
        <label>Benefit Sponsor Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Servicing Accounts</relationshipLabel>
        <relationshipName>servicingaccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <description>Select the type of Relationship for the Servicing Account.</description>
        <inlineHelpText>Select the type of Relationship for the Servicing Account.</inlineHelpText>
        <label>Servicing Account Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Account_Relationship_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date contract starts</description>
        <inlineHelpText>Enter the Date Relationship Started</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Svc_Acct__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account providing the service</description>
        <inlineHelpText>Lookup the Servicing Account of the Relationship</inlineHelpText>
        <label>Servicing Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Benefit Sponsor Accounts</relationshipLabel>
        <relationshipName>benefitsponsors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>REL-{00000000}</displayFormat>
        <label>Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Mbr_Group__c.object
<CustomObject>
    <fields>
        <fullName>Group_Number__c</fullName>
        <description>This is the Legacy Group ID number from Admin</description>
        <inlineHelpText>This is the Legacy Group ID number from Admin</inlineHelpText>
        <label>Group Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Enter a descriptive Member Group Name.</description>
        <inlineHelpText>Enter a descriptive Member Group Name.</inlineHelpText>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Group Status</description>
        <inlineHelpText>Group Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>PENDING</fullName>
                    <default>true</default>
                    <label>PENDING</label>
                </value>
                <value>
                    <fullName>TERMED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Member Group</label>
    <nameField>
        <displayFormat>MG-{00000000}</displayFormat>
        <label>Member Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Plan_Specific_Fees__c.object
<CustomObject>
    <fields>
        <fullName>Bill_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bill To Plan-Specific Fees By Product</relationshipLabel>
        <relationshipName>Plan_Specific_Fees_By_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consult_Fee_Mbr_Pd__c</fullName>
        <label>Consult Fee - Mbr Pd</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Consult_Fee_Plan_Pd__c</fullName>
        <label>Consult Fee - Plan Pd</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <formula>IF( Product__c = &apos;General Medical&apos;, Member_Group__r.Group_Number__c, &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Group__c</fullName>
        <label>Member Group</label>
        <referenceTo>Mbr_Group__c</referenceTo>
        <relationshipLabel>Plan-Specific Fees By Product</relationshipLabel>
        <relationshipName>Plan_Specific_Fees_By_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <formula>Subscription__r.SBQQ__ProductName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <label>Plan-Specific Fees By Product</label>
    <nameField>
        <displayFormat>PSF-{0000000}</displayFormat>
        <label>Plan Fees ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan-Specific Fees By Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/globalValueSets/Account_Relationship_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Benefit Partner or Vendor</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Contractee</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Provider Only</fullName>
    </customValue>
    <customValue>
        <fullName>Payer and Eligibility Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Payer Only</fullName>
    </customValue>
    <customValue>
        <fullName>Referral Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Benefit Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Contractor</fullName>
        <isActive>false</isActive>
        <label>Contractor</label>
    </customValue>
    <customValue>
        <fullName>Benefit Partner</fullName>
        <isActive>false</isActive>
        <label>Benefit Partner</label>
    </customValue>
    <customValue>
        <fullName>Benefit Sponsor</fullName>
        <isActive>false</isActive>
        <label>Benefit Sponsor</label>
    </customValue>
    <masterLabel>Account Relationship Type</masterLabel>
</GlobalValueSet>

manifest/classes/NASFGroupSelectLightningController_Test.cls
@isTest
private class NASFGroupSelectLightningController_Test {
	@TestSetup
    static void setup(){
        Account umrAcct = TestDataFactory.createUMR();
        Account testAcct = TestDataFactory.createRandomAccount();  
        Contact testCon = TestDataFactory.createContact(testAcct.Id);
        testAcct.Primary_Billing_Contact__c = testCon.Id;
        update testAcct;
        List<Mbr_Group__c> mgTest = TestDataFactory.createMbrGroup(testAcct.Id);
        
    }    
    
    @IsTest
    static void errorCheck_Test() {
        Account TestAcct = [SELECT Id FROM Account WHERE Name != 'UMR' LIMIT 1];
        Map<String, String> error = NASFGroupSelectLightningController.errorCheck(TestAcct.Id);
        system.assertNotEquals(Null, error);       
    }
    
    @IsTest
    static void filterMbrGroup_Test() {
        Account TestAcct = [SELECT Id FROM Account WHERE Name != 'UMR' LIMIT 1];
        String search1 = 'notExist';
        String search2 = 'Pending';
        NASFGroupSelectLightningController.filterMbrGroup(TestAcct.Id, search1, search2);
    }
    
    @IsTest
    static void CreateCase_Test() {
        List<Mbr_Group__c> mgTestLis = [SELECT Id, Name, Name__c, Group_Number__c, Status__c, LastModifiedBy.Name, LastModifiedDate, CreatedDate,
                                        (select Id,Name,Consult_Fee_Mbr_Pd__c, Consult_Fee_Plan_Pd__c FROM Plan_Specific_Fees_By_Product__r where Product__c ='General Medical' LIMIT 1)
       									FROM Mbr_Group__c LIMIT 3];
        List<String> mbIds = new List<String>();
        for(Mbr_Group__c mg : mgTestLis){
            mbIds.add(string.valueOf(mg.Id));
        }
        String caseId = NASFGroupSelectLightningController.CreateCase(mbIds);
        system.assertNotEquals(null, caseId);
        
    }
    
    @IsTest
    static void sendForm_Test(){
        List<Mbr_Group__c> mgTestLis = [SELECT Id, Name, Name__c, Group_Number__c, Status__c, LastModifiedBy.Name, LastModifiedDate, CreatedDate,
                                        (select Id,Name,Consult_Fee_Mbr_Pd__c, Consult_Fee_Plan_Pd__c FROM Plan_Specific_Fees_By_Product__r where Product__c ='General Medical' LIMIT 1)
       									FROM Mbr_Group__c LIMIT 3];
        List<String> mbIds = new List<String>();
        for(Mbr_Group__c mg : mgTestLis){
            mbIds.add(string.valueOf(mg.Id));
        }
        String emails = NASFGroupSelectLightningController.sendForm(mbIds);
        system.assertNotEquals(null, emails);
        
    }
    
    @IsTest
    static void flowCheck_Test() {
        Account TestAcct = [SELECT Id FROM Account LIMIT 1];
        String error = NASFGroupSelectLightningController.flowCheck(TestAcct.Id);
        system.assertNotEquals(Null, error);       
    }
    
    @IsTest
    static void findContactIdTest() {
        Account TestAcct = [SELECT Id, Primary_Billing_Contact__c FROM Account WHERE Name != 'UMR' LIMIT 1];
        String findCon = NASFGroupSelectLightningController.findContactId(TestAcct.Id);
        system.assertEquals(findCon, TestAcct.Primary_Billing_Contact__c);
    }
    
    @IsTest
	static void srvAcctWrapper_Test() {
        NASFGroupSelectLightningController.srvAcctWrapper wrapper = new NASFGroupSelectLightningController.srvAcctWrapper(null, null, null);
        wrapper.isChecked = null;
        wrapper.srvAcctId = null;
        wrapper.srvAcctName = null;
        system.assertEquals(null, wrapper.isChecked);
        system.assertEquals(null, wrapper.srvAcctId);
        system.assertEquals(null, wrapper.srvAcctName);
    }
    
    @IsTest
    static void findSrvAcctTest() {
        Account TestAcct = [SELECT Id, Primary_Billing_Contact__c FROM Account WHERE Name != 'UMR' LIMIT 1];
        Account acct2 = new Account();
        acct2.Name ='Acct Rel Test';
        Insert acct2;        
        Acct_Rel__c acctRel = new Acct_Rel__c();
        acctRel.Benefit_Sponsor__c = TestAcct.Id;
        acctRel.Svc_Acct__c = acct2.Id;
        acctRel.Relationship_Type__c = 'Contractee';
        acctRel.Start_Date__c = system.today();
        insert acctRel;
        NASFGroupSelectLightningController.findSrvAcct(TestAcct.Id);
    }
}