manifest/objects/Acct_Rel__c.object
<CustomObject>
    <description>Models the possible contracts between any two accounts regardless of hierarchy</description>
    <fields>
        <fullName>Benefit_Sponsor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account receiving services</description>
        <inlineHelpText>Lookup the Benefit Sponsor Account (Account receiving services) of the Relationship</inlineHelpText>
        <label>Benefit Sponsor Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Servicing Accounts</relationshipLabel>
        <relationshipName>servicingaccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>Required on Contractee/Broker</description>
        <inlineHelpText>Required on Contractee/Broker</inlineHelpText>
        <label>Servicing Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Relationship_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Contract_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <description>Select the type of Relationship for the Servicing Account.</description>
        <inlineHelpText>Select the type of Relationship for the Servicing Account.</inlineHelpText>
        <label>Servicing Account Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Account_Relationship_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date contract starts</description>
        <inlineHelpText>Enter the Date Relationship Started</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Svc_Acct__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account providing the service</description>
        <inlineHelpText>Lookup the Servicing Account of the Relationship</inlineHelpText>
        <label>Servicing Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Benefit Sponsor Accounts</relationshipLabel>
        <relationshipName>benefitsponsors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>REL-{00000000}</displayFormat>
        <label>Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/AcctGrpConParse_Exception__c.object
<CustomObject>
    <fields>
        <fullName>Short_Desc__c</fullName>
        <description>Abbreviated string hinting at the cause.</description>
        <label>Short Description</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AcctGrpConParse Exception</label>
    <nameField>
        <displayFormat>AGCPE-{00000000}</displayFormat>
        <label>AcctGrpConParse Exception</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AcctGrpConParse Exceptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/AcctGrpConParsing_Item__c.object
<CustomObject>
    <description>Staging queue to hold all data transmitted to create Accounts, groups, and contacts.</description>
    <fields>
        <fullName>Item_Data__c</fullName>
        <description>Data used to create supporting records</description>
        <label>Item Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>AcctGrpConParsing Item</label>
    <nameField>
        <displayFormat>AGCPI-{00000000}</displayFormat>
        <label>AcctGrpConParsing Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AcctGrpConParsing Item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Mkt_Site_User__c.object
<CustomObject>
    <label>Mkt Site User</label>
    <nameField>
        <displayFormat>MSU-{00000000}</displayFormat>
        <label>Mkt Site User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mkt Site Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/globalValueSets/Account_Relationship_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Benefit Partner or Vendor</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Contractee</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Provider Only</fullName>
    </customValue>
    <customValue>
        <fullName>Payer and Eligibility Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Payer Only</fullName>
    </customValue>
    <customValue>
        <fullName>Referral Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Benefit Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Contractor</fullName>
        <isActive>false</isActive>
        <label>Contractor</label>
    </customValue>
    <customValue>
        <fullName>Benefit Partner</fullName>
        <isActive>false</isActive>
        <label>Benefit Partner</label>
    </customValue>
    <customValue>
        <fullName>Benefit Sponsor</fullName>
        <isActive>false</isActive>
        <label>Benefit Sponsor</label>
    </customValue>
    <masterLabel>Account Relationship Type</masterLabel>
</GlobalValueSet>

manifest/globalValueSets/Contract_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Health Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Platform</fullName>
    </customValue>
    <masterLabel>Contract Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

manifest/classes/F1bContact_Test.cls
public class F1bContact_Test {
  public static void noContactData() {
    SBQQ.TriggerControl.disable();
    List<AcctGrpConParsing_Item__c> agcpiList = [
      SELECT Id, Item_Data__c
      FROM AcctGrpConParsing_Item__c
    ];
    F1BMainParser f1bp = new F1BMainParser();
    f1bp.parse(agcpiList[0].Item_Data__c);
    F1bp_Test.buildData(f1bp);
    Contact dataContact = [SELECT Id FROM Contact];
    f1bp.f1bcp = null;
    Test.startTest();
    F1BProcessor.ProcessEntry(f1bp, agcpiList[0].Id);
    //System.assertEquals(0, [ SELECT Count() FROM Contact WHERE Id != :dataContact.Id ]);
    Test.stopTest();
    SBQQ.TriggerControl.enable();
  }

  public static void marketUserCheckboxCheck_Test() {
    List<AcctGrpConParsing_Item__c> agcpiList = [
      SELECT Id, Item_Data__c
      FROM AcctGrpConParsing_Item__c
    ];
    F1BMainParser f1bp = new F1BMainParser();
    f1bp.parse(agcpiList[0].Item_Data__c);
    F1bp_Test.buildData(f1bp);
    Contact dataContact = [SELECT Id FROM Contact];
    Test.startTest();
    F1BProcessor.ProcessEntry(f1bp, agcpiList[0].Id);
    //System.assertEquals(1, [ SELECT Count() FROM Contact WHERE Marketing_Site_User__c = True AND Id != :dataContact.Id ]);
    //System.assertEquals(1, [ SELECT Count() FROM Contact WHERE Marketing_Site_User__c = False AND Id != :dataContact.Id ]);
    Test.stopTest();
  }

  public static void dupContactError_Test() {
    List<AcctGrpConParsing_Item__c> agcpiList = [
      SELECT Id, Item_Data__c
      FROM AcctGrpConParsing_Item__c
    ];
    F1BMainParser f1bp = new F1BMainParser();
    f1bp.parse(agcpiList[0].Item_Data__c);
    F1bp_Test.buildData(f1bp);
    Contact con = new Contact(
      lastName = 'test',
      firstName = 'test',
      Email = 'test@tsSst.com'
    );
    insert con;
    Map<String, Contact> mapCon = new Map<String, Contact>();
    mapCon.put('SAE', con);
    List<Map<String, Contact>> contactList = new List<Map<String, Contact>>();
    contactList.add(mapCon);
    f1bp.f1bcp.bspContacts = contactList;
    Test.startTest();
    F1BProcessor.ProcessEntry(f1bp, agcpiList[0].Id);
    //System.assertEquals(0, [SELECT Count() FROM AcctGrpConParse_Exception__c WHERE Short_Desc__c = 'CANNOT_CREATE_CONTACT' ]);
    Test.stopTest();
  }

  public static void updateContact() {
    List<AcctGrpConParsing_Item__c> agcpiList = [
      SELECT Id, Item_Data__c
      FROM AcctGrpConParsing_Item__c
    ];
    F1BMainParser f1bp = new F1BMainParser();
    f1bp.parse(agcpiList[0].Item_Data__c);
    F1bp_Test.buildData(f1bp);
    Contact con = new Contact(
      lastName = 'test',
      firstName = 'test',
      Email = 'test@tsSst.com',
      Marketing_Site_User__c = false
    );
    insert con;
    Map<String, Contact> mapCon = new Map<String, Contact>();
    mapCon.put('Marketing', con);
    List<Map<String, Contact>> contactList = new List<Map<String, Contact>>();
    contactList.add(mapCon);
    f1bp.f1bcp.bspContacts = contactList;
    Test.startTest();
    F1BProcessor.ProcessEntry(f1bp, agcpiList[0].Id);
    //System.assertEquals(true, [SELECT Marketing_Site_User__c FROM Contact WHERE Id =: con.Id].Marketing_Site_User__c);
    Test.stopTest();
  }

  /*
    public static void createMktUser() {
        Account acct = TestDataFactory.createParentAccount();
        Account ParentAcct = [SELECT Id FROM Account WHERE Name = 'National General'];
		List<AcctGrpConParsing_Item__c> agcpiList = [SELECT Id, Item_Data__c FROM AcctGrpConParsing_Item__c ];
		F1BMainParser f1bp = new F1BMainParser();
		f1bp.parse(agcpiList[0].Item_Data__c);
		F1bp_Test.buildData(f1bp);
        Test.startTest();
        Contact con = new Contact(lastName = 'test', firstName = 'test', Email = 'test@tsSst.com', Marketing_Site_User__c = true, AccountId = acct.Id);
		insert con;
        Acct_Rel__c acctRel = new Acct_Rel__c(Benefit_Sponsor__c = acct.Id, Svc_Acct__c = ParentAcct.Id, Relationship_Type__c = 'Contractee', 
                                              Contract_Type__c = 'Direct', Start_Date__c = date.today());
        insert acctRel;
		Map<String, Contact> mapCon = new Map<String, Contact>();
		mapCon.put('Marketing', con);
		List<Map<String, Contact>> contactList = new List<Map<String, Contact>>();
		contactList.add(mapCon);
		f1bp.f1bcp.bspContacts = contactList;
        system.debug(f1bp.ParentGuid);
		F1BProcessor.ProcessEntry(f1bp, agcpiList[0].Id);
		System.assertEquals(1, [SELECT count() FROM Mkt_Site_User__c]);
		Test.stopTest();
	}
	*/
}