manifest/objects/Acct_Rel__c.object
<CustomObject>
    <description>Models the possible contracts between any two accounts regardless of hierarchy</description>
    <fields>
        <fullName>Benefit_Sponsor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account receiving services</description>
        <inlineHelpText>Lookup the Benefit Sponsor Account (Account receiving services) of the Relationship</inlineHelpText>
        <label>Benefit Sponsor Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Servicing Accounts</relationshipLabel>
        <relationshipName>servicingaccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Broker_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Who helped with the deal</description>
        <inlineHelpText>Lookup the Contact Name of Broker</inlineHelpText>
        <label>Broker Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Contact - Value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Svc_Acct__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Relationships</relationshipLabel>
        <relationshipName>Account_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Broker_Flat_Rate__c</fullName>
        <description>Flat Rate Commission for Broker</description>
        <inlineHelpText>Enter the Flat Rate Commission for Broker</inlineHelpText>
        <label>Broker Flat-Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Svc_Acct__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account providing the service</description>
        <inlineHelpText>Lookup the Servicing Account of the Relationship</inlineHelpText>
        <label>Servicing Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Benefit Sponsor Accounts</relationshipLabel>
        <relationshipName>benefitsponsors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>REL-{00000000}</displayFormat>
        <label>Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Mbr_Group__c.object
<CustomObject>
    <fields>
        <fullName>Active_Date__c</fullName>
        <description>Date Group was built in Admin</description>
        <inlineHelpText>Date Group was built in Admin</inlineHelpText>
        <label>Active Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <description>Account that the Group is created</description>
        <inlineHelpText>Account that the Group is created</inlineHelpText>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Member Groups</relationshipLabel>
        <relationshipName>Member_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <description>System Generated Global UniqueId</description>
        <externalId>true</externalId>
        <inlineHelpText>System Generated Global UniqueId</inlineHelpText>
        <label>GUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Enter a descriptive Member Group Name.</description>
        <inlineHelpText>Enter a descriptive Member Group Name.</inlineHelpText>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Member Group</label>
    <nameField>
        <displayFormat>MG-{00000000}</displayFormat>
        <label>Member Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Mbr_Group_Role__c.object
<CustomObject>
    <fields>
        <fullName>Mbr_Group__c</fullName>
        <description>SF Record name of the Group</description>
        <inlineHelpText>SF Record name of the Group</inlineHelpText>
        <label>Member Group</label>
        <referenceTo>Mbr_Group__c</referenceTo>
        <relationshipLabel>Member Group Roles</relationshipLabel>
        <relationshipName>Member_Group_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Member Group Role</label>
    <nameField>
        <displayFormat>MGR-{00000000}</displayFormat>
        <label>Member Group Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Group Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Plan_Specific_Fees__c.object
<CustomObject>
    <fields>
        <fullName>Member_Group__c</fullName>
        <label>Member Group</label>
        <referenceTo>Mbr_Group__c</referenceTo>
        <relationshipLabel>Plan-Specific Fees By Product</relationshipLabel>
        <relationshipName>Plan_Specific_Fees_By_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Plan-Specific Fees By Product</label>
    <nameField>
        <displayFormat>PSF-{0000000}</displayFormat>
        <label>Plan Fees ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan-Specific Fees By Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>Consult_Fees__c</fullName>
        <label>Consult Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product used to sell this subscription.</description>
        <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/classes/IntakeFormController_Test.cls
@IsTest
public with sharing class IntakeFormController_Test {
  static testMethod void testNASF() {
    Account umrAcct = TestDataFactory.createUMR();
    Profile p = [SELECT Id FROM Profile LIMIT 1];
    User u = TestDataFactory.createUser(p.Id);

    Contact am = TestDataFactory.createContactDynamicVals(
      'Tim',
      'Amity',
      'tim@amity.tim',
      null
    );

    Account ab = TestDataFactory.createAccountUMRNoInsert();
    ab.Friendly_Account_Name__c = 'Brk';
    ab.GUID__c = 'ced85d79-65b7-4b3e-aa3c-039c0fe65406';
    insert ab;

    Contact cb = TestDataFactory.createContactDynamicVals(
      'Barry',
      'Broker',
      'barry@broker.barry',
      ab.Id
    );

    insert new List<SObject>{ u, am, cb };

    Account a = TestDataFactory.createAccount('Test Account, LLC');

    Acct_Rel__c arc = TestDataFactory.createAccRel(ab.Id, 'Broker', null, null);
    arc.Benefit_Sponsor__c = a.Id;
    arc.Svc_Acct__c = ab.Id;
    arc.Broker_Contact__c = cb.Id;
    arc.Broker_Flat_Rate__c = 100.30;

    Acct_Rel__c arc2 = TestDataFactory.createAccRel(
      ab.Id,
      'Payer Only',
      null,
      null
    );
    arc2.Svc_Acct__c = a.Id;
    arc2.Benefit_Sponsor__c = a.Id;

    Acct_Rel__c arc3 = TestDataFactory.createAccRel(
      ab.Id,
      'Broker',
      null,
      null
    );
    arc3.Svc_Acct__c = a.Id;
    arc3.Benefit_Sponsor__c = a.Id;
    arc3.Broker_Contact__c = cb.Id;
    arc3.Broker_Flat_Rate__c = 100.30;

    Acct_Rel__c arc4 = TestDataFactory.createAccRel(
      ab.Id,
      'Contractee',
      'Direct',
      'N/A'
    );
    arc4.Benefit_Sponsor__c = a.Id;

    Mbr_Group__c mg = TestDataFactory.createMbrGroup(a.Id)[0];
    /*mg.Client_Account__c = a.Id;
        mg.Active_Date__c = Date.today() - 30;
        mg.Name__c = 'great group';*/

    insert new List<SObject>{ arc, arc2, arc4 };

    Plan_Specific_Fees__c psf = TestDataFactory.PlanSpecificFees();
    psf.Member_Group__c = mg.Id;

    Mbr_Group_Role__c mgr = TestDataFactory.createGroupRole(
      mg.Id,
      'Billing',
      ab.Id,
      cb.Id
    );
    insert new List<SObject>{ mgr, psf };
    Id tmpPb = Test.getStandardPricebookId();

    Opportunity o = TestDataFactory.createOpportunityWithPriceBook(
      a.Id,
      tmpPb,
      null
    );
    o.LeadSource = 'Sales';
    insert o;

    Product2 prod = TestDataFactory.createSingleProduct(
      'Behavioral Health',
      'Behavioral Health',
      'BH1PT'
    );
    insert prod;

    PricebookEntry tmpPbe = TestDataFactory.createPriceBookEntries(
      new List<Product2>{ prod },
      tmpPb
    )[0];
    //new PricebookEntry(Pricebook2Id = tmpPb, Product2Id = prod.Id, UnitPrice = 0, IsActive = true);
    insert tmpPbe;
    SBQQ__Subscription__c sub = TestDataFactory.createSBQQSubscription(a.Id);
    sub.SBQQ__Product__c = prod.Id;
    insert sub;

    /* OpportunityLineItem oli = new OpportunityLineItem();
        oli.OpportunityId = o.Id;
        oli.Consult_Fees__c = 2;
        oli.Product2Id = prod.Id;
        oli.PricebookEntryId = tmpPbe.Id;
        oli.Quantity=1;
        oli.TotalPrice = 23;
        insert oli;*/

    Test.startTest();
    // Open the preview page, run all three actions
    Test.setCurrentPage(Page.IntakeFormPreview);
    ApexPages.currentPage().getParameters().put('oid', o.Id);
    IntakeFormPreviewController ic = new IntakeFormPreviewController();
    ic.sendIntakeForm();
    ic.showPDF();
    ic.cancelIntakeForm();

    // Open the View page as PDF
    Test.setCurrentPage(Page.IntakeFormView);
    ApexPages.currentPage().getParameters().put('oid', o.Id);
    ApexPages.currentPage().getParameters().put('view', 'pdf');
    IntakeFormViewController pc = new IntakeFormViewController();
    System.assert(pc.opportunityId == o.Id);
    Test.stopTest();
  }
}