manifest/objects/AcctGrpConParsing_Item__c.object
<CustomObject>
    <description>Staging queue to hold all data transmitted to create Accounts, groups, and contacts.</description>
    <fields>
        <fullName>Batch_Key__c</fullName>
        <description>Used to identify grouped submissions</description>
        <label>Batch Key</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Data__c</fullName>
        <description>Data used to create supporting records</description>
        <label>Item Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Item_Defaults__c</fullName>
        <label>Item Defaults</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Item_Key__c</fullName>
        <label>Item Key</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>UMR, GENERIC, etc.</description>
        <label>Source</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AcctGrpConParsing Item</label>
    <nameField>
        <displayFormat>AGCPI-{00000000}</displayFormat>
        <label>AcctGrpConParsing Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AcctGrpConParsing Item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/classes/UmrUploadWebService.cls
global class UmrUploadWebService {
  // Create items in queue to allow for future processing.  This overcomes response timeouts in webservice call
  webService static String PostData(
    string incomingData,
    string fieldDefaultData
  ) {
    String batchid = String.valueOf(DateTime.now().getTime());

    // Put data back into object form
    List<PostingData> tmpPostedData = (List<PostingData>) JSON.deserialize(
      incomingData,
      List<PostingData>.class
    );
    Map<String, String> mappedDefaults = null;
    if (!String.isBlank(fieldDefaultData))
      mappedDefaults = (Map<String, String>) JSON.deserialize(
        fieldDefaultData,
        Map<String, String>.class
      );

    List<AcctGrpConParsing_Item__c> queuedItems = new List<AcctGrpConParsing_Item__c>();
    for (PostingData tmpPd : tmpPostedData) {
      AcctGrpConParsing_Item__c tmpAGCPI = new AcctGrpConParsing_Item__c(
        source__c = 'UMR',
        batch_key__c = batchid,
        item_data__c = JSON.serialize(tmpPd),
        item_key__c = tmpPd.groupId,
        item_defaults__c = fieldDefaultData
      );
      queuedItems.add(tmpAGCPI);
    }
    insert queuedItems;
    UmrAcctGrpConParse_Bch uagcpb = new UmrAcctGrpConParse_Bch(null);
    System.scheduleBatch(uagcpb, 'UMR Batch Processing', 5, 1);
    return JSON.serialize(
      '[' + batchid + '] ' + queuedItems.size() + ' items have been queued.'
    );
  }
}