manifest/objects/Acct_Rel__c.object
<CustomObject>
    <description>Models the possible contracts between any two accounts regardless of hierarchy</description>
    <fields>
        <fullName>Chronic_Care_Broker_Flat_Rate__c</fullName>
        <label>Chronic Care Broker Flat Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Chronic_Care_Broker_Percentage__c</fullName>
        <label>Chronic Care Broker Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>REL-{00000000}</displayFormat>
        <label>Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Broker_Opp_Rel__c.object
<CustomObject>
    <description>Junction object between Broker Account Relationship  and Opportunity</description>
    <fields>
        <fullName>Broker_Rel__c</fullName>
        <description>Account Relationship type of Broker</description>
        <label>Broker Relationship</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>No Broker Relationship found for the Account</errorMessage>
            <filterItems>
                <field>Acct_Rel__c.Relationship_Type__c</field>
                <operation>equals</operation>
                <value>Broker, Benefit Partner or Vendor, Broker/Benefit Consultant</value>
            </filterItems>
            <infoMessage>Please Search and Select the Broker Relationship for the Account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Acct_Rel__c</referenceTo>
        <relationshipName>Broker_Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Chronic_Care_Broker_Flat_Rate__c</fullName>
        <label>Chronic Care Broker Flat Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Chronic_Care_Broker_Percentage__c</fullName>
        <label>Chronic Care Broker Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opp_Broker__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opportunity_Brokers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Broker / Ben Con Opportunity Relation</label>
    <nameField>
        <displayFormat>BO-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Opportunity Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/classes/Brkr_Opp_Tests.cls
@IsTest
private class Brkr_Opp_Tests {
  @IsTest
  static void SourceTest() {
    // Create rel accounts
    Account svc_account = TestDataFactory.createAccount('Servicing Account');
    Account bsp_account = TestDataFactory.createParentAccount();

    // create acct rel
    Acct_Rel__c tmpAr = TestDataFactory.createAcctRel(
      svc_account.id,
      bsp_account.id
    );

    // create opportunity
    Opportunity tmpOpp = TestDataFactory.createOpportunity(bsp_account.id);
    tmpOpp.stagename = 'Prospect';
    tmpOpp.closedate = Date.today() + 90;
    insert tmpOpp;

    // finally create broker / opp rel

    Broker_Opp_Rel__c tmpBor = TestDataFactory.createBrokerOppRel();
    tmpBor.opp_broker__c = tmpOpp.id;
    tmpBor.broker_rel__c = tmpAr.id;
    insert tmpBor;
    Broker_Opp_Rel__c bko = [
      SELECT
        Id,
        Chronic_Care_Broker_Flat_Rate__c,
        Chronic_Care_Broker_Percentage__c
      FROM Broker_Opp_Rel__c
    ];
    system.assertEquals(0.10, bko.Chronic_Care_Broker_Flat_Rate__c);
    system.assertEquals(0.10, bko.Chronic_Care_Broker_Percentage__c);
  }
}