manifest/objects/Acct_Rel__c.object
<CustomObject>
    <description>Models the possible contracts between any two accounts regardless of hierarchy</description>
    <fields>
        <fullName>Benefit_Sponsor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account receiving services</description>
        <inlineHelpText>Lookup the Benefit Sponsor Account (Account receiving services) of the Relationship</inlineHelpText>
        <label>Benefit Sponsor Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Servicing Accounts</relationshipLabel>
        <relationshipName>servicingaccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legacy_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Former Account which got merged into the Legacy Id to the Master Account</description>
        <label>Legacy Id</label>
        <referenceTo>Legacy_Id__c</referenceTo>
        <relationshipLabel>Former Relationships</relationshipLabel>
        <relationshipName>Former_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Svc_Acct__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account providing the service</description>
        <inlineHelpText>Lookup the Servicing Account of the Relationship</inlineHelpText>
        <label>Servicing Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Benefit Sponsor Accounts</relationshipLabel>
        <relationshipName>benefitsponsors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>REL-{00000000}</displayFormat>
        <label>Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Legacy_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the former Account which got converted into Legacy Id on Master Account</description>
        <label>Legacy Id</label>
        <referenceTo>Legacy_Id__c</referenceTo>
        <relationshipLabel>Legacy Assets</relationshipLabel>
        <relationshipName>Legacy_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscribed Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Id__c</fullName>
        <externalId>true</externalId>
        <label>Source Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Legacy_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the former Account which got converted into Legacy Id on Master Account</description>
        <label>Legacy Id</label>
        <referenceTo>Legacy_Id__c</referenceTo>
        <relationshipLabel>Legacy Cases</relationshipLabel>
        <relationshipName>Legacy_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Id__c</fullName>
        <externalId>true</externalId>
        <label>Source Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

manifest/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Legacy_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the former Account which got converted into Legacy Id on Master Account</description>
        <label>Legacy Id</label>
        <referenceTo>Legacy_Id__c</referenceTo>
        <relationshipLabel>Legacy Contracts</relationshipLabel>
        <relationshipName>Legacy_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Legacy_Id__c.object
<CustomObject>
    <fields>
        <fullName>Master_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>ID of account that won the merge.</description>
        <label>Master Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Legacy Ids</relationshipLabel>
        <relationshipName>Legacy_Ids</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Id__c</fullName>
        <label>Source Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BD</fullName>
                </value>
                <value>
                    <fullName>HUB</fullName>
                </value>
                <value>
                    <fullName>TD</fullName>
                </value>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>LV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>guid__c</fullName>
        <label>GUID</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <label>Legacy Id</label>
    <nameField>
        <displayFormat>LID-{00000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Legacy Ids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Location__c.object
<CustomObject>
    <description>Used to store non-contractual locations such as broker locations, hospitals, and stores</description>
    <fields>
        <fullName>Legacy_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the former Account which got converted into Legacy Id on Master Account</description>
        <label>Legacy Id</label>
        <referenceTo>Legacy_Id__c</referenceTo>
        <relationshipLabel>Former Locations</relationshipLabel>
        <relationshipName>Former_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location_HQ__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location HQ</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Mbr_Group__c.object
<CustomObject>
    <fields>
        <fullName>Client_Account_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client Account Location associated with the Group</description>
        <inlineHelpText>This links the member group to a specific location on the client account.</inlineHelpText>
        <label>Client Account Location</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Location not found on Client Account</errorMessage>
            <filterItems>
                <field>Location__c.Location_HQ__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Client_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Member Groups</relationshipLabel>
        <relationshipName>Member_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Account_Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Connects the member group to an account relationship object record.</description>
        <inlineHelpText>This links the member group to a specific relationship on the client account.  For example, group can be linked to a specific health plan relationship to show it is under medicaid, commercial, etc.</inlineHelpText>
        <label>*Deprecated* Client Account Relationship</label>
        <referenceTo>Acct_Rel__c</referenceTo>
        <relationshipLabel>Member Groups</relationshipLabel>
        <relationshipName>Member_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <description>Account that the Group is created</description>
        <inlineHelpText>Account that the Group is created</inlineHelpText>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Member Groups</relationshipLabel>
        <relationshipName>Member_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <description>System Generated Global UniqueId</description>
        <externalId>true</externalId>
        <inlineHelpText>System Generated Global UniqueId</inlineHelpText>
        <label>GUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Legacy_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the former Account which got converted into Legacy Id on Master Account</description>
        <label>Legacy Id</label>
        <referenceTo>Legacy_Id__c</referenceTo>
        <relationshipLabel>Legacy Member Groups</relationshipLabel>
        <relationshipName>Legacy_Member_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Id__c</fullName>
        <description>Salesforce ID from original system record was migrated</description>
        <externalId>true</externalId>
        <inlineHelpText>Salesforce ID from original system record was migrated</inlineHelpText>
        <label>Source Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Use this as a backend field to identify the source of member group record</description>
        <inlineHelpText>Use this as a backend field to identify the source of member group record</inlineHelpText>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Data_Source</valueSetName>
        </valueSet>
    </fields>
    <label>Member Group</label>
    <nameField>
        <displayFormat>MG-{00000000}</displayFormat>
        <label>Member Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/SBQQ__SubscribedAsset__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscribedAssetHelp</customHelpPage>
    <description>Links a particular asset to the subscription that covers it.</description>
    <fields>
        <fullName>SBQQ__Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Asset being covered by a subscription.</description>
        <inlineHelpText>Asset being covered by a subscription.</inlineHelpText>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Subscription__c</fullName>
        <description>Subscription that covers the asset.</description>
        <inlineHelpText>Subscription that covers the asset.</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Subscribed Assets</relationshipLabel>
        <relationshipName>SubscribedAssets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subscribed Asset</label>
    <nameField>
        <displayFormat>SA-{00000000}</displayFormat>
        <label>Subscribed Asset#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribed Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>Legacy_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the former Account which got converted into Legacy Id on Master Account</description>
        <label>Legacy Id</label>
        <referenceTo>Legacy_Id__c</referenceTo>
        <relationshipLabel>Legacy Subscriptions</relationshipLabel>
        <relationshipName>Legacy_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account that owns this subscription. This relationship is used for volume discount calculations.</description>
        <inlineHelpText>Account that owns this subscription. This relationship is used for volume discount calculations.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contract that governs this subscription.</description>
        <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Id__c</fullName>
        <description>** Back End only ** Do not add to page layouts</description>
        <externalId>true</externalId>
        <label>Source Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/globalValueSets/Data_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>HUB</fullName>
        <default>true</default>
        <label>HUB</label>
    </customValue>
    <customValue>
        <fullName>TD</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>LVGO</fullName>
    </customValue>
    <customValue>
        <fullName>GCRM</fullName>
    </customValue>
    <masterLabel>Data Source</masterLabel>
</GlobalValueSet>

manifest/classes/MergeAccounts.cls
public with sharing class MergeAccounts {
  public static void mergeAccounts(Map<String, String> accountsMap) {
    Account masterAccount, childAccount;

    List<String> errorList = new List<String>();

    List<Account> account2Update = new List<Account>();
    List<Acct_Rel__c> ServRel2Update = new List<Acct_Rel__c>();
    List<Acct_Rel__c> BenRel2Update = new List<Acct_Rel__c>();
    List<Location__c> Location2Update = new List<Location__c>();
    List<Contact> Contacts2Update = new List<Contact>();
    List<AccountContactRelation> acr2Insert = new List<AccountContactRelation>();
    List<Opportunity> opp2Update = new List<Opportunity>();
    List<Contract> cont2Update = new List<Contract>();
    List<SBQQ__Subscription__c> subs2Update = new List<SBQQ__Subscription__c>();
    List<Asset> assets2Update = new List<Asset>();
    List<Mbr_Group__c> mebGrp2Update = new List<Mbr_Group__c>();
    List<Case> case2Update = new List<Case>();
    List<Task> task2Update = new List<Task>();
    List<Event> event2Update = new List<Event>();

    Map<String, Account> masterAccountMap = new Map<String, Account>();
    Map<String, Account> childAccountMap = new Map<String, Account>();
    //Map<Id,String> childAccountIds = new Map<Id,String>();
    Map<String, Legacy_Id__c> legacyIdMap = new Map<String, Legacy_Id__c>();
    Map<String, List<Acct_Rel__c>> serRelationsMap = new Map<String, List<Acct_Rel__c>>();
    Map<String, List<Acct_Rel__c>> benRelationsMap = new Map<String, List<Acct_Rel__c>>();
    Map<String, List<Location__c>> locationMap = new Map<String, List<Location__c>>();
    Map<String, List<Contact>> contactMap = new Map<String, List<Contact>>();
    Map<String, List<AccountContactRelation>> acrMap = new Map<String, List<AccountContactRelation>>();
    Map<String, List<Opportunity>> oppMap = new Map<String, List<Opportunity>>();
    Map<String, List<Contract>> contrMap = new Map<String, List<Contract>>();
    Map<String, List<SBQQ__Subscription__c>> subsMap = new Map<String, List<SBQQ__Subscription__c>>();
    Map<String, List<Asset>> assetMap = new Map<String, List<Asset>>();
    Map<String, List<Mbr_Group__c>> mbrGrpMap = new Map<String, List<Mbr_Group__c>>();
    Map<String, List<Case>> caseMap = new Map<String, List<Case>>();
    Map<String, List<Task>> taskMap = new Map<String, List<Task>>();
    Map<String, List<Event>> eventMap = new Map<String, List<Event>>();

    for (Account cAccount : [
      SELECT id, name, source__c, source_id__c, GUID__c
      FROM Account
      WHERE GUID__c IN :accountsMap.keySet()
    ]) {
      childAccountMap.put(cAccount.GUID__c, cAccount);
      //childAccountIds.put(cAccount.id,cAccount.GUID__c);
    }
    for (Account mAccount : [
      SELECT id, name, source__c, source_id__c, GUID__c
      FROM Account
      WHERE GUID__c IN :accountsMap.values()
    ]) {
      masterAccountMap.put(mAccount.GUID__c, mAccount);
    }
    for (Legacy_Id__c legacyId : [
      SELECT id, GUID__c
      FROM Legacy_Id__c
      WHERE Master_Account__r.guid__c IN :accountsMap.values()
    ]) {
      legacyIdMap.put(legacyId.GUID__c, legacyId);
    }
    for (Account sevAccount : [
      SELECT id, guid__c, (SELECT id, Svc_Acct__c FROM benefitsponsors__r)
      FROM Account
      WHERE guid__c IN :accountsMap.keySet()
    ]) {
      serRelationsMap.put(sevAccount.guid__c, sevAccount.benefitsponsors__r);
    }
    for (Account benAccount : [
      SELECT
        id,
        guid__c,
        (SELECT id, Benefit_Sponsor__c FROM servicingaccounts__r)
      FROM Account
      WHERE guid__c IN :accountsMap.keySet()
    ]) {
      benRelationsMap.put(benAccount.guid__c, benAccount.servicingaccounts__r);
    }
    for (Account locAccount : [
      SELECT id, guid__c, (SELECT id, Location_HQ__c FROM Locations__r)
      FROM Account
      WHERE guid__c IN :accountsMap.keySet()
    ]) {
      locationMap.put(locAccount.guid__c, locAccount.Locations__r);
    }
    for (Account contAccount : [
      SELECT id, guid__c, (SELECT id, accountId FROM Contacts)
      FROM Account
      WHERE guid__c IN :accountsMap.keySet()
    ]) {
      contactMap.put(contAccount.guid__c, contAccount.contacts);
    }
    for (Account acrAccount : [
      SELECT
        id,
        guid__c,
        (SELECT id, accountId, contactId FROM AccountContactRelations)
      FROM Account
      WHERE guid__c IN :accountsMap.keySet()
    ]) {
      acrMap.put(acrAccount.guid__c, acrAccount.AccountContactRelations);
    }
    for (Account oppAccount : [
      SELECT id, guid__c, (SELECT id, accountId FROM opportunities)
      FROM Account
      WHERE guid__c IN :accountsMap.keySet()
    ]) {
      oppMap.put(oppAccount.guid__c, oppAccount.opportunities);
    }
    for (Account contAccount : [
      SELECT id, guid__c, (SELECT id, accountId FROM Contracts)
      FROM Account
      WHERE guid__c IN :accountsMap.keySet()
    ]) {
      contrMap.put(contAccount.guid__c, contAccount.Contracts);
    }
    for (Account subAccount : [
      SELECT
        id,
        guid__c,
        (SELECT id, SBQQ__Account__c FROM SBQQ__Subscriptions__r)
      FROM Account
      WHERE guid__c IN :accountsMap.keySet()
    ]) {
      subsMap.put(subAccount.guid__c, subAccount.SBQQ__Subscriptions__r);
    }
    for (Account assetAccount : [
      SELECT id, guid__c, (SELECT id, accountId FROM Assets)
      FROM Account
      WHERE guid__c IN :accountsMap.keySet()
    ]) {
      assetMap.put(assetAccount.guid__c, assetAccount.Assets);
    }
    for (Account mbrAccount : [
      SELECT id, guid__c, (SELECT id, Client_Account__c FROM Member_Groups__r)
      FROM Account
      WHERE guid__c IN :accountsMap.keySet()
    ]) {
      mbrgrpMap.put(mbrAccount.guid__c, mbrAccount.Member_Groups__r);
    }
    for (Account caseAccount : [
      SELECT id, guid__c, (SELECT id, accountId, contactId FROM cases)
      FROM Account
      WHERE guid__c IN :accountsMap.keySet()
    ]) {
      caseMap.put(caseAccount.guid__c, caseAccount.cases);
    }
    for (Account eventAccount : [
      SELECT Id, name, (SELECT id, whoid FROM events)
      FROM account
      WHERE guid__c IN :accountsMap.keySet()
    ]) {
      eventMap.put(eventAccount.guid__c, eventAccount.events);
    }
    for (Account taskAccount : [
      SELECT Id, name, (SELECT id, whoid FROM tasks)
      FROM account
      WHERE guid__c IN :accountsMap.keySet()
    ]) {
      taskMap.put(taskAccount.guid__c, taskAccount.tasks);
    }

    for (String cGUID : accountsMap.keySet()) {
      if (childAccountMap.get(cGUID) == null) {
        errorList.add('Child account not found for the GUID : ' + cGUID + '\n');
        continue;
      }
      //update ChildAccount
      childAccount = childAccountMap.get(cGUID);
      childAccount.guid__c = null;
      account2Update.add(childAccount);

      // EEM: might use containsKey vs checking for null or ''
      if (masterAccountMap.get(accountsMap.get(cGUID)) == null) {
        errorList.add(
          'Master account not found for the GUID : ' +
            accountsMap.get(cGUID) +
            '\n'
        );
        continue;
      }
      masterAccount = masterAccountMap.get(accountsMap.get(cGUID));

      //Create a LegacyId on MasterAccount if not Present already
      Legacy_Id__c legacyId;
      if (legacyIdMap.get(cGUID) != null) {
        System.debug(
          'Legacy Id already present on the Master Account ' +
            masterAccount.guid__c +
            ' for the ChildAccount ' +
            childAccount.guid__c
        );
        legacyId = legacyIdMap.get(cGUID);
      } else {
        legacyId = new Legacy_Id__c(
          guid__c = cGUID,
          Master_Account__c = masterAccount.id,
          Original_Name__c = childAccount.name,
          Source__c = childAccount.source__c,
          Source_Id__c = childAccount.source_id__c
        );
        Database.SaveResult saveResult = Database.insert(legacyId, false);
        if (!saveResult.isSuccess()) {
          errorList.add(
            'Exception ' +
              saveResult.errors.get(0).getMessage() +
              ' on inserting LegacyId for the ChildAccount ' +
              childAccount.guid__c +
              '\n'
          );
          continue;
        }
      }

      //Merge ServicingAccount Relationships
      if (
        serRelationsMap.get(cGUID) != null &&
        serRelationsMap.get(cGUID).size() > 0
      ) {
        for (Acct_Rel__c serRel : serRelationsMap.get(cGUID)) {
          serRel.Svc_Acct__c = masterAccount.id;
          serRel.Legacy_Id__c = legacyId.Id;
          ServRel2Update.add(serRel);
        }
      }

      //Merge BenefitSponsor Relationships
      if (
        benRelationsMap.get(cGUID) != null &&
        benRelationsMap.get(cGUID).size() > 0
      ) {
        for (Acct_Rel__c benRel : benRelationsMap.get(cGUID)) {
          benRel.Benefit_Sponsor__c = masterAccount.id;
          benRel.legacy_Id__C = legacyId.id;
          BenRel2Update.add(benRel);
        }
      }

      //Merge Locations
      if (locationMap.get(cGUID) != null && locationMap.get(cGUID).size() > 0) {
        for (Location__c loc : locationMap.get(cGUID)) {
          loc.Location_HQ__c = masterAccount.id;
          loc.legacy_Id__C = legacyId.id;
          Location2Update.add(loc);
        }
      }

      //Merge Contact
      if (contactMap.get(cGUID) != null && contactMap.get(cGUID).size() > 0) {
        for (Contact contact : contactMap.get(cGUID)) {
          contact.AccountId = masterAccount.id;
          contact.legacy_Id__C = legacyId.id;
          Contacts2Update.add(contact);
        }
      }

      //Merge AccountContactRelationship
      if (acrMap.get(cGUID) != null && acrMap.get(cGUID).size() > 0) {
        for (AccountContactRelation acr : acrMap.get(cGUID)) {
          AccountContactRelation acr2 = acr.clone(false, true, true, false);
          acr2.AccountId = masterAccount.id;
          acr2.contactId = acr.contactId;
          acr2Insert.add(acr2);
        }
      }

      //Merge MemberGroup
      if (mbrGrpMap.get(cGUID) != null && mbrGrpMap.get(cGUID).size() > 0) {
        for (Mbr_Group__c mbrGroup : mbrGrpMap.get(cGUID)) {
          mbrGroup.Client_Account__c = masterAccount.id;
          mbrGroup.legacy_Id__C = legacyId.id;
          mebGrp2Update.add(mbrGroup);
        }
      }

      //Merge Opportunity
      if (oppMap.get(cGUID) != null && oppMap.get(cGUID).size() > 0) {
        for (Opportunity opp : oppMap.get(cGUID)) {
          opp.AccountId = masterAccount.id;
          opp.legacy_Id__C = legacyId.id;
          Opp2Update.add(opp);
        }
      }

      //Merge Contract
      if (contrMap.get(cGUID) != null && contrMap.get(cGUID).size() > 0) {
        for (Contract contract : contrMap.get(cGUID)) {
          contract.AccountId = masterAccount.id;
          contract.legacy_Id__C = legacyId.id;
          cont2Update.add(contract);
        }
      }

      //Merge Subscription
      if (subsMap.get(cGUID) != null && subsMap.get(cGUID).size() > 0) {
        for (SBQQ__Subscription__c sub : subsMap.get(cGUID)) {
          sub.SBQQ__Account__c = masterAccount.id;
          sub.legacy_Id__C = legacyId.id;
          subs2Update.add(sub);
        }
      }

      //Merge Assets
      if (assetMap.get(cGUID) != null && assetMap.get(cGUID).size() > 0) {
        for (Asset asset : assetMap.get(cGUID)) {
          asset.AccountId = masterAccount.id;
          asset.legacy_Id__C = legacyId.id;
          Assets2Update.add(asset);
        }
      }

      //Merge Cases
      if (caseMap.get(cGUID) != null && caseMap.get(cGUID).size() > 0) {
        for (Case c : caseMap.get(cGUID)) {
          c.AccountId = masterAccount.id;
          c.legacy_Id__C = legacyId.id;
          Case2Update.add(c);
        }
      }

      //Merge events
      if (eventMap.get(cGUID) != null && eventMap.get(cGUID).size() > 0) {
        for (Event event : eventMap.get(cGUID)) {
          event.whatId = masterAccount.id;
          event2Update.add(event);
        }
      }

      //Merge tasks
      if (taskMap.get(cGUID) != null && taskMap.get(cGUID).size() > 0) {
        for (Task task : taskMap.get(cGUID)) {
          task.whatId = masterAccount.id;
          task2Update.add(task);
        }
      }
    }

    List<Database.SaveResult> saveResultsSAccount = Database.update(
      account2Update,
      false
    );
    List<Database.SaveResult> saveResultsServRel = Database.update(
      ServRel2Update,
      false
    );
    List<Database.SaveResult> saveResultsBenRel = Database.update(
      BenRel2Update,
      false
    );
    List<Database.SaveResult> saveResultsLocation = Database.update(
      Location2Update,
      false
    );
    List<Database.SaveResult> saveResultsContact = Database.update(
      Contacts2Update,
      false
    );
    List<Database.SaveResult> saveResultsAcr = Database.Insert(
      acr2Insert,
      false
    );
    List<Database.SaveResult> saveResultsMbrGroup = Database.update(
      mebGrp2Update,
      false
    );
    List<Database.SaveResult> saveResultsOpp = Database.update(
      opp2Update,
      false
    );
    List<Database.SaveResult> saveResultsContract = Database.update(
      cont2Update,
      false
    );
    List<Database.SaveResult> saveResultsSubs = Database.update(
      subs2Update,
      false
    );
    List<Database.SaveResult> saveResultsAssets = Database.update(
      assets2Update,
      false
    );
    List<Database.SaveResult> saveResultsCase = Database.update(
      case2Update,
      false
    );
    List<Database.SaveResult> saveResultsEvent = Database.update(
      event2Update,
      false
    );
    List<Database.SaveResult> saveResultsTask = Database.update(
      task2Update,
      false
    );

    // EEM: May want to filter results by those that are NOT 'SUCCESS' otherwise debug will truncate log
    for (Database.SaveResult resulta : saveResultsSAccount) {
      System.debug(resulta);
    }
    for (Database.SaveResult result : saveResultsServRel) {
      System.debug(result);
    }
    for (Database.SaveResult result : saveResultsBenRel) {
      System.debug(result);
    }
    for (Database.SaveResult result : saveResultsLocation) {
      System.debug(result);
    }
    for (Database.SaveResult result : saveResultsContact) {
      System.debug(result);
    }
    for (Database.SaveResult result : saveResultsAcr) {
      System.debug(result);
    }
    for (Database.SaveResult result : saveResultsMbrGroup) {
      System.debug(result);
    }
    for (Database.SaveResult result : saveResultsOpp) {
      System.debug(result);
    }
    for (Database.SaveResult result : saveResultsContract) {
      System.debug(result);
    }
    for (Database.SaveResult result : saveResultsSubs) {
      System.debug(result);
    }
    for (Database.SaveResult result : saveResultsAssets) {
      System.debug(result);
    }
    for (Database.SaveResult result : saveResultsCase) {
      System.debug(result);
    }
    for (Database.SaveResult result : saveResultsEvent) {
      System.debug(result);
    }
    for (Database.SaveResult result : saveResultsTask) {
      System.debug(result);
    }

    System.debug(errorList);
  }
  // EEM: this process must be run one-each to prevent governor limits. tasks and events will prove to challenge the limits of 50k records read
}