manifest/objects/Acct_Rel__c.object
<CustomObject>
    <description>Models the possible contracts between any two accounts regardless of hierarchy</description>
    <fields>
        <fullName>Benefit_Sponsor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account receiving services</description>
        <inlineHelpText>Lookup the Benefit Sponsor Account (Account receiving services) of the Relationship</inlineHelpText>
        <label>Benefit Sponsor Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Servicing Accounts</relationshipLabel>
        <relationshipName>servicingaccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Broker_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Who helped with the deal</description>
        <inlineHelpText>Lookup the Contact Name of Broker</inlineHelpText>
        <label>Broker Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Contact - Value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Svc_Acct__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Relationships</relationshipLabel>
        <relationshipName>Account_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Broker_Flat_Rate__c</fullName>
        <description>Flat Rate Commission for Broker</description>
        <inlineHelpText>Enter the Flat Rate Commission for Broker</inlineHelpText>
        <label>Broker Flat-Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Broker_Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Physical location of a organization&apos;s site</description>
        <inlineHelpText>Lookup the Broker&apos;s Location</inlineHelpText>
        <label>Broker Location ID</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Location - Value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Location__c.Location_HQ__c</field>
                <operation>equals</operation>
                <valueField>$Source.Svc_Acct__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Account Relationships</relationshipLabel>
        <relationshipName>Account_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Broker_Percentage__c</fullName>
        <description>Percentage Commission Amount for Broker</description>
        <inlineHelpText>Enter the Percentage Commission Amount for Broker</inlineHelpText>
        <label>Broker Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Chronic_Care_Broker_Flat_Rate__c</fullName>
        <label>Chronic Care Broker Flat Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Chronic_Care_Broker_Percentage__c</fullName>
        <label>Chronic Care Broker Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <description>Select the type of Relationship for the Servicing Account.</description>
        <inlineHelpText>Select the type of Relationship for the Servicing Account.</inlineHelpText>
        <label>Servicing Account Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Account_Relationship_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date contract starts</description>
        <inlineHelpText>Enter the Date Relationship Started</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Svc_Acct__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account providing the service</description>
        <inlineHelpText>Lookup the Servicing Account of the Relationship</inlineHelpText>
        <label>Servicing Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Benefit Sponsor Accounts</relationshipLabel>
        <relationshipName>benefitsponsors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>REL-{00000000}</displayFormat>
        <label>Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Location__c.object
<CustomObject>
    <description>Used to store non-contractual locations such as broker locations, hospitals, and stores</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/OpportunityContactRole.object
<CustomObject>
    <fields>
        <fullName>Broker_Flat_Rate__c</fullName>
        <label>Broker Flat-Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Broker_Percentage__c</fullName>
        <label>Broker Percentage</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Chronic_Care_Broker_Flat_Rate__c</fullName>
        <label>Chronic Care Broker Flat-Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Chronic_Care_Broker_Percentage__c</fullName>
        <label>Chronic Care Broker Percentage</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

manifest/objects/Picklist_Value_Mapping__mdt.object
<CustomObject>
    <fields>
        <fullName>Value_Mapping__c</fullName>
        <label>Value Mapping</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Picklist Value Mapping</label>
    <pluralLabel>Picklist Value Mappings</pluralLabel>
</CustomObject>

manifest/globalValueSets/Account_Relationship_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Benefit Partner or Vendor</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Contractee</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Provider Only</fullName>
    </customValue>
    <customValue>
        <fullName>Payer and Eligibility Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Payer Only</fullName>
    </customValue>
    <customValue>
        <fullName>Referral Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Benefit Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Contractor</fullName>
        <isActive>false</isActive>
        <label>Contractor</label>
    </customValue>
    <customValue>
        <fullName>Benefit Partner</fullName>
        <isActive>false</isActive>
        <label>Benefit Partner</label>
    </customValue>
    <customValue>
        <fullName>Benefit Sponsor</fullName>
        <isActive>false</isActive>
        <label>Benefit Sponsor</label>
    </customValue>
    <masterLabel>Account Relationship Type</masterLabel>
</GlobalValueSet>

manifest/classes/OpportunityContactRoleHelper.cls
/***********************************************************************************************************
Class Name : OpportunityContactRoleHelper
Created by : Vineel Muppa
**************** Revision History*****************

* JIRA          CHANGED DATE    CHANGED BY         DESCRIPTION      
*---------------------------------------------------------------------------------
* SCDEV-4353    27-Dec-2023		Elambaruthi T		Setup Default Owner to Salesforce Support User
* SCDEV-4762    23-Jan-2024		Elambaruthi T		Account Relationship Mapping (Servicing Account Role)

***********************************************************************************************************/
public class OpportunityContactRoleHelper {
  public static void createAccouintRelationship(
    List<OpportunityContactRole> listOppConRoles
  ) {
    /* SCDEV-4353 [Starts] */
    String tdSFSupportUserId = GCRM_ProcessOrder_Utlity.getMuleSoftIntegrationDefaultOwner(
      UserInfo.getUserId()
    );
    /* SCDEV-4353 [Ends] */
    /* SCDEV-4762 [Starts] */
    Picklist_Value_Mapping__mdt pvMap = Picklist_Value_Mapping__mdt.getInstance(
      'Servicing_Account_Role_Mapping'
    );
    Map<String, String> relTypePicklistValueMap = (Map<String, String>) JSON.deserialize(
      pvMap.Value_Mapping__c,
      Map<String, String>.class
    );
    /* SCDEV-4762 [Ends] */

    Set<String> setConRoles = new Set<String>{
      'General Agency',
      'Broker',
      'Benefit Consultant'
    };
    Set<Id> setOppIds = new Set<Id>();
    Set<Id> setConIds = new Set<Id>();
    Set<Id> setAccIds = new Set<Id>();

    for (OpportunityContactRole recOCR : listOppConRoles) {
      if (setConRoles.contains(recOCR.Role)) {
        setOppIds.add(recOCR.OpportunityId);
        setConIds.add(recOCR.ContactId);
      }
    }
    Map<Id, Contact> mapCon = new Map<Id, Contact>(
      [SELECT Id, AccountId, Location__c FROM Contact WHERE id IN :setConIds]
    );
    Map<Id, Opportunity> mapOpp = new Map<Id, Opportunity>();
    for (Opportunity recOpp : [
      SELECT Id, AccountId, CloseDate
      FROM Opportunity
      WHERE id IN :setOppIds
    ]) {
      setAccIds.add(recOpp.AccountId);
      mapOpp.put(recOpp.id, recOpp);
    }
    Set<String> setAccRel = new Set<String>();
    for (Acct_Rel__c recAR : [
      SELECT
        Broker_Contact__c,
        Broker_Flat_Rate__c,
        Broker_Percentage__c,
        Chronic_Care_Broker_Flat_Rate__c,
        Chronic_Care_Broker_Percentage__c,
        Relationship_Type__c
      FROM Acct_Rel__c
      WHERE
        Benefit_Sponsor__c IN :setAccIds
        AND Broker_Contact__c IN :setConIds
        AND Relationship_Type__c IN :setConRoles
    ]) {
      setAccRel.add(
        recAR.Broker_Contact__c +
          '-' +
          recAR.Broker_Flat_Rate__c +
          '-' +
          recAR.Chronic_Care_Broker_Flat_Rate__c +
          '-' +
          recAR.Chronic_Care_Broker_Percentage__c +
          '-' +
          recAR.Relationship_Type__c
      );
    }
    List<Acct_Rel__c> listAccRelInsert = new List<Acct_Rel__c>();
    for (OpportunityContactRole recOCR : listOppConRoles) {
      /* SCDEV-4762 [Starts] */
      //String roleName=(recOCR.Role=='Broker' || recOCR.Role=='General Agency')?'Broker':'Benefit Partner or Vendor';
      String roleName = 'Benefit Partner or Vendor';
      if (relTypePicklistValueMap.containsKey(recOCR.Role)) {
        roleName = relTypePicklistValueMap.get(recOCR.Role);
      }
      /* SCDEV-4762 [Ends] */
      if (
        setConRoles.contains(recOCR.Role) &&
        setAccRel.add(
          recOCR.ContactId +
            '-' +
            recOCR.Broker_Flat_Rate__c +
            '-' +
            recOCR.Chronic_Care_Broker_Flat_Rate__c +
            '-' +
            recOCR.Chronic_Care_Broker_Percentage__c +
            '-' +
            roleName
        )
      ) {
        Acct_Rel__c objAR = new Acct_Rel__c();
        objAR.Benefit_Sponsor__c = mapOpp.get(recOCR.OpportunityId).AccountId;
        objAR.Start_Date__c = mapOpp.get(recOCR.OpportunityId).CloseDate;
        objAR.Broker_Contact__c = recOCR.ContactId;
        objAR.Broker_Flat_Rate__c = recOCR.Broker_Flat_Rate__c;
        objAR.Broker_Percentage__c = recOCR.Broker_Percentage__c;
        objAR.Chronic_Care_Broker_Flat_Rate__c = recOCR.Chronic_Care_Broker_Flat_Rate__c;
        objAR.Chronic_Care_Broker_Percentage__c = recOCR.Chronic_Care_Broker_Percentage__c;
        objAR.Relationship_Type__c = roleName;
        objAR.Broker_Location__c = mapCon.get(recOCR.ContactId).Location__c;
        objAR.Svc_Acct__c = mapCon.get(recOCR.ContactId).AccountId;
        /* SCDEV-4353 [Starts] */
        objAR.OwnerId = tdSFSupportUserId;
        /* SCDEV-4353 [Ends] */
        listAccRelInsert.add(objAR);
      }
    }
    if (listAccRelInsert != null && listAccRelInsert.size() > 0)
      insert listAccRelInsert;
  }
}