manifest/objects/Acct_Rel__c.object
<CustomObject>
    <description>Models the possible contracts between any two accounts regardless of hierarchy</description>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>Required on Contractee/Broker</description>
        <inlineHelpText>Required on Contractee/Broker</inlineHelpText>
        <label>Servicing Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Relationship_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Contract_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>Select the Line of Business</description>
        <inlineHelpText>Select the Line of Business</inlineHelpText>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Relationship_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Commercial_Fully_Insured_FI</fullName>
                    <label>Commercial Fully Insured (FI)</label>
                </value>
                <value>
                    <fullName>Commercial_Administrative_Services_Only_ASO</fullName>
                    <label>Commercial Administrative Services Only (ASO)</label>
                </value>
                <value>
                    <fullName>Marketplace_Exchange</fullName>
                    <label>Marketplace Exchange</label>
                </value>
                <value>
                    <fullName>Medicare-Medicaid Plan (MMP)</fullName>
                </value>
                <value>
                    <fullName>Dual Eligible Special Needs Plans (DSNP)</fullName>
                </value>
                <value>
                    <fullName>Medicaid_Managed_Care</fullName>
                    <label>Medicaid Managed Care</label>
                </value>
                <value>
                    <fullName>Medicaid Fee for Service (FFS)</fullName>
                </value>
                <value>
                    <fullName>Children’s Health Insurance Program (CHIP)</fullName>
                </value>
                <value>
                    <fullName>Temporary Assistance for Needy Families (TANF)</fullName>
                </value>
                <value>
                    <fullName>Medicare Supplement</fullName>
                </value>
                <value>
                    <fullName>Medicare Fee for Service (FFS)</fullName>
                </value>
                <value>
                    <fullName>Medicare Advantage with Part D (MAPD)</fullName>
                </value>
                <value>
                    <fullName>Medicare_Advantage_MA</fullName>
                    <label>Medicare Advantage (MA)</label>
                </value>
                <value>
                    <fullName>Critical Illness</fullName>
                </value>
                <value>
                    <fullName>Extended Health Care</fullName>
                </value>
                <value>
                    <fullName>Chambers of Commerce</fullName>
                </value>
                <value>
                    <fullName>Maximum Benefit</fullName>
                </value>
                <value>
                    <fullName>CINUP</fullName>
                </value>
                <value>
                    <fullName>Health Plan Commercial Solutions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <description>Select the type of Relationship for the Servicing Account.</description>
        <inlineHelpText>Select the type of Relationship for the Servicing Account.</inlineHelpText>
        <label>Servicing Account Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Account_Relationship_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>REL-{00000000}</displayFormat>
        <label>Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Business_Region__c</fullName>
        <formula>Text(Account.Business_Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Region</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

manifest/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Business_Region__c</fullName>
        <formula>TEXT(SBQQ__Opportunity__r.Business_Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CPQ_Pricebook__c</fullName>
        <formula>SBQQ__Opportunity__r.CPQ_Pricebook__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CPQ Pricebook</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Carrier__c</fullName>
        <formula>SBQQ__Opportunity__r.Carrier__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Carrier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <formula>SBQQ__Opportunity__r.Line_of_Business__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Line of Business</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Model__c</fullName>
        <formula>SBQQ__Opportunity__r.Pricing_Model__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pricing Model</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Channels__c</fullName>
        <formula>SBQQ__Opportunity__r.Sales_Channels__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Channels</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>SBQQ__AmendedContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the relationship to your Amended Contract.</description>
        <inlineHelpText>Lookup to your Amended Contract.</inlineHelpText>
        <label>Amended Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Amendment Opportunities</relationshipLabel>
        <relationshipName>AmendmentOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

manifest/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this Opportunity Product.</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>OpportunityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

manifest/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Business_Region__c</fullName>
        <label>Business Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CPQ_Pricebook__c</fullName>
        <label>CPQ Pricebook</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sales_Channels__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>CPQ_Pricebooks</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Carrier__c</fullName>
        <description>Added new Picklist values</description>
        <label>Carrier</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CPQ_Pricebook__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Carrier</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Include_in_Octiv_Proposal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used by Octiv to determine if a fee page should be produced/included for this Quote based upon the Proposal Template selected on the Opportunity.</description>
        <inlineHelpText>This field is used by Octiv to determine if a fee page should be produced/included for this Quote based upon the Proposal Template selected on the Opportunity.</inlineHelpText>
        <label>Include in Octiv Proposal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <inlineHelpText>ASO is for Opt In</inlineHelpText>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Carrier__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Line_of_Business</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pricing_Model__c</fullName>
        <label>Pricing Model</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CPQ_Pricebook__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASO Pricing</fullName>
                </value>
                <value>
                    <fullName>Shared Savings 80-20</fullName>
                </value>
                <value>
                    <fullName>Shared Savings 60-40</fullName>
                </value>
                <value>
                    <fullName>Shared Risk</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
                <value>
                    <fullName>Contracted Pricing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Channels__c</fullName>
        <label>Sales Channels</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sales_Channels</valueSetName>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>Provider</fullName>
        <active>true</active>
        <description>This record type belongs to the Provider group selling Provider pricebook products.</description>
        <label>Provider</label>
    </recordTypes>
    <recordTypes>
        <fullName>Teladoc</fullName>
        <active>true</active>
        <label>Teladoc</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>CPQ_Pricebook__c</fullName>
        <formula>TEXT(SBQQ__Quote__r.CPQ_Pricebook__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CPQ Pricebook</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Carrier__c</fullName>
        <formula>TEXT(SBQQ__Quote__r.Carrier__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Carrier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consult_Type__c</fullName>
        <label>Consult Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Consult_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fee_Type__c</fullName>
        <description>Captures the FeeType at the Product level</description>
        <label>Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Fee_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/globalValueSets/Account_Relationship_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Benefit Partner or Vendor</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Contractee</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Provider Only</fullName>
    </customValue>
    <customValue>
        <fullName>Payer and Eligibility Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Payer Only</fullName>
    </customValue>
    <customValue>
        <fullName>Referral Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Benefit Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Contractor</fullName>
        <isActive>false</isActive>
        <label>Contractor</label>
    </customValue>
    <customValue>
        <fullName>Benefit Partner</fullName>
        <isActive>false</isActive>
        <label>Benefit Partner</label>
    </customValue>
    <customValue>
        <fullName>Benefit Sponsor</fullName>
        <isActive>false</isActive>
        <label>Benefit Sponsor</label>
    </customValue>
    <masterLabel>Account Relationship Type</masterLabel>
</GlobalValueSet>

manifest/globalValueSets/Business_Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>USA</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Europe</fullName>
    </customValue>
    <customValue>
        <fullName>Asia-ME</fullName>
    </customValue>
    <customValue>
        <fullName>Aus-NZ</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <description>Global region - where the contract will reside</description>
    <masterLabel>Business Region</masterLabel>
</GlobalValueSet>

manifest/globalValueSets/Carrier.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accolade</fullName>
    </customValue>
    <customValue>
        <fullName>Aetna</fullName>
    </customValue>
    <customValue>
        <fullName>Alliant</fullName>
    </customValue>
    <customValue>
        <fullName>AmeriHealth</fullName>
    </customValue>
    <customValue>
        <fullName>Anthem</fullName>
    </customValue>
    <customValue>
        <fullName>Aultcare</fullName>
    </customValue>
    <customValue>
        <fullName>BCBS AL</fullName>
    </customValue>
    <customValue>
        <fullName>BCBS KC</fullName>
    </customValue>
    <customValue>
        <fullName>BCBS Massachusetts</fullName>
    </customValue>
    <customValue>
        <fullName>BCBS Michigan</fullName>
    </customValue>
    <customValue>
        <fullName>BCBS NC</fullName>
    </customValue>
    <customValue>
        <fullName>BCBS RI</fullName>
    </customValue>
    <customValue>
        <fullName>BCBS SC</fullName>
    </customValue>
    <customValue>
        <fullName>BCBS SC - Planned Administrators</fullName>
    </customValue>
    <customValue>
        <fullName>BCBS SC - TCC Benefits</fullName>
    </customValue>
    <customValue>
        <fullName>BCBS TN</fullName>
    </customValue>
    <customValue>
        <fullName>BCS Financial</fullName>
    </customValue>
    <customValue>
        <fullName>Blue Cross of Idaho</fullName>
    </customValue>
    <customValue>
        <fullName>Blue Shield of California</fullName>
    </customValue>
    <customValue>
        <fullName>Cambia Health / Regence</fullName>
    </customValue>
    <customValue>
        <fullName>Capital BlueCross</fullName>
    </customValue>
    <customValue>
        <fullName>Caremark PSM (Point Solution Mgmt)</fullName>
    </customValue>
    <customValue>
        <fullName>Caremark TC (Transform Care)</fullName>
    </customValue>
    <customValue>
        <fullName>CareMoat Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>Castlight</fullName>
    </customValue>
    <customValue>
        <fullName>Centene</fullName>
    </customValue>
    <customValue>
        <fullName>Cerner</fullName>
    </customValue>
    <customValue>
        <fullName>Cigna</fullName>
    </customValue>
    <customValue>
        <fullName>Cobalt Benefits Group</fullName>
    </customValue>
    <customValue>
        <fullName>Coresource</fullName>
    </customValue>
    <customValue>
        <fullName>UMR</fullName>
    </customValue>
    <description>Added new Picklist values</description>
    <masterLabel>Carrier</masterLabel>
</GlobalValueSet>

manifest/globalValueSets/Consult_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Included</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 1 - Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 1 - Included</fullName>
    </customValue>
    <customValue>
        <fullName>MFN - Standard</fullName>
    </customValue>
    <customValue>
        <fullName>MFN - Included</fullName>
    </customValue>
    <customValue>
        <fullName>Mercer WTW - Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Mercer/WTW - Included</fullName>
    </customValue>
    <customValue>
        <fullName>Custom</fullName>
    </customValue>
    <masterLabel>Consult_Types</masterLabel>
</GlobalValueSet>

manifest/globalValueSets/Contract_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Health Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Platform</fullName>
    </customValue>
    <masterLabel>Contract Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

manifest/globalValueSets/CPQ_Pricebooks.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Carrier</fullName>
    </customValue>
    <customValue>
        <fullName>Canada Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Canada Insurance (New)</fullName>
    </customValue>
    <customValue>
        <fullName>Canada Insurance (Exist)</fullName>
    </customValue>
    <customValue>
        <fullName>HealthPlan</fullName>
    </customValue>
    <customValue>
        <fullName>Complex Case Mgmt</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>HHS</fullName>
    </customValue>
    <customValue>
        <fullName>Cross-Sell</fullName>
        <isActive>false</isActive>
        <label>Cross-Sell</label>
    </customValue>
    <masterLabel>CPQ Pricebooks</masterLabel>
</GlobalValueSet>

manifest/globalValueSets/Fee_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PEPM</fullName>
    </customValue>
    <customValue>
        <fullName>PMPM</fullName>
    </customValue>
    <customValue>
        <fullName>PPPM</fullName>
    </customValue>
    <customValue>
        <fullName>Flat Rate</fullName>
    </customValue>
    <customValue>
        <fullName>Case Rate</fullName>
    </customValue>
    <masterLabel>Fee type</masterLabel>
</GlobalValueSet>

manifest/globalValueSets/Line_of_Business.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ASO</fullName>
    </customValue>
    <customValue>
        <fullName>ASO – 100% AND $0 Copay</fullName>
    </customValue>
    <customValue>
        <fullName>ASO – 100% or $0 Copay</fullName>
    </customValue>
    <customValue>
        <fullName>ASO - Baseline</fullName>
    </customValue>
    <customValue>
        <fullName>ASO - Custom</fullName>
    </customValue>
    <customValue>
        <fullName>ASO - Digital Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>ASO - Full Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>ASO - Opt In</fullName>
    </customValue>
    <customValue>
        <fullName>ASO - Opt Out</fullName>
    </customValue>
    <customValue>
        <fullName>ASO - Standard Communications</fullName>
    </customValue>
    <customValue>
        <fullName>Exchange</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Insured</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Insured and Medicare Advantage</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Health Connect 360</fullName>
    </customValue>
    <customValue>
        <fullName>HTN Bundle</fullName>
    </customValue>
    <customValue>
        <fullName>Marketplace/Commercial</fullName>
    </customValue>
    <customValue>
        <fullName>Medicaid</fullName>
    </customValue>
    <customValue>
        <fullName>Medicare</fullName>
    </customValue>
    <customValue>
        <fullName>Medicare Advantage</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-Year</fullName>
    </customValue>
    <customValue>
        <fullName>NY ASO</fullName>
    </customValue>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Standard w/ Coaching</fullName>
    </customValue>
    <customValue>
        <fullName>Standard w/ Upfront Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 1</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 2</fullName>
    </customValue>
    <masterLabel>Line of Business</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

manifest/globalValueSets/Sales_Channels.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>US Employer</fullName>
    </customValue>
    <customValue>
        <fullName>US HealthPlan</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital and Health Systems</fullName>
    </customValue>
    <masterLabel>Sales Channels</masterLabel>
</GlobalValueSet>

manifest/classes/OpportunityTriggerHelperTest.cls
/*https://teladochealth--preprod2.my.salesforce.com/_ui/common/apex/debug/ApexCSIPage#
 * Created by amruthakommuri on 2019-02-12.
 **/

@isTest
private class OpportunityTriggerHelperTest {
  //Defined test dataset
  @testSetup
  static void setupdata() {
    Test.startTest();
    SBQQ.TriggerControl.disable();
    Account umrAcct = TestDataFactory.createUMR();

    //create an account record
    Account accObj = TestDataFactory.createAccountUMR();

    //Create Account Relationships
    List<Acct_Rel__c> accRelList = new List<Acct_Rel__c>();

    Acct_Rel__c acctRel1 = TestDataFactory.createAccRel(accObj.Id);
    acctRel1.Relationship_Type__c = 'Payer and Eligibility Provider';
    acctRel1.Contract_Type__c = null;
    accRelList.add(acctRel1);

    Acct_Rel__c acctRel2 = TestDataFactory.createAccRel(accObj.Id);
    acctRel2.Relationship_Type__c = 'Eligibility Provider Only';
    acctRel2.Contract_Type__c = null;
    accRelList.add(acctRel2);
    insert accRelList;

    //create an opportunity record
    Opportunity oppObj2 = TestDataFactory.createOpportunity(accObj.Id);
    insert oppObj2;

    List<SBQQ__Quote__c> quoList = new List<SBQQ__Quote__c>();

    //Create 2 quote records
    SBQQ__Quote__c quoObj1 = TestDataFactory.createQuote(oppObj2.Id);
    quoObj1.SBQQ__Primary__c = true;
    quoList.add(quoObj1);

    SBQQ__Quote__c quoObj2 = TestDataFactory.createQuote(oppObj2.Id);
    quoObj2.SBQQ__Primary__c = false;
    quoList.add(quoObj2);
    insert quolist;

    list<Product2> prodlist = new List<Product2>();

    //create BD US core bundle product
    Product2 prod1 = TestDataFactory.createSingleProduct(
      'EMS 2.0 Bundle',
      'Expert Medical Services',
      'BD-USEMP-BUNDLE-2.0'
    );
    prodlist.add(Prod1);

    //create TD Standard Bundle product
    Product2 prod2 = TestDataFactory.createSingleProduct(
      'TD Bundle - Standard',
      'Teladoc',
      'TD-STD'
    );
    prodlist.add(Prod2);

    //create Gen Med product
    Product2 prod3 = TestDataFactory.createSingleProduct(
      'General Medical',
      'General Medical',
      'GM'
    );
    prodlist.add(Prod3);

    //create TD-Included Bundle
    Product2 prod4 = TestDataFactory.createSingleProduct(
      'TD Bundle - Included - less than 1000',
      'Teladoc',
      'TD-INCL-L1000'
    );
    prodlist.add(Prod4);

    Product2 prod5 = TestDataFactory.createSingleProduct(
      'HealthiestYou',
      'General Medical',
      'HY'
    );
    prodlist.add(Prod5);

    Product2 prod6 = TestDataFactory.createSingleProduct(
      'HY - Consult Fee',
      'General Medical',
      'HYCF'
    );
    prodlist.add(Prod6);

    insert Prodlist;

    //create a contract record 2
    Contract conObj2 = TestDataFactory.createContractNoInsert(
      accObj.Id,
      oppObj2.id,
      null
    );
    conObj2.Status = 'Draft';
    conObj2.CurrencyIsoCode = 'USD';
    conObj2.StartDate = Date.Today();
    conObj2.ContractTerm = 12;
    insert conObj2;
    SBQQ.TriggerControl.enable();
    Test.StopTest();
  }

  //Test Case for 'Telehealth Services - Both TD Standard & TD Included' proposal template
  @isTest
  static void combiledTDTemplateValid() {
    List<Opportunity> opplist = [SELECT id FROM Opportunity];
    List<Contract> clist = [SELECT id FROM contract];
    List<Account> acclist = [SELECT id FROM Account];
    List<SBQQ__Quote__c> quolist = [SELECT id FROM SBQQ__Quote__c];
    list<Product2> prodlist = [SELECT id FROM Product2];
    test.startTest();
    SBQQ.TriggerControl.disable();
    //Create quote lines for the primary quote
    SBQQ__QuoteLine__c quoline1 = new SBQQ__QuoteLine__c();
    quoline1.RecordTypeId = Schema.SObjectType.SBQQ__QuoteLine__c.getRecordTypeInfosByName()
      .get('Standard')
      .getRecordTypeId();
    quoline1.SBQQ__Quote__c = quolist[0].Id;
    quoline1.SBQQ__Product__c = prodlist[1].Id;
    quoline1.CurrencyIsoCode = 'USD';
    quoline1.Consult_Type__c = 'Standard';
    insert quoline1;
    SBQQ__QuoteLine__c quoline2 = new SBQQ__QuoteLine__c();
    quoline2.RecordTypeId = Schema.SObjectType.SBQQ__QuoteLine__c.getRecordTypeInfosByName()
      .get('Standard')
      .getRecordTypeId();
    quoline2.SBQQ__Quote__c = quolist[0].Id;
    quoline2.SBQQ__Product__c = prodlist[2].Id;
    quoline2.CurrencyIsoCode = 'USD';
    quoline2.Consult_Type__c = 'Standard';
    insert quoline2;

    //Create quote lines for the primary quote
    SBQQ__QuoteLine__c quoline3 = new SBQQ__QuoteLine__c();
    quoline3.RecordTypeId = Schema.SObjectType.SBQQ__QuoteLine__c.getRecordTypeInfosByName()
      .get('Standard')
      .getRecordTypeId();
    quoline3.SBQQ__Quote__c = quolist[0].Id;
    quoline3.SBQQ__Product__c = prodlist[3].Id;
    quoline3.CurrencyIsoCode = 'USD';
    quoline3.Consult_Type__c = 'Included';
    insert quoline3;
    SBQQ__QuoteLine__c quoline4 = new SBQQ__QuoteLine__c();
    quoline4.RecordTypeId = Schema.SObjectType.SBQQ__QuoteLine__c.getRecordTypeInfosByName()
      .get('Standard')
      .getRecordTypeId();
    quoline4.SBQQ__Quote__c = quolist[1].Id;
    quoline4.SBQQ__Product__c = prodlist[2].Id;
    quoline4.CurrencyIsoCode = 'USD';
    quoline4.Consult_Type__c = 'Included';
    insert quoline4;

    opplist[0]
      .Proposal_Template__c = 'Telehealth Services - Both TD Standard & TD Included';
    update opplist[0];
    system.assertEquals(
      'Telehealth Services - Both TD Standard & TD Included',
      opplist[0].Proposal_Template__c
    );
    SBQQ.TriggerControl.enable();
    test.stopTest();
  }

  //Test Case for 'HY Core Bundle Standard' proposal template
  @isTest
  static void HYCoreStandardTemplateValid() {
    List<Opportunity> opplist = [SELECT id FROM Opportunity];
    List<Contract> clist = [SELECT id FROM contract];
    List<Account> acclist = [SELECT id FROM Account];
    List<SBQQ__Quote__c> quolist = [SELECT id FROM SBQQ__Quote__c];
    list<Product2> prodlist = [SELECT id FROM Product2];
    Test.startTest();
    SBQQ.TriggerControl.disable();
    //Create quote lines for the primary quote
    SBQQ__QuoteLine__c quoline3 = new SBQQ__QuoteLine__c();
    quoline3.RecordTypeId = Schema.SObjectType.SBQQ__QuoteLine__c.getRecordTypeInfosByName()
      .get('Standard')
      .getRecordTypeId();
    quoline3.SBQQ__Quote__c = quolist[0].Id;
    quoline3.SBQQ__Product__c = prodlist[4].Id;
    quoline3.CurrencyIsoCode = 'USD';
    quoline3.Consult_Type__c = 'Standard';
    insert quoline3;
    SBQQ__QuoteLine__c quoline1 = new SBQQ__QuoteLine__c();
    quoline1.RecordTypeId = Schema.SObjectType.SBQQ__QuoteLine__c.getRecordTypeInfosByName()
      .get('Standard')
      .getRecordTypeId();
    quoline1.SBQQ__Quote__c = quolist[0].Id;
    quoline1.SBQQ__Product__c = prodlist[5].Id;
    quoline1.CurrencyIsoCode = 'USD';
    quoline1.Consult_Type__c = 'Standard';
    insert quoline1;

    opplist[0].Proposal_Template__c = 'HY Core Bundle Standard';
    update opplist[0];
    system.assertEquals(
      'HY Core Bundle Standard',
      opplist[0].Proposal_Template__c
    );
    SBQQ.TriggerControl.enable();
    Test.Stoptest();
  }

  @isTest
  static void DynamicTemplateValid() {
    List<Opportunity> opplist = [SELECT id FROM Opportunity];
    List<Contract> clist = [SELECT id FROM contract];
    List<Account> acclist = [SELECT id FROM Account];
    List<SBQQ__Quote__c> quolist = [SELECT id FROM SBQQ__Quote__c];
    list<Product2> prodlist = [SELECT id FROM Product2];
    Test.StartTest();
    //Create quote lines for the primary quote
    SBQQ__QuoteLine__c quoline3 = new SBQQ__QuoteLine__c();
    quoline3.RecordTypeId = Schema.SObjectType.SBQQ__QuoteLine__c.getRecordTypeInfosByName()
      .get('Standard')
      .getRecordTypeId();
    quoline3.SBQQ__Quote__c = quolist[0].Id;
    quoline3.SBQQ__Product__c = prodlist[1].Id;
    quoline3.CurrencyIsoCode = 'USD';
    quoline3.Consult_Type__c = 'Standard';
    insert quoline3;

    opplist[0].Proposal_Template__c = 'Dynamic Proposal on Primary Quote';
    update opplist[0];
    system.assertEquals(
      'Dynamic Proposal on Primary Quote',
      opplist[0].Proposal_Template__c
    );
    Test.stopTest();
  }

  //Test Case for 'HY Core Bundle Included' proposal template
  @isTest
  static void HYCoreIncludedTemplateValid() {
    List<Opportunity> opplist = [SELECT id FROM Opportunity];
    List<Contract> clist = [SELECT id FROM contract];
    List<Account> acclist = [SELECT id FROM Account];
    List<SBQQ__Quote__c> quolist = [SELECT id FROM SBQQ__Quote__c];
    list<Product2> prodlist = [SELECT id, Name FROM Product2];
    Test.startTest();
    SBQQ.TriggerControl.disable();
    //Create quote lines for the primary quote
    SBQQ__QuoteLine__c quoline3 = new SBQQ__QuoteLine__c();
    quoline3.RecordTypeId = Schema.SObjectType.SBQQ__QuoteLine__c.getRecordTypeInfosByName()
      .get('Standard')
      .getRecordTypeId();
    quoline3.SBQQ__Quote__c = quolist[0].Id;
    quoline3.SBQQ__Product__c = prodlist[4].Id;
    quoline3.CurrencyIsoCode = 'USD';
    quoline3.Consult_Type__c = 'Included';
    insert quoline3;
    SBQQ__QuoteLine__c quoline1 = new SBQQ__QuoteLine__c();
    quoline1.RecordTypeId = Schema.SObjectType.SBQQ__QuoteLine__c.getRecordTypeInfosByName()
      .get('Standard')
      .getRecordTypeId();
    quoline1.SBQQ__Quote__c = quolist[0].Id;
    quoline1.SBQQ__Product__c = prodlist[5].Id;
    quoline1.CurrencyIsoCode = 'USD';
    quoline1.Consult_Type__c = 'Standard';
    insert quoline1;
    system.debug(prodlist[5].Name);
    system.debug(prodlist[4].Name);
    opplist[0].Proposal_Template__c = 'HY Core Bundle Included';

    update opplist[0];
    system.assertEquals(
      'HY Core Bundle Included',
      opplist[0].Proposal_Template__c
    );
    SBQQ.TriggerControl.enable();
    Test.StopTest();
  }

  @isTest
  static void validationPrimaryCarrier() {
    test.startTest();
    SBQQ.TriggerControl.disable();
    List<Contract> clist = [SELECT id FROM contract];
    Account accObj = [SELECT Id FROM Account WHERE Name != 'UMR'];
    Opportunity opp = new Opportunity();
    opp.Name = 'test 1';
    opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName()
      .get('Employer – Teladoc and HY Products')
      .getRecordTypeId();
    opp.AccountId = accObj.Id;
    opp.Type = 'New Business';
    opp.Business_Region__c = 'USA';
    opp.CurrencyIsoCode = 'USD';
    opp.StageName = 'Prospect';
    opp.Probability = 10;
    opp.Initial_of_Lives__c = 500;
    opp.Fee_Type__c = 'PEPM';
    opp.LeadSource = 'Sales';
    opp.CloseDate = Date.Today();
    opp.LeadSource = 'Sales';
    opp.SBQQ__AmendedContract__c = clist[0].Id;
    insert opp;

    SBQQ__Quote__c quo = new SBQQ__Quote__c();
    quo.RecordTypeId = Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByName()
      .get('Teladoc')
      .getRecordTypeId();
    quo.SBQQ__Opportunity2__c = opp.Id;
    quo.SBQQ__Primary__c = true;
    quo.Sales_Channels__c = 'US HealthPlan';
    quo.Carrier__c = 'Aetna';
    quo.Line_of_Business__c = 'ASO';
    quo.Pricing_Model__c = 'Contracted Pricing';
    quo.CPQ_Pricebook__c = 'Carrier';
    quo.Include_in_Octiv_Proposal__c = false;
    insert quo;

    try {
      OpportunityTriggerHelper.updateQuoteRecordType(
        new List<SBQQ__Quote__c>{ quo }
      );
      OpportunityTriggerHelper.getOppQuoteMap(new List<Opportunity>{ opp });
      OpportunityTriggerHelper.getTDStandardCountMap(
        new List<Opportunity>{ opp }
      );
      OpportunityTriggerHelper.getTDIncludedCountMap(
        new List<Opportunity>{ opp }
      );
      OpportunityTriggerHelper.getBDStandardCountMap(
        new List<Opportunity>{ opp }
      );
      OpportunityTriggerHelper.getEMS2StandardCountMap(
        new List<Opportunity>{ opp }
      );
      OpportunityTriggerHelper.getEMS2IncludedCountMap(
        new List<Opportunity>{ opp }
      );
      OpportunityTriggerHelper.getHYStandardCountMap(
        new List<Opportunity>{ opp }
      );
      OpportunityTriggerHelper.getHYIncludedCountMap(
        new List<Opportunity>{ opp }
      );
      OpportunityTriggerHelper.getBHCustomCountMap(
        new List<Opportunity>{ opp }
      );
      OpportunityTriggerHelper.getBackCareCountMap(
        new List<Opportunity>{ opp }
      );
      opp.StageName = 'Contracting';
      update opp;
    } catch (Exception e) {
      //Below values will be deprecated later for Contract Path LOB functionality
      //Boolean expectedExceptionThrown =  e.getMessage().contains('The Contract Path field is required for any health plan related opportunities.') ? true : false;
      //System.AssertEquals(expectedExceptionThrown, true);
    }
    SBQQ.TriggerControl.enable();
    test.stopTest();
  }

  @isTest
  static void testaccRelCreation() {
    List<Contract> clist = [SELECT id FROM contract];
    Account accObj = [SELECT Id FROM Account WHERE Name != 'UMR'];
    Id pricebookId = Test.getStandardPricebookId();

    //Create your product
    Product2 prod = new Product2(
      Name = 'Product X',
      ProductCode = 'Pro-X',
      isActive = true
    );
    insert prod;

    //Create your pricebook entry
    PricebookEntry pbEntry = new PricebookEntry(
      Pricebook2Id = pricebookId,
      Product2Id = prod.Id,
      UnitPrice = 100.00,
      IsActive = true
    );
    insert pbEntry;

    Opportunity opp = new Opportunity();
    opp.Name = 'test 1';
    opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName()
      .get('Employer – Teladoc and HY Products')
      .getRecordTypeId();
    opp.AccountId = accObj.Id;
    opp.Type = 'New Business';
    opp.Business_Region__c = 'USA';
    opp.CurrencyIsoCode = 'USD';
    opp.StageName = 'Prospect';
    opp.Probability = 10;
    opp.Initial_of_Lives__c = 500;
    opp.Fee_Type__c = 'PEPM';
    opp.LeadSource = 'Sales';
    opp.CloseDate = Date.Today();
    opp.LeadSource = 'Sales';
    opp.SBQQ__AmendedContract__c = clist[0].Id;
    opp.pricebook2Id = pricebookId;
    insert opp;
    /*
        List<SBQQ__Quote__c> quolist =[Select id from SBQQ__Quote__c];
        list<Product2> prodlist =[select id, Name from Product2];
        
        //Create quote lines for the primary quote
        SBQQ__QuoteLine__c quoline3 = new SBQQ__QuoteLine__c();
        quoline3.RecordTypeId = Schema.SObjectType.SBQQ__QuoteLine__c.getRecordTypeInfosByName().get('Standard').getRecordTypeId();
        quoline3.SBQQ__Quote__c = quolist[0].Id;
        quoline3.SBQQ__Product__c = prodlist[4].Id;
        quoline3.CurrencyIsoCode ='USD';
        quoline3.Consult_Type__c = 'Included';
        insert quoline3;*/

    //create your opportunity line item.  This assumes you already have an opportunity created, called opp
    OpportunityLineItem oli = new OpportunityLineItem(
      OpportunityId = opp.Id,
      Quantity = 5,
      PricebookEntryId = pbEntry.Id,
      TotalPrice = 100
    );
    insert oli;
    test.startTest();
    SBQQ.TriggerControl.disable();
    SBQQ__Quote__c quo = new SBQQ__Quote__c();
    quo.RecordTypeId = Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByName()
      .get('Teladoc')
      .getRecordTypeId();
    quo.SBQQ__Opportunity2__c = opp.Id;
    quo.SBQQ__Primary__c = true;
    quo.Sales_Channels__c = 'US Employer';
    //quo.Carrier__c ='Direct';
    //quo.Line_of_Business__c = 'ASO';
    //quo.Pricing_Model__c ='Contracted Pricing';
    //quo.CPQ_Pricebook__c = 'Carrier';
    //quo.Include_in_Octiv_Proposal__c = false;
    insert quo;

    opp.Benefit_Consultant_Involved_in_Deal__c = 'No';
    opp.Contract_Path__c = accObj.Id;
    opp.StageName = 'Contracting';
    update opp;
    SBQQ.TriggerControl.enable();
    Test.stopTest();
  }

  /**
   * @description Test method for createStageMetricObjRec
   * Test method to create the Stage Metric records for Opportunity Stage Change
   */
  @isTest
  static void createStageMetricObjRec_positive() {
    Opportunity oppRecord = [
      SELECT Id, AccountId, Sub_Channel__c, StageName
      FROM Opportunity
      LIMIT 1
    ];

    Test.startTest();
    oppRecord.StageName = 'Discovery';
    oppRecord.Benefit_Consultant_Involved_in_Deal__c = 'No';
    oppRecord.Contract_Path__c = oppRecord.AccountId;
    update oppRecord;
    Test.stopTest();

    List<L2O_Stage_Metric__c> stageMetricsList = [
      SELECT Id, Name
      FROM L2O_Stage_Metric__c
      WHERE L2O_Opportunity__c = :oppRecord.Id
    ];
    //Two Stage Metrics gets created one up on Opp creation and second upon Stage Change
    System.assertEquals(stageMetricsList.Size(), 2);
  }
}