manifest/objects/Acct_Rel__c.object
<CustomObject>
    <description>Models the possible contracts between any two accounts regardless of hierarchy</description>
    <fields>
        <fullName>Benefit_Sponsor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account receiving services</description>
        <inlineHelpText>Lookup the Benefit Sponsor Account (Account receiving services) of the Relationship</inlineHelpText>
        <label>Benefit Sponsor Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Servicing Accounts</relationshipLabel>
        <relationshipName>servicingaccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <description>Select the type of Relationship for the Servicing Account.</description>
        <inlineHelpText>Select the type of Relationship for the Servicing Account.</inlineHelpText>
        <label>Servicing Account Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Account_Relationship_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date contract starts</description>
        <inlineHelpText>Enter the Date Relationship Started</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Svc_Acct__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account providing the service</description>
        <inlineHelpText>Lookup the Servicing Account of the Relationship</inlineHelpText>
        <label>Servicing Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Benefit Sponsor Accounts</relationshipLabel>
        <relationshipName>benefitsponsors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>REL-{00000000}</displayFormat>
        <label>Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

manifest/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>CPQ_Pricebook__c</fullName>
        <formula>SBQQ__Opportunity__r.CPQ_Pricebook__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CPQ Pricebook</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>RFP_Count__c</fullName>
        <description>This field is updated by the Dynamic Rollup summary package.. This should be Read only field for all profiles except admins</description>
        <label>RFP Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RFP_Finalist__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will replace the RFP finalist picklist field in Teladoc Prod.</description>
        <inlineHelpText>Is this Opportunity an RFP finalist?</inlineHelpText>
        <label>RFP Finalist</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Contracted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Internal flag used to kick off automatic asset and subscription conversion.</description>
        <inlineHelpText>Salesforce CPQ uses this field to automatically convert assets and subscriptions.</inlineHelpText>
        <label>Contracted</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Benefit_Consultant_Involved_in_Deal__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Consultant_Involved_in_Deal__c</fullName>
    <label>Benefit Consultant Involved in Deal?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <label>No Involvement</label>
            </value>
            <value>
                <fullName>Consultant introduced us, but was not involved in selling</fullName>
                <label>Yes - Consultant introduced us, but was not involved in selling</label>
            </value>
            <value>
                <fullName>Consultant introduced us, and was involved in selling</fullName>
                <label>Yes - Consultant introduced us, and was involved in selling</label>
            </value>
            <value>
                <fullName>Consultant did not introduce us, but was involved in selling</fullName>
                <label>Yes - Consultant did not introduce us, but was involved in selling</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Contract_Path__c.field-meta.xml
<CustomField>
    <fullName>Contract_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Direct contracts, please select &quot;Livongo&quot;. Indicates the Contract Path for the Opportunity, and required for Opps to be closed won. Once an Opp is won, the Contract Path will be represented as a relationship associated to the Client Overview.</description>
    <inlineHelpText>Direct contracts, please select &quot;Livongo&quot;. Indicates the Contract Path for the Opportunity, and required for Opps to be closed won. Once an Opp is won, the Contract Path will be represented as a relationship associated to the Client Overview.</inlineHelpText>
    <label>Contract Path</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contract Path must be a Partner Account.</errorMessage>
        <filterItems>
            <field>$Source.Source__c</field>
            <operation>equals</operation>
            <value>TD</value>
        </filterItems>
        <infoMessage>Contract Path must be a Partner Account.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Opportunities (Contract Path)</relationshipLabel>
    <relationshipName>LVGO_Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

manifest/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this Opportunity Product.</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>OpportunityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

manifest/objects/Order.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Contracted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the order is contracted.</description>
        <inlineHelpText>Indicates if the order is contracted.</inlineHelpText>
        <label>Contracted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Quotas__c.object
<CustomObject>
    <fields>
        <fullName>ARR_Quotas_Amount__c</fullName>
        <label>ARR Quotas Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Total_ARR__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Sub total for all Est. Annual Recurring Revenue (ARR)</description>
        <label>Current Total ARR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Total_IYR__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Current Sub total for Est. In Year Revenue (IYR)</description>
        <label>Current Total IYR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ending_Date__c</fullName>
        <label>Ending Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IYR_Quotas_Amount__c</fullName>
        <label>IYR Quotas Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quotas_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quotas Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Starting_Date__c</fullName>
        <label>Starting Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Quotas</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quota Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/RFP__c.object
<CustomObject>
    <description>Request For Proposals</description>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>Specified Due Date in the RFP</description>
        <inlineHelpText>Specified Due Date in the RFP</inlineHelpText>
        <label>Due Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent Opportunity of the RFP</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>RFPs</relationshipLabel>
        <relationshipName>RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_plan__c</fullName>
        <inlineHelpText>Created in Spark</inlineHelpText>
        <label>Opportunity plan?</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Relationship_map__c</fullName>
        <inlineHelpText>Created in Spark</inlineHelpText>
        <label>Relationship map?</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Release_Date__c</fullName>
        <description>Date the RFP was released by customer</description>
        <inlineHelpText>Date the RFP was released by customer</inlineHelpText>
        <label>Release Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>RFP</label>
    <nameField>
        <label>Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFPs</pluralLabel>
    <recordTypes>
        <fullName>Edit</fullName>
        <active>true</active>
        <label>Edit</label>
    </recordTypes>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <description>The record is created</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>CPQ_Pricebook__c</fullName>
        <label>CPQ Pricebook</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sales_Channels__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>CPQ_Pricebooks</valueSetName>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>CPQ_Pricebook__c</fullName>
        <formula>TEXT(SBQQ__Quote__r.CPQ_Pricebook__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CPQ Pricebook</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/globalValueSets/Account_Relationship_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Benefit Partner or Vendor</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Contractee</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Provider Only</fullName>
    </customValue>
    <customValue>
        <fullName>Payer and Eligibility Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Payer Only</fullName>
    </customValue>
    <customValue>
        <fullName>Referral Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Benefit Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Contractor</fullName>
        <isActive>false</isActive>
        <label>Contractor</label>
    </customValue>
    <customValue>
        <fullName>Benefit Partner</fullName>
        <isActive>false</isActive>
        <label>Benefit Partner</label>
    </customValue>
    <customValue>
        <fullName>Benefit Sponsor</fullName>
        <isActive>false</isActive>
        <label>Benefit Sponsor</label>
    </customValue>
    <masterLabel>Account Relationship Type</masterLabel>
</GlobalValueSet>

manifest/globalValueSets/CPQ_Pricebooks.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Carrier</fullName>
    </customValue>
    <customValue>
        <fullName>Canada Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Canada Insurance (New)</fullName>
    </customValue>
    <customValue>
        <fullName>Canada Insurance (Exist)</fullName>
    </customValue>
    <customValue>
        <fullName>HealthPlan</fullName>
    </customValue>
    <customValue>
        <fullName>Complex Case Mgmt</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>HHS</fullName>
    </customValue>
    <customValue>
        <fullName>Cross-Sell</fullName>
        <isActive>false</isActive>
        <label>Cross-Sell</label>
    </customValue>
    <masterLabel>CPQ Pricebooks</masterLabel>
</GlobalValueSet>

manifest/classes/OpportunityValidatorTest.cls
/**
 * Created by amruthakommuri on 2019-06-17.
 */

@isTest
public with sharing class OpportunityValidatorTest {
  //Defined test dataset
  @testSetup
  static void setupdata() {
    //create an account record
    Account accObj = TestDataFactory.createAccountUMR();

    List<Acct_Rel__c> accRelList = new List<Acct_Rel__c>();

    Acct_Rel__c acctRel1 = TestDataFactory.createAccRel(accObj.Id);
    insert acctRel1;

    Id pricebookId = Test.getStandardPricebookId();

    //Create Quota Record
    Quotas__c quota = new Quotas__c();
    quota.ARR_Quotas_Amount__c = 1000;
    quota.IYR_Quotas_Amount__c = 2000;
    quota.Quotas_Owner__c = UserInfo.getUserId();
    quota.role__c = 'System Administrator';
    quota.Ending_Date__c = date.today().addMonths(3);
    quota.Starting_Date__c = date.today();
    insert quota;

    //create an opportunity record
    Opportunity oppObj = TestDataFactory.createOpportunity(accObj.Id);
    oppObj.Pricebook2Id = pricebookId;
    oppObj.Benefit_Consultant_Involved_in_Deal__c = 'NO';
    oppObj.LeadSource = 'Sales';
    oppObj.StageName = 'Prospect';
    oppObj.Quotas__c = quota.Id;
    oppObj.OwnerId = UserInfo.getUserId();
    insert oppObj;

    //create Gen Med product
    Product2 prod2 = TestDataFactory.createSingleProduct(
      'General Medical',
      'General Medical',
      'GM'
    );
    insert prod2;

    PricebookEntry pbEntry = TestDataFactory.createPriceBookEntries(
      new List<Product2>{ prod2 },
      pricebookId
    )[0];
    insert pbEntry;

    //Create a quote record
    SBQQ__Quote__c quoObj = TestDataFactory.createQuote(oppObj.Id);
    insert quoObj;

    SBQQ.TriggerControl.disable();
    //Create quotelines
    SBQQ__QuoteLine__c quoline1 = TestDataFactory.createQuoteLine(
      quoObj.Id,
      prod2.Id
    );
    insert quoline1;
  }

  @isTest
  public static void OpportunityContractingPassesValidation() {
    test.startTest();
    SBQQ.TriggerControl.disable();
    List<Opportunity> opplist = [SELECT id FROM Opportunity];
    PricebookEntry pbEntry = [SELECT Id, UnitPrice FROM PricebookEntry];
      Account accObj = TestDataFactory.createAccountUMR();
    OpportunityLineItem opl = new OpportunityLineItem();
    opl.OpportunityId = opplist[0].id;
    opl.Quantity = 500;
    opl.PricebookEntryId = pbEntry.Id;
    opl.TotalPrice = 500 * pbEntry.UnitPrice;

    insert opl;
    Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
    User u4 = new User(
      Alias = 'standt1',
      Country = 'United Kingdom',
      Email = 'demo1@teladochealth.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Testing',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      ProfileId = p.Id,
      TimeZoneSidKey = 'America/Los_Angeles',
      UserName = 'testoppvalid4@teladochealth.com'
    );
    insert u4;
    System.runAs(u4) {
      opplist[0].Contract_Path__c =accObj.Id; //System.Label.TD_Teladoc_Account;
      opplist[0].StageName = 'Contracting';
      update opplist;
      opplist[0].CloseDate = Date.Today().AddDays(7);
      update opplist;

      System.AssertEquals(Date.Today().AddDays(7), opplist[0].CloseDate);
    }
    SBQQ.TriggerControl.enable();
    test.stopTest();
  }

  @isTest
  public static void OpportunityContractingFailsValidation() {
    test.startTest();
    SBQQ.TriggerControl.disable();
    List<Opportunity> opplist = [SELECT id FROM Opportunity];
    PricebookEntry pbEntry = [SELECT Id, UnitPrice FROM PricebookEntry];
     Account accObj = TestDataFactory.createAccountUMR();
    OpportunityLineItem opl = new OpportunityLineItem();
    opl.OpportunityId = opplist[0].id;
    opl.Quantity = 500;
    opl.PricebookEntryId = pbEntry.Id;
    opl.TotalPrice = 500 * pbEntry.UnitPrice;
    insert opl;
    List<SBQQ__Quote__c> quolist = [SELECT id FROM SBQQ__Quote__c];
    Profile p = [SELECT Id FROM Profile WHERE Name = 'Sales Operations'];
    User u3 = new User(
      Alias = 'standt1',
      Country = 'United Kingdom',
      Email = 'demo1@teladochealth.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Testing',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      ProfileId = p.Id,
      TimeZoneSidKey = 'America/Los_Angeles',
      UserName = 'testoppvalid3@teladochealth.com'
    );
    insert u3;
    quolist[0].CPQ_Pricebook__c = 'Direct';
    update quolist;
    opplist[0].Contract_Path__c =accObj.Id; //System.Label.TD_Teladoc_Account;
    opplist[0].StageName = 'Contracting';
    opplist[0].OwnerId = u3.Id;
    update opplist;
    System.runAs(u3) {
      try {
        opplist[0].CloseDate = Date.Today().AddDays(7);
        update opplist;
      } catch (Exception e) {
        Boolean expectedExceptionThrown = e.getMessage()
            .contains(
              'Only user with Contracting Permission or System Administrator modify opportunity after the CPQ Records are created.'
            )
          ? true
          : false;
        System.AssertEquals(false, expectedExceptionThrown);
      }
    }
    SBQQ.TriggerControl.enable();
    test.stopTest();
  }

  @isTest
  public static void OpportunityClosedWonPassesValidation() {
    test.startTest();
    SBQQ.TriggerControl.disable();
    List<Opportunity> opplist = [SELECT id, CloseDate FROM Opportunity];
    PricebookEntry pbEntry = [SELECT Id, UnitPrice FROM PricebookEntry];
      Account accObj = TestDataFactory.createAccountUMR();
    OpportunityLineItem opl = new OpportunityLineItem();
    opl.OpportunityId = opplist[0].id;
    opl.Quantity = 500;
    opl.PricebookEntryId = pbEntry.Id;
    opl.TotalPrice = 500 * pbEntry.UnitPrice;
    insert opl;
    List<SBQQ__Quote__c> quolist = [SELECT id FROM SBQQ__Quote__c];
    Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
    User u1 = new User(
      Alias = 'standt1',
      Country = 'United Kingdom',
      Email = 'demo1@teladochealth.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Testing',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      ProfileId = p.Id,
      TimeZoneSidKey = 'America/Los_Angeles',
      UserName = 'testoppvalid1@teladochealth.com'
    );
    insert u1;
    System.runAs(u1) {
      quolist[0].CPQ_Pricebook__c = 'Direct';
      update quolist;
     opplist[0].Contract_Path__c = accObj.Id;//System.Label.TD_Teladoc_Account;
      opplist[0].StageName = 'Closed Won';
      opplist[0].Contracted_Date__c = Date.Today().AddDays(3);
      opplist[0]
        .Contract_Service_Agreement_Status__c = 'N/A - Under Master Agreement';
      update opplist;
      // new validation rule prevent revenue date change
      //opplist[0].CloseDate = Date.Today().AddDays (7);
      //update opplist;

      System.assertEquals(Date.Today(), opplist[0].CloseDate);
      SBQQ.TriggerControl.enable();
      test.stopTest();
    }
  }

  @isTest
  public static void OpportunityClosedWonFailsValidation() {
    test.startTest();
    SBQQ.TriggerControl.disable();
    List<Opportunity> opplist = [SELECT id, CloseDate FROM Opportunity];
    PricebookEntry pbEntry = [SELECT Id, UnitPrice FROM PricebookEntry];
      Account accObj = TestDataFactory.createAccountUMR();
    OpportunityLineItem opl = new OpportunityLineItem();
    opl.OpportunityId = opplist[0].id;
    opl.Quantity = 500;
    opl.PricebookEntryId = pbEntry.Id;
    opl.TotalPrice = 500 * pbEntry.UnitPrice;
    insert opl;
    List<SBQQ__Quote__c> quolist = [SELECT id FROM SBQQ__Quote__c];
    Profile p = [SELECT Id FROM Profile WHERE Name = 'Sales Operations'];
    User u2 = new User(
      Alias = 'standt1',
      Country = 'United Kingdom',
      Email = 'demo1@teladochealth.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Testing',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      ProfileId = p.Id,
      TimeZoneSidKey = 'America/Los_Angeles',
      UserName = 'testoppvalid2@teladochealth.com'
    );
    insert u2;
    quolist[0].CPQ_Pricebook__c = 'Direct';
    update quolist;
    opplist[0].Contract_Path__c =accObj.Id; //System.Label.TD_Teladoc_Account;
    opplist[0].StageName = 'Closed Won';
    opplist[0].Contracted_Date__c = Date.Today().AddDays(3);
    opplist[0].OwnerId = u2.Id;
    opplist[0]
      .Contract_Service_Agreement_Status__c = 'N/A - Under Master Agreement';

    update opplist;
    System.runAs(u2) {
      try {
        opplist[0].CloseDate = Date.Today().AddDays(7);
        update opplist;
      } catch (Exception e) {
        Boolean expectedExceptionThrown = e.getMessage()
            .contains(
              'Only System Administrators can edit a Closed Won Opportunity.'
            )
          ? true
          : false;
        System.AssertEquals(true, expectedExceptionThrown);
      }
    }
    SBQQ.TriggerControl.enable();
    test.stopTest();
  }

  //Test case for Contractee Relationship validation for Contracting/Closed Won Stage Change
  @isTest
  static void opportunityStageValidation() {
    test.startTest();
    SBQQ.TriggerControl.disable();
    List<Opportunity> opplist = [SELECT id FROM Opportunity];
    PricebookEntry pbEntry = [SELECT Id, UnitPrice FROM PricebookEntry];
      Account accObj = TestDataFactory.createAccountUMR();
    OpportunityLineItem opl = new OpportunityLineItem();
    opl.OpportunityId = opplist[0].id;
    opl.Quantity = 500;
    opl.PricebookEntryId = pbEntry.Id;
    opl.TotalPrice = 500 * pbEntry.UnitPrice;
    insert opl;
    //        List<Account> acclist =[select id from Account ];
    //        List<Acct_Rel__c> acctRellist =[select id from Acct_Rel__c];

    //        Acct_Rel__c acctRel3 = new Acct_Rel__c();
    //        acctRel3.Benefit_Sponsor__c = acclist[0].Id;
    //        acctRel3.Svc_Acct__c = acclist[0].Id;
    //        acctRel3.Relationship_Type__c = 'Contractee';
    //        acctRel3.Start_Date__c = Date.Today();
    //
    //        insert acctRel3;
    opplist[0]
      .Contract_Service_Agreement_Status__c = 'N/A - Under Master Agreement';
    opplist[0].Contract_Path__c =accObj.Id; //System.Label.TD_Teladoc_Account;
    opplist[0].StageName = 'Closed Won';
    opplist[0].Contracted_Date__c = Date.Today();
    update opplist;

    system.assertEquals('Closed Won', opplist[0].StageName);
    SBQQ.TriggerControl.enable();
    test.stopTest();
  }

  //Test case for Contractee Relationship validation for Contracting/Closed Won Stage Change
  @isTest
  static void opportunityStageErrorValidation() {
    test.startTest();
    SBQQ.TriggerControl.disable();
    List<Opportunity> opplist = [SELECT id FROM Opportunity];
    List<Account> acclist = [SELECT id FROM Account];
     Account accObj = TestDataFactory.createAccountUMR();
    List<Acct_Rel__c> acctRellist = [SELECT id FROM Acct_Rel__c];

    try {
      opplist[0].Contract_Path__c =accObj.Id; //System.Label.TD_Teladoc_Account;
      opplist[0].StageName = 'Contracting';
      update opplist;
    } catch (Exception e) {
      //Below values will be deprecated later for Contract Path LOB functionality
      //Boolean expectedExceptionThrown =  e.getMessage().contains('No Contractee relationship exists on account')?true : false;
      //System.AssertEquals(expectedExceptionThrown, true);
    }
    SBQQ.TriggerControl.enable();
    test.stopTest();
  }

  //Test case for Contractee Relationship validation for Contracting/Closed Won Stage Change
  @isTest
  static void OppRFPCreateTest() {
    test.startTest();
    SBQQ.TriggerControl.disable();
      Account accObj = TestDataFactory.createAccountUMR();
    Opportunity opp = [SELECT id FROM Opportunity LIMIT 1];
    opp.Contract_Path__c =accObj.Id; //System.Label.TD_Teladoc_Account;
    opp.StageName = 'Proposal';
    update opp;
    PricebookEntry pbEntry = [SELECT Id, UnitPrice FROM PricebookEntry];
    OpportunityLineItem opl = new OpportunityLineItem();
    opl.OpportunityId = opp.id;
    opl.Quantity = 500;
    opl.PricebookEntryId = pbEntry.Id;
    opl.TotalPrice = 500 * pbEntry.UnitPrice;
    insert opl;
    RFP__c rfp = new RFP__c(
      Opportunity__c = opp.id,
      Opportunity_plan__c = 'No',
      Relationship_map__c = 'No',
      Due_Date__c = Date.Today().addDays(30),
      Release_Date__c = Date.Today().addDays(15)
    );
    Database.insert(rfp);
    SBQQ.TriggerControl.enable();
    test.stopTest();
  }

  //Test case for enabling RFP finalist Checkbox on Opportunity
  @isTest
  static void OppRFPFinalistTest() {
    test.startTest();
    SBQQ.TriggerControl.disable();
       Account accObj = TestDataFactory.createAccountUMR();
    Opportunity opp = [
      SELECT Id, stageName, RFP_Finalist__c, RFP_Count__c
      FROM Opportunity
      LIMIT 1
    ];
    opp.Contract_Path__c = accObj.Id;//System.Label.TD_Teladoc_Account;
    opp.StageName = 'Proposal';
    update opp;
    PricebookEntry pbEntry = [SELECT Id, UnitPrice FROM PricebookEntry];
    OpportunityLineItem opl = new OpportunityLineItem();
    opl.OpportunityId = opp.Id;
    opl.Quantity = 500;
    opl.PricebookEntryId = pbEntry.Id;
    opl.TotalPrice = 500 * pbEntry.UnitPrice;
    insert opl;
    RFP__c rfp = new RFP__c(
      Opportunity__c = opp.Id,
      Opportunity_plan__c = 'No',
      Relationship_map__c = 'No',
      Due_Date__c = Date.Today().addDays(30),
      Release_Date__c = Date.Today().addDays(15)
    );
    Database.insert(rfp);

    opp.Contracted_Date__c = Date.today();
    opp.Contract_Service_Agreement_Status__c = 'Executed';
    opp.StageName = 'Closed Won';
    update opp;

    Opportunity oppAfterUpdate = [
      SELECT Id, stageName, RFP_Finalist__c, RFP_Count__c
      FROM Opportunity
      WHERE Id = :opp.Id
    ];
    //Verify if the RFP Finalist checkbox on Opp is updated to True
    System.assertEquals(true, oppAfterUpdate.RFP_Finalist__c);
    SBQQ.TriggerControl.enable();
    test.stopTest();
  }

  @isTest
  static void validateQuoteTotalSumFields() {
    test.startTest();
    SBQQ.TriggerControl.disable();   
    //Getting Test user
    List<String> lstUsernames = System.Label.TeladocHealth_SF_Support_Users.replaceAll(
        '\\s+',
        ''
      )
      .split(',');
    List<User> result = [
      SELECT Id, Name, lastname, firstname, username, email
      FROM User
      WHERE IsActive = TRUE AND profile.name='System Administrator' //username IN :lstUsernames
      ORDER BY LastName ASC
      LIMIT 1
    ];

    Opportunity opp = [SELECT Id, Quotas__c FROM Opportunity LIMIT 1];
    //create Quota record
    Quotas__c quota = new Quotas__c();
    quota.ARR_Quotas_Amount__c = 1000;
    quota.IYR_Quotas_Amount__c = 2000;
    quota.Quotas_Owner__c = result[0].id;
    quota.Ending_Date__c = date.today().addMonths(3);
    quota.Starting_Date__c = date.today();
    insert quota;

    opp.Quotas__c = quota.Id;
    update opp;
    SBQQ.TriggerControl.enable();
    test.stopTest();
    List<Quotas__c> quotas_inserted = [
      SELECT Id, Current_Total_ARR__c, Current_Total_IYR__c
      FROM Quotas__c
      WHERE Quotas_Owner__c = :result[0].id
    ];
    //System.assertEquals(2000, quotas_inserted[0].Current_Total_ARR__c,'failed in arr');
    //System.assertEquals(4000, quotas_inserted[0].Current_Total_IYR__c,'failed in iyr');
  }

  //Test case for validateContractingOpp method
  @isTest
  static void validateContractingOpp_positive() {
    test.startTest();
    SBQQ.TriggerControl.disable();
      Account accObj = TestDataFactory.createAccountUMR();
    Opportunity opp = [
      SELECT Id, stageName, RFP_Finalist__c, RFP_Count__c
      FROM Opportunity
      LIMIT 1
    ];
    opp.Contract_Path__c =accObj.Id; //System.Label.TD_Teladoc_Account;
    opp.StageName = 'Proposal';
    opp.SBQQ__Contracted__c = true;

    update opp;

    opp.Contracted_Date__c = Date.today();
    opp.StageName = 'Contracting';
    update opp;
    SBQQ.TriggerControl.enable();
    test.stopTest();
  }
}