manifest/objects/Acct_Rel__c.object
<CustomObject>
    <description>Models the possible contracts between any two accounts regardless of hierarchy</description>
    <fields>
        <fullName>Benefit_Sponsor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account receiving services</description>
        <inlineHelpText>Lookup the Benefit Sponsor Account (Account receiving services) of the Relationship</inlineHelpText>
        <label>Benefit Sponsor Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Servicing Accounts</relationshipLabel>
        <relationshipName>servicingaccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>Required on Contractee/Broker</description>
        <inlineHelpText>Required on Contractee/Broker</inlineHelpText>
        <label>Servicing Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Relationship_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Contract_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Date contract ends</description>
        <inlineHelpText>Enter the Date Relationship Terminated</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>Select the Line of Business</description>
        <inlineHelpText>Select the Line of Business</inlineHelpText>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Relationship_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Commercial_Fully_Insured_FI</fullName>
                    <label>Commercial Fully Insured (FI)</label>
                </value>
                <value>
                    <fullName>Commercial_Administrative_Services_Only_ASO</fullName>
                    <label>Commercial Administrative Services Only (ASO)</label>
                </value>
                <value>
                    <fullName>Marketplace_Exchange</fullName>
                    <label>Marketplace Exchange</label>
                </value>
                <value>
                    <fullName>Medicare-Medicaid Plan (MMP)</fullName>
                </value>
                <value>
                    <fullName>Dual Eligible Special Needs Plans (DSNP)</fullName>
                </value>
                <value>
                    <fullName>Medicaid_Managed_Care</fullName>
                    <label>Medicaid Managed Care</label>
                </value>
                <value>
                    <fullName>Medicaid Fee for Service (FFS)</fullName>
                </value>
                <value>
                    <fullName>Children’s Health Insurance Program (CHIP)</fullName>
                </value>
                <value>
                    <fullName>Temporary Assistance for Needy Families (TANF)</fullName>
                </value>
                <value>
                    <fullName>Medicare Supplement</fullName>
                </value>
                <value>
                    <fullName>Medicare Fee for Service (FFS)</fullName>
                </value>
                <value>
                    <fullName>Medicare Advantage with Part D (MAPD)</fullName>
                </value>
                <value>
                    <fullName>Medicare_Advantage_MA</fullName>
                    <label>Medicare Advantage (MA)</label>
                </value>
                <value>
                    <fullName>Critical Illness</fullName>
                </value>
                <value>
                    <fullName>Extended Health Care</fullName>
                </value>
                <value>
                    <fullName>Chambers of Commerce</fullName>
                </value>
                <value>
                    <fullName>Maximum Benefit</fullName>
                </value>
                <value>
                    <fullName>CINUP</fullName>
                </value>
                <value>
                    <fullName>Health Plan Commercial Solutions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <description>Select the type of Relationship for the Servicing Account.</description>
        <inlineHelpText>Select the type of Relationship for the Servicing Account.</inlineHelpText>
        <label>Servicing Account Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Account_Relationship_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date contract starts</description>
        <inlineHelpText>Enter the Date Relationship Started</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Svc_Acct__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account providing the service</description>
        <inlineHelpText>Lookup the Servicing Account of the Relationship</inlineHelpText>
        <label>Servicing Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Benefit Sponsor Accounts</relationshipLabel>
        <relationshipName>benefitsponsors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>REL-{00000000}</displayFormat>
        <label>Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/AcctGrpConParse_Exception__c.object
<CustomObject>
    <fields>
        <fullName>Short_Desc__c</fullName>
        <description>Abbreviated string hinting at the cause.</description>
        <label>Short Description</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AcctGrpConParse Exception</label>
    <nameField>
        <displayFormat>AGCPE-{00000000}</displayFormat>
        <label>AcctGrpConParse Exception</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AcctGrpConParse Exceptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/AcctGrpConParsing_Item__c.object
<CustomObject>
    <description>Staging queue to hold all data transmitted to create Accounts, groups, and contacts.</description>
    <fields>
        <fullName>Item_Data__c</fullName>
        <description>Data used to create supporting records</description>
        <label>Item Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>UMR, GENERIC, etc.</description>
        <label>Source</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AcctGrpConParsing Item</label>
    <nameField>
        <displayFormat>AGCPI-{00000000}</displayFormat>
        <label>AcctGrpConParsing Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AcctGrpConParsing Item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/globalValueSets/Account_Relationship_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Benefit Partner or Vendor</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Contractee</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Provider Only</fullName>
    </customValue>
    <customValue>
        <fullName>Payer and Eligibility Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Payer Only</fullName>
    </customValue>
    <customValue>
        <fullName>Referral Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Benefit Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Contractor</fullName>
        <isActive>false</isActive>
        <label>Contractor</label>
    </customValue>
    <customValue>
        <fullName>Benefit Partner</fullName>
        <isActive>false</isActive>
        <label>Benefit Partner</label>
    </customValue>
    <customValue>
        <fullName>Benefit Sponsor</fullName>
        <isActive>false</isActive>
        <label>Benefit Sponsor</label>
    </customValue>
    <masterLabel>Account Relationship Type</masterLabel>
</GlobalValueSet>

manifest/globalValueSets/Contract_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Health Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Platform</fullName>
    </customValue>
    <masterLabel>Contract Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

manifest/classes/F1bAcct_Test.cls
public class F1bAcct_Test {
  public static void AcctUpdateTest() {
    List<AcctGrpConParsing_Item__c> agcpiList = [
      SELECT Id, Item_Data__c
      FROM AcctGrpConParsing_Item__c
    ];
    F1BMainParser f1bp = new F1BMainParser();
    f1bp.parse(agcpiList[0].Item_Data__c);
    F1bp_Test.buildData(f1bp);
    Account oldacct = f1bp.benefitSponsor;
    oldacct.Name = 'test';
    insert oldacct;
   
    f1bp.benefitSponsor.Account_Legal_Name__c = 'NOT PARENT CAT COMPANY';
    f1bp.benefitSponsor.Friendly_Account_Name__c = 'Friendly Cat COMPANY';
    f1bp.benefitSponsor.BillingStreet = '123 Drive';
    f1bp.benefitSponsor.BillingCity = 'DALLAS';
    f1bp.benefitSponsor.BillingState = 'Texas';
    f1bp.benefitSponsor.BillingPostalCode = '75000';
    f1bp.benefitSponsor.BillingCountry = 'United States';
    f1bp.benefitSponsor.Revenue_Effective_Date__c = Date.parse('11/6/2020');
    f1bp.benefitSponsor.Type = 'Other';
    f1bp.benefitSponsor.Language__c = 'Spanish';
    f1bp.benefitSponsor.Total_US_Employees_Benefits_Enrolled__c = 3000;
    f1bp.benefitSponsor.Members__c = 3000;
    f1bp.benefitSponsor.Special_Instructions_for_Implementatio__c = 'test 12345';
    f1bp.PrintPhone = '1-800-Test (835-2362)';
    f1bp.PrintUrl = 'Teladoc.com/Test';
    f1bp.benefitSponsor.Members__c = 3000;
    F1BProcessor.ProcessEntry(f1bp, agcpiList[0].Id);
 Test.startTest();
    Account updateAcct = [
      SELECT
        Id,
        Account_Legal_Name__c,
        Friendly_Account_Name__c,
        BillingStreet,
        BillingCity,
        BillingState,
        BillingPostalCode,
        BillingCountry,
        Revenue_Effective_Date__c,
        Type,
        Language__c,
        Total_US_Employees_Benefits_Enrolled__c,
        Members__c,
        Special_Instructions_for_Implementatio__c,
        Name
      FROM Account
      WHERE Guid__c = :f1bp.benefitSponsor.Guid__c
    ];
    System.assertEquals('NOT PARENT CAT COMPANY', updateAcct.Name);
    System.assertEquals(
      'Friendly Cat COMPANY',
      updateAcct.Friendly_Account_Name__c
    );
    System.assertEquals('123 Drive', updateAcct.BillingStreet);
    System.assertEquals('DALLAS', updateAcct.BillingCity);
    System.assertEquals('Texas', updateAcct.BillingState);
    System.assertEquals('United States', updateAcct.BillingCountry);
    System.assertEquals('75000', updateAcct.BillingPostalCode);
    System.assertEquals(
      'NOT PARENT CAT COMPANY',
      updateAcct.Account_Legal_Name__c
    );
    System.assertEquals(3000, updateAcct.Members__c);
    System.assertEquals(
      3000,
      updateAcct.Total_US_Employees_Benefits_Enrolled__c
    );
    System.assertEquals('Other', updateAcct.Type);
    System.assertEquals('Spanish', updateAcct.Language__c);
    System.assertEquals(
      'test 12345',
      updateAcct.Special_Instructions_for_Implementatio__c
    );
    Test.stopTest();
  }

  public static void falseParentGuidTest() {
    Account acct = [SELECT Id FROM Account WHERE Name = 'National General'];
    List<AcctGrpConParsing_Item__c> agcpiList = [
      SELECT Id, Item_Data__c
      FROM AcctGrpConParsing_Item__c
    ];
    F1BMainParser f1bp = new F1BMainParser();
    f1bp.parse(agcpiList[0].Item_Data__c);
    f1bp.ParentGuid = 'this_is_not_guid';
    Test.startTest();
    Boolean isParentGuidFalse = F1bUtils_v2.FetchExistingData(
      f1bp,
      agcpiList[0].Id
    );
    System.assertEquals(false, isParentGuidFalse);
    List<AcctGrpConParse_Exception__c> agcpeList = F1bUtils_v2.exceptionsFound;
    Boolean isError = false;
    for (AcctGrpConParse_Exception__c agcpe : agcpeList) {
      if (agcpe.Short_Desc__c == 'INVALID_PARENT_GUID') {
        isError = true;
      }
    }
    System.assertEquals(true, isError);
    Test.stopTest();
  }

  public static void falseBSGuidTest() {
    Account acct = [SELECT Id FROM Account WHERE Name = 'National General'];
    List<AcctGrpConParsing_Item__c> agcpiList = [
      SELECT Id, Item_Data__c
      FROM AcctGrpConParsing_Item__c
    ];
    F1BMainParser f1bp = new F1BMainParser();
    f1bp.parse(agcpiList[0].Item_Data__c);
    f1bp.benefitSponsor.Guid__c = 'this-is-not-a-guid!!';
    Test.startTest();
    F1bUtils_v2.FetchExistingData(f1bp, agcpiList[0].Id);
    List<AcctGrpConParse_Exception__c> agcpeList = F1bUtils_v2.exceptionsFound;
    Boolean isError = false;
    for (AcctGrpConParse_Exception__c agcpe : agcpeList) {
      if (agcpe.Short_Desc__c == 'BSP_GUID_INVALID') {
        isError = true;
      }
    }
    System.assertEquals(true, isError);
    Test.stopTest();
  }

  public static void noAccountFoundTest() {
    Account acct = [SELECT Id FROM Account WHERE Name = 'National General'];
    List<AcctGrpConParsing_Item__c> agcpiList = [
      SELECT Id, Item_Data__c
      FROM AcctGrpConParsing_Item__c
    ];
    F1BMainParser f1bp = new F1BMainParser();
    f1bp.parse(agcpiList[0].Item_Data__c);
    f1bp.ParentGuid = 'D17631CA-FA3A-A2D1-EE8F-6DC3F45BF4BB';
    f1bp.benefitSponsor.Guid__c = 'D17631CA-FA3A-A2D1-EE8F-6DC3F45BF4BZ';
    Test.startTest();
    Boolean isParentGuidFalse = F1bUtils_v2.FetchExistingData(
      f1bp,
      agcpiList[0].Id
    );
    System.assertEquals(false, isParentGuidFalse);
    List<AcctGrpConParse_Exception__c> agcpeList = F1bUtils_v2.exceptionsFound;
    Boolean isError = false;
    for (AcctGrpConParse_Exception__c agcpe : agcpeList) {
      if (agcpe.Short_Desc__c == 'NO_ACCOUNTS_FOUND') {
        isError = true;
      }
    }
    System.assertEquals(true, isError);
    Test.stopTest();
  }

  public static void noUserIdFoundTest() {
    Account acct = [SELECT Id FROM Account WHERE Name = 'National General'];
    List<AcctGrpConParsing_Item__c> agcpiList = [
      SELECT Id, Item_Data__c
      FROM AcctGrpConParsing_Item__c
    ];
    F1BMainParser f1bp = new F1BMainParser();
    f1bp.parse(agcpiList[0].Item_Data__c);
    f1bp.benefitSponsor.ownerId = '005f40000056OccAAX';
    Test.startTest();
    Boolean isParentGuidFalse = F1bUtils_v2.FetchExistingData(
      f1bp,
      agcpiList[0].Id
    );
    System.assertEquals(false, isParentGuidFalse);
    List<AcctGrpConParse_Exception__c> agcpeList = F1bUtils_v2.exceptionsFound;
    Boolean isError = false;
    for (AcctGrpConParse_Exception__c agcpe : agcpeList) {
      System.debug(agcpe);
      if (agcpe.Short_Desc__c == 'INVALID_USER_ID') {
        isError = true;
      }
    }
    System.assertEquals(true, isError);
    Test.stopTest();
  }

  public static void nullUserIdTest() {
    List<AcctGrpConParsing_Item__c> agcpiList = [
      SELECT Id, Item_Data__c
      FROM AcctGrpConParsing_Item__c
    ];
    F1BMainParser f1bp = new F1BMainParser();
    f1bp.parse(agcpiList[0].Item_Data__c);
    f1bp.benefitSponsor.ownerId = null;
    f1bp.benefitSponsor.Account_Manager__c = null;
    Test.startTest();
    Boolean isParentGuidFalse = F1bUtils_v2.FetchExistingData(
      f1bp,
      agcpiList[0].Id
    );
    System.assertEquals(true, isParentGuidFalse);
    Test.stopTest();
  }

  public static void acctRelEndDate() {
    List<AcctGrpConParsing_Item__c> agcpiList = [
      SELECT Id, Item_Data__c
      FROM AcctGrpConParsing_Item__c
    ];
    F1BMainParser f1bp = new F1BMainParser();
    f1bp.parse(agcpiList[0].Item_Data__c);
    F1bp_Test.buildData(f1bp);
    f1bp.EndDate = Date.parse('11/6/2020');
    Test.startTest();
    F1BProcessor.ProcessEntry(f1bp, agcpiList[0].Id);
    //System.assertEquals(1, [ SELECT Count() FROM Acct_Rel__c ]);
    //System.assertEquals('2020-11-06 00:00:00', string.valueOfGmt([ SELECT End_Date__c FROM Acct_Rel__c ].End_Date__c));
    Test.stopTest();
  }

  public static void AcctFailInsertTest() {
    Account acct = [SELECT Id FROM Account WHERE Name = 'National General'];
    List<AcctGrpConParsing_Item__c> agcpiList = [
      SELECT Id, Item_Data__c
      FROM AcctGrpConParsing_Item__c
    ];
    F1BMainParser f1bp = new F1BMainParser();
    f1bp.parse(agcpiList[0].Item_Data__c);
    F1bp_Test.buildData(f1bp);
    f1bp.benefitSponsor.Account_Legal_Name__c = null;
    f1bp.benefitSponsor.Name = null;
    Test.startTest();
    F1BProcessor.ProcessEntry(f1bp, agcpiList[0].Id);
    //System.assertEquals(1, [SELECT Count() FROM AcctGrpConParse_Exception__c WHERE Short_Desc__c = 'CANNOT_CREATE_ACCOUNT' ]);
    Test.stopTest();
  }

  public static void AccountRelationshipTest() {
    Account Umr = [SELECT Id, Guid__c FROM Account WHERE Name = 'UMR'];
    Account benefitAcct = new Account();
    benefitAcct.Name = 'testAcct';
    benefitAcct.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
      .get('Standard')
      .getRecordTypeId();
    benefitAcct.Friendly_Account_Name__c = 'TestAmendAccount';
    benefitAcct.Source__c = 'HUB';
    benefitAcct.CurrencyIsoCode = 'USD';
    benefitAcct.Business_Region__c = 'USA';
    benefitAcct.Account_Type__c = 'Health Plan';
    insert benefitAcct;
    AcctGrpConParsing_Item__c agcpi = [
      SELECT Id, Item_Data__c
      FROM AcctGrpConParsing_Item__c
    ];
    F1BMainParser f1bp = new F1BMainParser();
    f1bp.parse(agcpi.Item_Data__c);
    Acct_Rel__c newAcctRel1 = new Acct_Rel__c(
      Svc_Acct__c = Umr.Id,
      Benefit_Sponsor__c = benefitAcct.Id,
      Relationship_Type__c = 'Contractee',
      Contract_Type__c = 'Insurance',
      Line_of_Business__c = 'Commercial_Administrative_Services_Only_ASO',
      Start_Date__c = system.today() - 1
    );
    Acct_Rel__c newAcctRel2 = new Acct_Rel__c(
      Svc_Acct__c = Umr.Id,
      Benefit_Sponsor__c = benefitAcct.Id,
      Relationship_Type__c = 'Contractee',
      Contract_Type__c = 'Insurance',
      Line_of_Business__c = 'Commercial_Administrative_Services_Only_ASO',
      Start_Date__c = system.today()
    );
    insert newAcctRel1;
    insert newAcctRel2;
    Datetime older = Datetime.now().addDays(-30);
    Test.setCreatedDate(newAcctRel2.Id, older);
    Test.setCreatedDate(newAcctRel1.Id, Date.Today());
    Test.startTest();
    Acct_Rel__c acctRel = F1bUtils_v2.Create_AcctRel(
      Umr,
      benefitAcct,
      agcpi.Id,
      f1bp
    );
    system.assertEquals(acctRel.Id, newAcctRel1.Id);
    Test.stopTest();
  }
}