manifest/objects/Acct_Rel__c.object
<CustomObject>
    <description>Models the possible contracts between any two accounts regardless of hierarchy</description>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>REL-{00000000}</displayFormat>
        <label>Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this Opportunity Product.</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>OpportunityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

manifest/objects/Quotas__c.object
<CustomObject>
    <label>Quotas</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quota Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>CPQ_Pricebook__c</fullName>
        <label>CPQ Pricebook</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sales_Channels__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>CPQ_Pricebooks</valueSetName>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>CPQ_Pricebook__c</fullName>
        <formula>TEXT(SBQQ__Quote__r.CPQ_Pricebook__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CPQ Pricebook</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/globalValueSets/CPQ_Pricebooks.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Carrier</fullName>
    </customValue>
    <customValue>
        <fullName>Canada Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Canada Insurance (New)</fullName>
    </customValue>
    <customValue>
        <fullName>Canada Insurance (Exist)</fullName>
    </customValue>
    <customValue>
        <fullName>HealthPlan</fullName>
    </customValue>
    <customValue>
        <fullName>Complex Case Mgmt</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>HHS</fullName>
    </customValue>
    <customValue>
        <fullName>Cross-Sell</fullName>
        <isActive>false</isActive>
        <label>Cross-Sell</label>
    </customValue>
    <masterLabel>CPQ Pricebooks</masterLabel>
</GlobalValueSet>

manifest/classes/Quotas_Test.cls
@isTest
private class Quotas_Test {
  @testSetup
  static void setupdata() {
    Account umrAcct = TestDataFactory.createUMR();

   Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
   User u1 = TestDataFactory.createUser(p.Id);
   insert u1;
    

    Quotas__c quotas = TestDataFactory.createQuotas(u1.Id);
    insert quotas;
    Account accObj = TestDataFactory.createAccountUMR();

    Acct_Rel__c acctRel1 = TestDataFactory.createAccRel(accObj.Id);
    insert acctRel1;

    Id pricebookId = Test.getStandardPricebookId();
    //create an opportunity record
    Opportunity oppObj = TestDataFactory.createOpportunityWithPriceBook(
      accObj.Id,
      pricebookId,
      u1.Id
    );
    insert oppObj;

    Product2 prod2 = TestDataFactory.createProducts(
      new List<String>{ 'General Medical' }
    )[0];
    insert prod2;

    PricebookEntry pbEntry = TestDataFactory.createPriceBookEntries(
      new List<Product2>{ prod2 },
      pricebookId
    )[0];
    insert pbEntry;

    //Create a quote record
    SBQQ__Quote__c quoObj = TestDataFactory.createQuote(oppObj.Id);
    quoObj.CPQ_Pricebook__c = 'Broker';
    insert quoObj;

    SBQQ__QuoteLine__c quoline1 = TestDataFactory.createQuoteLine(
      quoObj.Id,
      prod2.Id
    );
    insert quoline1;
  }
  @isTest
  static void updateOppForQuotas() {
     
    test.startTest();
    SBQQ.TriggerControl.disable();
    Opportunity oppObj = [SELECT Id, Pricebook2Id FROM Opportunity];
    PricebookEntry pbEntry = [SELECT Id, UnitPrice FROM PricebookEntry];
    Account accObj = TestDataFactory.createAccountUMR();
    OpportunityLineItem opl = TestDataFactory.createOLI(
      oppObj.Id,
      pbEntry.Id,
      null
    );
    opl.Quantity = 500;
    opl.TotalPrice = 500 * pbEntry.UnitPrice;
    insert opl;
    //Account accObj = [SELECT Id FROM Account WHERE Name = 'TestAmendAccount'];
   // User u1 = [SELECT Id FROM User WHERE Alias = 'standt1'];
    Quotas__c quotas = [SELECT Id FROM Quotas__c];

    oppObj.Contracted_Date__c = Date.Today();
    oppObj.Contract_Service_Agreement_Status__c = 'N/A - Under Master Agreement';
    oppObj.Contract_Path__c =accObj.Id; //System.Label.TD_Teladoc_Account;
    oppObj.StageName = 'Closed Won';
	 update oppObj;
    system.assertEquals(
      quotas.Id,
      [SELECT quotas__c FROM Opportunity WHERE Id = :oppObj.Id].quotas__c
   );
    SBQQ.TriggerControl.enable();
    test.stopTest();
  }

}