manifest/objects/Acct_Rel__c.object
<CustomObject>
    <description>Models the possible contracts between any two accounts regardless of hierarchy</description>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>Required on Contractee/Broker</description>
        <inlineHelpText>Required on Contractee/Broker</inlineHelpText>
        <label>Servicing Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Relationship_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Contract_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <description>Select the type of Relationship for the Servicing Account.</description>
        <inlineHelpText>Select the type of Relationship for the Servicing Account.</inlineHelpText>
        <label>Servicing Account Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Account_Relationship_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>REL-{00000000}</displayFormat>
        <label>Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/globalValueSets/Account_Relationship_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Benefit Partner or Vendor</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Contractee</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Provider Only</fullName>
    </customValue>
    <customValue>
        <fullName>Payer and Eligibility Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Payer Only</fullName>
    </customValue>
    <customValue>
        <fullName>Referral Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Benefit Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Contractor</fullName>
        <isActive>false</isActive>
        <label>Contractor</label>
    </customValue>
    <customValue>
        <fullName>Benefit Partner</fullName>
        <isActive>false</isActive>
        <label>Benefit Partner</label>
    </customValue>
    <customValue>
        <fullName>Benefit Sponsor</fullName>
        <isActive>false</isActive>
        <label>Benefit Sponsor</label>
    </customValue>
    <masterLabel>Account Relationship Type</masterLabel>
</GlobalValueSet>

manifest/globalValueSets/Contract_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Health Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Platform</fullName>
    </customValue>
    <masterLabel>Contract Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

manifest/classes/PrimaryCarrierLookupLWC_Controller_Test.cls
@isTest
private class PrimaryCarrierLookupLWC_Controller_Test {
  @testSetup
  static void setupdata() {
    Account umrAcct = TestDataFactory.createUMR();
    //create an account record
    Account accObj = TestDataFactory.createAccountUMR();

    //Create Account Relationships
    List<Acct_Rel__c> accRelList = new List<Acct_Rel__c>();

    Acct_Rel__c acctRel1 = TestDataFactory.createAccRel(accObj.Id);
    acctRel1.Relationship_Type__c = 'Payer and Eligibility Provider';
    acctRel1.Contract_Type__c = null;
    accRelList.add(acctRel1);

    Acct_Rel__c acctRel2 = TestDataFactory.createAccRel(accObj.Id);
    acctRel2.Relationship_Type__c = 'Eligibility Provider Only';
    acctRel2.Contract_Type__c = null;
    accRelList.add(acctRel2);

    insert accRelList;

    //create an opportunity record
    Opportunity oppObj2 = TestDataFactory.createOpportunity(accObj.Id);
    oppObj2.LeadSource = 'Sales';
    insert oppObj2;
  }

  @isTest
  static void fetchAcctRel_Test() {
    Opportunity opp = [SELECT Id, AccountId FROM Opportunity];
    List<Acct_Rel__c> acctRelList = PrimaryCarrierLookupLWC_Controller.fetchAcctRel(
      opp.Id
    );
    system.assertEquals(2, acctRelList.size());
  }

  @isTest
  static void updateOpp_Test() {
    Opportunity opp = [SELECT Id, AccountId FROM Opportunity];
    Acct_Rel__c acctRel = [SELECT Id FROM Acct_Rel__c LIMIT 1];
    PrimaryCarrierLookupLWC_Controller.updateOpp(opp.Id, acctRel.Id);
    system.assertEquals(
      acctRel.Id,
      [SELECT Primary_Carrier__c FROM Opportunity].Primary_Carrier__c
    );
  }

  @isTest
  static void fetchCurrnetCarrier_Test() {
    Opportunity opp = [SELECT Id, AccountId FROM Opportunity];
    Acct_Rel__c acctRel = PrimaryCarrierLookupLWC_Controller.fetchCurrnetCarrier(
      opp.Id
    );
    system.assertEquals(null, acctRel);
  }

  @isTest
  static void validatePC_Test() {
    Opportunity opp = [SELECT Id, AccountId FROM Opportunity];
    Opportunity oppTest = PrimaryCarrierLookupLWC_Controller.validatePC(opp.Id);
    system.assertEquals(null, oppTest);
  }
}