manifest/objects/AcctGrpConParse_Exception__c.object
<CustomObject>
    <fields>
        <fullName>AGCPI__c</fullName>
        <description>Parent to this exception</description>
        <label>AcctGrpConParsing Item</label>
        <referenceTo>AcctGrpConParsing_Item__c</referenceTo>
        <relationshipLabel>AcctGrpConParse Exceptions</relationshipLabel>
        <relationshipName>AcctGrpConParse_Exceptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <description>What is the category of this exception (e.g. INFO, FORMAT ERROR, CONTENT ERROR, REQUIRED)</description>
        <label>Exception Type</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Desc__c</fullName>
        <description>Everything about the exception.</description>
        <label>Full Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SObject__c</fullName>
        <description>Which object was affected.</description>
        <label>SObject</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Short_Desc__c</fullName>
        <description>Abbreviated string hinting at the cause.</description>
        <label>Short Description</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AcctGrpConParse Exception</label>
    <nameField>
        <displayFormat>AGCPE-{00000000}</displayFormat>
        <label>AcctGrpConParse Exception</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AcctGrpConParse Exceptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/AcctGrpConParsing_Item__c.object
<CustomObject>
    <description>Staging queue to hold all data transmitted to create Accounts, groups, and contacts.</description>
    <fields>
        <fullName>Batch_Key__c</fullName>
        <description>Used to identify grouped submissions</description>
        <label>Batch Key</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Batch_Time__c</fullName>
        <description>When this batch was uploaded.</description>
        <label>Batch Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Item_Key__c</fullName>
        <label>Item Key</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>UMR, GENERIC, etc.</description>
        <label>Source</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AcctGrpConParsing Item</label>
    <nameField>
        <displayFormat>AGCPI-{00000000}</displayFormat>
        <label>AcctGrpConParsing Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AcctGrpConParsing Item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Plan_Specific_Fees__c.object
<CustomObject>
    <fields>
        <fullName>PSF_ProductCode__c</fullName>
        <formula>IF( Asset__c != NULL, Asset__r.Product2.ProductCode,  Subscription__r.SBQQ__Product__r.ProductCode)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PSF ProductCode</label>
        <type>Text</type>
    </fields>
    <label>Plan-Specific Fees By Product</label>
    <nameField>
        <displayFormat>PSF-{0000000}</displayFormat>
        <label>Plan Fees ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan-Specific Fees By Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/classes/MassPsfDeletion_Bch.cls
global without sharing class MassPsfDeletion_Bch implements Database.Batchable<sObject> {
    AcctGrpConParsing_Item__c agcpi = new AcctGrpConParsing_Item__c(Batch_Key__c = String.valueOf(DateTime.now().getTime()), Item_Key__c = String.valueOf(DateTime.now().getTime()/1000), Processed__c = true, Batch_Time__c = DateTime.now(), Source__c = 'PSF_DELETION');
    global Database.QueryLocator start(Database.BatchableContext bc) {
        insert agcpi;
        return Database.getQueryLocator([SELECT Id FROM Plan_Specific_Fees__c WHERE Psf_ProductCode__c IN ('BH')]);
    }
    
    global void execute(Database.BatchableContext bc, List<Plan_Specific_Fees__c> scope) {
        Database.DeleteResult[] dr = Database.delete(scope, false);
        for (Database.DeleteResult rowSr : dr) {
            if (!rowSr.isSuccess()) {
                for (Database.Error rowError : rowSr.getErrors()) {
                    createException(agcpi.Id, 'PLAN_SPECIFIC_FEES__C', 'ERROR', 'PSF_DELETE_FAILED',
                                    rowError.getMessage());
                }
            }
        } 
    }
    global void finish(Database.BatchableContext bc) {
    }
    global void createException(Id sourceAgcpi, String exType, String sObjectName, String shortDesc, String fullDesc) {
        AcctGrpConParse_Exception__c tmpAgcpe = new AcctGrpConParse_Exception__c();
        tmpAgcpe.Agcpi__c = sourceAgcpi;
        tmpAgcpe.Exception_Type__c = exType.trim().toUpperCase();
        tmpAgcpe.sobject__c = sObjectName.trim().toUpperCase();
        tmpAgcpe.Short_Desc__c = shortDesc.left(64).trim().toUpperCase();
        if (fullDesc.length() > 255) {
            tmpAgcpe.Full_Desc__c = fullDesc.substring(0, 255);
        } else {
            tmpAgcpe.Full_Desc__c = fullDesc;
            
        }
        insert tmpAgcpe;
    }
}