manifest/objects/AcctGrpConParsing_Item__c.object
<CustomObject>
    <description>Staging queue to hold all data transmitted to create Accounts, groups, and contacts.</description>
    <fields>
        <fullName>Batch_Key__c</fullName>
        <description>Used to identify grouped submissions</description>
        <label>Batch Key</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Batch_Time__c</fullName>
        <description>When this batch was uploaded.</description>
        <label>Batch Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Item_Data__c</fullName>
        <description>Data used to create supporting records</description>
        <label>Item Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Item_Defaults__c</fullName>
        <label>Item Defaults</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Item_Key__c</fullName>
        <label>Item Key</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>UMR, GENERIC, etc.</description>
        <label>Source</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AcctGrpConParsing Item</label>
    <nameField>
        <displayFormat>AGCPI-{00000000}</displayFormat>
        <label>AcctGrpConParsing Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AcctGrpConParsing Item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Disclaimers__c.object
<CustomObject>
    <description>Standard Welcome Kit disclaimer language options.</description>
    <fields>
        <fullName>Disclaimer_Language__c</fullName>
        <description>Specific boilerplate language options related to Welcome Kit disclaimer</description>
        <inlineHelpText>Specific boilerplate language options related to Welcome Kit disclaimer</inlineHelpText>
        <label>Disclaimer Language</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Source_Id__c</fullName>
        <externalId>true</externalId>
        <label>Source Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Disclaimers</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disclaimers</pluralLabel>
    <recordTypes>
        <fullName>Teladoc</fullName>
        <active>true</active>
        <description>For fields on Member Group Object (Disclaimer - Teladoc, Disclaimer - Client, Disclaimer - Custom)</description>
        <label>Disclaimer</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Source_Id__c</fullName>
        <externalId>true</externalId>
        <label>Source Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account that owns this subscription. This relationship is used for volume discount calculations.</description>
        <inlineHelpText>Account that owns this subscription. This relationship is used for volume discount calculations.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product used to sell this subscription.</description>
        <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity of this subscription product purchased by the customer.</description>
        <inlineHelpText>Quantity of this subscription product purchased by the customer.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Source_Id__c</fullName>
        <description>** Back End only ** Do not add to page layouts</description>
        <externalId>true</externalId>
        <label>Source Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Web_URLs__c.object
<CustomObject>
    <description>Storage of Teladoc custom URLs for print and web fulfillment</description>
    <label>Web URLs</label>
    <nameField>
        <label>Web URL</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Web URLs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/classes/UmrAcctGrpConParse_Bch_Test.cls
@isTest
private class UmrAcctGrpConParse_Bch_Test {
  @TestSetup
  static void setup() {
    Account umrAcct = TestDataFactory.createUMR();
    List<Product2> cpq_prods = new List<Product2>();
    Product2 prod_gm = new Product2(name = 'General Medical');
    Product2 prod_bh = new Product2(name = 'Behavioral Health Care');
    Product2 prod_derm = new Product2(name = 'Dermatology');

    Database.insert(new List<SObject>{ prod_gm, prod_bh, prod_derm });

    Account tmpAcct = new Account(
      Name = 'UMR',
      Account_Legal_Name__c = 'UMR',
      Source__c = 'HUB',
      CurrencyIsoCode = 'USD',
      Business_Region__c = 'USA'
    );

    insert tmpAcct;
    List<SBQQ__Subscription__c> umr_subs = new List<SBQQ__Subscription__c>();
    umr_subs.add(
      new SBQQ__Subscription__c(
        Source_Id__c = 'a2h60000001Rxg6AAC',
        SBQQ__Account__c = tmpAcct.Id,
        SBQQ__Product__c = prod_gm.Id,
        SBQQ__Quantity__c = 100
      )
    );
    umr_subs.add(
      new SBQQ__Subscription__c(
        Source_Id__c = 'a2hf2000002IW0CAAW',
        SBQQ__Account__c = tmpAcct.Id,
        SBQQ__Product__c = prod_bh.Id,
        SBQQ__Quantity__c = 100
      )
    );
    umr_subs.add(
      new SBQQ__Subscription__c(
        Source_Id__c = 'a2hf2000002IW0DAAW',
        SBQQ__Account__c = tmpAcct.Id,
        SBQQ__Product__c = prod_derm.Id,
        SBQQ__Quantity__c = 100
      )
    );
    insert umr_subs;
    List<AcctGrpConParsing_Item__c> tmpAgcpis = Test.loadData(
      AcctGrpConParsing_Item__c.sObjectType,
      'umr_agcpi_tests'
    );
    for (AcctGrpConParsing_Item__c tmpAgcpi : tmpAgcpis) {
      tmpAgcpi.processed__c = false;
    }
    update tmpAgcpis;
    Disclaimers__c tmpDisclaimer = new Disclaimers__c(
      Name = 'STND',
      Disclaimer_Language__c = '© 2019 Teladoc Health, Inc. All rights reserved. Teladoc and the Teladoc logo are registered trademarks of Teladoc Health, Inc. and may not be used without written permission. Teladoc does not replace the primary care physician. Teladoc does not guarantee that a prescription will be written. Teladoc operates subject to state regulation and may not be available in certain states. Teladoc does not prescribe DEA controlled substances, non therapeutic drugs and certain other drugs which may be harmful because of their potential for abuse. Teladoc physicians reserve the right to deny care for potential misuse of services.'
    );
    insert tmpDisclaimer;

    Web_URLs__c tmpUrL = new Web_URLs__c(Name = 'Teladoc.com');
    insert tmpUrL;
  }

  @IsTest
  static void UmrAcctGrpConParse_Bch_Null_Test() {
    string query = null;
    Test.startTest();
    UmrAcctGrpConParse_Bch testing = new UmrAcctGrpConParse_Bch(query);
    DataBase.executeBatch(testing);
    Test.stopTest();
  }

  @IsTest
  static void UmrAcctGrpConParse_Bch_Test() {
    string query = 'select id, batch_key__c, batch_time__c, item_data__c, item_defaults__c, item_key__c from acctgrpconparsing_item__c where source__c = \'UMR\' and processed__c = false';

    Test.startTest();
    UmrAcctGrpConParse_Bch testing = new UmrAcctGrpConParse_Bch(query);
    DataBase.executeBatch(testing);
    Test.stopTest();
  }
}