manifest/objects/Acct_Rel__c.object
<CustomObject>
    <description>Models the possible contracts between any two accounts regardless of hierarchy</description>
    <fields>
        <fullName>Benefit_Sponsor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account receiving services</description>
        <inlineHelpText>Lookup the Benefit Sponsor Account (Account receiving services) of the Relationship</inlineHelpText>
        <label>Benefit Sponsor Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Servicing Accounts</relationshipLabel>
        <relationshipName>servicingaccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Date contract ends</description>
        <inlineHelpText>Enter the Date Relationship Terminated</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <description>Select the type of Relationship for the Servicing Account.</description>
        <inlineHelpText>Select the type of Relationship for the Servicing Account.</inlineHelpText>
        <label>Servicing Account Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Account_Relationship_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>REL-{00000000}</displayFormat>
        <label>Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Approvals__c</fullName>
        <description>Display text for approval message on Edit Lines and Quote.  BR below is carriage return</description>
        <formula>IF(Approval_Custom_Consult_Fees__c, &apos;Custom Consult Fees&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_Direct_Broker_Included_2499__c, TEXT(CPQ_Pricebook__c) &amp; &apos; Consults Included and Lives &gt; 9999&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_Free_Trial__c, &apos;Free Trial Period&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_GM_BH_HY_Zero_Net_Price__c, &apos;GM, BH, HY or BD Zero Net Price&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_GM_HY_Broker_Direct_U_Cap_0__c, TEXT(CPQ_Pricebook__c) &amp; &apos; &apos; &amp; &apos; GM or HY Initial Utilization Cap is Zero&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_GM_HY_Util_Cap_Changed_or_0__c, &apos; GM or HY Initial Utilization Cap is Zero or Changed from Default&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_GM_Included_w_Other_Products__c, &apos;GM Consults Included with Other Products&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_GM_Missing_w_Other_Products__c, &apos;Invalid Standalone Product&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_GM_More_than_1__c, &apos;There is More than One GM Listed in Quote Lines&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_HY_Standard__c, &apos;HY has a Standard Consult Fee&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_HY_with_Anything__c, &apos;HY with Invalid Products&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_Line_Discounted__c, &apos;Line Level Discount&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_Quote_Discounted__c, &apos;Quote Level Discount&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_First_Consult_Free__c, &apos;First Consult Free&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_BD_Standalone__c, &apos;Best Doctors Standalone or Invalid Combo&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_Software_Development_Kit__c, &apos;Marketing Product – SDK&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_BD_1000_lives__c, &apos;BD optional product &lt; 1000 lives&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_EMS_Standard_5000_lives__c, &apos;EMS Standard &lt; 5000 lives&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_BD_Consult_Type__c , &apos;BH consult type different from GM or HY&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_No_Carrier_price__c, &apos;No price for product in the Carrier pricebook&apos; &amp; BR(), &apos;&apos;) &amp;
IF( Approval_BH_with_PL__c, &apos;Behavioral Health Care Standalone or Invalid Combo&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_GLOBALCARE_3000_lives__c , &apos;Global Care optional product &lt; 3000 lives&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_GlobalCare_Included__c, &apos;Global Care Consult Type Included&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_GM_Standard__c, &apos;GM has a Standard Consult Fee&apos;&amp; BR(), &apos;&apos;)&amp;
IF( Approval_SPS_20k_lives__c , &apos;SPS has a 0 fee&apos; &amp; BR(), &apos;&apos;)&amp;
IF( Approval_SPS_60k_lives__c , &apos;SPS optional product &gt; 60K lives&apos; &amp; BR(), &apos;&apos;)&amp;
IF( Approval_DedicatedPhone_200K__c , &apos;Dedicated Phone 200K Lives or Less&apos; &amp; BR(), &apos;&apos;)&amp;
IF( Approval_Case_Rate__c , &apos;Case Rate changed from default&apos; &amp; BR(), &apos;&apos;)&amp;
IF( Approval_TIMAP_5000_lives__c, &apos;TIMAP &lt; 5000 lives&apos; &amp; BR(), &apos;&apos;)&amp;
IF(Approval_PRIM360_10000_lives__c, &apos;PRIMARY CARE &lt; 1000 lives&apos; &amp; BR(), &apos;&apos;)&amp;
IF(Approval_PRIM360_Fee_Type__c, &apos;PRIMARY CARE Fee Type&apos; &amp; BR(), &apos;&apos;)&amp;
IF(Approval_Milestone_Based_Pricing__c, &apos;Milestone Based Pricing&apos; &amp; BR(), &apos;&apos;)&amp;
IF(Approval_Provider_Based_Care__c, &apos;Provider Based Care with Invalid Products&apos; &amp; BR(), &apos;&apos;)&amp;
IF(Approval_LandingPage_1M_Revenue__c, &apos;Net Annual Revenue &lt; $1,000,000.00&apos; &amp; BR(), &apos;&apos;)</formula>
        <inlineHelpText>Display text for approval message on Edit Lines and Quote.  BR below is carriage return</inlineHelpText>
        <label>Approvals</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/globalValueSets/Account_Relationship_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Benefit Partner or Vendor</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Contractee</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Provider Only</fullName>
    </customValue>
    <customValue>
        <fullName>Payer and Eligibility Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Payer Only</fullName>
    </customValue>
    <customValue>
        <fullName>Referral Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Benefit Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Contractor</fullName>
        <isActive>false</isActive>
        <label>Contractor</label>
    </customValue>
    <customValue>
        <fullName>Benefit Partner</fullName>
        <isActive>false</isActive>
        <label>Benefit Partner</label>
    </customValue>
    <customValue>
        <fullName>Benefit Sponsor</fullName>
        <isActive>false</isActive>
        <label>Benefit Sponsor</label>
    </customValue>
    <masterLabel>Account Relationship Type</masterLabel>
</GlobalValueSet>

manifest/classes/CreateContractController.cls
public with sharing class CreateContractController {   
    @AuraEnabled
    public static string errorCheck(Id recordId){
        boolean contracteeRel = false;
        boolean quoteApproved = true;
        
        String error;
        Opportunity opp = [SELECT Id, AccountId, StageName, Account.Primary_Billing_Contact__c, Initial_of_Lives__c,
                           (SELECT Id, Contact.Name FROM OpportunityContactRoles) FROM Opportunity WHERE Id =: recordId];
        
        List<SBQQ__Quote__c> sbqqQte = [SELECT Id, SBQQ__Primary__c, Approvals__c, SBQQ__Status__c FROM SBQQ__Quote__c 
                                  WHERE SBQQ__Primary__c = TRUE 
                                  AND SBQQ__Opportunity2__c =:recordId];
        
        List<OpportunityLineItem> oppProd = [SELECT Id FROM OpportunityLineItem WHERE ProductCode='EMO2' AND OpportunityId =: recordId];
        
        if(sbqqQte.size() > 0){
            system.debug(sbqqQte[0].SBQQ__Status__c != 'Approved');
            if(sbqqQte[0].Approvals__c !=null && sbqqQte[0].SBQQ__Status__c != 'Approved') {
                quoteApproved = false;
            }
        }   
           
        List<Profile> PROFILE = [SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId() LIMIT 1];
        String MyProflieName = PROFILE[0].Name;
        if (MyProflieName != 'System Administrator') {
            List<Acct_Rel__c> acctRelList = [SELECT Relationship_Type__c FROM Acct_Rel__c WHERE Benefit_Sponsor__c =: opp.AccountId AND (End_Date__c > today OR End_Date__c = null)];            
            for (Acct_Rel__c acctRel : acctRelList) {
                if (acctRel.Relationship_Type__c == 'Contractee') {
                    contracteeRel = true;
                }
            }
        } else {
            contracteeRel = true;
        }
        
        //Below values will be deprecated later for Contract Path LOB functionality
        /*if (contracteeRel == false) {
            error = 'No Contractee relationship exists on account';
            return error;
        }*/
        
        if (opp.Initial_of_Lives__c == null) {
            error = 'Number of Lives field missing, can not create a Contract';
            return error;
        } else if (opp.Account.Primary_Billing_Contact__c == null){
            error = 'Primary Billing Contact missing, can not create a Contract';
            return error;
        } else if (opp.OpportunityContactRoles.size() == 0) {
            error = 'Contact Role is missing, can not create a Contract';
            return error;
        } else if (oppProd.size() > 0){
            error = 'Can not create contract with EMS products are on the quote';
            return error;
        } else if (sbqqQte.size() == 0) {
            error = 'No Primary Quote for the Opportunity, Can not create a Contract';
            return error;
        } else if (!quoteApproved) {
            error = 'Primary Quote is not Approved, Can not create a Contract';
            return error;
        } else if(opp.StageName != 'Contracting') {
            error = 'The Opportunity must be in Contracting to create an Octiv Contract';
            return error;
        }
       
        return null;
    }     
}