manifest/objects/AcctGrpConParsing_Item__c.object
<CustomObject>
    <description>Staging queue to hold all data transmitted to create Accounts, groups, and contacts.</description>
    <fields>
        <fullName>Batch_Key__c</fullName>
        <description>Used to identify grouped submissions</description>
        <label>Batch Key</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Batch_Time__c</fullName>
        <description>When this batch was uploaded.</description>
        <label>Batch Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Item_Data__c</fullName>
        <description>Data used to create supporting records</description>
        <label>Item Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Item_Defaults__c</fullName>
        <label>Item Defaults</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Item_Key__c</fullName>
        <label>Item Key</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>UMR, GENERIC, etc.</description>
        <label>Source</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AcctGrpConParsing Item</label>
    <nameField>
        <displayFormat>AGCPI-{00000000}</displayFormat>
        <label>AcctGrpConParsing Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AcctGrpConParsing Item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/classes/AGCPI_PRE_Test.cls
@IsTest
private class AGCPI_PRE_Test {
  @IsTest
  static void Test_Batch_Key() {
    String batchid = String.valueOf(DateTime.now().getTime());
    AcctGrpConParsing_Item__c tmpAgcpi = new AcctGrpConParsing_Item__c(
      Source__c = 'UMR',
      Batch_Key__c = batchid,
      Item_Key__c = '12345',
      Item_Data__c = '{}',
      Item_Defaults__c = '{}'
    );
    List<AcctGrpConParsing_Item__c> newAgcpi = new List<AcctGrpConParsing_Item__c>{
      tmpAgcpi
    };
    DateTime tmpTime = DateTime.newInstance(
      Long.ValueOf(tmpAgcpi.Batch_Key__c)
    );
    System.Debug(tmpTime);
    Database.SaveResult[] sr = Database.insert(newAgcpi);
    tmpAgcpi = [
      SELECT id, Batch_Time__c
      FROM AcctGrpConParsing_Item__c
      WHERE Item_Key__c = '12345'
    ];
    System.assertNotEquals(null, tmpAgcpi.Batch_Time__c);
  }
}