manifest/objects/AcctGrpConParsing_Item__c.object
<CustomObject>
    <description>Staging queue to hold all data transmitted to create Accounts, groups, and contacts.</description>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <label>AcctGrpConParsing Item</label>
    <nameField>
        <displayFormat>AGCPI-{00000000}</displayFormat>
        <label>AcctGrpConParsing Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AcctGrpConParsing Item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/F1b_Remove_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Key_Word__c</fullName>
        <label>Key Word</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>F1b_Remove_Setting</label>
</CustomObject>

manifest/classes/Flow1b_E2E_Test.cls
@IsTest
private class Flow1b_E2E_Test {
  @TestSetup
  public static void setup() {
    F1b_Remove_Setting__c f1bSetting = F1b_Remove_Setting__c.getOrgDefaults();
    f1bSetting.Key_Word__c = 'NONE;!!!';
    insert f1bSetting;
  }
  @IsTest
  static void Flow1b_E2E_Test() {
    List<AcctGrpConParsing_Item__c> tmpAgcpis = Test.loadData(
      AcctGrpConParsing_Item__c.sObjectType,
      'flow1b_agcpi_no_error_Tests'
    );
    for (AcctGrpConParsing_Item__c tmpAgcpi : tmpAgcpis) {
      tmpAgcpi.processed__c = false;
    }
    update tmpAgcpis;
    String result = Flow1b_E2E.Flow1b_E2E('123');
    Boolean checkResult = result.contains('NO_RECORDS_FOUND');
    system.assertNotEquals(true, checkResult);
  }

  @IsTest
  static void Flow1b_E2E_No_Record_Test() {
    String result = Flow1b_E2E.Flow1b_E2E('123');
    Boolean checkResult = result.contains('NO_RECORDS_FOUND');
    system.assertNotEquals(false, checkResult);
  }
}