manifest/objects/Acct_Rel__c.object
<CustomObject>
    <description>Models the possible contracts between any two accounts regardless of hierarchy</description>
    <fields>
        <fullName>Benefit_Sponsor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account receiving services</description>
        <inlineHelpText>Lookup the Benefit Sponsor Account (Account receiving services) of the Relationship</inlineHelpText>
        <label>Benefit Sponsor Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Servicing Accounts</relationshipLabel>
        <relationshipName>servicingaccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>Required on Contractee/Broker</description>
        <inlineHelpText>Required on Contractee/Broker</inlineHelpText>
        <label>Servicing Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Relationship_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Contract_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <description>Select the type of Relationship for the Servicing Account.</description>
        <inlineHelpText>Select the type of Relationship for the Servicing Account.</inlineHelpText>
        <label>Servicing Account Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Account_Relationship_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Svc_Acct__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account providing the service</description>
        <inlineHelpText>Lookup the Servicing Account of the Relationship</inlineHelpText>
        <label>Servicing Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Benefit Sponsor Accounts</relationshipLabel>
        <relationshipName>benefitsponsors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>REL-{00000000}</displayFormat>
        <label>Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Msg_Bus_Fields__mdt.object
<CustomObject>
    <fields>
        <fullName>Account_Fields__c</fullName>
        <label>Account Fields</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact_Fields__c</fullName>
        <label>Contact Fields</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity_Fields__c</fullName>
        <label>Opportunity Fields</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity_Line_Item_Fields__c</fullName>
        <label>Opportunity Line Item Fields</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Parser_Name__c</fullName>
        <label>Parser Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Msg Bus Fields</label>
    <pluralLabel>Msg Bus Fields</pluralLabel>
</CustomObject>

manifest/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this Opportunity Product.</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>OpportunityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

manifest/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>Admin_Fee__c</fullName>
        <label>Admin Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Anchor__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to mark the anchor product of the Bundle. The anchor product holds the total price of the bundle.</description>
        <inlineHelpText>Flag to mark the anchor product of the Bundle. The anchor product holds the total price of the bundle.</inlineHelpText>
        <label>Anchor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>At_Risk_PPPM__c</fullName>
        <label>At Risk Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Disable_Coaching__c</fullName>
        <description>Used in Product rule to configure MyStrength product</description>
        <label>Disable Mental Health Guidance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NO</fullName>
                    <default>true</default>
                    <label>NO</label>
                </value>
                <value>
                    <fullName>YES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Disable_Teletherapy__c</fullName>
        <description>Used in Product rule to configure MyStrength product</description>
        <label>Disable Teletherapy</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NO</fullName>
                </value>
                <value>
                    <fullName>YES</fullName>
                    <default>true</default>
                    <label>YES</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GrandParent_Product_Code__c</fullName>
        <formula>SBQQ__RequiredBy__r.SBQQ__RequiredBy__r.SBQQ__Product__r.ProductCode</formula>
        <label>GrandParent Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership_Fee__c</fullName>
        <description>This is the PEPM/PMPM that includes any discounts.  It is the Net Unit Price (which is annual) divided by 12.  It is also used to populate the Subscription Membership Fee field (formula).

    SBQQ__NetPrice__c/IF(SBQQ__SubscriptionTerm__c &lt;&gt; Null, SBQQ__SubscriptionTerm__c, Quote_Subscription_Term__c)</description>
        <formula>IF( NOT(ISNULL(Subscription_Fee__c)), Subscription_Fee__c ,If(Additional_Disc__c = 0,SBQQ__ListPrice__c - SBQQ__AdditionalDiscountAmount__c, SBQQ__ListPrice__c - Additional_Disc__c) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the PEPM/PMPM that includes any discounts.</inlineHelpText>
        <label>Membership Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_ARR__c</fullName>
        <label>Net ARR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Parent_Product_Code__c</fullName>
        <formula>SBQQ__RequiredBy__r.SBQQ__ProductCode__c</formula>
        <label>Parent Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Participant_Quantity__c</fullName>
        <label>Participant Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Rollup__c</fullName>
        <formula>IF(
NOT(ISBLANK(SBQQ__RequiredBy__c)),
IF(
NOT(ISBLANK(SBQQ__RequiredBy__r.SBQQ__RequiredBy__c)),
IF(
NOT(ISBLANK(SBQQ__RequiredBy__r.SBQQ__RequiredBy__r.SBQQ__RequiredBy__c)),
IF(
NOT(ISBLANK(SBQQ__RequiredBy__r.SBQQ__RequiredBy__r.SBQQ__RequiredBy__r.SBQQ__RequiredBy__c)),
SBQQ__RequiredBy__r.SBQQ__RequiredBy__r.SBQQ__RequiredBy__r.SBQQ__Product__r.Name,
SBQQ__RequiredBy__r.SBQQ__RequiredBy__r.SBQQ__RequiredBy__r.SBQQ__Product__r.Name
),
SBQQ__RequiredBy__r.SBQQ__RequiredBy__r.SBQQ__Product__r.Name
),
SBQQ__RequiredBy__r.SBQQ__Product__r.Name
),
SBQQ__Product__r.Name
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Rollup</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__EffectiveSubscriptionTerm__c</fullName>
        <description>Effective term for this subscription.</description>
        <formula>IF(ISBLANK(SBQQ__SubscriptionTerm__c),
       IF(ISBLANK(SBQQ__Group__r.SBQQ__SubscriptionTerm__c),SBQQ__Quote__r.SBQQ__SubscriptionTerm__c,SBQQ__Group__r.SBQQ__SubscriptionTerm__c),
       SBQQ__SubscriptionTerm__c
    )</formula>
        <inlineHelpText>Effective term for this subscription.</inlineHelpText>
        <label>Effective Subscription Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Up_Front_Fee__c</fullName>
        <label>Up Front Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/globalValueSets/Account_Relationship_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Benefit Partner or Vendor</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Contractee</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Provider Only</fullName>
    </customValue>
    <customValue>
        <fullName>Payer and Eligibility Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Payer Only</fullName>
    </customValue>
    <customValue>
        <fullName>Referral Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Benefit Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Contractor</fullName>
        <isActive>false</isActive>
        <label>Contractor</label>
    </customValue>
    <customValue>
        <fullName>Benefit Partner</fullName>
        <isActive>false</isActive>
        <label>Benefit Partner</label>
    </customValue>
    <customValue>
        <fullName>Benefit Sponsor</fullName>
        <isActive>false</isActive>
        <label>Benefit Sponsor</label>
    </customValue>
    <masterLabel>Account Relationship Type</masterLabel>
</GlobalValueSet>

manifest/globalValueSets/Contract_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Health Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Platform</fullName>
    </customValue>
    <masterLabel>Contract Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

manifest/classes/MB_OppJSONGenerator.cls
// TDH SIDE
public without sharing class MB_OppJSONGenerator {
  public static JSONGenerator generateJSONContent(String guid) {
    Msg_Bus_Fields__mdt fields = [
      SELECT
        Account_Fields__c,
        Contact_Fields__c,
        Opportunity_Fields__c,
        Opportunity_Line_Item_Fields__c
      FROM Msg_Bus_Fields__mdt
      WHERE Parser_Name__c = 'Opportunity_Parser'
      LIMIT 1
    ];
    List<String> oppFields = fields.Opportunity_Fields__c.replaceAll('\\s+', '')
      .split(',');
    List<String> acctFields = fields.Account_Fields__c.replaceAll('\\s+', '')
      .split(',');
    //List<String> conFields = fields.Contact_Fields__c.replaceAll( '\\s+', '').split(',');
    List<String> oppliFields = fields.Opportunity_Line_Item_Fields__c.replaceAll(
        '\\s+',
        ''
      )
      .split(',');

    String oppQuery = 'SELECT ';
    for (Integer i = 0; i < oppFields.size(); i++) {
      if (oppFields.size() - 1 == i) {
        oppQuery =
          oppQuery +
          oppFields[i] +
          ' FROM Opportunity WHERE Opp_Guid__c = \'' +
          guid +
          '\'';
      } else {
        oppQuery = oppQuery + oppFields[i] + ', ';
      }
    }
    system.debug(oppQuery);
    Opportunity opp = Database.query(oppQuery);

    String acctQuery = 'SELECT ';
    for (Integer i = 0; i < acctFields.size(); i++) {
      if (acctFields.size() - 1 == i) {
        acctQuery =
          acctQuery +
          acctFields[i] +
          ' FROM Account WHERE Id = \'' +
          opp.AccountId +
          '\'';
      } else {
        acctQuery = acctQuery + acctFields[i] + ', ';
      }
    }
    Account acct = Database.query(acctQuery);

    Account carrierAcct = null;
    String carrierAcctQuery = 'SELECT ';
    if (opp.Primary_Carrier_Account__c != null) {
      String primAcctGuid = [
        SELECT Svc_Acct__r.Guid__c
        FROM Acct_Rel__c
        WHERE Id = :opp.Primary_Carrier__c
      ]
      .Svc_Acct__r.Guid__c;
      for (Integer i = 0; i < acctFields.size(); i++) {
        if (acctFields.size() - 1 == i) {
          carrierAcctQuery =
            carrierAcctQuery +
            acctFields[i] +
            ' FROM Account WHERE Guid__c = \'' +
            primAcctGuid +
            '\'';
        } else {
          carrierAcctQuery = carrierAcctQuery + acctFields[i] + ', ';
        }
      }
      carrierAcct = Database.query(carrierAcctQuery);
    } 
    /*SCDEV-4859 - Changes Begin
    else if (
      opp.Parent_Opportunity__c != null &&
      opp.Parent_Opportunity__r.Sub_Type__c == 'TPA/Reseller'
    ) {
      List<Acct_Rel__c> resellerAcctRel = [
        SELECT Svc_Acct__r.Guid__c
        FROM Acct_Rel__c
        WHERE
          Svc_Acct__c = :opp.Parent_Opportunity__r.AccountId
          AND Relationship_Type__c = 'Contractee'
          AND Contract_Type__c = 'Reseller'
          AND Benefit_Sponsor__c = :opp.AccountId
      ];
      if (!resellerAcctRel.isEmpty()) {
        for (Integer i = 0; i < acctFields.size(); i++) {
          if (acctFields.size() - 1 == i) {
            carrierAcctQuery =
              carrierAcctQuery +
              acctFields[i] +
              ' FROM Account WHERE Guid__c = \'' +
              resellerAcctRel[0].Svc_Acct__r.Guid__c +
              '\'';
          } else {
            carrierAcctQuery = carrierAcctQuery + acctFields[i] + ', ';
          }
        }
        carrierAcct = Database.query(carrierAcctQuery);
      }
    }
	SCDEV-4859 Changes End*/

    String oppliQuery = 'SELECT ';
    for (Integer i = 0; i < oppliFields.size(); i++) {
      if (oppliFields.size() - 1 == i) {
        oppliQuery =
          oppliQuery +
          oppliFields[i] +
          ' FROM OpportunityLineItem WHERE OpportunityId = \'' +
          opp.Id +
          '\'';
      } else {
        oppliQuery = oppliQuery + oppliFields[i] + ', ';
      }
    }
    List<String> byPassList = new List<String>{
      'Primary_Carrier__r.Svc_Acct__r.GUID__c',
      'Parent_Opportunity__r.Sub_Type__c',
      'Parent_Opportunity__r.AccountId'
    };
    List<OpportunityLineItem> oppliList = Database.query(oppliQuery);
    List<OpportunityLineItem> lvnPppliList = new List<OpportunityLineItem>();
    List<String> lvnProdCode = new List<String>();
    List<Product2> prodList = [
      SELECT Id, ProductCode
      FROM Product2
      WHERE Family LIKE '%Livongo%'
    ];
    for (Product2 prod : prodList) {
      lvnProdCode.add(prod.ProductCode);
    }

    for (OpportunityLineItem oppli : oppliList) {
      if (lvnProdCode.contains(oppli.ProductCode)) {
        lvnPppliList.add(oppli);
      }
    }

    JSONGenerator gen = JSON.createGenerator(true);
    gen.writeStartObject();
    gen.writeStringField('CreatedbyId', UserInfo.getUserId());
    gen.writeStringField('Createddate', String.valueOf(system.now()));

    gen.writeFieldName('Account');
    gen.writeStartObject();
    for (String acctField : acctFields) {
      if (acctField == 'Name') {
        if (acct.get(acctField) == null) {
          gen.writeNullField('Name');
        } else {
          String accName = String.valueOf(acct.get(acctField));
          accName = accName.length() > 80 ? accName.substring(0, 80) : accName;
          gen.writeStringField('Name', accName);
        }
      }
      if (acct.get(acctField) != null) {
        gen.writeStringField(
          acctField,
          (String) String.valueOf(acct.get(acctField))
        );
      } else {
        gen.writeNullField(acctField);
      }
    }
    if (opp.get('Primary_Carrier_LOB__c') != null) {
      gen.writeStringField(
        'LOB',
        (String) String.valueOf(opp.get('Primary_Carrier_LOB__c'))
      );
    } else {
      gen.writeNullField('LOB');
    }
    gen.writeEndObject();

    gen.writeFieldName('Opportunity');
    gen.writeStartObject();
    for (String oppField : oppFields) {
      if (!byPassList.contains(oppField)) {
        if (opp.get(oppField) != null) {
          if (oppField == 'Client_Manager__c') {
            String managerId = [
              SELECT Id
              FROM USER
              WHERE Name = :String.valueOf(opp.get(oppField))
            ]
            .Id;
            gen.writeStringField(oppField, (String) String.valueOf(managerId));
          } else if (oppField == 'Name') {
            if (opp.get('Name') == null) {
              gen.writeNullField('Name');
            } else {
              String OppName = (String.valueOf(opp.get(oppField)));
              OppName = OppName.length() > 80
                ? OppName.substring(0, 80)
                : OppName;
              gen.writeStringField('Name', OppName);
              //gen.writeStringField('Name', (String) (String.valueOf(opp.get(oppField))));
            }
          } else {
            gen.writeStringField(
              oppField,
              (String) String.valueOf(opp.get(oppField))
            );
          }
        } else {
          gen.writeNullField(oppField);
        }
      }
    }
    gen.writeEndObject();

    if (carrierAcct != null) {
      gen.writeFieldName('PrimaryCarrierAccount');
      gen.writeStartObject();
      for (String acctField : acctFields) {
        if (carrierAcct.get(acctField) != null) {
          gen.writeStringField(
            acctField,
            (String) String.valueOf(carrierAcct.get(acctField))
          );
        } else {
          gen.writeNullField(acctField);
        }
      }
      gen.writeEndObject();
    }

    gen.writeFieldName('OpportunityLineItem');
    gen.writeStartArray();
    for (OpportunityLineItem oppli : lvnPppliList) {
      gen.writeStartObject();
      for (String oppliField : oppliFields) {
        system.debug('oppliField:: ' + oppliField);
        switch on oppliField {
          when 'Anchor__c' {
            if (oppli.Anchor__c == null) {
              gen.writeNullField('Anchor');
            } else {
              gen.writeStringField(
                'Anchor',
                (String) String.valueOf(oppli.get(oppliField))
              );
            }
          }
          when 'SBQQ__QuoteLine__r.SBQQ__EffectiveSubscriptionTerm__c' {
            if (
              oppli.SBQQ__QuoteLine__r.SBQQ__EffectiveSubscriptionTerm__c ==
              null
            ) {
              gen.writeNullField('SubscriptionTerm');
            } else {
              gen.writeStringField(
                'SubscriptionTerm',
                (String) String.valueOf(
                  oppli.SBQQ__QuoteLine__r.SBQQ__EffectiveSubscriptionTerm__c
                )
              );
            }
          }
          when 'Membership_fee__c' {
            if (oppli.Membership_fee__c == null) {
              gen.writeNullField('SalesPrice');
            } else {
              gen.writeStringField(
                'SalesPrice',
                (String) String.valueOf(oppli.get(oppliField))
              );
            }
          }
          when 'SBQQ__QuoteLine__r.Parent_Product_Code__c' {
            if (oppli.SBQQ__QuoteLine__r.Parent_Product_Code__c == null) {
              gen.writeNullField('ParentsProductCode');
            } else {
              gen.writeStringField(
                'ParentsProductCode',
                (String) String.valueOf(
                  oppli.SBQQ__QuoteLine__r.Parent_Product_Code__c
                )
              );
            }
          }
          when 'SBQQ__QuoteLine__r.GrandParent_Product_Code__c' {
            if (oppli.SBQQ__QuoteLine__r.GrandParent_Product_Code__c == null) {
              gen.writeNullField('GrandParentsProductCode');
            } else {
              gen.writeStringField(
                'GrandParentsProductCode',
                (String) String.valueOf(
                  oppli.SBQQ__QuoteLine__r.GrandParent_Product_Code__c
                )
              );
            }
          }
          when 'SBQQ__QuoteLine__r.Participant_Quantity__c' {
            if (oppli.SBQQ__QuoteLine__r.Participant_Quantity__c == null) {
              gen.writeNullField('ParticipantQuantity');
            } else {
              gen.writeStringField(
                'ParticipantQuantity',
                (String) String.valueOf(
                  Math.Round(oppli.SBQQ__QuoteLine__r.Participant_Quantity__c)
                )
              );
            }
          }
          when 'SBQQ__QuoteLine__r.Admin_Fee__c' {
            if (oppli.SBQQ__QuoteLine__r.Admin_Fee__c == null) {
              gen.writeNullField('AdminFee');
            } else {
              gen.writeStringField(
                'AdminFee',
                (String) String.valueOf(
                  Math.Round(oppli.SBQQ__QuoteLine__r.Admin_Fee__c)
                )
              );
            }
          }
          when 'SBQQ__QuoteLine__r.At_Risk_PPPM__c' {
            if (oppli.SBQQ__QuoteLine__r.At_Risk_PPPM__c == null) {
              gen.writeNullField('AtRiskFee');
            } else {
              gen.writeStringField(
                'AtRiskFee',
                (String) String.valueOf(
                  Math.Round(oppli.SBQQ__QuoteLine__r.At_Risk_PPPM__c)
                )
              );
            }
          }
          when 'SBQQ__QuoteLine__r.Up_Front_Fee__c' {
            if (oppli.SBQQ__QuoteLine__r.Up_Front_Fee__c == null) {
              gen.writeNullField('UpFrontFee');
            } else {
              gen.writeStringField(
                'UpFrontFee',
                (String) String.valueOf(
                  Math.Round(oppli.SBQQ__QuoteLine__r.Up_Front_Fee__c)
                )
              );
            }
          }
          when 'SBQQ__QuoteLine__r.Disable_Teletherapy__c' {
            if (oppli.SBQQ__QuoteLine__r.Disable_Teletherapy__c == null) {
              gen.writeNullField('DisableTeletherapy');
            } else {
              gen.writeStringField(
                'DisableTeletherapy',
                (String) String.valueOf(
                  oppli.SBQQ__QuoteLine__r.Disable_Teletherapy__c
                )
              );
            }
          }
          when 'SBQQ__QuoteLine__r.Disable_Coaching__c' {
            if (oppli.SBQQ__QuoteLine__r.Disable_Coaching__c == null) {
              gen.writeNullField('DisableBHCoaching');
            } else {
              gen.writeStringField(
                'DisableBHCoaching',
                (String) String.valueOf(
                  oppli.SBQQ__QuoteLine__r.Disable_Coaching__c
                )
              );
            }
          }
          when 'Net_ARR__c' {
            if (oppli.Net_ARR__c == null) {
              gen.writeNullField('NetArr');
            } else {
              gen.writeStringField(
                'NetArr',
                (String) String.valueOf(oppli.get(oppliField))
              );
            }
          }
    	 when 'Product_Rollup__c' {                                   //Added By rushikesh 5537
            if (oppli.Product_Rollup__c == null) {
              gen.writeNullField('ProductRollup');
            } else {
              gen.writeStringField(
                'ProductRollup',
                (String) String.valueOf(oppli.get(oppliField))
              );
            }
          } 
          when 'Name' {
            if (oppli.Name == null) {
              gen.writeNullField('Name');
            } else {
              String oppLiName = String.valueOf(oppli.get(oppliField));
              oppLiName = oppLiName.length() > 80
                ? oppLiName.substring(0, 80)
                : oppLiName;
              gen.writeStringField('Name', oppLiName);
              //gen.writeStringField('Name', (String) (String.valueOf(oppli.get(oppliField))));
            }
          }
          when else {
            if (oppli.get(oppliField) != null) {
              system.debug('oppliField::: ' + oppliField);
              system.debug(
                'fieldName:: ' + (String) String.valueOf(oppli.get(oppliField))
              );
              gen.writeStringField(
                oppliField,
                (String) String.valueOf(oppli.get(oppliField))
              );
            } else {
              gen.writeNullField(oppliField);
            }
          }
        }
      }
      gen.writeEndObject();
    }
    gen.writeEndArray();
    /*
        gen.writeFieldName('Contact');
        gen.writeStartArray();
        for(Contact con : conList){
            gen.writeStartObject();
            for (String conField : conFields) {
                if (con.get(conField) != null) {
                    gen.writeStringField(conField, (String) con.get(conField));
                }
            }
            gen.writeEndObject();
        }
        gen.writeEndArray();
        */
    gen.writeEndObject();

    String pretty = gen.getAsString();
    system.debug(pretty);

    return gen;
  }

  public static JSONGenerator generateDeleteJSON(String guid) {
    JSONGenerator gen = JSON.createGenerator(true);
    gen.writeStartObject();
    gen.writeStringField('CreatedbyId', UserInfo.getUserId());
    gen.writeStringField('Createddate', String.valueOf(system.now()));

    gen.writeFieldName('Opportunity');
    gen.writeStartObject();
    gen.writeStringField('Opp_Guid__c', (String) guid);
    gen.writeEndObject();
    return gen;
  }
}