manifest/objects/AcctGrpConParse_Exception__c.object
<CustomObject>
    <fields>
        <fullName>AGCPI__c</fullName>
        <description>Parent to this exception</description>
        <label>AcctGrpConParsing Item</label>
        <referenceTo>AcctGrpConParsing_Item__c</referenceTo>
        <relationshipLabel>AcctGrpConParse Exceptions</relationshipLabel>
        <relationshipName>AcctGrpConParse_Exceptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <description>What is the category of this exception (e.g. INFO, FORMAT ERROR, CONTENT ERROR, REQUIRED)</description>
        <label>Exception Type</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Desc__c</fullName>
        <description>Everything about the exception.</description>
        <label>Full Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SObject__c</fullName>
        <description>Which object was affected.</description>
        <label>SObject</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Short_Desc__c</fullName>
        <description>Abbreviated string hinting at the cause.</description>
        <label>Short Description</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AcctGrpConParse Exception</label>
    <nameField>
        <displayFormat>AGCPE-{00000000}</displayFormat>
        <label>AcctGrpConParse Exception</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AcctGrpConParse Exceptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/AcctGrpConParsing_Item__c.object
<CustomObject>
    <description>Staging queue to hold all data transmitted to create Accounts, groups, and contacts.</description>
    <fields>
        <fullName>Batch_Key__c</fullName>
        <description>Used to identify grouped submissions</description>
        <label>Batch Key</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Batch_Time__c</fullName>
        <description>When this batch was uploaded.</description>
        <label>Batch Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Item_Key__c</fullName>
        <label>Item Key</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>UMR, GENERIC, etc.</description>
        <label>Source</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AcctGrpConParsing Item</label>
    <nameField>
        <displayFormat>AGCPI-{00000000}</displayFormat>
        <label>AcctGrpConParsing Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AcctGrpConParsing Item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Consult_Fees__c</fullName>
        <label>Consult Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__RequiredBySubscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The parent Subscription. If populated, this Asset is a child in a bundle.</inlineHelpText>
        <label>Required By Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Assets (Required By Subscription)</relationshipLabel>
        <relationshipName>ChildAssets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Plan_Specific_Fees__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Copay_May_Be_Less__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Actual Copay May Be Less</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Plan-Specific Fees By Product (Asset)</relationshipLabel>
        <relationshipName>Plan_Specific_Fees_By_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consult_Fee_Initial_Diagnostic_Mbr_Pd__c</fullName>
        <label>Consult Fee- Psych/MD-1stvisitonly-MbrPd</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Consult_Fee_Initial_Diagnostic_Plan_Pd__c</fullName>
        <label>Consult Fee-Psych/MD-1stvisitonly-PlanPd</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Consult_Fee_Mbr_Pd__c</fullName>
        <label>Consult Fee - Mbr Pd</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Consult_Fee_Ongoing_MD_Mbr_Pd__c</fullName>
        <label>Consult Fee- Psych/MD-ONGOINGvisit-MbrPd</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Consult_Fee_Ongoing_MD_Plan_Pd__c</fullName>
        <label>Consult Fee-Psych/MD-ONGOINGvisit-PlanPd</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Consult_Fee_Ongoing_Non_MD_Mbr_Pd__c</fullName>
        <label>Consult Fee- Non-Psychiatrist- Mbr Pd</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Consult_Fee_Ongoing_Non_MD_Plan_Pd__c</fullName>
        <label>Consult Fee- Non-Psychiatrist- Plan Pd</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Consult_Fee_Plan_Pd__c</fullName>
        <label>Consult Fee - Plan Pd</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DERMConsult_Fee_Mbr_Pd__c</fullName>
        <label>DERMConsult Fee - Mbr Pd</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DERMConsult_Fee_Plan_Pd__c</fullName>
        <label>DERMConsult Fee - Plan Pd</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Member_Group__c</fullName>
        <label>Member Group</label>
        <referenceTo>Mbr_Group__c</referenceTo>
        <relationshipLabel>Plan-Specific Fees By Product</relationshipLabel>
        <relationshipName>Plan_Specific_Fees_By_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_End_Date__c</fullName>
        <label>Product End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Start_Date__c</fullName>
        <label>Product Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Plan-Specific Fees By Product</relationshipLabel>
        <relationshipName>Plan_Specific_Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TC_Client_Case_Rate_Fee__c</fullName>
        <description>Tobacco Cessation Client Case Rate Fee</description>
        <inlineHelpText>Tobacco Cessation Client Case Rate Fee</inlineHelpText>
        <label>Client Case Rate Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TC_Mbr_Case_Rate_Fee__c</fullName>
        <label>Mbr Case Rate Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Plan-Specific Fees By Product</label>
    <nameField>
        <displayFormat>PSF-{0000000}</displayFormat>
        <label>Plan Fees ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan-Specific Fees By Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>Consult_Fees__c</fullName>
        <label>Consult Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product used to sell this subscription.</description>
        <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/classes/MassPsfMigration.cls
public class MassPsfMigration {
  List<Plan_Specific_Fees__c> psfToUpdate = new List<Plan_Specific_Fees__c>();
  List<Plan_Specific_Fees__c> psfToInsert = new List<Plan_Specific_Fees__c>();

  Map<String, Plan_Specific_Fees__c> parentPsf = new Map<String, Plan_Specific_Fees__c>();
  Map<String, Plan_Specific_Fees__c> currentPsf = new Map<String, Plan_Specific_Fees__c>();
  // PSF needing conversion
  List<String> productKeys = new List <String>{ 'BH', 'TC', 'DERM', 'MH'};
  Map<String, List<String>> assetKeys = new Map<String, List<String>>();

  public void ProcessRecords(Id memberGroupId){

    assetKeys.put('BH' , new List<String>{ 'BHP1T','BHPOT','BHNPT'});
    assetKeys.put('MH', new List<String>{ 'BHPOT', 'BHPOOT','BHNPT'});
    assetKeys.put('TC', new List<String>{ 'TCPROGFEE'});
    assetKeys.put('DERM', new List<String>{ 'DERMFEE'});


    Set<String> assetProductCodes = new Set<String>();
    for(String tmpAssetKey : assetKeys.keySet()){
      for(String tmpProd : assetKeys.get(tmpAssetKey)){
        assetProductCodes.add(tmpProd);
      }
    }

    Set<Id> subscriptionIdsInUse = new Set<Id>();
    List<Plan_Specific_Fees__c> scopedPsf =
    [SELECT Id, Member_Group__c, Asset__c, Actual_Copay_May_Be_Less__c, Consult_Fee_Initial_Diagnostic_Mbr_Pd__c, Consult_Fee_Initial_Diagnostic_Plan_Pd__c
        , Consult_Fee_Mbr_Pd__c, Consult_Fee_Plan_Pd__c, Consult_Fee_Ongoing_MD_Mbr_Pd__c, Consult_Fee_Ongoing_MD_Plan_Pd__c
        , Consult_Fee_Ongoing_Non_MD_Mbr_Pd__c, Consult_Fee_Ongoing_Non_MD_Plan_Pd__c, DERMConsult_Fee_Mbr_Pd__c, DERMConsult_Fee_Plan_Pd__c
        , TC_Client_Case_Rate_Fee__c, TC_Mbr_Case_Rate_Fee__c, Subscription__r.sbqq__Product__r.ProductCode, Subscription__c, Product_Start_Date__c, Product_End_Date__c
    FROM Plan_Specific_Fees__c
    where  subscription__r.sbqq__product__r.productcode in :productKeys
    and member_group__c = :memberGroupId];

    // Exist if no psf exist meeting criteria
    if(scopedPsf.size() == 0)
      return;

    // Map group + sub productcode and gather subscription ids
    for(Plan_Specific_Fees__c tmpPsf : scopedPsf){
      subscriptionIdsInUse.add(tmpPsf.subscription__c);
      parentPsf.put(tmpPsf.member_group__c + '_' + tmpPsf.subscription__r.sbqq__product__r.productcode, tmpPsf);
    }

    // Pull all assets for subscriptions
    List<Asset> subscribedAssets = [select id, product2.productcode, consult_fees__c, sbqq__requiredbysubscription__c, Product2Id
    from asset
    where sbqq__RequiredBySubscription__c in :subscriptionIdsInUse];

    // Map assets for psf-level search
    Map<String, Asset> mappedAssets = new Map<String, Asset>();
    for(Asset tmpAsset : subscribedAssets){
      mappedAssets.put(tmpAsset.sbqq__RequiredBySubscription__c + '_' + tmpAsset.product2.productcode, tmpAsset);
    }
    if(assetProductCodes.size() > 0){
      List<Plan_Specific_Fees__c> existingPsf =
      [SELECT Id, Member_Group__c, Asset__c, Actual_Copay_May_Be_Less__c, Consult_Fee_Initial_Diagnostic_Mbr_Pd__c, Consult_Fee_Initial_Diagnostic_Plan_Pd__c
          , Consult_Fee_Mbr_Pd__c, Consult_Fee_Plan_Pd__c, Consult_Fee_Ongoing_MD_Mbr_Pd__c, Consult_Fee_Ongoing_MD_Plan_Pd__c
          , Consult_Fee_Ongoing_Non_MD_Mbr_Pd__c, Consult_Fee_Ongoing_Non_MD_Plan_Pd__c, DERMConsult_Fee_Mbr_Pd__c, DERMConsult_Fee_Plan_Pd__c
          , TC_Client_Case_Rate_Fee__c, TC_Mbr_Case_Rate_Fee__c, Asset__r.Product2.ProductCode , Subscription__c, Product_Start_Date__c, Product_End_Date__c
      FROM Plan_Specific_Fees__c
      where  member_group__c = :memberGroupId and Asset__r.Product2.ProductCode in :assetProductCodes];

      for(Plan_Specific_Fees__c tmpPsf : existingPsf){
        currentPsf.put(tmpPsf.Member_Group__c + '_' + tmpPsf.Asset__r.Product2.ProductCode, tmpPsf);
      }
      //system.debug('ParentPSF:' + parentPsf.keyset());

      for(String tmpKeyPrefix : parentPsf.keySet()){
        String[] keys = tmpKeyPrefix.split('_'); // 0 = member group id, 1 = parent productcode
        //system.debug('keys: ' + keys);
        List<String> apk = assetKeys.get(keys[1]);
        //system.debug('APK: '+ apk);
        for(String tmpKey : apk){
          string targetKey = keys[0] + '_' + tmpKey;
          if(currentPsf.containsKey(targetKey)){
            system.debug('Found existing psf for: ' + targetKey);
          } else {
            // Grab current 'parent' psf
            Plan_Specific_Fees__c sourcePsf = parentPsf.get(tmpKeyPrefix);
            switch on keys[1] {
              when 'BH'{
                string targetAssetKey = sourcePsf.Subscription__c + '_' + tmpKey;
                Asset targetAsset = mappedAssets.get(targetAssetKey);
                if(targetAsset != null){
                  Plan_Specific_Fees__c newPsf = new Plan_Specific_Fees__c(
                      Member_Group__c = sourcePsf.Member_Group__c,
                      Subscription__c = sourcePsf.subscription__c,
                      Asset__c = targetAsset.Id,
                      Product_Start_Date__c = sourcePsf.Product_Start_Date__c,
                      Product_End_Date__c = sourcePsf.Product_End_Date__c,
                      Actual_Copay_May_Be_Less__c = sourcePsf.Actual_Copay_May_Be_Less__c);
                  switch on tmpKey {
                    when 'BHP1T' {
                      newPsf.Consult_Fee_Mbr_Pd__c = sourcePsf.Consult_Fee_Initial_Diagnostic_Mbr_Pd__c;
                      newPsf.Consult_Fee_Plan_Pd__c = sourcePsf.Consult_Fee_Initial_Diagnostic_Plan_Pd__c;
                    }
                    when 'BHPOT' {
                      newPsf.Consult_Fee_Mbr_Pd__c = sourcePsf.Consult_Fee_Ongoing_MD_Mbr_Pd__c;
                      newPsf.Consult_Fee_Plan_Pd__c = sourcePsf.Consult_Fee_Ongoing_MD_Plan_Pd__c;
                    }
                    when 'BHNPT' {
                      newPsf.Consult_Fee_Mbr_Pd__c = sourcePsf.Consult_Fee_Ongoing_Non_MD_Mbr_Pd__c;
                      newPsf.Consult_Fee_Plan_Pd__c = sourcePsf.Consult_Fee_Ongoing_Non_MD_Plan_Pd__c;
                    }
                  }
                  psfToInsert.add(newPsf);
                } else {
                  system.debug('No asset found for: ' + targetAssetKey);
                }
              }
              when 'MH'{

              }
              when 'TC'{
                string targetAssetKey = sourcePsf.Subscription__c + '_' + tmpKey;
                Asset targetAsset = mappedAssets.get(targetAssetKey);
                if(targetAsset != null){
                  sourcePsf.Asset__c = targetAsset.Id;
                  sourcePsf.Consult_Fee_Mbr_Pd__c = sourcePsf.TC_Mbr_Case_Rate_Fee__c;
                  sourcePsf.Consult_Fee_Plan_Pd__c = sourcePsf.TC_Client_Case_Rate_Fee__c;
                  psfToUpdate.add(sourcePsf);
                } else {
                  system.debug('No asset found for: ' + targetAssetKey);
                }
              }
              when 'DERM'{
                string targetAssetKey = sourcePsf.Subscription__c + '_' + tmpKey;
                Asset targetAsset = mappedAssets.get(targetAssetKey);
                if(targetAsset != null){
                  sourcePsf.Asset__c = targetAsset.Id;
                  sourcePsf.Consult_Fee_Mbr_Pd__c = sourcePsf.DERMConsult_Fee_Mbr_Pd__c;
                  sourcePsf.Consult_Fee_Plan_Pd__c = sourcePsf.DERMConsult_Fee_Plan_Pd__c;
                  psfToUpdate.add(sourcePsf);
                } else {
                  system.debug('No asset found for: ' + targetAssetKey);
                }
              }
            }
          }
        }
      }

      // Commit changes if any exist
      if(psfToUpdate.size() > 0 || psfToInsert.size() > 0) {
        AcctGrpConParsing_Item__c newAgcpi = new AcctGrpConParsing_Item__c(Batch_Time__c = DateTime.now(),
            Batch_Key__c = String.valueOf(DateTime.now().getTime()), Item_Key__c = memberGroupId, Processed__c = true,
        Source__c = 'PSFMIG');
        insert newAgcpi;

        List<AcctGrpConParse_Exception__c> newAgcpe = new List<AcctGrpConParse_Exception__c>();

        if (psfToUpdate.size() > 0) {
          system.debug('PSF to update: ' + psfToUpdate.size());
          Database.SaveResult[] sr = Database.update(psfToUpdate, false);
          for(Database.SaveResult tmpSr : sr){
            if(!tmpSr.isSuccess()){
              for(Database.Error dbe: tmpSr.getErrors()){
                newAgcpe.add(createException(newAgcpi.Id, 'ERROR','Plan_Specific_Fees__c','PSF_UPD', dbe.message));
              }
            }
          }
        }
        if (psfToInsert.size() > 0) {
          system.debug('PSF to insert: ' + psfToInsert.size());
          Database.SaveResult[] sr = Database.insert(psfToInsert, false);
          for(Database.SaveResult tmpSr : sr){
            if(!tmpSr.isSuccess()){
              for(Database.Error dbe: tmpSr.getErrors()){
                newAgcpe.add(createException(newAgcpi.Id, 'ERROR','Plan_Specific_Fees__c','PSF_INS', dbe.message));
              }
            }
          }
        }
        if(newAgcpe.size() > 0)
          Database.insert(newAgcpe, false);
      }
    }
  }
  AcctGrpConParse_Exception__c createException(Id sourceAgcpi, String exType, String sObjectName, String shortDesc, String fullDesc) {
    AcctGrpConParse_Exception__c tmpAgcpe = new AcctGrpConParse_Exception__c();
    tmpAgcpe.Agcpi__c = sourceAgcpi;
    tmpAgcpe.Exception_Type__c = exType.trim().toUpperCase();
    tmpAgcpe.sobject__c = sObjectName.trim().toUpperCase();
    tmpAgcpe.Short_Desc__c = shortDesc.left(64).trim().toUpperCase();
    if (fullDesc.length() > 255) {
      tmpAgcpe.Full_Desc__c = fullDesc.substring(0, 255);
    } else {
      tmpAgcpe.Full_Desc__c = fullDesc;

    }
    return tmpAgcpe;
  }
}