manifest/objects/Acct_Rel__c.object
<CustomObject>
    <description>Models the possible contracts between any two accounts regardless of hierarchy</description>
    <fields>
        <fullName>Benefit_Sponsor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account receiving services</description>
        <inlineHelpText>Lookup the Benefit Sponsor Account (Account receiving services) of the Relationship</inlineHelpText>
        <label>Benefit Sponsor Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Servicing Accounts</relationshipLabel>
        <relationshipName>servicingaccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>REL-{00000000}</displayFormat>
        <label>Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/LVGO__Account__c.object
<CustomObject>
    <fields>
        <fullName>LVGO__TD_Acct_Guid__c</fullName>
        <description>Cloning TDH__Acct_Guid__c from TDH GuidPackage</description>
        <externalId>true</externalId>
        <label>TD Acct Guid</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LVGO__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Payer/ASO</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>TPA</fullName>
                </value>
                <value>
                    <fullName>Self Funded Employer</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Hospital/Health System</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Medicare Advantage</fullName>
                </value>
                <value>
                    <fullName>PBM</fullName>
                </value>
                <value>
                    <fullName>Business Development</fullName>
                </value>
                <value>
                    <fullName>Ops Partner</fullName>
                </value>
                <value>
                    <fullName>Managed Care Organization</fullName>
                </value>
                <value>
                    <fullName>Fully-Insured Employer</fullName>
                    <label>Fully Insured Employer</label>
                </value>
                <value>
                    <fullName>Labor/Pension Fund</fullName>
                </value>
                <value>
                    <fullName>Federal Government</fullName>
                </value>
                <value>
                    <fullName>Other Partner</fullName>
                </value>
                <value>
                    <fullName>Behavioral Health Provider</fullName>
                </value>
                <value>
                    <fullName>Chronic Care Management Organization</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Physician / Hospital</fullName>
                </value>
                <value>
                    <fullName>Referral Agent</fullName>
                </value>
                <value>
                    <fullName>Reseller</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>LV Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/LVGO__Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>LVGO__Account__c</fullName>
        <label>Account</label>
        <referenceTo>LVGO__Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>LVGO_Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LVGO__CloseDate__c</fullName>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LVGO__LeadSource__c</fullName>
        <label>LeadSource</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Undefined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LVGO__StageName__c</fullName>
        <label>Stage</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Discovery</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>Review/Negotiation</fullName>
                </value>
                <value>
                    <fullName>Contracting</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
                <value>
                    <fullName>Closed No Decision</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LVGO__TD_Opp_Guid__c</fullName>
        <description>Cloning TDH__Opp_Guid__c from TDH GuidPackage</description>
        <externalId>true</externalId>
        <label>TD Opp Guid</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LVGO__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Business</fullName>
                </value>
                <value>
                    <fullName>Existing Business</fullName>
                </value>
                <value>
                    <fullName>Re-Sign Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>LV Opportunity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Message_Bus_Toggle__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Enable_MB_LV_Island__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Enable LV Custom Object Creation</inlineHelpText>
        <label>Enable MB LV Island</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_MB_LV_Org__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to Control Message Bus rest callout</description>
        <label>Enable MB LV Org</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_MB__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable MB</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Error_Email_Enable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Error Email Enable</label>
        <type>Checkbox</type>
    </fields>
    <label>Message Bus Toggle</label>
</CustomObject>

manifest/classes/InvokeMessageBusTest.cls
@istest
public class InvokeMessageBusTest {
  @testSetup
  public static void setup() {
    list<Product2> prodlist = new List<Product2>();
    //create an Account
    Account accObj = TestDataFactory.createAccount();
    insert accObj;
    List<Acct_Rel__c> accRelList = new List<Acct_Rel__c>();

    Acct_Rel__c acctRel1 = TestDataFactory.createAccRel(accObj.Id);
    acctRel1.Benefit_Sponsor__c = accObj.Id;
    insert acctRel1;

    LVGO__Account__c lvgoAccount = new LVGO__Account__c();
    lvgoAccount.Name = 'Livongo';
    lvgoAccount.LVGO__TD_Acct_Guid__c = 'FD5E35E0-5175-D1CB-06B8-B48C018EA7C9';
    insert lvgoAccount;

    LVGO__Opportunity__c lvopp = new LVGO__Opportunity__c();
    lvopp.Name = 'Test Opportunity ';
    lvopp.LVGO__StageName__c = 'Prospect';
    lvopp.LVGO__Type__c = 'Renewal';
    lvopp.LVGO__CloseDate__c = Date.today().addDays(1);
    lvopp.LVGO__LeadSource__c = 'Other';
    lvopp.LVGO__Account__c = lvgoAccount.Id;
    lvopp.LVGO__TD_Opp_Guid__c = '416805C1-85B3-D317-121B-B939FA02A645';
    insert lvopp;

    Pricebook2 livongoPricebook = new Pricebook2(
      Name = 'Livongo',
      IsActive = true
    );
    insert livongoPricebook;

    Id StandardPricebook = Test.getStandardPricebookId();
    Pricebook2 TeladocPriceBook = new Pricebook2(
      Name = 'Teladoc Price Book',
      IsActive = true
    );
    insert TeladocPriceBook;
    //create an opportunity record
    Opportunity oppObj = TestDataFactory.createOpportunity(accObj.Id);
    oppObj.Pricebook2Id = TeladocPriceBook.Id;
    oppObj.Benefit_Consultant_Involved_in_Deal__c = 'NO';
    oppObj.LeadSource = 'Sales';
    oppObj.StageName = 'Discovery';
    insert oppObj;

    // create a chronic care Product
    Product2 prod1 = TestDataFactory.createSingleProduct(
      'Prediabetes Management',
      'Chronic Care - Prediabetes',
      'DIABP'
    );
    prodlist.add(Prod1);
    insert Prodlist;

    PricebookEntry[] spbEntry = TestDataFactory.createPriceBookEntries(
      Prodlist,
      StandardPricebook
    );
    insert spbEntry;
    PricebookEntry[] tpbEntry = TestDataFactory.createPriceBookEntries(
      Prodlist,
      TeladocPriceBook.Id
    );
    insert tpbEntry;
  }

  @isTest
  public static void testMBInvoke() {
    Message_Bus_Toggle__c MB = Message_Bus_Toggle__c.getOrgDefaults();
    MB.Enable_MB_LV_Island__c = true;
    MB.Enable_MB_LV_Org__c = false;
    MB.Enable_MB__c = true;
    MB.Error_Email_Enable__c = true;

    insert MB;
    Test.StartTest();
    List<Id> oppIds = new List<Id>();
    Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1 FOR UPDATE];
    opp.StageName = 'Closed Won';
    update Opp;
    oppIds.add(Opp.Id);
    InvokeMessageBus.OppInvokeMB(oppIds);
    Test.StopTest();
  }
  @isTest
  public static void testMBInvokeLVOrg() {
    Test.setMock(HttpCalloutMock.class, new MB_MockIncomingQ_Test());
    Message_Bus_Toggle__c MB = Message_Bus_Toggle__c.getOrgDefaults();
    MB.Enable_MB_LV_Island__c = false;
    MB.Enable_MB_LV_Org__c = true;
    MB.Enable_MB__c = true;
    MB.Error_Email_Enable__c = true;

    insert MB;
    Test.StartTest();
    List<Id> oppIds = new List<Id>();
    Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1 FOR UPDATE];
    opp.StageName = 'Closed Won';
    update Opp;
    oppIds.add(Opp.Id);
    InvokeMessageBus.OppInvokeMB(oppIds);
    Test.StopTest();
  }
}