manifest/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Apttus_DocuApi__DocuSignEnvelope__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Apttus_CMDSign__Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated agreement</description>
        <inlineHelpText>ID of the associated agreement</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipName>DocuSignEnvelopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_DocuApi__Status__c</fullName>
        <description>Envelope status from DocuSign</description>
        <inlineHelpText>Envelope status from DocuSign</inlineHelpText>
        <label>Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>DocuSign Envelope</label>
    <nameField>
        <label>DocuSign Envelope Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DocuSign Envelopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/classes/APTS_formData_Test.cls
@isTest
public class APTS_formData_Test {
    
    @isTest
    Public Static void testFormdate(){
        Apttus__APTS_Agreement__c agmt = new Apttus__APTS_Agreement__c();
        agmt.Name = 'Test - Agmt';
        insert agmt;
        
        Apttus_DocuApi__DocuSignEnvelope__c env = new Apttus_DocuApi__DocuSignEnvelope__c();
        env.Name = '4917f32e-ed9d-49f7-bf9e-ac0b7dadc89a';
        env.Apttus_CMDSign__Agreement__c = agmt.Id;
        env.Apttus_DocuApi__Status__c = 'Sent';
        insert env;
        
        Apttus_DocuApi__DocuSignEnvelope__c updateEnv = [Select Id, Name from Apttus_DocuApi__DocuSignEnvelope__c 
                                                        where Id =:env.Id];
        updateEnv.Apttus_DocuApi__Status__c = 'completed';
        update updateEnv;
        
        Test.startTest();
       
        Test.setMock(HttpCalloutMock.class, new APTS_getformDatamock_Test());        
        
        APTS_GetFormData.getFormData(new List<Id>{updateEnv.Id});
        System.assertNotEquals(null, updateEnv.Id, 'Records found successfully');
        Test.stopTest();
    }
    
}