manifest/objects/Apttus__AgreementLineItem__c.object
<CustomObject>
    <description>Represents a product or service line item associated with an agreement</description>
    <fields>
        <fullName>APTS_Consult_Fee__c</fullName>
        <formula>APTS_Quote_Line__r.L2O_Consult_Fee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Consult Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_Fee_Code__c</fullName>
        <formula>APTS_Quote_Line__r.L2O_Fee_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fee Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Quote_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Agreement Line Items (Quote Line)</relationshipLabel>
        <relationshipName>Agreement_Line_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_Required_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RequiredBy</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Agreement Line Items (RequiredBy)</relationshipLabel>
        <relationshipName>Agreement_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__AgreementId__c</fullName>
        <description>ID of the associated agreement</description>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Agreement Line Items</relationshipLabel>
        <relationshipName>AgreementLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Agreement Line Item</label>
    <nameField>
        <displayFormat>AL-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__ProductOption__c.object
<CustomObject>
    <customHelpPage>SBQQ__ProductOptionHelp</customHelpPage>
    <description>Option for a configurable product.</description>
    <label>Product Option</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__ProductOption__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product option that generated this line (if any).</description>
        <inlineHelpText>Product option that generated this line (if any).</inlineHelpText>
        <label>Product Option</label>
        <referenceTo>SBQQ__ProductOption__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/classes/APTS_SetConsultFee_Test.cls
/*************************************************************************     
* @description This class is used as Test class for APTS_SetConsultAndFeeCode apex class
* @param NA
* @Author InfoSys Developer
**************************************************************************/
@isTest
public class APTS_SetConsultFee_Test{
    public static Id pricebookId = Test.getStandardPricebookId();
    
    @testSetup
    static void createdata()
    {
        Test.startTest();
        List<Account> accountList= APTS_TestDataUtility_Test.createAccount(true,1);
        Product2 parentProduct=new Product2();
        Apttus__APTS_Agreement__c testagreementrec=new Apttus__APTS_Agreement__c();
        Account testaccount=new Account();   
        Opportunity testopportunity=new Opportunity();  
        List<Product2> childproducts=new List<Product2>(); 
        Id quoteId;
        List<Opportunity> oppList = APTS_TestDataUtility_Test.createOpportunity(true,accountList); 
        List<Contact> conList =  APTS_TestDataUtility_Test.createContact(true,accountList); 
        APTS_TestDataUtility_Test.createContactRoles(true,oppList,conList[0].id);     
        List<SBQQ__Quote__c> quotelist=APTS_TestDataUtility_Test.createQuote(true,oppList);
        for(SBQQ__Quote__c quoterec:quotelist)
        {
            quoteId=quoterec.Id;   
        }
        List<Product2> testproducts=APTS_TestDataUtility_Test.createtestproducts();
        for(Product2 parprod:testproducts)
        {
            if(parprod.Name=='Mental Health Care (US)')
            {
                parentProduct=parprod;   
            }
            else
            {
                childproducts.add(parprod);   
            }
        }
        List<SBQQ__ProductOption__c> testproductoptions=APTS_TestDataUtility_Test.createproductoptions(parentProduct,childproducts);
        List<SBQQ__QuoteLine__c> testQuoteLines=APTS_TestDataUtility_Test.createquotelines(quoteId,parentProduct.Id,testproductoptions);
        for(Opportunity opprec:oppList)
        {
            testopportunity=opprec;  
        }
        for(Account accrec:accountList)
        {
            testaccount=accrec;   
        }
        testagreementrec=APTS_TestDataUtility_Test.createagreement(quoteId,testopportunity.Id,testaccount.Id);
        List<Apttus__AgreementLineItem__c> testagreementlineitems=APTS_TestDataUtility_Test.createagreementlineitem(testagreementrec.Id,testQuoteLines);
        System.assertNotEquals(null, testagreementlineitems, 'Success');
        Test.stopTest();
    } 
    
    @isTest
    static void callmethod() {
        Test.startTest();
        List<Apttus__AgreementLineItem__c> testdata=[Select Id,APTS_Consult_Fee__c,APTS_Fee_Code__c,APTS_Required_By__c,Apttus__AgreementId__c,APTS_Quote_Line__c from Apttus__AgreementLineItem__c];
        List<List<Apttus__AgreementLineItem__c>> classtestdata=new List<List<Apttus__AgreementLineItem__c>>();
        classtestdata.add(testdata);
        APTS_SetConsultFeeAndFeeCode.setconsultfeefeecode(classtestdata);
        System.assertNotEquals(null, classtestdata, 'Success');
        Test.stopTest();
    }
}