manifest/objects/Apttus__AgreementLineItem__c.object
<CustomObject>
    <description>Represents a product or service line item associated with an agreement</description>
    <fields>
        <fullName>Apttus__AgreementId__c</fullName>
        <description>ID of the associated agreement</description>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Agreement Line Items</relationshipLabel>
        <relationshipName>AgreementLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the selected product or service</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Agreement Line Items</relationshipLabel>
        <relationshipName>AgreementLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agreement Line Item</label>
    <nameField>
        <displayFormat>AL-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Product_Family__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Product Families</relationshipLabel>
        <relationshipName>Product_Families</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Family_Name__c</fullName>
        <label>Product Family Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Hardware</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>License Platform</fullName>
                </value>
                <value>
                    <fullName>Expert Medical Services</fullName>
                </value>
                <value>
                    <fullName>Chronic Care Services</fullName>
                </value>
                <value>
                    <fullName>Virtual Care Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Family</label>
    <nameField>
        <displayFormat>PF-{0000}</displayFormat>
        <label>Product Family</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/classes/ProductFamily_Test.cls
@isTest
public class ProductFamily_Test {
    
    @testsetup Static void productFamilydata(){
        
        List<String> productList = New List<String>{'License Platform', 'Behavioral Health', 'Diabetes', 'Hardware', 'Software', 'Services',
            'Expert Medical Services'};
            List<Product2> prdList = New List<Product2>();
        for(integer localCount=0; localCount<7; localCount++){
            Product2 prd = New Product2();
            prd.Name = productList.get(localCount)+'Product';
            prd.Family = productList.get(localCount);
            prdList.add(prd);
        }
        insert prdList;
        System.assertNotEquals(null, prdList, 'Success');
        
        List<Apttus__APTS_Agreement__c> agrList = New List<Apttus__APTS_Agreement__c>();
        List<Apttus__AgreementLineItem__c> agrLineItem = New List<Apttus__AgreementLineItem__c>();
        List<Product_Family__c> prdFamList = New List<Product_Family__c>();
        for(integer i=0; i<2; i++){
            Apttus__APTS_Agreement__c agr = New Apttus__APTS_Agreement__c(Name='Test Agreement'+i);
            AgrList.add(agr);                       
        }
        insert agrList;
        System.assertNotEquals(null, agrList, 'Success');
        
        for(integer m=0; m<agrList.size(); m++){
            for(integer j=0; j<7; j++){
                Apttus__AgreementLineItem__c agrLine = New Apttus__AgreementLineItem__c();
                agrLine.Apttus__AgreementId__c = agrList.get(m).Id;
                agrLine.Apttus__ProductId__c = prdList.get(j).Id;
                agrLineItem.add(agrLine);
            }
            for(integer k=0; k<7; k++){
                Product_Family__c prdFam = new Product_Family__c();
                prdFam.Agreement__c = agrList.get(m).Id;
                prdFam.Product_Family_Name__c = prdList.get(k).Name;
                prdFamList.add(prdFam);
            } 
        }
        
        insert agrLineItem;
        insert prdFamList;
        System.assertNotEquals(null, agrLineItem, 'Success');
        System.assertNotEquals(null, prdFamList, 'Success');
        
    }
    
    @isTest
   Private static void productFamilyTest(){        
                
        Test.startTest();
        
        List<Apttus__AgreementLineItem__c> agrLineItem = [select Id, Name,Apttus__AgreementId__c,
                                        Apttus__ProductId__c
                                        from Apttus__AgreementLineItem__c];        
       ProductFamilyHandler.createProductfamilies(agrLineItem);
       ProductFamilyHandler.deleteProductfamilies(agrLineItem);
       System.assertNotEquals(null, agrLineItem, 'Records found successfully');
        
        Test.stopTest();
    }
}