manifest/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Consult_Fees__c</fullName>
        <label>Consult Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Number_of_Lives__c</fullName>
        <label>Number of Lives</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__RequiredBySubscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The parent Subscription. If populated, this Asset is a child in a bundle.</inlineHelpText>
        <label>Required By Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Assets (Required By Subscription)</relationshipLabel>
        <relationshipName>ChildAssets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscribed Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Teladoc_Net_Fee__c</fullName>
        <label>Teladoc Net Fee</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Mbr_Group__c.object
<CustomObject>
    <fields>
        <fullName>Active_Date__c</fullName>
        <description>Date Group was built in Admin</description>
        <inlineHelpText>Date Group was built in Admin</inlineHelpText>
        <label>Active Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <description>Account that the Group is created</description>
        <inlineHelpText>Account that the Group is created</inlineHelpText>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Member Groups</relationshipLabel>
        <relationshipName>Member_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Enter a descriptive Member Group Name.</description>
        <inlineHelpText>Enter a descriptive Member Group Name.</inlineHelpText>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Use this as a backend field to identify the source of member group record</description>
        <inlineHelpText>Use this as a backend field to identify the source of member group record</inlineHelpText>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Data_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Group Status</description>
        <inlineHelpText>Group Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>PENDING</fullName>
                    <default>true</default>
                    <label>PENDING</label>
                </value>
                <value>
                    <fullName>TERMED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Member Group</label>
    <nameField>
        <displayFormat>MG-{00000000}</displayFormat>
        <label>Member Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Plan_Specific_Fees__c.object
<CustomObject>
    <fields>
        <fullName>Consult_Fee_Mbr_Pd__c</fullName>
        <label>Consult Fee - Mbr Pd</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Consult_Fee_Plan_Pd__c</fullName>
        <label>Consult Fee - Plan Pd</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Consult_Frequency__c</fullName>
        <label>Consult Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Per Year</fullName>
                </value>
                <value>
                    <fullName>Per Life</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Consults_per_Family__c</fullName>
        <label>Consults per Family</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Member_Group__c</fullName>
        <label>Member Group</label>
        <referenceTo>Mbr_Group__c</referenceTo>
        <relationshipLabel>Plan-Specific Fees By Product</relationshipLabel>
        <relationshipName>Plan_Specific_Fees_By_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Start_Date__c</fullName>
        <label>Product Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Plan-Specific Fees By Product</relationshipLabel>
        <relationshipName>Plan_Specific_Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Teladoc_Net_Fee__c</fullName>
        <formula>Product_Under_Contract__r.Teladoc_Net_Fee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Teladoc Net Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Plan-Specific Fees By Product</label>
    <nameField>
        <displayFormat>PSF-{0000000}</displayFormat>
        <label>Plan Fees ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan-Specific Fees By Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>Consult_Fees__c</fullName>
        <label>Consult Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account that owns this subscription. This relationship is used for volume discount calculations.</description>
        <inlineHelpText>Account that owns this subscription. This relationship is used for volume discount calculations.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product used to sell this subscription.</description>
        <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity of this subscription product purchased by the customer.</description>
        <inlineHelpText>Quantity of this subscription product purchased by the customer.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Active</fullName>
                    <default>true</default>
                    <label>Not Yet Active</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/globalValueSets/Data_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>HUB</fullName>
        <default>true</default>
        <label>HUB</label>
    </customValue>
    <customValue>
        <fullName>TD</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>LVGO</fullName>
    </customValue>
    <customValue>
        <fullName>GCRM</fullName>
    </customValue>
    <masterLabel>Data Source</masterLabel>
</GlobalValueSet>

manifest/classes/MassivePsfCreationButtonControll_Test.cls
@IsTest
private class MassivePsfCreationButtonControll_Test {
    @TestSetup
    static void testsetup() {
        Account umrAcct = TestDataFactory.createUMR();           
        List<Account> acct = new List<Account>();
        Account a = new Account(
            Name = 'Test01',
            Source__c = 'HUB'
        );
        acct.add(a);
        
        insert acct;
        

        List<Mbr_Group__c> mg = new List<Mbr_Group__c>();
        Mbr_Group__c grp = new Mbr_Group__c(
            Name__c = 'testgrp1',
            Client_Account__c = a.Id,
            Status__c = 'ACTIVE',
            Active_Date__c = Date.today()
        );
        mg.add(grp);
        Mbr_Group__c grp2 = new Mbr_Group__c(
            Name__c = 'testgrp2',
            Client_Account__c = a.Id,
            Status__c = 'ACTIVE',
            Active_Date__c = Date.today()
        );
        mg.add(grp2);
        insert mg;
        
        List<Product2> pd = new List<Product2>();    
        
        Product2 prod = new Product2(
            Name = 'Dermatology',
            Family = 'Dermatology',
            ProductCode = 'DERM',
            IsActive = true
        );
        pd.add(prod);
        
        Product2 prod2 = new Product2(
            Name = 'Dermatology',
            Family = 'Dermatology',
            ProductCode = 'DERMFEE',
            IsActive = true
        );
        pd.add(prod2);
        
        Product2 prod3 = new Product2(
            Name = 'Tobacco Cessation',
            Family = 'Tobacco Cessation',
            ProductCode = 'TCPROGFEE',
            IsActive = true
        );
        pd.add(prod3);
        
        
        Product2 prod3_1 = new Product2(
            Name = 'Tobacco Cessation',
            Family = 'Tobacco Cessation',
            ProductCode = 'TCPROGFEE',
            IsActive = true
        );
        pd.add(prod3_1);
        
        Product2 prod4 = new Product2(
            Name = 'General Medical',
            Family = 'General Medical',
            ProductCode = 'GM',
            IsActive = true
        );
        pd.add(prod4);
        
        Product2 prod5 = new Product2(
            Name = 'Behavioral Health',
            Family = 'Behavioral Health',
            ProductCode = 'BHNPT',
            IsActive = true
        );
        pd.add(prod5);
        
        Product2 prod6 = new Product2(
            Name = 'Behavioral Health',
            Family = 'Behavioral Health',
            ProductCode = 'BHP1T',
            IsActive = true
        );
        pd.add(prod6);
        
        Product2 prod7 = new Product2(
            Name = 'Behavioral Health',
            Family = 'Behavioral Health',
            ProductCode = 'BHPOT',
            IsActive = true
        );
        pd.add(prod7);
        
        Product2 prod8 = new Product2(
            Name = 'Behavioral Health',
            Family = 'Behavioral Health',
            ProductCode = 'BH',
            IsActive = true
        );
        pd.add(prod8);
        
        insert pd;  
        
        List<SBQQ__Subscription__c> subL = new List<SBQQ__Subscription__c>();
 
        SBQQ__Subscription__c sub = new SBQQ__Subscription__c(
            SBQQ__Account__c = a.Id,
            Status__c = 'Active',
            SBQQ__Quantity__c = 500,
            Consult_Fees__c = 0.90,
            SBQQ__Product__c = prod.Id
        );
        subL.add(sub);
        
        SBQQ__Subscription__c sub2 = new SBQQ__Subscription__c(
            SBQQ__Account__c = a.Id,
            Status__c = 'Active',
            SBQQ__Quantity__c = 500,
            Consult_Fees__c = 0.90,
            SBQQ__Product__c = prod3.Id
        );
        subL.add(sub2);
        
        SBQQ__Subscription__c sub3 = new SBQQ__Subscription__c(
            SBQQ__Account__c = a.Id,
            Status__c = 'Active',
            SBQQ__Quantity__c = 500,
            Consult_Fees__c = 0.90,
            SBQQ__Product__c = prod4.Id
        );
        subL.add(sub3);
        
        SBQQ__Subscription__c sub4 = new SBQQ__Subscription__c(
            SBQQ__Account__c = a.Id,
            Status__c = 'Active',
            SBQQ__Quantity__c = 500,
            Consult_Fees__c = 0.90,
            SBQQ__Product__c = prod8.Id
        );
        subL.add(sub4);
    
        insert subL;
        
        
        Plan_Specific_Fees__c gpRec = new Plan_Specific_Fees__c(
            Member_Group__c = grp.Id,
            Consult_Fee_Mbr_Pd__c = 0.80,
            Consults_per_Family__c = 4,
            Consult_Fee_Plan_Pd__c = 0.80,
            Consult_Frequency__c = 'Per Year',
            Subscription__c = sub.Id,
            Product_Start_Date__c  = Date.Today()
            
        );
        insert gpRec;
     
        
		List<Asset> assetL = new List<Asset>();
        
        Asset ast = new Asset(
            AccountId = a.Id,
            Consult_Fees__c = 0.30,
            Number_of_Lives__c = null,
            Teladoc_Net_Fee__c = null,
            InstallDate = Date.today(),
            Product2Id = prod2.Id,
            Name = 'test asset',
            SBQQ__RequiredBySubscription__c = sub.Id
        );
        assetL.add(ast);
        
        Asset ast2 = new Asset(
            AccountId = a.Id,
            Consult_Fees__c = 0.60,
            Number_of_Lives__c = 1000,
            Teladoc_Net_Fee__c = 0.80,
            InstallDate = Date.today(),
            Product2Id = prod3.Id,
            Name = 'Consult Fee- Psych/MD-ONGOING-Total',
            SBQQ__RequiredBySubscription__c = sub2.Id
        );
        assetL.add(ast2);
        
        Asset ast3 = new Asset(
            AccountId = a.Id,
            Consult_Fees__c = 0.60,
            Number_of_Lives__c = 1000,
            Teladoc_Net_Fee__c = 0.80,
            InstallDate = Date.today(),
            Product2Id = prod5.Id,
            Name = 'test asset',
            SBQQ__RequiredBySubscription__c = sub4.Id
        );
        assetL.add(ast3);
        
        Asset ast4 = new Asset(
            AccountId = a.Id,
            Consult_Fees__c = 0.60,
            Number_of_Lives__c = 1000,
            Teladoc_Net_Fee__c = 0.80,
            InstallDate = Date.today(),
            Product2Id = prod6.Id,
            Name = 'test asset',
            SBQQ__RequiredBySubscription__c = sub4.Id
        );
        assetL.add(ast4);
        
        Asset astt = new Asset(
            AccountId = a.Id,
            Consult_Fees__c = 0.60,
            Number_of_Lives__c = 1000,
            Teladoc_Net_Fee__c = 0.80,
            InstallDate = Date.today(),
            Product2Id = prod7.Id,
            Name = 'test asset',
            SBQQ__RequiredBySubscription__c = sub4.Id
        );
        assetL.add(astt);
        
        insert assetL;
    }
    
    @IsTest
    static void webServiceCallTest() {
        SBQQ__Subscription__c subBH = [SELECT Id FROM SBQQ__Subscription__c WHERE SBQQ__Product__r.ProductCode ='BH'];
        
        MassPsfCreationButtonController.callMassiveCreation(subBH.Id);
    }
    
    @isTest
    static void countRecord() {
        SBQQ__Subscription__c sub = [SELECT id FROM SBQQ__Subscription__c LIMIT 1];
        MassPsfCreationButtonController.doCount(sub.Id);
    }
}