manifest/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Number_of_Lives__c</fullName>
        <label>Number of Lives</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscribed Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Teladoc_Net_Fee__c</fullName>
        <label>Teladoc Net Fee</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Mbr_Group__c.object
<CustomObject>
    <label>Member Group</label>
    <nameField>
        <displayFormat>MG-{00000000}</displayFormat>
        <label>Member Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Mbr_Group_Role__c.object
<CustomObject>
    <fields>
        <fullName>Mbr_Group__c</fullName>
        <description>SF Record name of the Group</description>
        <inlineHelpText>SF Record name of the Group</inlineHelpText>
        <label>Member Group</label>
        <referenceTo>Mbr_Group__c</referenceTo>
        <relationshipLabel>Member Group Roles</relationshipLabel>
        <relationshipName>Member_Group_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Member Group Role</label>
    <nameField>
        <displayFormat>MGR-{00000000}</displayFormat>
        <label>Member Group Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Group Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product used to sell this subscription.</description>
        <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/classes/psfUploadController_Test.cls
@isTest
private class psfUploadController_Test {
  @TestSetup
  public static void setup() {
    Account umrAcct = TestDataFactory.createUMR();
    List<Account> acct = new List<Account>();
    Account a = TestDataFactory.createAccount('Test01');
    acct.add(a);
    List<Mbr_Group__c> mg = TestDataFactory.createMbrGroup(a.Id);
    Mbr_Group_Role__c r = TestDataFactory.createGroupRole(
      mg[0].Id,
      'Payer',
      a.Id,
      null
    );
    insert r;
    List<Product2> pd = new List<Product2>();
    Product2 prod8 = TestDataFactory.CreateProductWithDynamicVals(
      'Nutrition',
      'Nutrition',
      'NUT'
    );
    pd.add(prod8);
    Product2 prod9 = TestDataFactory.CreateProductWithDynamicVals(
      'NUTFEE',
      'Nutrition',
      'NUTFEE'
    );
    pd.add(prod9);
    Product2 prod5 = TestDataFactory.CreateProductWithDynamicVals(
      'Behavioral Health',
      'Behavioral Health',
      'BHNPT'
    );
    pd.add(prod5);
    Product2 prod6 = TestDataFactory.CreateProductWithDynamicVals(
      'Behavioral Health',
      'Behavioral Health',
      'BHP1T'
    );
    pd.add(prod6);
    Product2 prod7 = TestDataFactory.CreateProductWithDynamicVals(
      'Behavioral Health',
      'Behavioral Health',
      'BHPOT'
    );
    pd.add(prod7);
    Product2 prod4 = TestDataFactory.CreateProductWithDynamicVals(
      'Behavioral Health',
      'Behavioral Health',
      'BH'
    );
    pd.add(prod4);
    insert pd;

    SBQQ__Subscription__c sub = TestDataFactory.createSBQQSubscripWithProdNoInsert(
      a.Id,
      prod8.Id
    );
    insert sub;

    SBQQ__Subscription__c sub2 = TestDataFactory.createSBQQSubscripWithProdNoInsert(
      a.Id,
      prod4.Id
    );
    insert sub2;

    List<Asset> assetL = new List<Asset>();
    Asset ast = TestDataFactory.createAssetNoInsert(
      'test asset',
      60,
      a.Id,
      null,
      prod5.Id,
      sub.Id
    );
    ast.Number_of_Lives__c = null;
    ast.Teladoc_Net_Fee__c = null;
    ast.InstallDate = Date.today();
    assetL.add(ast);

    Asset ast3 = TestDataFactory.createAssetNoInsert(
      'test asset',
      60,
      a.Id,
      null,
      prod5.Id,
      sub2.Id
    );
    ast3.Number_of_Lives__c = 1000;
    ast3.Teladoc_Net_Fee__c = 0.80;
    ast3.InstallDate = Date.today();
    assetL.add(ast3);

    Asset ast4 = TestDataFactory.createAssetNoInsert(
      'test asset',
      60,
      a.Id,
      null,
      prod6.Id,
      sub2.Id
    );
    ast4.Number_of_Lives__c = 1000;
    ast4.Teladoc_Net_Fee__c = 0.80;
    ast4.InstallDate = Date.today();
    assetL.add(ast4);

    Asset astt = TestDataFactory.createAssetNoInsert(
      'test asset',
      60,
      a.Id,
      null,
      prod7.Id,
      sub2.Id
    );
    astt.Number_of_Lives__c = 1000;
    astt.Teladoc_Net_Fee__c = 0.80;
    astt.InstallDate = Date.today();
    assetL.add(astt);

    insert assetL;
  }

  static testMethod void testfileupload() {
    Test.startTest();
    Mbr_Group__c grp = [SELECT Id FROM Mbr_Group__c LIMIT 1];
    SBQQ__Subscription__c sub = [
      SELECT Id
      FROM SBQQ__Subscription__c
      WHERE Sbqq__product__r.productCode = 'NUT'
    ];
    SBQQ__Subscription__c sub1 = [
      SELECT Id
      FROM SBQQ__Subscription__c
      WHERE Sbqq__product__r.productCode = 'BH'
    ];
    String str =
      'Member Group ID,Product Start Date,Actual Copay May Be Less,Consult Fee Plan Paid,Consult Fee Member Paid,Subscription ID,Asset Product Code\n' +
      grp.Id +
      ',12/1/2021,true,85,0,' +
      sub.Id +
      ',DERMFEE\n' +
      grp.Id +
      ',12/1/2021,true,60,0,' +
      sub1.Id +
      ',BHNPT\n' +
      grp.Id +
      ',12/1/2021,true,60,0,' +
      sub1.Id +
      ',BHP1T\n' +
      grp.Id +
      ',12/1/2021,true,60,0,' +
      sub1.Id +
      ',BHPOT\n' +
      grp.Id +
      ',12/1/2021,true,600,0,' +
      sub1.Id +
      ',BHNPT\n' +
      grp.Id +
      ',12/1/2021,true,60,0,' +
      sub1.Id +
      ',BHP1T\n' +
      grp.Id +
      ',12/1/2021,true,60,0,' +
      sub1.Id +
      ',BHPOT';

    ContentVersion contentVersionInsert = TestDataFactory.createContentVersion(
      str
    );
    insert contentVersionInsert;
    ContentVersion contentVersionSelect = [
      SELECT ContentDocumentId
      FROM ContentVersion
      WHERE Id = :contentVersionInsert.Id
      LIMIT 1
    ];

    psfUploadController.readCSVFile(contentVersionSelect.ContentDocumentId);
    Test.stopTest();
  }
}