manifest/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Consult_Fees__c</fullName>
        <label>Consult Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fee_Type__c</fullName>
        <label>Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PEPM</fullName>
                </value>
                <value>
                    <fullName>PMPM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__RequiredByAsset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The parent Asset. If populated, this Asset is a child in a bundle.</inlineHelpText>
        <label>Required By Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Assets (Required By Asset)</relationshipLabel>
        <relationshipName>ChildAssets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__RequiredByProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent Product of this Asset.</description>
        <inlineHelpText>Parent Product of this Asset.</inlineHelpText>
        <label>Parent Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Child Assets</relationshipLabel>
        <relationshipName>ChildAssets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__RequiredBySubscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The parent Subscription. If populated, this Asset is a child in a bundle.</inlineHelpText>
        <label>Required By Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Assets (Required By Subscription)</relationshipLabel>
        <relationshipName>ChildAssets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionStartDate__c</fullName>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscribed Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>Consult_Fees__c</fullName>
        <label>Consult Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Membership_Fee__c</fullName>
        <description>New field created to allow editing by account management for price changes.  A workflow will be built to enter the value when Subscription is originally created.</description>
        <inlineHelpText>New field created to allow editing by account management for price changes.  A workflow will be built to enter the value when Subscription is originally created.</inlineHelpText>
        <label>Current Membership Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fee_Type__c</fullName>
        <description>Keeping the Pikclist optinos un restricted as Process Builder copies the value from Opportunity Fee Type which might be different than</description>
        <inlineHelpText>Which Fee Type relates to this Subscription</inlineHelpText>
        <label>Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PEPM</fullName>
                </value>
                <value>
                    <fullName>PMPM</fullName>
                </value>
                <value>
                    <fullName>Case Rate</fullName>
                </value>
                <value>
                    <fullName>N/A (?)</fullName>
                </value>
                <value>
                    <fullName>PPPM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account that owns this subscription. This relationship is used for volume discount calculations.</description>
        <inlineHelpText>Account that owns this subscription. This relationship is used for volume discount calculations.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product used to sell this subscription.</description>
        <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionStartDate__c</fullName>
        <description>Matches the quote line start date by default. If blank, it will match the contract start date.</description>
        <inlineHelpText>Matches the quote line start date by default. If blank, it will match the contract start date.</inlineHelpText>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <description>Termination date for subscription</description>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/classes/subOptionsController.cls
public without sharing class subOptionsController {
  public class subAssetWrapper {
    @auraEnabled
    public String subId { get; set; }
    @auraEnabled
    public String productCode { get; set; }
    @auraEnabled
    public String feeType { get; set; }
    @auraEnabled
    public String membershipFee { get; set; }
    @auraEnabled
    public String asset { get; set; }

    public subAssetWrapper(
      String subId,
      String productCode,
      String feeType,
      String membershipFee,
      String asset
    ) {
      this.subId = subId;
      this.productCode = productCode;
      this.feeType = feeType;
      this.membershipFee = membershipFee;
      this.asset = asset;
    }
  }

  @auraEnabled
  public static String accountName(String parentGUID) {
    try {
      Account acct = [SELECT Name FROM Account WHERE Guid__c = :parentGUID];
      return acct.Name;
    } catch (exception e) {
      return null;
    }
  }

  @auraEnabled
  public static List<subAssetWrapper> createSubAsset(String parentGUID) {
    List<subAssetWrapper> subAssetList = new List<subAssetWrapper>();
    for (SBQQ__Subscription__c sub : [
      SELECT
        Id,
        Fee_Type__c,
        SBQQ__Product__r.ProductCode,
        Current_Membership_Fee__c,
        (SELECT Consult_Fees__c, Product2.ProductCode FROM SBQQ__ChildAssets__r)
      FROM SBQQ__Subscription__c
      WHERE
        SBQQ__Account__r.Guid__c = :parentGUID
        AND (SBQQ__SubscriptionStartDate__c <= TODAY
        OR Termination_Date__c = NULL)
      ORDER BY SBQQ__SubscriptionStartDate__c DESC
    ]) {
      Boolean hasAsset = false;
      String BHP1T;
      String BHPOT;
      String BHNPT;
      String assetString;
      for (Asset asset : sub.SBQQ__ChildAssets__r) {
        hasAsset = true;
        if (sub.SBQQ__Product__r.ProductCode != 'BH') {
          assetString = ('Total Fee: ' + asset.Consult_Fees__c);
          subAssetList.add(
            new subAssetWrapper(
              sub.Id,
              sub.SBQQ__Product__r.ProductCode,
              sub.Fee_Type__c,
              string.valueOf(sub.Current_Membership_Fee__c),
              assetString
            )
          );
        } else {
          if (asset.Product2.ProductCode == 'BHP1T') {
            BHP1T = string.valueOf(asset.Consult_Fees__c);
          } else if (asset.Product2.ProductCode == 'BHPOT') {
            BHPOT = string.valueOf(asset.Consult_Fees__c);
          } else if (asset.Product2.ProductCode == 'BHNPT') {
            BHNPT = string.valueOf(asset.Consult_Fees__c);
          }
          if (BHP1T != null && BHPOT != null && BHNPT != null) {
            assetString =
              '[BHP1T: ' +
              BHP1T +
              '], [ BHPOT: ' +
              BHPOT +
              '], [BHNPT: ' +
              BHNPT +
              ']';
            subAssetList.add(
              new subAssetWrapper(
                sub.Id,
                sub.SBQQ__Product__r.ProductCode,
                sub.Fee_Type__c,
                string.valueOf(sub.Current_Membership_Fee__c),
                assetString
              )
            );
          }
        }
      }
      if (!hasAsset) {
        assetString = 'No Asset';
        subAssetList.add(
          new subAssetWrapper(
            sub.Id,
            sub.SBQQ__Product__r.ProductCode,
            sub.Fee_Type__c,
            string.valueOf(sub.Current_Membership_Fee__c),
            assetString
          )
        );
      }
    }
    return subAssetList;
  }
}