manifest/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscribed Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Mbr_Group__c.object
<CustomObject>
    <fields>
        <fullName>Disable_Flow__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable Flow</label>
        <type>Checkbox</type>
    </fields>
    <label>Member Group</label>
    <nameField>
        <displayFormat>MG-{00000000}</displayFormat>
        <label>Member Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Plan_Specific_Fees__c.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Plan-Specific Fees By Product (Asset)</relationshipLabel>
        <relationshipName>Plan_Specific_Fees_By_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan-Specific Fees By Product</label>
    <nameField>
        <displayFormat>PSF-{0000000}</displayFormat>
        <label>Plan Fees ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan-Specific Fees By Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Disable_Flow__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable Flow</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/PSF_Permission_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuration to allow deletion of PSF records</description>
    <fields>
        <fullName>User_Permission__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Group of users that are allowed to delete PSF records.</description>
        <label>User Permission</label>
        <type>Checkbox</type>
    </fields>
    <label>PSF Permission Setting</label>
</CustomObject>

manifest/objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/classes/PSF_Trg_Test.cls
@IsTest
private class PSF_Trg_Test {
  @IsTest
  static void Test_Psf_Duplicate_Prevention() {
    Account umrAcct = TestDataFactory.createUMR();
    Account tmpAcct = TestDataFactory.createTempAcct();
    Mbr_Group__c tmpGrp = TestDataFactory.createSingleMbrGroup(tmpAcct.Id);
    Contract tmpContract = TestDataFactory.createContract(tmpAcct.Id);
    SBQQ__Subscription__c tmpSubscription = TestDataFactory.createSBQQSubscription(
      tmpAcct.Id,
      tmpContract.Id
    );
    Plan_Specific_Fees__c tmpPsf = TestDataFactory.createSinglePlanSpecificFees(
      tmpGrp.Id,
      tmpSubscription.Id
    );
  }

  @IsTest
  static void Test_Psf_flowTest() {
    PSF_Permission_Setting__c objDS = new PSF_Permission_Setting__c(
      SetupOwnerId = UserInfo.getUserId(),
      User_Permission__c = true
    );
    insert objDS;
    Account umrAcct = TestDataFactory.createUMR();
    Account tmpAcct = TestDataFactory.createTempAcct();
    Mbr_Group__c tmpGrp = TestDataFactory.createSingleMbrGroup(tmpAcct.Id);
    Product2 prod = TestDataFactory.createSingleProduct();
    SBQQ__Subscription__c sub = TestDataFactory.createSBQQSubscripWithProd(
      tmpAcct.Id,
      prod.Id
    );
    Plan_Specific_Fees__c tmpPsf = TestDataFactory.createSinglePlanSpecificFees(
      tmpGrp.Id,
      sub.Id
    );
    Mbr_Group__c tmpGrp2 = [SELECT Disable_Flow__c FROM Mbr_Group__c];
    system.assertEquals(true, tmpGrp2.Disable_Flow__c);
    delete tmpPsf;
    Mbr_Group__c tmpGrp3 = [SELECT Disable_Flow__c FROM Mbr_Group__c];
    system.assertEquals(false, tmpGrp3.Disable_Flow__c);
  }

  @IsTest
  static void Test_Psf_Errors() {
    Account umrAcct = TestDataFactory.createUMR();
    Account tmpAcct = TestDataFactory.createTempAcct();
    Mbr_Group__c tmpGrp = TestDataFactory.createSingleMbrGroup(tmpAcct.Id);
    Product2 prod = TestDataFactory.createSingleProduct();
    Asset tempAss = TestDataFactory.createSingleAsset(tmpAcct.Id, prod.Id);
    SBQQ__Subscription__c sub = TestDataFactory.createSBQQSubscripWithProd(
      tmpAcct.Id,
      prod.Id
    );
    try {
      Plan_Specific_Fees__c tmpPsf = TestDataFactory.createSinglePlanSpecificFees(
        tmpGrp.Id,
        sub.Id
      );
      tmpPsf.Asset__c = tempAss.Id;
      upsert tmpPsf;
    } catch (Exception ex) {
    }
  }
}