manifest/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Consult_Fees__c</fullName>
        <label>Consult Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fee_Type__c</fullName>
        <label>Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PEPM</fullName>
                </value>
                <value>
                    <fullName>PMPM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this asset.</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__RequiredByAsset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The parent Asset. If populated, this Asset is a child in a bundle.</inlineHelpText>
        <label>Required By Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Assets (Required By Asset)</relationshipLabel>
        <relationshipName>ChildAssets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__RequiredByProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent Product of this Asset.</description>
        <inlineHelpText>Parent Product of this Asset.</inlineHelpText>
        <label>Parent Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Child Assets</relationshipLabel>
        <relationshipName>ChildAssets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__RequiredBySubscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The parent Subscription. If populated, this Asset is a child in a bundle.</inlineHelpText>
        <label>Required By Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Assets (Required By Subscription)</relationshipLabel>
        <relationshipName>ChildAssets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionStartDate__c</fullName>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscribed Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Order.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Plan_Specific_Fees__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Copay_May_Be_Less__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Actual Copay May Be Less</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Plan-Specific Fees By Product (Asset)</relationshipLabel>
        <relationshipName>Plan_Specific_Fees_By_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consult_Fee_Mbr_Pd__c</fullName>
        <label>Consult Fee - Mbr Pd</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Consult_Fee_Plan_Pd__c</fullName>
        <label>Consult Fee - Plan Pd</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Membership_Fee__c</fullName>
        <formula>Subscription__r.Current_Membership_Fee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Membership Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Member_Group__c</fullName>
        <label>Member Group</label>
        <referenceTo>Mbr_Group__c</referenceTo>
        <relationshipLabel>Plan-Specific Fees By Product</relationshipLabel>
        <relationshipName>Plan_Specific_Fees_By_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PSF_ProductCode__c</fullName>
        <formula>IF( Asset__c != NULL, Asset__r.Product2.ProductCode,  Subscription__r.SBQQ__Product__r.ProductCode)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PSF ProductCode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_End_Date__c</fullName>
        <label>Product End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Start_Date__c</fullName>
        <label>Product Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Plan-Specific Fees By Product</relationshipLabel>
        <relationshipName>Plan_Specific_Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan-Specific Fees By Product</label>
    <nameField>
        <displayFormat>PSF-{0000000}</displayFormat>
        <label>Plan Fees ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan-Specific Fees By Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>Consult_Fees__c</fullName>
        <label>Consult Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fee_Type__c</fullName>
        <description>Captures the FeeType at the Product level</description>
        <label>Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Fee_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/SBQQ__SubscribedQuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscribedAssetHelp</customHelpPage>
    <description>Links a particular asset to the subscription that covers it.</description>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the quote for the quoteLines.</description>
        <inlineHelpText>Identifies the quote for the quoteLines.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote</relationshipLabel>
        <relationshipName>Quote</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscribed Quote Line</label>
    <nameField>
        <displayFormat>SQL-{00000000}</displayFormat>
        <label>Subscribed Quote Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribed Quote Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>Consult_Fees__c</fullName>
        <label>Consult Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Membership_Fee__c</fullName>
        <description>New field created to allow editing by account management for price changes.  A workflow will be built to enter the value when Subscription is originally created.</description>
        <inlineHelpText>New field created to allow editing by account management for price changes.  A workflow will be built to enter the value when Subscription is originally created.</inlineHelpText>
        <label>Current Membership Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fee_Type__c</fullName>
        <description>Keeping the Pikclist optinos un restricted as Process Builder copies the value from Opportunity Fee Type which might be different than</description>
        <inlineHelpText>Which Fee Type relates to this Subscription</inlineHelpText>
        <label>Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PEPM</fullName>
                </value>
                <value>
                    <fullName>PMPM</fullName>
                </value>
                <value>
                    <fullName>Case Rate</fullName>
                </value>
                <value>
                    <fullName>N/A (?)</fullName>
                </value>
                <value>
                    <fullName>PPPM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account that owns this subscription. This relationship is used for volume discount calculations.</description>
        <inlineHelpText>Account that owns this subscription. This relationship is used for volume discount calculations.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product used to sell this subscription.</description>
        <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this subscription.</description>
        <inlineHelpText>Quote line that generated this subscription.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionStartDate__c</fullName>
        <description>Matches the quote line start date by default. If blank, it will match the contract start date.</description>
        <inlineHelpText>Matches the quote line start date by default. If blank, it will match the contract start date.</inlineHelpText>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <description>Termination date for subscription</description>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/globalValueSets/Fee_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PEPM</fullName>
    </customValue>
    <customValue>
        <fullName>PMPM</fullName>
    </customValue>
    <customValue>
        <fullName>PPPM</fullName>
    </customValue>
    <customValue>
        <fullName>Flat Rate</fullName>
    </customValue>
    <customValue>
        <fullName>Case Rate</fullName>
    </customValue>
    <masterLabel>Fee type</masterLabel>
</GlobalValueSet>

manifest/classes/BundleClass.cls
public class BundleClass {
    public static Map<SBQQ__Subscription__c, bhSubAssetWrapper> bhSubAssetMap { get; set; }
    public static Map<SBQQ__Subscription__c, p360SubAssetWrapper> p360SubAssetMap { get; set; }
    public static Map<SBQQ__Subscription__c, mhSubAssetWrapper> mhSubAssetMap { get; set; }
    public static Map<String, List<Plan_Specific_Fees__c>> existingBHPsf { get; set; }
    public static Map<String, List<Plan_Specific_Fees__c>> existingp360Psf { get; set; }
    public static Map<String, List<Plan_Specific_Fees__c>> existingMHPsf { get; set; }

    public class bhSubAssetWrapper{
        public Asset BHP1TAsset {get; set;}
        public Asset BHPOTAsset {get; set;}
        public Asset BHNPTAsset {get; set;}
        public bhSubAssetWrapper(Asset BHP1TAsset, Asset BHPOTAsset, Asset BHNPTAsset) {
            this.BHP1TAsset = BHP1TAsset;
            this.BHPOTAsset = BHPOTAsset;
            this.BHNPTAsset = BHNPTAsset;
        }
    }
    public class p360SubAssetWrapper{
        public Asset PRIMCARECFAsset {get; set;}
        public Asset PRIMCAREACFAsset {get; set;}
        public Asset NEWPATCFAsset {get; set;}
        public Asset PRIMCAREFCFAsset {get; set;}
        public p360SubAssetWrapper(Asset PRIMCARECFAsset, Asset PRIMCAREACFAsset, Asset NEWPATCFAsset, Asset PRIMCAREFCFAsset) {
            this.PRIMCARECFAsset = PRIMCARECFAsset;
            this.PRIMCAREACFAsset = PRIMCAREACFAsset;
            this.NEWPATCFAsset = NEWPATCFAsset;
            this.PRIMCAREFCFAsset = PRIMCAREFCFAsset;
        }
    }
    
    public class mhSubAssetWrapper{
        public Asset BHPOTAsset {get; set;}
        public Asset BHPOOTAsset {get; set;}
        public Asset BHNPTAsset {get; set;}
        public Asset BHP1TAsset {get; set;}
        public mhSubAssetWrapper(Asset BHPOTAsset, Asset BHPOOTAsset, Asset BHNPTAsset, Asset BHP1TAsset) {
            this.BHPOTAsset = BHPOTAsset;
            this.BHPOOTAsset = BHPOOTAsset;
            this.BHNPTAsset = BHNPTAsset;
            this.BHP1TAsset = BHP1TAsset;
        }
    }
    
    public static void createBhMhSubAssetMap(String parentGUID) {
        if (bhSubAssetMap == Null) {
			bhSubAssetMap = new Map<SBQQ__Subscription__c, bhSubAssetWrapper>();
		}
        if (p360SubAssetMap == Null) {
			p360SubAssetMap = new Map<SBQQ__Subscription__c, p360SubAssetWrapper>();
		}
        if (mhSubAssetMap == Null) {
			mhSubAssetMap = new Map<SBQQ__Subscription__c, mhSubAssetWrapper>();
		}	
        for (SBQQ__Subscription__c sub: [SELECT Id, Fee_Type__c, SBQQ__Product__r.ProductCode, Current_Membership_Fee__c, SBQQ__QuoteLine__r.SBQQ__Quote__r.SBQQ__Opportunity2__r.Opp_Guid__c, (SELECT Id, Consult_Fees__c, Product2.ProductCode FROM SBQQ__ChildAssets__r) 
                                         FROM SBQQ__Subscription__c WHERE SBQQ__Account__r.Guid__c =: parentGUID AND SBQQ__Product__r.ProductCode = 'BH' 
                                         AND (SBQQ__SubscriptionStartDate__c <= TODAY OR Termination_Date__c = Null) ORDER BY SBQQ__SubscriptionStartDate__c DESC]) {
            Asset BHP1T, BHPOT, BHNPT;                                 
            for (Asset asset: sub.SBQQ__ChildAssets__r) {
                if (asset.Product2.ProductCode == 'BHP1T') {
                        BHP1T 
                            
                            = asset;
                } else if (asset.Product2.ProductCode == 'BHPOT') { 
                        BHPOT = asset;
                } else if (asset.Product2.ProductCode == 'BHNPT') {
                        BHNPT = asset;
                } 
            }
            bhSubAssetMap.put(sub, new bhSubAssetWrapper(BHP1T, BHPOT, BHNPT));                           
        }
        for (SBQQ__Subscription__c sub: [SELECT Id, Fee_Type__c, SBQQ__Product__r.ProductCode, Current_Membership_Fee__c,  SBQQ__QuoteLine__r.SBQQ__Quote__r.SBQQ__Opportunity2__r.Opp_Guid__c,(SELECT Id, Consult_Fees__c, Product2.ProductCode FROM SBQQ__ChildAssets__r) 
                                         FROM SBQQ__Subscription__c WHERE SBQQ__Account__r.Guid__c =: parentGUID AND SBQQ__Product__r.ProductCode = 'PRIM360CARE' 
                                         AND (SBQQ__SubscriptionStartDate__c <= TODAY OR Termination_Date__c = Null) ORDER BY SBQQ__SubscriptionStartDate__c DESC]) {
            Asset PRIMCARECF, PRIMCAREACF, NEWPATCF, PRIMCAREFCF;                                 
            for (Asset asset: sub.SBQQ__ChildAssets__r) {
                if (asset.Product2.ProductCode == 'PRIMCARECF') {
                        PRIMCARECF = asset;
                } else if (asset.Product2.ProductCode == 'PRIMCAREACF') { 
                        PRIMCAREACF = asset;
                } else if (asset.Product2.ProductCode == 'NEWPATCF') {
                        NEWPATCF = asset;
                }
                else if (asset.Product2.ProductCode == 'PRIMCAREFCF') {
                        PRIMCAREFCF = asset;
                }
 
            }
            p360SubAssetMap.put(sub, new p360SubAssetWrapper(PRIMCARECF, PRIMCAREACF, NEWPATCF, PRIMCAREFCF));                           
        }
        for (SBQQ__Subscription__c sub: [SELECT Id, Fee_Type__c, SBQQ__Product__r.ProductCode, Current_Membership_Fee__c, SBQQ__QuoteLine__r.SBQQ__Quote__r.SBQQ__Opportunity2__r.Opp_Guid__c, (SELECT Id, Consult_Fees__c, Product2.ProductCode FROM SBQQ__ChildAssets__r) 
                                         FROM SBQQ__Subscription__c WHERE SBQQ__Account__r.Guid__c =: parentGUID AND SBQQ__Product__r.ProductCode = 'MH' 
                                         AND (SBQQ__SubscriptionStartDate__c <= TODAY OR Termination_Date__c = Null) ORDER BY SBQQ__SubscriptionStartDate__c DESC]) {
            Asset BHPOT, BHPOOT, BHNPT, BHP1T;                                 
            for (Asset asset: sub.SBQQ__ChildAssets__r) {
                if (asset.Product2.ProductCode == 'BHPOT') {
                        BHPOT = asset;
                } else if (asset.Product2.ProductCode == 'BHPOOT') { 
                        BHPOOT = asset;
                } else if (asset.Product2.ProductCode == 'BHNPT') {
                        BHNPT = asset;
                } else if (asset.Product2.ProductCOde == 'BHP1T') {
                    	BHP1T = asset;
                }
            }
            mhSubAssetMap.put(sub, new mhSubAssetWrapper(BHPOT, BHPOOT, BHNPT, BHP1T));                           
        }   
    }
  
    public Map<String, Plan_Specific_Fees__c> findBH(Map<String, Plan_Specific_Fees__c> bhPsfMap, SBQQ__Subscription__c sub, String opportunityGUID) {
        if (bhSubAssetMap == Null) {
            return null;
		}
        Map<String, Plan_Specific_Fees__c> updatedPSF = new Map<String, Plan_Specific_Fees__c>();
        Plan_Specific_Fees__c BHP1T, BHPOT, BHNPT;
        for (String productCode: bhPsfMap.keySet()) {
            switch on productCode {
                when 'BHP1T' {
                    BHP1T = bhPsfMap.get(productCode);
                }
                when 'BHPOT' {
                    BHPOT = bhPsfMap.get(productCode);
                }
                when 'BHNPT' {
                    BHNPT = bhPsfMap.get(productCode);
                }
            }  
        }
        for (SBQQ__Subscription__c mapSub: bhSubAssetMap.keySet()) {
            if (mapSub.Fee_Type__c == sub.Fee_Type__c && mapSub.Current_Membership_Fee__c == sub.Current_Membership_Fee__c && ((opportunityGUID!=null && opportunityGUID == mapSub.SBQQ__QuoteLine__r.SBQQ__Quote__r.SBQQ__Opportunity2__r.Opp_Guid__c) || (opportunityGUID==null || opportunityGUID=='')) &&
                bhSubAssetMap.get(mapSub).BHP1TAsset.Consult_Fees__c == (BHP1T.Consult_Fee_Mbr_Pd__c + BHP1T.Consult_Fee_Plan_Pd__c) &&
                bhSubAssetMap.get(mapSub).BHPOTAsset.Consult_Fees__c == (BHPOT.Consult_Fee_Mbr_Pd__c + BHPOT.Consult_Fee_Plan_Pd__c) &&
                bhSubAssetMap.get(mapSub).BHNPTAsset.Consult_Fees__c == (BHNPT.Consult_Fee_Mbr_Pd__c + BHNPT.Consult_Fee_Plan_Pd__c)) {
                    BHP1T.Asset__c = bhSubAssetMap.get(mapSub).BHP1TAsset.Id;
                    BHPOT.Asset__c = bhSubAssetMap.get(mapSub).BHPOTAsset.Id;
                    BHNPT.Asset__c = bhSubAssetMap.get(mapSub).BHNPTAsset.Id;
                    BHP1T.Subscription__c = mapSub.Id;
                    BHPOT.Subscription__c = mapSub.Id;
                    BHNPT.Subscription__c = mapSub.Id;
                    updatedPSF.put('BHP1T', BHP1T);
                    updatedPSF.put('BHPOT', BHPOT);
                    updatedPSF.put('BHNPT', BHNPT);
                    break;
                }
        }
        if (updatedPSf.size() != 3)
            return null;
        else 
            return updatedPSF;
    }
    public Map<String, Plan_Specific_Fees__c> findp360(Map<String, Plan_Specific_Fees__c> p360PsfMap, SBQQ__Subscription__c sub, String opportunityGUID	) {
        if (p360SubAssetMap == Null) {
            return null;
		}
        Map<String, Plan_Specific_Fees__c> updatedPSF = new Map<String, Plan_Specific_Fees__c>();
        Plan_Specific_Fees__c PRIMCARECF, PRIMCAREACF, NEWPATCF, PRIMCAREFCF;
        for (String productCode: p360PsfMap.keySet()) {
            switch on productCode {
                when 'PRIMCARECF' {
                    PRIMCARECF = p360PsfMap.get(productCode);
                }
                when 'PRIMCAREACF' {
                    PRIMCAREACF = p360PsfMap.get(productCode);
                }
                when 'NEWPATCF' {
                    NEWPATCF = p360PsfMap.get(productCode);
                }
                when 'PRIMCAREFCF' {
                    PRIMCAREFCF = p360PsfMap.get(productCode);
                }
            }  
        }
        for (SBQQ__Subscription__c mapSub: p360SubAssetMap.keySet()) {
            if (mapSub.Fee_Type__c == sub.Fee_Type__c && mapSub.Current_Membership_Fee__c == sub.Current_Membership_Fee__c && ((opportunityGUID!=null && opportunityGUID == mapSub.SBQQ__QuoteLine__r.SBQQ__Quote__r.SBQQ__Opportunity2__r.Opp_Guid__c) || (opportunityGUID==null || opportunityGUID=='')) &&
                p360SubAssetMap.get(mapSub).PRIMCARECFAsset.Consult_Fees__c == (PRIMCARECF.Consult_Fee_Mbr_Pd__c + PRIMCARECF.Consult_Fee_Plan_Pd__c) &&
                p360SubAssetMap.get(mapSub).PRIMCAREACFAsset.Consult_Fees__c == (PRIMCAREACF.Consult_Fee_Mbr_Pd__c + PRIMCAREACF.Consult_Fee_Plan_Pd__c) &&
                p360SubAssetMap.get(mapSub).NEWPATCFAsset.Consult_Fees__c == (NEWPATCF.Consult_Fee_Mbr_Pd__c + NEWPATCF.Consult_Fee_Plan_Pd__c) &&
                p360SubAssetMap.get(mapSub).PRIMCAREFCFAsset.Consult_Fees__c == (PRIMCAREFCF.Consult_Fee_Mbr_Pd__c + PRIMCAREFCF.Consult_Fee_Plan_Pd__c)) {
                    PRIMCARECF.Asset__c = p360SubAssetMap.get(mapSub).PRIMCARECFAsset.Id;
                    PRIMCAREACF.Asset__c = p360SubAssetMap.get(mapSub).PRIMCAREACFAsset.Id;
                    NEWPATCF.Asset__c = p360SubAssetMap.get(mapSub).NEWPATCFAsset.Id;
                    PRIMCAREFCF.Asset__c = p360SubAssetMap.get(mapSub).PRIMCAREFCFAsset.Id;
                    PRIMCARECF.Subscription__c = mapSub.Id;
                    PRIMCAREACF.Subscription__c = mapSub.Id;
                    NEWPATCF.Subscription__c = mapSub.Id;
                    PRIMCAREFCF.Subscription__c = mapSub.Id;
                    updatedPSF.put('PRIMCARECF', PRIMCARECF);
                    updatedPSF.put('PRIMCAREACF', PRIMCAREACF);
                    updatedPSF.put('NEWPATCF', NEWPATCF);
                    updatedPSF.put('PRIMCAREFCF', PRIMCAREFCF);
                    break;
                }
        }
        if (updatedPSf.size() != 4)
            return null;
        else 
            return updatedPSF;
    }
    
    public Map<String, Plan_Specific_Fees__c> findMH(Map<String, Plan_Specific_Fees__c> mhPsfMap, SBQQ__Subscription__c sub, String opportunityGUID) {
        if (mhSubAssetMap == Null) {
            return null;
		}
        Map<String, Plan_Specific_Fees__c> updatedPSF = new Map<String, Plan_Specific_Fees__c>();
        Plan_Specific_Fees__c BHPOT, BHPOOT, BHNPT, BHP1T;
        for (String productCode: mhPsfMap.keySet()) {
            switch on productCode {
                when 'BHPOT' {
                    BHPOT = mhPsfMap.get(productCode);
                }
                when 'BHPOOT' {
                    BHPOOT = mhPsfMap.get(productCode);
                }
                when 'BHNPT' {
                    BHNPT = mhPsfMap.get(productCode);
                }
                when 'BHP1T' {
                    BHP1T = mhPsfMap.get(productCode);
                }
            }  
        }
        for (SBQQ__Subscription__c mapSub: mhSubAssetMap.keySet()) {
            if (mapSub.Fee_Type__c == sub.Fee_Type__c && mapSub.Current_Membership_Fee__c == sub.Current_Membership_Fee__c && ((opportunityGUID!=null && opportunityGUID == mapSub.SBQQ__QuoteLine__r.SBQQ__Quote__r.SBQQ__Opportunity2__r.Opp_Guid__c) || (opportunityGUID==null || opportunityGUID=='')) &&
                mhSubAssetMap.get(mapSub).BHPOTAsset.Consult_Fees__c == (BHPOT.Consult_Fee_Mbr_Pd__c + BHPOT.Consult_Fee_Plan_Pd__c) &&
                mhSubAssetMap.get(mapSub).BHPOOTAsset.Consult_Fees__c == (BHPOOT.Consult_Fee_Mbr_Pd__c + BHPOOT.Consult_Fee_Plan_Pd__c) &&
                mhSubAssetMap.get(mapSub).BHNPTAsset.Consult_Fees__c == (BHNPT.Consult_Fee_Mbr_Pd__c + BHNPT.Consult_Fee_Plan_Pd__c) && 
                mhSubAssetMap.get(mapSub).BHP1TAsset.Consult_Fees__c == (BHP1T.Consult_Fee_Mbr_Pd__c + BHP1T.Consult_Fee_Plan_Pd__c)) {
                    BHPOT.Asset__c = mhSubAssetMap.get(mapSub).BHPOTAsset.Id;
                    BHPOOT.Asset__c = mhSubAssetMap.get(mapSub).BHPOOTAsset.Id;
                    BHNPT.Asset__c = mhSubAssetMap.get(mapSub).BHNPTAsset.Id;
                    BHP1T.Asset__c = mhSubAssetMap.get(mapSub).BHP1TAsset.Id;
                    BHPOT.Subscription__c = mapSub.Id;
                    BHPOOT.Subscription__c = mapSub.Id;
                    BHNPT.Subscription__c = mapSub.Id;
                    BHP1T.Subscription__c = mapSub.Id;
                    updatedPSF.put('BHPOT', BHPOT);
                    updatedPSF.put('BHPOOT', BHPOOT);
                    updatedPSF.put('BHNPT', BHNPT);
                    updatedPSF.put('BHP1T', BHP1T);
                    break;
                }
        }
        if (updatedPSf.size() != 4)
            return null;
        else 
            return updatedPSF;
    }
   
    public void createExistingKey(String prodCode, List<Plan_Specific_Fees__c> psfList) {
        if (existingBHPsf == Null) {
			existingBHPsf = new Map<String, List<Plan_Specific_Fees__c>>();
		}
        if (existingMHPsf == Null) {
			existingMHPsf = new Map<String, List<Plan_Specific_Fees__c>>();
		}
        Map<String, List<Plan_Specific_Fees__c>> psfMap = new Map<String, List<Plan_Specific_Fees__c>>();
        for (Plan_Specific_Fees__c psf : psfList) {
            if (psfMap.containsKey(psf.Subscription__c)) {
                psfMap.get(psf.Subscription__c).add(psf);
                psfMap.put(psf.Subscription__c, psfMap.get(psf.Subscription__c));
            } else {
                List<Plan_Specific_Fees__c> newList = new List<Plan_Specific_Fees__c>();
                newList.add(psf);
                psfMap.put(psf.Subscription__c, newList);
            }  
        }
        if (prodCode == 'BH') {
            for (String subId: psfMap.keyset()) {
                String BHP1TMbr, BHPOTMbr, BHNPTMbr, startDate, endDate, payLess;
                List<Plan_Specific_Fees__c> oldBHPsf = new List<Plan_Specific_Fees__c>();
                for (Plan_Specific_Fees__c psf: psfMap.get(subId)) {
                    switch on psf.PSF_ProductCode__c {
                        when 'BHP1T' {
                            BHP1TMbr = String.valueOf(psf.Consult_Fee_Mbr_Pd__c.setscale(2));
                            startDate = String.valueOf(psf.Product_Start_Date__c);
                            endDate = String.valueOf(psf.Product_End_Date__c);
                            payLess = String.valueOf(psf.Actual_Copay_May_Be_Less__c);
                        }
                        when 'BHPOT' {
                            BHPOTMbr = String.valueOf(psf.Consult_Fee_Mbr_Pd__c.setscale(2));
                        }
                        when 'BHNPT' {
                            BHNPTMbr = String.valueOf(psf.Consult_Fee_Mbr_Pd__c.setscale(2));
                        }
                    }
                    oldBHPsf.add(psf);
                }
                String key = startDate + '__' + String.valueOf(subId) + '__' + endDate + '__' + payLess + '__' + BHP1TMbr + '__' + BHPOTMbr + '__' + BHNPTMbr;
                existingBHPsf.put(key, oldBHPsf);
            }
        }if (prodCode == 'PRIM360CARE') {
            for (String subId: psfMap.keyset()) {
                String PRIMCARECFMbr, PRIMCAREACFMbr, NEWPATCFMbr,PRIMCAREFCFMbr, startDate, endDate, payLess;
                List<Plan_Specific_Fees__c> oldp360Psf = new List<Plan_Specific_Fees__c>();
                for (Plan_Specific_Fees__c psf: psfMap.get(subId)) {
                    switch on psf.PSF_ProductCode__c {
                        when 'PRIMCARECF' {
                            PRIMCARECFMbr = String.valueOf(psf.Consult_Fee_Mbr_Pd__c.setscale(2));
                            startDate = String.valueOf(psf.Product_Start_Date__c);
                            endDate = String.valueOf(psf.Product_End_Date__c);
                            payLess = String.valueOf(psf.Actual_Copay_May_Be_Less__c);
                        }
                        when 'PRIMCAREACF' {
                            PRIMCAREACFMbr = String.valueOf(psf.Consult_Fee_Mbr_Pd__c.setscale(2));
                        }
                        when 'NEWPATCF' {
                            NEWPATCFMbr = String.valueOf(psf.Consult_Fee_Mbr_Pd__c.setscale(2));
                        }
                        when 'PRIMCAREFCF' {
                            PRIMCAREFCFMbr = String.valueOf(psf.Consult_Fee_Mbr_Pd__c.setscale(2));
                        }
                    }
                    oldp360Psf.add(psf);
                }
                String key = startDate + '__' + String.valueOf(subId) + '__' + endDate + '__' + payLess + '__' + PRIMCARECFMbr + '__' + PRIMCAREACFMbr + '__' + NEWPATCFMbr + '__' + PRIMCAREFCFMbr;
                existingp360Psf.put(key, oldp360Psf);
            }
        } else if (prodCode == 'MH') {
            for (String subId: psfMap.keyset()) {
                String BHPOTMbr, BHPOOTMbr, BHNPTMbr, BHP1TMbr, startDate, endDate, payLess;
                List<Plan_Specific_Fees__c> oldMhPsf = new List<Plan_Specific_Fees__c>();
                for (Plan_Specific_Fees__c psf: psfMap.get(subId)) {
                    switch on psf.PSF_ProductCode__c {
                        when 'BHPOT' {
                            BHPOTMbr = String.valueOf(psf.Consult_Fee_Mbr_Pd__c.setscale(2));
                            startDate = String.valueOf(psf.Product_Start_Date__c);
                            endDate = String.valueOf(psf.Product_End_Date__c);
                            payLess = String.valueOf(psf.Actual_Copay_May_Be_Less__c);
                        }
                        when 'BHPOOT' {
                            BHPOOTMbr = String.valueOf(psf.Consult_Fee_Mbr_Pd__c.setscale(2));
                        }
                        when 'BHNPT' {
                            BHNPTMbr = String.valueOf(psf.Consult_Fee_Mbr_Pd__c.setscale(2));
                        }
                        when 'BHP1T' {
                            BHP1TMbr = String.valueOf(psf.Consult_Fee_Mbr_Pd__c.setscale(2));
                        }
                    }
                    oldMhPsf.add(psf);
                }
                String key = startDate + '__' + String.valueOf(subId) + '__' + endDate + '__' + payLess + '__' + BHPOTMbr + '__' + BHPOOTMbr + '__' + BHNPTMbr + '__' + BHP1TMbr;
                existingMHPsf.put(key, oldMhPsf);
            }
        }
    }

    public Map<String, List<Plan_Specific_Fees__c>> buildNewKey(String subProdCode, Map<String, Plan_Specific_Fees__c> bhMap) {
        Map<String, List<Plan_Specific_Fees__c>> newKey = new Map<String, List<Plan_Specific_Fees__c>>();
        List<Plan_Specific_Fees__c> psfList = new List<Plan_Specific_Fees__c>();
        if (subProdCode == 'BH') {
            String BHP1TMbr, BHPOTMbr, BHNPTMbr, startDate, endDate, payLess, subId, key;
            for (String prodCode: bhMap.keySet()) {
                switch on prodCode {
                    when 'BHP1T' {
                        BHP1TMbr = String.valueOf(bhMap.get(prodCode).Consult_Fee_Mbr_Pd__c.setscale(2));
                        startDate = String.valueOf(bhMap.get(prodCode).Product_Start_Date__c);
                        endDate = String.valueOf(bhMap.get(prodCode).Product_End_Date__c);
                        payLess = String.valueOf(bhMap.get(prodCode).Actual_Copay_May_Be_Less__c);
                        subId = String.valueOf(bhMap.get(prodCode).Subscription__c);
                    }
                    when 'BHPOT' {
                        BHPOTMbr = String.valueOf(bhMap.get(prodCode).Consult_Fee_Mbr_Pd__c.setscale(2));
                    }
                    when 'BHNPT' {
                        BHNPTMbr = String.valueOf(bhMap.get(prodCode).Consult_Fee_Mbr_Pd__c.setscale(2));
                    }
                }
                psfList.add(bhMap.get(prodCode));
            }
            key = startDate + '__' + subId + '__' + endDate + '__' + payLess + '__' + BHP1TMbr + '__' + BHPOTMbr + '__' + BHNPTMbr;
            newKey.put(key, psfList);
        }if (subProdCode == 'PRIM360CARE') {
            String PRIMCARECFMbr, PRIMCAREACFMbr, NEWPATCFMbr,PRIMCAREFCFMbr, startDate, endDate, payLess, subId, key;
            for (String prodCode: bhMap.keySet()) {
                switch on prodCode {
                    when 'PRIMCARECF' {
                        PRIMCARECFMbr = String.valueOf(bhMap.get(prodCode).Consult_Fee_Mbr_Pd__c.setscale(2));
                        startDate = String.valueOf(bhMap.get(prodCode).Product_Start_Date__c);
                        endDate = String.valueOf(bhMap.get(prodCode).Product_End_Date__c);
                        payLess = String.valueOf(bhMap.get(prodCode).Actual_Copay_May_Be_Less__c);
                        subId = String.valueOf(bhMap.get(prodCode).Subscription__c);
                    }
                    when 'PRIMCAREACF' {
                        PRIMCAREACFMbr = String.valueOf(bhMap.get(prodCode).Consult_Fee_Mbr_Pd__c.setscale(2));
                    }
                    when 'NEWPATCF' {
                        NEWPATCFMbr = String.valueOf(bhMap.get(prodCode).Consult_Fee_Mbr_Pd__c.setscale(2));
                    }
                     when 'PRIMCAREFCF' {
                        PRIMCAREFCFMbr = String.valueOf(bhMap.get(prodCode).Consult_Fee_Mbr_Pd__c.setscale(2));
                    }
                }
                psfList.add(bhMap.get(prodCode));
            }
            key = startDate + '__' + subId + '__' + endDate + '__' + payLess + '__' + PRIMCARECFMbr + '__' + PRIMCAREACFMbr + '__' + NEWPATCFMbr + '__' + PRIMCAREFCFMbr;
            newKey.put(key, psfList);
        } else if (subProdCode == 'MH') {
            String BHPOTMbr, BHPOOTMbr, BHNPTMbr, BHP1TMbr, startDate, endDate, payLess, subId, key;
            for (String prodCode: bhMap.keySet()) {
                switch on prodCode {
                    when 'BHPOT' {
                        BHPOTMbr = String.valueOf(bhMap.get(prodCode).Consult_Fee_Mbr_Pd__c.setscale(2));
                        startDate = String.valueOf(bhMap.get(prodCode).Product_Start_Date__c);
                        endDate = String.valueOf(bhMap.get(prodCode).Product_End_Date__c);
                        payLess = String.valueOf(bhMap.get(prodCode).Actual_Copay_May_Be_Less__c);
                        subId = String.valueOf(bhMap.get(prodCode).Subscription__c);
                    }
                    when 'BHPOOT' {
                        BHPOOTMbr = String.valueOf(bhMap.get(prodCode).Consult_Fee_Mbr_Pd__c.setscale(2));
                    }
                    when 'BHNPT' {
                        BHNPTMbr = String.valueOf(bhMap.get(prodCode).Consult_Fee_Mbr_Pd__c.setscale(2));
                    }
                    when 'BHP1T' {
                        BHP1TMbr = String.valueOf(bhMap.get(prodCode).Consult_Fee_Mbr_Pd__c.setscale(2));
                    }
                }
                psfList.add(bhMap.get(prodCode));
            }
            key = startDate + '__' + subId + '__' + endDate + '__' + payLess + '__' + BHPOTMbr + '__' + BHPOOTMbr + '__' + BHNPTMbr + '__' + BHP1TMbr;
            newKey.put(key, psfList);
        }
        return newKey;
    }
    
    public static void insertPsf(Map<String, List<Plan_Specific_Fees__c>> psfMap, String mbrGroupId, String agcpiId) {
        List<Plan_Specific_Fees__c> createPSFList = new List<Plan_Specific_Fees__c>();
        for (List<Plan_Specific_Fees__c> psfList: psfMap.values()) {
            for (Plan_Specific_Fees__c psf: psfList) {
                Plan_Specific_Fees__c clonePSF = psf.clone(false);
                clonePSF.Member_Group__c = mbrGroupId;
                createPSFList.add(clonePSF);
            }
        }
        Database.SaveResult[] srbh = Database.insert(createPSFList, false);
        for (Database.SaveResult rowSr : srbh) {
            if (!rowSr.isSuccess()) {
                for (Database.Error rowError : rowSr.getErrors()) {
                    F1bUtils_v2.LogException(agcpiId, 'PLAN_SPECIFIC_FEES__C', 'ERROR', 'PSF_INSERT_FAILED',
                                             rowError.getMessage());
                }
            }
        }
    }  
    
    public static void deletePsf(Map<String, List<Plan_Specific_Fees__c>> psfMap, String agcpiId) {
        List<Plan_Specific_Fees__c> deletePsfList = new List<Plan_Specific_Fees__c>();
        for (List<Plan_Specific_Fees__c> psfList: psfMap.values()) {
            deletePsfList.addAll(psfList);
        }
        Database.DeleteResult[] dr = Database.delete(deletePsfList, false);
        boolean isError = false;
        for (Database.DeleteResult rowSr : dr) {
            if (!rowSr.isSuccess()) {
                isError = true;
                for (Database.Error rowError : rowSr.getErrors()) {
                    F1bUtils_v2.LogException(agcpiId, 'PLAN_SPECIFIC_FEES__C', 'ERROR', 'PSF_DELETE_FAILED',
                                             rowError.getMessage());
                }
            }
        }
        if (!isError)
            psfMap.clear(); 
    }
}