manifest/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Consult_Fees__c</fullName>
        <label>Consult Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fee_Type__c</fullName>
        <label>Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PEPM</fullName>
                </value>
                <value>
                    <fullName>PMPM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__RequiredByAsset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The parent Asset. If populated, this Asset is a child in a bundle.</inlineHelpText>
        <label>Required By Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Assets (Required By Asset)</relationshipLabel>
        <relationshipName>ChildAssets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__RequiredByProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent Product of this Asset.</description>
        <inlineHelpText>Parent Product of this Asset.</inlineHelpText>
        <label>Parent Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Child Assets</relationshipLabel>
        <relationshipName>ChildAssets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__RequiredBySubscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The parent Subscription. If populated, this Asset is a child in a bundle.</inlineHelpText>
        <label>Required By Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Assets (Required By Subscription)</relationshipLabel>
        <relationshipName>ChildAssets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionStartDate__c</fullName>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscribed Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>Consult_Fees__c</fullName>
        <label>Consult Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Membership_Fee__c</fullName>
        <description>New field created to allow editing by account management for price changes.  A workflow will be built to enter the value when Subscription is originally created.</description>
        <inlineHelpText>New field created to allow editing by account management for price changes.  A workflow will be built to enter the value when Subscription is originally created.</inlineHelpText>
        <label>Current Membership Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fee_Type__c</fullName>
        <description>Keeping the Pikclist optinos un restricted as Process Builder copies the value from Opportunity Fee Type which might be different than</description>
        <inlineHelpText>Which Fee Type relates to this Subscription</inlineHelpText>
        <label>Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PEPM</fullName>
                </value>
                <value>
                    <fullName>PMPM</fullName>
                </value>
                <value>
                    <fullName>Case Rate</fullName>
                </value>
                <value>
                    <fullName>N/A (?)</fullName>
                </value>
                <value>
                    <fullName>PPPM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account that owns this subscription. This relationship is used for volume discount calculations.</description>
        <inlineHelpText>Account that owns this subscription. This relationship is used for volume discount calculations.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product used to sell this subscription.</description>
        <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionStartDate__c</fullName>
        <description>Matches the quote line start date by default. If blank, it will match the contract start date.</description>
        <inlineHelpText>Matches the quote line start date by default. If blank, it will match the contract start date.</inlineHelpText>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <description>Termination date for subscription</description>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/classes/OrgSubscriptions.cls
@RestResource(urlMapping='/orgsubsoption/*')
global class OrgSubscriptions {
  @HttpGet
  global static String doGet() {
    List<String> result = new List<String>();
    RestRequest req = RestContext.request;
    RestResponse res = RestContext.response;
    String parentGUID = req.requestURI.substring(
      req.requestURI.lastIndexOf('/') + 1
    );
    List<SBQQ__Subscription__c> subList = [
      SELECT
        Id,
        Fee_Type__c,
        SBQQ__Product__r.ProductCode,
        Current_Membership_Fee__c,
        (SELECT Consult_Fees__c, Product2.ProductCode FROM SBQQ__ChildAssets__r)
      FROM SBQQ__Subscription__c
      WHERE
        SBQQ__Account__r.Guid__c = :parentGUID
        AND (SBQQ__SubscriptionStartDate__c <= TODAY
        OR Termination_Date__c = NULL)
      ORDER BY SBQQ__SubscriptionStartDate__c DESC
    ];
    JSONGenerator gen = JSON.createGenerator(false);
    gen.writeStartArray();
    for (SBQQ__Subscription__c sub : subList) {
      gen.writeStartObject();
      gen.writeStringField('SubscriptionId', sub.Id);
      gen.writeStringField('ProductCode', sub.SBQQ__Product__r.ProductCode);
      gen.writeStringField('Fee_Type__c', sub.Fee_Type__c);
      gen.writeNumberField(
        'Current_Membership_Fee__c',
        sub.Current_Membership_Fee__c
      );
      gen.writeFieldName('Asset');
      gen.writeStartArray();
      for (Asset ast : sub.SBQQ__ChildAssets__r) {
        gen.writeStartObject();
        gen.writeStringField('AssetId', ast.Id);
        gen.writeStringField('ProductCode', ast.Product2.ProductCode);
        gen.writeNumberField('Consult_Fees__c', ast.Consult_Fees__c);
        gen.writeEndObject();
      }
      gen.writeEndArray();
      gen.writeEndObject();
    }
    gen.writeEndArray();

    return gen.getAsString();
  }
}