manifest/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Fee_Type__c</fullName>
        <label>Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PEPM</fullName>
                </value>
                <value>
                    <fullName>PMPM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this asset.</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscribed Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity from which this Contract was created.</description>
        <inlineHelpText>The Opportunity from which this Contract was created.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Plan_Specific_Fees__c.object
<CustomObject>
    <fields>
        <fullName>Current_Membership_Fee__c</fullName>
        <formula>Subscription__r.Current_Membership_Fee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Membership Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Membership_fee__c</fullName>
        <formula>Subscription__r.Membership_Fee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Membership fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <formula>Subscription__r.SBQQ__ProductName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Plan-Specific Fees By Product</relationshipLabel>
        <relationshipName>Plan_Specific_Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan-Specific Fees By Product</label>
    <nameField>
        <displayFormat>PSF-{0000000}</displayFormat>
        <label>Plan Fees ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan-Specific Fees By Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__EndDate__c</fullName>
        <description>End date for subscriptions in this group.</description>
        <inlineHelpText>End date for subscriptions in this group.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Start date for subscriptions in this quote.</description>
        <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>Teladoc</fullName>
        <active>true</active>
        <label>Teladoc</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>Consult_Type__c</fullName>
        <label>Consult Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Consult_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fee_Type__c</fullName>
        <description>Captures the FeeType at the Product level</description>
        <label>Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Fee_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Membership_Fee__c</fullName>
        <description>This is the PEPM/PMPM that includes any discounts.  It is the Net Unit Price (which is annual) divided by 12.  It is also used to populate the Subscription Membership Fee field (formula).

    SBQQ__NetPrice__c/IF(SBQQ__SubscriptionTerm__c &lt;&gt; Null, SBQQ__SubscriptionTerm__c, Quote_Subscription_Term__c)</description>
        <formula>IF( NOT(ISNULL(Subscription_Fee__c)), Subscription_Fee__c ,If(Additional_Disc__c = 0,SBQQ__ListPrice__c - SBQQ__AdditionalDiscountAmount__c, SBQQ__ListPrice__c - Additional_Disc__c) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the PEPM/PMPM that includes any discounts.</inlineHelpText>
        <label>Membership Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__EndDate__c</fullName>
        <description>Date the service represented by this line item will end (only applies if product is a subscription).</description>
        <inlineHelpText>Date the service represented by this line item will end (only applies if product is a subscription).</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProductName__c</fullName>
        <description>Name for the product referenced by this line item.</description>
        <formula>SBQQ__Product__r.Name</formula>
        <inlineHelpText>Name for the product referenced by this line item.</inlineHelpText>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity being quoted.</description>
        <inlineHelpText>Quantity being quoted.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Date the service represented by this line item will begin (only applies if product is a subscription).</description>
        <inlineHelpText>The date the subscription for this product begins.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>Consult_Type__c</fullName>
        <label>Consult Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Consult_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Membership_Fee__c</fullName>
        <description>New field created to allow editing by account management for price changes.  A workflow will be built to enter the value when Subscription is originally created.</description>
        <inlineHelpText>New field created to allow editing by account management for price changes.  A workflow will be built to enter the value when Subscription is originally created.</inlineHelpText>
        <label>Current Membership Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fee_Type__c</fullName>
        <description>Keeping the Pikclist optinos un restricted as Process Builder copies the value from Opportunity Fee Type which might be different than</description>
        <inlineHelpText>Which Fee Type relates to this Subscription</inlineHelpText>
        <label>Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PEPM</fullName>
                </value>
                <value>
                    <fullName>PMPM</fullName>
                </value>
                <value>
                    <fullName>Case Rate</fullName>
                </value>
                <value>
                    <fullName>N/A (?)</fullName>
                </value>
                <value>
                    <fullName>PPPM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Membership_Fee__c</fullName>
        <description>This is the PEPM/PMPM that includes any discounts. It is populated from the Quote Line Item Membership Fee field via the formula below. The Membership Fee is the Net Unit Fee (annual) divided by 12.</description>
        <formula>SBQQ__QuoteLine__r.Membership_Fee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the PEPM/PMPM that includes any discounts.</inlineHelpText>
        <label>Membership Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__EndDate__c</fullName>
        <description>The last date this contract is valid.</description>
        <formula>if ( ISBLANK (SBQQ__SubscriptionEndDate__c), SBQQ__Contract__r.EndDate, SBQQ__SubscriptionEndDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The last date this contract is valid.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProductName__c</fullName>
        <description>Pulls in the Product Name</description>
        <formula>SBQQ__Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pulls in the Product Name</inlineHelpText>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity of this subscription product purchased by the customer.</description>
        <inlineHelpText>Quantity of this subscription product purchased by the customer.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this subscription.</description>
        <inlineHelpText>Quote line that generated this subscription.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>The first date this subscription is in effect.</description>
        <formula>if ( ISBLANK (SBQQ__SubscriptionStartDate__c), SBQQ__Contract__r.StartDate, SBQQ__SubscriptionStartDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The first date this subscription is in effect.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/globalValueSets/Consult_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Included</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 1 - Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 1 - Included</fullName>
    </customValue>
    <customValue>
        <fullName>MFN - Standard</fullName>
    </customValue>
    <customValue>
        <fullName>MFN - Included</fullName>
    </customValue>
    <customValue>
        <fullName>Mercer WTW - Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Mercer/WTW - Included</fullName>
    </customValue>
    <customValue>
        <fullName>Custom</fullName>
    </customValue>
    <masterLabel>Consult_Types</masterLabel>
</GlobalValueSet>

manifest/globalValueSets/Fee_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PEPM</fullName>
    </customValue>
    <customValue>
        <fullName>PMPM</fullName>
    </customValue>
    <customValue>
        <fullName>PPPM</fullName>
    </customValue>
    <customValue>
        <fullName>Flat Rate</fullName>
    </customValue>
    <customValue>
        <fullName>Case Rate</fullName>
    </customValue>
    <masterLabel>Fee type</masterLabel>
</GlobalValueSet>

manifest/classes/opportunityReopenLwcController.cls
public with sharing class opportunityReopenLwcController {
    @AuraEnabled
    public static List<Contract> getContract(Id recordId) {
       List<Contract> contractList  = [Select Id, ContractNumber, Name, SBQQ__Opportunity__c, SBQQ__Opportunity__r.Name, StartDate, EndDate, Status 
                                       FROM Contract WHERE SBQQ__Opportunity__c =:recordId];
       return contractList;
    }
    
    @AuraEnabled
    public static List<SBQQ__Subscription__c> getSubs(Id recordId) {
       List<SBQQ__Quote__c> qteList = [SELECT Id, RecordtypeId FROM SBQQ__Quote__c WHERE SBQQ__Opportunity2__c =:recordId AND SBQQ__Primary__c = TRUE];

       List<SBQQ__Subscription__c> subList  = [SELECT Id, Name, SBQQ__QuoteLine__c, SBQQ__QuoteLine__r.Name, Fee_Type__c, SBQQ__ProductName__c, Membership_Fee__c, 
                                               Consult_Type__c, Current_Membership_Fee__c, SBQQ__Quantity__c, SBQQ__StartDate__c, SBQQ__EndDate__c 
											   FROM SBQQ__Subscription__c WHERE SBQQ__QuoteLine__r.SBQQ__Quote__c in :qteList];
       return subList;
    }
    
    @AuraEnabled
    public static List<Plan_Specific_Fees__c> getPsf(Id recordId) {
        List<SBQQ__Quote__c> qteList = [SELECT Id, RecordtypeId FROM SBQQ__Quote__c WHERE SBQQ__Opportunity2__c =:recordId AND SBQQ__Primary__c = TRUE];
        Map<Id,SBQQ__Subscription__c> subscriptionMap = new Map<Id,SBQQ__Subscription__c>();
        subscriptionMap = new Map<Id,SBQQ__Subscription__c>([SELECT Id, Name, SBQQ__QuoteLine__c, Fee_Type__c, SBQQ__ProductName__c, Membership_Fee__c, 
                                                             Consult_Type__c, Current_Membership_Fee__c, SBQQ__Quantity__c, SBQQ__StartDate__c, SBQQ__EndDate__c 
                                                             FROM SBQQ__Subscription__c WHERE SBQQ__QuoteLine__r.SBQQ__Quote__c in :qteList]);
        List<Plan_Specific_Fees__c> psfList = [SELECT Id, Name, Product__c, CreatedDate, Member_Group__c, Member_Group__r.Name, Member_Group_Name__c, Product_End_Date__c, 
                                               Product_Start_Date__c, Subscription__c, Subscription__r.Name FROM Plan_Specific_Fees__c 
                                               WHERE Subscription__c in : subscriptionMap.keySet()];
        return psfList;                                                      
    }
    
    @AuraEnabled
    public static List<Asset> getAsset(Id recordId) {
        List<SBQQ__Quote__c> qteList = [SELECT Id, RecordtypeId FROM SBQQ__Quote__c WHERE SBQQ__Opportunity2__c =:recordId AND SBQQ__Primary__c = TRUE];
        List<Asset> assetList = [SELECT Id, Name, Product2.Name, Status, Implementation_Status__c, Number_of_Lives__c, Teladoc_Net_Fee__c,
                                 SBQQ__RequiredBySubscription__c, SBQQ__RequiredBySubscription__r.Name, Fee_Type__c, Consult_Fees__c 
                                 FROM Asset WHERE SBQQ__QuoteLine__r.SBQQ__Quote__c in :qteList];
        return assetList;                                                      
    } 
    
    @AuraEnabled(cacheable=true)
    public static List<RecordType> getRecordType() {
        List<RecordType> rtList = [SELECT Id,Name FROM RecordType WHERE SObjectType='Opportunity'];
        
        return rtList;
    } 
    
    @AuraEnabled
    public static void deleteChildRecord(List<Plan_Specific_Fees__c> psfList, List<Contract> contList, List<Asset> assetList, List<SBQQ__Subscription__c> subList){
      
        delete assetList;
        delete psfList;     
        delete subList;
        delete contList;

    }
    
    @AuraEnabled
    public static void editOppAccountQuote(Id recordId, Id recordTypeId){
        List<SBQQ__Quote__c> qteList = [SELECT Id, RecordtypeId FROM SBQQ__Quote__c WHERE SBQQ__Opportunity2__c =:recordId AND SBQQ__Primary__c = TRUE];
        Opportunity opp = [SELECT Id, AccountId FROM Opportunity WHERE Id =: recordId];
        opp.SBQQ__Contracted__c= false;
        opp.CPQ_Contracted_Date__c = null;
        opp.recordtypeId = recordTypeId;
        opp.Is_Requested_Close__c = false;
        update opp;
        Map<Id,opportunity> oppMap = new Map<Id,opportunity>();
        for(opportunity oppRec : [select id,stageName,AccountId from opportunity where AccountId =: opp.AccountId and stageName = :'Closed Won'])
        {
            oppMap.put(oppRec.AccountId,oppRec);
        }
        Account acct = [SELECT Id, Type FROM Account WHERE Id =: opp.AccountId];
        if(!oppMap.containsKey(acct.Id) && acct.Type!= null && acct.Type == 'Customer') {     
            acct.type = 'Prospect';   
            update acct;
        }
        List<SBQQ__Quote__c> quote2Update = new List <SBQQ__Quote__c>();
        for(SBQQ__Quote__c quote : qteList) { 
            quote.recordtypeId = Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByName().get('Teladoc').getRecordTypeId();   
            quote2Update.add(quote);
        } 
        update quote2Update;            
    }
    
    @AuraEnabled
    public static string checkOppReady(Id recordId){
        string errorMsg = null;
        String userProfileName = [select Name from profile where id =: userinfo.getProfileId()].Name;

        if(!userProfileName.contains('System Administrator')) {
            errorMsg = 'Only System Administrator can re-open an opportunity';
            return errorMsg;
        }
        Opportunity opp = [SELECT Id, stageName FROM Opportunity WHERE Id =: recordId];
		if(opp.stageName != 'Closed Won' && opp.stageName != 'Contracting'){
            errorMsg = 'Opportunity stage is not Closed Won or Contracting.';
            return errorMsg;
        }
        
        return errorMsg;
    }
    
    // TODO: rethink logic baesd on contract and not parents acct
    @AuraEnabled
    public static List<Opportunity> checkAmendOpp(Id recordId) {
        List<Opportunity> OppIdList = new List<Opportunity>();
        List<Contract> contList = [SELECT Id FROM Contract WHERE SBQQ__Opportunity__c =: recordId];
        if (contList.size() > 0) {
            List<Opportunity> amendOppList = [SELECT Id, Name FROM Opportunity WHERE SBQQ__AmendedContract__c =: contList[0].Id AND SBQQ__Contracted__c = true];
            if (amendOppList.size() > 0) {
                for(Opportunity opp: amendOppList) {
                    OppIdList.add(opp);
                }
                return OppIdList;
            } else {
                return OppIdList;
            }
        }
       
        return OppIdList;
       
    }
   
    @AuraEnabled
    public static void clearContractedField(Id recordId){
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Id =: recordId];
        opp.Contracted_Date__c = null;
        opp.Contract_Service_Agreement_Status__c = null;
        update opp;
    }
    
}