manifest/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Number_of_Lives__c</fullName>
        <label>Number of Lives</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscribed Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Teladoc_Net_Fee__c</fullName>
        <label>Teladoc Net Fee</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Mbr_Group__c.object
<CustomObject>
    <label>Member Group</label>
    <nameField>
        <displayFormat>MG-{00000000}</displayFormat>
        <label>Member Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Plan_Specific_Fees__c.object
<CustomObject>
    <fields>
        <fullName>Member_Group__c</fullName>
        <label>Member Group</label>
        <referenceTo>Mbr_Group__c</referenceTo>
        <relationshipLabel>Plan-Specific Fees By Product</relationshipLabel>
        <relationshipName>Plan_Specific_Fees_By_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Plan-Specific Fees By Product</relationshipLabel>
        <relationshipName>Plan_Specific_Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Teladoc_Net_Fee__c</fullName>
        <formula>Product_Under_Contract__r.Teladoc_Net_Fee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Teladoc Net Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Plan-Specific Fees By Product</label>
    <nameField>
        <displayFormat>PSF-{0000000}</displayFormat>
        <label>Plan Fees ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan-Specific Fees By Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product used to sell this subscription.</description>
        <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/classes/PsfMassCreate_Test.cls
@IsTest
private class PsfMassCreate_Test {
  @TestSetup
  static void testsetup() {
    Account umrAcct = TestDataFactory.createUMR();
    List<Account> acct = new List<Account>();
      Test.startTest();
    Account a = TestDataFactory.createAccountUMRNoInsert();
    acct.add(a);
    insert acct;

    List<Mbr_Group__c> mg = TestDataFactory.createMbrGroupList(a.Id);

    List<Product2> pd = new List<Product2>();

    Product2 prod = TestDataFactory.CreateProductWithDynamicVals(
      'Dermatology',
      'Dermatology',
      'DERM'
    );
    pd.add(prod);

    Product2 prod2 = TestDataFactory.CreateProductWithDynamicVals(
      'Dermatology',
      'Dermatology',
      'DERMFEE'
    );
    pd.add(prod2);

    Product2 prod3 = TestDataFactory.CreateProductWithDynamicVals(
      'Tobacco Cessation',
      'Tobacco Cessation',
      'TCPROGFEE'
    );
    pd.add(prod3);

    Product2 prod3_1 = TestDataFactory.CreateProductWithDynamicVals(
      'Tobacco Cessation',
      'Tobacco Cessation',
      'TCPROGFEE'
    );
    pd.add(prod3_1);

    Product2 prod4 = TestDataFactory.CreateProductWithDynamicVals(
      'General Medical',
      'General Medical',
      'GM'
    );
    pd.add(prod4);

    Product2 prod5 = TestDataFactory.CreateProductWithDynamicVals(
      'Behavioral Health',
      'Behavioral Health',
      'BHNPT'
    );
    pd.add(prod5);

    Product2 prod6 = TestDataFactory.CreateProductWithDynamicVals(
      'Behavioral Health',
      'Behavioral Health',
      'BHP1T'
    );
    pd.add(prod6);

    Product2 prod7 = TestDataFactory.CreateProductWithDynamicVals(
      'Behavioral Health',
      'Behavioral Health',
      'BHPOT'
    );
    pd.add(prod7);

    Product2 prod8 = TestDataFactory.CreateProductWithDynamicVals(
      'Behavioral Health',
      'Behavioral Health',
      'BH'
    );
    pd.add(prod8);
    insert pd;

    List<SBQQ__Subscription__c> subL = new List<SBQQ__Subscription__c>();

    SBQQ__Subscription__c sub = TestDataFactory.createSBQQSubscripWithProdNoInsert(
      acct[0].Id,
      pd[0].Id
    );
    subL.add(sub);

    SBQQ__Subscription__c sub2 = TestDataFactory.createSBQQSubscripWithProdNoInsert(
      acct[0].Id,
      prod3.Id
    );
    subL.add(sub2);

    SBQQ__Subscription__c sub3 = TestDataFactory.createSBQQSubscripWithProdNoInsert(
      acct[0].Id,
      prod4.Id
    );
    subL.add(sub3);

    SBQQ__Subscription__c sub4 = TestDataFactory.createSBQQSubscripWithProdNoInsert(
      acct[0].Id,
      prod8.Id
    );
    subL.add(sub4);
    insert subL;

    Plan_Specific_Fees__c gpRec = TestDataFactory.createSinglePlanSpecificFees(
      mg[0].Id,
      sub.Id
    );
Test.stopTest();
    List<Asset> assetL = new List<Asset>();
    Asset ast = TestDataFactory.createAssetNoInsert(
      'test asset',
      0.30,
      a.Id,
      null,
      prod2.Id,
      sub.Id
    );
    assetL.add(ast);

    Asset ast3 = TestDataFactory.createAssetNoInsert(
      'test asset',
      0.60,
      a.Id,
      null,
      prod5.Id,
      sub4.Id
    );
    ast3.Number_of_Lives__c = 1000;
    ast3.Teladoc_Net_Fee__c = 0.80;
    ast3.InstallDate = Date.today();
    assetL.add(ast3);

    Asset ast4 = TestDataFactory.createAssetNoInsert(
      'test asset',
      0.60,
      a.Id,
      null,
      prod6.Id,
      sub4.Id
    );
    ast4.Number_of_Lives__c = 1000;
    ast4.Teladoc_Net_Fee__c = 0.80;
    ast4.InstallDate = Date.today();

    assetL.add(ast4);
    Asset astt = TestDataFactory.createAssetNoInsert(
      'test asset',
      0.60,
      a.Id,
      null,
      prod7.Id,
      sub4.Id
    );
    astt.Number_of_Lives__c = 1000;
    astt.Teladoc_Net_Fee__c = 0.80;
    astt.InstallDate = Date.today();
    assetL.add(astt);
    insert assetL;
  }

  @IsTest
  static void psfCreateTest() {
    SBQQ__Subscription__c subGM = [
      SELECT Id
      FROM SBQQ__Subscription__c
      WHERE SBQQ__Product__r.ProductCode = 'GM'
    ];
    PsfMassCreate.CreateForSubscription(subGM.Id);
    List<Plan_Specific_Fees__c> subscriptionPsf = [
      SELECT id, Member_Group__c
      FROM Plan_Specific_Fees__c
      WHERE subscription__c = :subGM.Id
    ];
    System.assertEquals(10, subscriptionPsf.size());
Test.startTest();
    SBQQ__Subscription__c subDERM = [
      SELECT Id
      FROM SBQQ__Subscription__c
      WHERE SBQQ__Product__r.ProductCode = 'DERM'
    ];
    PsfMassCreate.CreateForSubscription(subDERM.Id);
    subscriptionPsf = [
      SELECT id, Member_Group__c
      FROM Plan_Specific_Fees__c
      WHERE subscription__c = :subDERM.Id
    ];
    System.assertEquals(10, subscriptionPsf.size());

    SBQQ__Subscription__c subTC = [
      SELECT Id
      FROM SBQQ__Subscription__c
      WHERE SBQQ__Product__r.ProductCode = 'TCPROGFEE'
    ];
    PsfMassCreate.CreateForSubscription(subTC.Id);
    subscriptionPsf = [
      SELECT id, Member_Group__c
      FROM Plan_Specific_Fees__c
      WHERE subscription__c = :subTC.Id
    ];
    System.assertEquals(10, subscriptionPsf.size());

    SBQQ__Subscription__c subBH = [
      SELECT Id
      FROM SBQQ__Subscription__c
      WHERE SBQQ__Product__r.ProductCode = 'BH'
    ];
      Test.stopTest();
    PsfMassCreate.CreateForSubscription(subBH.Id);
    subscriptionPsf = [
      SELECT id, Member_Group__c
      FROM Plan_Specific_Fees__c
      WHERE subscription__c = :subBH.Id
    ];
    System.assertEquals(30, subscriptionPsf.size());
  }
}