manifest/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Consult_Fees__c</fullName>
        <label>Consult Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Number_of_Lives__c</fullName>
        <label>Number of Lives</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__RequiredBySubscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The parent Subscription. If populated, this Asset is a child in a bundle.</inlineHelpText>
        <label>Required By Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Assets (Required By Subscription)</relationshipLabel>
        <relationshipName>ChildAssets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscribed Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Teladoc_Net_Fee__c</fullName>
        <label>Teladoc Net Fee</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Mbr_Group__c.object
<CustomObject>
    <fields>
        <fullName>Active_Date__c</fullName>
        <description>Date Group was built in Admin</description>
        <inlineHelpText>Date Group was built in Admin</inlineHelpText>
        <label>Active Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Copay_May_Be_Less__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for RTE clients where copay amount is determined by their deductible or individual file, and may be less than the listed consult fee.  This value at Group level will determine if PSF records will have this box checked or not.</description>
        <inlineHelpText>Used for RTE clients where copay amount is determined by their deductible or individual file, and may be less than the listed consult fee</inlineHelpText>
        <label>Actual Copay May Be Less</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <description>Account that the Group is created</description>
        <inlineHelpText>Account that the Group is created</inlineHelpText>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Member Groups</relationshipLabel>
        <relationshipName>Member_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Enter a descriptive Member Group Name.</description>
        <inlineHelpText>Enter a descriptive Member Group Name.</inlineHelpText>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Use this as a backend field to identify the source of member group record</description>
        <inlineHelpText>Use this as a backend field to identify the source of member group record</inlineHelpText>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Data_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Group Status</description>
        <inlineHelpText>Group Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>PENDING</fullName>
                    <default>true</default>
                    <label>PENDING</label>
                </value>
                <value>
                    <fullName>TERMED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Member Group</label>
    <nameField>
        <displayFormat>MG-{00000000}</displayFormat>
        <label>Member Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Mbr_Group_Role__c.object
<CustomObject>
    <fields>
        <fullName>Mbr_Group__c</fullName>
        <description>SF Record name of the Group</description>
        <inlineHelpText>SF Record name of the Group</inlineHelpText>
        <label>Member Group</label>
        <referenceTo>Mbr_Group__c</referenceTo>
        <relationshipLabel>Member Group Roles</relationshipLabel>
        <relationshipName>Member_Group_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role_Type__c</fullName>
        <description>Type of association with Group</description>
        <inlineHelpText>Type of association with Group</inlineHelpText>
        <label>Role Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Fee_Group_Role_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account that is servicing the type of role</description>
        <inlineHelpText>Account that is servicing the type of role</inlineHelpText>
        <label>Source Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Member Group Roles</relationshipLabel>
        <relationshipName>Member_Group_Roles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Member Group Role</label>
    <nameField>
        <displayFormat>MGR-{00000000}</displayFormat>
        <label>Member Group Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Group Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Plan_Specific_Fees__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Copay_May_Be_Less__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Actual Copay May Be Less</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Plan-Specific Fees By Product (Asset)</relationshipLabel>
        <relationshipName>Plan_Specific_Fees_By_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consult_Fee_Mbr_Pd__c</fullName>
        <label>Consult Fee - Mbr Pd</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Consult_Fee_Plan_Pd__c</fullName>
        <label>Consult Fee - Plan Pd</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Consult_Frequency__c</fullName>
        <label>Consult Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Per Year</fullName>
                </value>
                <value>
                    <fullName>Per Life</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Consults_per_Family__c</fullName>
        <label>Consults per Family</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Member_Group__c</fullName>
        <label>Member Group</label>
        <referenceTo>Mbr_Group__c</referenceTo>
        <relationshipLabel>Plan-Specific Fees By Product</relationshipLabel>
        <relationshipName>Plan_Specific_Fees_By_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Start_Date__c</fullName>
        <label>Product Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Plan-Specific Fees By Product</relationshipLabel>
        <relationshipName>Plan_Specific_Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Teladoc_Net_Fee__c</fullName>
        <formula>Product_Under_Contract__r.Teladoc_Net_Fee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Teladoc Net Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Plan-Specific Fees By Product</label>
    <nameField>
        <displayFormat>PSF-{0000000}</displayFormat>
        <label>Plan Fees ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan-Specific Fees By Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/PSF_Permission_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuration to allow deletion of PSF records</description>
    <fields>
        <fullName>User_Permission__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Group of users that are allowed to delete PSF records.</description>
        <label>User Permission</label>
        <type>Checkbox</type>
    </fields>
    <label>PSF Permission Setting</label>
</CustomObject>

manifest/objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>Consult_Fees__c</fullName>
        <label>Consult Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account that owns this subscription. This relationship is used for volume discount calculations.</description>
        <inlineHelpText>Account that owns this subscription. This relationship is used for volume discount calculations.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product used to sell this subscription.</description>
        <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity of this subscription product purchased by the customer.</description>
        <inlineHelpText>Quantity of this subscription product purchased by the customer.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Active</fullName>
                    <default>true</default>
                    <label>Not Yet Active</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/globalValueSets/Data_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>HUB</fullName>
        <default>true</default>
        <label>HUB</label>
    </customValue>
    <customValue>
        <fullName>TD</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>LVGO</fullName>
    </customValue>
    <customValue>
        <fullName>GCRM</fullName>
    </customValue>
    <masterLabel>Data Source</masterLabel>
</GlobalValueSet>

manifest/globalValueSets/Fee_Group_Role_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Benefit Sponsor</fullName>
    </customValue>
    <customValue>
        <fullName>Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Contractee</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Payer</fullName>
    </customValue>
    <customValue>
        <fullName>MSU Access</fullName>
    </customValue>
    <masterLabel>Fee Group Role Type</masterLabel>
</GlobalValueSet>

manifest/classes/MassPsfPageLwc_Controller_Test.cls
@IsTest
private class MassPsfPageLwc_Controller_Test {
    @TestSetup
    static void testsetup() {
        
        PSF_Permission_Setting__c objDS=new PSF_Permission_Setting__c(SetupOwnerId=UserInfo.getUserId(),User_Permission__c=true);
        insert objDS;
        Account umrAcct = TestDataFactory.createUMR();
        Account a = new Account(Name = 'Test01', Source__c = 'HUB');
		insert a;
        Account testAcc = new Account(Name = 'Test02', Source__c = 'HUB');
		insert testAcc;
        
        List<Mbr_Group__c> mg = new List<Mbr_Group__c>();
        Mbr_Group__c grp = new Mbr_Group__c(Name__c = 'testgrp1', Client_Account__c = a.Id, Status__c = 'ACTIVE', Active_Date__c = Date.today());
        mg.add(grp);
        Mbr_Group__c grp2 = new Mbr_Group__c(Name__c = 'testgrp2', Client_Account__c = a.Id, Status__c = 'ACTIVE', Active_Date__c = Date.today());
        mg.add(grp2);
        insert mg;
        Mbr_Group_Role__c r = new Mbr_Group_Role__c(Role_Type__c = 'Payer', Source_Account__c = testAcc.Id, Mbr_Group__c = mg[0].Id);
        insert r;
        Mbr_Group_Role__c r2 = new Mbr_Group_Role__c(Role_Type__c = 'Billing', Source_Account__c = testAcc.Id, Mbr_Group__c = mg[0].Id);
        insert r2;
        Mbr_Group_Role__c r3 = new Mbr_Group_Role__c(Role_Type__c = 'Contractee', Source_Account__c = testAcc.Id, Mbr_Group__c = mg[0].Id);
        insert r3;
		
        List<Product2> pd = new List<Product2>();
        Product2 prod = new Product2(Name = 'GLOBALCARE', Family = 'GLOBAL CARE', ProductCode = 'GLOBALCARE', IsActive = true);
        pd.add(prod);
        Product2 prod2 = new Product2(Name = 'Dermatology', Family = 'Dermatology', ProductCode = 'DERM', IsActive = true);
        pd.add(prod2);
        Product2 prod3 = new Product2( Name = 'Tobacco Cessation', Family = 'Tobacco Cessation', ProductCode = 'TC', IsActive = true);
        pd.add(prod3);
        Product2 prod4 = new Product2(Name = 'General Medical', Family = 'General Medical', ProductCode = 'GM', IsActive = true);
        pd.add(prod4);
        Product2 prod5 = new Product2(Name = 'Behavioral Health', Family = 'Behavioral Health', ProductCode = 'BH', IsActive = true);
        pd.add(prod5);
        Product2 prod6 = new Product2(Name = 'Back Care', Family = 'Musculoskelatal', ProductCode = 'TDBC', IsActive = true);
        pd.add(prod6);
        Product2 prod7 = new Product2(Name = 'test1', Family = 'Musculoskelatal', ProductCode = 'TDBC', IsActive = true);
        pd.add(prod7);
        Product2 prod8 = new Product2(Name = 'Nutrition', Family = 'Nutrition', ProductCode = 'NUT', IsActive = true);
        pd.add(prod8);
        Product2 prod9 = new Product2(Name = 'NUTFEE', Family = 'Nutrition', ProductCode = 'NUTFEE', IsActive = true);
        pd.add(prod9);
        insert pd;
        Plan_Specific_Fees__c gpRec = new Plan_Specific_Fees__c(Member_Group__c = grp.Id, Consult_Fee_Mbr_Pd__c = 0.80, Consults_per_Family__c = 4, Consult_Fee_Plan_Pd__c = 0.80, Consult_Frequency__c = 'Per Year');
        insert gpRec;
        List<SBQQ__Subscription__c> subL = new List<SBQQ__Subscription__c>();
        SBQQ__Subscription__c sub12 = new SBQQ__Subscription__c(SBQQ__Account__c = a.Id, Status__c = 'Active', SBQQ__Quantity__c = 500, Consult_Fees__c = 0.90, SBQQ__Product__c = prod9.Id);
        subL.add(sub12);
        SBQQ__Subscription__c sub11 = new SBQQ__Subscription__c(SBQQ__Account__c = a.Id, Status__c = 'Active', SBQQ__Quantity__c = 500, Consult_Fees__c = 0.90, SBQQ__Product__c = prod6.Id);
        subL.add(sub11);
        SBQQ__Subscription__c sub9 = new SBQQ__Subscription__c(SBQQ__Account__c = a.Id, Status__c = 'Active', SBQQ__Quantity__c = 500, Consult_Fees__c = 0.90, SBQQ__Product__c = prod8.Id);
        subL.add(sub9);
        SBQQ__Subscription__c sub8 = new SBQQ__Subscription__c(SBQQ__Account__c = a.Id, Status__c = 'Active', SBQQ__Quantity__c = 500, Consult_Fees__c = 0.90, SBQQ__Product__c = prod7.Id);
        subL.add(sub8);
        SBQQ__Subscription__c sub = new SBQQ__Subscription__c(SBQQ__Account__c = a.Id, Status__c = 'Active', SBQQ__Quantity__c = 500, Consult_Fees__c = 0.90, SBQQ__Product__c = prod.Id);
        subL.add(sub);
        SBQQ__Subscription__c sub2 = new SBQQ__Subscription__c(SBQQ__Account__c = a.Id, Status__c = 'Active', SBQQ__Quantity__c = 500, Consult_Fees__c = 0.90, SBQQ__Product__c = prod5.Id);
        subL.add(sub2);       
        SBQQ__Subscription__c sub3 = new SBQQ__Subscription__c(SBQQ__Account__c = a.Id, Status__c = 'Active', SBQQ__Quantity__c = 500, Consult_Fees__c = 0.90, SBQQ__Product__c = prod4.Id);
        subL.add(sub3);
        SBQQ__Subscription__c sub4 = new SBQQ__Subscription__c( SBQQ__Account__c = a.Id, Status__c = 'Active', SBQQ__Quantity__c = 500, Consult_Fees__c = 0.90, SBQQ__Product__c = prod3.Id);
        subL.add(sub4);
        SBQQ__Subscription__c sub5 = new SBQQ__Subscription__c( SBQQ__Account__c = a.Id, Status__c = 'Active', SBQQ__Quantity__c = 500, Consult_Fees__c = 0.90, SBQQ__Product__c = prod2.Id);
        subL.add(sub5);
        insert subL;
        gpRec.Subscription__c = sub.Id;
        gpRec.Product_Start_Date__c = Date.Today();
        gpRec.Actual_Copay_May_Be_Less__c = TRUE;
        update gpRec;
        List<Asset> assetL = new List<Asset>();
        Asset ast = new Asset(AccountId = a.Id, Consult_Fees__c = null, Number_of_Lives__c = null, Teladoc_Net_Fee__c = null, InstallDate = Date.today(), Product2Id = prod.Id, Name = 'test asset', SBQQ__RequiredBySubscription__c = sub.Id);
        assetL.add(ast); 
        Asset ast3 = new Asset(AccountId = a.Id, Consult_Fees__c = 0.60, Number_of_Lives__c = 1000, Teladoc_Net_Fee__c = 0.80, InstallDate = Date.today(), Product2Id = prod3.Id, Name = 'test asset', SBQQ__RequiredBySubscription__c = sub3.Id);
        assetL.add(ast3);
        Asset ast4 = new Asset(
            AccountId = a.Id,
            Consult_Fees__c = 0.60,
            Number_of_Lives__c = 1000,
            Teladoc_Net_Fee__c = 0.80,
            InstallDate = Date.today(),
            Product2Id = prod4.Id,
            Name = 'test asset',
            SBQQ__RequiredBySubscription__c = sub4.Id
        );
        assetL.add(ast4);
        
        Asset astt = new Asset(
            AccountId = a.Id,
            Consult_Fees__c = 0.60,
            Number_of_Lives__c = 1000,
            Teladoc_Net_Fee__c = 0.80,
            InstallDate = Date.today(),
            Product2Id = prod4.Id,
            Name = 'test asset',
            SBQQ__RequiredBySubscription__c = sub9.Id
        );
        assetL.add(astt);
        
        Asset astt1 = new Asset(
            AccountId = a.Id,
            Consult_Fees__c = 0.60,
            Number_of_Lives__c = 1000,
            Teladoc_Net_Fee__c = 0.80,
            InstallDate = Date.today(),
            Product2Id = prod4.Id,
            Name = 'test asset',
            SBQQ__RequiredBySubscription__c = sub11.Id
        );
        assetL.add(astt1);
        
        Asset astt2 = new Asset(
            AccountId = a.Id,
            Consult_Fees__c = 0.60,
            Number_of_Lives__c = 1000,
            Teladoc_Net_Fee__c = 0.80,
            InstallDate = Date.today(),
            Name = 'test asset',
            SBQQ__RequiredBySubscription__c = sub12.Id
        );
        assetL.add(astt2);
        
        Asset ast5 = new Asset(
            AccountId = a.Id,
            Consult_Fees__c = null,
            Number_of_Lives__c = 1000,
            Teladoc_Net_Fee__c = 0.80,
            InstallDate = Date.today(),
            Product2Id = prod5.Id,
            Name = 'test asset',
            SBQQ__RequiredBySubscription__c = sub5.Id
        );
        assetL.add(ast5);
        
        Asset ast6 = new Asset(
            AccountId = a.Id,
            Consult_Fees__c = 0.60,
            Number_of_Lives__c = 1000,
            Teladoc_Net_Fee__c = 0.80,
            InstallDate = Date.today(),
            Product2Id = prod2.Id,
            Name = 'Consult Fee- Psych/MD-1stvisitonly-Total',
            SBQQ__RequiredBySubscription__c = sub2.Id
        );
        assetL.add(ast6);
        
        Asset ast7 = new Asset(
            AccountId = a.Id,
            Consult_Fees__c = 0.60,
            Number_of_Lives__c = 1000,
            Teladoc_Net_Fee__c = 0.80,
            InstallDate = Date.today(),
            Product2Id = prod2.Id,
            Name = 'Consult Fee- Non-Psychiatrist- Total',
            SBQQ__RequiredBySubscription__c = sub2.Id
        );
        assetL.add(ast7);
        
        Asset ast2 = new Asset(
            AccountId = a.Id,
            Consult_Fees__c = 0.60,
            Number_of_Lives__c = 1000,
            Teladoc_Net_Fee__c = 0.80,
            InstallDate = Date.today(),
            Product2Id = prod2.Id,
            Name = 'Consult Fee- Psych/MD-ONGOING-Total',
            SBQQ__RequiredBySubscription__c = sub2.Id
        );
        assetL.add(ast2);
        insert assetL;
    }
    
    @IsTest
    static void findSub() {
        Mbr_Group__c mg = [SELECT Id, Client_Account__r.Id FROM Mbr_Group__c WHERE Name__c ='testgrp1' LIMIT 1];
        string mgId = string.valueOf(mg.id);
        MassPsfPageLwc_Controller.findSub(mgId);             
    }
    
    @IsTest
    static void mgName() {
        Mbr_Group__c mg = [SELECT Id, Client_Account__r.Id FROM Mbr_Group__c WHERE Name__c ='testgrp1' LIMIT 1];
        string mgId = string.valueOf(mg.id);
        String NameString = MassPsfPageLwc_Controller.mgName(mgId);  
        system.assertEquals('testgrp1', NameString);
    }
    
    @IsTest
    static void deletePSF() {
        Plan_Specific_Fees__c psf = [SELECT Id, Subscription__c, Member_Group__c FROM Plan_Specific_Fees__c];
        MassPsfPageLwc_Controller.deletePSF(psf.Member_Group__c, psf.Subscription__c);  
        system.assertEquals(0, [SELECT count() FROM Plan_Specific_Fees__c]);
    }
    
    @IsTest
    static void getHistories() {
        Plan_Specific_Fees__c psf = [SELECT Id, Member_Group__c, Subscription__c FROM Plan_Specific_Fees__c];
        List<Plan_Specific_Fees__History> psfHist = MassPsfPageLwc_Controller.getHistories(psf.Member_Group__c, psf.Subscription__c); 
        system.assertEquals(0, psfHist.size());
    }
    @IsTest
    static void getPSF() {
        Plan_Specific_Fees__c psf = [SELECT Id, Member_Group__c FROM Plan_Specific_Fees__c];
        MassPsfPageLwc_Controller.getPSF(psf.id);  
    }
    
     @IsTest
    static void getMbrGrpRoles() {
        //Mbr_Group__c mg = [SELECT Id, Client_Account__r.Id FROM Mbr_Group__c WHERE Name__c ='testgrp1' LIMIT 1];
        List<Mbr_Group_Role__c> mbrGrpList = [SELECT Id, Role_Type__c, Source_Account__c, Mbr_Group__c FROM Mbr_Group_Role__c WHERE 
                                              Role_Type__c IN ('Payer', 'Contractee', 'Billing')];
        string mgId = string.valueOf(mbrGrpList[0].Mbr_Group__c);
        string psfId = '';
        system.debug('PSFS:: ' + mgId);
        MassPsfPageLwc_Controller.getMbrGrpRoles(mgId,psfId);  
        Plan_Specific_Fees__c psfRecord = [SELECT Id, Member_Group__c FROM Plan_Specific_Fees__c WHERE Member_Group__c =:mgId LIMIT 1];
        MassPsfPageLwc_Controller.getMbrGrpRoles(mgId,psfRecord.Id); 
        
    }
    
    @IsTest
    static void findObjTypeTest() {
        Account acct = [SELECT Id FROM Account WHERE Name = 'Test01'];
        String objType = MassPsfPageLwc_Controller.findObjType(acct.Id);
        system.assertEquals('Account' , objType);
    }
    
    @IsTest
    static void createUpdateDeleteBHTest() {
        List<Plan_Specific_Fees__c> psfList = new List<Plan_Specific_Fees__c>();
        Mbr_Group__c mbrGroup = [SELECT Id FROM Mbr_Group__c LIMIT 1];
        SBQQ__Subscription__c sub = [SELECT Id FROM SBQQ__Subscription__c WHERE SBQQ__Product__r.ProductCode = 'BH'];
        Asset BHP1TAsset = [SELECT Id FROM Asset WHERE Name = 'Consult Fee- Psych/MD-1stvisitonly-Total'];
        Asset BHPOTAsset = [SELECT Id FROM Asset WHERE Name = 'Consult Fee- Psych/MD-ONGOING-Total'];
        Asset BHNPTAsset = [SELECT Id FROM Asset WHERE Name = 'Consult Fee- Non-Psychiatrist- Total'];
        Plan_Specific_Fees__c psf1 = new Plan_Specific_Fees__c();
        psf1.Asset__c = BHP1TAsset.Id;
        psf1.Consult_Fee_Mbr_Pd__c = 0.6;
        psf1.Member_Group__c = mbrGroup.Id;
        psf1.Subscription__c = sub.Id;
        psfList.add(psf1);
        Plan_Specific_Fees__c psf2 = new Plan_Specific_Fees__c();
        psf2.Asset__c = BHPOTAsset.Id;
        psf2.Consult_Fee_Mbr_Pd__c = 0.6;
        psf2.Member_Group__c = mbrGroup.Id;
        psf2.Subscription__c = sub.Id;
        psfList.add(psf2);
        Plan_Specific_Fees__c psf3 = new Plan_Specific_Fees__c();
        psf3.Asset__c = BHNPTAsset.Id;
        psf3.Consult_Fee_Mbr_Pd__c = 0.6;
        psf3.Member_Group__c = mbrGroup.Id;
        psf3.Subscription__c = sub.Id;
        psfList.add(psf3);
        MassPsfPageLwc_Controller.createPSF(psfList);
        system.assertEquals(4, [SELECT Count() FROM Plan_Specific_Fees__c]);
		psf1.Actual_Copay_May_Be_Less__c = true;
        List<Plan_Specific_Fees__c> updateList = new List<Plan_Specific_Fees__c>();
        updateList.add(psf1);
        updateList.add(psf2);
        updateList.add(psf3);
        MassPsfPageLwc_Controller.updatePSF(updateList, mbrGroup.Id, sub.Id);
        MassPsfPageLwc_Controller.deletePSF(mbrGroup.Id, sub.Id);
        system.assertEquals(1, [SELECT Count() FROM Plan_Specific_Fees__c]);
    }
  
}