manifest/objects/Briefing__c.object
<CustomObject>
    <fields>
        <fullName>Briefing_Name__c</fullName>
        <label>Briefing Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Virtual</fullName>
                </value>
                <value>
                    <fullName>Santa Barbara</fullName>
                </value>
                <value>
                    <fullName>Barcelona</fullName>
                    <isActive>false</isActive>
                    <label>Barcelona</label>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                    <isActive>false</isActive>
                    <label>Dallas</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Briefings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Preferred_Date__c</fullName>
        <inlineHelpText>1 week lead time preferred.</inlineHelpText>
        <label>Preferred Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Products2__c</fullName>
        <label>Products</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_Time_Zone__c</fullName>
        <label>Request Time Zone</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Eastern</fullName>
                </value>
                <value>
                    <fullName>Central</fullName>
                </value>
                <value>
                    <fullName>Mountain</fullName>
                </value>
                <value>
                    <fullName>Pacific</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Experience Center Briefing Request</label>
    <nameField>
        <displayFormat>ECBR-{0000}</displayFormat>
        <label>Briefing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Experience Center Briefing Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Location__c.object
<CustomObject>
    <description>Used to store non-contractual locations such as broker locations, hospitals, and stores</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this Opportunity Product.</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>OpportunityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

manifest/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/classes/ExperienceCenter_Before_Test.cls
@isTest
private class ExperienceCenter_Before_Test {
  @testSetup
  static void setupdata() {
    Account accObj = TestDataFactory.createAccountUMR();

    Id pricebookId = Test.getStandardPricebookId();

    //create an opportunity record
    Opportunity oppObj = TestDataFactory.createOpportunityWithPriceBook(
      accObj.Id,
      pricebookId,
      null
    );
    oppObj.LeadSource = 'Sales';
    insert oppObj;

    //create Gen Med product
    Product2 prod2 = TestDataFactory.createSingleProduct(
      'General Medical',
      'General Medical',
      'GM'
    );
    insert prod2;

    PricebookEntry pbEntry = TestDataFactory.createPriceBookEntries(
      new List<Product2>{ prod2 },
      pricebookId
    )[0];
    insert pbEntry;

    //Create a quote record
    SBQQ__Quote__c quoObj = TestDataFactory.createQuote(oppObj.Id);
    insert quoObj;
  }
  @isTest
  static void experienceCenterTriggerTest() {
    test.startTest();
    Opportunity oppObj = [SELECT Id FROM Opportunity];
    SBQQ__Quote__c q = [SELECT Id FROM SBQQ__Quote__c];
    Product2 prod = [SELECT Id FROM Product2];
    PricebookEntry pbEntry = [SELECT Id, UnitPrice FROM PricebookEntry];
    SBQQ__QuoteLine__c quoline1 = TestDataFactory.createQuoteLine(
      q.Id,
      prod.Id
    );
    insert quoline1;

    OpportunityLineItem opl = TestDataFactory.createOLI(
      oppObj.Id,
      pbEntry.Id,
      null
    );
    opl.TotalPrice = 500 * pbEntry.UnitPrice;

    insert opl;

    Briefing__c ecbr = new Briefing__c();
    ecbr.opportunity__c = oppObj.Id;
    ecbr.location__c = 'Virtual';
    ecbr.Preferred_Date__c = DateTime.newInstance(2021, 6, 6, 3, 3, 3);
    ecbr.Request_Time_Zone__c = 'Eastern';
    insert ecbr;

    Briefing__c testEcbr = [
      SELECT Products2__c, Briefing_Name__c
      FROM Briefing__c
    ];
    system.assertEquals(
      'General Medical, General Medical',
      testEcbr.Products2__c
    );
    system.assertEquals(
      'TestAmendAccount Virtual ' +
        Date.today().month() +
        '-' +
        Date.today().year(),
      testEcbr.Briefing_Name__c
    );
    test.stoptest();
  }
}