manifest/objects/BusItem__c.object
<CustomObject>
    <description>Used to transport information between instances</description>
    <fields>
        <fullName>GUID__c</fullName>
        <description>Item GUID for tracking across instances</description>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>36</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Payload__c</fullName>
        <description>JSON payload</description>
        <label>Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has this record been processed/send + acknowledged</description>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_to__c</fullName>
        <label>Send to</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceOwnerId__c</fullName>
        <label>SourceOwnerId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceUrl__c</fullName>
        <description>What started this exchange</description>
        <label>SourceUrl</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>where did this payload come from</description>
        <label>Source</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>BusItem</label>
    <nameField>
        <displayFormat>BI-{00000000}</displayFormat>
        <label>BusItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BusItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Allow_ITH_Transfer__c</fullName>
        <formula>If( AND ( OR(text(Status) ==&apos;AQL&apos;, text(Status) ==&apos;MQL&apos;), !ISBLANK(FirstName), !ISBLANK(LastName), !ISBLANK(Email), !ISBLANK(Phone), !ISBLANK(Company)), true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Allow ITH Transfer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Microsoft_Involved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Microsoft Involved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HUB</fullName>
                    <default>true</default>
                    <label>HUB</label>
                </value>
                <value>
                    <fullName>LV</fullName>
                </value>
                <value>
                    <fullName>BD</fullName>
                    <isActive>false</isActive>
                    <label>BD</label>
                </value>
                <value>
                    <fullName>TD</fullName>
                    <isActive>false</isActive>
                    <label>TD</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transferred_To__c</fullName>
        <inlineHelpText>Select the company this lead is transferred to.</inlineHelpText>
        <label>Transferred To</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>ITH</fullName>
                </value>
                <value>
                    <fullName>Livongo</fullName>
                    <isActive>false</isActive>
                    <label>Livongo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

manifest/classes/TDH2ITH_Lead_Controller.cls
public without sharing class TDH2ITH_Lead_Controller {
  @AuraEnabled
  public static Lead getLead(String recordId) {
    Lead ld = [
      SELECT
        Id,
        Status,
        allow_ith_transfer__c,
        Microsoft_Involved__c,
        FirstName,
        OwnerId,
        LastName,
        Title,
        Company,
        Description,
        Email,
        Street,
        City,
        State,
        Postalcode,
        Country,
        Phone
      FROM Lead
      WHERE Id = :recordId
    ];
    return ld;
  }

  @AuraEnabled
  public static resWrapper sendRecord(Lead ld) {
    String jsonString = JSON.serialize(ld);
    EtlItem newItem = new EtlItem();
    newItem.parserName = 'Lead';
    newItem.requestVersion = '1.0';
    newItem.payload = jsonString;
    String jsonstr = JSON.serialize(newItem);
    system.debug(jsonstr);
    HttpRequest req1 = new HttpRequest();
    req1.setEndpoint('callout:ITH_Org/services/apexrest/tdh2ithbus/');
    req1.setMethod('POST');
    req1.setHeader('Content-Type', 'application/json');
    req1.setHeader('accept', 'application/json');
    req1.setBody(jsonstr);
    Http http = new Http();
    HTTPResponse res1 = http.send(req1);
    while (res1.getStatusCode() == 302) {
      req1.setEndpoint(res1.getHeader('Location'));
      res1 = new Http().send(req1);
    }

    BusItem__c busItem = new BusItem__c();
    busItem.Payload__c = jsonString;
    busItem.Processed__c = false;
    busItem.Source__c = 'TDH';
    busItem.Send_to__c = 'ITH';
    busItem.GUID__c = GlobalIdUtils.generateGuid();
    busItem.SourceOwnerId__c = ld.OwnerId;
    busItem.SourceUrl__c =
      URL.getOrgDomainUrl().toExternalForm() +
      '/' +
      ld.Id;

    if (res1.getStatusCode() != 200) {
      busItem.Status__c = 'Callout_Status: ' + res1.getStatusCode();
      resWrapper resWrapper = new resWrapper(
        'false',
        'ERROR CODE: ' + String.valueOf(res1.getStatusCode())
      );
      insert busItem;
      return resWrapper;
    } else {
      busItem.Status__c = 'RESPONSE_BODY ' + res1.getbody();
      busItem.Processed__c = true;
      insert busItem;
      String res = res1.getbody().unescapeEcmaScript();
      res = res.substring(1, res.length() - 1);
      resWrapper deserializedRes = (resWrapper) JSON.deserialize(
        res,
        resWrapper.class
      );
      if (deserializedRes.isInsert == 'true') {
        ld.Transferred_To__c = 'ITH';
        update ld;
      }
      return deserializedRes;
    }
  }

  public class resWrapper {
    @auraEnabled
    public String isInsert { get; set; }
    @auraEnabled
    public String result { get; set; }
    public resWrapper(String isInsert, String result) {
      this.isInsert = isInsert;
      this.result = result;
    }
  }
}