manifest/objects/BusItem__c.object
<CustomObject>
    <description>Used to transport information between instances</description>
    <fields>
        <fullName>GUID__c</fullName>
        <description>Item GUID for tracking across instances</description>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>36</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Payload__c</fullName>
        <description>JSON payload</description>
        <label>Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has this record been processed/send + acknowledged</description>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_to__c</fullName>
        <label>Send to</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceOwnerId__c</fullName>
        <label>SourceOwnerId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceUrl__c</fullName>
        <description>What started this exchange</description>
        <label>SourceUrl</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>where did this payload come from</description>
        <label>Source</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>BusItem</label>
    <nameField>
        <displayFormat>BI-{00000000}</displayFormat>
        <label>BusItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BusItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Allow_Transfer__c</fullName>
        <formula>If( AND ( OR(text(Status) ==&apos;AQL&apos;, text(Status) ==&apos;MQL&apos;), !ISBLANK(FirstName), !ISBLANK(LastName), !ISBLANK(Email), !ISBLANK(Phone), !ISBLANK(Company), !ISBLANK(TEXT(Transferred_To__c))), true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Allow Transfer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HUB</fullName>
                    <default>true</default>
                    <label>HUB</label>
                </value>
                <value>
                    <fullName>LV</fullName>
                </value>
                <value>
                    <fullName>BD</fullName>
                    <isActive>false</isActive>
                    <label>BD</label>
                </value>
                <value>
                    <fullName>TD</fullName>
                    <isActive>false</isActive>
                    <label>TD</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transferred_To__c</fullName>
        <inlineHelpText>Select the company this lead is transferred to.</inlineHelpText>
        <label>Transferred To</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>ITH</fullName>
                </value>
                <value>
                    <fullName>Livongo</fullName>
                    <isActive>false</isActive>
                    <label>Livongo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Lead.object
    <fields>
        <fullName>L2O_Lead_Source_Detail__c</fullName>
        <label>Lead Source Detail</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>LeadSource</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Web Chat</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Event - Sponsored</fullName>
                </value>
                <value>
                    <fullName>Paid - Display</fullName>
                </value>
                <value>
                    <fullName>Paid - Search</fullName>
                </value>
                <value>
                    <fullName>Paid - Social</fullName>
                </value>
                <value>
                    <fullName>Third Party Acquired</fullName>
                </value>
                <value>
                    <fullName>Web Form</fullName>
                </value>
                <value>
                    <fullName>Webinar - Hosted</fullName>
                </value>
                <value>
                    <fullName>Webinar - Sponsored</fullName>
                </value>
                <value>
                    <fullName>Event - Hosted</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Reseller</fullName>
                </value>
                <value>
                    <fullName>TPA</fullName>
                </value>
                <value>
                    <fullName>Benefit Consultant</fullName>
                </value>
                <value>
                    <fullName>Referral Agent</fullName>
                </value>
                <value>
                    <fullName>AHIP Conference</fullName>
                </value>
                <value>
                    <fullName>AIS</fullName>
                </value>
                <value>
                    <fullName>American Hospital Association</fullName>
                </value>
                <value>
                    <fullName>American Hospital Association Webinar</fullName>
                </value>
                <value>
                    <fullName>ATA</fullName>
                </value>
                <value>
                    <fullName>Becker&apos;s</fullName>
                </value>
                <value>
                    <fullName>Becker&apos;s Webinar</fullName>
                </value>
                <value>
                    <fullName>Blue National Summit</fullName>
                </value>
                <value>
                    <fullName>Blues Conference</fullName>
                </value>
                <value>
                    <fullName>Conference Board</fullName>
                </value>
                <value>
                    <fullName>EHBC Conference</fullName>
                </value>
                <value>
                    <fullName>Data.com (Jigsaw)</fullName>
                </value>
                <value>
                    <fullName>Employee-generated</fullName>
                </value>
                <value>
                    <fullName>Employer List 9.11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Lead.object
    <fields>
        <fullName>L2O_Lead_Source_Detail_Other__c</fullName>
        <label>Lead Source Detail – Other</label>
        <length>255</length>
        <type>Text</type>
    </fields>

objects/Lead.object
    <fields>
        <fullName>L2O_Microsoft_Involved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates Microsoft involvement. Field can be set manually but is also to be part of the lead conversion process.</description>
        <label>Microsoft Involved</label>
        <type>Checkbox</type>
    </fields>

classes/TDH_Lead_Controller.cls
/*************************************************************************     
* @description This class is used for passing lead information and callng rest resource in ith
* @param NA
* @Author InfoSys Developer
**************************************************************************/
public without sharing class TDH_Lead_Controller {
    /**
* @description This is an Aura Enabled method called by TDH_LeadtransferController
* @param recordId is Lead record id from controller
* @return ld which are lead records
**/
    @AuraEnabled 
    public static Lead getLead(String recordId) {
        Lead ld = [SELECT Id, Status,L2O_Microsoft_Involved__c,LeadSource,L2O_Lead_Source_Detail__c,L2O_Lead_Source_Detail_Other__c, Allow_Transfer__c, Transferred_To__c, FirstName, OwnerId, LastName, Title, Company, Description, Email, Street, City, State, Postalcode, Country, Phone FROM Lead WHERE Id =: recordId];
        return ld;
    }
    /**
* @description This is an Aura Enabled method called by TDH_LeadtransferController which send record to ith
* @param ld is Lead record id from controller
* @return deserializedRes which is ResWrapper object
**/
    @AuraEnabled
    public static ResWrapper sendRecord(Lead ld) {
        String jsonString = JSON.serialize(ld); 
        EtlItem newItem = new EtlItem();
        newItem.parserName = 'Lead';
        newItem.requestVersion = '1.0';
        newItem.payload = jsonString;
        String jsonstr = JSON.serialize(newItem);
        HttpRequest req1 = new HttpRequest();
        if (ld.Transferred_To__c == 'ITH') {
            req1.setEndpoint('callout:ITH_Org_New/services/apexrest/gcrm2ithbus/');
        } 
        req1.setMethod('POST');
        req1.setHeader('Content-Type','application/json');
        req1.setHeader('accept','application/json');
        req1.setBody(jsonstr);
        Http http = new Http();
        HTTPResponse res1 = http.send(req1);
        while (res1.getStatusCode() == 302) {
            req1.setEndpoint(res1.getHeader('Location'));
            res1 = new Http().send(req1);
            
        }
        
        BusItem__c busItem = new BusItem__c();
        busItem.Payload__c = jsonString;
        busItem.Processed__c = false;
        busItem.Source__c = 'TDH';
        if (ld.Transferred_To__c == 'ITH') {
            busItem.Send_to__c = 'ITH';
        } 
        if((GlobalIdUtils.isGuid(busItem.GUID__c)==false)||String.isBlank(busItem.GUID__c))
        {
        busItem.GUID__c = GlobalIdUtils.generateGuid();
        }
        
        busItem.SourceOwnerId__c = ld.OwnerId;
        busItem.SourceUrl__c = URL.getSalesforceBaseUrl().toExternalForm() + '/' + ld.Id;
        
        if (res1.getStatusCode() != 200) {
            busItem.Status__c = 'Callout_Status: ' + res1.getStatusCode();
            ResWrapper resWrapper = new ResWrapper('false', 'ERROR CODE: ' + String.valueOf(res1.getStatusCode()));
            insert busItem;         
            return resWrapper;
        } else {
            busItem.Status__c = 'RESPONSE_BODY ' + res1.getbody(); 
            busItem.Processed__c = true;
            insert busItem;         
            String res = res1.getbody().unescapeEcmaScript();
            res  = res.substring(1, res.length() - 1);
            ResWrapper deserializedRes = (ResWrapper)JSON.deserialize(res, ResWrapper.class); 
            return deserializedRes;
        }        	
    }
    /**
* @description ResWrapper is being used by TDH_Lead_Controller which sets value of isInsert and result
* @param NA
* @Author InfoSys Developer
**/   
    public class ResWrapper {
/**
* @description isInsert used to set value for isInsert variable
*/
        @auraEnabled
        public String isInsert {get; set;}
/**
* @description result used to store result 
*/
        @auraEnabled
        public String result {get; set;}
        /**
* @description ResWrapper used as a constructor
* @param isInsert used to set the isInsert value and result used to send the result data
* @param result used to send the result data
*/
        public ResWrapper(String isInsert, String result){
            this.isInsert = isInsert;
            this.result = result;
        }
    }
}