manifest/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity from which this Contract was created.</description>
        <inlineHelpText>The Opportunity from which this Contract was created.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__RenewalOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Renewal opportunity generated to track the renewal of this contract.</description>
        <inlineHelpText>Renewal opportunity generated to track the renewal of this contract.</inlineHelpText>
        <label>Renewal Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Renewal Contracts</relationshipLabel>
        <relationshipName>RenewedContracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2O_Amend_Asset_Contact__c</fullName>
        <description>Field is updated via the Manage Install Base LWC and used to create an Opportunity Contact Role for Asset only amendments</description>
        <formula>Account.L2O_Amend_Asset_Contact__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amend Asset Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2O_IsAccountAmendAssets__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Helper field to identify if this Opportunity was created from the amend asset flow</description>
        <label>IsAccountAmendAssets</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__AmendedContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the relationship to your Amended Contract.</description>
        <inlineHelpText>Lookup to your Amended Contract.</inlineHelpText>
        <label>Amended Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Amendment Opportunities</relationshipLabel>
        <relationshipName>AmendmentOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

manifest/objects/OpportunityContactRole.object
<CustomObject>
</CustomObject>

objects/OpportunityContactRole.object
    <fields>
        <fullName>L2O_Broker_Flat_Rate__c</fullName>
        <description>The $ rate for the partner contact</description>
        <label>Broker Flat Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

objects/OpportunityContactRole.object
    <fields>
        <fullName>L2O_Broker_Percentage__c</fullName>
        <description>The % rate for the partner contact</description>
        <label>Broker Percentage</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>

objects/OpportunityContactRole.object
    <fields>
        <fullName>L2O_Chronic_Care_Flat_Rate__c</fullName>
        <description>The $ rate for the partner contact (if Chronic Care products are involved)</description>
        <label>Chronic Care Flat Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

objects/OpportunityContactRole.object
    <fields>
        <fullName>L2O_Chronic_Care_Percentage__c</fullName>
        <description>The % rate for the partner contact (if Chronic Care products are involved)</description>
        <label>Chronic Care Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>

manifest/classes/L2O_OperationOnAmmendedOpportunity.cls
/**
* Company : PwC.
* @description : L2O_OperationOnAmmendedOpportunity will be executed from the L2O_OpportunityTriggerHandler and will extend the L2O_TriggerHandler class .
* ************************************************************************************************************************************
* History : 
* @date 07/04/2022
* @author Neha Sharma
*/
public without sharing class L2O_OperationOnAmmendedOpportunity {
    /**
* @name  createContactRoleOnAmmendedOpportunity
* @description mapping quote status to opportunity stage
* @params none
*/  
    public void createContactRoleOnAmmendedOpportunity(){
        List<Opportunity> newOpportunityList = Trigger.New;
        List<Opportunity> ammendedOpportunityList = new List<Opportunity>();
        Map<String,String> ammendedFromAccountOpportunityMap = new  Map<String,String>();
        List<OpportunityContactRole> insertContactRoleList = new List<OpportunityContactRole>();
        Map<Id,Id> contractOppMap = new Map<Id,Id>();
        Set<Id> contractIdSet = new Set<Id>();
        for(Opportunity opp: newOpportunityList){
            if(opp.SBQQ__AmendedContract__c != null){
                ammendedOpportunityList.add(opp);
                contractIdSet.add(opp.SBQQ__AmendedContract__c);
                contractOppMap.put(opp.SBQQ__AmendedContract__c,opp.id);
            }
            if(opp.L2O_IsAccountAmendAssets__c){
               
                ammendedFromAccountOpportunityMap.put(opp.Id,opp.L2O_Amend_Asset_Contact__c);
                
            }
            
        }
        if(!ammendedOpportunityList.isEmpty() || !ammendedFromAccountOpportunityMap.isEmpty()){
            insertContactRoleList = getContactRolesToInsert(contractIdSet,contractOppMap,ammendedFromAccountOpportunityMap);
            
        }
        
        // Insert OpportunityContactRole
        if(!insertContactRoleList.isEmpty()){
            Database.insert(insertContactRoleList,true);
        }
        
    }
    /**
* @name  getContactRolesToInsert
* @description calculating the contact roles to be attached
* @param  contractIdSet to pass the new values
* @param  contractOppCurrentMapp to pass the amended 
* @param  amendFromAssetContactRoleMap to pass the amended 
* @return List<OpportunityContactRole>
**/
    public List<OpportunityContactRole> getContactRolesToInsert(Set<Id> contractIdSet,Map<Id,Id> contractOppCurrentMapp,Map<String,String> amendFromAssetContactRoleMap){
        Set<Id> oppIdSet = new Set<Id>(); 
        Map<Id,Id> contractRenewOppMap = new Map<Id,Id>(); 
        Map<Id,Id> contractOppMap = new Map<Id,Id>(); 
        List<OpportunityContactRole> oppContactRoleList = new List<OpportunityContactRole>();
        List<OpportunityContactRole> oppContactRoletoInsertList = new List<OpportunityContactRole>();
        
        for(Contract con: [SELECT id,SBQQ__RenewalOpportunity__c,SBQQ__Opportunity__c 
                               FROM Contract 
                               WHERE Id IN :contractIdSet]){
                oppIdSet.add(con.SBQQ__Opportunity__c); 
                contractOppMap.put(con.SBQQ__Opportunity__c,con.id);
                contractRenewOppMap.put(con.id,con.SBQQ__RenewalOpportunity__c);
            }
            
            //getting contactroles for existing opportunities
            if(!oppIdSet.isEmpty()){
            for(Opportunity opp : [SELECT id,
                                   (SELECT id,Role,OpportunityId,IsPrimary,ContactId,L2O_Broker_Flat_Rate__c,
                                    L2O_Broker_Percentage__c,L2O_Chronic_Care_Flat_Rate__c,L2O_Chronic_Care_Percentage__c
                                   FROM OpportunityContactRoles) 
                                   FROM Opportunity 
                                   WHERE ID IN: oppIdSet]){
                for(OpportunityContactRole oppCon: opp.OpportunityContactRoles){
                    oppContactRoleList.add(oppCon);
                }
             } 
        }
            if(!oppContactRoleList.isEmpty()){
               
                oppContactRoletoInsertList = getContactRoleValues(oppContactRoleList,contractOppCurrentMapp,contractOppMap);
            } 
        //getting contactroles for existing opportunities for ammend asset functionality
        if(!amendFromAssetContactRoleMap.isEmpty()){
            for (String key : amendFromAssetContactRoleMap.keySet()) {
                OpportunityContactRole oppConRole = new OpportunityContactRole();
                 oppConRole.OpportunityId =  key ;
                 oppConRole.ContactId = amendFromAssetContactRoleMap.get(key);
                 oppContactRoletoInsertList.add(oppConRole);
            }
            
        }
        // Return list of OpportunityContactRole
        return oppContactRoletoInsertList;  
    }
    /**
* @name  getContactRoleValues
* @description calculating the contact roles to be attached
* @param  existingRolesList to pass the new values
* @param  contractOppCurrentMapp to pass the amended 
* @param  contractOppMap to pass the amended 
* @return List<OpportunityContactRole>
**/   
    public List<OpportunityContactRole> getContactRoleValues(List<OpportunityContactRole> existingRolesList,Map<Id,Id> contractOppCurrentMapp,Map<Id,Id> contractOppMap){
        List<OpportunityContactRole> oppContactRoletoInsertList = new List<OpportunityContactRole>();
        for(OpportunityContactRole oppCon: existingRolesList){
                      String contractId = contractOppMap.get(oppCon.OpportunityId);
                   
                    //check if the contract is not null and existing opportunity has comments
                    if(contractId != null && contractOppCurrentMapp.get(contractId) != null){
                        OpportunityContactRole oppConRole = new OpportunityContactRole();
                        oppConRole.Role = oppCon.role;
                        oppConRole.IsPrimary = oppCon.IsPrimary;
                        oppConRole.OpportunityId =  contractOppCurrentMapp.get(contractId);
                        oppConRole.ContactId = oppCon.ContactId;
                        oppContactRoletoInsertList.add(oppConRole);
                        // Populate the Role and Commission Rate fields #169948
                            if(oppCon.Role == L2O_Constants.OPPCON_ROLE_BROKER || oppCon.Role == L2O_Constants.OPPCON_ROLE_BENEFIT_CONSULTANT || oppCon.Role == L2O_Constants.OPPCON_ROLE_GENERAL_AGENCY){
                                oppConRole.L2O_Broker_Flat_Rate__c = oppCon.L2O_Broker_Flat_Rate__c;
                                oppConRole.L2O_Broker_Percentage__c = oppCon.L2O_Broker_Percentage__c;
                                oppConRole.L2O_Chronic_Care_Flat_Rate__c = oppCon.L2O_Chronic_Care_Flat_Rate__c;
                                oppConRole.L2O_Chronic_Care_Percentage__c = oppCon.L2O_Chronic_Care_Percentage__c;
                            }
                        
                    }
                }
        // Return list of OpportunityContactRole
        return oppContactRoletoInsertList;
        
    }   
    
}