manifest/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>CPQ_Pricebook__c</fullName>
        <formula>SBQQ__Opportunity__r.CPQ_Pricebook__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CPQ Pricebook</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HealthPlan_Opt_In__c</fullName>
        <formula>SBQQ__Opportunity__r.HealthPlan_Opt_In__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>HealthPlan Opt-In</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity from which this Contract was created.</description>
        <inlineHelpText>The Opportunity from which this Contract was created.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>SBQQ__AmendedContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the relationship to your Amended Contract.</description>
        <inlineHelpText>Lookup to your Amended Contract.</inlineHelpText>
        <label>Amended Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Amendment Opportunities</relationshipLabel>
        <relationshipName>AmendmentOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__RenewedContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contract being renewed by this renewal opportunity. In case opportunity rolls up several contracts this points at the master contract.</description>
        <inlineHelpText>Contract being renewed by this renewal opportunity. If the several contracts roll up to this opportunity, this points at the master contract.</inlineHelpText>
        <label>Renewed Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Renewal Opportunities</relationshipLabel>
        <relationshipName>RenewalOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

manifest/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Source_Id__c</fullName>
        <externalId>true</externalId>
        <label>Source Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>CPQ_Pricebook__c</fullName>
        <label>CPQ Pricebook</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sales_Channels__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>CPQ_Pricebooks</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HealthPlan_Opt_In__c</fullName>
        <label>HealthPlan Opt-In</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CPQ_Pricebook__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Start date for subscriptions in this quote.</description>
        <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__Type__c</fullName>
        <description>Indicates the type of quote.</description>
        <inlineHelpText>Indicates the type of quote.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote</fullName>
                    <default>true</default>
                    <label>Quote</label>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Change Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Id__c</fullName>
        <externalId>true</externalId>
        <label>Source Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>CPQ_Pricebook__c</fullName>
        <formula>TEXT(SBQQ__Quote__r.CPQ_Pricebook__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CPQ Pricebook</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Date the service represented by this line item will begin (only applies if product is a subscription).</description>
        <inlineHelpText>The date the subscription for this product begins.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/globalValueSets/CPQ_Pricebooks.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Carrier</fullName>
    </customValue>
    <customValue>
        <fullName>Canada Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Canada Insurance (New)</fullName>
    </customValue>
    <customValue>
        <fullName>Canada Insurance (Exist)</fullName>
    </customValue>
    <customValue>
        <fullName>HealthPlan</fullName>
    </customValue>
    <customValue>
        <fullName>Complex Case Mgmt</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>HHS</fullName>
    </customValue>
    <customValue>
        <fullName>Cross-Sell</fullName>
        <isActive>false</isActive>
        <label>Cross-Sell</label>
    </customValue>
    <masterLabel>CPQ Pricebooks</masterLabel>
</GlobalValueSet>

manifest/classes/QuoteTriggerHelperTester.cls
@isTest
public class QuoteTriggerHelperTester {
  static private void createPriceInfo(String pSbqqType) {
    test.StartTest();
    SBQQ.TriggerControl.disable();
    //20171026 - Create instead of select
    //Account a = [select id from Account where Name = 'BioHorizons Implant Systems, Inc'];
    //Account aRef = new Account(ExternalSysId__c = 'TestAcct1234567890');
    //Account a = new Account(Name = 'BioHorizons Implant Systems, Inc', ExternalSysId__c = 'TestAcct1234567890');
    Account aRef = new Account(Source_Id__c = '123456789012345678');
    Account a = TestDataFactory.createAccountUMRNoInsert();
    a.Type = 'Employer';
    a.Source_Id__c = '123456789012345678';
    a.Phone = '111-283-2839';

    Opportunity o = TestDataFactory.createOpportunityWithPriceBook(
      null,
      null,
      null
    );
    o.Account = aRef;
    o.StageName = 'Prospect';
    o.LeadSource = 'Sales';
    //insert o;

    Contract c = new Contract();
    c.Account = aRef;
    c.SBQQ__Opportunity__c = o.id;

    //insert c;

    //insert aro;

    Database.SaveResult[] sr = Database.insert(new List<SObject>{ a, o, c });

    Opportunity aro = TestDataFactory.createOpportunityWithPriceBook(
      null,
      null,
      null
    );
    aro.Account = aRef;
    aro.StageName = 'Prospect';
    aro.SBQQ__AmendedContract__c = c.id;
    aro.SBQQ__RenewedContract__c = c.id;
    insert aro;
    SBQQ__Quote__c aq = TestDataFactory.createQuote(aro.Id);
    aq.SBQQ__Type__c = pSbqqType;
    aq.SBQQ__Primary__c = true;
    aq.CPQ_Pricebook__c = 'Broker'; //EEM: Carrier->ASO->UMR is no longer valid.
    aq.SBQQ__StartDate__c = Date.today();
    aq.HealthPlan_Opt_In__c = 'No';
    aq.SBQQ__Type__c = 'Amendment';
    insert aq;

    //20171026 - create instead of select
    //Product2 p = [select id from Product2 where ProductCode='GM'];

    Product2 tmpPrd = TestDataFactory.createSingleProduct(
      'Gen Med',
      'Gen Med',
      'GM'
    );
    insert tmpPrd;

    Id tmpPb = Test.getStandardPricebookId();

    PricebookEntry tmpPbe = TestDataFactory.createPriceBookEntries(
      new List<Product2>{ tmpPrd },
      tmpPb
    )[0];
    insert tmpPbe;

    SBQQ__QuoteLine__c aql = TestDataFactory.createQuoteLine(aq.Id, tmpPrd.Id);

    insert aql;

    Map<id, SBQQ__QuoteLine__c> quoteLinesMap = new Map<id, SBQQ__QuoteLine__c>();
    quoteLinesMap.put(aql.Id, aql);
    QuoteTriggerHelper.addMissingFeeProductsToAmendments(quoteLinesMap);
    SBQQ.TriggerControl.enable();
    test.StopTest();
  }
  /*static testMethod void runAmendmentTest() {
        createPriceInfo('Amendment');
    }*/

  static testMethod void runRenewalTest() {
    createPriceInfo('Renewal');
  }
}