manifest/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Mbr_Group__c.object
<CustomObject>
    <fields>
        <fullName>Client_Account__c</fullName>
        <description>Account that the Group is created</description>
        <inlineHelpText>Account that the Group is created</inlineHelpText>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Member Groups</relationshipLabel>
        <relationshipName>Member_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <description>System Generated Global UniqueId</description>
        <externalId>true</externalId>
        <inlineHelpText>System Generated Global UniqueId</inlineHelpText>
        <label>GUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Enter a descriptive Member Group Name.</description>
        <inlineHelpText>Enter a descriptive Member Group Name.</inlineHelpText>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OneAppAccess__c</fullName>
        <inlineHelpText>OneApp = Yes, unless they are HealthiestYou, PLI (private label), SDK, or international, or the org hasn&apos;t migrated.</inlineHelpText>
        <label>OneApp Access</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Group Status</description>
        <inlineHelpText>Group Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>PENDING</fullName>
                    <default>true</default>
                    <label>PENDING</label>
                </value>
                <value>
                    <fullName>TERMED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <description>This date will allow for staged terminations in the future.  A nightly batch job will check if this date has passed and set status to termed along with all blank term dates on associated PSF records.</description>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <label>Member Group</label>
    <nameField>
        <displayFormat>MG-{00000000}</displayFormat>
        <label>Member Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Plan_Specific_Fees__c.object
<CustomObject>
    <fields>
        <fullName>Current_Membership_Fee__c</fullName>
        <formula>Subscription__r.Current_Membership_Fee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Membership Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Plan-Specific Fees By Product</relationshipLabel>
        <relationshipName>Plan_Specific_Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan-Specific Fees By Product</label>
    <nameField>
        <displayFormat>PSF-{0000000}</displayFormat>
        <label>Plan Fees ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan-Specific Fees By Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>Fee_Type__c</fullName>
        <description>Captures the FeeType at the Product level</description>
        <label>Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Fee_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__ListPrice__c</fullName>
        <description>List unit price for the product quoted by this line item. List Price originates from the price book.</description>
        <inlineHelpText>List unit price for the product quoted by this line item. List Price originates from the price book.</inlineHelpText>
        <label>List Unit Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProductName__c</fullName>
        <description>Name for the product referenced by this line item.</description>
        <formula>SBQQ__Product__r.Name</formula>
        <inlineHelpText>Name for the product referenced by this line item.</inlineHelpText>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity being quoted.</description>
        <inlineHelpText>Quantity being quoted.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>Current_Membership_Fee__c</fullName>
        <description>New field created to allow editing by account management for price changes.  A workflow will be built to enter the value when Subscription is originally created.</description>
        <inlineHelpText>New field created to allow editing by account management for price changes.  A workflow will be built to enter the value when Subscription is originally created.</inlineHelpText>
        <label>Current Membership Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fee_Type__c</fullName>
        <description>Keeping the Pikclist optinos un restricted as Process Builder copies the value from Opportunity Fee Type which might be different than</description>
        <inlineHelpText>Which Fee Type relates to this Subscription</inlineHelpText>
        <label>Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PEPM</fullName>
                </value>
                <value>
                    <fullName>PMPM</fullName>
                </value>
                <value>
                    <fullName>Case Rate</fullName>
                </value>
                <value>
                    <fullName>N/A (?)</fullName>
                </value>
                <value>
                    <fullName>PPPM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account that owns this subscription. This relationship is used for volume discount calculations.</description>
        <inlineHelpText>Account that owns this subscription. This relationship is used for volume discount calculations.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contract that governs this subscription.</description>
        <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__ListPrice__c</fullName>
        <description>List price for this subscription product.</description>
        <inlineHelpText>List price for this subscription product.</inlineHelpText>
        <label>List Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProductName__c</fullName>
        <description>Pulls in the Product Name</description>
        <formula>SBQQ__Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pulls in the Product Name</inlineHelpText>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product used to sell this subscription.</description>
        <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity of this subscription product purchased by the customer.</description>
        <inlineHelpText>Quantity of this subscription product purchased by the customer.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this subscription.</description>
        <inlineHelpText>Quote line that generated this subscription.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionStartDate__c</fullName>
        <description>Matches the quote line start date by default. If blank, it will match the contract start date.</description>
        <inlineHelpText>Matches the quote line start date by default. If blank, it will match the contract start date.</inlineHelpText>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Active</fullName>
                    <default>true</default>
                    <label>Not Yet Active</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <description>Termination date for subscription</description>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/globalValueSets/Fee_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PEPM</fullName>
    </customValue>
    <customValue>
        <fullName>PMPM</fullName>
    </customValue>
    <customValue>
        <fullName>PPPM</fullName>
    </customValue>
    <customValue>
        <fullName>Flat Rate</fullName>
    </customValue>
    <customValue>
        <fullName>Case Rate</fullName>
    </customValue>
    <masterLabel>Fee type</masterLabel>
</GlobalValueSet>

manifest/classes/GrpTermBchTest.cls
@isTest
private class GrpTermBchTest {
  @TestSetup
  static void setup() {
    SBQQ.TriggerControl.disable();
  
    Account umrAcct = TestDataFactory.createUMR();
    Account testAcct = TestDataFactory.createParentAccount();
    Contact conObj = TestDataFactory.createContact(testAcct.Id);
    SBQQ__Quote__c quoteObj = TestDataFactory.createQuote();
        Test.startTest();
    Opportunity oppObj = TestDataFactory.createCWOpportunity(
      quoteObj,
      testAcct.Id
    );
       Test.stopTest();
    TestDataFactory.CreateProduct();
    TestDataFactory.createQuoteLine(quoteObj.Id);
    product2 prodBH = [
      SELECT Id, Name, ProductCode
      FROM product2
      WHERE ProductCode = 'BH'
    ];
    product2 prodGM = [
      SELECT Id, Name, ProductCode
      FROM product2
      WHERE ProductCode = 'GM'
    ];
    product2 prodBHP1T = [
      SELECT Id, Name, ProductCode
      FROM product2
      WHERE ProductCode = 'BHP1T'
    ];
    product2 prodBHPOT = [
      SELECT Id, Name, ProductCode
      FROM product2
      WHERE ProductCode = 'BHPOT'
    ];
    product2 prodBHNPT = [
      SELECT Id, Name, ProductCode
      FROM product2
      WHERE ProductCode = 'BHNPT'
    ];

    Contract contObj = TestDataFactory.createContract(
      testAcct.Id,
      oppObj.Id,
      quoteObj.Id
    );
    SBQQ__QuoteLine__c objQL = [
      SELECT Id, Name, SBQQ__Quote__c, SBQQ__Product__c, SBQQ__ListPrice__c
      FROM SBQQ__QuoteLine__c
      WHERE SBQQ__Product__r.ProductCode = 'BH'
    ];
    SBQQ__QuoteLine__c objQLGM = [
      SELECT Id, Name, SBQQ__Quote__c, SBQQ__Product__c, SBQQ__ListPrice__c
      FROM SBQQ__QuoteLine__c
      WHERE SBQQ__Product__r.ProductCode = 'GM'
    ];
    SBQQ__Subscription__c subtest = new SBQQ__Subscription__c(
      SBQQ__Quantity__c = 1000,
      SBQQ__QuoteLine__c = objQL.Id,
      SBQQ__Account__c = testAcct.Id,
      SBQQ__Contract__c = contObj.Id,
      fee_type__c = 'PEPM',
      SBQQ__SubscriptionStartDate__c = system.today() - 1,
      SBQQ__Product__c = objQL.SBQQ__Product__c,
      Current_Membership_Fee__c = 10
    );
    SBQQ__Subscription__c subGMtest = new SBQQ__Subscription__c(
      SBQQ__Quantity__c = 1000,
      SBQQ__QuoteLine__c = objQLGM.Id,
      SBQQ__Account__c = testAcct.Id,
      SBQQ__Contract__c = contObj.Id,
      fee_type__c = 'PEPM',
      SBQQ__SubscriptionStartDate__c = system.today() - 1,
      SBQQ__Product__c = objQLGM.SBQQ__Product__c,
      Current_Membership_Fee__c = 10
    );

    insert subtest;
    insert subGMtest;
    TestDataFactory.createAsset(
      'Consult Fee- Psych/MD-1stvisitonly-Total',
      90,
      testAcct.Id,
      conObj.Id,
      prodBHP1T.Id,
      subtest.Id
    );
    TestDataFactory.createAsset(
      'Consult Fee- Non-Psychiatrist- Total',
      90,
      testAcct.Id,
      conObj.Id,
      prodBHPOT.Id,
      subtest.Id
    );
    TestDataFactory.createAsset(
      'Consult Fee- Psych/MD-ONGOING-Total',
      90,
      testAcct.Id,
      conObj.Id,
      prodBHNPT.Id,
      subtest.Id
    );
    TestDataFactory.createAsset(
      'GM - Consult Fee',
      45,
      testAcct.Id,
      conObj.Id,
      prodGM.Id,
      subGMtest.Id
    );

    Mbr_Group__c mgTest = new Mbr_Group__c();
    mgTest.name__c = 'testLogo';
    mgTest.Client_Account__c = testAcct.Id;
    mgTest.GUID__c = '0D2D00E4-3151-0287-DD24-2913C77F0659';
    mgTest.Status__c = 'Active';
    mgTest.Termination_Date__c = Date.newInstance(2016, 12, 9);
    mgTest.OneAppAccess__c = 'Yes';
    insert mgTest;

    SBQQ__Subscription__c sub = [
      SELECT SBQQ__ProductName__c, id
      FROM SBQQ__Subscription__c
      WHERE SBQQ__ProductName__c = 'Product: BH'
    ];
    List<Plan_Specific_Fees__c> psfList = new List<Plan_Specific_Fees__c>();
    Plan_Specific_Fees__c psf1 = new Plan_Specific_Fees__c(
      Member_Group__c = mgTest.id,
      Subscription__c = sub.Id,
      Actual_Copay_May_Be_Less__c = false,
      Consult_Fee_Mbr_Pd__c = 90
    );
    psfList.add(psf1);
    Plan_Specific_Fees__c psf2 = new Plan_Specific_Fees__c(
      Member_Group__c = mgTest.id,
      Subscription__c = sub.Id,
      Actual_Copay_May_Be_Less__c = false,
      Consult_Fee_Mbr_Pd__c = 90
    );
    psfList.add(psf2);
    Plan_Specific_Fees__c psf3 = new Plan_Specific_Fees__c(
      Member_Group__c = mgTest.id,
      Subscription__c = sub.Id,
      Actual_Copay_May_Be_Less__c = false,
      Consult_Fee_Mbr_Pd__c = 90
    );
    psfList.add(psf3);
    insert psfList;

    SBQQ.TriggerControl.enable();
  }

  static testMethod void test() {
          Test.startTest();
    Mbr_Group__c testMbrGrp = [
      SELECT Status__c, Termination_Date__c
      FROM Mbr_Group__c
    ];
    system.assertEquals('ACTIVE', testMbrGrp.Status__c);

    GrpTerm_Bch testing = new GrpTerm_Bch();
    DataBase.executeBatch(testing);
       Test.stopTest();
    system.assertEquals(
      'TERMED',
      [SELECT Status__c FROM Mbr_Group__c].Status__c
    );
    system.assertEquals(
      testMbrGrp.Termination_Date__c,
      [SELECT Product_End_Date__c FROM Plan_Specific_Fees__c LIMIT 1]
      .Product_End_Date__c
    );
  }
}