manifest/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity from which this Contract was created.</description>
        <inlineHelpText>The Opportunity from which this Contract was created.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contract.object
    <fields>
        <fullName>L2O_Channel_Segment__c</fullName>
        <label>Channel Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Employer</fullName>
                </value>
                <value>
                    <fullName>Health Plan</fullName>
                </value>
                <value>
                    <fullName>Client Management</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Hospital &amp; Health System (HHS)</fullName>
                </value>
                <value>
                    <fullName>Partner (Broker)</fullName>
                    <isActive>false</isActive>
                    <label>Partner (Broker)</label>
                </value>
                <value>
                    <fullName>Partner (Consultant)</fullName>
                    <isActive>false</isActive>
                    <label>Partner (Consultant)</label>
                </value>
                <value>
                    <fullName>Partner (Reseller)</fullName>
                    <isActive>false</isActive>
                    <label>Partner (Reseller)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Contract.object
    <fields>
        <fullName>L2O_Contract_Path__c</fullName>
        <label>Contract Path</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contract_Path</valueSetName>
        </valueSet>
    </fields>

objects/Contract.object
    <fields>
        <fullName>L2O_Contract_Path_Sub_type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contract_Path_Sub_Types</valueSetName>
        </valueSet>
    </fields>

manifest/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2O_Channel_Segment__c</fullName>
        <description>Which of the 5 segments (Employer, Health Plan, Client Management, INTL, HHS) is this Opportunity a part of?</description>
        <label>Channel Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Employer</fullName>
                </value>
                <value>
                    <fullName>Health Plan</fullName>
                </value>
                <value>
                    <fullName>Client Management</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Hospital &amp; Health System (HHS)</fullName>
                </value>
                <value>
                    <fullName>Partner (Broker)</fullName>
                    <isActive>false</isActive>
                    <label>Partner (Broker)</label>
                </value>
                <value>
                    <fullName>Partner (Consultant)</fullName>
                    <isActive>false</isActive>
                    <label>Partner (Consultant)</label>
                </value>
                <value>
                    <fullName>Partner (Reseller)</fullName>
                    <isActive>false</isActive>
                    <label>Partner (Reseller)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2O_Contract_Path_Sub_type__c</fullName>
        <description>Does the Contract Path have: No pricing, Contracted Pricing or New Pricing</description>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contract_Path_Sub_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2O_Contract_Path__c</fullName>
        <description>How should this Opportunity be Contracted?</description>
        <label>Contract Path</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contract_Path</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2O_Initial_of_Lives__c</fullName>
        <description># of Employees or Members, in this piece of Business</description>
        <inlineHelpText>Number of lives, either employees OR members, to be closed (formerly \Initial # of Lives\&quot;). Should be only what will be acquired if this particular piece of business is closed - not the total number at the company. SALES REPS: Be conservative!&quot;</inlineHelpText>
        <label>Number of Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>L2O_Subtype__c</fullName>
        <label>Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Sale</fullName>
                </value>
                <value>
                    <fullName>Initial Sale - Partner</fullName>
                </value>
                <value>
                    <fullName>Hunting License</fullName>
                </value>
                <value>
                    <fullName>Pilot</fullName>
                </value>
                <value>
                    <fullName>Change Order</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Pilot to Paid Conversion</fullName>
                </value>
                <value>
                    <fullName>Attrition / Expiry</fullName>
                </value>
                <value>
                    <fullName>Pilot Extension</fullName>
                </value>
                <value>
                    <fullName>Contract Path Change</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                    <isActive>false</isActive>
                    <label>Expansion</label>
                </value>
                <value>
                    <fullName>Expansion / Add-On</fullName>
                    <isActive>false</isActive>
                    <label>Expansion / Add-On</label>
                </value>
                <value>
                    <fullName>Initial Sale - Direct</fullName>
                    <isActive>false</isActive>
                    <label>Initial Sale - Direct</label>
                </value>
                <value>
                    <fullName>New Population</fullName>
                    <isActive>false</isActive>
                    <label>New Population</label>
                </value>
                <value>
                    <fullName>Recontracting</fullName>
                    <isActive>false</isActive>
                    <label>Recontracting</label>
                </value>
                <value>
                    <fullName>Renewal + Expansion</fullName>
                    <isActive>false</isActive>
                    <label>Renewal + Expansion</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__AmendedContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the relationship to your Amended Contract.</description>
        <inlineHelpText>Lookup to your Amended Contract.</inlineHelpText>
        <label>Amended Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Amendment Opportunities</relationshipLabel>
        <relationshipName>AmendmentOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__RenewedContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contract being renewed by this renewal opportunity. In case opportunity rolls up several contracts this points at the master contract.</description>
        <inlineHelpText>Contract being renewed by this renewal opportunity. If the several contracts roll up to this opportunity, this points at the master contract.</inlineHelpText>
        <label>Renewed Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Renewal Opportunities</relationshipLabel>
        <relationshipName>RenewalOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

manifest/globalValueSets/Contract_Path.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>US Health Plan</fullName>
    </customValue>
    <customValue>
        <fullName>Complex Case Mgmt</fullName>
    </customValue>
    <customValue>
        <fullName>TPA/Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital &amp; Health Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Intl Insurer</fullName>
    </customValue>
    <customValue>
        <fullName>Cross-Sell</fullName>
        <isActive>false</isActive>
        <label>Cross-Sell</label>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
        <isActive>false</isActive>
        <label>Broker</label>
    </customValue>
    <customValue>
        <fullName>Carrier</fullName>
        <isActive>false</isActive>
        <label>Carrier</label>
    </customValue>
    <customValue>
        <fullName>Canada Direct</fullName>
        <isActive>false</isActive>
        <label>Canada Direct</label>
    </customValue>
    <customValue>
        <fullName>Canada Insurance (New)</fullName>
        <isActive>false</isActive>
        <label>Canada Insurance (New)</label>
    </customValue>
    <customValue>
        <fullName>Canada Insurance (Exist)</fullName>
        <isActive>false</isActive>
        <label>Canada Insurance (Exist)</label>
    </customValue>
    <description>Values as per TDUAT</description>
    <masterLabel>Contract Path</masterLabel>
</GlobalValueSet>

globalValueSets/Contract_Path_Sub_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>Contracted Pricing</fullName>
    </customValue>
    <customValue>
        <fullName>New Pricing</fullName>
    </customValue>
    <masterLabel>Contract Path Sub Types</masterLabel>
</GlobalValueSet>

manifest/classes/L2O_OperationOnAmmendedOpportunity_Test.cls
/**
* Company : PwC.
* @description : Test Class for L2O_OperationOnAmmendedOpportunity apex
* ************************************************************************************************************************************
* History : 
* @date 12/04/2022
* @author Neha Sharma
*/
@isTest
public class L2O_OperationOnAmmendedOpportunity_Test {
    /**
* @name  testSetup 
* @description To create setup records for test class.
* @params  none
**/
    @testSetup
    static void testSetup() {
        // create test data
        List<Account> accountList= L2O_DataFactoryTest.createAccount(true,1);  
        List<Opportunity> oppList = L2O_DataFactoryTest.createOpportunity(true,accountList);  
        List<Contact> conList =  L2O_DataFactoryTest.createContact(true, accountList);
        L2O_DataFactoryTest.createContactRoles(true,oppList,conList[0].id);
        Contract contract = new Contract();
        contract.AccountId = accountList[0].id;
        contract.SBQQ__Opportunity__c = oppList[0].id;
        contract.StartDate = System.today();
        contract.Status = 'Draft';
        contract.ContractTerm = 36;
        insert contract;
        
    }
    
    
    /**
* @name  testQuoteDefaultValues
* @description To test the Quote default fields with automated values.
* @params  none
**/
    @isTest static void testAmendedOpportunityContactRole() {
        Test.startTest();
        List<Contract> contract = [SELECT Id,AccountId FROM Contract WHERE ID != null LIMIT 1];
        //create Opportunity
        Opportunity opp = new Opportunity();
        opp.name = 'testing contact role amend';
        opp.AccountId = contract[0].AccountId;
        opp.StageName = 'Prospect';
        opp.CloseDate = system.today();
        opp.SBQQ__AmendedContract__c = contract[0].id;
        opp.Type = 'Existing Business';
        opp.L2O_Initial_of_Lives__c=2300;
        opp.Pricebook2Id = Test.getStandardPricebookId();
        opp.L2O_Contract_Path__c = 'Direct';
        opp.L2O_Contract_Path_Sub_type__c = 'None';
        opp.L2O_Channel_Segment__c ='Employer';
        opp.L2O_Subtype__c = 'Change Order';
        insert opp;
        System.assert(opp.id != null,'pass');
    }       
/**
* @name  testQuoteDefaultValues
* @description To test the Quote default fields with automated values.
* @params  none
**/
    @isTest static void testRenewOpportunityContactRole() {
        Test.startTest();
        List<Contract> contract = [SELECT Id,AccountId FROM Contract WHERE ID != null LIMIT 1];
        //create Opportunity
        Opportunity opp = new Opportunity();
        opp.name = 'testing contact role amend';
        opp.AccountId = contract[0].AccountId;
        opp.StageName = 'Prospect';
        opp.CloseDate = system.today();
        opp.SBQQ__RenewedContract__c = contract[0].id;
        opp.Type = 'Existing Business';
        opp.L2O_Initial_of_Lives__c=2300;
        opp.Pricebook2Id = Test.getStandardPricebookId();
        opp.L2O_Contract_Path__c = 'Direct';
        opp.L2O_Contract_Path_Sub_type__c = 'None';
        opp.L2O_Channel_Segment__c ='Employer';
        opp.L2O_Subtype__c = 'Change Order';
        insert opp;
        System.assert(opp.id != null,'pass');
       
    }
}