manifest/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity from which this Contract was created.</description>
        <inlineHelpText>The Opportunity from which this Contract was created.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contract.object
    <fields>
        <fullName>L2O_GUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

manifest/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2O_GUID__c</fullName>
        <description>Global Unique Identifier that is used for integration</description>
        <externalId>true</externalId>
        <inlineHelpText>System Generated Global UniqueId</inlineHelpText>
        <label>GUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>L2O_InitialOpportunityGUID__c</fullName>
        <description>Contains the related New Business GUID</description>
        <label>Initial Opportunity GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__AmendedContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the relationship to your Amended Contract.</description>
        <inlineHelpText>Lookup to your Amended Contract.</inlineHelpText>
        <label>Amended Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Amendment Opportunities</relationshipLabel>
        <relationshipName>AmendmentOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__RenewedContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contract being renewed by this renewal opportunity. In case opportunity rolls up several contracts this points at the master contract.</description>
        <inlineHelpText>Contract being renewed by this renewal opportunity. If the several contracts roll up to this opportunity, this points at the master contract.</inlineHelpText>
        <label>Renewed Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Renewal Opportunities</relationshipLabel>
        <relationshipName>RenewalOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

manifest/classes/L2O_GenerateOrder_Controller.cls
public class L2O_GenerateOrder_Controller {
    
    @auraEnabled(cacheable=true)
    Public Static integer getContracts(string oppId){
        
        integer ConlistSize;
        Set<ID> conIds = new Set<ID>();
        List<Contract> conList = new List<Contract>();
        List<Opportunity> oppList = [select Id, SBQQ__AmendedContract__c, SBQQ__RenewedContract__c, L2O_InitialOpportunityGUID__c, L2O_GUID__c from Opportunity where Id =: oppId limit 1];
        if(!oppList.isEmpty()){
            if(!String.IsBlank(oppList[0].SBQQ__AmendedContract__c)) {
               conIds.add(oppList[0].SBQQ__AmendedContract__c);
            }
            else if(!String.IsBlank(oppList[0].SBQQ__RenewedContract__c)) {
               conIds.add(oppList[0].SBQQ__RenewedContract__c); 
            }
            else {
                conList = [Select Id,Status from Contract where SBQQ__Opportunity__c =: oppId Limit 1];
                conIds.add(conList[0].Id);
            }
        }
        ConlistSize = conIds.size();
        return ConlistSize;        
    }
}