manifest/objects/Dev_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global config for development</description>
    <fields>
        <fullName>Disable_Triggers__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Disable trigger execution</description>
        <label>Disable Triggers</label>
        <type>Checkbox</type>
    </fields>
    <label>Dev Setting</label>
</CustomObject>

manifest/objects/LVGO__Account__c.object
<CustomObject>
    <fields>
        <fullName>LVGO__TD_Acct_Guid__c</fullName>
        <description>Cloning TDH__Acct_Guid__c from TDH GuidPackage</description>
        <externalId>true</externalId>
        <label>TD Acct Guid</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LVGO__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Payer/ASO</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>TPA</fullName>
                </value>
                <value>
                    <fullName>Self Funded Employer</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Hospital/Health System</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Medicare Advantage</fullName>
                </value>
                <value>
                    <fullName>PBM</fullName>
                </value>
                <value>
                    <fullName>Business Development</fullName>
                </value>
                <value>
                    <fullName>Ops Partner</fullName>
                </value>
                <value>
                    <fullName>Managed Care Organization</fullName>
                </value>
                <value>
                    <fullName>Fully-Insured Employer</fullName>
                    <label>Fully Insured Employer</label>
                </value>
                <value>
                    <fullName>Labor/Pension Fund</fullName>
                </value>
                <value>
                    <fullName>Federal Government</fullName>
                </value>
                <value>
                    <fullName>Other Partner</fullName>
                </value>
                <value>
                    <fullName>Behavioral Health Provider</fullName>
                </value>
                <value>
                    <fullName>Chronic Care Management Organization</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Physician / Hospital</fullName>
                </value>
                <value>
                    <fullName>Referral Agent</fullName>
                </value>
                <value>
                    <fullName>Reseller</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>LV Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/LVGO__Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>LVGO__Account__c</fullName>
        <label>Account</label>
        <referenceTo>LVGO__Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>LVGO_Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LVGO__CloseDate__c</fullName>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LVGO__LeadSource__c</fullName>
        <label>LeadSource</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Undefined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LVGO__StageName__c</fullName>
        <label>Stage</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Discovery</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>Review/Negotiation</fullName>
                </value>
                <value>
                    <fullName>Contracting</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
                <value>
                    <fullName>Closed No Decision</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LVGO__TD_Opp_Guid__c</fullName>
        <description>Cloning TDH__Opp_Guid__c from TDH GuidPackage</description>
        <externalId>true</externalId>
        <label>TD Opp Guid</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LVGO__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Business</fullName>
                </value>
                <value>
                    <fullName>Existing Business</fullName>
                </value>
                <value>
                    <fullName>Re-Sign Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>LV Opportunity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Message_Bus_Toggle__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Enable_MB_LV_Island__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Enable LV Custom Object Creation</inlineHelpText>
        <label>Enable MB LV Island</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_MB__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable MB</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Error_Email_Enable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Error Email Enable</label>
        <type>Checkbox</type>
    </fields>
    <label>Message Bus Toggle</label>
</CustomObject>

manifest/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this Opportunity Product.</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>OpportunityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

manifest/objects/Q_Item__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Outgoing</fullName>
                </value>
                <value>
                    <fullName>Incoming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Q Item</label>
    <nameField>
        <label>Q Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Q Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Business_Region__c</fullName>
        <label>Business Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CPQ_Pricebook__c</fullName>
        <label>CPQ Pricebook</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sales_Channels__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>CPQ_Pricebooks</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Include_in_Octiv_Proposal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used by Octiv to determine if a fee page should be produced/included for this Quote based upon the Proposal Template selected on the Opportunity.</description>
        <inlineHelpText>This field is used by Octiv to determine if a fee page should be produced/included for this Quote based upon the Proposal Template selected on the Opportunity.</inlineHelpText>
        <label>Include in Octiv Proposal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Channels__c</fullName>
        <label>Sales Channels</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sales_Channels</valueSetName>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>Teladoc</fullName>
        <active>true</active>
        <label>Teladoc</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>CPQ_Pricebook__c</fullName>
        <formula>TEXT(SBQQ__Quote__r.CPQ_Pricebook__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CPQ Pricebook</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fee_Type__c</fullName>
        <description>Captures the FeeType at the Product level</description>
        <label>Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Fee_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity being quoted.</description>
        <inlineHelpText>Quantity being quoted.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/globalValueSets/Business_Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>USA</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Europe</fullName>
    </customValue>
    <customValue>
        <fullName>Asia-ME</fullName>
    </customValue>
    <customValue>
        <fullName>Aus-NZ</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <description>Global region - where the contract will reside</description>
    <masterLabel>Business Region</masterLabel>
</GlobalValueSet>

manifest/globalValueSets/CPQ_Pricebooks.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Carrier</fullName>
    </customValue>
    <customValue>
        <fullName>Canada Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Canada Insurance (New)</fullName>
    </customValue>
    <customValue>
        <fullName>Canada Insurance (Exist)</fullName>
    </customValue>
    <customValue>
        <fullName>HealthPlan</fullName>
    </customValue>
    <customValue>
        <fullName>Complex Case Mgmt</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>HHS</fullName>
    </customValue>
    <customValue>
        <fullName>Cross-Sell</fullName>
        <isActive>false</isActive>
        <label>Cross-Sell</label>
    </customValue>
    <masterLabel>CPQ Pricebooks</masterLabel>
</GlobalValueSet>

manifest/globalValueSets/Fee_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PEPM</fullName>
    </customValue>
    <customValue>
        <fullName>PMPM</fullName>
    </customValue>
    <customValue>
        <fullName>PPPM</fullName>
    </customValue>
    <customValue>
        <fullName>Flat Rate</fullName>
    </customValue>
    <customValue>
        <fullName>Case Rate</fullName>
    </customValue>
    <masterLabel>Fee type</masterLabel>
</GlobalValueSet>

manifest/globalValueSets/Sales_Channels.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>US Employer</fullName>
    </customValue>
    <customValue>
        <fullName>US HealthPlan</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital and Health Systems</fullName>
    </customValue>
    <masterLabel>Sales Channels</masterLabel>
</GlobalValueSet>

manifest/classes/MB_TDHMsgBus_Test.cls
@IsTest
private class MB_TDHMsgBus_Test {
  @TestSetup
  public static void setup() {
    Message_Bus_Toggle__c MB = Message_Bus_Toggle__c.getOrgDefaults();
    MB.Enable_MB__c = true;
    MB.Error_Email_Enable__c = true;
    MB.Enable_MB_LV_Island__c = true;
    insert MB;
    Dev_Settings__c objDS = new Dev_Settings__c(
      SetupOwnerId = UserInfo.getUserId(),
      Disable_Triggers__c = true
    );
    insert objDS;
    Test.setMock(HttpCalloutMock.class, new MB_MockMsgBus_Test());
    Account umrAcct = new Account(
      Name = 'UMR',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Standard')
        .getRecordTypeId(),
      Friendly_Account_Name__c = 'TestAmendAccount',
      Source__c = 'HUB',
      CurrencyIsoCode = 'USD',
      Business_Region__c = 'USA',
      Account_Type__c = 'Health Plan'
    );
    insert umrAcct;

    LVGO__Account__c lvgoAccount = new LVGO__Account__c();
    lvgoAccount.Name = 'Livongo';
    lvgoAccount.LVGO__TD_Acct_Guid__c = 'FD5E35E0-5175-D1CB-06B8-B48C018EA7C9';
    insert lvgoAccount;

    LVGO__Opportunity__c lvopp = new LVGO__Opportunity__c();
    lvopp.Name = 'Test Opportunity ';
    lvopp.LVGO__StageName__c = 'Prospect';
    lvopp.LVGO__Type__c = 'Renewal';
    lvopp.LVGO__CloseDate__c = Date.today().addDays(1);
    lvopp.LVGO__LeadSource__c = 'Other';
    lvopp.LVGO__Account__c = lvgoAccount.Id;
    lvopp.LVGO__TD_Opp_Guid__c = '416805C1-85B3-D317-121B-B939FA02A645';
    insert lvopp;

    Pricebook2 livongoPricebook = new Pricebook2(
      Name = 'Livongo',
      IsActive = true
    );
    insert livongoPricebook;

    Id pricebookId = Test.getStandardPricebookId();
    List<Opportunity> lstOpps = new List<Opportunity>();
    Opportunity oppObj = new Opportunity(
      Name = 'No Line Item',
      RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName()
        .get('Employer – Teladoc and HY Products')
        .getRecordTypeId(),
      AccountId = umrAcct.Id,
      Type = 'New Business',
      Business_Region__c = 'USA',
      CurrencyIsoCode = 'USD',
      StageName = 'Prospect',
      Probability = 10,
      Initial_of_Lives__c = 500,
      Fee_Type__c = 'PEPM',
      CloseDate = Date.Today(),
      Contracted_Date__c = Date.Today(),
      Pricebook2Id = pricebookId,
      LeadSource = 'Marketing',
      Decision_Date__c = Date.Today()
    );
    lstOpps.add(oppObj);

    Opportunity oppObj2 = new Opportunity(
      Name = 'Got Line Item',
      RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName()
        .get('Employer – Teladoc and HY Products')
        .getRecordTypeId(),
      isLVN__c = true,
      AccountId = umrAcct.Id,
      Type = 'New Business',
      Business_Region__c = 'USA',
      CurrencyIsoCode = 'USD',
      StageName = 'Prospect',
      Probability = 10,
      Initial_of_Lives__c = 500,
      Fee_Type__c = 'PEPM',
      Benefit_Consultant_Involved_in_Deal__c = 'No',
      CloseDate = Date.Today(),
      Contracted_Date__c = Date.Today(),
      Pricebook2Id = pricebookId,
      LeadSource = 'Marketing',
      Decision_Date__c = Date.Today()
    );

    lstOpps.add(oppObj2);

    insert lstOpps;

    List<Product2> prodList = new List<Product2>();
    Product2 prod1 = new Product2(
      Name = 'Livongo DIAB',
      ProductCode = 'DIAB',
      IsActive = true,
      Family = 'Livongo'
    );
    Product2 prod2 = new Product2(
      Name = 'Livongo BH',
      ProductCode = 'BH',
      IsActive = true,
      Family = 'Livongo'
    );
    Product2 prod3 = new Product2(
      Name = 'General Medical',
      ProductCode = 'GM',
      IsActive = true,
      Family = 'General Medical'
    );
    prodList.add(prod1);
    prodList.add(prod2);
    prodList.add(prod3);
    insert prodList;

    List<SBQQ__Quote__c> lstQts = new List<SBQQ__Quote__c>();
    SBQQ__Quote__c quoObj1 = new SBQQ__Quote__c(
      RecordTypeId = Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByName()
        .get('Teladoc')
        .getRecordTypeId(),
      SBQQ__Opportunity2__c = oppObj.Id,
      SBQQ__Primary__c = true,
      Sales_Channels__c = 'US Employer',
      CPQ_Pricebook__c = 'Direct',
      Include_in_Octiv_Proposal__c = false
    );
    lstQts.add(quoObj1);

    SBQQ__Quote__c quoObj2 = new SBQQ__Quote__c(
      RecordTypeId = Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByName()
        .get('Teladoc')
        .getRecordTypeId(),
      SBQQ__Opportunity2__c = oppObj2.Id,
      SBQQ__Primary__c = true,
      Sales_Channels__c = 'US Employer',
      CPQ_Pricebook__c = 'Direct',
      Include_in_Octiv_Proposal__c = false
    );
    lstQts.add(quoObj2);

    insert lstQts;

    /*
        List<SBQQ__QuoteLine__c> qteLineList = new List<SBQQ__QuoteLine__c>();
        SBQQ__QuoteLine__c quoline1 = new SBQQ__QuoteLine__c(SBQQ__Quote__c = quoObj2.Id ,SBQQ__Product__c = prod1.Id, SBQQ__Quantity__c = 500, Consult_Type__c = 'Standard', SBQQ__PricingMethod__c = 'List',
                                                             CurrencyIsoCode = 'USD', SBQQ__Number__c = 1);
        qteLineList.add(quoline1);
        SBQQ__QuoteLine__c quoline2 = new SBQQ__QuoteLine__c(SBQQ__Quote__c = quoObj2.Id ,SBQQ__Product__c = prod2.Id, SBQQ__Quantity__c = 500, Consult_Type__c = 'Standard', SBQQ__PricingMethod__c = 'List',
                                                             CurrencyIsoCode = 'USD', SBQQ__Number__c = 1);
        qteLineList.add(quoline2);
         SBQQ__QuoteLine__c quoline3 = new SBQQ__QuoteLine__c(SBQQ__Quote__c = quoObj2.Id ,SBQQ__Product__c = prod3.Id, SBQQ__Quantity__c = 500, Consult_Type__c = 'Standard', SBQQ__PricingMethod__c = 'List',
                                                             CurrencyIsoCode = 'USD', SBQQ__Number__c = 1);
        qteLineList.add(quoline3); 
        
        insert qteLineList;
        */
    List<PricebookEntry> pbList = new List<PricebookEntry>();
    PricebookEntry pbEntry1 = new PricebookEntry(
      Pricebook2Id = pricebookId,
      Product2Id = prod1.Id,
      UnitPrice = 1.40,
      IsActive = true
    );
    PricebookEntry pbEntry2 = new PricebookEntry(
      Pricebook2Id = pricebookId,
      Product2Id = prod2.Id,
      UnitPrice = 1.40,
      IsActive = true
    );
    PricebookEntry pbEntry3 = new PricebookEntry(
      Pricebook2Id = pricebookId,
      Product2Id = prod3.Id,
      UnitPrice = 1.40,
      IsActive = true
    );
    pbList.add(pbEntry1);
    pbList.add(pbEntry2);
    pbList.add(pbEntry3);
    insert pbList;

    /*
        List<OpportunityLineItem> oppLiList = new List<OpportunityLineItem>();
        OpportunityLineItem oppli = new OpportunityLIneItem(OpportunityId = oppObj2.Id, Quantity = 1, TotalPrice = 100, product2Id = prod1.Id, pricebookEntryId = pbEntry1.Id, SBQQ__QuoteLine__c = quoline1.Id);
        OpportunityLineItem oppli2 = new OpportunityLIneItem(OpportunityId = oppObj2.Id, Quantity = 1, TotalPrice = 100, product2Id = prod2.Id, pricebookEntryId = pbEntry2.Id, SBQQ__QuoteLine__c = quoline2.Id);
        OpportunityLineItem oppli3 = new OpportunityLIneItem(OpportunityId = oppObj2.Id, Quantity = 1, TotalPrice = 100, product2Id = prod3.Id, pricebookEntryId = pbEntry3.Id, SBQQ__QuoteLine__c = quoline3.Id);
        oppLiList.add(oppli);
        oppLiList.add(oppli2);
        oppLiList.add(oppli3);
        insert oppLiList;
        */

    delete objDS;
  }

  @IsTest
  static void NewUpdate() {
    Test.startTest();
    Dev_Settings__c objDS = new Dev_Settings__c(
      SetupOwnerId = UserInfo.getUserId(),
      Disable_Triggers__c = true
    );
    insert objDS;
    Opportunity oppWithProd = [
      SELECT Id
      FROM Opportunity
      WHERE Name = 'Got Line Item'
    ];
    oppWithProd.StageName = 'Contracting';
    update oppWithProd;
    MB_UpdateQueueable.doChainJob = false;
    MB_InsertQueueable.doChainJob = false;
    Test.setMock(HttpCalloutMock.class, new MB_MockMsgBus_Test());
    Id pricebookId = Test.getStandardPricebookId();
    Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'No Line Item'];
    SBQQ__Quote__c quoObj1 = [
      SELECT Id
      FROM SBQQ__Quote__c
      WHERE SBQQ__Opportunity2__r.Name = 'No Line Item'
    ];
    Product2 prod1 = [SELECT Id FROM Product2 LIMIT 1];
    SBQQ__QuoteLine__c quoline1 = new SBQQ__QuoteLine__c(
      SBQQ__Quote__c = quoObj1.Id,
      SBQQ__Product__c = prod1.Id,
      SBQQ__Quantity__c = 500,
      Consult_Type__c = 'Standard',
      SBQQ__PricingMethod__c = 'List',
      CurrencyIsoCode = 'USD',
      SBQQ__Number__c = 1
    );
    insert quoline1;
    List<Q_Item__c> beforeDeleteQlist = [SELECT Id FROM Q_Item__c];
    PricebookEntry pbEntry = [SELECT Id FROM PricebookEntry LIMIT 1];
    OpportunityLineItem oppli = new OpportunityLIneItem(
      OpportunityId = opp.Id,
      Quantity = 1,
      TotalPrice = 100,
      product2Id = prod1.Id,
      pricebookEntryId = pbEntry.Id,
      SBQQ__QuoteLine__c = quoline1.Id
    );
    insert oppli;
    List<Q_Item__c> qlist = [SELECT Id FROM Q_Item__c];
    system.assertEquals(beforeDeleteQlist.size(), qlist.size());
    Test.stopTest();
  }

  @IsTest
  static void MsgQItemNoneAsyncOutgoing_Test() {
    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new MB_MockIncomingQ_Test());
    String body = '{"attributes": {"type": "Q_Item__c"},"Payload__c": "{}","ItemKey__c": "DE3C1C1E-5197-18DB-9539-27043fA22EB4","Status__c": "Pending","Src__c": "TDH","Dst__c": "LVN","Parser_Name__c": "parserName","Type__c":"Outgoing"}';
    RestRequest req = new RestRequest();
    RestResponse res = new RestResponse();
    req.requestURI = '/services/apexrest/msgqitembus/';
    req.httpMethod = 'POST';
    req.requestBody = Blob.valueOf(body);
    RestContext.request = req;
    RestContext.response = res;
    String result = MsgQItemBus.processQ();
    Test.stopTest();
  }

  @isTest
  static void DeleteOppLine() {
    MB_UpdateQueueable.doChainJob = false;
    MB_InsertQueueable.doChainJob = false;
    test.startTest();
    Dev_Settings__c objDS = new Dev_Settings__c(
      SetupOwnerId = UserInfo.getUserId(),
      Disable_Triggers__c = true
    );
    insert objDS;

    Test.setMock(HttpCalloutMock.class, new MB_MockMsgBus_Test());

    Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'No Line Item'];
    opp.StageName = 'Contracting';
    update opp;

    Id pricebookId = Test.getStandardPricebookId();
    //Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'No Line Item'];
    SBQQ__Quote__c quoObj1 = [
      SELECT Id
      FROM SBQQ__Quote__c
      WHERE SBQQ__Opportunity2__r.Name = 'No Line Item'
    ];
    Product2 prod1 = [SELECT Id FROM Product2 LIMIT 1];
    SBQQ__QuoteLine__c quoline1 = new SBQQ__QuoteLine__c(
      SBQQ__Quote__c = quoObj1.Id,
      SBQQ__Product__c = prod1.Id,
      SBQQ__Quantity__c = 500,
      Consult_Type__c = 'Standard',
      SBQQ__PricingMethod__c = 'List',
      CurrencyIsoCode = 'USD',
      SBQQ__Number__c = 1
    );
    insert quoline1;
    PricebookEntry pbEntry = [SELECT Id FROM PricebookEntry LIMIT 1];
    OpportunityLineItem opplinew = new OpportunityLIneItem(
      OpportunityId = opp.Id,
      Quantity = 1,
      TotalPrice = 100,
      product2Id = prod1.Id,
      pricebookEntryId = pbEntry.Id,
      SBQQ__QuoteLine__c = quoline1.Id
    );
    insert opplinew;

    OpportunityLineItem oppli = [SELECT Id FROM OpportunityLineItem LIMIT 1];
    delete oppli;
    test.stopTest();
    //List<Q_Item__c> qlist = [SELECT Id FROM Q_Item__c];
    //system.assertEquals(1, qlist.size());
  }

  @isTest
  static void OppTrg() {
    test.startTest();
    Test.setMock(HttpCalloutMock.class, new MB_MockMsgBus_Test());
    Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Got Line Item'];
    opp.StageName = 'Contracting';
    update opp;
    test.stopTest();
    //List<Q_Item__c> qlist = [SELECT Id FROM Q_Item__c];
    //system.assertEquals(1, qlist.size());
  }

  @isTest
  static void OppTrgIsLvn() {
    test.startTest();
    MB_UpdateQueueable.doChainJob = false;
    MB_InsertQueueable.doChainJob = false;
    Test.setMock(HttpCalloutMock.class, new MB_MockMsgBus_Test());
    Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Got Line Item'];
    opp.StageName = 'Contracting';
    opp.isLVN__c = true;
    update opp;
    test.stopTest();
    //List<Q_Item__c> qlist = [SELECT Id FROM Q_Item__c];
    //system.assertEquals(1, qlist.size());
  }

  @isTest
  static void OppTrgIsLvn2() {
    List<Id> oppIds = new List<Id>();
    test.startTest();
    MB_UpdateQueueable.doChainJob = false;
    MB_InsertQueueable.doChainJob = false;
    Test.setMock(HttpCalloutMock.class, new MB_MockMsgBus_Test());
    Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Got Line Item'];
    opp.StageName = 'Closed Won';
    opp.isLVN__c = true;
    update opp;
    oppIds.add(Opp.Id);
    //InvokeMessageBus.OppInvokeMB(oppIds);
    test.stopTest();
    //List<Q_Item__c> qlist = [SELECT Id FROM Q_Item__c];
    //system.assertEquals(1, qlist.size());
  }

  @IsTest
  static void skippingStage() {
    MB_UpdateQueueable.doChainJob = false;
    MB_InsertQueueable.doChainJob = false;
    test.startTest();
    Test.setMock(HttpCalloutMock.class, new MB_MockMsgBus_Test());
    Id pricebookId = Test.getStandardPricebookId();
    Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Got Line Item'];

    opp.Contract_Service_Agreement_Status__c = 'Executed';
    opp.Contracted_Date__c = Date.Today();
    opp.StageName = 'Closed Won';
    try {
      update opp;
    } catch (exception e) {
      String error = e.getMessage();
      system.debug(e.getMessage());
      system.assertEquals(true, error.contains('Cannot move an Opportunity'));
    }
    test.stopTest();
  }

  @isTest
  static void DeleteOppTrg() {
    test.startTest();
    Test.setMock(HttpCalloutMock.class, new MB_MockMsgBus_Test());
    Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'No Line Item'];
    SBQQ__Quote__c q = [
      SELECT id
      FROM SBQQ__Quote__c
      WHERE SBQQ__Opportunity2__c = :opp.id
    ];
    q.SBQQ__Primary__c = false;
    update q;
    delete q;
    opp.isLVN__c = true;
    update opp;
    system.debug('opp :::' + opp);
    delete opp;
    test.stopTest();
  }
}