manifest/objects/F1b_Remove_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Key_Word__c</fullName>
        <label>Key Word</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>F1b_Remove_Setting</label>
</CustomObject>

manifest/objects/Mbr_Group__c.object
<CustomObject>
    <fields>
        <fullName>Card_Template__c</fullName>
        <description>This populates the Send Card checkbox field on the NASF.  If Card Template value = No Card or Email or NULL then Send Card is NOT checked.  If Card Template value = Logo Card or STND then the box is Send Card box is checked on the NASF.</description>
        <label>Card Template</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Logo Card</fullName>
                </value>
                <value>
                    <fullName>STND Card</fullName>
                </value>
                <value>
                    <fullName>No Card</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Co_Brand_with_Logo__c</fullName>
        <description>Identifies this group should have 2 logo brands on the WK</description>
        <inlineHelpText>Identifies this group should have 2 logo brands on the WK</inlineHelpText>
        <label>Co-Brand with Logo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Communication_Mode__c</fullName>
        <description>Determines if specific Comm. Mode verbiage needs to be used on Welcome Letter</description>
        <inlineHelpText>Determines if specific Comm. Mode verbiage needs to be used on Welcome Letter</inlineHelpText>
        <label>Communication Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Default</fullName>
                    <default>true</default>
                    <label>Default</label>
                </value>
                <value>
                    <fullName>By phone</fullName>
                </value>
                <value>
                    <fullName>By video</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MK_Idcardfront1__c</fullName>
        <description>ID Card 1 (front)</description>
        <inlineHelpText>ID Card 1 (front)</inlineHelpText>
        <label>MK_Idcardfront1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Default</fullName>
                    <default>true</default>
                    <label>Default</label>
                </value>
                <value>
                    <fullName>IDF1_Covered_txt</fullName>
                </value>
                <value>
                    <fullName>IDF1_ID_no_dep</fullName>
                </value>
                <value>
                    <fullName>IDF1_Txt</fullName>
                </value>
                <value>
                    <fullName>IDF1_Txt_ES</fullName>
                </value>
                <value>
                    <fullName>IDF1_No_Cardname</fullName>
                </value>
                <value>
                    <fullName>IDF1_NoDep_No Cardname</fullName>
                </value>
                <value>
                    <fullName>IDF1_NoUserID</fullName>
                </value>
                <value>
                    <fullName>IDF1_NoDep_No_CardName</fullName>
                </value>
                <value>
                    <fullName>IDF1_Covered_Txt_S</fullName>
                </value>
                <value>
                    <fullName>IDF1_OnlyMadeAvailBy</fullName>
                </value>
                <value>
                    <fullName>IDF1_Txt_URL_Phone</fullName>
                </value>
                <value>
                    <fullName>IDF1_Txt_ES_URL_Phone</fullName>
                </value>
                <value>
                    <fullName>IDF1_No_MadeAvailableBy</fullName>
                </value>
                <value>
                    <fullName>IDF1_NoCard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Brand__c</fullName>
        <description>This field is set to set the Service Brand for EMO Product. The trigger on PSF set the default value to &apos;Taledoc&apos; for EMO2 Product and &apos;BestDoctors&apos; for EMO product. User can overwrite the value set by the trigger.</description>
        <label>Service Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Teladoc (Aetna)</fullName>
                </value>
                <value>
                    <fullName>Teladoc (Canada)</fullName>
                </value>
                <value>
                    <fullName>Teladoc (US)</fullName>
                </value>
                <value>
                    <fullName>Teladoc Health (Internal)</fullName>
                </value>
                <value>
                    <fullName>HealthiestYou</fullName>
                </value>
                <value>
                    <fullName>Livongo</fullName>
                </value>
                <value>
                    <fullName>BestDoctors</fullName>
                    <isActive>false</isActive>
                    <label>BestDoctors</label>
                </value>
                <value>
                    <fullName>Teladoc</fullName>
                    <isActive>false</isActive>
                    <label>Teladoc</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipping_Class__c</fullName>
        <description>Standard, First or Drop ship Welcome Letters.  If different from &quot;Standard&quot; then must obtain approval from Welcome Kit team.</description>
        <inlineHelpText>Standard, First or Drop ship Welcome Letters.  If different from &quot;Standard&quot; then must obtain approval from Welcome Kit team.</inlineHelpText>
        <label>Shipping Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>S</fullName>
                    <default>true</default>
                    <label>S</label>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WK_Card_Includes_Logo__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Does the welcome kit card have the client logo on it?</description>
        <inlineHelpText>Does the welcome kit card have the client logo on it?</inlineHelpText>
        <label>WK Card Includes Logo?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WK_Includes_Insert__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Will these welcome kits include an MHD insert?  Used by the printer for fulfillment.</description>
        <inlineHelpText>Will these welcome kits include an MHD insert?  Used by the printer for fulfillment.</inlineHelpText>
        <label>WK - Includes Insert?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WK_Mail_to__c</fullName>
        <description>Where to mail the welcome kit</description>
        <inlineHelpText>Where to mail the welcome kit</inlineHelpText>
        <label>WK Mail-to</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Member</fullName>
                    <default>true</default>
                    <label>Member</label>
                </value>
                <value>
                    <fullName>Client (fee applies)</fullName>
                </value>
                <value>
                    <fullName>TPA (fee applies)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WK_Retroactive_Date__c</fullName>
        <label>Retroactive Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WK_Retroactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Retroactive Welcome Kit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WK_Send_Card_Date__c</fullName>
        <label>Send Card Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WK_Template__c</fullName>
        <description>Determines appearance and language of Welcome Letters,added new option rimary360_VF</description>
        <inlineHelpText>Determines appearance and language of Welcome Letters</inlineHelpText>
        <label>WK Template</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>10C100_HF</fullName>
                </value>
                <value>
                    <fullName>10CH100</fullName>
                </value>
                <value>
                    <fullName>10CMCare_Healthfirst</fullName>
                </value>
                <value>
                    <fullName>10E100_BSC</fullName>
                </value>
                <value>
                    <fullName>10E100_CloverMCare</fullName>
                </value>
                <value>
                    <fullName>10E100_Fallon</fullName>
                </value>
                <value>
                    <fullName>10E100_FallonMCare</fullName>
                </value>
                <value>
                    <fullName>10E100_HF</fullName>
                </value>
                <value>
                    <fullName>10E100_MolinaMCare</fullName>
                </value>
                <value>
                    <fullName>10E100_Premera</fullName>
                </value>
                <value>
                    <fullName>10E100_TD_EMS</fullName>
                </value>
                <value>
                    <fullName>10E100MCare_2019</fullName>
                </value>
                <value>
                    <fullName>10EJ100_Nippon</fullName>
                </value>
                <value>
                    <fullName>10EK100_Nippon</fullName>
                </value>
                <value>
                    <fullName>10EMcare</fullName>
                </value>
                <value>
                    <fullName>10EMCare_Centene</fullName>
                </value>
                <value>
                    <fullName>10EMCare_City of New York</fullName>
                </value>
                <value>
                    <fullName>10EMCare_Healthfirst</fullName>
                </value>
                <value>
                    <fullName>10EMCAREHNE</fullName>
                </value>
                <value>
                    <fullName>10ES_Centene_Commercial</fullName>
                </value>
                <value>
                    <fullName>10ES100_Medicaid</fullName>
                </value>
                <value>
                    <fullName>10ES100_Medicaid_Affinity</fullName>
                </value>
                <value>
                    <fullName>10ES100_Medicaid_IN</fullName>
                </value>
                <value>
                    <fullName>10ES100_Medicaid_NY</fullName>
                </value>
                <value>
                    <fullName>10ES100_Medicaid_OR</fullName>
                </value>
                <value>
                    <fullName>10ES100_Medicaid_TX</fullName>
                </value>
                <value>
                    <fullName>10ES100_Medicaid_WA</fullName>
                </value>
                <value>
                    <fullName>10ES100_MedicareMedicaid_TX</fullName>
                </value>
                <value>
                    <fullName>10ES100_Molina</fullName>
                </value>
                <value>
                    <fullName>10ES100_Molina2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Member Group</label>
    <nameField>
        <displayFormat>MG-{00000000}</displayFormat>
        <label>Member Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/classes/F1BWelcomeKitParser.cls
public class F1BWelcomeKitParser extends F1BBaseParser {
  // TODO: Cleanup instance variables replaced by sobject
  public String DisclaimerClient { get; set; }
  public String DisclaimerTeladoc { get; set; }

  public F1BWelcomeKitParser() {
    super();
  }
  public void Parse(JSONParser parser, Mbr_Group__c targetGroup) {
    while (parser.nextToken() != System.JSONToken.END_OBJECT) {
      if (parser.getCurrentToken() == System.JSONToken.FIELD_NAME) {
        List<String> f1bKeyWord = F1b_Remove_Setting__c.getOrgDefaults()
          .Key_Word__c.split(';');
        String fieldName = parser.getText();
        if (parser.nextToken() != System.JSONToken.VALUE_NULL) {
          String fieldValue = parser.getText();
          if (grpWKEtlMap.containsKey(fieldName)) {
            String mappedFieldName = grpWKEtlMap.get(fieldName);
            fieldDeltas.add(mappedFieldName);
            if (f1bKeyWord.contains(fieldValue.toUpperCase().trim())) {
              targetGroup.put(
                mappedFieldName,
                FetchTypedValue('Mbr_Group__c', mappedFieldName, null)
              );
            } else {
              targetGroup.put(
                mappedFieldName,
                FetchTypedValue('Mbr_Group__c', mappedFieldName, fieldValue)
              );
            }
          } else {
            System.debug(
              LoggingLevel.WARN,
              'Contact_Z consuming unrecognized property: ' + fieldName
            );
            consumeObject(parser);
          }

          switch on fieldName {
            when 'RetroFlag' {
              targetGroup.Wk_Retroactive__c = yieldBoolean(
                'RetroFlag',
                parser.getText()
              );
              fieldDeltas.add('Wk_Retroactive__c');
            }
            when 'CardLogo' {
              targetGroup.Wk_Card_Includes_Logo__c = yieldBoolean(
                'CardLogo',
                parser.getText()
              );
              fieldDeltas.add('Wk_Card_Includes_Logo__c');
            }
            when 'IncludesInsert' {
              targetGroup.Wk_Includes_Insert__c = yieldBoolean(
                'IncludesInsert',
                parser.getText()
              );
              fieldDeltas.add('Wk_Includes_Insert__c');
            }
            when 'CoBrandLogo' {
              try {
                if (parser.getText() == 'Y' || parser.getText() == 'y')
                  targetGroup.Co_Brand_with_Logo__c = 'Yes';
                else if (parser.getText() == 'N' || parser.getText() == 'n')
                  targetGroup.Co_Brand_with_Logo__c = 'No';
              } catch (exception e) {
                if (parser.getBooleanValue())
                  targetGroup.Co_Brand_with_Logo__c = 'Yes';
                else
                  targetGroup.Co_Brand_with_Logo__c = 'No';
              }
              fieldDeltas.add('Co_Brand_with_Logo__c');
            }
            when 'DisclaimerClient' {
              if (f1bKeyWord.contains(parser.getText().toUpperCase().trim())) {
                DisclaimerClient = null;
              } else {
                DisclaimerClient = parser.getText();
              }
            }
            when 'DisclaimerTeladoc' {
              if (f1bKeyWord.contains(parser.getText().toUpperCase().trim())) {
                DisclaimerTeladoc = null;
              } else {
                DisclaimerTeladoc = parser.getText();
              }
            }
            when else {
              System.debug(
                LoggingLevel.WARN,
                'WelcomeKit_Z consuming unrecognized property: ' + fieldName
              );
              consumeObject(parser);
            }
          }
        }
      }
    }
    System.debug(LoggingLevel.FINE, 'WelcomeKit: ' + parsingErrors);
  }

  private static Map<String, String> grpWKEtlMap = new Map<String, String>{
    'PrintMailClass' => 'Shipping_Class__c',
    'TemplateID' => 'Wk_Template__c',
    'SendDate' => 'Wk_Send_Card_Date__c',
    'RetroDate' => 'Wk_Retroactive_Date__c',
    'CardIssuedTo' => 'Wk_Mail_To__c',
    'CardTemplate' => 'Card_Template__c',
    'CoBrandLogo' => 'Co_Brand_With_Logo__c',
    'CommunicationMode' => 'Communication_Mode__c',
    'IDCardFront1' => 'Mk_IdcardFront1__c',
    'TeladocBrand' => 'Service_Brand__c'
  };
}