manifest/objects/F1b_Remove_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Key_Word__c</fullName>
        <label>Key Word</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>F1b_Remove_Setting</label>
</CustomObject>

manifest/objects/LVGO__ClientMemberCode__c.object
<CustomObject>
    <description>Client Member Codes may be used to facilitate registration or to classify clients into groups for reporting and billing (or a combination of these options).  Legacy Registration Codes and Tags are captured as Client Member Codes in Salesforce.</description>
    <fields>
        <fullName>LVGO__ClientMemberCode__c</fullName>
        <description>Defines the Client Member Code value (e.g. &quot;VALLEYPROTEINS&quot;)</description>
        <inlineHelpText>Defines the Client Member Code value (e.g. &quot;VALLEYPROTEINS&quot;).
The Client Member Code must contain only UPPERCASE letters, numbers, and/or a dash. It should not contain any other special characters</inlineHelpText>
        <label>Code</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>LV Client Member Code</label>
    <nameField>
        <displayFormat>CMC-{000000}</displayFormat>
        <label>CM Code Assignment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LV Client Member Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Mbr_Group__c.object
<CustomObject>
    <fields>
        <fullName>Active_Date__c</fullName>
        <description>Date Group was built in Admin</description>
        <inlineHelpText>Date Group was built in Admin</inlineHelpText>
        <label>Active Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Allow_Caregiver_Program__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Option to allow group members the caregiver program functionality</description>
        <inlineHelpText>Option to allow group members the caregiver program functionality</inlineHelpText>
        <label>Allow Caregiver Program</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Allow_Conversion_to_Retail__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Option to allow group members the option to convert to Retail</description>
        <inlineHelpText>Option to allow group members the option to convert to Retail</inlineHelpText>
        <label>Allow Conversion to Retail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Allow_Geo_Fencing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Option to allow Geo-Fencing</description>
        <inlineHelpText>Option to allow Geo-Fencing</inlineHelpText>
        <label>Allow Geo-Fencing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AltLogo1_ID__c</fullName>
        <description>Enter the logo document name for logo to appear.</description>
        <inlineHelpText>Enter the logo document name for logo to appear.</inlineHelpText>
        <label>AltLogo1 ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AltLogo2_ID__c</fullName>
        <description>Enter the logo document name for logo to appear.</description>
        <inlineHelpText>Enter the logo document name for logo to appear.</inlineHelpText>
        <label>AltLogo2 ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Any_Special_Instructions__c</fullName>
        <description>Special instructions or information for fulfillment</description>
        <inlineHelpText>Special instructions or information for fulfillment</inlineHelpText>
        <label>Any Special Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Card_Name__c</fullName>
        <description>Client name as they want it printed on the Welcome Kit cards</description>
        <inlineHelpText>Client name as they want it printed on the Welcome Kit cards. 43 spaces maximum.
12/31/14- increased to 65 characters.</inlineHelpText>
        <label>WK - Client Name for Card</label>
        <length>65</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consult_Billing_Method__c</fullName>
        <description>Select &quot;Claims&quot; if group will pay via claims.  Select &quot;Invoice&quot; if group will pay via invoice.  Select &quot;Invoice + Claims&quot; if group will pay via invoice but want claims for informational purposes.</description>
        <inlineHelpText>Select &quot;Claims&quot; if group will pay via claims.  Select &quot;Invoice&quot; if group will pay via invoice.  Select &quot;Invoice + Claims&quot; if group will pay via invoice but want claims for informational purposes.</inlineHelpText>
        <label>Consult Billing Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Claims</fullName>
                </value>
                <value>
                    <fullName>Informational Claims</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Consult_Message_on_WK__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines if the consult message should be present on Welcome Letters</description>
        <inlineHelpText>Determines if the consult message should be present on Welcome Letters</inlineHelpText>
        <label>Consult Message on WK?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cross_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cross Billing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disclaimer_Custom__c</fullName>
        <description>This is purely for the marketing site only and should only be used for legal client specific disclaimer. This will ride above any other disclaimers and below the companycopy field and has a max character limit of 1400.</description>
        <inlineHelpText>Text field accommodating client legal disclaimers. Displayed on printed/digital marketing material. Note that non Latin-based characters are NOT supported. Disclaimers containing these characters must be handled by an inserted disclaimer sheet. Max 1400</inlineHelpText>
        <label>Disclaimer - Custom</label>
        <length>1400</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Elig_Dep_Inc_In_File__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Will eligibility dependents be included in the stage file?</description>
        <inlineHelpText>Will eligibility dependents be included in the stage file?</inlineHelpText>
        <label>Eligibility Dependents Included In File</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Eligibility_Option__c</fullName>
        <description>Eligibility type</description>
        <inlineHelpText>Eligibility type</inlineHelpText>
        <label>Eligibility Option</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>API(Staged Eligibility &amp; Open)</fullName>
                    <label>API (Staged Eligibility &amp; Open)</label>
                </value>
                <value>
                    <fullName>Client Site</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>RTE</fullName>
                </value>
                <value>
                    <fullName>Staged Eligibility</fullName>
                </value>
                <value>
                    <fullName>Staged Eligibility &amp; RTE</fullName>
                </value>
                <value>
                    <fullName>Staged Registration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Enable_Livongo_Combined_Eligibility__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box when a client will provide a singular Eligibility file for processing.  Required for myStrength Complete.</inlineHelpText>
        <label>Enable Livongo Combined Eligibility</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>F1BReporting_Category__c</fullName>
        <label>F1BReporting Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <description>System Generated Global UniqueId</description>
        <externalId>true</externalId>
        <inlineHelpText>System Generated Global UniqueId</inlineHelpText>
        <label>GUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <description>This is the Legacy Group ID number from Admin</description>
        <inlineHelpText>This is the Legacy Group ID number from Admin</inlineHelpText>
        <label>Group Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Health_Assistant__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Only Groups that have BOTH General Medical (GM) + Expert Medical Opinion (EMO) should have this box checked.</description>
        <inlineHelpText>Health Assistant should be checked for ALL OneApp groups - Health Assistant turns on the chat bot functionality within the app.</inlineHelpText>
        <label>Health Assistant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LV_Client_Member_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LV Client Member Code Lookup</label>
        <referenceTo>LVGO__ClientMemberCode__c</referenceTo>
        <relationshipLabel>Member Groups</relationshipLabel>
        <relationshipName>Member_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Logo1_ID__c</fullName>
        <label>Logo1_ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logo3_ID__c</fullName>
        <label>Logo3_ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logo4_ID__c</fullName>
        <description>This field will be used for French logos</description>
        <inlineHelpText>This field is to only be used for Canadian clients with an alternate French logo.</inlineHelpText>
        <label>Logo4 ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logo_Tag_ID__c</fullName>
        <label>Logo Tag# ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Enter a descriptive Member Group Name.</description>
        <inlineHelpText>Enter a descriptive Member Group Name.</inlineHelpText>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OneAppAccess__c</fullName>
        <inlineHelpText>OneApp = Yes, unless they are HealthiestYou, PLI (private label), SDK, or international, or the org hasn&apos;t migrated.</inlineHelpText>
        <label>OneApp Access</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sexual_Health_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Option to allow Sexual Health product for group members</description>
        <inlineHelpText>Option to allow Sexual Health product for group members</inlineHelpText>
        <label>Allow Sexual Health</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Group Status</description>
        <inlineHelpText>Group Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>PENDING</fullName>
                    <default>true</default>
                    <label>PENDING</label>
                </value>
                <value>
                    <fullName>TERMED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <description>This date will allow for staged terminations in the future.  A nightly batch job will check if this date has passed and set status to termed along with all blank term dates on associated PSF records.</description>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WK_Card_Includes_Logo__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Does the welcome kit card have the client logo on it?</description>
        <inlineHelpText>Does the welcome kit card have the client logo on it?</inlineHelpText>
        <label>WK Card Includes Logo?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Welcome_Letter_Consult_Message__c</fullName>
        <description>This consult message field to be only used for new Welcome Letter and has a 160 char limit.</description>
        <inlineHelpText>This consult message field to be only used for new Welcome Letter and has a 160 char limit.</inlineHelpText>
        <label>Welcome Letter Consult Message</label>
        <length>160</length>
        <type>Text</type>
    </fields>
    <label>Member Group</label>
    <nameField>
        <displayFormat>MG-{00000000}</displayFormat>
        <label>Member Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/classes/F1BMbrGroupParser.cls
public with sharing class F1BMbrGroupParser extends F1BBaseParser {
  public Mbr_Group__c ephMbrGroup { get; set; }
  public String ReportCategory { get; set; }
  public String SfdcPayerGuid { get; set; }
  public F1BWelcomeKitParser f1bpwk { get; set; }
  public List<PsfDataWrapper> f1bpsf { get; set; }

  public F1BMbrGroupParser() {
    super();
    ephMbrGroup = new Mbr_Group__c();
  }
  public override void Parse(JSONParser parser) {
    ephMbrGroup = new Mbr_Group__c();
    SObject grpObject = (SObject) ephMbrGroup;
    while (parser.nextToken() != System.JSONToken.END_OBJECT) {
      if (parser.getCurrentToken() == System.JSONToken.FIELD_NAME) {
        String fieldName = parser.getText();
        List<String> f1bKeyWord = F1b_Remove_Setting__c.getOrgDefaults()
          .Key_Word__c.split(';');
        if (parser.nextToken() != System.JSONToken.VALUE_NULL) {
          String fieldValue = parser.getText();
          if (mbrGrpEtlMap.containsKey(fieldName)) {
            if (fieldName == 'GUID') {
              if (
                String.isBlank(fieldValue) || !GlobalIdUtils.isGuid(fieldValue)
              ) {
                parsingErrors.put('GROUP_GUID', 'Blank or invalid.');
              }
            }
            String mappedFieldName = mbrGrpEtlMap.get(fieldName);
            fieldDeltas.add(mappedFieldName);
            if (f1bKeyWord.contains(fieldValue.toUpperCase().trim())) {
              grpObject.put(
                mappedFieldName,
                FetchTypedValue('Mbr_Group__c', mappedFieldName, null)
              );
            } else {
              grpObject.put(
                mappedFieldName,
                FetchTypedValue('Mbr_Group__c', mappedFieldName, fieldValue)
              );
            }
          } else {
            switch on fieldName {
              when 'SFDCPayerGUID' {
                if (
                  f1bKeyWord.contains(parser.getText().toUpperCase().trim())
                ) {
                  SfdcPayerGuid = null;
                } else {
                  SfdcPayerGuid = parser.getText();
                }
              }
              when 'ReportCategory' {
                if (
                  f1bKeyWord.contains(parser.getText().toUpperCase().trim())
                ) {
                  ReportCategory = null;
                } else {
                  ReportCategory = parser.getText();
                }
              }
              when 'AllowGeoFencing', 'AllowConversion', 'AllowCaregiver', 'AllowSexualHealthOptOut','AllowHealthAssistant','WKCardincludesLogo','ConsultMessageWK','CrossBilling','EnableLivongoCombinedEligibility' {
                  if(mbrGrpBoolFieldMap.ContainsKey(fieldName)){
                          String mappedFieldName = mbrGrpBoolFieldMap.get(fieldName);
                          ephMbrGroup.put(mappedFieldName,yieldBoolean(fieldName,parser.getText()));
                          fieldDeltas.add(mappedFieldName);
                  }               
              }
              when 'OneAppAccess' {
                  if(parser.getText() == 'true') {
                     ephMbrGroup.OneAppAccess__c = 'Yes'; 
                  }
                  else if(parser.getText() == 'false') {
                     ephMbrGroup.OneAppAccess__c = 'No';
                  }
                fieldDeltas.add('OneAppAccess__c');
              }
              when 'Products' {
                f1bpsf = F1BPsfParser.arrayOfProducts(parser, parsingErrors);
              }
              when 'WelcomeKit' {
                f1bpwk = new F1BWelcomeKitParser();
                f1bpwk.Parse(parser, ephMbrGroup);
              }
              when 'LVClientMemberCodeLookup' {
                  String livongoClientCode = parser.getText();
                  if(String.isNotBlank(livongoClientCode)) {  
                      ephMbrGroup.LV_Client_Member_Code__c = [Select Id,LVGO__ClientMemberCode__c FROM LVGO__ClientMemberCode__c Where LVGO__ClientMemberCode__c =:livongoClientCode]?.Id;
                 	  fieldDeltas.add('LV_Client_Member_Code__c');
                  }
              }
              when else {
                System.debug(
                  LoggingLevel.WARN,
                  'Group_Z consuming unrecognized property: ' + fieldName
                );
                consumeObject(parser);
              }
            }
          }
        }
      }
    }
    System.debug(LoggingLevel.FINE, 'Member Group: ' + parsingErrors);
  }

  public static Boolean CalculateDelta(
    Set<String> fields,
    Mbr_Group__c shellGrp,
    Mbr_Group__c existingGrp
  ) {
    Boolean isSame = false;
    for (String field : fields) {
      if (shellGrp.get(field) != existingGrp.get(field)) {
        system.debug(field);
        existingGrp.put(field, shellGrp.get(field));
        isSame = true;
      }
    }
    return isSame;
  }

    private static Map<String, String> mbrGrpBoolFieldMap = new Map<String, String>{
        'AllowHealthAssistant'=>'Health_Assistant__c',
            'AllowCaregiver'=>'Allow_Caregiver_Program__c',
            'AllowGeoFencing'=>'Allow_Geo_Fencing__c',
            'AllowConversion'=>'Allow_Conversion_To_Retail__c',
            'AllowSexualHealthOptOut'=>'Sexual_Health_Opt_Out__c',
            'WKCardincludesLogo' => 'WK_Card_Includes_Logo__c',
            'ConsultMessageWK' => 'Consult_Message_on_WK__c',
            'CrossBilling' => 'Cross_Billing__c' ,
		    'EnableLivongoCombinedEligibility'=> 'Enable_Livongo_Combined_Eligibility__c'       //SCDEV-5872    
            };   
  private static Map<String, String> mbrGrpEtlMap = new Map<String, String>{
    'GroupID' => 'Group_Number__c',
    'GUID' => 'Guid__c',
    'GroupName' => 'Name__c',
    //'GroupStartDate' => 'Active_Date__c',
    'GroupEndDate' => 'Termination_Date__c',
    'CardName' => 'Card_Name__c',
    'ConsultBillingMethod' => 'Consult_Billing_Method__c',
    'Status' => 'Status__c',
    'Eligibility' => 'Eligibility_Option__c',
    'SpecialInstructions' => 'Any_Special_Instructions__c',
    'LogoTagId' => 'Logo_Tag_ID__c',
    'EligibilityDependentsIncludedInFile' => 'Elig_Dep_Inc_In_File__c',
    'ReportCategory' => 'F1BReporting_Category__c',
    'DisclaimerCustom' => 'Disclaimer_Custom__c',
    'WelcomeLetterConsultMessage' => 'Welcome_Letter_Consult_Message__c',
    'Logo1gId' => 'Logo1_ID__c',
    'Logo3gId' => 'Logo3_ID__c',
    'Logo4gId' => 'Logo4_ID__c',
    'AltLogo1gId' => 'AltLogo1_ID__c',
    'AltLogo2gId' => 'AltLogo2_ID__c',
    'MKConsultArea' => 'MK_consultarea__c',
    'CardTemplate' => 'Card_Template__c',
    'CoBrandWithLogo' => 'Co_Brand_with_Logo__c',
    'LineOfBusiness' => 'Admin_Line_of_Business__c',
    'LivongoRegistrationCode' =>'Livongo_Registration_code__c',           //SCDEV-5872
    'EnableChronicCareReferrals' =>'Enable_Chronic_Care_Referrals__c'    //SCDEV-5872
  };
}