manifest/objects/G2LCRM_Flow__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>G2LCRM_V4_Flow__c</fullName>
        <defaultValue>false</defaultValue>
        <label>G2LCRM V4 Flow</label>
        <type>Checkbox</type>
    </fields>
    <label>G2LCRM Flow</label>
</CustomObject>

manifest/objects/G2LCRM_Item__c.object
<CustomObject>
    <fields>
        <fullName>MUID__c</fullName>
        <label>MUID</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Processor__c</fullName>
        <label>Processor</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>account</fullName>
                </value>
                <value>
                    <fullName>order</fullName>
                </value>
                <value>
                    <fullName>accountV3</fullName>
                </value>
                <value>
                    <fullName>orderV3</fullName>
                </value>
                <value>
                    <fullName>orderItemV3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>(&quot;New&quot;)</defaultValue>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Done</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Processed with Error</fullName>
                </value>
                <value>
                    <fullName>Re-Broadcasted</fullName>
                </value>
                <value>
                    <fullName>Re-Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>G2LCRM Item</label>
    <nameField>
        <displayFormat>G2L-{00000000}</displayFormat>
        <label>G2LCRM ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>G2LCRM Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/G2LItemLog__c.object
<CustomObject>
    <fields>
        <fullName>G2LCRM_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>G2LCRM Item</label>
        <referenceTo>G2LCRM_Item__c</referenceTo>
        <relationshipLabel>G2LItemLogs</relationshipLabel>
        <relationshipName>G2LItemLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUID__c</fullName>
        <label>MUID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>G2LItemLog</label>
    <nameField>
        <displayFormat>G2LIL-{00000000}</displayFormat>
        <label>G2LItemLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>G2LItemLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/classes/GCRM_Process_V3_Bch.cls
global with sharing class GCRM_Process_V3_Bch implements Database.Batchable<SObject>, Database.AllowsCallouts {
    private String orderMUID {get;set;}
    private Boolean isReprocessed{get; set;}
    global GCRM_Process_V3_Bch(String muid,Boolean reprocessed){
        orderMUID = muid;
        isReprocessed = reprocessed;
    }
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, MUID__c, Status__c,Processor__c from G2LCRM_Item__c where MUID__c = \'' + orderMUID + '\'';
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext bc, List<G2LCRM_Item__c> scope) {
        SBQQ.TriggerControl.disable();
        G2LCRM_Flow__c settings = G2LCRM_Flow__c.getInstance();
        
        Boolean ispresale = false;
        for(G2LCRM_Item__c g2lci : scope){
            g2lci.Status__c = 'Processing';
            if(g2lci.Processor__c == 'PreSale'){
                ispresale = true;
            }
        }
        update scope;
        ExceptionCustomLog.captureCustomException(orderMUID,'','', '', '', '', '','');
        if(!settings.G2LCRM_V4_Flow__c)
        {
            if(ispresale){
            	GCRM_Process_PreSales gcrmPre = new GCRM_Process_PreSales();
            	gcrmPre.ProcessPayload(orderMUID);
        	}
            else{
                GCRM_Ingest_OrderV3.ingestG2LByMUID(orderMUID);
            	GCRM_Process_OrderV3.ProcessOrderByMUID(orderMUID);
            }
            
        }
        else 
        {
            //GCRM_Process_Payload gpab = new GCRM_Process_Payload();
            GCRMProcess gpab = new GCRMProcess();
			gpab.ProcessOrderByMUID(orderMUID);
        }
        ExceptionCustomLog.saveResultsToG2LItemLog();
    }
    global void finish(Database.BatchableContext bc) {
        /*
        List<G2LCRM_Item__c> g2items = [Select Id, MUID__c from G2LCRM_Item__c where MUID__c = :orderMUID];
        for(G2LCRM_Item__c g2lci : g2items){
            g2lci.Status__c = 'Done';
        }
        update g2items;
        */
        List<G2LCRM_Item__c> g2items = [Select Id, Status__c, Processed__c, (Select Id from G2LItemLogs__r) from G2LCRM_Item__c where MUID__c = :orderMUID];
        for(G2LCRM_Item__c g2lci : g2items){
            g2lci.Processed__c = true;
            if(g2lci.G2LItemLogs__r.size()>0){
                g2lci.Status__c = 'Processed with Error';
            }else if(isReprocessed){
                g2lci.Status__c = 'Re-Processed';
            }else{
                g2lci.Status__c = 'Done';
            }
            
        }
        update g2items;
        G2LItemErrorReportEmail.sendErrorReport(orderMUID);
        SBQQ.TriggerControl.enable();
    }
}