manifest/objects/G2LCRM_Item__c.object
<CustomObject>
    <fields>
        <fullName>Account_GUID__c</fullName>
        <label>Account GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Action__c</fullName>
        <defaultValue>&quot;create&quot;</defaultValue>
        <label>Action</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>create</fullName>
                </value>
                <value>
                    <fullName>update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUID__c</fullName>
        <label>MUID</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opp_GUId__c</fullName>
        <label>Opp GUId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_GUID__c</fullName>
        <label>Order GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processor__c</fullName>
        <label>Processor</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>account</fullName>
                </value>
                <value>
                    <fullName>order</fullName>
                </value>
                <value>
                    <fullName>accountV3</fullName>
                </value>
                <value>
                    <fullName>orderV3</fullName>
                </value>
                <value>
                    <fullName>orderItemV3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_System_Name__c</fullName>
        <label>Source System Name</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>(&quot;New&quot;)</defaultValue>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Done</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Processed with Error</fullName>
                </value>
                <value>
                    <fullName>Re-Broadcasted</fullName>
                </value>
                <value>
                    <fullName>Re-Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>G2LCRM Item</label>
    <nameField>
        <displayFormat>G2L-{00000000}</displayFormat>
        <label>G2LCRM ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>G2LCRM Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/G2LItemLog__c.object
<CustomObject>
    <fields>
        <fullName>G2LCRM_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>G2LCRM Item</label>
        <referenceTo>G2LCRM_Item__c</referenceTo>
        <relationshipLabel>G2LItemLogs</relationshipLabel>
        <relationshipName>G2LItemLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUID__c</fullName>
        <label>MUID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Module__c</fullName>
        <label>Module</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parsing_Results__c</fullName>
        <label>Parsing Results</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>G2LItemLog</label>
    <nameField>
        <displayFormat>G2LIL-{00000000}</displayFormat>
        <label>G2LItemLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>G2LItemLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/classes/G2LItemErrorReportEmail.cls
public class G2LItemErrorReportEmail {
    public static void sendErrorReport(String muid) {
        // Query the error logs
        List<G2LItemLog__c> errorLogs = [
            SELECT G2LCRM_Item__r.Account_GUID__c,
            G2LCRM_Item__r.Name,
            G2LCRM_Item__r.Source_System_Name__c,
            G2LCRM_Item__r.Opp_GUId__c,
            G2LCRM_Item__r.Order_GUID__c,
            G2LCRM_Item__c,
            G2LCRM_Item__r.Processor__c,
            G2LCRM_Item__r.Action__c,
            G2LCRM_Item__r.Status__c,
            Module__c,
            Method__c,
            Parsing_Results__c
            FROM G2LItemLog__c
            WHERE MUID__c = :muid order by createdDate
        ];
        
        if (!errorLogs.isEmpty()) {          
            // Build the HTML body
            String htmlBody = '<html><head><style>' +
                'table { border-collapse: collapse; width: 100%; }' +
                'th, td { border: 1px solid #ddd; padding: 8px; }' +
                'th { font-weight: bold; background-color: #f2f2f2; }' +
                '.parsing-result { min-width: 200px; }'+
                '.headercss { font-weight: bold }'+
                '</style></head><body>';
            htmlBody += '<h2>G2LCRM Error Report</h2>';
            htmlBody += '<div class="headercss">Source System Name : '+ errorLogs[0].G2LCRM_Item__r.Source_System_Name__c +'<br/>MUID : '+muid + '<br/>Account GUID : '+ errorLogs[0].G2LCRM_Item__r.Account_GUID__c +' <br/>Opportunity GUID : '+  errorLogs[0].G2LCRM_Item__r.Opp_GUId__c+' <br/>Order GUID : '+ errorLogs[0].G2LCRM_Item__r.Order_GUID__c+'</div>';
            htmlBody += '<br/><table class="table table-striped">';
            htmlBody += '<thead><tr><th>G2LCRMItem Name</th><th>Processor</th><th>Action</th><th>Status</th><th>Module</th><th>Method</th><th class="parsing-result">Parsing Result</th></tr></thead>';
            htmlBody += '<tbody>';
            
            for (G2LItemLog__c log : errorLogs) {
                htmlBody += '<tr>';
                htmlBody += '<td>' + log.G2LCRM_Item__r.Name+ '</td>';
                htmlBody += '<td>' + log.G2LCRM_Item__r.Processor__c + '</td>';
                htmlBody += '<td>' + log.G2LCRM_Item__r.Action__c + '</td>';
                htmlBody += '<td>' + log.G2LCRM_Item__r.Status__c + '</td>';
                htmlBody += '<td>' + log.Module__c + '</td>';
                htmlBody += '<td>' + log.Method__c + '</td>';
                htmlBody += '<td class="parsing-result">' + log.Parsing_Results__c + '</td>';
                htmlBody += '</tr>';
            }
            
            htmlBody += '</tbody></table>';
            htmlBody += '</body></html>';
            
            // Create and send the email
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            email.setToAddresses(new String[] {Label.Support_Team_Email});
            email.setSubject('Error Report for G2LCRM MUID: ' + muid);
            email.setHtmlBody(htmlBody);
            
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { email });
        }
    }
}