manifest/objects/L2O_Consult_Fee__c.object
<CustomObject>
    <fields>
        <fullName>L2O_Consult_Fee__c</fullName>
        <label>Consult Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>L2O_Parent_Product_Code__c</fullName>
        <formula>IF(ISBLANK(L2O_Parent_Product__r.ProductCode), &apos;NULL&apos; , L2O_Parent_Product__r.ProductCode)</formula>
        <label>Parent Product Code</label>
        <type>Text</type>
    </fields>
    <label>Consult Fee</label>
    <nameField>
        <displayFormat>CCF-{00000}</displayFormat>
        <label>Consult Fee</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consult Fees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

manifest/objects/Order.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/sbaa__Approval__c.object
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Quote.</description>
        <inlineHelpText>Lookup to Quote.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Approvals</relationshipLabel>
        <relationshipName>Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sbaa__ApprovalChain__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Approval Chain to which this Approval belongs</description>
        <inlineHelpText>Approval Chain to which this Approval belongs</inlineHelpText>
        <label>Approval Chain</label>
        <referenceTo>sbaa__ApprovalChain__c</referenceTo>
        <relationshipLabel>Approvals</relationshipLabel>
        <relationshipName>Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sbaa__ApprovalStep__c</fullName>
        <description>Step (level) at which this approval is required.</description>
        <inlineHelpText>Step (level) at which this approval is required.</inlineHelpText>
        <label>Approval Step</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sbaa__ApprovedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User who approved this Approval</description>
        <inlineHelpText>User who approved this Approval</inlineHelpText>
        <label>Approved By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ApprovedApprovals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sbaa__Approver__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to the Approver associated with this Approval.</description>
        <inlineHelpText>Lookup to the Approver associated with this Approval.</inlineHelpText>
        <label>Approver</label>
        <referenceTo>sbaa__Approver__c</referenceTo>
        <relationshipLabel>Approvals</relationshipLabel>
        <relationshipName>Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sbaa__Archived__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When Archived Approvals is enabled, indicates that this Approval is archived</description>
        <inlineHelpText>When Archived Approvals is enabled, indicates that this Approval is archived</inlineHelpText>
        <label>Archived</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sbaa__CommentsLong__c</fullName>
        <description>Approver&apos;s Comments</description>
        <inlineHelpText>Approver&apos;s Comments</inlineHelpText>
        <label>Comments</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>sbaa__RejectedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User who rejected this Approval</description>
        <inlineHelpText>User who rejected this Approval</inlineHelpText>
        <label>Rejected By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RejectedApprovals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sbaa__Status__c</fullName>
        <description>Status of this approval.</description>
        <inlineHelpText>Status of this approval.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                    <default>true</default>
                    <label>Assigned</label>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

manifest/objects/sbaa__ApprovalChain__c.object
<CustomObject>
    <customHelpPage>sbaa__ApprovalChainHelp</customHelpPage>
    <description>Chain of approvals. Multiple chains can be active in parallel on any given record.</description>
    <label>Approval Chain</label>
    <nameField>
        <label>Chain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Chains</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

manifest/objects/sbaa__Approver__c.object
<CustomObject>
    <customHelpPage>sbaa__ApproverHelp</customHelpPage>
    <description>Approvers are associated with the Approval Rule, driving what occurs on the Approval itself.</description>
    <label>Approver</label>
    <nameField>
        <label>Approver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__EffectiveStartDate__c</fullName>
        <description>Effective start date for this subscription.</description>
        <formula>IF(ISBLANK(SBQQ__StartDate__c),
  IF(ISBLANK(SBQQ__Group__r.SBQQ__StartDate__c),SBQQ__Quote__r.SBQQ__StartDate__c,SBQQ__Group__r.SBQQ__StartDate__c),
  SBQQ__StartDate__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Effective start date for this subscription.</inlineHelpText>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__ListPrice__c</fullName>
        <description>List unit price for the product quoted by this line item. List Price originates from the price book.</description>
        <inlineHelpText>List unit price for the product quoted by this line item. List Price originates from the price book.</inlineHelpText>
        <label>List Unit Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__NetTotal__c</fullName>
        <description>Net total price for this quote line item.</description>
        <formula>IF(AND(SBQQ__Renewal__c, !SBQQ__Existing__c, ISBLANK(SBQQ__PriorQuantity__c)), 0, SBQQ__NetPrice__c * SBQQ__EffectiveQuantity__c)</formula>
        <inlineHelpText>Net total price for this quote line item.</inlineHelpText>
        <label>Net Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProductName__c</fullName>
        <description>Name for the product referenced by this line item.</description>
        <formula>SBQQ__Product__r.Name</formula>
        <inlineHelpText>Name for the product referenced by this line item.</inlineHelpText>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity being quoted.</description>
        <inlineHelpText>Quantity being quoted.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
    <fields>
        <fullName>L2O_Consult_Fee__c</fullName>
        <description>Used when UGH Products are configured</description>
        <label>Consult Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

objects/SBQQ__QuoteLine__c.object
    <fields>
        <fullName>L2O_Membership_Fee__c</fullName>
        <description>This is the recurring subscription fee</description>
        <formula>IF(NOT(ISBLANK(TEXT(SBQQ__SubscriptionPricing__c))),
IF(ISPICKVAL(L2O_Service_Platform__c,&apos;HHS&apos;), SBQQ__NetPrice__c / SBQQ__ProrateMultiplier__c, SBQQ__ListPrice__c - L2O_Per_Unit_Discount__c), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The per unit per month price of this Subscription. Formerly known as Membership Fee</inlineHelpText>
        <label>Subscription Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

objects/SBQQ__QuoteLine__c.object
    <fields>
        <fullName>L2O_Parent_Product_Code__c</fullName>
        <description>Product code of the Parent Product related to this slide</description>
        <formula>IF(ISBLANK(SBQQ__RequiredBy__r.SBQQ__ProductCode__c), &apos;NULL&apos; , SBQQ__RequiredBy__r.SBQQ__ProductCode__c)</formula>
        <label>Parent Product Code</label>
        <type>Text</type>
    </fields>

objects/SBQQ__QuoteLine__c.object
    <fields>
        <fullName>L2O_Per_Unit_Discount__c</fullName>
        <description>Deal with USGH line items have the &quot;Per Unit Discount&quot; and not the OOB Add. Discount.
Per Unit Discount will only be Amount value and will basically be a dollar amount that can be deducted from List unit price</description>
        <label>Per Unit Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

manifest/objects/SBQQ__SubscribedQuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscribedAssetHelp</customHelpPage>
    <description>Links a particular asset to the subscription that covers it.</description>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the quote for the quoteLines.</description>
        <inlineHelpText>Identifies the quote for the quoteLines.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote</relationshipLabel>
        <relationshipName>Quote</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscribed Quote Line</label>
    <nameField>
        <displayFormat>SQL-{00000000}</displayFormat>
        <label>Subscribed Quote Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribed Quote Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/L2O_ApprovalController.cls
/**
* Company : PwC.
* @description : L2O_ApprovalController will be executed from the L2O_ApprovalRejectionSummary.
* *******************************************************************************************************************************************
* History : 
* @date 13/04/2022
* @author Harshita Paliwal
*/
public with sharing class L2O_ApprovalController {

    /**
    * @name  quoteId
    * @description quote Id value.
    * @params  none
    **/
    public String quoteId{get;set;}
    /**
    * @name  quoteValues
    * @description quote value.
    * @params  none
    **/
    public SBQQ__Quote__c quoteValues{
        get {
          SBQQ__Quote__c quote = [SELECT Id, Name FROM SBQQ__Quote__c WHERE id =: quoteId LIMIT 1];
          return quote; }
       set;
    }
    /**    
    * @name  lineItems
    * @description quote line items value.
    * @params  none
    **/
    public List<SBQQ__QuoteLine__c> lineItems{
        get{        
            List<SBQQ__QuoteLine__c> quoteList = [SELECT Name,SBQQ__ProductName__c,L2O_Parent_Product_Code__c,
                                                  SBQQ__Quantity__c,SBQQ__ListPrice__c,L2O_Per_Unit_Discount__c,
                                                  L2O_Membership_Fee__c,L2O_Consult_Fee__c,SBQQ__EffectiveStartDate__c,
                                                  SBQQ__Quote__r.L2O_ORG_LINK__c,SBQQ__NetTotal__c 
                                                  FROM SBQQ__QuoteLine__c WHERE SBQQ__Quote__c=:quoteId];
            
            return quoteList;
        }
        set;
    }
    /**
    * @name  lastApprovedBy
    * @description last approver of approval record.
    * @params  none
    **/
    public String lastApprovedBy{get;set;}
    /**
    * @name  listofapprovalRecords
    * @description list of approval records.
    * @params  none
    **/
    public List<sbaa__Approval__c> listofapprovalRecords{
        
        get{     
            List<sbaa__Approval__c> listofapprovalRecords = new List<sbaa__Approval__c>();
            List<sbaa__Approval__c> approvalRecords = [SELECT Name,sbaa__ApprovalChain__r.Name,sbaa__CommentsLong__c,sbaa__Status__c,
                                                 LastModifiedDate,sbaa__ApprovedBy__r.Name,sbaa__Archived__c,sbaa__ApprovalStep__c,sbaa__Approver__r.Name 
                                                 FROM sbaa__Approval__c WHERE Quote__c=:quoteId ORDER BY LastModifiedDate];
            
            for(sbaa__Approval__c approval:approvalRecords){
                if(approval.sbaa__Status__c == L2O_Constants.APPROVAL_STATUS_APPROVED && approval.sbaa__Archived__c == false){
                    listofapprovalRecords.add(approval);
                }
            }   
            if(!listofapprovalRecords.isEmpty()){
             lastApprovedBy = listofapprovalRecords.get(listofapprovalRecords.size()-1).sbaa__Approver__r.Name;
            }
            return listofapprovalRecords;
        }
           
    }
    /**
    * @name  lastRejectedBy
    * @description last approver of rejected record.
    * @params  none
    **/
    public String lastRejectedBy{get;set;}
    /**
    * @name  listOfRejectionRecords
    * @description list of rejection records.
    * @params  none
    **/
    public List<sbaa__Approval__c> listOfRejectionRecords{
        get{        
            
            List<sbaa__Approval__c> listOfRejectionRecords = new List<sbaa__Approval__c>();
            List<sbaa__Approval__c> rejectionRecords = [SELECT Name,sbaa__ApprovalChain__r.Name,sbaa__CommentsLong__c,sbaa__Status__c,
                                                 sbaa__RejectedBy__r.Name,sbaa__Archived__c,sbaa__ApprovalStep__c,sbaa__Approver__r.Name
                                                 FROM sbaa__Approval__c WHERE Quote__c=:quoteId];
               
            for(sbaa__Approval__c rejection:rejectionRecords){

                     if(rejection.sbaa__Status__c == L2O_Constants.APPROVAL_STATUS_REJECTED && rejection.sbaa__Archived__c == false){
                    	listOfRejectionRecords.add(rejection);
                     }
            }
            
            if(!listOfRejectionRecords.isEmpty()){
                lastRejectedBy = listOfRejectionRecords.get(listOfRejectionRecords.size()-1).sbaa__Approver__r.Name;

            } 
            
            return listOfRejectionRecords;
        }
      
    }
   
}