manifest/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Last_Status_Date__c</fullName>
        <description>Lead Trigger Updates the field when the Lead Status is updated.</description>
        <inlineHelpText>The Date/Time when the current Lead Status was set. Read Only field.</inlineHelpText>
        <label>Last Status Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Last_Status__c</fullName>
        <description>Lead Trigger updates the Last Status field when the Lead Status gets updated. Read Only field</description>
        <inlineHelpText>Read only field to capture the Last Status of the Lead.</inlineHelpText>
        <label>Last Status</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>LV Lead</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Last_Status__c.field-meta.xml
<CustomField>
    <fullName>Last_Status__c</fullName>
    <label>Last Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Last_Status_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Status_Date__c</fullName>
    <label>Last Status Date</label>
    <type>DateTime</type>
</CustomField>

manifest/classes/LeadTriggerHelper.cls
/**
 * Created by jpatel on 4/23/18.
 */

public with sharing class LeadTriggerHelper {
  public static void leadConvertionUpdate(List<Lead> leads) {
    //List of opportunity and Contact to update
    List<Opportunity> updateOppList = new List<Opportunity>();
    List<Contact> updateContactList = new List<Contact>();
    for (Lead l : leads) {
      if (l.IsConverted) {
        if (l.convertedOpportunityId != null)
          updateOppList.add(
            new Opportunity(id = l.convertedOpportunityId, Lead__c = l.Id)
          );
        if (l.ConvertedContactId != null)
          updateContactList.add(
            new Contact(id = l.ConvertedContactId, Lead__c = l.Id)
          );
      }
    }
    //update Contact and Opportunity
    update updateOppList;
    update updateContactList;
  }

  //This is to capture the LastStatus Change and LastStatusDate so these values can be added to the single report instead of looking into Lead History table
  public static void leadStatusChange(List<Lead> leads, Map<Id, Lead> oldMap) {
    Lead oldLead;
    for (Lead l : leads) {
      if (oldMap == null) {
        l.Last_Status__c = l.status;
        l.Last_Status_Date__c = Datetime.now();
      } else if (
        oldMap.get(l.id) != null &&
        l.status != oldMap.get(l.id).status
      ) {
        l.Last_Status__c = oldMap.get(l.id).status;
        l.Last_Status_Date__c = Datetime.now();
      }
    }
  }

  public static void leadCurrencyChange(
    List<Lead> leads,
    Map<Id, Lead> oldMap
  ) {
    Map<Id, User> CadUser = new Map<Id, User>(
      [SELECT Id FROM User WHERE DefaultCurrencyIsoCode = 'CAD']
    );
    for (Lead l : leads) {
      if (
        oldMap.get(l.Id) != null &&
        l.OwnerId != oldMap.get(l.Id).OwnerId &&
        CadUser.containsKey(l.ownerId) &&
        l.CurrencyIsoCode != 'CAD'
      ) {
        l.CurrencyIsoCode = 'CAD';
      } else if (
        oldMap.get(l.Id) != null &&
        l.OwnerId != oldMap.get(l.Id).OwnerId &&
        !CadUser.containsKey(l.ownerId) &&
        l.CurrencyIsoCode != 'USD'
      ) {
        l.CurrencyIsoCode = 'USD';
      }
    }
  }
}