manifest/objects/Legacy_Id__c.object
<CustomObject>
    <fields>
        <fullName>Master_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>ID of account that won the merge.</description>
        <label>Master Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Legacy Ids</relationshipLabel>
        <relationshipName>Legacy_Ids</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Name__c</fullName>
        <label>Original Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Id__c</fullName>
        <label>Source Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BD</fullName>
                </value>
                <value>
                    <fullName>HUB</fullName>
                </value>
                <value>
                    <fullName>TD</fullName>
                </value>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>LV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>guid__c</fullName>
        <label>GUID</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <label>Legacy Id</label>
    <nameField>
        <displayFormat>LID-{00000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Legacy Ids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Location__c.object
<CustomObject>
    <description>Used to store non-contractual locations such as broker locations, hospitals, and stores</description>
    <fields>
        <fullName>Former_GUID__c</fullName>
        <description>GUID of location when it was an ACCOUNT</description>
        <externalId>true</externalId>
        <label>Former GUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Legacy_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the former Account which got converted into Legacy Id on Master Account</description>
        <label>Legacy Id</label>
        <referenceTo>Legacy_Id__c</referenceTo>
        <relationshipLabel>Former Locations</relationshipLabel>
        <relationshipName>Former_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location_HQ__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location HQ</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/classes/AccountTriggerHelper.cls
public with sharing class AccountTriggerHelper {
  public static void setGUID(List<Account> new_accounts) {
    Set<String> candidate_guids = new Set<String>();
    Set<String> all_guids = new Set<String>();
    for (Account tmp_account : new_accounts) {
      all_guids.add(tmp_account.guid__c);
      if (tmp_account.source__c != 'HUB')
        continue;
      // Create new GUID if account is new or has invalid GUID
      if (
        String.isBlank(tmp_account.GUID__c) ||
        !GlobalIdUtils.isGuid(tmp_account.GUID__c)
      ) {
        tmp_account.GUID__c = GlobalIdUtils.generateGuid();
        candidate_guids.add(tmp_account.guid__c);
      } else
        candidate_guids.add(tmp_account.guid__c);
    }
    List<Legacy_Id__c> legacy_guids = [
      SELECT
        guid__c,
        source__c,
        source_id__c,
        original_name__c,
        master_account__r.name
      FROM legacy_id__c
      WHERE guid__c IN :all_guids
    ];
    Map<String, Legacy_id__c> mapped_lguids = new Map<String, Legacy_Id__c>();
    for (Legacy_Id__c tmp_lguid : legacy_guids) {
      mapped_lguids.put(tmp_lguid.guid__c, tmp_lguid);
    }

    List<Location__c> location_guids = [
      SELECT
        id,
        Former_GUID__c,
        Location_HQ__r.source__c,
        Location_HQ__r.source_id__c
      FROM location__C
      WHERE Former_GUID__c IN :all_guids
    ];
    Map<String, Location__c> mapped_locGuids = new Map<String, Location__c>();
    for (Location__c loc : location_guids) {
      mapped_locGuids.put(loc.Former_GUID__c, loc);
    }

    for (Account tmp_account : new_accounts) {
      if (mapped_lguids.containsKey(tmp_account.guid__c)) {
        legacy_id__c tmp_lguid = mapped_lguids.get(tmp_account.guid__c);
        if (tmp_lguid.guid__c != null) {
          string error_msg =
            'LEGACY ID FOUND: ' +
            tmp_lguid.guid__c +
            '_' +
            tmp_lguid.source__c +
            '_' +
            tmp_lguid.source_id__c;
          tmp_account.addError(error_msg);
        }
      }
      if (mapped_locGuids.containsKey(tmp_account.guid__c)) {
        Location__c tem_loc = mapped_locGuids.get(tmp_account.guid__c);
        if (tem_loc.Former_GUID__c != null) {
          string error_msg =
            'Location ID FOUND: ' +
            tem_loc.Former_GUID__c +
            '_' +
            tem_loc.Location_HQ__r.source__c +
            '_' +
            tem_loc.Location_HQ__r.source_id__c;
          tmp_account.addError(error_msg);
        }
      }
    }
  }
}