manifest/objects/Logo_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>isDocument__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isDocument</label>
        <type>Checkbox</type>
    </fields>
    <label>Logo Setting</label>
</CustomObject>

manifest/objects/Mbr_Group__c.object
<CustomObject>
    <fields>
        <fullName>Active_Date__c</fullName>
        <description>Date Group was built in Admin</description>
        <inlineHelpText>Date Group was built in Admin</inlineHelpText>
        <label>Active Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AltLogo1_ID__c</fullName>
        <description>Enter the logo document name for logo to appear.</description>
        <inlineHelpText>Enter the logo document name for logo to appear.</inlineHelpText>
        <label>AltLogo1 ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AltLogo2_ID__c</fullName>
        <description>Enter the logo document name for logo to appear.</description>
        <inlineHelpText>Enter the logo document name for logo to appear.</inlineHelpText>
        <label>AltLogo2 ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <description>Account that the Group is created</description>
        <inlineHelpText>Account that the Group is created</inlineHelpText>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Member Groups</relationshipLabel>
        <relationshipName>Member_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Logo1_ID__c</fullName>
        <label>Logo1_ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logo2_ID__c</fullName>
        <label>Logo2_ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logo3_ID__c</fullName>
        <label>Logo3_ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logo_Tag_ID__c</fullName>
        <label>Logo Tag# ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Enter a descriptive Member Group Name.</description>
        <inlineHelpText>Enter a descriptive Member Group Name.</inlineHelpText>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Use this as a backend field to identify the source of member group record</description>
        <inlineHelpText>Use this as a backend field to identify the source of member group record</inlineHelpText>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Data_Source</valueSetName>
        </valueSet>
    </fields>
    <label>Member Group</label>
    <nameField>
        <displayFormat>MG-{00000000}</displayFormat>
        <label>Member Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Mbr_Group_Role__c.object
<CustomObject>
    <fields>
        <fullName>Mbr_Group__c</fullName>
        <description>SF Record name of the Group</description>
        <inlineHelpText>SF Record name of the Group</inlineHelpText>
        <label>Member Group</label>
        <referenceTo>Mbr_Group__c</referenceTo>
        <relationshipLabel>Member Group Roles</relationshipLabel>
        <relationshipName>Member_Group_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role_Type__c</fullName>
        <description>Type of association with Group</description>
        <inlineHelpText>Type of association with Group</inlineHelpText>
        <label>Role Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Fee_Group_Role_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account that is servicing the type of role</description>
        <inlineHelpText>Account that is servicing the type of role</inlineHelpText>
        <label>Source Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Member Group Roles</relationshipLabel>
        <relationshipName>Member_Group_Roles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Member Group Role</label>
    <nameField>
        <displayFormat>MGR-{00000000}</displayFormat>
        <label>Member Group Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Group Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/globalValueSets/Data_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>HUB</fullName>
        <default>true</default>
        <label>HUB</label>
    </customValue>
    <customValue>
        <fullName>TD</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>LVGO</fullName>
    </customValue>
    <customValue>
        <fullName>GCRM</fullName>
    </customValue>
    <masterLabel>Data Source</masterLabel>
</GlobalValueSet>

manifest/globalValueSets/Fee_Group_Role_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Benefit Sponsor</fullName>
    </customValue>
    <customValue>
        <fullName>Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Contractee</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Payer</fullName>
    </customValue>
    <customValue>
        <fullName>MSU Access</fullName>
    </customValue>
    <masterLabel>Fee Group Role Type</masterLabel>
</GlobalValueSet>

manifest/classes/MemberGroupRoleController_Test.cls
@IsTest
private class MemberGroupRoleController_Test {
  @IsTest
  static void testBehavior() {
    Account umrAcct = TestDataFactory.createUMR();
    Account a = new Account(Name = 'Aetna', Source__c = 'HUB');
    insert a;
    Account b = new Account(Name = 'Aetna 1', Source__c = 'HUB');
    insert b;

    Mbr_Group__c g = new Mbr_Group__c(
      Name__c = 'test1',
      Client_Account__c = a.Id,
      Active_Date__c = Date.today()
    );
    insert g;

    Mbr_Group_Role__c r = new Mbr_Group_Role__c(
      Role_Type__c = 'Payer',
      Source_Account__c = b.Id,
      Mbr_Group__c = g.Id
    );
    insert r;

    Test.startTest();
    // Test group page
    ApexPages.StandardController sc = new ApexPages.StandardController(
      new Mbr_Group__c()
    );
    MemberGroupRoleController mc = new MemberGroupRoleController(sc);
    mc.setActiveDate();
    mc.addRole(); // force error adding a role

    mc.selGroup.Name__c = 'test2';
    mc.selGroup.Client_Account__c = a.Id;
    mc.selGroup.Active_Date__c = Date.today();

    // should be an error, since no new group info set
    mc.save();

    mc.newRoleWrapper.role.Role_Type__c = 'Broker';
    mc.addRole(); // force error adding a role

    mc.newRoleWrapper.role.Role_Type__c = null;
    mc.newRoleWrapper.role.Source_Account__c = b.Id;
    mc.addRole(); // force error adding a role

    mc.newRoleWrapper.role.Role_Type__c = 'Broker';
    mc.addRole(); // force error adding a role

    mc.save();
    mc.cancel();

    mc.selRoleId = mc.newRoleWrapper.role.Id;
    mc.deleteRole();

    Test.setCurrentPageReference(Page.MemberGroup);
    ApexPages.currentPage().getParameters().put('gid', g.Id);
    sc = new ApexPages.StandardController(g);

    mc = new MemberGroupRoleController(sc);
    mc.newRoleWrapper.role.Source_Account__c = null;
    mc.newRoleWrapper.role.Role_Type__c = 'Broker';
    mc.save();

    mc.newRoleWrapper.role.Source_Account__c = b.Id;
    mc.newRoleWrapper.role.Role_Type__c = null;
    mc.addRole(); // force error adding a role
    mc.save();

    mc.newRoleWrapper.role.Source_Account__c = b.Id;
    mc.newRoleWrapper.role.Role_Type__c = 'Eligibility Provider';
    mc.addRole(); // force error adding a role

    mc.newRoleWrapper.role.Source_Account__c = b.Id;
    mc.newRoleWrapper.role.Role_Type__c = 'ASO/TPA';
    mc.save();

    mc.newRoleWrapper.role.Source_Account__c = b.Id;
    mc.newRoleWrapper.role.Role_Type__c = 'Contractee';
    ApexPages.currentPage().getParameters().put('retURL', '/' + g.Id);
    mc.save();

    mc.newRoleWrapper.role.Source_Account__c = b.Id;
    mc.newRoleWrapper.role.Role_Type__c = 'Eligibility Provider';
    mc.addRole(); // force error adding a role
    mc.save();

    mc.newRoleWrapper.role.Source_Account__c = g.Id;
    mc.newRoleWrapper.role.Role_Type__c = 'NotaRole';
    mc.addRole(); // force error adding a role
    mc.save();

    mc.selRoleIndex = 2;
    mc.deleteRole();

    mc.selGroup.Logo_Tag_ID__c = 'biu';
    mc.selGroup.Logo1_ID__c = 'biu';
    mc.selGroup.Logo2_ID__c = 'biu';
    mc.selGroup.Logo3_ID__c = 'biu';
    mc.selGroup.AltLogo1_ID__c = 'biu';
    mc.selGroup.AltLogo2_ID__c = 'biu';
    mc.validateLogos();
    // force a nasty error
    try {
      mc.selGroup = g;
      mc.newRoleWrapper.role.Source_Account__c = g.Id;
      mc.newRoleWrapper.role.Role_Type__c = 'Broker';

      mc.addRole();
      mc.save();
    } catch (Exception e) {
      System.assert(!String.isBlank(e.getMessage()));
    }

    // Test redirect
    sc = new ApexPages.StandardController(r);
    MemberGroupRedirectExtension mgr = new MemberGroupRedirectExtension(sc);
    PageReference pageRef = Page.MemberGroupRedirect;
    pageRef.getParameters().put('id', r.Id);
    System.debug('RID:' + r.Id);
    Test.setCurrentPage(pageRef);
    mgr.redirect();
    delete r;
    mgr.redirect();

    // delete by Id
    Mbr_Group_Role__c roleToDelete = [SELECT Id FROM Mbr_Group_Role__c LIMIT 1];
    mc.selRoleId = roleToDelete.Id;
    mc.deleteRole();

    // Now make a new PSF
    mc.newPSF();

    // Test Cloning
    Test.setCurrentPageReference(Page.MemberGroup);
    ApexPages.currentPage().getParameters().put('id', g.Id);
    ApexPages.currentPage().getParameters().put('clone', '1');
    ApexPages.currentPage().getParameters().put('retURL', '/' + g.Id);

    sc = new ApexPages.StandardController(g);
    mc = new MemberGroupRoleController(sc);
    mc.selGroup.Name__c = 'newClone';
    mc.newRoleWrapper.role.Source_Account__c = b.Id;
    mc.newRoleWrapper.role.Role_Type__c = 'Benefit Sponsor';
    mc.addRole();
    mc.save();
    Test.stopTest();
  }

  @IsTest
  static void testBehavior2() {
    Account umrAcct = TestDataFactory.createUMR();
    Account a = new Account(Name = 'Aetna', Source__c = 'HUB');
    insert a;
    Account b = new Account(Name = 'Aetna 1', Source__c = 'HUB');
    insert b;

    Mbr_Group__c g = new Mbr_Group__c(
      Name__c = 'test1',
      Client_Account__c = a.Id,
      Active_Date__c = Date.today()
    );
    insert g;

    Mbr_Group_Role__c r = new Mbr_Group_Role__c(
      Role_Type__c = 'Payer',
      Source_Account__c = b.Id,
      Mbr_Group__c = g.Id
    );
    insert r;

    logo_setting__c ls = logo_setting__c.getOrgDefaults();
    ls.isDocument__c = true;
    insert ls;

    Test.startTest();
    // Test group page
    ApexPages.StandardController sc = new ApexPages.StandardController(
      new Mbr_Group__c()
    );
    MemberGroupRoleController mc = new MemberGroupRoleController(sc);
    mc.setActiveDate();
    mc.addRole(); // force error adding a role

    mc.selGroup.Name__c = 'test2';
    mc.selGroup.Client_Account__c = a.Id;
    mc.selGroup.Active_Date__c = Date.today();

    // should be an error, since no new group info set
    mc.save();

    mc.newRoleWrapper.role.Role_Type__c = 'Broker';
    mc.addRole(); // force error adding a role

    mc.newRoleWrapper.role.Role_Type__c = null;
    mc.newRoleWrapper.role.Source_Account__c = b.Id;
    mc.addRole(); // force error adding a role

    mc.newRoleWrapper.role.Role_Type__c = 'Broker';
    mc.addRole(); // force error adding a role

    mc.save();
    mc.cancel();

    mc.selRoleId = mc.newRoleWrapper.role.Id;
    mc.deleteRole();

    Test.setCurrentPageReference(Page.MemberGroup);
    ApexPages.currentPage().getParameters().put('gid', g.Id);
    sc = new ApexPages.StandardController(g);

    mc = new MemberGroupRoleController(sc);
    mc.newRoleWrapper.role.Source_Account__c = null;
    mc.newRoleWrapper.role.Role_Type__c = 'Broker';
    mc.save();

    mc.newRoleWrapper.role.Source_Account__c = b.Id;
    mc.newRoleWrapper.role.Role_Type__c = null;
    mc.addRole(); // force error adding a role
    mc.save();

    mc.newRoleWrapper.role.Source_Account__c = b.Id;
    mc.newRoleWrapper.role.Role_Type__c = 'Eligibility Provider';
    mc.addRole(); // force error adding a role

    mc.newRoleWrapper.role.Source_Account__c = b.Id;
    mc.newRoleWrapper.role.Role_Type__c = 'ASO/TPA';
    mc.save();

    mc.newRoleWrapper.role.Source_Account__c = b.Id;
    mc.newRoleWrapper.role.Role_Type__c = 'Contractee';
    ApexPages.currentPage().getParameters().put('retURL', '/' + g.Id);
    mc.save();

    mc.newRoleWrapper.role.Source_Account__c = b.Id;
    mc.newRoleWrapper.role.Role_Type__c = 'Eligibility Provider';
    mc.addRole(); // force error adding a role
    mc.save();

    mc.newRoleWrapper.role.Source_Account__c = g.Id;
    mc.newRoleWrapper.role.Role_Type__c = 'NotaRole';
    mc.addRole(); // force error adding a role
    mc.save();

    mc.selRoleIndex = 2;
    mc.deleteRole();

    mc.selGroup.Logo_Tag_ID__c = 'biu';
    mc.selGroup.Logo1_ID__c = 'biu';
    mc.selGroup.Logo2_ID__c = 'biu';
    mc.selGroup.Logo3_ID__c = 'biu';
    mc.selGroup.AltLogo1_ID__c = 'biu';
    mc.selGroup.AltLogo2_ID__c = 'biu';
    mc.validateLogos();
    // force a nasty error
    try {
      mc.selGroup = g;
      mc.newRoleWrapper.role.Source_Account__c = g.Id;
      mc.newRoleWrapper.role.Role_Type__c = 'Broker';

      mc.addRole();
      mc.save();
    } catch (Exception e) {
      System.assert(!String.isBlank(e.getMessage()));
    }

    // Test redirect
    sc = new ApexPages.StandardController(r);
    MemberGroupRedirectExtension mgr = new MemberGroupRedirectExtension(sc);
    PageReference pageRef = Page.MemberGroupRedirect;
    pageRef.getParameters().put('id', r.Id);
    System.debug('RID:' + r.Id);
    Test.setCurrentPage(pageRef);
    mgr.redirect();
    delete r;
    mgr.redirect();

    // delete by Id
    Mbr_Group_Role__c roleToDelete = [SELECT Id FROM Mbr_Group_Role__c LIMIT 1];
    mc.selRoleId = roleToDelete.Id;
    mc.deleteRole();

    // Now make a new PSF
    mc.newPSF();

    // Test Cloning
    Test.setCurrentPageReference(Page.MemberGroup);
    ApexPages.currentPage().getParameters().put('id', g.Id);
    ApexPages.currentPage().getParameters().put('clone', '1');
    ApexPages.currentPage().getParameters().put('retURL', '/' + g.Id);

    sc = new ApexPages.StandardController(g);
    mc = new MemberGroupRoleController(sc);
    mc.selGroup.Name__c = 'newClone';
    mc.newRoleWrapper.role.Source_Account__c = b.Id;
    mc.newRoleWrapper.role.Role_Type__c = 'Benefit Sponsor';
    mc.addRole();
    mc.save();
    Test.stopTest();
  }
}