manifest/objects/LVGO__Account__c.object
<CustomObject>
    <fields>
        <fullName>LVGO__Source_ID__c</fullName>
        <label>Source ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LVGO__Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TD</fullName>
                </value>
                <value>
                    <fullName>LV</fullName>
                </value>
                <value>
                    <fullName>ITH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>LV Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/LVGO__Contract__c.object
<CustomObject>
    <fields>
        <fullName>LVGO__Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Edits Controlled - Financially Material -  Flows to Redshift</inlineHelpText>
        <label>Account</label>
        <referenceTo>LVGO__Account__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>LVGO_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LVGO__BillingPartner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Integrated with NetSuite</description>
        <inlineHelpText>Integrated with NetSuite</inlineHelpText>
        <label>Billing Partner</label>
        <referenceTo>LVGO__Account__c</referenceTo>
        <relationshipLabel>Contracts (Billing Partner)</relationshipLabel>
        <relationshipName>LVGO_Contracts_BillingPartner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LVGO__Contract_Path__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Edits Controlled - Financially Material</inlineHelpText>
        <label>Contract Path</label>
        <referenceTo>LVGO__Account__c</referenceTo>
        <relationshipLabel>Contracts (Contract Path)</relationshipLabel>
        <relationshipName>LVGO_Contracts_ContractPath</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LVGO__Pricebook2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricebook</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>LGVO_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LV Contract</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/LVGO__Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>LVGO__Account__c</fullName>
        <label>Account</label>
        <referenceTo>LVGO__Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>LVGO_Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LVGO__BillingPartner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales will populate this field during the sales cycle with initial ideas around the Billing Partner for a deal.  Once a deal goes into contracting, the official Billing Partner is established as a relationship in the Relationship table.</description>
        <inlineHelpText>Sales will populate this field during the sales cycle with initial ideas around the Billing Partner for a deal.  Once a deal goes into contracting, the official Billing Partner is established as a relationship in the Relationship table.</inlineHelpText>
        <label>Pre-Contracting Billing Partner</label>
        <referenceTo>LVGO__Account__c</referenceTo>
        <relationshipLabel>Opportunities (Billing_Partner__c)</relationshipLabel>
        <relationshipName>LVGO_Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LVGO__Loss_Reason__c</fullName>
        <label>Loss Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lost to Competitor</fullName>
                </value>
                <value>
                    <fullName>No Budget / Lost Funding</fullName>
                </value>
                <value>
                    <fullName>No Decision / Non-Responsive</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LVGO__Lost_Reason__c</fullName>
        <label>Lost Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>LVGO__StageName__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>No Executive Approval</fullName>
                </value>
                <value>
                    <fullName>No Budget</fullName>
                </value>
                <value>
                    <fullName>Key Contact Departure/Leadership Change</fullName>
                </value>
                <value>
                    <fullName>Company Acquired</fullName>
                </value>
                <value>
                    <fullName>Lost to Competitor</fullName>
                </value>
                <value>
                    <fullName>Other Competing Priorities</fullName>
                </value>
                <value>
                    <fullName>Rebate Issues</fullName>
                </value>
                <value>
                    <fullName>Included in FI or ASO Opt-Out</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <label>Other (please specify in the opportunity update field)</label>
                </value>
                <value>
                    <fullName>Couldn&apos;t make a decision</fullName>
                </value>
                <value>
                    <fullName>Didn&apos;t Understand ROI</fullName>
                </value>
                <value>
                    <fullName>Lack of Understanding</fullName>
                </value>
                <value>
                    <fullName>No Budget - decided not to pursue</fullName>
                </value>
                <value>
                    <fullName>No Strategic Fit</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Teladoc Channel Partner Won It - Not Direct</fullName>
                </value>
                <value>
                    <fullName>Timing Wrong</fullName>
                </value>
                <value>
                    <fullName>Too Expensive</fullName>
                </value>
                <value>
                    <fullName>Transferred to ITH</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LVGO__Pre_Contracting_Contract_Paper__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales will populate this field during the sales cycle with expected Contract Paper for the Opportunity. Additionally, the Contract Path field is also required before an Opp can be closed won.</description>
        <inlineHelpText>Sales will populate this field during the sales cycle with expected Contract Paper for the Opportunity. Additionally, the Contract Path field is also required before an Opp can be closed won.</inlineHelpText>
        <label>Pre-Contracting Contract Paper</label>
        <referenceTo>LVGO__Account__c</referenceTo>
        <relationshipLabel>Opportunities (Pre-Contracting Contract Paper)</relationshipLabel>
        <relationshipName>LVGO_Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LVGO__Pricebook2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricebook</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>LGVO_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LVGO__Source_ID__c</fullName>
        <label>Source ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LVGO__Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TD</fullName>
                </value>
                <value>
                    <fullName>LV</fullName>
                </value>
                <value>
                    <fullName>ITH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LVGO__StageName__c</fullName>
        <label>Stage</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Discovery</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>Review/Negotiation</fullName>
                </value>
                <value>
                    <fullName>Contracting</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
                <value>
                    <fullName>Closed No Decision</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>LV Opportunity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/LVGO__OpportunityLineItem__c.object
<CustomObject>
    <fields>
        <fullName>LVGO__Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>LVGO__Opportunity__c</referenceTo>
        <relationshipLabel>Opportunity Products</relationshipLabel>
        <relationshipName>LGVO_OpportunityProducts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LVGO__Product_Participants__c</fullName>
        <inlineHelpText>For new opportunities, enter estimated recruitables or rPwX. For renewals, enter enrolled members.</inlineHelpText>
        <label>Program Participants (rPwX or Enrolled)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LVGO__Source_id__c</fullName>
        <label>Source Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LVGO__UnitPrice__c</fullName>
        <inlineHelpText>For all Whole Person opportunities, input the Whole Person PPPM for the solution. Do not input the incremental sales price. To capture a Whole Person upgrade populate the section below titled &apos;Whole Person Upgrade</inlineHelpText>
        <label>Sales Price</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>LV Opportunity Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LV OpportunityLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Q_Item__c.object
<CustomObject>
    <fields>
        <fullName>Parser_Name__c</fullName>
        <label>Parser Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payload__c</fullName>
        <label>Payload</label>
        <length>65536</length>
        <type>LongTextArea</type>
    </fields>
    <label>Q Item</label>
    <nameField>
        <label>Q Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Q Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/Q_Item_Exception__c.object
<CustomObject>
    <fields>
        <fullName>Q_Item__c</fullName>
        <label>Q Item</label>
        <referenceTo>Q_Item__c</referenceTo>
        <relationshipLabel>Q Item Exceptions</relationshipLabel>
        <relationshipName>Q_Item_Exceptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Q Item Exception</label>
    <nameField>
        <label>Q Item Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Q Item Exceptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/classes/MB_QXfr_Process.cls
// CORE PROCESS CLASSES (MOST LIKELY BE LVN SIDE)
public class MB_QXfr_Process {
  public static Map<String, Object> processQ(Q_Item__c qItem) {
    System.debug('In MB_QXfr_Process.Process Q');
    Map<String, Object> results = new Map<String, Object>();
    switch on qItem.Parser_Name__c {
      when 'Opportunity_Parser' {
        QItem_Opp_Parser qitemp = new QItem_Opp_Parser();
        qitemp.Parse(qItem.Payload__c);
        //System.debug('qitemp after parse() ' +qitemp );
        //System.debug('qitemp after parse(LVGO__UnitPrice__c) ' +qitemp.QItemOppli.oppliList[0].LVGO__UnitPrice__c );
        // System.debug('qitemp after parse(LVGO__Product_Participants__c) ' +qitemp.QItemOppli.oppliList[0].LVGO__Product_Participants__c );

        results = OpportunityParserProcess(qitemp, qItem.Id);
      }
      when 'Delete_Parser' {
        QItem_Opp_Parser qitemp = new QItem_Opp_Parser();
        qitemp.Parse(qItem.Payload__c);
        results = deleteOpp(qitemp, qItem.Id);
      }
      when else {
      }
    }
    return results;
  }

  public static Map<String, Object> OpportunityParserProcess(
    QItem_Opp_Parser qitemp,
    String qItemId
  ) {
    Map<String, Object> results = new Map<String, Object>();
    results.put('parsing_errors', null);
    results.put('dml_errors', null);
    results.put('lvn_acct_url', '');
    results.put('tdh_acct_id', '');
    results.put('lvn_opp_id', '');
    results.put('tdh_opp_id', '');
    Map<String, String> parsingErrors = new Map<String, String>();
    List<Q_Item_Exception__c> oldQEx = [
      SELECT Id
      FROM Q_Item_Exception__c
      WHERE Q_Item__c = :qItemId
    ];
    delete oldQEx;
    if (qitemp.QItemAcct != null && qitemp.QItemAcct.parsingErrors.size() > 0) {
      for (String error : qitemp.QItemAcct.parsingErrors.keyset()) {
        parsingErrors.put(
          'ACCOUNT_LEVEL_BAD_DATA',
          error + ' : ' + qitemp.QItemAcct.parsingErrors.get(error)
        );
      }
    }
    if (qitemp.QItemOpp != null && qitemp.QItemOpp.parsingErrors.size() > 0) {
      for (String error : qitemp.QItemOpp.parsingErrors.keyset()) {
        parsingErrors.put(
          'OPPORTUNITY_LEVEL_BAD_DATA',
          error + ' : ' + qitemp.QItemOpp.parsingErrors.get(error)
        );
      }
    }

    if (
      qitemp.QItemCarrierAcct != null &&
      qitemp.QItemCarrierAcct.parsingErrors.size() > 0
    ) {
      for (String error : qitemp.QItemCarrierAcct.parsingErrors.keyset()) {
        parsingErrors.put(
          'PRIMARY_CARRIER_ACCOUNT_LEVEL_BAD_DATA',
          error + ' : ' + qitemp.QItemCarrierAcct.parsingErrors.get(error)
        );
      }
    }

    if (
      qitemp.QItemOppli != null &&
      qitemp.QItemOppli.parsingErrors.size() > 0
    ) {
      for (String error : qitemp.QItemOppli.parsingErrors.keyset()) {
        parsingErrors.put(
          'PRODUCT_LEVEL_BAD_DATA',
          error + ' : ' + qitemp.QItemOppli.parsingErrors.get(error)
        );
      }
    }

    if (qitemp.QItemAcct.TdhAcctId != null) {
      results.put('tdh_acct_id', qitemp.QItemAcct.TdhAcctId);
      System.debug('TDH AccountId ' + qitemp.QItemAcct.TdhAcctId);
    }

    if (qitemp.QItemOpp.TdhOppId != null) {
      results.put('tdh_opp_id', qitemp.QItemOpp.TdhOppId);
    }

    if (parsingErrors.size() == 0) {
      system.debug('venu --- qitem' + qitemp);
      MB_QxfrUtils.FetchExistingData(qitemp, qItemId);
      LVGO__Account__c acct = new LVGO__Account__c();
      LVGO__Opportunity__c opp = new LVGO__Opportunity__c();

      if (MB_QxfrUtils.existingAcct == null) {
        acct = qitemp.QItemAcct.Acct;
        acct.Id = null;
        acct.LVGO__Source__c = 'TD';
        if (qitemp.QItemAcct.RecordType == 'Downmarket Client') {
          acct.RecordTypeId = MB_QxfrUtils.DownMarketId;
        }
        try {
          insert acct;
          results.put(
            'lvn_acct_url',
            URL.getOrgDomainUrl().toExternalForm() + '/' + acct.Id
          );
        } catch (exception e) {
          MB_QxfrUtils.LogException(
            qItemId,
            'LVGO__ACCOUNT__C',
            'DML_ERROR',
            'CANNOT_CREATE_LVGO__ACCOUNT__C',
            e.getMessage()
          );
          acct = null;
        }
      } else {
        acct = MB_QxfrUtils.existingAcct;
        Boolean isUpdateAcct = Account_Parser.CalculateDelta(
          qitemp.QItemAcct.fieldDeltas,
          qitemp.QItemAcct.Acct,
          acct
        );
        results.put(
          'lvn_acct_url',
          URL.getOrgDomainUrl().toExternalForm() + '/' + acct.Id
        );
        if (isUpdateAcct) {
          try {
            update acct;
          } catch (exception e) {
            MB_QxfrUtils.LogException(
              qItemId,
              'LVGO__ACCOUNT__C',
              'DML_ERROR',
              'CANNOT_UPDATE_LVGO__ACCOUNT__C',
              e.getMessage()
            );
          }
        }
      }

      if (acct != null) {
        if (MB_QxfrUtils.existingOpp == null) {
          system.debug(Opp.LVGO__Source_ID__c);
          opp = qitemp.QItemOpp.Opp;
          String StageValue = opp.LVGO__StageName__c;
          String lostReason = opp.LVGO__Loss_Reason__c;
          opp.Id = null;
          opp.LVGO__Account__c = acct.Id;
          opp.LVGO__Source__c = 'TD';
          opp.LVGO__StageName__c = 'Prospect';
          opp.LVGO__Lost_Reason__c = null;
          opp.LVGO__Pricebook2__c = MB_QxfrUtils.LvnPriceBookId;
          if (MB_QxfrUtils.contractAcct != null) {
            opp.LVGO__Pre_Contracting_Contract_Paper__c = MB_QxfrUtils.contractAcct.Id;
            opp.LVGO__BillingPartner__c = MB_QxfrUtils.contractAcct.Id;
            opp.LVGO__Contract_Path__c = MB_QxfrUtils.contractAcct.Id;
          } else {
            opp.LVGO__Pre_Contracting_Contract_Paper__c = MB_QxfrUtils.LvnAcct.Id;
            opp.LVGO__BillingPartner__c = MB_QxfrUtils.LvnAcct.Id;
            opp.LVGO__Contract_Path__c = MB_QxfrUtils.LvnAcct.Id;
          }

          try {
            insert opp;
            results.put('lvn_opp_id', opp.Id);
          } catch (exception e) {
            MB_QxfrUtils.LogException(
              qItemId,
              'LVGO__Opportunity__c',
              'DML_ERROR',
              'CANNOT_CREATE_LVGO__OPPORTUNITY__C',
              e.getMessage()
            );
            opp = null;
          }
          if (opp != null) {
            List<LVGO__OpportunityLineItem__c> oppliList = new List<LVGO__OpportunityLineItem__c>();
            for (
              LVGO__OpportunityLineItem__c oppli : MB_QxfrUtils.newOppli.values()
            ) {
              oppli.LVGO__Opportunity__c = opp.Id;
              oppliList.add(oppli);
            }
            Database.SaveResult[] sr = Database.insert(oppliList, false);
            for (Database.SaveResult rowSr : sr) {
              if (!rowSr.isSuccess()) {
                for (Database.Error rowError : rowSr.getErrors()) {
                  MB_QxfrUtils.LogException(
                    qItemId,
                    'LVGO__OpportunityLineItem__c',
                    'ERROR',
                    'CANNOT_INSERT_LVGO__OPPORTUNITYLINEITEM__C',
                    rowError.getMessage()
                  );
                }
              }
            }
            opp.LVGO__StageName__c = StageValue;
            opp.LVGO__Lost_Reason__c = lostReason;
            try {
              update opp;
              results.put('lvn_opp_id', opp.Id);
            } catch (exception e) {
              MB_QxfrUtils.LogException(
                qItemId,
                'LVGO__OPPORTUNITY__C',
                'DML_ERROR',
                'CANNOT_UPDATE_LVGO__OPPORTUNITY__C',
                e.getMessage()
              );
              opp = null;
            }
          }
        } else {
          opp = MB_QxfrUtils.existingOpp;
          Boolean isUpdateOpp = Opportunity_Parser.CalculateDelta(
            qitemp.QItemOpp.fieldDeltas,
            qitemp.QItemOpp.Opp,
            opp,
            acct
          );
          opp.LVGO__Source__c = 'TD';
          if (MB_QxfrUtils.contractAcct != null) {
            if (
              opp.LVGO__Pre_Contracting_Contract_Paper__c !=
              MB_QxfrUtils.contractAcct.Id ||
              opp.LVGO__BillingPartner__c != MB_QxfrUtils.contractAcct.Id
            ) {
              opp.LVGO__Pre_Contracting_Contract_Paper__c = MB_QxfrUtils.contractAcct.Id;
              opp.LVGO__BillingPartner__c = MB_QxfrUtils.contractAcct.Id;
              opp.LVGO__Contract_Path__c = MB_QxfrUtils.contractAcct.Id;
              isUpdateOpp = true;
            }
          } else {
            if (opp.LVGO__Contract_Path__c != MB_QxfrUtils.LvnAcct.Id) {
              isUpdateOpp = true;
            }
            opp.LVGO__Pre_Contracting_Contract_Paper__c = MB_QxfrUtils.LvnAcct.Id;
            opp.LVGO__BillingPartner__c = MB_QxfrUtils.LvnAcct.Id;
            opp.LVGO__Contract_Path__c = MB_QxfrUtils.LvnAcct.Id;
          }

          Boolean noProd = MB_QxfrUtils.newOppli.isEmpty();

          if (MB_QxfrUtils.existingOppli != null) {
            for (String key : MB_QxfrUtils.newOppli.keySet()) {
              if (MB_QxfrUtils.existingOppli.containsKey(key)) {
                MB_QxfrUtils.newOppli.remove(key);
                MB_QxfrUtils.existingOppli.remove(key);
              }
            }
          }
          for (
            LVGO__OpportunityLineItem__c oppli : MB_QxfrUtils.newOppli.values()
          ) {
            oppli.LVGO__Opportunity__c = opp.Id;
          }

          Database.SaveResult[] sr = Database.insert(
            MB_QxfrUtils.newOppli.values(),
            false
          );
          for (Database.SaveResult rowSr : sr) {
            if (!rowSr.isSuccess()) {
              for (Database.Error rowError : rowSr.getErrors()) {
                MB_QxfrUtils.LogException(
                  qItemId,
                  'OPPORTUNITYLINEITEM',
                  'ERROR',
                  'CANNOT_INSERT_OPPORTUNITYLINEITEM',
                  rowError.getMessage()
                );
              }
            }
          }

          if (MB_QxfrUtils.existingOppli != null) {
            List<LVGO__OpportunityLineItem__c> deleteOppliList = new List<LVGO__OpportunityLineItem__c>();
            for (
              List<LVGO__OpportunityLineItem__c> oppList : MB_QxfrUtils.existingOppli.values()
            ) {
              deleteOppliList.addAll(oppList);
            }
            Database.DeleteResult[] dr = Database.delete(
              deleteOppliList,
              false
            );
            for (Database.DeleteResult rowSr : dr) {
              if (!rowSr.isSuccess()) {
                for (Database.Error rowError : rowSr.getErrors()) {
                  MB_QxfrUtils.LogException(
                    qItemId,
                    'OPPORTUNITYLINEITEM',
                    'ERROR',
                    'CANNOT_DELETE_OPPORTUNITYLINEITEM',
                    rowError.getMessage()
                  );
                }
              }
            }
          }

          if (isUpdateOpp) {
            try {
              if (opp.LVGO__StageName__c == 'Closed Won' && noProd) {
                opp.LVGO__StageName__c = 'Closed Lost';
                opp.LVGO__Lost_Reason__c = 'Other';
                opp.LVGO__Opportunity_Update_Next_Step__c = 'No LVN Program in TD Opportuntiy';
              }
              update opp;
              results.put('lvn_opp_id', opp.Id);
            } catch (exception e) {
              MB_QxfrUtils.LogException(
                qItemId,
                'OPPORTUNITY',
                'DML_ERROR',
                'CANNOT_UPDATE_OPPORTUNITY',
                e.getMessage()
              );
            }
          }
        }
      }
    }
    MB_QxfrUtils.CommitDelta();

    Map<Id, Q_Item_Exception__c> qException = new Map<Id, Q_Item_Exception__c>(
      [
        SELECT Exception_Type__c, Short_Desc__c, SObject__c, Full_Desc__c
        FROM Q_Item_Exception__c
        WHERE Q_Item__c = :qItemId
      ]
    );
    results.put('dml_errors', qException);
    results.put('parsing_errors', parsingErrors);
    System.debug('Parsing_errors ' + parsingErrors);
    System.debug('dml_errors ' + qException);
    return results;
  }

  public static Map<String, Object> deleteOpp(
    QItem_Opp_Parser qitemp,
    String qItemId
  ) {
    Map<String, Object> results = new Map<String, Object>();
    results.put('parsing_errors', null);
    results.put('dml_errors', null);
    results.put('lvn_acct_url', '');
    results.put('tdh_acct_id', '');
    results.put('lvn_opp_id', '');
    results.put('tdh_opp_id', '');
    Map<String, String> parsingErrors = new Map<String, String>();
    List<Q_Item_Exception__c> oldQEx = [
      SELECT Id
      FROM Q_Item_Exception__c
      WHERE Q_Item__c = :qItemId
    ];
    delete oldQEx;
    if (qitemp == null || qitemp.parsingErrors.size() > 0) {
      parsingErrors.put(
        'BAD_ITEM_DATA',
        'The payload provided for [' + qItemId + '] was invalid.'
      );
    } else {
      List<LVGO__Opportunity__c> opp = [
        SELECT Id, LVGO__Contract__c
        FROM LVGO__Opportunity__c
        WHERE LVGO__TD_Opp_Guid__c = :qitemp.QItemOpp.Opp.LVGO__TD_Opp_Guid__c
      ];
      if (!opp.isEmpty()) {
        /*
                List<Relationship__c> rList = [SELECT Id FROM Relationship__c WHERE Opportunity_Partnership__c =: opp[0].Id OR Opportunity_Competition__c =: opp[0].Id];
                try {
                    Delete rList;
                } catch (exception e) {
                    MB_QxfrUtils.LogException(qItemId, 'RELATIONSHIP', 'DML_ERROR', 'CANNOT_DELETE_RELATIONSHIP', e.getMessage());
                }
                List<Contract> clientContract = [SELECT Id FROM Contract WHERE Id =: opp[0].ContractId];
                if(!clientContract.isEmpty()) {
                    List<Contract> programContract = [SELECT Id FROM Contract WHERE Client_Overview__c =: clientContract[0].Id];
                    if(!programContract.isEmpty()) {
                        try {
                            Delete programContract;
                        } catch (exception e) {
                            MB_QxfrUtils.LogException(qItemId, 'PROGRAM CONTRACT', 'DML_ERROR', 'CANNOT_DELETE_PROGRAMCONTRACT', e.getMessage());
                        }
                    }
                    try {
                        Delete clientContract;
                    } catch (exception e) {
                        MB_QxfrUtils.LogException(qItemId, 'CLIENT CONTRACT', 'DML_ERROR', 'CANNOT_DELETE_CLIENTCONTRACT', e.getMessage());
                    }
                }*/
        try {
          delete opp;
        } catch (exception e) {
          MB_QxfrUtils.LogException(
            qItemId,
            'OPPORTUNITY',
            'DML_ERROR',
            'CANNOT_DELETE_OPPORTUNITY',
            e.getMessage()
          );
        }
      }
    }
    MB_QxfrUtils.CommitDelta();
    Map<Id, Q_Item_Exception__c> qException = new Map<Id, Q_Item_Exception__c>(
      [
        SELECT Exception_Type__c, Short_Desc__c, SObject__c, Full_Desc__c
        FROM Q_Item_Exception__c
        WHERE Q_Item__c = :qItemId
      ]
    );
    results.put('dml_errors', qException);
    results.put('parsing_errors', parsingErrors);
    return results;
  }
}