manifest/objects/Mbr_Group__c.object
<CustomObject>
    <label>Member Group</label>
    <nameField>
        <displayFormat>MG-{00000000}</displayFormat>
        <label>Member Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this Opportunity Product.</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>OpportunityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

manifest/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/classes/relatedListLwcControllerTest.cls
@IsTest
private class relatedListLwcControllerTest {
    @TestSetup
    static void setup(){
        Account umrAcct = TestDataFactory.createUMR();        
        Account accObj = TestDataFactory.createAccountUMR();
        
        Mbr_Group__c mbrGrp = TestDataFactory.createMbrGroup(accObj.Id)[0];
        
        //create an opportunity record
        Opportunity opp = TestDataFactory.createOpportunity(accObj.Id);     
        opp.LeadSource = 'Sales';
        insert opp;
       
        SBQQ__Quote__c sbqqQte = TestDataFactory.createQuote(opp.Id);
        insert sbqqQte;
        
        //create Gen Med - Consult Fee product
        Product2 prod = TestDataFactory.createSingleProduct('GM - Consult Fee', 'General Medical', 'GMCF');
        insert Prod;
        
        SBQQ__QuoteLine__c quoline = TestDataFactory.createQuoteLine(sbqqQte.Id, prod.Id);
        insert quoline;
        
         

        
    }
    
    @IsTest
    static void getQteLineTest() {
        SBQQ__Quote__c qte = [SELECT Id FROM SBQQ__Quote__c];      
        List<SBQQ__QuoteLine__c> qteLineList = relateListLwcController.getQteLine(qte.Id);
        system.assertEquals(1, qteLineList.size());           
    }
    
    @IsTest
    static void getOppProdTest() {
        Opportunity opp = [SELECT Id FROM Opportunity];      
        List<OpportunityLineItem> oppProdList = relateListLwcController.getOppProd(opp.Id);
        system.assertEquals(0, oppProdList.size());           
    }
    
    @IsTest
    static void getOppQteTest() {
        Opportunity opp = [SELECT Id FROM Opportunity];      
        List<SBQQ__Quote__c> qteList = relateListLwcController.getOppQte(opp.Id);
        system.assertEquals(1, qteList.size());           
    }
}