manifest/objects/Mbr_Group__c.object
<CustomObject>
    <label>Member Group</label>
    <nameField>
        <displayFormat>MG-{00000000}</displayFormat>
        <label>Member Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Mbr_Group_Role__c.object
<CustomObject>
    <fields>
        <fullName>Mbr_Group__c</fullName>
        <description>SF Record name of the Group</description>
        <inlineHelpText>SF Record name of the Group</inlineHelpText>
        <label>Member Group</label>
        <referenceTo>Mbr_Group__c</referenceTo>
        <relationshipLabel>Member Group Roles</relationshipLabel>
        <relationshipName>Member_Group_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Member Group Role</label>
    <nameField>
        <displayFormat>MGR-{00000000}</displayFormat>
        <label>Member Group Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Group Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/classes/MemberGroupRedirectExtension.cls
public with sharing class MemberGroupRedirectExtension {
  private Mbr_Group_Role__c selGrp;

  // When a role is edited, this overrides the standard role edit screen by redirecting to Member Groups/Role section.
  // This will enforce rules and limits for creating roles.
  public MemberGroupRedirectExtension(ApexPages.StandardController stdCntrl) {
    selGrp = (Mbr_Group_Role__c) stdCntrl.getRecord();
  }

  public PageReference redirect() {
    // Find the parent member group and redirect
    List<Mbr_Group_Role__c> mgrs = [
      SELECT Id, Mbr_Group__c
      FROM Mbr_Group_Role__c
      WHERE Id = :selGrp.Id
      LIMIT 1
    ];
    if (mgrs.size() == 1) {
      PageReference pg = new PageReference('/apex/MemberGroup#r');
      pg.getParameters().put('id', mgrs[0].Mbr_Group__c);
      return pg;
    } else {
      return null;
    }
  }
}