manifest/objects/Mbr_Group__c.object
<CustomObject>
    <fields>
        <fullName>Active_Date__c</fullName>
        <description>Date Group was built in Admin</description>
        <inlineHelpText>Date Group was built in Admin</inlineHelpText>
        <label>Active Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <description>Account that the Group is created</description>
        <inlineHelpText>Account that the Group is created</inlineHelpText>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Member Groups</relationshipLabel>
        <relationshipName>Member_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Enter a descriptive Member Group Name.</description>
        <inlineHelpText>Enter a descriptive Member Group Name.</inlineHelpText>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Use this as a backend field to identify the source of member group record</description>
        <inlineHelpText>Use this as a backend field to identify the source of member group record</inlineHelpText>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Data_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Group Status</description>
        <inlineHelpText>Group Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>PENDING</fullName>
                    <default>true</default>
                    <label>PENDING</label>
                </value>
                <value>
                    <fullName>TERMED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <description>This date will allow for staged terminations in the future.  A nightly batch job will check if this date has passed and set status to termed along with all blank term dates on associated PSF records.</description>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <label>Member Group</label>
    <nameField>
        <displayFormat>MG-{00000000}</displayFormat>
        <label>Member Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Mbr_Group_Role__c.object
<CustomObject>
    <fields>
        <fullName>Mbr_Group__c</fullName>
        <description>SF Record name of the Group</description>
        <inlineHelpText>SF Record name of the Group</inlineHelpText>
        <label>Member Group</label>
        <referenceTo>Mbr_Group__c</referenceTo>
        <relationshipLabel>Member Group Roles</relationshipLabel>
        <relationshipName>Member_Group_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role_Type__c</fullName>
        <description>Type of association with Group</description>
        <inlineHelpText>Type of association with Group</inlineHelpText>
        <label>Role Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Fee_Group_Role_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account that is servicing the type of role</description>
        <inlineHelpText>Account that is servicing the type of role</inlineHelpText>
        <label>Source Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Member Group Roles</relationshipLabel>
        <relationshipName>Member_Group_Roles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Member Group Role</label>
    <nameField>
        <displayFormat>MGR-{00000000}</displayFormat>
        <label>Member Group Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Group Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>Consult_Fees__c</fullName>
        <label>Consult Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account that owns this subscription. This relationship is used for volume discount calculations.</description>
        <inlineHelpText>Account that owns this subscription. This relationship is used for volume discount calculations.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product used to sell this subscription.</description>
        <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity of this subscription product purchased by the customer.</description>
        <inlineHelpText>Quantity of this subscription product purchased by the customer.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Active</fullName>
                    <default>true</default>
                    <label>Not Yet Active</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <description>Termination date for subscription</description>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/globalValueSets/Data_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>HUB</fullName>
        <default>true</default>
        <label>HUB</label>
    </customValue>
    <customValue>
        <fullName>TD</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>LVGO</fullName>
    </customValue>
    <customValue>
        <fullName>GCRM</fullName>
    </customValue>
    <masterLabel>Data Source</masterLabel>
</GlobalValueSet>

manifest/globalValueSets/Fee_Group_Role_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Benefit Sponsor</fullName>
    </customValue>
    <customValue>
        <fullName>Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Contractee</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Payer</fullName>
    </customValue>
    <customValue>
        <fullName>MSU Access</fullName>
    </customValue>
    <masterLabel>Fee Group Role Type</masterLabel>
</GlobalValueSet>

manifest/classes/subTermBchTest.cls
@isTest
private class subTermBchTest {
  @TestSetup
  static void setup() {
    Account umrAcct = TestDataFactory.createUMR();
    List<Account> acct = new List<Account>();
    Account a = new Account(Name = 'Test01', Source__c = 'HUB');
    acct.add(a);

    insert acct;

    List<Mbr_Group__c> mg = new List<Mbr_Group__c>();
    Mbr_Group__c grp = new Mbr_Group__c(
      Name__c = 'testgrp1',
      Client_Account__c = a.Id,
      Status__c = 'ACTIVE',
      Active_Date__c = Date.today()
    );
    mg.add(grp);
    Mbr_Group__c grp2 = new Mbr_Group__c(
      Name__c = 'testgrp2',
      Client_Account__c = a.Id,
      Status__c = 'ACTIVE',
      Active_Date__c = Date.today()
    );
    mg.add(grp2);
    insert mg;

    Mbr_Group_Role__c r = new Mbr_Group_Role__c(
      Role_Type__c = 'Payer',
      Source_Account__c = a.Id,
      Mbr_Group__c = mg[0].Id
    );
    insert r;

    List<Product2> pd = new List<Product2>();
    Product2 prod = new Product2(
      Name = 'GLOBALCARE',
      Family = 'GLOBAL CARE',
      ProductCode = 'GLOBALCARE',
      IsActive = true
    );
    pd.add(prod);

    Product2 prod2 = new Product2(
      Name = 'Dermatology',
      Family = 'Dermatology',
      ProductCode = 'DERM',
      IsActive = true
    );
    pd.add(prod2);

    Product2 prod3 = new Product2(
      Name = 'Tobacco Cessation',
      Family = 'Tobacco Cessation',
      ProductCode = 'TC',
      IsActive = true
    );
    pd.add(prod3);

    Product2 prod4 = new Product2(
      Name = 'General Medical',
      Family = 'General Medical',
      ProductCode = 'GM',
      IsActive = true
    );
    pd.add(prod4);

    Product2 prod5 = new Product2(
      Name = 'Behavioral Health',
      Family = 'Behavioral Health',
      ProductCode = 'BH',
      IsActive = true
    );
    pd.add(prod5);

    Product2 prod6 = new Product2(
      Name = 'Back Care',
      Family = 'Musculoskelatal',
      ProductCode = 'TDBC',
      IsActive = true
    );
    pd.add(prod6);

    Product2 prod7 = new Product2(
      Name = 'test1',
      Family = 'Musculoskelatal',
      ProductCode = 'TDBC',
      IsActive = true
    );
    pd.add(prod7);

    Product2 prod8 = new Product2(
      Name = 'Nutrition',
      Family = 'Nutrition',
      ProductCode = 'NUT',
      IsActive = true
    );
    pd.add(prod8);

    Product2 prod9 = new Product2(
      Name = 'NUTFEE',
      Family = 'Nutrition',
      ProductCode = 'NUTFEE',
      IsActive = true
    );
    pd.add(prod9);

    insert pd;

    SBQQ__Subscription__c sub = new SBQQ__Subscription__c(
      SBQQ__Account__c = a.Id,
      Status__c = 'Active',
      SBQQ__Quantity__c = 500,
      Consult_Fees__c = 0.90,
      SBQQ__Product__c = prod.Id,
      Termination_Date__c = Date.newInstance(2016, 12, 9)
    );
    insert sub;
  }

  static testMethod void test() {
    SBQQ__Subscription__c sub = [
      SELECT Status__c, Termination_Date__c
      FROM SBQQ__Subscription__c
    ];
    system.assertEquals('Active', sub.Status__c);
    Test.startTest();
    subTerm_Bch testing = new subTerm_Bch();
    DataBase.executeBatch(testing);
    Test.stopTest();
    system.assertEquals(
      'Terminated',
      [SELECT Status__c FROM SBQQ__Subscription__c].Status__c
    );
  }
}