manifest/objects/Mbr_Group__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Copay_May_Be_Less__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for RTE clients where copay amount is determined by their deductible or individual file, and may be less than the listed consult fee.  This value at Group level will determine if PSF records will have this box checked or not.</description>
        <inlineHelpText>Used for RTE clients where copay amount is determined by their deductible or individual file, and may be less than the listed consult fee</inlineHelpText>
        <label>Actual Copay May Be Less</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <description>Account that the Group is created</description>
        <inlineHelpText>Account that the Group is created</inlineHelpText>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Member Groups</relationshipLabel>
        <relationshipName>Member_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Use this as a backend field to identify the source of member group record</description>
        <inlineHelpText>Use this as a backend field to identify the source of member group record</inlineHelpText>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Data_Source</valueSetName>
        </valueSet>
    </fields>
    <label>Member Group</label>
    <nameField>
        <displayFormat>MG-{00000000}</displayFormat>
        <label>Member Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Plan_Specific_Fees__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Copay_May_Be_Less__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Actual Copay May Be Less</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bill_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bill To Plan-Specific Fees By Product</relationshipLabel>
        <relationshipName>Plan_Specific_Fees_By_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member_Group__c</fullName>
        <label>Member Group</label>
        <referenceTo>Mbr_Group__c</referenceTo>
        <relationshipLabel>Plan-Specific Fees By Product</relationshipLabel>
        <relationshipName>Plan_Specific_Fees_By_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Start_Date__c</fullName>
        <label>Product Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Plan-Specific Fees By Product</relationshipLabel>
        <relationshipName>Plan_Specific_Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan-Specific Fees By Product</label>
    <nameField>
        <displayFormat>PSF-{0000000}</displayFormat>
        <label>Plan Fees ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan-Specific Fees By Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account that owns this subscription. This relationship is used for volume discount calculations.</description>
        <inlineHelpText>Account that owns this subscription. This relationship is used for volume discount calculations.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product used to sell this subscription.</description>
        <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/globalValueSets/Data_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>HUB</fullName>
        <default>true</default>
        <label>HUB</label>
    </customValue>
    <customValue>
        <fullName>TD</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>LVGO</fullName>
    </customValue>
    <customValue>
        <fullName>GCRM</fullName>
    </customValue>
    <masterLabel>Data Source</masterLabel>
</GlobalValueSet>

manifest/classes/PSF_Batch.cls
/**
 * Created by jpatel on 4/18/19.
 */

global without sharing class PSF_Batch implements Database.Batchable<sObject> {
  global Database.QueryLocator start(Database.BatchableContext BC) {
    return Database.getQueryLocator(
      'select id,Client_Account__c,Actual_Copay_May_Be_Less__c from Mbr_Group__c where Source__c = \'BD\' and LastModifiedDate  = TODAY'
    );
  }
  global void execute(
    Database.BatchableContext BC,
    List<Mbr_Group__c> mbrGroups
  ) {
    Set<Id> accountIds = new Set<Id>();
    List<Plan_Specific_Fees__c> psfList = new List<Plan_Specific_Fees__c>();
    Map<Id, Integer> SubPSFMap = new Map<Id, Integer>();

    //Collect all AccountIds for the MemberGroups
    for (Mbr_Group__c mbrGroup : mbrGroups) {
      accountIds.add(mbrGroup.Client_Account__c);
    }

    //Check existing PSF records on the subscription
    for (SBQQ__Subscription__c sub : [
      SELECT id, (SELECT id FROM Plan_Specific_Fees__r), SBQQ__Account__c
      FROM SBQQ__Subscription__c
      WHERE SBQQ__Account__c = :accountIds
    ]) {
      SubPSFMap.put(sub.id, sub.Plan_Specific_Fees__r.size());
    }

    for (Mbr_Group__c mbrGroup : [
      SELECT
        id,
        (SELECT id, subscription__c FROM Plan_Specific_Fees_By_Product__r)
      FROM mbr_group__c
      WHERE client_account__c = :accountIds
    ]) {
      for (
        Plan_Specific_Fees__c psf : mbrGroup.Plan_Specific_Fees_By_Product__r
      ) {
      }
    }

    //Get all the Expert Medical Service Subscription Map
    Map<Id, Account> accounts = new Map<Id, Account>(
      [
        SELECT
          id,
          (
            SELECT id, SBQQ__product__r.family
            FROM SBQQ__Subscriptions__r
            WHERE SBQQ__product__r.family = 'Expert Medical Services'
          )
        FROM Account
        WHERE id = :accountIds
      ]
    );

    for (Mbr_Group__c mbrGroup : mbrGroups) {
      System.debug('Member Group Id ' + mbrGroup.id);
      for (
        SBQQ__Subscription__c subscription : accounts.get(
            mbrGroup.Client_Account__c
          )
          .SBQQ__Subscriptions__r
      ) {
        System.debug('Subscription  Id ' + subscription.id);
        //if(SubPSFMap.get(subscription.id) == 0) {
        Plan_Specific_Fees__c psf = new Plan_Specific_Fees__c(
          Subscription__c = subscription.id,
          Member_Group__c = mbrGroup.id,
          Actual_Copay_May_Be_Less__c = mbrGroup.Actual_Copay_May_Be_Less__c,
          Product_Start_Date__c = Date.today()
        );
        psfList.add(psf);
        //}else{
        //    System.debug('PSF record exist for the Subscription');
        //}
      }
    }
    if (psfList != null && psfList.size() > 0) {
      Database.insert(psfList, true);
    }
  }
  global void finish(Database.BatchableContext BC) {
  }
}