manifest/objects/Mbr_Group__c.object
<CustomObject>
    <fields>
        <fullName>Group_Number__c</fullName>
        <description>This is the Legacy Group ID number from Admin</description>
        <inlineHelpText>This is the Legacy Group ID number from Admin</inlineHelpText>
        <label>Group Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Enter a descriptive Member Group Name.</description>
        <inlineHelpText>Enter a descriptive Member Group Name.</inlineHelpText>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Group Status</description>
        <inlineHelpText>Group Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>PENDING</fullName>
                    <default>true</default>
                    <label>PENDING</label>
                </value>
                <value>
                    <fullName>TERMED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Member Group</label>
    <nameField>
        <displayFormat>MG-{00000000}</displayFormat>
        <label>Member Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Plan_Specific_Fees__c.object
<CustomObject>
    <fields>
        <fullName>Bill_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bill To Plan-Specific Fees By Product</relationshipLabel>
        <relationshipName>Plan_Specific_Fees_By_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consult_Fee_Mbr_Pd__c</fullName>
        <label>Consult Fee - Mbr Pd</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Consult_Fee_Plan_Pd__c</fullName>
        <label>Consult Fee - Plan Pd</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <formula>IF( Product__c = &apos;General Medical&apos;, Member_Group__r.Group_Number__c, &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Group__c</fullName>
        <label>Member Group</label>
        <referenceTo>Mbr_Group__c</referenceTo>
        <relationshipLabel>Plan-Specific Fees By Product</relationshipLabel>
        <relationshipName>Plan_Specific_Fees_By_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <formula>Subscription__r.SBQQ__ProductName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <label>Plan-Specific Fees By Product</label>
    <nameField>
        <displayFormat>PSF-{0000000}</displayFormat>
        <label>Plan Fees ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan-Specific Fees By Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/classes/Mg2_NASFCreateCasePDF_Test.cls
@isTest
private class Mg2_NASFCreateCasePDF_Test {
  @TestSetup
  static void setup() {
    Account umrAcct = TestDataFactory.createUMR();
    Account testAcct = TestDataFactory.createRandomAccount();
    List<Mbr_Group__c> mgTest = TestDataFactory.createMbrGroup(testAcct.Id);
  }

  @IsTest
  static void passToConfig_Test() {
    List<Mbr_Group__c> mgTestLis = [
      SELECT
        Id,
        Name,
        Name__c,
        Group_Number__c,
        Status__c,
        LastModifiedBy.Name,
        LastModifiedDate,
        CreatedDate,
        (
          SELECT Id, Name, Consult_Fee_Mbr_Pd__c, Consult_Fee_Plan_Pd__c
          FROM Plan_Specific_Fees_By_Product__r
          WHERE Product__c = 'General Medical'
          LIMIT 1
        )
      FROM Mbr_Group__c
      LIMIT 3
    ];
    List<String> mbIds = new List<String>();
    for (Mbr_Group__c mg : mgTestLis) {
      mbIds.add(string.valueOf(mg.Id));
    }
    Mg2_NASFCreateCasePDF test = new Mg2_NASFCreateCasePDF();
    String caseId = test.passToConfig(mbIds);
    system.assertNotEquals(null, caseId);
  }

  @IsTest
  static void AcctForm_Test() {
    List<Mbr_Group__c> mgTestLis = [
      SELECT
        Id,
        Name,
        Name__c,
        Group_Number__c,
        Status__c,
        LastModifiedBy.Name,
        LastModifiedDate,
        CreatedDate,
        (
          SELECT Id, Name, Consult_Fee_Mbr_Pd__c, Consult_Fee_Plan_Pd__c
          FROM Plan_Specific_Fees_By_Product__r
          WHERE Product__c = 'General Medical'
          LIMIT 1
        )
      FROM Mbr_Group__c
      LIMIT 3
    ];
    List<String> mbIds = new List<String>();
    for (Mbr_Group__c mg : mgTestLis) {
      mbIds.add(string.valueOf(mg.Id));
    }
    Mg2_NASFCreateCasePDF test = new Mg2_NASFCreateCasePDF();
    List<String> emails = test.AcctForm(mbIds);
    system.assertNotEquals(null, emails);
  }
}