manifest/objects/Mbr_Group__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Group Status</description>
        <inlineHelpText>Group Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>PENDING</fullName>
                    <default>true</default>
                    <label>PENDING</label>
                </value>
                <value>
                    <fullName>TERMED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <description>This date will allow for staged terminations in the future.  A nightly batch job will check if this date has passed and set status to termed along with all blank term dates on associated PSF records.</description>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <label>Member Group</label>
    <nameField>
        <displayFormat>MG-{00000000}</displayFormat>
        <label>Member Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Plan_Specific_Fees__c.object
<CustomObject>
    <fields>
        <fullName>Member_Group__c</fullName>
        <label>Member Group</label>
        <referenceTo>Mbr_Group__c</referenceTo>
        <relationshipLabel>Plan-Specific Fees By Product</relationshipLabel>
        <relationshipName>Plan_Specific_Fees_By_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_End_Date__c</fullName>
        <label>Product End Date</label>
        <type>Date</type>
    </fields>
    <label>Plan-Specific Fees By Product</label>
    <nameField>
        <displayFormat>PSF-{0000000}</displayFormat>
        <label>Plan Fees ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan-Specific Fees By Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/classes/GrpTerm_Bch.cls
global class GrpTerm_Bch implements Database.Batchable<sObject> {
  global Database.QueryLocator start(Database.BatchableContext BC) {
    string query = 'SELECT Id, Termination_Date__c, Status__c FROM Mbr_Group__c WHERE Status__c != \'TERMED\' AND Termination_Date__c != null AND Termination_Date__c < TODAY';
    return Database.getQueryLocator(query);
  }
  global void execute(Database.BatchableContext BC, List<Mbr_Group__c> scope) {
    scope[0].Status__c = 'TERMED';
    List<Plan_Specific_Fees__c> updatePSF = [
      SELECT Id, Product_End_Date__c
      FROM Plan_Specific_Fees__c
      WHERE Product_End_Date__c = NULL AND Member_Group__c = :scope[0].Id
    ];
    for (Plan_Specific_Fees__c psf : updatePSF) {
      psf.Product_End_Date__c = scope[0].Termination_Date__c;
    }
    if (updatePSF.size() > 0) {
      Database.update(updatePSF, false);
    }
    Database.update(scope, false);
  }
  global void finish(Database.BatchableContext BC) {
  }
}