manifest/objects/Mbr_Group__c.object
<CustomObject>
    <fields>
        <fullName>Active_Date__c</fullName>
        <description>Date Group was built in Admin</description>
        <inlineHelpText>Date Group was built in Admin</inlineHelpText>
        <label>Active Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <description>Account that the Group is created</description>
        <inlineHelpText>Account that the Group is created</inlineHelpText>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Member Groups</relationshipLabel>
        <relationshipName>Member_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Enter a descriptive Member Group Name.</description>
        <inlineHelpText>Enter a descriptive Member Group Name.</inlineHelpText>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Use this as a backend field to identify the source of member group record</description>
        <inlineHelpText>Use this as a backend field to identify the source of member group record</inlineHelpText>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Data_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Group Status</description>
        <inlineHelpText>Group Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>PENDING</fullName>
                    <default>true</default>
                    <label>PENDING</label>
                </value>
                <value>
                    <fullName>TERMED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Member Group</label>
    <nameField>
        <displayFormat>MG-{00000000}</displayFormat>
        <label>Member Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/globalValueSets/Data_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>HUB</fullName>
        <default>true</default>
        <label>HUB</label>
    </customValue>
    <customValue>
        <fullName>TD</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>LVGO</fullName>
    </customValue>
    <customValue>
        <fullName>GCRM</fullName>
    </customValue>
    <masterLabel>Data Source</masterLabel>
</GlobalValueSet>

manifest/classes/MemberGroupCloneController_Test.cls
@IsTest
private class MemberGroupCloneController_Test {
  @IsTest
  static void findMgTest() {
    Account umrAcct = TestDataFactory.createUMR();
    ContentVersion cv = new ContentVersion();
    cv.Title = 'My Document';
    cv.PathOnClient = 'TestDocument.pdf';
    cv.VersionData = Blob.valueOf('Test Content');
    cv.IsMajorVersion = true;
    insert cv;

    document testDoc = new Document();
    testDoc.Body = Blob.valueOf('Some Text');
    testDoc.ContentType = 'application/pdf';
    testDoc.DeveloperName = 'my_document';
    testDoc.IsPublic = true;
    testDoc.Name = 'My Document';
    testDoc.FolderId = [SELECT id FROM folder WHERE name = 'Logos'].id;
    insert testDoc;
    Account acct = new Account(Name = 'Test01', Source__c = 'HUB');
    insert acct;
    Mbr_Group__c grp = new Mbr_Group__c(
      Name__c = 'testgrp1',
      Client_Account__c = acct.Id,
      Status__c = 'ACTIVE',
      Active_Date__c = Date.today()
    );
    String grpId = MemberGroupCloneController.createMbrGroup(grp);
    system.assertEquals(grp.Id, grpId);
  }
}