manifest/objects/Mbr_Group__c.object
<CustomObject>
    <fields>
        <fullName>Client_Account__c</fullName>
        <description>Account that the Group is created</description>
        <inlineHelpText>Account that the Group is created</inlineHelpText>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Member Groups</relationshipLabel>
        <relationshipName>Member_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <description>System Generated Global UniqueId</description>
        <externalId>true</externalId>
        <inlineHelpText>System Generated Global UniqueId</inlineHelpText>
        <label>GUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WK_Template__c</fullName>
        <description>Determines appearance and language of Welcome Letters,added new option rimary360_VF</description>
        <inlineHelpText>Determines appearance and language of Welcome Letters</inlineHelpText>
        <label>WK Template</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>10C100_HF</fullName>
                </value>
                <value>
                    <fullName>10CH100</fullName>
                </value>
                <value>
                    <fullName>10CMCare_Healthfirst</fullName>
                </value>
                <value>
                    <fullName>10E100_BSC</fullName>
                </value>
                <value>
                    <fullName>10E100_CloverMCare</fullName>
                </value>
                <value>
                    <fullName>10E100_Fallon</fullName>
                </value>
                <value>
                    <fullName>10E100_FallonMCare</fullName>
                </value>
                <value>
                    <fullName>10E100_HF</fullName>
                </value>
                <value>
                    <fullName>10E100_MolinaMCare</fullName>
                </value>
                <value>
                    <fullName>10E100_Premera</fullName>
                </value>
                <value>
                    <fullName>10E100_TD_EMS</fullName>
                </value>
                <value>
                    <fullName>10E100MCare_2019</fullName>
                </value>
                <value>
                    <fullName>10EJ100_Nippon</fullName>
                </value>
                <value>
                    <fullName>10EK100_Nippon</fullName>
                </value>
                <value>
                    <fullName>10EMcare</fullName>
                </value>
                <value>
                    <fullName>10EMCare_Centene</fullName>
                </value>
                <value>
                    <fullName>10EMCare_City of New York</fullName>
                </value>
                <value>
                    <fullName>10EMCare_Healthfirst</fullName>
                </value>
                <value>
                    <fullName>10EMCAREHNE</fullName>
                </value>
                <value>
                    <fullName>10ES_Centene_Commercial</fullName>
                </value>
                <value>
                    <fullName>10ES100_Medicaid</fullName>
                </value>
                <value>
                    <fullName>10ES100_Medicaid_Affinity</fullName>
                </value>
                <value>
                    <fullName>10ES100_Medicaid_IN</fullName>
                </value>
                <value>
                    <fullName>10ES100_Medicaid_NY</fullName>
                </value>
                <value>
                    <fullName>10ES100_Medicaid_OR</fullName>
                </value>
                <value>
                    <fullName>10ES100_Medicaid_TX</fullName>
                </value>
                <value>
                    <fullName>10ES100_Medicaid_WA</fullName>
                </value>
                <value>
                    <fullName>10ES100_MedicareMedicaid_TX</fullName>
                </value>
                <value>
                    <fullName>10ES100_Molina</fullName>
                </value>
                <value>
                    <fullName>10ES100_Molina2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Member Group</label>
    <nameField>
        <displayFormat>MG-{00000000}</displayFormat>
        <label>Member Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Mbr_Group_Role__c.object
<CustomObject>
    <fields>
        <fullName>Mbr_Group__c</fullName>
        <description>SF Record name of the Group</description>
        <inlineHelpText>SF Record name of the Group</inlineHelpText>
        <label>Member Group</label>
        <referenceTo>Mbr_Group__c</referenceTo>
        <relationshipLabel>Member Group Roles</relationshipLabel>
        <relationshipName>Member_Group_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role_Type__c</fullName>
        <description>Type of association with Group</description>
        <inlineHelpText>Type of association with Group</inlineHelpText>
        <label>Role Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Fee_Group_Role_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account that is servicing the type of role</description>
        <inlineHelpText>Account that is servicing the type of role</inlineHelpText>
        <label>Source Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Member Group Roles</relationshipLabel>
        <relationshipName>Member_Group_Roles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Member Group Role</label>
    <nameField>
        <displayFormat>MGR-{00000000}</displayFormat>
        <label>Member Group Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Group Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/globalValueSets/Fee_Group_Role_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Benefit Sponsor</fullName>
    </customValue>
    <customValue>
        <fullName>Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Contractee</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Payer</fullName>
    </customValue>
    <customValue>
        <fullName>MSU Access</fullName>
    </customValue>
    <masterLabel>Fee Group Role Type</masterLabel>
</GlobalValueSet>

manifest/classes/F1BspInfo.cls
@RestResource(urlMapping='/F1BspInfo/v1/*')
global class F1BspInfo {
  @HttpGet
  global static String fetchStatus() {
    RestRequest request = RestContext.request;
    // grab the caseId from the end of the URL
    String GUID = request.requestURI.substring(
      request.requestURI.lastIndexOf('/') + 1
    );
    Map<String, List<SObject>> infoNeeded = new Map<String, List<SObject>>();
    // 28B90FAF-3315-D249-299D-7BDE3EE7AD57
    List<Account> bspAccounts = [
      SELECT
        id,
        Report_Recipient_Emails__c,
        Members__c,
        Total_US_Employees_Benefits_Enrolled__c,
        Special_Instructions_for_Implementatio__c
      FROM Account
      WHERE GUID__c = :GUID
    ];
    Set<String> tmpEmails = new Set<String>();
    if (bspAccounts.size() > 0) {
      infoNeeded.put('BSP', bspAccounts);
      if (bspAccounts[0].Report_Recipient_Emails__c != null) {
        List<String> reportingEmails = bspAccounts[0]
          .Report_Recipient_Emails__c.Split(',');

        for (String tmpEmail : reportingEmails) {
          tmpEmails.add(tmpEmail.trim());
        }
      }
      if (tmpEmails.size() > 0) {
        List<Contact> reportingContacts = [
          SELECT id, FirstName, LastName, Email, Phone
          FROM Contact
          WHERE email IN :tmpEmails
        ];
        if (reportingContacts.size() > 0)
          infoNeeded.put('Reporting', reportingContacts);
      }
      List<Contact> bspContacts = [
        SELECT id, FirstName, LastName, Email, Phone
        FROM contact
        WHERE Account.GUID__C = :GUID AND Marketing_Site_User__c = TRUE
      ];
      infoNeeded.put('Marketing', bspContacts);
      List<Mbr_Group_Role__c> allGroups = [
        SELECT
          id,
          name,
          mbr_group__r.guid__c,
          mbr_group__r.WK_Template__c,
          Source_Account__r.guid__c,
          Source_Account__r.name,
          mbr_group__r.client_account__r.GUID__c,
          mbr_group__r.client_account__r.name
        FROM Mbr_Group_Role__c
        WHERE
          Role_Type__c = 'Benefit Sponsor'
          AND Source_Account__r.guid__c = :GUID
      ];
      infoNeeded.put('Groups', allGroups);
    }

    return JSON.serializePretty(infoNeeded);
  }
}