manifest/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Contracted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Internal flag used to kick off automatic asset and subscription conversion.</description>
        <inlineHelpText>Salesforce CPQ uses this field to automatically convert assets and subscriptions.</inlineHelpText>
        <label>Contracted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__PrimaryQuote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Points to primary quote on this opportunity.</description>
        <inlineHelpText>Salesforce CPQ uses this to point to the primary quote on this opportunity.</inlineHelpText>
        <label>Primary Quote</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>PrimaryOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Approvals__c</fullName>
        <description>Display text for approval message on Edit Lines and Quote.  BR below is carriage return</description>
        <formula>IF(Approval_Custom_Consult_Fees__c, &apos;Custom Consult Fees&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_Direct_Broker_Included_2499__c, TEXT(CPQ_Pricebook__c) &amp; &apos; Consults Included and Lives &gt; 9999&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_Free_Trial__c, &apos;Free Trial Period&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_GM_BH_HY_Zero_Net_Price__c, &apos;GM, BH, HY or BD Zero Net Price&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_GM_HY_Broker_Direct_U_Cap_0__c, TEXT(CPQ_Pricebook__c) &amp; &apos; &apos; &amp; &apos; GM or HY Initial Utilization Cap is Zero&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_GM_HY_Util_Cap_Changed_or_0__c, &apos; GM or HY Initial Utilization Cap is Zero or Changed from Default&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_GM_Included_w_Other_Products__c, &apos;GM Consults Included with Other Products&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_GM_Missing_w_Other_Products__c, &apos;Invalid Standalone Product&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_GM_More_than_1__c, &apos;There is More than One GM Listed in Quote Lines&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_HY_Standard__c, &apos;HY has a Standard Consult Fee&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_HY_with_Anything__c, &apos;HY with Invalid Products&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_Line_Discounted__c, &apos;Line Level Discount&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_Quote_Discounted__c, &apos;Quote Level Discount&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_First_Consult_Free__c, &apos;First Consult Free&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_BD_Standalone__c, &apos;Best Doctors Standalone or Invalid Combo&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_Software_Development_Kit__c, &apos;Marketing Product – SDK&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_BD_1000_lives__c, &apos;BD optional product &lt; 1000 lives&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_EMS_Standard_5000_lives__c, &apos;EMS Standard &lt; 5000 lives&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_BD_Consult_Type__c , &apos;BH consult type different from GM or HY&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_No_Carrier_price__c, &apos;No price for product in the Carrier pricebook&apos; &amp; BR(), &apos;&apos;) &amp;
IF( Approval_BH_with_PL__c, &apos;Behavioral Health Care Standalone or Invalid Combo&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_GLOBALCARE_3000_lives__c , &apos;Global Care optional product &lt; 3000 lives&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_GlobalCare_Included__c, &apos;Global Care Consult Type Included&apos; &amp; BR(), &apos;&apos;) &amp;
IF(Approval_GM_Standard__c, &apos;GM has a Standard Consult Fee&apos;&amp; BR(), &apos;&apos;)&amp;
IF( Approval_SPS_20k_lives__c , &apos;SPS has a 0 fee&apos; &amp; BR(), &apos;&apos;)&amp;
IF( Approval_SPS_60k_lives__c , &apos;SPS optional product &gt; 60K lives&apos; &amp; BR(), &apos;&apos;)&amp;
IF( Approval_DedicatedPhone_200K__c , &apos;Dedicated Phone 200K Lives or Less&apos; &amp; BR(), &apos;&apos;)&amp;
IF( Approval_Case_Rate__c , &apos;Case Rate changed from default&apos; &amp; BR(), &apos;&apos;)&amp;
IF( Approval_TIMAP_5000_lives__c, &apos;TIMAP &lt; 5000 lives&apos; &amp; BR(), &apos;&apos;)&amp;
IF(Approval_PRIM360_10000_lives__c, &apos;PRIMARY CARE &lt; 1000 lives&apos; &amp; BR(), &apos;&apos;)&amp;
IF(Approval_PRIM360_Fee_Type__c, &apos;PRIMARY CARE Fee Type&apos; &amp; BR(), &apos;&apos;)&amp;
IF(Approval_Milestone_Based_Pricing__c, &apos;Milestone Based Pricing&apos; &amp; BR(), &apos;&apos;)&amp;
IF(Approval_Provider_Based_Care__c, &apos;Provider Based Care with Invalid Products&apos; &amp; BR(), &apos;&apos;)&amp;
IF(Approval_LandingPage_1M_Revenue__c, &apos;Net Annual Revenue &lt; $1,000,000.00&apos; &amp; BR(), &apos;&apos;)</formula>
        <inlineHelpText>Display text for approval message on Edit Lines and Quote.  BR below is carriage return</inlineHelpText>
        <label>Approvals</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CPQ_Pricebook__c</fullName>
        <label>CPQ Pricebook</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sales_Channels__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>CPQ_Pricebooks</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>Read_Only</fullName>
        <active>true</active>
        <label>Read Only</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/globalValueSets/CPQ_Pricebooks.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Carrier</fullName>
    </customValue>
    <customValue>
        <fullName>Canada Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Canada Insurance (New)</fullName>
    </customValue>
    <customValue>
        <fullName>Canada Insurance (Exist)</fullName>
    </customValue>
    <customValue>
        <fullName>HealthPlan</fullName>
    </customValue>
    <customValue>
        <fullName>Complex Case Mgmt</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>HHS</fullName>
    </customValue>
    <customValue>
        <fullName>Cross-Sell</fullName>
        <isActive>false</isActive>
        <label>Cross-Sell</label>
    </customValue>
    <masterLabel>CPQ Pricebooks</masterLabel>
</GlobalValueSet>

manifest/classes/StartImplementationController.cls
public with Sharing class StartImplementationController {
    
    @AuraEnabled
    public static void startImplementation(String recordId){
        RecordType oppProvider = [select ID,SobjectType from RecordType where developername = 'Provider_Platform' and SObjectType = 'Opportunity'];
        RecordType oppReadOnly = [select ID,SobjectType from RecordType where developername = 'Read_Only' and SObjectType = 'Opportunity'];

        Opportunity opp = [Select Id,OwnerId, StageName,recordtypeId, CPQ_Pricebook__c,CPQ_Contracted_Date__c, SBQQ__Contracted__c,SBQQ__PrimaryQuote__c,SBQQ__PrimaryQuote__r.Approvals__c,SBQQ__PrimaryQuote__r.SBQQ__Status__c from Opportunity where Id = :recordId] ;
        User currentUser = [select profile.name, UserRoleId, UserRole.name from user where id =:userinfo.getUserId()];
        
        validate(Opp,currentUser);
        
        opp.SBQQ__Contracted__c = true;
        opp.CPQ_Contracted_Date__c = System.today();
        opp.Request_CIM__c = true;
        System.debug('Updated Opportunity Contracted checbox to TRUE');
        if(opp.recordtypeId != oppProvider.Id && opp.CPQ_Pricebook__c != 'Broker'){
            opp.recordtypeId = oppReadOnly.Id;
            System.debug('Updated Opportunity RecordType to ReadOnly');
        }
        try {
            update opp ;
        }catch(Exception e){
            throw new AuraHandledException('Opportunity update failed '+ e.getMessage());
        }
       	
    }
    
    @AuraEnabled
    public static void validate(Opportunity opp, User currentUser){
        //User must be a System Administrator or have Contracting Permission
        System.debug('OwnerId'+opp.OwnerId);
        System.debug('CurrentUserId'+ currentUser.Id);
        If(currentUser.UserRoleId != null && !currentUser.Profile.Name.contains('System Administrator') && !currentUser.Profile.Name.contains('Client Operations') && !currentUser.Profile.Name.contains('Client Manager') && !currentUser.UserRole.Name.contains('Contracts') && opp.ownerId != currentUser.Id){
            throw new AuraHandledException('Access Denied. You do not have authorization to start implementation');
        }
        //Opportunity must have PrimaryQuote
        If(opp.SBQQ__PrimaryQuote__c == null){
            throw new AuraHandledException('Missing Primary Quote');
        }
        //Opportunity Primary Quote must be in Approved Status
        If(opp.SBQQ__PrimaryQuote__r.Approvals__c != null && opp.SBQQ__PrimaryQuote__r.SBQQ__Status__c != 'Approved'){
            throw new AuraHandledException('Primary Quote is not Approved');            
        }
        //Opportunity Stage must be either in Contracting or Closed Won
        If(opp.StageName != 'Contracting' && opp.StageName != 'Closed Won'){
            throw new AuraHandledException('You cannot begin implementation until this opportunity is in Contracting stage');
        }
    }
}