manifest/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2O_Channel_Segment__c</fullName>
        <description>Which of the 5 segments (Employer, Health Plan, Client Management, INTL, HHS) is this Opportunity a part of?</description>
        <label>Channel Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Employer</fullName>
                </value>
                <value>
                    <fullName>Health Plan</fullName>
                </value>
                <value>
                    <fullName>Client Management</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Hospital &amp; Health System (HHS)</fullName>
                </value>
                <value>
                    <fullName>Partner (Broker)</fullName>
                    <isActive>false</isActive>
                    <label>Partner (Broker)</label>
                </value>
                <value>
                    <fullName>Partner (Consultant)</fullName>
                    <isActive>false</isActive>
                    <label>Partner (Consultant)</label>
                </value>
                <value>
                    <fullName>Partner (Reseller)</fullName>
                    <isActive>false</isActive>
                    <label>Partner (Reseller)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2O_Contract_Path_Sub_type__c</fullName>
        <description>Does the Contract Path have: No pricing, Contracted Pricing or New Pricing</description>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contract_Path_Sub_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2O_Contract_Path__c</fullName>
        <description>How should this Opportunity be Contracted?</description>
        <label>Contract Path</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contract_Path</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2O_Initial_of_Lives__c</fullName>
        <description># of Employees or Members, in this piece of Business</description>
        <inlineHelpText>Number of lives, either employees OR members, to be closed (formerly \Initial # of Lives\&quot;). Should be only what will be acquired if this particular piece of business is closed - not the total number at the company. SALES REPS: Be conservative!&quot;</inlineHelpText>
        <label>Number of Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>L2O_Subtype__c</fullName>
        <label>Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Sale</fullName>
                </value>
                <value>
                    <fullName>Initial Sale - Partner</fullName>
                </value>
                <value>
                    <fullName>Hunting License</fullName>
                </value>
                <value>
                    <fullName>Pilot</fullName>
                </value>
                <value>
                    <fullName>Change Order</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Pilot to Paid Conversion</fullName>
                </value>
                <value>
                    <fullName>Attrition / Expiry</fullName>
                </value>
                <value>
                    <fullName>Pilot Extension</fullName>
                </value>
                <value>
                    <fullName>Contract Path Change</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                    <isActive>false</isActive>
                    <label>Expansion</label>
                </value>
                <value>
                    <fullName>Expansion / Add-On</fullName>
                    <isActive>false</isActive>
                    <label>Expansion / Add-On</label>
                </value>
                <value>
                    <fullName>Initial Sale - Direct</fullName>
                    <isActive>false</isActive>
                    <label>Initial Sale - Direct</label>
                </value>
                <value>
                    <fullName>New Population</fullName>
                    <isActive>false</isActive>
                    <label>New Population</label>
                </value>
                <value>
                    <fullName>Recontracting</fullName>
                    <isActive>false</isActive>
                    <label>Recontracting</label>
                </value>
                <value>
                    <fullName>Renewal + Expansion</fullName>
                    <isActive>false</isActive>
                    <label>Renewal + Expansion</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

manifest/globalValueSets/Contract_Path.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>US Health Plan</fullName>
    </customValue>
    <customValue>
        <fullName>Complex Case Mgmt</fullName>
    </customValue>
    <customValue>
        <fullName>TPA/Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital &amp; Health Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Intl Insurer</fullName>
    </customValue>
    <customValue>
        <fullName>Cross-Sell</fullName>
        <isActive>false</isActive>
        <label>Cross-Sell</label>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
        <isActive>false</isActive>
        <label>Broker</label>
    </customValue>
    <customValue>
        <fullName>Carrier</fullName>
        <isActive>false</isActive>
        <label>Carrier</label>
    </customValue>
    <customValue>
        <fullName>Canada Direct</fullName>
        <isActive>false</isActive>
        <label>Canada Direct</label>
    </customValue>
    <customValue>
        <fullName>Canada Insurance (New)</fullName>
        <isActive>false</isActive>
        <label>Canada Insurance (New)</label>
    </customValue>
    <customValue>
        <fullName>Canada Insurance (Exist)</fullName>
        <isActive>false</isActive>
        <label>Canada Insurance (Exist)</label>
    </customValue>
    <description>Values as per TDUAT</description>
    <masterLabel>Contract Path</masterLabel>
</GlobalValueSet>

globalValueSets/Contract_Path_Sub_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>Contracted Pricing</fullName>
    </customValue>
    <customValue>
        <fullName>New Pricing</fullName>
    </customValue>
    <masterLabel>Contract Path Sub Types</masterLabel>
</GlobalValueSet>

manifest/classes/TestDataFactoryForPG_Test.cls
/*************************************************************************     
* @description This class is used for test Data
* @param NA
* @Author InfoSys Developer
**************************************************************************/  
@isTest
public class TestDataFactoryForPG_Test {
/*************************************************************************     
* @description This metod is used for the Account object record
* @param name : Name of the Account
  @return accObj : Account object record id
* @Author InfoSys Developer
**************************************************************************/      
    public static Account createAccount(String name){
        Account accObj = new Account();
        accObj.Name = name;
        accObj.CurrencyIsoCode = 'USD';
        accObj.BillingStreet = 'test road test state';
        accObj.BillingStreet = '1 Infinite Test';
        accObj.BillingCity = 'Cupertino';
        accObj.BillingState = 'Alabama';
        accObj.BillingPostalCode = '90210';
        accObj.BillingCountry = 'United States';
        accObj.Phone = '1-800-838-8282';
        insert accObj;
        return accObj;
    }
/*************************************************************************     
* @description This metod is used for the Opportunity object record
* @param accId : Account ID
  @return oppObj : Opportunity record ID
* @Author InfoSys Developer
**************************************************************************/      
    public static Opportunity createOpportunity(Id accId){
        Opportunity oppObj = new Opportunity();
        oppObj.Name = 'Test Factory Opp';
        oppObj.AccountId = accId;
        oppObj.Type = 'New Business';
        oppObj.CurrencyIsoCode = 'USD';
        oppObj.StageName = 'Prospect';
        oppObj.Probability = 10;
        oppObj.CloseDate = Date.Today();
        oppObj.LeadSource='Marketing';
        oppObj.L2O_Subtype__c = 'Initial Sale'; 
        oppObj.L2O_Contract_Path__c = 'Direct';
        oppObj.L2O_Contract_Path_Sub_type__c = 'None';
        oppObj.L2O_Channel_Segment__c ='Employer';
        oppObj.L2O_Initial_of_Lives__c=2300;
        oppObj.Pricebook2Id = Test.getStandardPricebookId();
        return oppObj;
    }  
    
}