manifest/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this Opportunity Product.</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>OpportunityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

manifest/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Net_ARR__c</fullName>
        <label>Net ARR</label>
        <summarizedField>SBQQ__QuoteLine__c.Net_ARR__c</summarizedField>
        <summaryForeignKey>SBQQ__QuoteLine__c.SBQQ__Quote__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>SBQQ__NetAmount__c</fullName>
        <description>Total Net Amount of each non-optional line item in this quote.</description>
        <inlineHelpText>Total Net Amount of each non-optional line item in this quote.</inlineHelpText>
        <label>Net Amount</label>
        <summarizedField>SBQQ__QuoteLine__c.SBQQ__NetTotal__c</summarizedField>
        <summaryFilterItems>
            <field>SBQQ__QuoteLine__c.SBQQ__Optional__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>SBQQ__QuoteLine__c.SBQQ__Quote__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>Consult_Fees__c</fullName>
        <label>Consult Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Consult_Type__c</fullName>
        <label>Consult Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Consult_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Initial_Utilization_Cap_Calculated__c</fullName>
        <description>This is the calculated field that takes into account the override.</description>
        <formula>IF(NOT(ISBLANK(Initial_Utilization_Cap_Override__c)), Initial_Utilization_Cap_Override__c, Initial_Utilization_Cap__c)</formula>
        <inlineHelpText>This is the calculated field that takes into account the override.</inlineHelpText>
        <label>Initial Utilization Cap</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Membership_Fee__c</fullName>
        <description>This is the PEPM/PMPM that includes any discounts.  It is the Net Unit Price (which is annual) divided by 12.  It is also used to populate the Subscription Membership Fee field (formula).

    SBQQ__NetPrice__c/IF(SBQQ__SubscriptionTerm__c &lt;&gt; Null, SBQQ__SubscriptionTerm__c, Quote_Subscription_Term__c)</description>
        <formula>IF( NOT(ISNULL(Subscription_Fee__c)), Subscription_Fee__c ,If(Additional_Disc__c = 0,SBQQ__ListPrice__c - SBQQ__AdditionalDiscountAmount__c, SBQQ__ListPrice__c - Additional_Disc__c) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the PEPM/PMPM that includes any discounts.</inlineHelpText>
        <label>Membership Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monthly_Price__c</fullName>
        <description>This is custom calculation field.</description>
        <formula>IF(TEXT(SBQQ__SubscriptionPricing__c) == &apos;Fixed Price&apos;,
IF(OR(Product_Code_No_formula__c = &apos;PL&apos;,Product_Code_No_formula__c = &apos;EFMAINT&apos;,AND(CPQ_Pricebook_No_formula__c = &apos;HHS&apos;, Product_Code_No_formula__c = &apos;BH&apos;)),
SBQQ__EffectiveQuantity__c*(SBQQ__NetPrice__c/12),
IF(Product_Family_No_formula__c = &apos;Livongo&apos;,
0,
SBQQ__EffectiveQuantity__c * (IF(NOT(ISBLANK(Additional_Disc__c)),SBQQ__ListPrice__c - Additional_Disc__c,SBQQ__ListPrice__c))
)
),0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Monthly Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_ARR__c</fullName>
        <label>Net ARR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Participant_Quantity__c</fullName>
        <label>Participant Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity being quoted.</description>
        <inlineHelpText>Quantity being quoted.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__RequiredBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links this line to another line in the same quote whose product requires this line&apos;s product.</description>
        <inlineHelpText>Indicates which other product on this quote requires it.</inlineHelpText>
        <label>Required By</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/globalValueSets/Consult_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Included</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 1 - Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 1 - Included</fullName>
    </customValue>
    <customValue>
        <fullName>MFN - Standard</fullName>
    </customValue>
    <customValue>
        <fullName>MFN - Included</fullName>
    </customValue>
    <customValue>
        <fullName>Mercer WTW - Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Mercer/WTW - Included</fullName>
    </customValue>
    <customValue>
        <fullName>Custom</fullName>
    </customValue>
    <masterLabel>Consult_Types</masterLabel>
</GlobalValueSet>

manifest/classes/relateListLwcController.cls
public with sharing class relateListLwcController {
    @AuraEnabled
    public static List<SBQQ__QuoteLine__c> getQteLine(Id recordId) {
        List<SBQQ__QuoteLine__c> qteLineList  = [SELECT Id, SBQQ__Product__r.Name, Membership_Fee__c, SBQQ__Quantity__c, Participant_Quantity__c,
                                                 Initial_Utilization_Cap_Calculated__c, Consult_Fees__c, Monthly_Price__c, 
                                                 SBQQ__RequiredBy__c, SBQQ__RequiredBy__r.Name, SBQQ__Product__r.ProductCode
                                                 FROM SBQQ__QuoteLine__c WHERE SBQQ__Quote__c =:recordId];
        return qteLineList;    
    }
    
    
    @AuraEnabled
    public static List<OpportunityLineItem> getOppProd(Id recordId) {
        List<OpportunityLineItem > oppLineList  = [SELECT Id, Product__c, Consult_Type__c, Quantity, Membership_Fee__c, SBQQ__QuoteLine__r.Participant_Quantity__c,
                                                   Monthly_Price__c, Initial_Utlization_Cap__c, TotalPrice ,Consult_Fees__c, Net_ARR__c 
                                                   FROM OpportunityLineItem WHERE OpportunityId =:recordId];
        return oppLineList;    
    }
    
    @AuraEnabled
    public static List<SBQQ__Quote__c> getOppQte(Id recordId) {
        List<SBQQ__Quote__c> oppQteList  = [SELECT Id, Name, SBQQ__NetAmount__c, SBQQ__Status__c, SBQQ__Primary__c,
                                                   CreatedById, CreatedBy.Name
                                                   FROM SBQQ__Quote__c WHERE SBQQ__Opportunity2__c =:recordId];
        return oppQteList;    
    }
    
    
}