manifest/objects/Order.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>SBQQ__SortOrder__c</fullName>
        <description>Determines a default sort order of products in the Product Lookup page, and therefore the order in which they are added to the quote.</description>
        <inlineHelpText>Determines a default sort order of products in the Product Lookup page, and therefore the order in which they are added to the quote.</inlineHelpText>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/classes/QuoteLineRelatedListController.cls
public with sharing class QuoteLineRelatedListController {
  // Wrapper class to use on the VF page.
  public class Row {
    public SBQQ__QuoteLine__c record { get; set; }
    public Integer indexInList { get; set; }

    public Row(SBQQ__QuoteLine__c qli, Integer index) {
      record = qli;
      indexInList = index;
    }
  }

  public List<Row> qLineItemRows { get; set; }
  public SBQQ__Quote__c currentQuote { get; set; }

  // Property for Sorting
  public String orderBy { get; set; }
  public String sortOrder { get; set; }
  public String previousOrderBy { get; set; }

  // Property for Paging
  public Integer currentPage { get; set; }
  public Integer itemsPerPage { get; set; }
  public Integer totalPages { get; set; }
  public Integer totalRecordsFound { get; set; }

  public QuoteLineRelatedListController(
    ApexPages.standardController controller
  ) {
    try {
      // Set default values
      //orderBy = 'Name';
      orderBy = 'SBQQ__Product__r.SBQQ__SortOrder__c';
      previousOrderBy = 'Name';
      sortOrder = 'ASC';
      itemsPerPage = 5;
      currentPage = 1;
      totalRecordsFound = 0;
      totalPages = 0;

      // Get current Quote
      currentQuote = [
        SELECT Id
        FROM SBQQ__Quote__c
        WHERE Id = :controller.getId()
      ];

      // Get the related Quote Line Items
      populateRows();
    } catch (Exception e) {
      ApexPages.addMessage(
        new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage())
      );
    }
  }

  // Method to do the query and populate current page rows
  public void populateRows() {
    try {
      qLineItemRows = new List<Row>();

      // Get SBQQ__QuoteLine__c fields to be queried from Field Set
      Id quoteId = currentQuote.Id; // Filter Parent Id.
      String query = 'SELECT Id, SBQQ__Product__r.Name, SBQQ__Product__r.SBQQ__SortOrder__c ';
      for (
        Schema.FieldSetMember f : Schema.SObjectType.SBQQ__QuoteLine__c.fieldSets.getMap()
          .get('QuoteLine_Fields_for_RelatedList')
          .getFields()
      ) {
        query += ',' + f.getFieldPath();
      }
      query +=
        ' FROM SBQQ__QuoteLine__c WHERE SBQQ__Quote__c =: quoteId ORDER BY ' +
        orderBy +
        ' ' +
        sortOrder;

      if (sortOrder == 'ASC') {
        query += ' NULLS FIRST';
      } else {
        query += ' NULLS LAST';
      }

      // Query all child quote line records from the current quote
      List<SBQQ__QuoteLine__c> allRecords = new List<SBQQ__QuoteLine__c>();
      for (SBQQ__QuoteLine__c acc : Database.query(query)) {
        allRecords.add(acc);
      }
      totalRecordsFound = allRecords.size();

      // Populate the current page to be shown to the user (according to the current pagination selection)
      if (allRecords.size() > 0) {
        totalPages =
          Decimal.valueOf(allRecords.size() / itemsPerPage).intValue() +
          (Math.mod(allRecords.size(), itemsPerPage) == 0 ? 0 : 1);

        if (currentPage > totalPages) {
          currentPage = totalPages;
        } else if (currentPage <= 0) {
          currentPage = 1;
        }

        Integer startIndex = (currentPage - 1) * itemsPerPage;
        Integer endIndex = allRecords.size() > (startIndex + itemsPerPage)
          ? (startIndex + itemsPerPage)
          : allRecords.size();

        Integer indexInPage = 0;
        for (Integer i = startIndex; i < endIndex; i++) {
          Row r = new Row(allRecords[i], indexInPage);
          qLineItemRows.add(r);
          indexInPage++;
        }
      } else {
        currentPage = 1;
        totalPages = 1;
      }

      allRecords = null;
    } catch (Exception e) {
      ApexPages.addMessage(
        new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage())
      );
    }
  }

  // Method used to control the column sorting and re-generate the page after it
  public void doSortRows() {
    try {
      if (previousOrderBy.equals(orderBy)) {
        if (sortOrder.equals('ASC')) {
          sortOrder = 'DESC';
        } else {
          sortOrder = 'ASC';
        }
      } else {
        sortOrder = 'ASC';
        previousOrderBy = orderBy;
      }

      populateRows();
    } catch (Exception e) {
      ApexPages.addMessage(
        new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage())
      );
    }
  }

  // <!--  Pagination Section
  public void nextPage() {
    if (currentPage + 1 <= totalPages) {
      currentPage++;
      populateRows();
    }
  }

  public void prevPage() {
    if (currentPage - 1 >= 1) {
      currentPage--;
      populateRows();
    }
  }

  public void goToFirst() {
    currentPage = 1;
    populateRows();
  }

  public void goToLast() {
    currentPage = totalPages;
    populateRows();
  }
  // END Pagination controlling --!>
}