manifest/objects/Plan_Specific_Fees__c.object
<CustomObject>
    <fields>
        <fullName>Product_End_Date__c</fullName>
        <label>Product End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Plan-Specific Fees By Product</relationshipLabel>
        <relationshipName>Plan_Specific_Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan-Specific Fees By Product</label>
    <nameField>
        <displayFormat>PSF-{0000000}</displayFormat>
        <label>Plan Fees ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan-Specific Fees By Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <description>Termination date for subscription</description>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/classes/psfProductEndDateBch.cls
global class psfProductEndDateBch implements Database.Batchable<sObject> {
  private List<Id> subList;
  global psfProductEndDateBch(List<Id> subIdList) {
    subList = subIdList;
  }
  global Database.QueryLocator start(Database.BatchableContext BC) {
    return Database.getQueryLocator(
      [
        SELECT
          Id,
          Product_End_Date__c,
          Subscription__c,
          Subscription__r.Termination_Date__c
        FROM Plan_Specific_Fees__c
        WHERE Subscription__c IN :subList
      ]
    );
  }
  global void execute(
    Database.BatchableContext BC,
    List<Plan_Specific_Fees__c> scope
  ) {
    List<Plan_Specific_Fees__c> tempList = new List<Plan_Specific_Fees__c>();
    for (Plan_Specific_Fees__c psf : scope) {
      if (psf.Product_End_Date__c != psf.Subscription__r.Termination_Date__c) {
        psf.Product_End_Date__c = psf.Subscription__r.Termination_Date__c;
        tempList.add(psf);
      }
    }
    if (tempList.size() > 0) {
      update tempList;
    }
  }
  global void finish(Database.BatchableContext BC) {
  }
}