manifest/objects/Q_Item__c.object
<CustomObject>
    <fields>
        <fullName>Dst__c</fullName>
        <label>Destination</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ItemKey__c</fullName>
        <externalId>true</externalId>
        <label>Item Key</label>
        <length>36</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Livongo_Account_Id__c</fullName>
        <label>Livongo Account Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parser_Name__c</fullName>
        <label>Parser Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parser_Version__c</fullName>
        <label>Parser Version</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payload__c</fullName>
        <label>Payload</label>
        <length>65536</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <length>65536</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Processed with error</fullName>
                </value>
                <value>
                    <fullName>Processed without error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Teladoc_Account_Id__c</fullName>
        <label>Teladoc Account Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Outgoing</fullName>
                </value>
                <value>
                    <fullName>Incoming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>src__c</fullName>
        <label>Source</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>Q Item</label>
    <nameField>
        <label>Q Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Q Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/classes/MB_Process_Batch.cls
// CORE CLASS
global class MB_Process_Batch implements Database.Batchable<sObject>, Database.AllowsCallouts {
  public List<Q_Item__c> nextQItem = new List<Q_Item__c>();
  global MB_Process_Batch(List<Q_Item__c> QItemGet) {
    nextQItem = QItemGet;
  }
  global List<Q_Item__c> start(Database.BatchableContext BC) {
    return nextQItem;
  }
  global void execute(Database.BatchableContext BC, List<Q_Item__c> scope) {
    Map<String, Object> results = MB_QXfr_Process.processQ(scope[0]);
    if (
      JSON.serialize(results.get('dml_errors')).length() > 2 ||
      JSON.serialize(results.get('parsing_errors')).length() > 2
    ) {
      scope[0].Status__c = 'Processed with error';
      scope[0].Result__c = JSON.serializePretty(results);
    } else {
      scope[0].Status__c = 'Processed without error';
      scope[0].Result__c = JSON.serializePretty(results);
    }
    scope[0].Processed__c = true;
    update scope[0];
  }

  global void finish(Database.BatchableContext BC) {
    AsyncApexJob a = [
      SELECT Id, Status, NumberOfErrors
      FROM AsyncApexJob
      WHERE Id = :BC.getJobId()
    ];
    if (a.NumberOfErrors == 0) {
      List<Q_Item__c> nextQItemList = [
        SELECT
          Payload__c,
          Itemkey__c,
          Result__c,
          Type__c,
          Processed__c,
          Src__c,
          Dst__c,
          Parser_Name__c,
          Parser_Version__c,
          Livongo_Account_Id__c,
          Teladoc_Account_Id__c
        FROM Q_Item__c
        WHERE Processed__c = FALSE AND Type__c = 'Incoming'
        ORDER BY CreatedDate ASC
        LIMIT 1
      ];
      if (nextQItemList.size() > 0) {
        Database.executeBatch(new MB_Process_Batch(nextQItemList), 1);
      }
    }
  }
}