manifest/objects/SBQQ__ProductOption__c.object
<CustomObject>
    <customHelpPage>SBQQ__ProductOptionHelp</customHelpPage>
    <description>Option for a configurable product.</description>
    <fields>
        <fullName>Consult_Type__c</fullName>
        <label>Consult Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Consult_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Bundled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that related product is bundled with the main product. Bundled options have fixed quantity and zero price.</description>
        <inlineHelpText>Select the checkbox to indicate that the related product is bundled with the main product. Bundled options have fixed quantity and zero price as price is included in the main product. Leave this unchecked if the price should be added to the option.</inlineHelpText>
        <label>Bundled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__ConfiguredSKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product SKU of the bundle that is being configured with this option. If you create the option from the product detail page, this should already be populated.</description>
        <inlineHelpText>Product SKU of the bundle that is being configured with this option. If you create the option from the product detail page, this should already be populated.</inlineHelpText>
        <label>Configured SKU</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>Options</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Number__c</fullName>
        <description>Sequential number that determines this option&apos;s sort order.</description>
        <inlineHelpText>Set the display order of this option within the feature it&apos;s assigned to.</inlineHelpText>
        <label>Number</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__OptionalSKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product SKU added if this option is selected.</description>
        <inlineHelpText>Enter or lookup the product SKU that should be added when this product is selected.</inlineHelpText>
        <label>Optional SKU</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Optional For</relationshipLabel>
        <relationshipName>OptionalFor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity of the related product that should be added to the quote.</description>
        <inlineHelpText>Quantity of the related product that should be added to the quote.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Type__c</fullName>
        <description>Type of this option.</description>
        <inlineHelpText>Use &quot;Component&quot; if this option, including quantity, is dependent on parent. Use&quot; Accessory&quot; if this option is dependent on parent but quantity is independent. Use &quot;Related Product&quot; for related but fully independent products.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Component</fullName>
                    <default>true</default>
                    <label>Component</label>
                </value>
                <value>
                    <fullName>Accessory</fullName>
                </value>
                <value>
                    <fullName>Related Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Option</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Type__c</fullName>
        <description>Indicates the type of quote.</description>
        <inlineHelpText>Indicates the type of quote.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote</fullName>
                    <default>true</default>
                    <label>Quote</label>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Change Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>Consult_Type__c</fullName>
        <label>Consult Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Consult_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__BundledQuantity__c</fullName>
        <description>For items with calculated quantities this field hold the original (user entered) quantity.</description>
        <inlineHelpText>For items with calculated quantities this field holds the original quantity entered by the user.</inlineHelpText>
        <label>Original Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Bundled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates the product on this line item is bundled (included) by another product in this quote. Bundled lines items are zero price and do not allow price or quantity to be edited.</description>
        <inlineHelpText>Indicates the product on this line item is bundled (included) by another product in this quote. Bundled lines items have a zero price and do not allow price or quantity to be edited.</inlineHelpText>
        <label>Bundled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__EffectiveQuantity__c</fullName>
        <description>Effective quantity used in computing totals. Same as quantity unless the product is block priced, covered by &quot;Slab&quot; discount schedule, or an existing subscription.</description>
        <formula>IF(OR(ISPICKVAL(SBQQ__DiscountScheduleType__c, &apos;Slab&apos;),ISPICKVAL(SBQQ__PricingMethod__c, &apos;Block&apos;)),IF(OR(AND(!SBQQ__Existing__c, !SBQQ__CarryoverLine__c, SBQQ__Quantity__c == 0),AND(OR(SBQQ__Existing__c, SBQQ__CarryoverLine__c),OR(SBQQ__Quantity__c == SBQQ__PriorQuantity__c - SBQQ__UpgradedQuantity__c,AND(!SBQQ__AllowAssetRefund__c, ISPICKVAL(SBQQ__SubscriptionPricing__c, &apos;&apos;), SBQQ__Quantity__c &lt; SBQQ__PriorQuantity__c - SBQQ__UpgradedQuantity__c)))),0,1),IF(AND(!SBQQ__Existing__c, !SBQQ__CarryoverLine__c),SBQQ__Quantity__c,IF(SBQQ__Quantity__c &gt;= SBQQ__PriorQuantity__c - SBQQ__UpgradedQuantity__c,IF(ISPICKVAL(SBQQ__SubscriptionPricing__c, &apos;Percent Of Total&apos;),SBQQ__Quantity__c,SBQQ__Quantity__c - SBQQ__PriorQuantity__c + SBQQ__UpgradedQuantity__c),IF(AND(!SBQQ__AllowAssetRefund__c, ISPICKVAL(SBQQ__SubscriptionPricing__c, &apos;&apos;)),0,SBQQ__Quantity__c - SBQQ__PriorQuantity__c + SBQQ__UpgradedQuantity__c))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Effective quantity used in computing totals. Same as quantity unless the product is block priced, covered by &quot;Slab&quot; discount schedule, or an existing subscription.</inlineHelpText>
        <label>Effective Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__NonDiscountable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Marks this line item as non-discountable.</description>
        <inlineHelpText>Marks this line item as non-discountable.</inlineHelpText>
        <label>Non Discountable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__NonPartnerDiscountable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Marks this line item non discountable for partners.</description>
        <inlineHelpText>Select the checkbox to make this line item non discountable for partners.</inlineHelpText>
        <label>Non Partner Discountable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Number__c</fullName>
        <description>Number indicating this line&apos;s position within its group or quote.</description>
        <inlineHelpText>Number indicating this line&apos;s position within its group or quote.</inlineHelpText>
        <label>Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__OptionLevel__c</fullName>
        <description>Indicates nest level of this option (only applies to lines that are generated from options).</description>
        <inlineHelpText>Indicates nest level of this option (only applies to lines that are generated from options).</inlineHelpText>
        <label>Option Level</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__OptionType__c</fullName>
        <description>Indicates the Option Type, which is copied from related Product Option. Determines how quantity is calculated.</description>
        <inlineHelpText>Indicates the Option Type, which is copied from related Product Option. Determines how quantity is calculated.</inlineHelpText>
        <label>Option Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Component</fullName>
                </value>
                <value>
                    <fullName>Accessory</fullName>
                </value>
                <value>
                    <fullName>Related Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__PriorQuantity__c</fullName>
        <description>Combined quantity of this product from prior purchases.</description>
        <inlineHelpText>Combined quantity of this product from prior purchases.</inlineHelpText>
        <label>Prior Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProductOption__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product option that generated this line (if any).</description>
        <inlineHelpText>Product option that generated this line (if any).</inlineHelpText>
        <label>Product Option</label>
        <referenceTo>SBQQ__ProductOption__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity being quoted.</description>
        <inlineHelpText>Quantity being quoted.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__RequiredBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links this line to another line in the same quote whose product requires this line&apos;s product.</description>
        <inlineHelpText>Indicates which other product on this quote requires it.</inlineHelpText>
        <label>Required By</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/globalValueSets/Consult_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Included</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 1 - Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 1 - Included</fullName>
    </customValue>
    <customValue>
        <fullName>MFN - Standard</fullName>
    </customValue>
    <customValue>
        <fullName>MFN - Included</fullName>
    </customValue>
    <customValue>
        <fullName>Mercer WTW - Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Mercer/WTW - Included</fullName>
    </customValue>
    <customValue>
        <fullName>Custom</fullName>
    </customValue>
    <masterLabel>Consult_Types</masterLabel>
</GlobalValueSet>

manifest/classes/QuoteLineTriggerHelper.cls
public class QuoteLineTriggerHelper {
  public static boolean runAddMissingFeeProductsToAmendments = true;

  public static void addMissingFeeProductsToAmendments(
    Map<id, SBQQ__QuoteLine__c> quoteLinesMap
  ) {
    if (runAddMissingFeeProductsToAmendments) {
      runAddMissingFeeProductsToAmendments = false;
      // get quote lines list from quote line ids.
      List<SBQQ__QuoteLine__c> quoteLines = [
        SELECT
          id,
          SBQQ__RequiredBy__c,
          SBQQ__Quote__c,
          SBQQ__Number__c,
          SBQQ__Product__c,
          SBQQ__Quantity__c,
          SBQQ__EffectiveQuantity__c,
          Consult_Type__c
        FROM SBQQ__QuoteLine__c
        WHERE id IN :quoteLinesMap.keySet()
      ];

      // get quote/product ids from quote lines.
      Map<id, id> quoteIdsMap = new Map<id, id>();
      Map<id, id> productIdsMap = new Map<id, id>();
      Map<id, id> excludeQuoteLinesMap = new Map<id, id>();
      for (SBQQ__QuoteLine__c ql : quoteLines) {
        if (!quoteIdsMap.containsKey(ql.SBQQ__Quote__c)) {
          quoteIdsMap.put(ql.SBQQ__Quote__c, ql.SBQQ__Quote__c);
        }
        if (!productIdsMap.containsKey(ql.SBQQ__Product__c)) {
          productIdsMap.put(ql.SBQQ__Product__c, ql.SBQQ__Product__c);
        }
        if (
          ql.SBQQ__RequiredBy__c != null &&
          !excludeQuoteLinesMap.containsKey(ql.SBQQ__RequiredBy__c)
        ) {
          excludeQuoteLinesMap.put(
            ql.SBQQ__RequiredBy__c,
            ql.SBQQ__RequiredBy__c
          );
        }
      }
      System.debug(
        'QuoteTriggerHelper.addMissingFeeProductsToAmendments(): quote ids map size: ' +
        quoteIdsMap.size()
      );
      System.debug(
        'QuoteTriggerHelper.addMissingFeeProductsToAmendments(): product ids map size: ' +
        productIdsMap.size()
      );

      // get quotes for these quote ids.
      List<SBQQ__Quote__c> quotes = [
        SELECT id, SBQQ__Type__c
        FROM SBQQ__Quote__c
        WHERE id IN :quoteIdsMap.values()
      ];
      System.debug(
        'QuoteTriggerHelper.addMissingFeeProductsToAmendments(): quotes size: ' +
        quotes.size()
      );

      // get product options from quote line products.
      List<SBQQ__ProductOption__c> productOptions = [
        SELECT
          id,
          SBQQ__OptionalSKU__c,
          SBQQ__ConfiguredSKU__c,
          SBQQ__Bundled__c
        FROM SBQQ__ProductOption__c
        WHERE SBQQ__ConfiguredSKU__c IN :productIdsMap.values()
      ];
      System.debug(
        'QuoteTriggerHelper.addMissingFeeProductsToAmendments(): product options size: ' +
        productOptions.size()
      );

      // create quote lines to insert list.
      List<SBQQ__QuoteLine__c> quoteLinesToInsert = new List<SBQQ__QuoteLine__c>();

      // create quote lines to update list.
      List<SBQQ__QuoteLine__c> quoteLinesToUpdate = new List<SBQQ__QuoteLine__c>();

      // loop through quotes.
      for (SBQQ__Quote__c q : quotes) {
        System.debug(
          'QuoteTriggerHelper.addMissingFeeProductsToAmendments(): quote: ' +
          q.id
        );
        // if this quote is an amendment,
        if (q.SBQQ__Type__c == 'Amendment') {
          // create quote number double.
          double quoteNumber = 1;

          // loop through quote lines.
          for (SBQQ__QuoteLine__c ql : quoteLines) {
            System.debug(
              'QuoteTriggerHelper.addMissingFeeProductsToAmendments(): quote line: ' +
              ql.id
            );
            // if this quote line's quote matches this quote's id and it is nto part of the exclude list,
            if (
              ql.SBQQ__Quote__c == q.id &&
              !excludeQuoteLinesMap.containsKey(ql.id)
            ) {
              // set number of quote line.
              ql.SBQQ__Number__c = quoteNumber;

              // add old quote line to quote lines to update list.
              quoteLinesToUpdate.add(ql);

              // increment quote number.
              quoteNumber++;

              // loop through product options.
              for (SBQQ__ProductOption__c po : productOptions) {
                // if this quote line's product matches this product option's configured sku,
                if (ql.SBQQ__Product__c == po.SBQQ__ConfiguredSKU__c) {
                  // add new quote line with optional sku to quote.
                  SBQQ__QuoteLine__c newQl = new SBQQ__QuoteLine__c();
                  newQl.SBQQ__Quote__c = q.id;
                  newQl.SBQQ__RequiredBy__c = ql.id;
                  newQl.SBQQ__ProductOption__c = po.id;
                  newQl.SBQQ__Product__c = po.SBQQ__OptionalSKU__c;
                  newQl.SBQQ__Quantity__c = ql.SBQQ__Quantity__c;
                  newQl.Consult_Type__c = ql.Consult_Type__c;

                  // required fields to show hierarchy properly
                  newQl.SBQQ__OptionType__c = 'Component';
                  newQl.SBQQ__Number__c = quoteNumber;
                  newQl.SBQQ__PriorQuantity__c = null;
                  newQl.SBQQ__Bundled__c = po.SBQQ__Bundled__c;
                  newQl.SBQQ__NonDiscountable__c = true;
                  newQl.SBQQ__NonPartnerDiscountable__c = true;
                  newQl.SBQQ__OptionLevel__c = 1;
                  newQl.SBQQ__BundledQuantity__c = 1;

                  // add new quote line to quote lines to insert list.
                  quoteLinesToInsert.add(newQl);

                  // increment quote number.
                  quoteNumber++;
                }
              }
            }
          }
        }
      }

      System.debug(
        'QuoteTriggerHelper.addMissingFeeProductsToAmendments(): quote lines to insert size: ' +
        quoteLinesToInsert.size()
      );
      // if we have quote lines to insert,
      if (quoteLinesToInsert.size() > 0) {
        // insert quote lines to insert.
        //insert quoteLinesToInsert;
      }

      System.debug(
        'QuoteTriggerHelper.addMissingFeeProductsToAmendments(): quote lines to update size: ' +
        quoteLinesToUpdate.size()
      );
      // if we have quote lines to update,
      if (quoteLinesToUpdate.size() > 0) {
        // update quote lines to update.
        update quoteLinesToUpdate;
      }
    }
  }
}