manifest/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Approval_Custom_Consult_Fees__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approval - Custom Consult Fees</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Include_in_Octiv_Proposal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used by Octiv to determine if a fee page should be produced/included for this Quote based upon the Proposal Template selected on the Opportunity.</description>
        <inlineHelpText>This field is used by Octiv to determine if a fee page should be produced/included for this Quote based upon the Proposal Template selected on the Opportunity.</inlineHelpText>
        <label>Include in Octiv Proposal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/classes/CreateProposalControllerTest.cls
@IsTest
private class CreateProposalControllerTest {
     @TestSetup
    static void setup(){
        Test.Starttest();
        Account parentAcctTest = TestDataFactory.createParentAccount();
        
        Opportunity opp = TestDataFactory.createOpportunity(parentAcctTest.Id);
        insert opp; 
        Test.Stoptest();
    }
    
    @IsTest
    static void errorCheckTest() {
        Opportunity opp = [SELECT Id FROM Opportunity];
        String result = CreateProposalController.errorCheck(opp.Id); 
        system.assertEquals('No Quote is selected to include in Octiv Proposal for the Opportunity, Can not create a Proposal', result);
         
        SBQQ__Quote__c quoteObj = new SBQQ__Quote__c();
        quoteObj.SBQQ__Status__c = 'pending';
        quoteObj.Include_in_Octiv_Proposal__c = true;
        quoteObj.Approval_Custom_Consult_Fees__c = true;
        quoteObj.SBQQ__Primary__c = true;
        quoteObj.SBQQ__Opportunity2__c = opp.Id;
        insert quoteObj;
        Test.Starttest();
        //SBQQ.TriggerControl.disable();
        result = CreateProposalController.errorCheck(opp.Id); 
        system.assertEquals('Quote Included in Octiv Proposal is not approved, Can not create a Proposal', result);
        quoteObj.Approval_Custom_Consult_Fees__c = false;
        update quoteObj;
        result = CreateProposalController.errorCheck(opp.Id); 
        system.assertEquals(null, result);
        //SBQQ.TriggerControl.enable();
        Test.StopTest();
        
    }

}