manifest/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Start date for subscriptions in this quote.</description>
        <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manifest/classes/QuoteUpdateOpp_Test.cls
@IsTest
Private class QuoteUpdateOpp_Test {
	@TestSetup
    static void setup(){
        Account acct = TestDataFactory.createParentAccount();
        Opportunity oppObj = TestDataFactory.createOpportunity(acct.Id);
		insert oppObj;
        
        SBQQ__Quote__c qte2 = TestDataFactory.createQuote(oppObj.Id);
        qte2.SBQQ__Account__c = acct.Id;
        insert qte2;
        
        SBQQ__Quote__c qte1 = TestDataFactory.createQuote(oppObj.Id);
		qte1.SBQQ__Account__c = acct.Id;
        qte1.SBQQ__StartDate__c = date.today();
        insert qte1;
        
        //qte1.SBQQ__StartDate__c = date.today();
        //update qte1;
 
    }
    @IsTest
    static void updateOppDate(){
        Opportunity oppObj = [SELECT CloseDate, Id FROM Opportunity];
        List<SBQQ__Quote__c> qte = [SELECT Id, SBQQ__StartDate__c FROM  SBQQ__Quote__c];
     //   system.assertEquals(date.today(), qte[0].SBQQ__StartDate__c);
        system.assertEquals(date.today(), qte[1].SBQQ__StartDate__c);
        system.assertEquals(date.today(), [SELECT CloseDate FROM Opportunity WHERE Id =: oppObj.Id].CloseDate);

        
    }
}